### ISSUE TITLE
VS code unable to open from WSL2 command line. Remote-WSL 0.44.5 extension bug

### ISSUE THREAD

**Issue by yanbin-pan** [microsoft/vscode-remote-release#3627] opened 2020-09-02 14:27 UTC
- VSCode Version: 1.48.2
- Local OS Version: Windows 2004
- Remote OS Version: Ubuntu18.04
- Remote Extension/Connection Type: WSL2

Steps to Reproduce:

1. Update to remote- wsl extension 0.44.5
2. use the command >> code .
3. Error is thrown and VSCode does not launch

To solve this problem I downgraded my Remote - WSL extension to version 0.44.4 .
This can be done from VSCode in the extension properties where a list of all available versions are displayed.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by jaimelr** [comment] 2020-09-03 03:24
I have the same issue with version 0.44.5 and WSL2. Downgrading to 0.44.4 also solved the problem.

**Comment by aeschli** [comment] 2020-09-04 10:45
@yanbin-pan @jaimelr What error do you get?

0.44.5 only has documentation changes, so I'm a bit puzzled...

**Comment by jaimelr** [comment] 2020-09-04 14:48
Hi @aeschli I updated again the version to 0.44.5 and now it's working correctly. The error I was getting was: `WSL resolver response: ::1:43329`. Perhaps this was a blinky or an error related to my machine state.

**Comment by yanbin-pan** [comment] 2020-09-06 21:34
> @yanbin-pan @jaimelr What error do you get?
> 
> 0.44.5 only has documentation changes, so I'm a bit puzzled...

@aeschli The error was related to WSL looking for VScode in the old 0.44.4 path instead of 0.44.5 the path was not updated to match the new version. But I think this has been solved as I have now updated to 0.44.5 and I can launch VS code.

**Comment by barasimumatik** [comment] 2020-09-08 07:32
I'm just posting this here in case there is something more to this error. 
The only difference with @yanbin-pan is that I use Debian 10.

I have tried to downgrade the extension and then upgrade it again, but in my case it doesn't work, and I get another error message:

`<3>init: (1160) ERROR: UtilConnectToInteropServer:300: connect failed 2`

**Comment by aeschli** [comment] 2020-09-08 12:13
@barasimumatik This sounds like a WSL issue. Maybe https://github.com/microsoft/WSL/issues/5065 ?

**Comment by barasimumatik** [comment] 2020-09-08 12:37
@aeschli Thank you! After having a look at that issue I found out that the error was related to a stale environment variable due to some bad scripting on my end 😅

**Comment by aeschli** [comment] 2020-09-09 11:20
Closing the issue as the 0.44.5 release seems fine. Not sure what exactly caused this. I would need reproducible steps.

**Closed by aeschli** 2020-09-09 11:20 UTC
Labels: wsl
