### ISSUE TITLE
Reveal in Explorer is not supported in the browser 

### ISSUE THREAD

**Issue by caiobarilli** [microsoft/vscode-remote-release#9053] opened 2023-10-02 20:25 UTC
the fix made in version 0.79.5 stopped working in the current version 0.81.7

history of this issue:
https://github.com/microsoft/vscode-remote-release/issues/8568

**Comment by palpa** [comment] 2023-10-03 20:17
Issue started on 0.81.5, rolling back to 0.81.4 Reveal in Explorer is working fine.

**Comment by aeschli** [comment] 2023-10-10 20:00
duplicate of #9037

**Closed by aeschli** 2023-10-10 20:00 UTC
