### ISSUE TITLE
Window Reload required immediately after machine fell asleep

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#7101] opened 2022-08-22 18:41 UTC
Type: <b>Bug</b>

1) Connect to a Remote-SSH box
2) Put your machine to sleep for 1 minute
3) wake it up again
4) SSH window needs reloading. 

This is a regression. It used to try to reconnect and was successful if the vscode server was still running (up to 3h).

Extension version: 0.85.2022082215
VS Code version: Code - Insiders 1.71.0-insider (235a92a3693176fbf9af16ec5b829c458a1d682f, 2022-08-22T05:33:35.823Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.8.0-1039-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--enable-proposed-api lszomoru.lszomoru-proposed-api-sample --enable-proposed-api donjayamanne.kusto --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.8.0-1039-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (4 x 2095)|
|Memory (System)|15.64GB (12.91GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30549187

```

</details>

**Comment by alexdima** [comment] 2022-08-22 19:24
From the log:
```
ERR resolveAuthority(ssh-remote) returned an error after 11601 ms CodeExpectedError
    at y._resolveAuthority (electronExtensionService.ts:387:9)
    at async y._resolveAuthorityAgain (electronExtensionService.ts:452:19)
ERR [remote-connection][Management   ][5e40a…][reconnect] A RemoteAuthorityResolverError occurred while trying to reconnect. Will give up now! Error:
ERR CodeExpectedError
    at y._resolveAuthority (electronExtensionService.ts:387:9)
    at async y._resolveAuthorityAgain (electronExtensionService.ts:452:19)
```

**Comment by alexdima** [comment] 2022-08-22 20:59
@roblourens From debugging a modified VS Code Insiders version, I observe that `resolveAuthority` returns a `NotAvailable` error (i.e. `RemoteAuthorityResolverError.NotAvailable`) which ends up being treated as a permanent error:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/5047891/186017714-d0fbec23-ff2d-4efe-9064-a1e8bb2a1fa6.png">

**Comment by roblourens** [comment] 2022-08-24 19:10
It's working for me - can someone share the Remote-SSH log? I'm not sure how the extension threw this exception with no message or stack?

**Comment by roblourens** [comment] 2022-09-29 22:03
Still happening?

**Comment by eleanorjboyd** [comment] 2022-12-09 22:13
Hello! I wanted to follow up to see if this issue was still persisting, thanks!

**Comment by roblourens** [comment] 2022-12-10 02:29
I think Kai mentioned this somewhat recently, but I think it can be considered a dupe of https://github.com/microsoft/vscode-remote-release/issues/5755

**Closed by roblourens** 2022-12-10 02:29 UTC
Labels: bug, ssh, info-needed

**Comment by roblourens** [comment] 2022-12-10 02:30
But a log from this case would still be helpful
