### ISSUE TITLE
[Remote-SSH Bug]: Unable to connect to remote host - "Unsupported platform: OpenBSD"

### ISSUE THREAD

**Issue by pitrh** [microsoft/vscode-remote-release#9200] opened 2023-11-13 09:09 UTC
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

The connection to a remote OpenBSD machine should succeed.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[10:08:48.354] Log Level: 2
[10:08:48.363] SSH Resolver called for "ssh-remote+bsdly.net", attempt 1
[10:08:48.363] "remote.SSH.useLocalServer": true
[10:08:48.363] "remote.SSH.useExecServer": false
[10:08:48.363] "remote.SSH.path": undefined
[10:08:48.363] "remote.SSH.configFile": undefined
[10:08:48.363] "remote.SSH.useFlock": true
[10:08:48.363] "remote.SSH.lockfilesInTmp": false
[10:08:48.363] "remote.SSH.localServerDownload": auto
[10:08:48.363] "remote.SSH.remoteServerListenOnSocket": false
[10:08:48.363] "remote.SSH.showLoginTerminal": false
[10:08:48.363] "remote.SSH.defaultExtensions": []
[10:08:48.363] "remote.SSH.loglevel": 2
[10:08:48.364] "remote.SSH.enableDynamicForwarding": true
[10:08:48.364] "remote.SSH.enableRemoteCommand": false
[10:08:48.364] "remote.SSH.serverPickPortsFromRange": {}
[10:08:48.364] "remote.SSH.serverInstallPath": {}
[10:08:48.370] VS Code version: 1.84.2
[10:08:48.370] Remote-SSH version: remote-ssh@0.107.0
[10:08:48.370] darwin arm64
[10:08:48.376] SSH Resolver called for host: bsdly.net
[10:08:48.376] Setting up SSH remote "bsdly.net"
[10:08:48.378] Acquiring local install lock: /var/folders/sl/7w4h_rv93kn_bhwtcqt12hn40000gn/T/vscode-remote-ssh-826e8508-install.lock
[10:08:48.380] Looking for existing server data file at /Users/peter/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-826e8508-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.0-tr/data.json
[10:08:48.380] Using commit id "1a5daa3a0231a0fbba4f14db7ec463cf99d7768e" and quality "stable" for server
[10:08:48.382] Install and start server if needed
[10:08:48.387] PATH: /opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/peter/.rd/bin:/Users/peter/.rd/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/peter/apps/john:/opt/homebrew/opt/fzf/bin:/Users/peter/.local/bin:/Users/peter/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
[10:08:48.387] Checking ssh with "ssh -V"
[10:08:48.399] > OpenSSH_9.4p1, LibreSSL 3.3.6

[10:08:48.403] askpass server listening on /var/folders/sl/7w4h_rv93kn_bhwtcqt12hn40000gn/T/vscode-ssh-askpass-58cbb05c9fb9d74243855468de2dc8a6a6957202.sock
[10:08:48.404] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/sl/7w4h_rv93kn_bhwtcqt12hn40000gn/T/vscode-ssh-askpass-a3b68fe0b79e6ed2eafa5b84e117481bc8029465.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61591","-o","ConnectTimeout=15","bsdly.net"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/peter/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-826e8508-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.0-tr/data.json"}
[10:08:48.404] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.AsEqMwBzig/Listeners","SHELL":"/bin/bash","DISPLAY":"/private/tmp/com.apple.launchd.b6iCItNd6R/org.macports:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code 2.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/sl/7w4h_rv93kn_bhwtcqt12hn40000gn/T/vscode-ssh-askpass-58cbb05c9fb9d74243855468de2dc8a6a6957202.sock"}
[10:08:48.405] Spawned 81197
[10:08:48.487] > local-server-1> Running ssh connection command: "-v -T -D 61591 -o ConnectTimeout=15 bsdly.net"
[10:08:48.488] > local-server-1> Spawned ssh, pid=81208
[10:08:48.492] stderr> OpenSSH_9.4p1, LibreSSL 3.3.6
[10:08:49.112] stderr> debug1: Server host key: ssh-ed25519 SHA256:P7SjBriHLc02piiuvsTsyMM3CxDOPkUVAQ6Elkag8zk
[10:08:49.927] stderr> Authenticated to bsdly.net ([185.181.61.63]:22) using "publickey".
[10:08:50.151] stderr> Warning: No xauth data; using fake authentication data for X11 forwarding.
[10:08:50.282] stderr> X11 forwarding request failed on channel 3
[10:08:50.400] > ready: b7fbbc161759
[10:08:50.533] > OpenBSD 7.4 GENERIC.MP#1382
[10:08:50.534] Platform: linux
[10:08:50.643] > /usr/local/bin/bash
[10:08:50.643] Shell: bash
[10:08:50.643] Creating bash subshell inside "bash"
[10:08:50.760] > bash version:  5.2.15(1)-release
[10:08:50.780] > bash version:  5.2.15(1)-release
[10:08:50.862] > bash version:  5.2.15(1)-release
> b7fbbc161759: running
[10:08:50.895] > Unsupported platform: OpenBSD
> b7fbbc161759: start
> exitCode==35==
> listeningOn====
> osReleaseId==OpenBSD==
[10:08:50.895] > arch====
> vscodeArch====
> bitness====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> b7fbbc161759: end
[10:08:50.895] Received install output: 
exitCode==35==
listeningOn====
osReleaseId==OpenBSD==arch====
vscodeArch====
bitness====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[10:08:50.896] Failed to parse remote port from server output
[10:08:50.896] Terminating local server
[10:08:50.900] Resolver error: Error: 
	at g.Create (/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:642290)
	at t.handleInstallOutput (/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:639656)
	at e (/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:699953)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:721822
	at async t.withShowDetailsEvent (/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:725481)
	at async /Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:696658
	at async C (/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:694709)
	at async t.resolveWithLocalServer (/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:696198)
	at async I (/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:719045)
	at async t.resolve (/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:722852)
	at async /Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:906656
[10:08:50.901] Local server exit: 15
[10:08:50.906] ------




[10:08:51.039] Opening exec server for ssh-remote+bsdly.net
[10:08:51.051] Initizing new exec server for ssh-remote+bsdly.net
[10:08:51.060] Acquiring local install lock: /var/folders/sl/7w4h_rv93kn_bhwtcqt12hn40000gn/T/vscode-remote-ssh-826e8508-install.lock
[10:08:51.061] Looking for existing server data file at /Users/peter/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-826e8508-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.0-es/data.json
[10:08:51.062] Using commit id "1a5daa3a0231a0fbba4f14db7ec463cf99d7768e" and quality "stable" for server
[10:08:51.064] Install and start server if needed
[10:08:51.075] askpass server listening on /var/folders/sl/7w4h_rv93kn_bhwtcqt12hn40000gn/T/vscode-ssh-askpass-42ce218376a159d86ce93599cffc77c2a90da211.sock
[10:08:51.076] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/sl/7w4h_rv93kn_bhwtcqt12hn40000gn/T/vscode-ssh-askpass-b02246f79dac53afde0ead50f4a487cd79d12f16.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61597","-o","ConnectTimeout=15","bsdly.net"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/peter/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-826e8508-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.0-es/data.json"}
[10:08:51.076] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.AsEqMwBzig/Listeners","SHELL":"/bin/bash","DISPLAY":"/private/tmp/com.apple.launchd.b6iCItNd6R/org.macports:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code 2.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/peter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/sl/7w4h_rv93kn_bhwtcqt12hn40000gn/T/vscode-ssh-askpass-42ce218376a159d86ce93599cffc77c2a90da211.sock"}
[10:08:51.077] Spawned 81217
[10:08:51.150] > local-server-2> Running ssh connection command: "-v -T -D 61597 -o ConnectTimeout=15 bsdly.net"
[10:08:51.152] > local-server-2> Spawned ssh, pid=81228
[10:08:51.156] stderr> OpenSSH_9.4p1, LibreSSL 3.3.6
[10:08:51.627] stderr> debug1: Server host key: ssh-ed25519 SHA256:P7SjBriHLc02piiuvsTsyMM3CxDOPkUVAQ6Elkag8zk
[10:08:52.597] stderr> Authenticated to bsdly.net ([185.181.61.63]:22) using "publickey".
[10:08:52.875] stderr> Warning: No xauth data; using fake authentication data for X11 forwarding.
[10:08:53.005] stderr> X11 forwarding request failed on channel 3
[10:08:53.124] > ready: adc6305ddcd1
[10:08:53.254] > OpenBSD 7.4 GENERIC.MP#1382
[10:08:53.255] Platform: linux
[10:08:53.374] > /usr/local/bin/bash
[10:08:53.375] Shell: bash
[10:08:53.375] Creating bash subshell inside "bash"
[10:08:53.501] > bash version:  5.2.15(1)-release
[10:08:53.543] > bash version:  5.2.15(1)-release
[10:08:53.592] > bash version:  5.2.15(1)-release
> adc6305ddcd1: running
[10:08:53.614] > Unsupported platform: OpenBSD
> adc6305ddcd1: start
> exitCode==35==
> listeningOn====
> osReleaseId==OpenBSD==
> arch====
> vscodeArch====
> bitness====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime====
> execServerToken==fc043cdedecb==
> adc6305ddcd1: end
[10:08:53.615] Received install output: 
exitCode==35==
listeningOn====
osReleaseId==OpenBSD==
arch====
vscodeArch====
bitness====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime====
execServerToken==fc043cdedecb==

[10:08:53.615] Failed to parse remote port from server output
[10:08:53.615] Terminating local server
[10:08:53.616] Exec server for ssh-remote+bsdly.net failed: Error
[10:08:53.617] Error opening exec server for ssh-remote+bsdly.net: Error
[10:08:53.619] Local server exit: 15

```

</p>
</details>

**Comment by bamurtaugh** [comment] 2023-11-29 19:51
Thanks for filing! I believe this is a dupe of https://github.com/microsoft/vscode-remote-release/issues/727, but please lmk if the request is different.

**Closed by bamurtaugh** 2023-11-29 19:51 UTC
Labels: ssh
