### ISSUE TITLE
Cannot open local folder after failing to build dev container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5811] opened 2021-11-02 10:34 UTC
@aeschli @bpasero The `"vscode.openFolder"` command appears to have stopped working when the building of a dev container failed. We offer to open the folder locally in that case, but that no longer works.

The console shows:
```
DEBUG Configuration keys changed in WORKSPACE target telemetry.enableTelemetry terminal.integrated.defaultProfile.linux
log.ts:283 
DEBUG Terminal process ready (shellProcessId: -1)
extensionService.ts:374
Error
    at jr.resolveAuthority (extensionHostManager.ts:372)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Yl._scanAndHandleExtensions (extensionService.ts:369)
    at async Yl._initialize (abstractExtensionService.ts:518)
extensionService.ts:376 Error handled: Not showing a notification for the error
log.ts:301   ERR Error received from starting extension host (kind: Remote)
log.ts:301   ERR Error
    at jr.resolveAuthority (extensionHostManager.ts:372)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Yl._scanAndHandleExtensions (extensionService.ts:369)
    at async Yl._initialize (abstractExtensionService.ts:518)
log.ts:301   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:301   ERR Error
    at jr.resolveAuthority (extensionHostManager.ts:372)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Yl._scanAndHandleExtensions (extensionService.ts:369)
    at async Yl._initialize (abstractExtensionService.ts:518)
log.ts:295  WARN Ignoring the error while validating workspace folder vscode-remote://dev-container%2B2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374/workspaces/smktst - An unknown error occurred. Please consult the log for more details.
log.ts:301   ERR Error
    at jr.resolveAuthority (extensionHostManager.ts:372)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Yl._scanAndHandleExtensions (extensionService.ts:369)
    at async Yl._initialize (abstractExtensionService.ts:518)
log.ts:301   ERR Error
    at jr.resolveAuthority (extensionHostManager.ts:372)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Yl._scanAndHandleExtensions (extensionService.ts:369)
    at async Yl._initialize (abstractExtensionService.ts:518)
abstractExtensionService.ts:1156 Extension 'ms-vscode.test-adapter-converter' uses PROPOSED API which is subject to change and removal without notice.
updateEnableProposedApi @ abstractExtensionService.ts:1156
_checkEnableProposedApi @ abstractExtensionService.ts:778
_checkEnabledAndProposedAPI @ abstractExtensionService.ts:788
_startLocalExtensionHost @ extensionService.ts:430
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
_startLocalExtensionHost @ extensionService.ts:427
_scanAndHandleExtensions @ extensionService.ts:382
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
_scanAndHandleExtensions @ extensionService.ts:365
_initialize @ abstractExtensionService.ts:518
async function (async)
_initialize @ abstractExtensionService.ts:516
(anonymous) @ extensionService.ts:107
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1004
(anonymous) @ extensionService.ts:106
Promise.then (async)
Yl @ extensionService.ts:104
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:449
(anonymous) @ workbench.ts:215
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:209
startup @ workbench.ts:141
open @ shared.desktop.main.ts:115
async function (async)
open @ shared.desktop.main.ts:106
C @ desktop.main.ts:47
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:174
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ extensionService.ts:575
(anonymous) @ fake:1
log.ts:301   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374/workspaces/smktst/.vscode/settings.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374/workspaces/smktst/.vscode/settings.json' (Error)
    at yi.doReadFileStream (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async yi.doReadFile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
log.ts:301   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374/workspaces/smktst/.vscode/tasks.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374/workspaces/smktst/.vscode/tasks.json' (Error)
    at yi.doReadFileStream (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async yi.doReadFile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
log.ts:301   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374/workspaces/smktst/.vscode/launch.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374/workspaces/smktst/.vscode/launch.json' (Error)
    at yi.doReadFileStream (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:27791)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async yi.doReadFile (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:26807)
    at async Object.factory (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:602:26722)
log.ts:301  
```

**Comment by aeschli** [comment] 2021-11-02 10:56
The log comes from not being able to resolve. I get the same when trying tring to reprodcusing with the test resolver"

- run out of sources
- add at https://github.com/microsoft/vscode/blob/3ed654b8e8d0310e0fcdd4a08ef12d873c73816a/extensions/vscode-test-resolver/src/extension.ts#L353
```
	actions.push({
		title: 'Open Folder',
		execute: async () => {
			await vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.parse('file:///home/martin/workspaces/testing/ext-web-sept-21-a'));
		}
	});
```
- run and in the OSS Dev window set `testresolver.startupError`
- open a TestResolver window
- resolving fails, error is same as you see (expect the last lines `Unable to read file`)
- Clicking on `Open Folder` works

**Comment by chrmarti** [comment] 2021-11-03 07:10
Steps with Remote-Containers:
- Run the command `Remote-Containers: Clone Repository in Container Volume...`
- Enter: https://github.com/chrmarti/smktst-fail-in-dockerfile
- In the eventual modal dialog, press `Open Dockerfile in Recovery Container` or run the command `Remote: Close Remote Connection`.
- Expecting a window reload, but there is an error instead.

**Comment by bpasero** [comment] 2021-11-03 07:56
Here is what happens:
* you click "Open Folder"
* this eventually reaches `[fileDialogService.pickFolderAndOpen](https://github.com/microsoft/vscode/blob/6e5661e423a91ab3afe743cf6ae633200eae781a/src/vs/workbench/services/dialogs/electron-sandbox/fileDialogService.ts#L99)`
* this wants to resolve a good default path to show as initial path for the dialog
* this is using `pathService.userHome` which is a `Promise`
* the promise is never resolving because it waits on `remoteAgentService.getEnvironment`

I would expect that a connection error would result in the `getEnvironment` call to fail with an error but that does not seem to be the case:

https://github.com/microsoft/vscode/blob/a8fb2993c72e9762d34a0d28a5d918f0551ed252/src/vs/workbench/services/path/common/pathService.ts#L90-L96

**Comment by bpasero** [comment] 2021-11-03 07:58
@chrmarti as a workaround you can set `forceLocalWindow` as option when calling `vscode.openFolder`, that would make sense in this case anyway.

**Comment by chrmarti** [comment] 2021-11-03 10:23
@bpasero I assume `forceLocalWindow` will not work when the URI is for opening a recovery container (which is a remote window).

**Comment by bpasero** [comment] 2021-11-03 10:30
Yeah it will only allow to pick local (on the local computer) folders.

**Comment by chrmarti** [comment] 2021-11-03 10:54
Adding @alexdima, this seems like a recent regression.

**Comment by alexdima** [comment] 2021-11-03 13:31
Did someone already do a blame search to identify the commit that introduced this regression?

**Comment by aeschli** [comment] 2021-11-03 13:59
The `Close Remote Connection` fails due to a veto from terminal. Exception thrown while serializing the terminal:
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalService.ts#L143

**Comment by alexdima** [comment] 2021-11-03 14:30
@aeschli Thank you for figuring that out! Is that also the root cause for `vscode.openFolder` not working? The terminal veto?

**Comment by aeschli** [comment] 2021-11-04 07:58
I just tested that fixing the terminal veto also fixes the `vscode.openFolder` scenario.

We can close this one as dup of https://github.com/microsoft/vscode/issues/136358

**Comment by aeschli** [comment] 2021-11-04 08:02
@bpasero Your steps might point to a different bug

**Comment by alexdima** [comment] 2021-11-04 08:32
@aeschli What steps should we try? I have tried with the steps @bpasero points to in https://github.com/microsoft/vscode-remote-release/issues/5811#issuecomment-958721369 , i.e. with the steps at https://github.com/microsoft/vscode-remote-release/issues/5811#issuecomment-957330567 but I cannot reproduce any hang, things appear to be in order.

**Comment by bpasero** [comment] 2021-11-04 08:36
Slight adjustment, the action needs to be:

```
await vscode.commands.executeCommand('vscode.openFolder');
```

**Comment by alexdima** [comment] 2021-11-04 08:59
Thank you for the extra info @bpasero . I can reproduce. I have added more logging on my side before calling the resolver and after it returns a value or throws an error. 

@aeschli In this case, I can see that the resolver never returns, so this is why `remoteAgentService.getEnvironment` never completes:

I would expect to see a log statement e.g. `resolveAuthority(test) returned an error`

```
[2021-11-04 09:55:48.090] [renderer1] [info] Invoking resolveAuthority(test)
[2021-11-04 09:55:48.490] [renderer1] [info] Starting extension host with pid 79162.
[2021-11-04 09:55:48.491] [renderer1] [info] [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 394 ms.
```

**Comment by aeschli** [comment] 2021-11-04 10:37
@chrmarti Just confirmed me that he is using `executeCommand('vscode.openFolder', uri)` which does not involve a dialog. I tested that a fix for https://github.com/microsoft/vscode/issues/136358 will fix his issue.

That leaves us with `vscode.commands.executeCommand('vscode.openFolder')` found by @bpasero.
Not sure if that ever worked. I created https://github.com/microsoft/vscode/issues/136425

Closing this containers issue as dup of  https://github.com/microsoft/vscode/issues/136358

**Closed by aeschli** 2021-11-04 10:37 UTC
Labels: bug, remote
