### ISSUE TITLE
Support offline installation on remote machine

### ISSUE THREAD

**Issue by idailylife** [microsoft/vscode-remote-release#3100] opened 2020-06-02 07:49 UTC
Per https://stackoverflow.com/questions/56671520/how-can-i-install-vscode-server-in-linux-offline, I think it would be better if we can install the package offline more feasibly.

**Comment by Chuxel** [comment] 2020-06-08 19:42
This appears to be a dupe of #1242.

**Closed by Chuxel** 2020-06-08 19:42 UTC
Labels: *duplicate, ssh
