### ISSUE TITLE
Installing VS Code server - Certificate signature failure

### ISSUE THREAD

**Issue by lavaude** [microsoft/vscode-remote-release#5085] opened 2021-05-21 07:07 UTC
Hi there,

- VSCode Version: 1.56.2
- Local OS Version: Windows 10 enterprise1909
- Remote OS Version: Debian buster (Docker) & Ubuntu 2004 (WSL2)
- Remote Extension/Connection Type: Docker & WSL2 (reproduced on both)
- Logs:

Debian buster (Docker):

```
...
Exit code 2
Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json

cat: /root/.vscode-server/data/Machine/settings.json: No such file or directory
Exit code 1
Start: Run in container: test -d /root/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d


Exit code 1
Installing VS Cpde Server for commit 3c4e3df9e89829dce27b7b5c24508306b151f30d
Start: Downloading VS Code ServerError: certificate signature failure
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (event.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
```

Ubuntu 2004 (WSL2)

```
...
Resolving wsl+Ubuntu-20.04, resolveAttempt: 1
Starting VS Code Server inside WSL (Ubuntu-20.04)
Extension version: 0.54.6, Windows build: 18363. Multi distro support: available. WSL path support: enabled
No shell environment set or found for current distro.
Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 -e sh -c "[ -d ~/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
Probing result: x86_64
No server install found in WSL, needs x64
Downloading server on client side to C:\Users\USR\AppData\Local\Temp\vscode-remote-wsl\3c4e3df9e89829dce27b7b5c24508306b151f30d\vscode-server-linux-x64..tar.gz.
https://update.code.visualstudio.com/commit:3c4e3df9e89829dce27b7b5c24508306b151f30d/server-linux-x64/stable
Unable to download server on client side: Error: Request downloadRequest failed with message: certificate signature failure. Will try to download on WSL side.
Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 3c4e3df9e89829dce27b7b5c24508306b151f30d stable .vscode-server 0 '}
Setting up server environment: Looking for /home/USR/.vscode-server/server-env-setup. Not found.
WSL version: 5.4.72-microsoft-standard-WSL2 Ubuntu-20.04
Installing VS Code Server for x64 (3c4e3df9e89829dce27b7b5c24508306b151f30d)
Downloading:   100%
Failed
--2021-05-18 17:04:10-- https://update.code.visualstudio.com/commit:3c4e3df9e89829dce27b7b5c24508306b151f30d/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... failed: Name or service not known.
wget: unable to resolve host address 'update.com.visualstudio.com'
```

Steps to Reproduce:

1. Remote- open in container or remote open in WSL

In our team we are all behind corporate proxy with authentication. We also have our own CA certificate for our internal services. This issue happens to a single colleague.

Any suggestions are warmly welcome :)

**Comment by chrmarti** [comment] 2021-05-21 08:50
Could you:
- Run `F1` > `Preferences: Configure Runtime Arguments`.
- Add `"log-level": "trace"` to the opened argv.json.
- Close all VS Code windows and then open a new VS Code window.
- Run `F1` > `Output: Focus on Output View`.
- Switch to the `Log (Extension Host)` channel.
- Search for the entries containing "ProxyResolver#getCaCertificates" (1 entry expected) and "ProxyResolver#useSystemCertificates" (0 or 1 entries expected) (`Cmd + F` works) and append the entries here.

Afterwards remove the `"log-level": "trace"` entry to stop filling the logs with trace output.

**Comment by lavaude** [comment] 2021-05-21 09:45
Thanks for the support @chrmarti 

ProxyResolver#getCaCertificates:
`[2021-05-21 11:27:42.346] [exthost] [debug] ProxyResolver#getCaCertificates count 77`

ProxyResolver#useSystemCertificates
Nothing showing up

However we have that for ProxyResolver#resolveProxy (my colleague as well as me, but everything is working fine on my side, so not sure this is related. I replaced the usr/pwd and proxy/port in the following logs to not expose any confidential data)

```
[2021-05-21 11:27:42.347] [exthost] [debug] ProxyResolver#resolveProxy settings https://default.exp-tas.com/vscode/ab PROXY USR:PWD@PROXY:PORT 
Error: Error for stack trace
    at resolveProxy (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
    at c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
    at new Promise (<anonymous>)
    at _PacProxyAgent.resolveP [as resolver] (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
    at _PacProxyAgent.<anonymous> (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
    at Generator.next (<anonymous>)
    at c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
    at _PacProxyAgent.callback (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
    at _PacProxyAgent.addRequest (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
    at new ClientRequest (_http_client.js:306:16)
    at request (https.js:313:10)
    at Object.patched [as request] (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
    at m._performRequest (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:1:44118)
    at new m (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:1:40681)
    at Object.value [as request] (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:1:41379)
    at c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:45:56150
    at new Promise (<anonymous>)
    at e.exports (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:45:54112)
    at e.exports (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:45:49513)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.fetch (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:45:45680)
    at async o.getFeatures (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:45:46906)
    at async c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:45:70118
    at async Promise.all (index 0)
    at async s.getFeaturesAsync (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:45:70148)
    at async t.PollingService.onTick (c:\Users\USR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender\dist\extension.js:45:68529)

```

**Comment by chrmarti** [comment] 2021-05-21 11:06
Can you download the server through the browser: https://update.code.visualstudio.com/commit:3c4e3df9e89829dce27b7b5c24508306b151f30d/server-linux-x64/stable ?

**Comment by lavaude** [comment] 2021-05-21 11:41
Yes, downloaded with success through Chrome

**Comment by chrmarti** [comment] 2021-05-21 12:19
Wild guess: Could you retry the download with Edge? That might add missing certificates to the system's root certificates (these are safely downloaded on demand). I think Chrome might have its own set of certificates (not entirely sure). Restart VS Code after that and retry.

Also: Can you install extensions through VS Code's Extensions UI?

**Comment by lavaude** [comment] 2021-05-21 12:29
Downloaded with edge, then VS code restarted: same issue.

We installed the remote WSL and remote container extension through the VS Code's extension UI

**Comment by chrmarti** [comment] 2021-05-21 12:55
What do you have in your user settings for 'HTTP Proxy Support' and 'HTTP System Certificates'?
![image](https://user-images.githubusercontent.com/9205389/119140523-88c3ae00-ba44-11eb-9f88-7a49c1b9bdb4.png)
![image](https://user-images.githubusercontent.com/9205389/119140551-9416d980-ba44-11eb-8471-dc7a96cf8524.png)

**Comment by lavaude** [comment] 2021-05-21 13:10
Same as you

**Comment by lavaude** [comment] 2021-05-26 06:02
Hi,

Let me know what you think about that workaround:

Considering that I prepare the dev docker image for our team. 
Could I just include the vscode-server somewhere during the build of the image? It would not anymore try to download it and have certificates/proxy issues...
If so, at which path and more importantly how to lock the version of vscode server required?
That could also be interesting for the extensions specified in the devcontainer.json and ensure we are all aligned...

**Comment by chrmarti** [comment] 2021-05-26 07:01
There are two location: The `vsch` folder in your local temp folder and the `vscode` Docker volume. The volume is used when possible (but, e.g., not with Docker Compose where we currently don't change the user's mount point). The exact folder layout might change in the future.

The server version must match the VS Code build. So you might need several server versions depending on what is being used.

That being said, this looks like a bug in the current implementation and I need to investigate how we can track it down further.

**Comment by lavaude** [comment] 2021-06-04 07:30
Hi @chrmarti 

I have another colleague having this issue.
The setup Windows / WSL / Docker can be a bit confusing sometime. 
Here the download fails on Windows side, right?

**Comment by lavaude** [comment] 2021-06-04 13:19
Our IT department did a live session and we get that problem:

connection: service.name=HTTP client.address=10.129.92.4 proxy.port=8080 client.interface=255:255.1 routing-domain=default
location-id=0 access_type=unknown
time: 2021-06-04 12:33:15 UTC
CONNECT tcp://vortex.data.microsoft.com:443/
DNS lookup was unrestricted
User-Agent: Mozilla/4.0 (compatible;)
user: unauthenticated
authentication status='not_attempted' authorization status='not_attempted'
url.category: Azure-Auth Bypass for specific sources@Policy
total categorization time: 0
static categorization time: 0
server.response.code: 0
client.response.code: 200
application.name: unavailable
application.operation: unavailable
application.group: unavailable
DSCP client outbound: 65
DSCP server outbound: 65

Is "vortex.data.microsoft.com" some mirror where vscode-server is?

I was trying to fully delete my version and my cache to check where exactly it is trying to reach (because it is working on my side).
I deleted 
C:\Users\lavaude\AppData\Local\Temp\vscode-remote-wsl\
In WSL
/tmp/*
~/.vscode-server
But I should be missing some tmp folder because no download happen and we can not compare

**Comment by lavaude** [comment] 2021-06-04 13:48
Oh and we could do a workaround with the remote-wsl extension by manually downloading and copying the vscode-server as follow:
Download there
https://update.code.visualstudio.com/commit:054a9295330880ed74ceaedda236253b4f39a335/server-linux-x64/stable
Then putting it there
C:\Users\lavaude\AppData\Local\Temp\vscode-remote-wsl\054a9295330880ed74ceaedda236253b4f39a335\vscode-server-stable-linux-x64.tar.gz
And starting the remote WSL extension

We understood that from the failure logs of WSL. 
But what about remote containers?
Same file to download? That we put where?

**Comment by brbecker** [comment] 2021-06-10 17:24
I am seeing the same issue as lavaude. I went through the debugging steps provided above and got essentially the same results that he did (the count for getCaCertificates differed).

I'm just using the Remote - Containers extension. I've modified the .devcontainer/Dockerfile to explicitly install our corporate CA certificates and to point node and pip at the updated list of CAs:

```
ADD .devcontainer/*.crt /usr/local/share/ca-certificates/
RUN chmod 644 /usr/local/share/ca-certificates/*.crt && \
    update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
ENV PIP_CERT=/etc/ssl/certs/ca-certificates.crt
```

If I manually attach to the container that is built, I can successfully download the server from inside the container using both curl (after telling it to follow redirects) and wget. The resulting files are identical.

```
curl https://update.code.visualstudio.com/commit:3c4e3df9e89829dce27b7b5c24508306b151f30d/server-linux-x64/stable -L -o curl-stable
wget https://update.code.visualstudio.com/commit:3c4e3df9e89829dce27b7b5c24508306b151f30d/server-linux-x64/stable

root ➜ /tmp $ cksum *stable
558020472 31491683 curl-stable
558020472 31491683 stable
```

If there's anything else you'd like me to try, please let me know.

**Comment by brbecker** [comment] 2021-06-10 17:34
I looked again and I am getting a slightly different error from lavaude when the container is being built (Error: unable to get local issuer certificate).

```
[33857 ms] Start: Run in container: test -d /vscode/vscode-server/bin/x64/054a9295330880ed74ceaedda236253b4f39a335
[33863 ms] 
[33864 ms] 
[33864 ms] Exit code 1
[33866 ms] Installing VS Code Server for commit 054a9295330880ed74ceaedda236253b4f39a335
[33866 ms] Start: Run in container: /bin/sh
[33938 ms] Start: Downloading VS Code Server
[33938 ms] 054a9295330880ed74ceaedda236253b4f39a335 x64 stable 
[34450 ms] Error: unable to get local issuer certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket._finishInit (_tls_wrap.js:932:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
```

**Comment by lavaude** [comment] 2021-06-29 11:29
Checking if any news.

@chrmarti , we can do a workaround for "remote-wsl" by manually downloading and putting the file here:
C:\Users\lavaude\AppData\Local\Temp\vscode-remote-wsl\054a9295330880ed74ceaedda236253b4f39a335\vscode-server-stable-linux-x64.tar.gz

But which file to download and where to put it for remote-containers? We tried a few ideas but without success...

**Comment by chrmarti** [comment] 2021-06-29 19:00
That's using, e.g., `<temp>\vsch\serverCache\054a9295330880ed74ceaedda236253b4f39a335\vscode-server-linux-x64.tar.gz`. Note that this can change in the future (e.g., to unify between extensions).

**Comment by joshwhieb** [comment] 2021-08-05 23:16
I'm running into a similar error as @brbecker .  I've tried adding the proxy settings to the devcontainer.json and the container environment variables as well with no luck.  I have the company certificates installed locally on the container and wget/curl of the vscode-server-stable works manually on the local machine and the container environment.

**Comment by lukebailey** [comment] 2021-08-10 10:07
We are seeing something similar and I assume related (running behind a corporate firewall):

![image](https://user-images.githubusercontent.com/3185073/128848760-28e73557-dace-4254-a87f-edff539ea513.png)

Strangely this was working fine until today, we manually include our certificate chain in the Ubuntu base image. It would be useful to understand the VS Code server download/installation process so that we can put appropriate exceptions in place if need be

**Comment by chrmarti** [comment] 2021-08-10 13:53
@lukebailey The download happens locally. Could you try updating your local root certificates?

**Comment by lukebailey** [comment] 2021-08-10 15:08
@chrmarti we have ended up putting in an SSL bypass for the domain https://update.code.visualstudio.com which resolves the issue, can you share some more details on how the VS Code Server package is downloaded (namely the command we can run locally outside of Docker) to reproduce this more easily and identify where in the certificate chain we have an issue. Thanks

**Comment by chrmarti** [comment] 2021-08-10 20:16
@lukebailey Are you using a proxy? Does this reproduce with VS Code 1.59 too?

The request made by Remote-Containers goes through the Node.js modules and gets the OS' root certificates patched in by VS Code. So there is no isolated command that would precisely replicate this. You could check with wget or curl (enable following redirects) for: https://update.code.visualstudio.com/commit:379476f0e13988d90fab105c5c19e7abc8b1dea8/server-linux-x64/stable

**Comment by lukebailey** [comment] 2021-08-11 07:52
@chrmarti we are still on 1.58.1, I didn't see anything related to this issue in the release notes for 1.59 but can look to upgrade and test. 

We are able to curl/wget/manually download from that link so is there a possibility the OS' root certificate is not getting passed through correctly to the Node.js modules - can we explicilty state this anywhere in VS Code (we already include the cert within the Docker images themselves)

**Comment by chrmarti** [comment] 2021-08-11 09:38
@lukebailey Are you seeing this with all machines or only some? I assume you are behind a network proxy using HTTPS? Which OS and version are you using?

Could you enable 'debug' logging (`F1` > `Developer: Set Log Level...`), reload the window and then check for any `ProxyResolver#getCaCertificates` entries in the `Log (Extension Host)` output channel?

**Comment by brbecker** [comment] 2021-08-12 23:19
@chrmarti I am still seeing this issue. I am currently on version 1.59.0.

When I try to open a vanilla devcontainer in an empty directory, it fails with:

```[14952 ms] Start: Run in container: /bin/sh
[15009 ms] Start: Run in container: apk info | grep -e '^libstdc++$' || (apk update && apk add libstdc++)
[15010 ms] Start: Run in container: test -d /vscode/vscode-server/bin/alpine/379476f0e13988d90fab105c5c19e7abc8b1dea8
[15032 ms] 
[15033 ms] 
[15034 ms] Exit code 1
[15035 ms] Installing VS Code Server for commit 379476f0e13988d90fab105c5c19e7abc8b1dea8
[15036 ms] Start: Downloading VS Code Server
[15036 ms] 379476f0e13988d90fab105c5c19e7abc8b1dea8 alpine stable 
[15462 ms] Error: unable to get local issuer certificate
        at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket._finishInit (_tls_wrap.js:932:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
[16797 ms] libstdc++
[16798 ms]
```
Enabling debug logging, I see only one line mentioning getCaCertificates:

```[2021-08-12 15:51:19.706] [exthost] [debug] ProxyResolver#getCaCertificates count 60
```

Attaching to the container using Docker Desktop, I can download the https://update.code.visualstudio.com/commit:379476f0e13988d90fab105c5c19e7abc8b1dea8/server-linux-x64/stable file using both curl and wget and get identical results.
```/tmp/curl # ls -la
total 97256
drwxr-xr-x 2 root root     4096 Aug 12 23:10 .
drwxrwxrwt 1 root root     4096 Aug 12 23:08 ..
-rw-r--r-- 1 root root 49786917 Aug  4 23:41 stable
-rw-r--r-- 1 root root 49786917 Aug 12 23:09 stable-curl
/tmp/curl # cksum *
3013243958 49786917 stable
3013243958 49786917 stable-curl
```

Since I am able to download the file manually, can I place it somewhere in the container or on the host so that vscode will just use it? I understand that I'll have to manually do this every time there's a VS Code update, but that's better than my current state where devcontainers just don't work at all.

**Comment by chrmarti** [comment] 2021-08-13 08:36
@brbecker Please see above: https://github.com/microsoft/vscode-remote-release/issues/5085#issuecomment-870839775

**Comment by nchandra-seg** [comment] 2021-11-10 18:39
Facing same issue. What is the solution?
[7599 ms] Start: Run in container: test -d /root/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643
[7605 ms] 
[7605 ms] 
[7605 ms] Exit code 1
[7606 ms] Installing VS Code Server for commit 6cba118ac49a1b88332f312a8f67186f7f3c1643
[7607 ms] Start: Downloading VS Code Server
[7607 ms] 6cba118ac49a1b88332f312a8f67186f7f3c1643 linux-x64 stable 
[7934 ms] Error: certificate has expired
        at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket._finishInit (_tls_wrap.js:932:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

**Comment by lukebailey** [comment] 2021-11-11 09:10
Adding an SSL bypass to the following domains on our firewall resolved the issue for now but is not an ideal solution:

update.code.visualstudio.com
vo.msecnd.net

**Comment by nchandra-seg** [comment] 2021-11-12 00:37
Hmm, curious how this solved the problem. I tried curl from that linux machine.
```
[xyz]$ curl https://update.code.visualstudio.com
Hello from VS Code! 👋[xyz]$ curl https://vo.msecnd.net
curl: (6) Could not resolve host: vo.msecnd.net
```

**Comment by ckihm** [comment] 2021-11-15 17:01
We have exactly the same problem. Also for us the download works both, manually with wget in the WSL distro (Ubuntu 20.04) and attached to the container with wget. Currently I am at a loss how to solve this problem. 

Adding SSL bypass exceptions as mentioned by @lukebailey  has not been tested yet. Even if the bypass should solve the problem, this can only remain a workaround and will certainly not be accepted as a permanent solution by our IT security officer.

**Comment by PvanHengel** [comment] 2021-12-21 14:54
Has anyone figured this out, ive spent an entire day trying to get my VSCode back online, it stopped working.  Ive updated everything I can find, and continue to get a certificate expired error, to no avail.  I had hoped by adding the env var NODE_EXTRA_CA_CERTS it would fix, which it does when I try a simple https.get() in the node terminal, but still when running via the extension it does not pick that up.  I'm curous if the extension is hard coded to its own certificate store?

**Comment by bbomgardner** [comment] 2022-01-12 00:38
For now, this worked for me. Download the tar.gz manually and place in the temp directory. The extension seemed to OK to pick it up from there instead of trying to download it.

```powershell
$commit = (code --version)[1]
Invoke-WebRequest -Url "https://update.code.visualstudio.com/commit:$commit/server-linux-x64/stable" -OutFile "$env:TEMP\vsch\serverCache\$commit\vscode-server-linux-x64.tar.gz"
```

**Comment by nchandra-seg** [comment] 2022-01-28 01:19
> For now, this worked for me. Download the tar.gz manually and place in the temp directory. The extension seemed to OK to pick it up from there instead of trying to download it.
> 
> ```powershell
> $commit = (code --version)[1]
> Invoke-WebRequest -Url "https://update.code.visualstudio.com/commit:$commit/server-linux-x64/stable" -OutFile "$env:TEMP\vsch\serverCache\$commit\vscode-server-linux-x64.tar.gz"
> ```
This works awesome. Thanks!!

**Comment by chrmarti** [comment] 2023-12-14 08:37
We now fall back to using Chromiums network stack if downloading through Node.js' network modules failed. Closing this as there are no changes in sight on our site that would improve this.

There is now an extension to help investigate proxy / SSL issues: Install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code.

If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.

Thanks.

**Closed by chrmarti** 2023-12-14 08:37 UTC
Labels: bug, proxy
