### ISSUE TITLE
SSH fails to connect: Connecting was canceled

### ISSUE THREAD

**Issue by arglog** [microsoft/vscode-remote-release#2788] opened 2020-04-17 21:34 UTC
- VSCode Version: 1.44.2
- Local OS Version: Windows_NT x64 10.0.18363
- Remote OS Version: Ubuntu 16.04.6 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
VSCode failed to establish the SSH connection to a remote machine, and this is the information in the output tab
```
[16:21:25.723] Log Level: 2
[16:21:25.737] remote-ssh@0.51.0
[16:21:25.737] win32 x64
[16:21:25.742] SSH Resolver called for "ssh-remote+www.abcd.com", attempt 1
[16:21:25.742] SSH Resolver called for host: www.abcd.com
[16:21:25.743] Setting up SSH remote "www.abcd.com"
[16:21:25.843] Using commit id "ff915844119ce9485abfe8aa9076ec76b5300ddd" and quality "stable" for server
[16:21:25.846] Install and start server if needed
[16:21:31.728] getPlatformForHost was canceled
[16:21:31.729] Resolver error: Connecting was canceled
[16:21:31.733] ------
```
Please let me know if you need more information or need me to test something on the remote machine. Thanks!

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by drkstr101** [comment] 2020-04-17 22:04
Yup, same here. Exact same setup but I'm on Ubuntu 18.  Remote stopped working in `1.44.2`.

**Comment by drkstr101** [comment] 2020-04-17 22:14
@arglog Installing [1.44.1](https://update.code.visualstudio.com/1.44.1/win32-x64-user/stable) release worked as a temporary fix. Make sure to disable auto-update until this is fixed.

**Comment by BruceZoom** [comment] 2020-04-20 11:46
You can remove everything in the folder .vscode-server on the server and reconnect to the server. Seems vscode is trying to reconfigure the server and conflicts with previous settings.

Be sure to backup your configurations in .vscode-server, otherwise, you need to reconfigure those for the remote from scratch.

**Comment by corgan2222** [comment] 2020-04-21 03:31
> 
> 
> @arglog Installing [1.44.1](https://update.code.visualstudio.com/1.44.1/win32-x64-user/stable) release worked as a temporary fix. Make sure to disable auto-update until this is fixed.

tnxs, going back to 1.44.1 worked for me

**Comment by drkstr101** [comment] 2020-05-07 22:32
I can confirm deleting `~/.vscode-server` fixes the problem. I would try this first before attempting to downgrade.

**Comment by Eggiverse** [comment] 2020-05-13 04:38
It seems this issue is gone with vscode 1.45.
My remote os is Ubuntu 16.04.

**Comment by zjs1224522500** [comment] 2020-06-01 04:00
Same here. Is there any clues to fix this isssu?

**Comment by bhavints** [comment] 2020-06-09 15:42
Issue for me was that I didn't notice you could select the OS when doing the Connect to Host command. Once I selected "Linux" as my remote OS, it worked.

**Comment by xnutsive** [comment] 2020-06-11 20:52
Had the issue today, removing  `~/.vscode-server` on the host worked for me, too. Thanks for pointing that out above, folks 👍

**Comment by moiseevigor** [comment] 2020-06-27 11:30
Running latest vscode and all is updated. The issue still persist. My local and remote machines are Ubuntu 16.04. No `~/.vscode-server` found on both of them. Please help!

**Comment by Yilgul** [comment] 2020-06-29 21:23
Same here

> 
> 
> Running latest vscode and all is updated. The issue still persists. My local and remote machines are Ubuntu 16.04. No `~/.vscode-server` found on both of them. Please help!
> 
> Trying remote connect `linux` does not change the behavior.
> 
> Regular ssh with agent and x11 forward works just fine!

Same here, exept remote is Ubuntu 20.04

**Comment by swapnilnshelar** [comment] 2020-07-04 07:54
> @arglog Installing [1.44.1](https://update.code.visualstudio.com/1.44.1/win32-x64-user/stable) release worked as a temporary fix. Make sure to disable auto-update until this is fixed.

thanks, downgrading worked for me, remote host Ubuntu 16.04.5

**Comment by moiseevigor** [comment] 2020-07-20 09:14
Latest version upgrade to `1.47.2` solves the issue. Thanks for the effort!! 
Works on ubuntu 16.

**Comment by okainov** [comment] 2020-07-28 07:30
>Issue for me was that I didn't notice you could select the OS when doing the Connect to Host command. Once I selected "Linux" as my remote OS, it worked.

I'm not sure where can one "select the OS" as there are no any prompts during connection, however one can just open `settings.json` and add

```
 "remote.SSH.remotePlatform": {
        "$remote_server_name": "linux"
    }
```
Remember to replace `$remote_server_name` to the actual server name.

From https://stackoverflow.com/a/61480018/1657819

**Comment by drkstr101** [comment] 2020-08-02 16:45
I believe the prompt is displayed on first connect when configuring the host. I remember being prompted at some point. It's good to know where one can force the setting though. Cheers and thank you for your suggestion!

**Comment by kanyi** [comment] 2020-08-29 12:20
The problem is the same here. In my situation, I try to connect Linux servers (Ubuntus, Debians) from a Windows 10 machine. The problem is the same, without administrator privilegs. When I try to connect with administrator the SSH connection working.

**Comment by bamurtaugh** [comment] 2020-11-04 01:24
Thanks for the discussion here! Since it looks like a variety of solutions were found, going to close out this issue. But if I might have missed something, or folks still have other questions or feedback, please just let me know, and I'd be happy to reopen or discuss further.

**Comment by dominikandreas** [comment] 2020-11-17 12:46
@bamurtaugh the issue persists for me as well. it shouldn't be closed until its actually fixed. the fact that there are workarounds helps but doesn't fix the underlying bug

**Comment by okainov** [comment] 2020-11-17 13:39
@dominikandreas cannot agree more!

**Comment by tbarbette** [comment] 2020-11-24 10:44
Still happening, yes... Deleting the vscode folder on the server solved it. But the bug is still there.

**Comment by bamurtaugh** [comment] 2021-03-24 22:37
Hey folks, I hadn't seen the replies here, thanks for the input.

I had closed it out based on highly upvoted comments such as https://github.com/microsoft/vscode-remote-release/issues/2788#issuecomment-641389166 and https://github.com/microsoft/vscode-remote-release/issues/2788#issuecomment-664829211, which listed solutions that seemed to work for folks. Removing `~/.vscode-server` also often helps with connectivity issues.

But since I'm getting input folks are still experiencing this, I'll go ahead and reopen, and please let me know what you're experiencing today. Thank you!

**Closed** 2021-04-21 01:15 UTC
Labels: polish, ssh

**Comment by roblourens** [comment] 2021-04-21 01:16
Currently this picker closes when focus is lost, that makes it easy to accidentally dismiss, which probably has happened a lot. I pushed a change to keep this picker open when it loses focus. Will be in the next Nightly and then stable a little later. Hope that helps.
