### ISSUE TITLE
Getting WSL install recommendation popup when WSL fails to connect

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1556] opened 2019-10-01 22:09 UTC
Testing https://github.com/microsoft/vscode-remote-release/issues/1518

- Try to connect to WSL, fail, e.g. in https://github.com/microsoft/vscode-remote-release/issues/1555
- See a notification appear that prompts me to install the Remote-WSL extension, even though it's obviously installed already
- If I click "install", I go to the extension viewlet with an error "Error while loading extensions..."

**Comment by aeschli** [comment] 2019-10-29 10:11
I'm not able to reproduce...

**Comment by aeschli** [comment] 2019-12-06 10:31
I now also see this consistently:
![image](https://user-images.githubusercontent.com/6461412/70315951-7e214480-17cf-11ea-993b-52f665038760.png)


We check for installed extensions here: https://github.com/microsoft/vscode/blob/08b0a9bc59793f85e0ad5d84242c902f26706d2d/src/vs/workbench/contrib/extensions/browser/extensionTipsService.ts#L512
but there are no installed extensions returned at all (I have many other extensions installed)

**Comment by sandy081** [comment] 2020-11-16 16:26
It's been quite a while that this issue has been created and there is no any complains from users on this. There have been quite number of improvements and refactorings done in recommendations land. Hence I am closing this. Please reopen it if you are still seeing this issue.

**Closed by sandy081** 2020-11-16 16:26 UTC
Labels: wsl
