### ISSUE TITLE
cannot remove remote host

### ISSUE THREAD

**Issue by charlinone** [microsoft/vscode-remote-release#3753] opened 2020-09-29 01:09 UTC
Issue Type: <b>Bug</b>

some hosts not be used any more,but cannot be removed

Extension version: 0.55.0
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.80GB (3.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by TengM95** [comment] 2020-10-03 03:41
read https://github.com/microsoft/vscode-remote-release/issues/3438

**Comment by Chuxel** [comment] 2020-10-12 00:51
Yes, you can edit the SSH config file to do that. Closing as a dupe of #3438 to do more..

**Closed by Chuxel** 2020-10-12 00:51 UTC
Labels: ssh
