### ISSUE TITLE
C++ Extension Fails To Install

### ISSUE THREAD

**Issue by cliffburdick** [microsoft/vscode-remote-release#89] opened 2019-05-03 19:08 UTC
Hi, I tried to install the C++ extension, but it seems to fail with the following error:

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Framework Assemblies'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Runtime (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```

Edit:
This is a windows 10 client with an Ubuntu 18.04 server using the remote-ssh plugin.

**Comment by mjbvz** [comment] 2019-05-03 20:54
Can you please share information about your local machine and the remote you are trying to connect to

**Comment by cliffburdick** [comment] 2019-05-03 22:23
Hi @mjbvz, this is a Windows 10 machine running code connecting to an Ubuntu 18.04 machine. All the other plugins I've tried work well. Let me know if you need more info.

**Comment by hacqr** [comment] 2019-05-05 08:43
The same error!
Local OS: Windows 10
Remote OS: Centos 7.5

**Comment by egamma** [comment] 2019-05-06 07:08
@cliffburdick which remote are you using remote-wsl, remote-containers, remote-ssh?

**Comment by cliffburdick** [comment] 2019-05-06 14:33
@egamma this is remote-ssh.

**Comment by egamma** [comment] 2019-05-07 07:57
>Installing package 'C/C++ language components (Linux / x86_64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

This hints that the extension download was corrupt, @sandy081 any idea what is going on here?

**Comment by sandy081** [comment] 2019-05-07 10:53
@egamma This happens when the downloaded zip is not complete. 

Its not extension installation issue. This is happening when C++ extension is downloading its run time dependencies. Its better to move to C++ extension repo and see if they know about such issues already.

**Comment by egamma** [comment] 2019-05-07 12:05
Thanks @sandy081, moving to the c++ repo

**Comment by egamma** [comment] 2019-05-07 12:08
Actually this looks like a dupe of https://github.com/microsoft/vscode-cpptools/issues/2246

**Closed by egamma** 2019-05-07 12:08 UTC
Labels: extension-issue
