### ISSUE TITLE
alternatives to `code-server serve-local`

### ISSUE THREAD

**Issue by matifali** [microsoft/vscode-remote-release#8706] opened 2023-07-12 13:42 UTC
I was able to use code-server on my local network using
```bash
wget -O- https://aka.ms/install-vscode-server/setup.sh | sh
code-server --accept-server-license-terms serve-local --without-connection-token --quality stable
```
But it seems like the [link](https://aka.ms/install-vscode-server/setup.sh) to download the code-server is no more valid

Are there any workarounds to achieve the same setup with 
`code tunnel`

Note:
> I know about https://coder/code-server but that doesn't allow using extensions from the Microsoft marketplace (e.g. GitHub Copilot) and also settings sync doesn't work

**Comment by Igorgro** [comment] 2023-07-13 06:48
You can setup self-hosted vscode server using this instruction: https://github.com/microsoft/vscode/issues/135856#issuecomment-1170091265

**Comment by matifali** [comment] 2023-07-13 06:51
@Igorgro Great Thank you :)

**Comment by bamurtaugh** [comment] 2023-07-27 21:27
Closing as a duplicate of https://github.com/microsoft/vscode/issues/168492.

**Closed by bamurtaugh** 2023-07-27 21:27 UTC
Labels: code-server

**Comment by matifali** [comment] 2023-08-07 07:30
> You can setup self-hosted vscode server using this instruction: https://github.com/microsoft/vscode/issues/135856#issuecomment-1170091265

This workaround suddenly stopped working. :(
