### ISSUE TITLE
Have to kill the vscode-server process for each SSH-connect [RHEL/CentOS 6.10] NFSv4

### ISSUE THREAD

**Issue by csaar95** [microsoft/vscode-remote-release#716] opened 2019-06-17 14:46 UTC
- VSCode Version: 1.36.0-insider (system setup), Commit 11b88a3323878a98b418e4efca77e7afabd50d01
- Local OS Version: Windows_NT x64 10.0.17763
- Remote OS Version: CentOS release 6.10 (Final)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Reinstall the missing libraries for RHEL/CentOS [link](https://github.com/microsoft/vscode-remote-release/issues/103#issuecomment-497118857)
2. Setting up local and remote host for ssh connection (key, config..)
3. `Remote SSH: Connect to Host...`

- Before connecting to the remote host, vscode-server is not  running.
- Starting the ssh connection to the remote host -> starts vscode-server on the remote machine.
```
[root@xxx ~]# ps -ef | grep code
yyy   1981     1  0 16:16 ?        00:00:00 sh /home/yyy/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/server.sh --port=0
yyy   1989  1981  0 16:16 ?        00:00:01 /home/yyy/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/node /home/yyy/.vscode-server-insiders/bin/11b88a3323878a98b418e4efca77e7afabd50d01/out/vs/server/main.js --port=0
```
- All is working fine, ready to open a folder into the workspace.
- Now the extension is reconnecting to the remote host, but can't establish a connection (*Connect to VS Code Server - retry ...*).
- If I kill the already running VS Code Server process, the retry works and opens the directory into the workspace.
```
 [root@xxx ~]# kill -9 1989
```

**Comment by roblourens** [comment] 2019-06-19 04:53
Interesting, could you share the full log from the "Remote - SSH" output channel when connecting is failing??

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by csaar95** [comment] 2019-06-19 06:29
```
remote-ssh@0.42.2
SSH Resolver called for "ssh-remote+xxx"
SSH Resolver called for host: xxx
Setting up SSH remote "xxx"
Using commit id "11b88a3323878a98b418e4efca77e7afabd50d01" and quality "insider" for server
Install and start server if needed
> 
> Installation already in progress...
> 8ebb1538-e1a1-4836-abde-89020eee2224##24##
> 
"install" terminal command done
Received install output: 8ebb1538-e1a1-4836-abde-89020eee2224##24##
Server installation process already in progress - waiting and retrying 1
> 
> Installation already in progress...
> 8ebb1538-e1a1-4836-abde-89020eee2224##24##
> 
"install" terminal command done
Received install output: 8ebb1538-e1a1-4836-abde-89020eee2224##24##
Server installation process already in progress - waiting and retrying 2
> 
> Installation already in progress...
> 8ebb1538-e1a1-4836-abde-89020eee2224##24##
> 
"install" terminal command done
Received install output: 8ebb1538-e1a1-4836-abde-89020eee2224##24##
Server installation process already in progress - waiting and retrying 3

[...]

> 
> Installation already in progress...
> 
> 8ebb1538-e1a1-4836-abde-89020eee2224##24##
> 
"install" terminal command done
Received install output: 8ebb1538-e1a1-4836-abde-89020eee2224##24##
Server installation process already in progress - waiting and retrying 28
> 
> Installation already in progress...
> 8ebb1538-e1a1-4836-abde-89020eee2224##24##
> 
"install" terminal command done
Received install output: 8ebb1538-e1a1-4836-abde-89020eee2224##24##
Server installation process already in progress - waiting and retrying 29
> 
> Installation already in progress...
> 8ebb1538-e1a1-4836-abde-89020eee2224##24##
> 
> 
"install" terminal command done
Received install output: 8ebb1538-e1a1-4836-abde-89020eee2224##24##
Server installation process already in progress - waiting and retrying 30
```

**Comment by roblourens** [comment] 2019-06-19 16:56
Are you on a filesystem where file locking might not work correctly? 

Can you try running the command "Uninstall VS Code Server from Host" and trying again?

**Comment by KapitanOczywisty** [comment] 2019-06-20 13:18
I my case lock file is ending with `)`, and I'm not sure if this is intended. I'm just changing it's name and then it works for a bit.

**Comment by roblourens** [comment] 2019-06-20 19:02
I think I fixed this in today's nightly build, please make sure it updates then let me know if it happens agian.

**Comment by KapitanOczywisty** [comment] 2019-06-20 19:15
@roblourens correct. Normal build won't work at all with my configuration.

**Comment by csaar95** [comment] 2019-06-21 06:29
- Updated to Commit *c3fe2d8acde04e579880413ae4622a1f551efdcc*
- After uninstalling and reinstalling the VS Code Server from the remote host, the same problem appears
- Filesystem is NFSv4, which should support file locking ([link](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.idan400/lockv4.htm)

**Comment by roblourens** [comment] 2019-06-27 00:13
Ok, my gut feel is that it would be related to NFS somehow but I will have to try it out.

**Comment by csaar95** [comment] 2019-07-04 06:30
Do you need any further information?

**Comment by roblourens** [comment] 2019-07-15 03:37
Is this still an issue @csaar95? I set up an NFS drive for testing and am able to connect with no issues.

**Comment by csaar95** [comment] 2019-07-15 06:40
Updated to Version: 1.37.0-insider (system setup), Commit: 894056d11c7fffb261a0100fd4dcbf8cff84a8c0

Still the same issue, after chosing a folder, VSCode is going into the retry-loop.

**Comment by roblourens** [comment] 2019-07-15 15:01
Can you run `mount` and share the line for the NFS drive? Mine looks like

```
127.0.0.1:/datadrive/shared on /mnt/shared type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)
```

Also the output of `uname -a`?

And if you know the name of the command to mount the nfs drive, that would be helpful as well.

**Comment by csaar95** [comment] 2019-07-15 15:59
- `mount`
```
192.168.xxx.yyy:/mnt/export/csaar95 on /home/csaar95 type nfs (rw,vers=4,addr=192.168.xxx.yyy,clientaddr=192.168.xxx.zzz)
```

- `uname -a`
```
Linux xxx 2.6.32-754.17.1.el6.x86_64 #1 SMP Tue Jul 2 12:42:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Mount via `auto.home` and NIS
```
[xxx:/home/csaar95] ypcat auto.home | grep csaar95
192.168.xxx.yyy:/mnt/export/csaar95
```

**Comment by roblourens** [comment] 2019-07-15 16:34
In https://github.com/microsoft/vscode-remote-release/issues/885 someone said it works in nfs 4.1 but not 4.0 so I will try to downgrade and test again. If you have any way to upgrade that might be a workaround for you.

**Comment by roblourens** [comment] 2019-07-16 23:54
I've added a setting `remote.SSH.lockfilesInTmp` which you can set that should fix this. Please try it out in tomorrow's nightly ssh extension and let me know. I haven't been able to actually repro the issue so I think that's all I'll be able to do. Calling this a dupe of https://github.com/microsoft/vscode-remote-release/issues/885

**Closed by roblourens** 2019-07-16 23:54 UTC
Labels: bug, ssh
