### ISSUE TITLE
vscode 1.52 connect to remote server

### ISSUE THREAD

**Issue by starxchina** [microsoft/vscode-remote-release#4211] opened 2020-12-15 09:05 UTC
I have connected to the server, but after a few seconds vscode alert "Cannot reconnect. Please reload the window"
vscode: macos version 
server:centos 7.8

**Comment by roblourens** [comment] 2020-12-17 18:54
>>Is your host ARM or x86? Can you share the Remote-SSH log from the output channel?

>mac OS Catalina 10.15.6 x86

I meant the remote CentOS host

**Comment by alexdima** [comment] 2020-12-18 22:00
This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (https://github.com/microsoft/vscode/issues/112843)

**Comment by starxchina** [comment] 2020-12-19 03:56
> > > Is your host ARM or x86? Can you share the Remote-SSH log from the output channel?
> 
> > mac OS Catalina 10.15.6 x86
> 
> I meant the remote CentOS host

remote:CentOS Linux release 7.9.2009 (Core)
<img width="1441" alt="Screen Shot 2020-12-19 at 11 51 27 AM" src="https://user-images.githubusercontent.com/38390902/102680204-2d6d6580-41f1-11eb-8c70-53863a13813c.png">
<img width="1442" alt="Screen Shot 2020-12-19 at 11 52 01 AM" src="https://user-images.githubusercontent.com/38390902/102680208-33fbdd00-41f1-11eb-9030-d3870928a3b3.png">

**Comment by alexr00** [comment] 2020-12-21 13:39
@starxchina would you be willing to try the following steps? This would help us confirm that we've found the issue, and you'll also get to use a more up-to-date version.

1. On your remote machine, add the following line to your .bashrc file: `export VSCODE_DISABLE_PROC_READING=true`
2. Install [VS Code Insiders](https://code.visualstudio.com/insiders/)
3. Try to repro your original issue with VS Code Insiders. 

Setting that environment variable will cause VS Code (insiders only right now, I'll make a proper fix that doesn't involve an environment variable for the next stable release), to not do the proc filesystem reading that we do to automatically forward ports for you. This does mean that automatic port forwarding will not work while you have that environment variable set.

**Comment by stephenstack** [comment] 2021-01-09 22:17
Hi @alexr00 

Spent about 3 hours trying to fix this same issue today. I followed your instructions. Was able to connect successfully on insiders with or without the env-var. 

I'll keep insiders on my machine in case you need any further info. Going to rollback my prod vscode to a prev version. Unless there's a way to turn of the port forwarding.
Thanks

**Comment by alexr00** [comment] 2021-01-11 10:18
@stephenstack the fix that doesn't require an environment variable is available in insiders, so glad to hear that using insiders solved it for you. There is no way to turn off the problematic code in 1.52.

**Comment by alexr00** [comment] 2021-01-11 10:18
duplicate of https://github.com/microsoft/vscode/issues/112843

**Closed by alexr00** 2021-01-11 10:18 UTC

**Comment by stephenstack** [comment] 2021-01-11 14:20
@alexr00 A reboot of my laptop resolved the issues... really odd.
