### ISSUE TITLE
SSH: Whould like to be able to install extensions to remote servers from the list of the extensions already installed locally, right via ssh

### ISSUE THREAD

**Issue by sergei3000** [microsoft/vscode-remote-release#241] opened 2019-05-08 14:59 UTC
The problem:
I got everything running on my remote server with your cool new remote features. Thankfully that server has all the connections needed.
Now I would like to  install new extensions to the remote server but I cannot do it. The problem is that I need to be in the corporate network to ssh to the server, and there are certain security limitations in that network. I can browse websites while being in this network, curl works also, but VS Code wouldn't connect to the Extensions Marketplace. It says "We cannot connect to the Extensions Marketplace at this time, please try again later".
To install new extensions, I have to switch to another network, but I loose my ssh connection at the moment I do that. So there is no way I can install extensions from the Marketplace to my remote server.

Proposed solution:
I think it would be great to have a possibility to copy extensions installed into VS Code locally, to the remote location via ssh.

**Comment by egamma** [comment] 2019-05-08 15:43
Duplicate of #15

**Closed by egamma** 2019-05-08 15:43 UTC
