### ISSUE TITLE
[Remote-SSH Bug]: openssh is incompatible with VSCode's Remote Development 

### ISSUE THREAD

**Issue by etanman** [microsoft/vscode-remote-release#8861] opened 2023-08-19 03:38 UTC
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->
Specific questions please see here
(https://github.com/PowerShell/Win32-OpenSSH/issues/2116)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment] 2023-09-15 03:26
Seems like a dupe of https://github.com/microsoft/vscode-remote-release/issues/8929

**Closed by roblourens** 2023-09-15 03:26 UTC
Labels: ssh
