### ISSUE TITLE
Support "Include" in openssh config

### ISSUE THREAD

**Issue by lukewang1024** [microsoft/vscode-remote-release#691] opened 2019-06-14 11:26 UTC
Issue Type: <b>Feature Request</b>

One may choose to split his ssh_config up into several parts for maintainability, by "Include" keyword as stated in the man page:

```
     Include
             Include the specified configuration file(s).  Multiple pathnames may be specified and each pathname may con-
             tain glob(7) wildcards and, for user configurations, shell-like `~' references to user home directories.
             Files without absolute paths are assumed to be in ~/.ssh if included in a user configuration file or /etc/ssh
             if included from the system configuration file.  Include directive may appear inside a Match or Host block to
             perform conditional inclusion.
```

It would be great if "Remote - SSH" can support this so that guys with similar setup can see all their configured hosts directly. Thanks!

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.5.0

**Comment by ryansully** [comment] 2019-06-21 02:00
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/65?

**Comment by roblourens** [comment] 2019-06-27 00:08
Yes thanks

**Closed by roblourens** 2019-06-27 00:08 UTC
Labels: feature-request, ssh
