### ISSUE TITLE
Disconnects from WSL every startup

### ISSUE THREAD

**Issue by ahillikerMDSOL** [microsoft/vscode-remote-release#4782] opened 2021-03-26 22:05 UTC
Issue Type: <b>Bug</b>

Every time I start the application, it hangs and disconnects. I then have to manually reconnect or restart app again.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042
Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (3.38GB free)|
|Process Argv|--crash-reporter-id e918a852-be67-4c4b-878b-42483b0ca633|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30280385
pythonvspyt943cf:30280190
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by aeschli** [comment] 2021-03-29 10:56
Can you paste the WSL log here?

So everything connects successfully, and then after a while you see the reconnect dialog?

**Comment by ahillikerMDSOL** [comment] 2021-03-29 18:08
It appears to connect, but seems to show a cached version of my previously opened workspace. If I make edits before the error appears (typically a few seconds) they fail to save.

I mistyped earlier; this doesn't occur each time I start the application, I think it's more accurately once per boot (which essentially equates to every time I open the app as I typically shut down the machine at night).

Here's a successful connection log if that helps - I wasn't sure how to view the log until just now so I'll try to view it next time it fails to load:

`[2021-03-29 18:01:18.249] Resolving wsl+Ubuntu, resolveAttempt: 1
[2021-03-29 18:01:18.283] Starting VS Code Server inside WSL (Ubuntu)
[2021-03-29 18:01:18.283] Extension version: 0.54.6, Windows build: 19042. Multi distro support: available. WSL path support: enabled
[2021-03-29 18:01:18.283] No shell environment set or found for current distro.
[2021-03-29 18:01:18.376] Connecting to daemon started by other Remote-WSL window... 4.19.128-microsoft-standard Ubuntu
[2021-03-29 18:01:18.380] Pinging 172.23.63.110:43131...
[2021-03-29 18:01:18.384] 172.23.63.110:43131 responded
[2021-03-29 18:01:18.384] WSL resolver response: 172.23.63.110:43131
[2021-03-29 18:01:18.384] To debug connection issues, open a local browser on http://172.23.63.110:43131/version`

**Comment by ahillikerMDSOL** [comment] 2021-03-30 13:36
OK here's a log from a connection failure:

```[2021-03-30 13:33:21.700] Resolving wsl+Ubuntu, resolveAttempt: 1
[2021-03-30 13:33:21.738] Starting VS Code Server inside WSL (Ubuntu)
[2021-03-30 13:33:21.738] Extension version: 0.54.6, Windows build: 19042. Multi distro support: available. WSL path support: enabled
[2021-03-30 13:33:21.738] No shell environment set or found for current distro.
[2021-03-30 13:33:21.843] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2021-03-30 13:33:21.924] Probing result: found
[2021-03-30 13:33:21.924] Server install found in WSL
[2021-03-30 13:33:21.924] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8 stable .vscode-server 0  '}
[2021-03-30 13:33:22.149] Setting up server environment: Looking for /home/zaxxon/.vscode-server/server-env-setup. Not found.
[2021-03-30 13:33:22.149] WSL version: 4.19.128-microsoft-standard Ubuntu
[2021-03-30 13:33:22.149] WSL2-shell-PID: 151
[2021-03-30 13:33:22.149] Starting server: /home/zaxxon/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/server.sh  --port=0 --use-host-proxy --without-browser-env-var --print-ip-address --enable-remote-auto-shutdown  
[2021-03-30 13:33:22.459] 
[2021-03-30 13:33:22.459] 
[2021-03-30 13:33:22.459] *
[2021-03-30 13:33:22.459] * Visual Studio Code Server
[2021-03-30 13:33:22.459] *
[2021-03-30 13:33:22.459] * Reminder: You may only use this software with Visual Studio family products,
[2021-03-30 13:33:22.459] * as described in the license https://aka.ms/vscode-remote/license
[2021-03-30 13:33:22.459] *
[2021-03-30 13:33:22.459] 
[2021-03-30 13:33:22.459] IP Address: 172.23.63.110
[2021-03-30 13:33:22.459] Extension host agent listening on 44797
[2021-03-30 13:33:22.459] 
[2021-03-30 13:33:22.459] [09:33:23] Extension host agent started.
[2021-03-30 13:33:22.464] Pinging 172.23.63.110:44797...
[2021-03-30 13:33:22.469] 172.23.63.110:44797 responded
[2021-03-30 13:33:22.469] WSL resolver response: 172.23.63.110:44797
[2021-03-30 13:33:22.469] To debug connection issues, open a local browser on http://172.23.63.110:44797/version```

When I go to the URL in the last line it says: `2b9aebd5354a3629c3aba0a5f5df49f43d6689f8`

**Comment by ahillikerMDSOL** [comment] 2021-03-30 13:39
And a few moments later the following appeared in the log:

```
[2021-03-30 13:38:37.788] [09:33:24] [::ffff:172.23.48.1][75019c67][ExtensionHostConnection] New connection established.
[2021-03-30 13:38:37.788] [09:33:24] [::ffff:172.23.48.1][9139e0fd][ManagementConnection] New connection established.
[2021-03-30 13:38:37.788] [09:33:39] [::ffff:172.23.48.1][75019c67][ExtensionHostConnection] <770> Launched Extension Host Process.
[2021-03-30 13:38:37.788] EXTHOST-LOG:::::
[2021-03-30 13:38:37.788] ["Error: invalid distance too far back\n    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)"]
[2021-03-30 13:38:37.788] EXTHOST-STDERR::::::::/home/zaxxon/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostProcess.js:3
[2021-03-30 13:38:37.788]  *--------------------------------------------------------*/(function(){var ge=["require","exports","vs/base/common/uri","vs/base/common/event","vs/platform/instantiation/common/instantiation","vs/base/common/lifecycle","vs/workbench/api/common/extHost.protocol","vs/base/common/path","vs/workbench/api/common/extHostTypes","vs/base/common/platform","vs/base/common/strings","vs/platform/log/common/log","vs/base/common/arrays","vs/base/common/network","vs/workbench/api/common/extHostRpcService","vs/base/common/errors","vs/base/common/types","vs/nls","vs/nls!vs/server/remoteExtensionHostProcess","vs/base/common/async","vs/workbench/api/common/extHostTypeConverters","vs/base/common/cancellation","vs/base/common/map","vs/base/common/objects","vs/base/node/pfs","vs/base/common/resources","vs/base/common/buffer","vs/workbench/api/common/extHostInitDataService","vs/base/common/uuid","fs","vs/platform/extensions/common/extensions","vs/base/common/extpath","vs/workbench/services/search/common/search","vs/workbench/api/common/extHostWorkspace","vs/base/common/glob","child_process","vs/workbench/api/common/extHostTerminalService","vs/workbench/api/common/extHostConfiguration","vs/base/common/process","os","vs/workbench/api/common/extHostDocumentsAndEditors","vs/platform/registry/common/platform","vs/workbench/services/extensions/common/extensions","vs/workbench/api/common/extHostExtensionService","vs/editor/common/core/range","vs/workbench/api/common/extHostDebugService","vs/base/common/stopwatch","vs/base/common/codicons","vs/editor/common/core/position","vs/base/common/errorMessage","vs/platform/files/common/files","vs/workbench/api/common/extHostTunnelService","vs/workbench/contrib/notebook/common/notebookCommon","vs/workbench/api/common/extHostCommands","vs/base/common/assert","vs/base/common/collections","vs/base/common/decorators","vs/base/common/json","vs/base/common/linkedList","vs/base/common/marshalling","vs/platform/contextkey/common/contextkey","vs/platform/workspace/common/workspace","vs/workbench/api/common/extHostFileSystemInfo","vs/workbench/api/common/extHostUriTransformerService","vs/workbench/api/common/extHostApiDeprecationService","vs/workbench/api/common/extHostOutput","vs/workbench/api/common/extHostWebview","vs/workbench/api/common/extHostTask","vs/base/common/performance","vs/workbench/api/common/extHostSearch","vs/base/common/functional","vs/base/common/idGenerator","vs/base/common/iterator","vs/base/common/numbers","vs/base/common/hash","vs/base/common/severity","vs/base/common/normalization","vs/base/common/labels","vs/editor/common/modes/languageSelector","vs/base/node/processes","vs/platform/instantiation/common/extensions","vs/editor/common/modes","vs/platform/instantiation/common/serviceCollection","vs/platform/configuration/common/configurationRegistry","vs/platform/configuration/common/configuration","vs/workbench/api/common/shared/webview","vs/workbench/api/common/exHostSecretState","vs/workbench/api/common/extHostFileSystemConsumer","vs/workbench/api/common/extHostStorage","vs/workbench/api/common/extHostStoragePaths","vs/workbench/services/search/node/ripgrepSearchUtils","vs/base/common/comparers","vs/base/common/stream","vs/base/common/uint","vs/base/common/filters","vs/base/common/fuzzyScorer","vs/base/common/htmlContent","vs/base/common/uriIpc","string_decoder","vs/base/node/powershell","vs/base/parts/ipc/common/ipc","vs/base/parts/ipc/common/ipc.net","vs/editor/common/core/characterClassifier","vs/editor/common/model","vs/editor/common/model/wordHelper","vs/editor/common/services/semanticTokensDto","vs/editor/common/viewModel/prefixSumComputer","vs/platform/instantiation/common/descriptors","vs/platform/log/node/spdlogLog","vs/platform/markers/common/markers","vs/platform/jsonschemas/common/jsonContributionRegistry","vs/platform/remote/common/remoteAuthorityResolver","vs/platform/remote/common/remoteHosts","vs/platform/terminal/node/terminalEnvironment","vs/platform/workspaces/common/workspaces","vs/workbench/api/common/cache","vs/workbench/contrib/debug/common/abstractDebugAdapter","net","vs/workbench/api/common/extHostDocumentData","vs/workbench/api/common/extHostTextEditor","vs/workbench/services/extensions/common/proxyIdentifier","vs/workbench/api/common/extHostDecorations","vs/workbench/api/common/extHostWindow","vs/workbench/services/search/common/searchExtTypes","vs/workbench/services/search/common/textSearchManager","vs/workbench/services/search/node/textSearchManager","vs/workbench/services/search/node/ripgrepTextSearchEngine","vs/base/parts/ipc/node/ipc.net","vs/base/common/jsonFormatter","vs/base/common/jsonEdit","vs/base/common/lazy","vs/base/common/processes","vs/base/common/iconLabels","vs/base/node/decoder","vs/base/node/extpath","vs/editor/common/controller/wordCharacterClassifier","vs/editor/common/core/selection","vs/editor/common/model/textModelSearch","vs/editor/common/modes/languageConfiguration","vs/editor/common/modes/linkComputer","vs/editor/common/modes/tokenizationRegistry","vs/editor/common/model/mirrorTextModel","vs/nls!vs/base/common/date","vs/base/common/date","vs/nls!vs/base/common/errorMessage","vs/nls!vs/base/node/processes","vs/base/node/shell","vs/nls!vs/editor/common/config/editorOptions","vs/editor/common/config/editorOptions","vs/nls!vs/platform/configuration/common/configurationRegistry","vs/nls!vs/platform/extensionManagement/common/extensionManagement","vs/nls!vs/platform/files/common/files","vs/nls!vs/platform/markers/common/markers","vs/nls!vs/platform/terminal/node/terminalProcess","vs/nls!vs/platform/theme/common/iconRegistry","vs/nls!vs/platform/workspaces/common/workspaces","vs/nls!vs/workbench/api/common/extHost.api.impl","vs/nls!vs/workbench/api/common/extHostDiagnostics","vs/nls!vs/workbench/api/common/extHostExtensionActivator","vs/nls!vs/workbench/api/common/extHostExtensionService","vs/nls!vs/workbench/api/common/extHostProgress","vs/nls!vs/workbench/api/common/extHostStatusBar","vs/nls!vs/workbench/api/common/extHostTerminalService","vs/nls!vs/workbench/api/common/extHostTreeViews","vs/nls!vs/workbench/api/common/extHostWorkspace","vs/nls!vs/workbench/api/node/extHostDebugService","vs/nls!vs/workbench/common/views","vs/nls!vs/workbench/contrib/debug/common/abstractDebugAdapter","vs/nls!vs/workbench/contrib/debug/node/debugAdapter","vs/nls!vs/workbench/contrib/externalTerminal/node/externalTerminalService","vs/nls!vs/workbench/contrib/search/common/queryBuilder","vs/nls!vs/workbench/contrib/terminal/common/terminal","vs/nls!vs/workbench/services/configurationResolver/common/variableResolver","vs/platform/editor/common/editor","vs/platform/instantiation/common/graph","vs/editor/common/services/modelService","vs/editor/common/modes/languageFeatureRegistry","vs/platform/commands/common/commands","vs/platform/environment/common/environment","vs/platform/extensionManagement/common/extensionManagement","vs/platform/extensionManagement/common/extensionManagementUtil","vs/platform/instantiation/common/instantiationService","vs/platform/notification/common/notification","vs/platform/product/common/product","vs/platform/progress/common/progress","vs/platform/configuration/common/configurationModels","vs/platform/sign/node/signService","vs/platform/terminal/common/terminalDataBuffering","vs/platform/terminal/node/terminalProcess","vs/platform/theme/common/theme","vs/platform/theme/common/themeService","vs/platform/theme/common/iconRegistry","vs/workbench/api/common/extHostEditorTabs","vs/workbench/api/common/extHostMemento","vs/workbench/api/common/extHostSecrets","vs/workbench/api/common/extHostCodeInsets","vs/workbench/common/views","vs/workbench/api/common/apiCommands","vs/workbench/contrib/debug/common/debugUtils","vs/workbench/contrib/debug/node/debugAdapter","vs/workbench/contrib/externalTerminal/node/externalTerminal","vs/workbench/contrib/externalTerminal/node/externalTerminalService","vs/workbench/contrib/debug/node/terminals","vs/workbench/api/common/extHostNotebookConcatDocument","vs/workbench/api/common/extHostTheming","vs/workbench/contrib/tasks/common/taskService","vs/workbench/contrib/terminal/common/environmentVariable","vs/workbench/contrib/terminal/common/environmentVariableCollection","vs/workbench/contrib/terminal/common/environmentVariableShared","vs/workbench/contrib/terminal/common/terminal","vs/workbench/contrib/terminal/common/terminalEnvironment","vs/workbench/contrib/terminal/node/terminal","vs/workbench/contrib/terminal/node/terminalEnvironment","vs/workbench/contrib/testing/common/testCollection","vs/workbench/services/configurationResolver/common/variableResolver","vs/workbench/services/editor/common/editorGroupsService","vs/workbench/services/editor/common/editorService","vs/workbench/api/common/extHostDocumentSaveParticipant","vs/workbench/api/common/extHostFileSystemEventService","vs/workbench/api/common/extHostNotebookDocument","vs/workbench/api/common/extHostNotebookEditor","vs/workbench/api/common/extHostProgress","vs/workbench/api/common/extHostTreeViews","vs/workbench/contrib/testing/common/ownedTestCollection","vs/workbench/services/extensions/common/extensionDescriptionRegistry","vs/workbench/services/extensions/common/extensionHostProtocol","vs/workbench/api/common/extHostExtensionActivator","vs/workbench/api/node/extHostLogService","vs/workbench/services/extensions/common/lazyPromise","vs/workbench/api/common/extHostAuthentication","vs/workbench/api/common/extHostBulkEdits","vs/workbench/api/common/extHostClipboard","vs/workbench/api/common/extHostApiCommands","vs/workbench/api/common/extHostComments","vs/workbench/api/common/extHostDiagnostics","vs/workbench/api/common/extHostDialogs","vs/workbench/api/common/extHostDocumentContentProviders","vs/workbench/api/common/extHostDocuments","vs/workbench/api/common/extHostFileSystem","vs/workbench/api/common/extHostLabelService","vs/workbench/api/common/extHostLanguageFeatures","vs/workbench/api/common/extHostLanguages","vs/workbench/api/common/extHostMessageService","vs/workbench/api/common/extHostNotebook","vs/workbench/api/common/extHostQuickOpen","vs/workbench/api/common/extHostSCM","vs/workbench/api/common/extHostStatusBar","vs/workbench/api/common/extHostTextEditors","vs/workbench/api/common/extHostTimeline","vs/workbench/api/common/extHostUriOpener","vs/workbench/api/common/extHostUrls","vs/workbench/api/common/extHostCustomEditors","vs/workbench/api/common/extHostWebviewPanels","vs/workbench/api/common/extHostWebviewView","vs/workbench/api/node/extHostDownloadService","vs/workbench/api/node/extHostOutputService","vs/workbench/api/node/extHostTunnelService","vs/workbench/services/extensions/common/rpcProtocol","vs/workbench/services/remote/common/remoteAgentService","vs/workbench/services/path/common/pathService","vs/workbench/api/common/extHostTesting","vs/workbench/contrib/search/common/queryBuilder","vs/workbench/api/common/shared/workspaceContains","vs/workbench/api/common/extHostRequireInterceptor","vs/workbench/api/node/extHostDebugService","vs/workbench/api/node/extHostTask","vs/workbench/api/node/extHostTerminalService","vs/workbench/services/extensions/common/extensionHostMain","vs/workbench/services/search/common/fileSearchManager","vs/workbench/api/common/extHost.api.impl","vs/workbench/api/common/extHost.common.services","vs/workbench/services/textfile/common/encoding","vs/workbench/services/extensions/node/proxyResolver","http","vs/workbench/services/search/node/ripgrepFileSearch","vscode-ripgrep","vs/workbench/services/search/node/fileSearch","vs/workbench/services/search/node/ripgrepSearchProvider","vs/workbench/services/search/node/textSearchAdapter","vs/workbench/services/search/node/rawSearchService","vs/workbench/api/node/extHostSearch","vs/workbench/api/node/extHostCLIServer","vs/workbench/api/node/extHostExtensionService","vs/workbench/api/node/extHost.node.services","vs/workbench/services/extensions/node/extensionHostProcessSetup","util","vs/base/common/marked/marked","https","tls","url","vscode-proxy-agent","events","vscode-regexpp","graceful-fs","crypto","zlib","minimist","vs/server/remoteExtensionHostProcess"],pe=function(Q){for(var e=[],v=0,D=Q.length;v<D;v++)e[v]=ge[Q[v]];return e};define(ge[54],pe([0,1]),function(Q,e){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.ok=void 0;function v(D,R){if(!D)throw new Error(R?`Assertion failed (${R})`:"Assertion Failed")}e.ok=v}),define(ge[55],pe([0,1]),function(Q,e){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.SetMap=e.diffMaps=e.diffSets=e.fromMap=e.groupBy=e.forEach=e.values=void 0;const v=Object.prototype.hasOwnProperty;function D(T){const k=[];for(let g in T)v.call(T,g)&&k.push(T[g]);return k}e.values=D;function R(T,k){for(let g in T)if(v.call(T,g)&&k({key:g,value:T[g]},function(){delete T[g]})===!1)return}e.forEach=R;function P(T,k){const g=Object.create(null);for(const f of T){const l=k(f);let m=g[l];m||(m=g[l]=[]),m.push(f)}return g}e.groupBy=P;function C(T){const k=Object.create(null);return T&&T.forEach((g,f)=>{k[f]=g}),k}e.fromMap=C;function I(T,k){const g=[],f=[];for(let l of T)k.has(l)||g.push(l);for(let l of k)T.has(l)||f.push(l);return{removed:g,added:f}}e.diffSets=I;function y(T,k){const g=[],f=[];for(let[l,m]of T)k.has(l)||g.push(m);for(let[l,m]of k)T.has(l)||f.push(m);return{removed:g,added:f}}e.diffMaps=y;class i{constructor(){this.map=new Map}add(k,g){let f=this.map.get(k);f||(f=new Set,this.map.set(k,f)),f.add(g)}delete(k,g){const f=this.map.get(k);!f||(f.delete(g),f.size===0&&this.map.delete(k))}forEach(k,g){const f=this.map.get(k);!f||f.forEach(g)}}e.SetMap=i}),define(ge[56],pe([0,1]),function(Q,e){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.throttle=e.debounce=e.memoize=e.createMemoizer=e.createDecorator=void 0;function v(y){return(i,T,k)=>{let g=null,f=null;if(typeof k.value=="function"?(g="value",f=k.value):typeof k.get=="function"&&(g="get",f=k.get),!f)throw new Error("not supported");k[g]=y(f,T)}}e.createDecorator=v;let D=0;function R(){const y=`$memoize${D++}`;let i;const T=function(g,f,l){let m=null,S=null;if(typeof l.value=="function"?(m="value",S=l.value,S.length!==0&&console.warn("Memoize should only be used in functions with zero parameters")):typeof l.get=="function"&&(m="get",S=l.get),!S)throw new Error("not supported");const w=`${y}:${f}`;l[m]=function(...p){return i=this,this.hasOwnProperty(w)||Object.defineProperty(this,w,{configurable:!0,enumerable:!1,writable:!0,value:S.apply(this,p)}),this[w]}};return T.clear=()=>{typeof i!="undefined"&&Object.getOwnPropertyNames(i).forEach(k=>{k.indexOf(y)===0&&delete i[k]})},T}e.createMemoizer=R;function P(y,i,T){return R()(y,i,T)}e.memoize=P;function C(y,i,T){return v((k,g)=>{const f=`$debounce$${g}`,l=`$debounce$result$${g}`;return function(...m){this[l]||(this[l]=T?T():void 0),clearTimeout(this[f]),i&&(this[l]=i(this[l],...m),m=[this[l]]),this[f]=setTimeout(()=>{k.apply(this,m),this[l]=T?T():void 0},y)}})}e.debounce=C;function I(y,i,T){return v((k,g)=>{const f=`$throttle$timer$${g}`,l=`$throttle$result$${g}`,m=`$throttle$lastRun$${g}`,S=`$throttle$pending$${g}`;return function(...w){if(this[l]||(this[l]=T?T():void 0),(this[m]===null||this[m]===void 0)&&(this[m]=-Number.MAX_VALUE),i&&(this[l]=i(this[l],...w)),!this[S]){const p=this[m]+y;p<=Date.now()?(this[m]=Date.now(),k.apply(this,[this[l]]),this[l]=T?T():void 0):(this[S]=!0,this[f]=setTimeout(()=>{this[S]=!1,this[m]=Date.now(),k.apply(this,[this[l]]),this[l]=T?T():void 0},p-Date.now()))}}})}e.throttle=I}),define(ge[15],pe([0,1]),function(Q,e){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.createErrorWithActions=e.isErrorWithActions=e.ExpectedError=e.NotSupportedError=e.NotImplementedError=e.getErrorMessage=e.disposed=e.readonly=e.illegalState=e.illegalArgument=e.canceled=e.CancellationError=e.isPromiseCanceledError=e.transformErrorForSerialization=e.onUnexpectedExternalError=e.onUnexpectedError=e.setUnexpectedErrorHandler=e.errorHandler=e.ErrorHandler=void 0;class v{constructor(){this.listeners=[],this.unexpectedErrorHandler=function(t){setTimeout(()=>{throw t.stack?new Error(t.message+`
[2021-03-30 13:38:37.788]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
[2021-03-30 13:38:37.788] 
[2021-03-30 13:38:37.788] Error: invalid distance too far back
[2021-03-30 13:38:37.788] 
[2021-03-30 13:38:37.788] Error: invalid distance too far back
[2021-03-30 13:38:37.788]     at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
[2021-03-30 13:38:37.788]     at Timeout._onTimeout (/home/zaxxon/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostProcess.js:3:16107)
[2021-03-30 13:38:37.788]     at listOnTimeout (internal/timers.js:549:17)
[2021-03-30 13:38:37.788]     at processTimers (internal/timers.js:492:7)
[2021-03-30 13:38:37.788] 
[2021-03-30 13:38:37.788] [09:33:39] [::ffff:172.23.48.1][75019c67][ExtensionHostConnection] <770> Extension Host Process exited with code: 1, signal: null.
[2021-03-30 13:38:37.788] Last EH closed, waiting before shutting down
[2021-03-30 13:38:37.788] [09:33:39] Last EH closed, waiting before shutting down
[2021-03-30 13:38:37.788] [09:33:39] [::ffff:172.23.48.1][9139e0fd][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2021-03-30 13:38:37.788] Last EH closed, shutting down
[2021-03-30 13:38:37.788] [09:38:39] Last EH closed, shutting down
[2021-03-30 13:38:37.797] [09:33:39] [::ffff:172.23.48.1][75019c67][ExtensionHostConnection] Unknown reconnection token.
[2021-03-30 13:38:37.798] VS Code Server for WSL closed unexpectedly.
[2021-03-30 13:38:37.798] C:\WINDOWS\System32\wsl.exe -d Ubuntu -e kill 151
[2021-03-30 13:38:37.880] WSL Daemon exited with code 0
```

**Comment by aeschli** [comment] 2021-06-09 14:09
@ahillikerMDSOL  Can you test if this is an installation issue?
- close all VSCode Windows
- in a WSL shell: `rm -r ..vscode-server/bin`
- reopen VSCode

marking as duplicate of #5047

**Closed by aeschli** 2021-06-09 14:09 UTC
Labels: needs-more-info, wsl
