### ISSUE TITLE
"Auto forward ports" setting is ignored (remote.autoForwardPorts)

### ISSUE THREAD

**Issue by qpwo** [microsoft/vscode-remote-release#5368] opened 2021-07-22 17:30 UTC
- VSCode Version: 1.58.2
- Local OS Version: macOS big sur 11.4
- Remote OS Version: Ubuntu 20.04.2 LTS
- Remote Extension/Connection Type: SSH
- Logs: Attached as file

Steps to Reproduce:

1. Set `"remote.autoForwardPorts": false` in your user, remote, or project settings.json, or in all of them.
2. Connect to a host using an IdentityFile with `ForwardAgent yes` in your `~/.ssh/config`
3. Run `npm start` from a react project
4. The port is still forwarded!

[logs.txt](https://github.com/microsoft/vscode-remote-release/files/6864128/logs.txt)

**Comment by bamurtaugh** [comment] 2021-07-30 00:15
cc @alexr00

**Comment by alexr00** [comment] 2021-07-30 08:40
Can you please share what your `npm start` script does?

**Comment by alexr00** [comment] 2021-07-30 14:40
Does it end up opening a browser?

**Comment by qpwo** [comment] 2021-07-30 15:39
Yes, but I have browser=none in my .env, so I think it's VSCode that's opening it.

**Comment by alexr00** [comment] 2021-08-02 09:40
There is no default in VS Code that would cause it to know to open a browser from `npm start`, so it sounds like your npm script is opening a browser. If you open a browser from within VS Code, a port could get forwarded. This is not controlled by `remote.autoForwardPorts` as that setting is specific to discovering ports by looking at your running processes or terminal output.  

Duplicate of https://github.com/microsoft/vscode/issues/129050

**Closed by alexr00** 2021-08-02 09:40 UTC
Labels: needs more info, ssh
