### ISSUE TITLE
setting default distro add green checkmark

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#1536] opened 2019-10-01 10:08 UTC
re #1511

* have ubuntu 16 (default) and ubuntu 18 installed
* connect to ubuntu 16 (it gets the green checkmark and the folder)
* make ubuntu 18 the default distro
* :bug: it now gets the green checkmark and folder even though I am still connected to 16

![Oct-01-2019 12-05-32](https://user-images.githubusercontent.com/1794099/65953381-1d2e6680-e444-11e9-9a66-74794b3edf05.gif)

**Comment by alexr00** [comment] 2019-10-01 14:03
@jrieken what version of Windows is this?

**Comment by alexr00** [comment] 2019-10-01 14:04
Possibly the same as https://github.com/microsoft/vscode-remote-release/issues/1546

**Comment by jrieken** [comment] 2019-10-01 14:41
Oh, I just updated to 1903, so it was the version before that....

**Comment by alexr00** [comment] 2019-10-01 14:57
Duplicate of #1546 then. 

It might be best to just not show the green check mark for versions without multi-distro support...

**Closed by alexr00** 2019-10-01 14:57 UTC
Labels: bug, wsl

**Comment by jrieken** [comment] 2019-10-01 15:00
Tho, I still see the issue with windows 1903

**Comment by alexr00** [comment] 2019-10-01 15:19
@jrieken I think this would be because the URIs in your recent history would still use an authority that just indicates that they belong to the default distro, not to a specific distro.
