### ISSUE TITLE
Unable to connect to wsl2 when using a custom kernel

### ISSUE THREAD

**Issue by WangYneos** [microsoft/vscode-remote-release#2631] opened 2020-03-29 04:36 UTC
when I try to connect to wsl2 with a custom kernel
(build with Microsoft/config-wsl )
```
Linux WangYneos-PC 5.5.0-WangYneos-WSL-Kernel #1 SMP Fri Mar 27 08:47:38 CST 2020 x86_64 GNU/Linux
```
 I always got an error
![图片](https://user-images.githubusercontent.com/42824603/77840383-6ecc6980-71b9-11ea-958c-0c9eaa1c5f85.png)

![图片](https://user-images.githubusercontent.com/42824603/77840371-52c8c800-71b9-11ea-92c4-f9f015e0a7a9.png)

but after I switch to default kernel ,it's working
![图片](https://user-images.githubusercontent.com/42824603/77840350-19905800-71b9-11ea-87e9-fc05b0094e2e.png)

it seems there is a problem with the WSL resolver. 
hope to know how to solve the problem

**Comment by WangYneos** [comment] 2020-03-29 04:40
full log
#5.5 custom kernel
```
[2020-03-29 04:31:32.455] Resolving wsl+Arch, resolveAttempt: 1
[2020-03-29 04:31:32.741] Starting VS Code Server inside WSL (Arch)
[2020-03-29 04:31:32.741] Extension version: 0.42.4, Windows build: 19592. Multi distro support: available. WSL path support: enabled
[2020-03-29 04:31:33.324] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Arch -e sh -c "[ -d ~/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-03-29 04:31:41.868] Probing result: found
[2020-03-29 04:31:41.868] Server install found in WSL
[2020-03-29 04:31:41.869] Launching C:\WINDOWS\System32\wsl.exe -d Arch sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 0ba0ca52957102ca3527cf479571617f0de6ed50 stable .vscode-server 0  ' in c:\Users\yneos\.vscode\extensions\ms-vscode-remote.remote-wsl-0.42.4, env: {
[2020-03-29 04:31:41.869]   "VSCODE_WSL_EXT_LOCATION": "c:\\Users\\yneos\\.vscode\\extensions\\ms-vscode-remote.remote-wsl-0.42.4",
[2020-03-29 04:31:41.869]   "WSLENV": "VSCODE_WSL_EXT_LOCATION/up"
[2020-03-29 04:31:41.869] }
[2020-03-29 04:31:42.182] Setting up server environment: Looking for /root/.vscode-server/server-env-setup. Not found.
[2020-03-29 04:31:42.182] WSL version: 5.5.0-WangYneos-WSL-Kernel Arch
[2020-03-29 04:31:42.182] Starting server: /root/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/server.sh  --port=0  
[2020-03-29 04:31:42.777] 
[2020-03-29 04:31:42.778] 
[2020-03-29 04:31:42.778] *
[2020-03-29 04:31:42.778] * Visual Studio Code Server
[2020-03-29 04:31:42.778] *
[2020-03-29 04:31:42.778] * Reminder: You may only use this software with Visual Studio family products,
[2020-03-29 04:31:42.778] * as described in the license https://aka.ms/vscode-remote/license
[2020-03-29 04:31:42.778] *
[2020-03-29 04:31:42.778] 
[2020-03-29 04:31:42.778] 
[2020-03-29 04:31:43.079] IP Address: 172.25.181.106
[2020-03-29 04:31:43.079] Extension host agent listening on 39383
[2020-03-29 04:31:43.079] 
[2020-03-29 04:31:43.079] 
[2020-03-29 04:31:43.079] [12:31:42] Extension host agent started.
[2020-03-29 04:31:43.080] WSL resolver response: 127.0.0.1:39383
[2020-03-29 04:31:43.080] To debug connection issues, open a local browser on http://127.0.0.1:39383/version
```
#4.19 kernel (default one)
```
[2020-03-29 04:39:04.578] Resolving wsl+Arch, resolveAttempt: 1
[2020-03-29 04:39:04.677] Starting VS Code Server inside WSL (Arch)
[2020-03-29 04:39:04.677] Extension version: 0.42.4, Windows build: 19592. Multi distro support: available. WSL path support: enabled
[2020-03-29 04:39:05.003] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Arch -e sh -c "[ -d ~/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-03-29 04:39:06.912] Setting up server environment: Looking for /root/.vscode-server/server-env-setup. Not found.
[2020-03-29 04:39:06.912] WSL version: 4.19.104-microsoft-standard Arch
[2020-03-29 04:39:06.912] WSL2-shell-PID: 12
[2020-03-29 04:39:06.912] Starting server: /root/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/server.sh  --port=0 --enable-remote-auto-shutdown 
[2020-03-29 04:39:07.816] 
[2020-03-29 04:39:07.816] 
[2020-03-29 04:39:07.816] *
[2020-03-29 04:39:07.816] * Visual Studio Code Server
[2020-03-29 04:39:07.816] *
[2020-03-29 04:39:07.816] * Reminder: You may only use this software with Visual Studio family products,
[2020-03-29 04:39:07.816] * as described in the license https://aka.ms/vscode-remote/license
[2020-03-29 04:39:07.816] *
[2020-03-29 04:39:07.816] 
[2020-03-29 04:39:07.816] 
[2020-03-29 04:39:08.119] IP Address: 172.25.187.34
[2020-03-29 04:39:08.119] Extension host agent listening on 42591
[2020-03-29 04:39:08.119] 
[2020-03-29 04:39:08.119] 
[2020-03-29 04:39:08.119] [12:39:07] Extension host agent started.
[2020-03-29 04:39:08.165] Pinging 172.25.187.34:42591...
[2020-03-29 04:39:08.188] 172.25.187.34:42591 responded
[2020-03-29 04:39:08.190] WSL resolver response: 172.25.187.34:42591
[2020-03-29 04:39:08.190] To debug connection issues, open a local browser on http://172.25.187.34:42591/version
```

**Comment by aeschli** [comment] 2020-11-09 21:40
The problem is that the kernel name is ` 5.5.0-WangYneos-WSL-Kernel` and not 4.19.104-microsoft-standard. We use the Kernel name to discover that we are in WSL and whether it is WSL1 or WSL2.

But in 0.44.4 I made a fix for this and now it would also work with your Kernel name.
The new heuristic is:
- it is WSL if we find the `WSL_DISTRO_NAME` env variable set of if `uname -r` matches version-Microsoft
- It is WSL1 `uname -r` matches version-Microsoft
- else it is WSL2


Please speak up if that is not the casse

**Closed by aeschli** 2020-11-09 21:40 UTC
Labels: wsl
