### ISSUE TITLE
Can no longer connect to remote server

### ISSUE THREAD

**Issue by hyang336** [microsoft/vscode-remote-release#6176] opened 2022-01-17 08:13 UTC
I have been using remote-SSH in VS code to connect to a linux server (Compute Canada) for a month. It worked great in the beginning, then about a week ago, it starts showing issues. Initially it just kept disconnecting randomly. Today I found out that the Explorer no longer shows files on the server and the connection was very slow to establish (I verified that the server is running properly by connecting with MobaXterm). I tried to reconnect through VS Code, and ended up not being to connect to the server at all. I tried all the solutions I could find: 

deleting .vscode-server on the host, 
deleting .wget-hsts on the host, 
run remote-SSH: Kill VS Code Server on Host, 
set "remote.SSH.useLocalServer": false, 
set "remote.SSH.useFlock": true, 
set "remote.SSH.connectTimeout": 60 

None of these worked. It either keeps asking for password over and over again, or just hang, which is the current behavior I ended up with.
My current settings.json:

{
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
    "remote.SSH.remotePlatform": {
        "graham.computecanada.ca": "linux"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "jupyter.askForKernelRestart": false,
    "remote.SSH.useLocalServer": true,
    "remote.SSH.connectTimeout": 60
}

- VSCode Version: 1.63
- Local OS Version: Windows 10 Home 20H2
- Remote OS Version: Gentoo Base System release 2.6
- Remote Extension/Connection Type: SSH
- Logs:
[02:56:57.364] Log Level: 2
[02:56:57.368] remote-ssh@0.70.0
[02:56:57.368] win32 x64
[02:56:57.369] SSH Resolver called for "ssh-remote+graham.computecanada.ca", attempt 1
[02:56:57.369] "remote.SSH.useLocalServer": true
[02:56:57.369] "remote.SSH.path": undefined
[02:56:57.370] "remote.SSH.configFile": undefined
[02:56:57.370] "remote.SSH.useFlock": true
[02:56:57.370] "remote.SSH.lockfilesInTmp": false
[02:56:57.370] "remote.SSH.localServerDownload": auto
[02:56:57.370] "remote.SSH.remoteServerListenOnSocket": false
[02:56:57.370] "remote.SSH.showLoginTerminal": false
[02:56:57.370] "remote.SSH.defaultExtensions": []
[02:56:57.370] "remote.SSH.loglevel": 2
[02:56:57.371] "remote.SSH.serverPickPortsFromRange": {}
[02:56:57.371] "remote.SSH.enableDynamicForwarding": true
[02:56:57.371] "remote.SSH.serverInstallPath": {}
[02:56:57.374] SSH Resolver called for host: graham.computecanada.ca
[02:56:57.374] Setting up SSH remote "graham.computecanada.ca"
[02:56:57.376] Acquiring local install lock: C:\Users\haozi\AppData\Local\Temp\vscode-remote-ssh-ceafebc4-install.lock
[02:56:57.387] Looking for existing server data file at c:\Users\haozi\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-ceafebc4-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0\data.json
[02:56:57.388] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[02:56:57.390] Install and start server if needed
[02:56:57.392] Checking ssh with "ssh -V"
[02:56:57.415] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[02:56:57.416] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[02:56:57.435] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[02:56:57.437] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[02:56:57.552] > OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021

[02:56:57.555] Using SSH config file "C:\Users\haozi\.ssh\config"
[02:56:57.555] askpass server listening on \\.\pipe\vscode-ssh-askpass-e7ff0daa1dc877cd15dbde502223a92d1bbc7a01-sock
[02:56:57.556] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-de807039e64c7981d65637dd3c419f6c7f5d19f0-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","64580","-F","C:\\Users\\haozi\\.ssh\\config","graham.computecanada.ca","bash"],"dataFilePath":"c:\\Users\\haozi\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-ceafebc4-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0\\data.json"}
[02:56:57.556] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\haozi\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.70.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\haozi\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\haozi\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.70.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-e7ff0daa1dc877cd15dbde502223a92d1bbc7a01-sock"}
[02:56:57.561] Spawned 15064
[02:56:57.631] > local-server-1> Spawned ssh, pid=19868
[02:56:57.650] stderr> OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021
[02:56:57.992] stderr> debug1: Server host key: ssh-ed25519 SHA256:mf1jJ3ndpXhpo0k38xVxjH8Kjtq3o1+ZtTVbeM0xeCk
[02:56:58.618] Got askpass request: {"request":"(hyang336@graham.computecanada.ca) Password: "}
[02:56:58.618] Showing password prompt
[02:56:58.618] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-a8effe5911387254c064f11df97da7a9c6c008cf-sock
[02:56:58.618] Writing password prompt to globalState
[02:57:11.604] Got password response
[02:57:11.604] Interactor gave response: ************
[02:57:11.605] Cleaning up other-window auth server
[02:57:11.798] stderr> Authenticated to graham.computecanada.ca ([199.241.166.3]:22).
[02:57:13.919] > ready: 1626109214fc
[02:57:13.978] > Linux 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021
[02:57:13.979] Platform: linux
[02:57:14.070] > 1626109214fc: running
[02:57:14.303] > Acquiring lock on /home/hyang336/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/vscode-remote-lock.hyang336.899d46d82c4c95423fb7e10e68eba52050e30ba3
[02:57:14.340] > Installing to /home/hyang336/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3...
[02:57:14.349] > 1626109214fc%%1%%
[02:57:14.384] > Downloading with wget
[02:57:15.482] > Download complete
[02:57:15.504] > 1626109214fc%%2%%
> tar --version:
[02:57:15.536] > tar (GNU tar) 1.32
> Copyright (C) 2019 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[02:57:21.426] > Checking /home/hyang336/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba3.log and /home/hyang336/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba3.pid for a running server

Steps to Reproduce:

1. attempt remote-ssh
2. type in password
3. I have deleted/renamed the .vscode-server folder either through another program that does allow me to connect to the server or using Remote-SSH to delete it for more than 10 times, together with Kill VS Code Server on Host. So the suggestion in #2518 did not work.

Thanks,
HY

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by hyang336** [comment] 2022-01-17 08:21
I also noticed that the lock number is always the same no matter how many times I delete it, how is this number generated?

**Comment by bamurtaugh** [comment] 2022-01-26 01:21
Thanks for reporting. Are you able to SSH into the server successfully from a regular terminal (i.e. not using Remote-SSH)?

**Comment by bamurtaugh** [comment] 2022-01-26 18:01
Thanks for confirming @hyang336! Closing as the issue is resolved now.

**Closed by bamurtaugh** 2022-01-26 18:01 UTC
Labels: ssh
