### ISSUE TITLE
Open ssh repository in container fails with host key verification

### ISSUE THREAD

**Issue by tarioch** [microsoft/vscode-remote-release#2087] opened 2019-12-23 22:38 UTC
- VSCode Version: 1.41.1
- Local OS Version: Windows 10
- Remote Extension/Connection Type: Docker
Steps to Reproduce:

1. run Remote-Containers: Open Repository in Container...
2. specify an ssh git repository
3. the container that tries to git clone it fails with host key verification error

**Comment by lem8r** [comment] 2020-01-05 13:58
Similar issue on Linux.
When I reopen repo in devcontainer using docker-compose I can't use git anymore. It says 
**Git: Host Verification failed**.

But if I run `git fetch` in terminal and answer `yes` to
```bash
The authenticity of host 'bitbucket.org (18.205.93.2)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)?
```
I can use all git features again.

**Comment by chrmarti** [comment] 2020-01-06 11:18
/duplicate #1578

@tarioch Duplicate of #1578.

@lem8r That sounds like a limitation of the built-in Git support. Maybe that could show a better error message.

**Closed** 2020-01-06 11:18 UTC
Labels: *duplicate

**Comment by lem8r** [comment] 2020-01-06 13:34
> @lem8r That sounds like a limitation of the built-in Git support. Maybe that could show a better error message.

I found a solution of my problem by adding
```Dockerfile
RUN echo "StrictHostKeyChecking no" >> /home/vscode/.ssh/config
```
to Dockerfile of my devcontainer image
