### ISSUE TITLE
`remote-cli` not being added to PATH with `"terminal.integrated.inheritEnv": false`

### ISSUE THREAD

**Issue by pmagwene** [microsoft/vscode-remote-release#6289] opened 2022-02-06 01:35 UTC
Note: This bug was not an issue when using VSCode 1.63.2; so something about the 1.64.0 updates seems to be the source of the problem.

- VSCode Version: 1.64.0
- Local OS Version: MacOS 10.15.7
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Create a connection to remote host via SSH
2. Try to run `code` from embedded terminal in remote VS Code window
3.  `code` not on PATH
4.  `code` is found in `~/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/remote-cli`
5.  `~/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin` is being automatically pre-pended to PATH but the location of `code` is not
# Workaround

1. Copy `code` to `~/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin`
2. Edit `code` so line that starts with `ROOT` reads:
    ```
    ROOT=$(dirname "$(dirname "$0")")
    ```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by yongzhang** [comment] 2022-02-07 01:59
Same issue happens today.

**Comment by raidenz** [comment] 2022-02-07 13:26
have the same problem with WSL

workaround
```
# C:\Users\{username}\.vscode\extensions\ms-vscode-remote.remote-wsl-0.63.13\scripts\wslCode.sh

# update last line
"$VSCODE_REMOTE_BIN/$COMMIT/bin/remote-cli/$APP_NAME" "$@"
```

**Comment by aeschli** [comment] 2022-02-07 20:23
The issue should only exist with external terminals in WSL if the Remote-WSL is not yet updated to 0.64.2.

The integrated terminal in a remote window (SSH, Containers, WSL) will get the new path (bin/remote-cli) from the parent terminal process:

When I try this in SSH, I see this:
![image](https://user-images.githubusercontent.com/6461412/152865505-63c39afd-e234-4bdf-ae35-497de5289946.png)

Interestingly I also see the `bin/5554b12acf27056905806867f251c859323ff7e9/bin` path. I wonder who sets it.
@roblourens @tanhakabir 
Could it be that the terminal session is restored and doesn't have the new path? @Tyriar

**Comment by Tyriar** [comment] 2022-02-07 20:36
@aeschli yes restored terminals could cause this if you set `env` internally as we track the environment variables that are explicitly set and restore with them.

**Comment by aeschli** [comment] 2022-02-07 21:01
Is there a way that users can reset the terminal state?

**Comment by Tyriar** [comment] 2022-02-07 22:07
@aeschli only way is to close it and reopen another one, didn't consider this edge case when we built the feature and not sure there's anything we can do about it.

**Comment by aeschli** [comment] 2022-02-08 08:05
@Tyriar When restoring, can you check that the restored PATH contains all the PATH entries from the parent process? There could be other path entries that were added recently e.g. by the user in the OS that might be of interest.

**Comment by pmagwene** [comment] 2022-02-08 16:44
Original issue reporter here.  

I don't think the issue is only with restored terminals as I've tried the recommendation here:

https://github.com/microsoft/vscode/issues/142321#issuecomment-1032382066

And `remote-cli` is still not being added to my path. 

Again, my setup is:

VSCode Version: 1.64.0
Local OS Version: MacOS 10.15.7
Remote OS Version: Ubuntu 20.04
Remote Extension/Connection Type: SSH

**Comment by aeschli** [comment] 2022-02-08 16:51
@pmagwene What is the PATH in your remote integrated terminal then? Can you add a screenshot? Can it be that your shell startup scripts replace the PATH?

**Comment by pmagwene** [comment] 2022-02-08 16:55
Here's my `PATH`. Note that VS Code is injecting it's appropriate `bin` into the PATH, just not the `remote-cli` subdirectory.

```
$ env | grep PATH
PATH=/home/pm21/miniconda3/bin:/home/pm21/miniconda3/condabin:/home/pm21/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin:/home/pm21/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by roblourens** [comment] 2022-02-08 19:22
The extra `/bin` path comes from the Remote-SSH installer. That isn't needed now that some code in vscode adds the correct remote-cli path. I will remove our path tweak.

**Comment by aeschli** [comment] 2022-02-08 20:10
@morkovka1337 I think the problem is that you have "terminal.integrated.inheritEnv"; false configured. That doesn't go well together with the code command in the integrated terminal in remote windows. Can you set it to true?

**Comment by Tyriar** [comment] 2022-02-08 22:27
I guess the expectation here is for remote to add the bin dir even when `inheritEnv` is false, just not building the rest of the enviornment?

**Comment by aeschli** [comment] 2022-02-09 08:05
> I guess the expectation here is for remote to add the bin dir even when `inheritEnv` is false, just not building the rest of the enviornment?

Yes, our path should always be added.

**Comment by Tyriar** [comment] 2022-02-09 15:36
@aeschli yes that's right, `useShellEnvironment` means use `getResolvedShellEnv`, otherwise derive the environment from the parent process of VS Code (to align with how terminals typically work).

**Comment by aeschli** [comment] 2022-02-09 15:53
I suggest we fix it for March given that there's a workaround

**Closed** 2022-02-16 13:16 UTC
Labels: remote
