### ISSUE TITLE
serverReadyAction (and by extenstion vscode.env.openExternal) should forward 0.0.0.0:port as well as localhost:port - and reuse the input port unless already in use

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1115] opened 2019-08-07 00:52 UTC
Differences between how ports are published via the Docker CLI/Docker Compose and our ad-hoc forwarding behavior currently cause a situation where running applications inside the container will work in one situation but not the other. Here's the challenge:

1. "appPort" and Docker Compose's "port" setting **publish** the port - the port is not forwarded as much as made available externally. In these cases, a running application needs to bet setup to listen to all interfaces (`0.0.0.0`). This is discussed in #1009 related to Flask and .NET Core
2.  Unfortunately, if you use a `launch.json` with a `serverReadyAction`, `0.0.0.0` does not work. This would happen with a config that looked like this:
     ```json
    "serverReadyAction": {
        "pattern": "Now listening on: (.*)\n",
        "uriFormat": "%s",
        "action":"openExternally"
    }
    ```
3. Finally, if extensions are parsing output to do something like this on their own with `vscode.env.openExternal`, it would not work.

Unfortunately if you use `127.0.0.1` or `locahost` instead, 2-3 above work, but 1 does not.

In addition, the forwarding goes to a random port instead of the input port - which means if you close the browser you can't get back to it.

//cc: @mjbvz @kieferrm

**Comment by damccull** [comment] 2019-09-05 23:16
I'm experiencing this issue (#1348, closed because it's a duplicate of this) and, while it's not a deal-breaker because the app becomes available on both the random port and the published port, it's undesirable behavior and confusing. Would like to see it fixed.

**Comment by weinand** [comment] 2019-09-18 11:19
Analysis from the "serverReadyAction" perspective:

Assuming a server program that emits a "Now listening ..." message with code like this:
```ts
  const HOST = '0.0.0.0';
  const PORT = '3000';
  // ...
  console.log(`Now listening on http://${HOST}:${PORT}`);
```

then the following "serverReadyAction" configuration could be used:
```json
"serverReadyAction":{
	"action": "openExternally",
	"pattern": "Now listening on (.*)"
}
```

This works fine in the local case: 
- the following dialog shows up:
   ![2019-09-18_13-02-33](https://user-images.githubusercontent.com/1898161/65143170-9aa1b200-da14-11e9-9876-524d53058a30.png)
- Pressing "Open Link" opens the "http://0.0.0.0:3000" link in a local browser which sucessfully loads the link and hits the breakpoint.

In the remote case (SSH), the only difference is that the local browser cannot load the "http://0.0.0.0:3000" link because the server is running remotely and no port-forwarding has been established.

This can easily be worked around by only detecting the port and not the full url with the "0.0.0.0" hostname:
```json
"serverReadyAction":{
	"action": "openExternally",
	"pattern": "Now listening on .*:([0-9]+)"
}
```

With this launch config the resulting url becomes "http://localhost:3000" which is rewritten to some random port "http://127.0.0.1:55551".

**Comment by alexandrudima** [comment] 2019-09-30 14:22
Just pushed changes for the last two things

**Closed by alexandrudima** 2019-09-30 14:22 UTC
Labels: containers, feature-request

**Comment by alexandrudima** [comment] 2019-10-07 07:28
@Chuxel Could you please verify that this works?

**Comment by alexandrudima** [comment] 2019-10-07 10:46
Verification steps:
* start docker
* clone `https://github.com/Microsoft/vscode-remote-try-node`
* when prompted, reopen the folder in a container
* edit `server.js`:
```js

```

**Comment by alexr00** [comment] 2019-10-07 11:57
It worked great, but in my browser the opened link was actually `http://127.0.0.1:60793/`. Not sure if that matters.
