### ISSUE TITLE
While connect from another pc at same user get the same source ip

### ISSUE THREAD

**Issue by xahys** [microsoft/vscode-remote-release#7544] opened 2022-11-18 06:25 UTC
- VSCode Version: v0.76.1
- Local OS Version: Windows 10
- Remote OS Version: Red Hat Enterprise Linux Server Release 7.9
- Remote Extension/Connection Type: SSH
- Logs: 

Nov 18 08:43:36 myserver devuser: SESSION = 1000210, SOURCE = 192.168.1.100, ACCOUNT = devuser, CWD = /, CMD = pwd

Steps to Reproduce:

0. On a remote server need user with authorized_keys with 2+ ssh_keys (count users connect = ssh keys)
1. From 1 PC (source example: 192.168.1.100) : Connect to host as any user, use "Remote Explorer", and connect to host via "Connect to host in new window" (Connect without password, only ssh-keys rsa)
2. After connect, execute command  "tail -f /var/log/secure"
3. From 2 PC (source example: 192.168.1.136), with different ssh-key connect as same user, use rules connection as 1 PC (different in ssh-key only and source address connect)
4. From 2 PC execute command "pwd"
5. From 1 PC get log format as:
Nov 18 08:43:36 myserver devuser: SESSION = 1000210, SOURCE = 192.168.1.100, ACCOUNT = devuser, CWD = /, CMD = pwd

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by eleanorjboyd** [comment] 2022-11-18 16:32
Hello! To clarify the problem, you are connecting twice to the the same remote and what is the issue going wrong? You are getting the same remote IP address for both connections? Does that include the port address?

**Comment by xahys** [comment] 2022-11-18 18:42
Hi. Yes

**Comment by eleanorjboyd** [comment] 2022-11-21 19:27
Hello! This is actually the expected behavior to be on the same VS Code server that was started by the first PC which is why you are seeing the the same IP address for the second connection.

**Comment by eleanorjboyd** [comment] 2022-11-21 19:27
closing since it is expected behavior, thanks!

**Closed by eleanorjboyd** 2022-11-21 19:27 UTC
Labels: ssh, info-needed
