### ISSUE TITLE
Code Server returning error Your platform or architecture is not supported by our forwarding tool. You may be able to run with `--no-forward

### ISSUE THREAD

**Issue by ricardosantos9521** [microsoft/vscode-remote-release#6949] opened 2022-07-14 18:29 UTC
- VSCode Version: VS Code Server dev
- Local OS Version: 
- - PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

Steps to Reproduce:

1. code-serve in a raspberrypi4 
2.
![image](https://user-images.githubusercontent.com/20097801/179055749-0dd0bd23-bf5a-4a06-866f-f9805afdd2a8.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment] 2022-07-14 18:47
Currently our port forwarding service doesn't support ARM linux machines. We have an issue internally tracking this and will hopefully have it resolved in the near future.

**Comment by Blitz-Cloud** [comment] 2022-08-20 20:49
Same problem here

**Comment by connor4312** [comment] 2022-08-20 21:44
This'll actually be fixed in a release on Monday, as I've completed the work to remove dependence on a separate external tool and integrated forwarding natively in our Rust code (functional duplicate of https://github.com/microsoft/vscode-cli/issues/434)

**Closed by connor4312** 2022-08-20 21:44 UTC
Labels: upstream, code-server

**Comment by techiezia** [comment] 2022-08-21 15:28
Hi @connor4312 seem like the link (https://github.com/microsoft/vscode-cli/issues/434) is broken or repository is not opensource yet.

**Comment by connor4312** [comment] 2022-08-23 22:52
Apologies, that repo is not open source at the moment...

However, this has now been released! This should now work on Raspberry Pi's using 64 bit images (compatible with models 3B and onwards)

**Comment by tlockney** [comment] 2022-09-06 04:29
It seems the installer is still installing the older version (`VS Code Server 20220823.4`) and I get a failure when trying to update with that version installed:

```
[2022-09-05 21:28:39] info Update to 20220903.2 (UTC 1662182760) available
[2022-09-05 21:28:40] error error requesting https://vscodeserverlauncher.blob.core.windows.net/builds/20220903.2/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu: 404 <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:4f348f92-601e-003e-5da9-c17f2d000000
Time:2022-09-06T04:28:40.0049636Z</Message></Error>
```

**Comment by connor4312** [comment] 2022-09-06 15:11
Yes, apologies. I've attempted to get a musl build going which caused some issues. I will get a new deploy out today.
