### ISSUE TITLE
Opening folder cloned in Windows in a container (or WSL) shows all files modified 

### ISSUE THREAD

**Issue by drcrook1** [microsoft/vscode-remote-release#302] opened 2019-05-13 22:11 UTC
Host Machine is windows 10.  Container is debian based.  I suspect it has to do with the line endings that change in every file.  In my case this was ~4,500 files and trying to sort through that change set to find and undo various things in the vscode git extension or even command line to sort through the nonsense is just out of hand when my repository is that large.

I ended up accidentally deleting all of my in progress changes to get back to ground zero for this.  I would suspect I am not unique here.

**Comment by drcrook1** [comment] 2019-05-13 23:50
Captured an image of the latest of it doing it just to show some evidence.

![image](https://user-images.githubusercontent.com/6099287/57661309-45fab000-75b8-11e9-891b-d5165d9a3c44.png)

**Comment by Chuxel** [comment] 2019-05-14 00:48
@drcrook1 This is due to git's internal handling of line feeds and the "auto CRLF" feature. We mention this in the install instructions for both containers and WSL since there's nothing VS Code inherently can do about it.  There's a number of threads about whether the fact that git auto-enables CRLF conversion on Windows by defaults is good or bad, but in this case, it causes files to appear to be modified.  (The repo will have everything as "LF" and the Linux side expects "LF", but your filesystem will have everything "CRLF" if you cloned using Windows. The reverse can technically also happen.)  You can either disable auto CRLF and re-clone to get everything to be pulled down as LF, or the more bullet-proof way is to add a `.gitattributes` file that specifies your line endings.  Once that is checked in, others will not see the problem.

More here: https://code.visualstudio.com/docs/remote/troubleshooting#_resolving-git-line-ending-issues-in-containers-resulting-in-many-modified-files

**Comment by chrmarti** [comment] 2019-05-14 17:39
@Chuxel Have you tried configuring the container's git to ignore line endings? E.g.: https://stackoverflow.com/a/29518701/7857763 (If that works we could try to automatically set it.)

**Comment by Chuxel** [comment] 2019-05-14 19:37
@chrmarti Yeah that's an alternative to `* text=auto eol=lf` in the repo. The challenge is that we'd be messing with the default in the container without people knowing.  I think the problem is that if you did change the line endings intentionally, that would be ignored and you wouldn't know why.  It's even less clear cut for WSL which has the same problem.

We might want to instead detect if someone is in a situation where this will be a problem and offer to resolve by creating or modifying a `.gitattributes` file at the repo root.  That way it can get checked in and the next person doesn't hit the problem.  This would also raise visibility to the fact that the default changed so there's no expectation mismatch.

**Comment by chrmarti** [comment] 2019-05-15 15:26
We could offer to add it (`*        -crlf`) to `$GIT_DIR/info/attributes`. That way it will stay across container-rebuilds and it will not "force" the user to check something in. This would also work for the repositories we ship the configuration for with vscode-dev-containers.

**Comment by Chuxel** [comment] 2019-05-15 16:57
@chrmarti Yeah I think that would work as well. It would make sense to do this for WSL as well.

**Comment by chrmarti** [comment] 2020-10-13 14:50
@Chuxel I haven't heard anything about this issue recently. How was this resolved or is it still an issue?

**Closed** 2020-10-16 10:07 UTC
Labels: *out-of-scope, containers, feature-request, windows, wsl
