### ISSUE TITLE
cannot set environment variables

### ISSUE THREAD

**Issue by hinayuki64** [microsoft/vscode-remote-release#2972] opened 2020-05-10 18:41 UTC
Issue Type: <b>Bug</b>

I now use Ubuntu WSL(20.04).

I set env variables , using a command "export PATH="$PATH:(path which I want to add)"" on the original WSL bash (not in vscode).
Of course, in the original WSL, the variables are added (checked by "echo $PATH")
However, in the bash terminal in vscode, they are still not added.

Extension version: 0.44.2
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (0.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.93GB (0.64GB free)|
|VM|0%|
</details>

**Comment by Chuxel** [comment] 2020-06-09 01:07
I believe this is a duplicate of #1700. Environment variables of the currently WSL open shell are not transferred when typing `code .`. These need to be added to your `.bashrc` or equivalent for your shell.

**Closed by Chuxel** 2020-06-09 01:07 UTC
Labels: *duplicate
