### ISSUE TITLE
Container: "Unable to watch for file changes in this large workspace"

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-remote-release#4978] opened 2021-04-28 18:19 UTC
Reopening #3804, it's started happening again on recent versions of VSCode

- VSCode Version: 1.55.2, probably 1.54+?
- Local OS Version: MacOS 11.3
- Remote OS Version: Gentoo container on Ubuntu 18.04 host
- Remote Extension/Connection Type: Container on remote host
- Logs:

Steps to Reproduce:

I'm connecting to a Docker container running on a remote host through a VPN.

1. Connect to VPN
2. Open workspace/folder in remote container
3. Force/dirty quit VSCode or kill the VPN while VSCode is running
4. See "watcher limit" error next time I connect to the container
5. Disconnect from the container (gracefully skill all VSCode instances)
6. See all these watchers when I go into the container manually
```
danf@depot ~ $ cat /proc/sys/fs/inotify/max_user_watches
524288
danf@depot /depot $ sudo ps -aux | grep watch
danf  2004  0.0  0.1 856760 39888 ?        Sl   Apr23   0:02 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
danf  3608  0.0  0.0   8728  3288 pts/1    Ss+  Apr22   0:00 /bin/bash /depot/build/config/vscode/vsbash -c npm run watch
danf  3611  0.0  0.1 622764 52236 pts/1    Sl+  Apr22   2:11 npm run watch
danf  3623  0.3  0.5 705860 172540 pts/1   Sl+  Apr22  26:51 node /depot/vscode-shell-command/node_modules/.bin/tsc -watch -p ./
danf  5885  0.0  0.1 857012 38816 ?        Sl   Apr26   0:01 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
danf  6223  0.4  0.9 1149540 320156 ?      Sl   Apr27   7:05 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
danf  6584  0.0  0.1 856812 38492 ?        Sl   Apr22   0:03 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
danf 11549  0.0  0.2 906932 70860 ?        Sl   Apr27   0:04 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
danf 13898  0.2  0.9 1149688 321452 ?      Sl   Apr26   7:22 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
danf 24700  0.3  0.9 1149348 319876 ?      Sl   Apr26   9:04 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
danf 28203  6.5  0.2 907620 70884 ?        Sl   10:59   0:03 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
danf 28984  0.0  0.0   7988  2192 pts/2    S+   10:59   0:00 grep --colour=auto watch
danf 32701  0.4  1.0 1170548 341544 ?      Sl   Apr27   6:44 /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/danf/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/bootstrap-fork --type=watcherService
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by dfarley1** [comment] 2021-08-04 20:47
Bumping this, it's still happening on VSCode 1.58. One zombie process was watching ~90K files!

**Comment by aeschli** [comment] 2022-12-15 13:36
Closing as I'm not able to reproduce

**Closed by aeschli** 2022-12-15 13:36 UTC
Labels: remote
