### ISSUE TITLE
Remote-ssh can not connect unless delete .vscode-server folder on the remote every time using ssh.

### ISSUE THREAD

**Issue by sisrfeng** [microsoft/vscode-remote-release#2828] opened 2020-04-25 01:57 UTC
- VSCode Version: the latest 
- Local OS Version: win10
- Remote OS Version: ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/53520949/80268538-790b5600-86da-11ea-8aee-0be7c475031f.png)
After retry for many times:
![image](https://user-images.githubusercontent.com/53520949/80268568-ac4de500-86da-11ea-89be-b977e33df122.png)

```
[09:49:50.763] > Found running server...
> 
> *
[09:49:50.768] > 
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 38855 with wget
> failed: Connection refused.
> e009e0418a08##28##
[09:49:50.768] Received install output: e009e0418a08##28##
[09:49:50.768] Server status check failed - waiting and retrying
[09:49:50.855] > 
> 
[09:49:51.160] "install" terminal command done
[09:49:51.160] Install terminal quit with output: 
[09:49:51.771] Running script with connection command: ssh -T -D 56396 8xp bash
[09:49:51.773] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:49:51.858] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[09:49:51.858] Got some output, clearing connection timeout
[09:49:51.950] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:49:52.339] > 
> 
> 
> 
> 
> 
> 
> 
> 
[09:49:52.367] > e009e0418a08: running
> 
[09:49:52.437] > Acquiring lock on /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844119c
> e9485abfe8aa9076ec76b5300ddd
> 
[09:49:52.477] > \ln /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844119ce9485abfe8aa90
> 76ec76b5300ddd.target /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844
> 119ce9485abfe8aa9076ec76b5300ddd
> 
[09:49:52.491] > Found existing installation at /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd...
> 
[09:49:52.501] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
[09:49:52.509] > 
> *
> 
> Checking server status on port 38855 with wget
> failed: Connection refused.
> e009e0418a08##28##
[09:49:52.510] Received install output: e009e0418a08##28##
[09:49:52.510] Server status check failed - waiting and retrying
[09:49:52.520] > 
> 
[09:49:52.821] "install" terminal command done
[09:49:52.821] Install terminal quit with output: 
[09:49:53.515] Running script with connection command: ssh -T -D 56396 8xp bash
[09:49:53.519] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:49:53.626] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[09:49:53.627] Got some output, clearing connection timeout
[09:49:53.698] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:49:54.101] > 
> 
> 
> 
> 
> 
> 
> 
> 
[09:49:54.154] > e009e0418a08: running
> 
[09:49:54.221] > Acquiring lock on /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844119c
> e9485abfe8aa9076ec76b5300ddd
> 
[09:49:54.272] > \ln /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844119ce9485abfe8aa90
> 76ec76b5300ddd.target /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844
> 119ce9485abfe8aa9076ec76b5300ddd
> 
[09:49:54.285] > Found existing installation at /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd...
> 
[09:49:54.299] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
[09:49:54.305] > 
> 
> Checking server status on port 38855 with wget
> failed: Connection refused.
> e009e0418a08##28##
> 
[09:49:54.305] Received install output: e009e0418a08##28##
[09:49:54.305] Server status check failed - waiting and retrying
[09:49:54.618] "install" terminal command done
[09:49:54.619] Install terminal quit with output: 
[09:49:55.309] Running script with connection command: ssh -T -D 56396 8xp bash
[09:49:55.311] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:49:55.435] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[09:49:55.435] Got some output, clearing connection timeout
[09:49:55.490] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:49:55.908] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:49:55.978] > e009e0418a08: running
> 
[09:49:56.060] > Acquiring lock on /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844119c
> e9485abfe8aa9076ec76b5300ddd
> 
[09:49:56.104] > \ln /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844119ce9485abfe8aa90
> 76ec76b5300ddd.target /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.lwf.ff915844
> 119ce9485abfe8aa9076ec76b5300ddd
> Found existing installation at /home/lwf/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd...
> 
[09:49:56.112] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[09:49:56.121] > Checking server status on port 38855 with wget
> failed: Connection refused.
> e009e0418a08##28##
> 
[09:49:56.121] Received install output: e009e0418a08##28##
[09:49:56.121] Server status check failed - waiting and retrying
[09:49:56.446] "install" terminal command done
[09:49:56.447] Install terminal quit with output: 
[09:49:57.122] Resolver error: 
[09:49:57.125] ------




[09:49:57.942] Unhandled rejection: Error (FileSystemError): 
	at _handleError (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:618:364)
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by sisrfeng** [comment] 2020-04-25 02:00
the log on the remote

Visual Studio Code Server
Reminder: You may only use this software with Visual Studio family products,
as described in the license https://aka.ms/vscode-remote/license
[16:08:36] Extension host agent started.
[16:08:36] [127.0.0.1][0388d74d][ManagementConnection] New connection established.
[16:08:36] [127.0.0.1][013c0641][ExtensionHostConnection] New connection established.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[16:08:37] [127.0.0.1][013c0641][ExtensionHostConnection] <25477> Launched Extension Host Process.
[16:08:53] [127.0.0.1][0388d74d][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[16:08:54] [127.0.0.1][013c0641][ExtensionHostConnection] <25477> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[16:08:54] Last EH closed, waiting before shutting down
Last EH closed, shutting down
[16:13:54] Last EH closed, shutting down

**Comment by sisrfeng** [comment] 2020-04-25 02:01
My temporary solution:
ssh to the remote with mobaxterm and delete .vscode-server

**Comment by sisrfeng** [comment] 2020-04-25 02:04
The problem maybe happens after I tried to use zsh as my default shell on the remote but lately switch back to bash.
Many thanks!

**Comment by sisrfeng** [comment] 2020-04-29 02:01
Do I need to provide any other information？ thanks!

**Comment by sisrfeng** [comment] 2020-05-03 01:26
My temporary solution:
ssh to the remote with mobaxterm and delete a log file under .vscode-server every time.
The log file's name looks like.ff9158119ce9485abfeaa90776b5300ddd.log
But it is not a  good solution.
Many thanks!

**Comment by davidmcnamee** [comment] 2020-06-04 18:46
My friend has the same problem from his Windows 10 laptop connecting to the university's linux server. Nothing abnormal shows up in the server logs, and the client's only _error_ message is "Connection refused."

It's super weird that deleting the `.log` file is what fixes the problem; could this be a bug in the latest release?

**Comment by sisrfeng** [comment] 2020-06-07 01:39
> My friend has the same problem from his Windows 10 laptop connecting to the university's linux server. Nothing abnormal shows up in the server logs, and the client's only _error_ message is "Connection refused."
> 
> It's super weird that deleting the `.log` file is what fixes the problem; could this be a bug in the latest release?

how did you find deleting the .log file is what fixes the problem? 
I've forgotten how I find it.

**Comment by mcswell** [comment] 2020-06-23 20:19
Same here: I was able to connect VSC to a remote and use it to edit remote files, but a VSC-internal terminal would just hang trying to start.  An external terminal was fine (I'm using WSL in the Ms Terminal).  From the external terminal, I deleted all my *.log files, and then magic: the VSC terminal worked again.  Bizarre.

I was hoping this magic might also solve this problem:
    https://github.com/microsoft/vscode-remote-release/issues/3139
But no such luck...

**Comment by mcswell** [comment] 2020-06-24 16:45
FWIW, today I tried deleting subsets of the log files on the remote, hoping to see which one(s) prevented login.  When I deleted this one:
    ~/.vscode-server/.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.log
VSC was suddenly able to log in.  

I can't rule out that some of the other files might have been problematic as well, though, since I had deleted them previously (but as I say, I couldn't get in until I deleted this last one).  Specifically, I had previously done:
    find .vscode-server/ -name "*Authentication.log" -exec rm {} \;
    find .vscode-server/ -name "*exthost*.log" -exec rm {} \;

**Comment by mcswell** [comment] 2020-06-25 14:15
This morning I confirmed that deleting that one file (.vscode-server/.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.log) is necessary and sufficient to allow login.  

This is a reproducible error on my system, in the sense that it happens every day.  However, closing VSC and immediately re-opening it does NOT trigger the error.  Not sure what's going on there...

**Comment by david-leon** [comment] 2020-07-03 01:30
> 
> 
> This morning I confirmed that deleting that one file (.vscode-server/.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.log) is necessary and sufficient to allow login.
> 
> This is a reproducible error on my system, in the sense that it happens every day. However, closing VSC and immediately re-opening it does NOT trigger the error. Not sure what's going on there... I notice that on 2 May, @sisrfeng had changed the title of this issue from "...on the remote every day" to "...on the remote every time". Seems like the former might be correct, although that doesn't make much sense.

Same symptom here, I'll try deleting the log file later.

**Comment by ivanthewebber** [comment] 2020-07-06 16:04
Deleting the log worked like a charm for me

**Comment by tejasa97** [comment] 2020-07-12 09:12
@ivanthewebber Did the exact same thing, performed a `rm -rf ~/.vscode-server` and it seems OK for now

**Comment by mcswell** [comment] 2020-07-14 14:32
I have not had to rm the log file for several days now, possibly since v1.47.0.  I didn't see anything in the change logs about fixing this, nor do I see anything here.  Was it fixed with the new version?  or have I just been lucky for a few days?

**Comment by Chuxel** [comment] 2020-07-14 14:54
//cc: @roblourens

**Comment by roblourens** [comment] 2020-07-15 23:38
It seems like the server is still running, but it is in a bad state where it doesn't want to accept a new connection -

> failed: Connection refused.

We don't kill the server in this case, but you are forcing this by removing the file that tells us how to contact the server. A cleaner workaround is to run the command "Kill VS Code Server".

I have no clue why this is happening but I wonder if someone could try this to maybe get more info.

- Encounter this issue where you can't connect
- Check the log for `Checking server status on port XYZ with wget` for some port number XYZ
- Connect with an external terminal and run a command like (replacing XYZ with the port you found) `wget --no-proxy -nv -O - http://127.0.0.1:XYZ/delay-shutdown`
- or, `curl --noproxy 127.0.0.1 -s http://127.0.0.1:XYZ/delay-shutdown` if you are using curl

and share the output with me

**Comment by leon-li1** [comment] 2020-07-16 02:53
Here is what I got from the log:
```
~/.vscode-server $ cat .5763d909d5f12fe19f215cbfdd29a91c0fa9208a.log


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 129.97.167.47
IP Address: 10.10.152.47
IP Address: 10.1.152.47
Extension host agent listening on 32897


[08:59:38] Extension host agent started.
[08:59:38] [127.0.0.1][a0c20b59][ManagementConnection] New connection established.
[08:59:38] [127.0.0.1][1bda91c6][ExtensionHostConnection] New connection established.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
setterm: unrecognized option '-x'
Try 'setterm --help' for more information.
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
[08:59:39] [127.0.0.1][1bda91c6][ExtensionHostConnection] <13422> Launched Extension Host Process.
[10:46:08] [127.0.0.1][a0c20b59][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[10:46:09] [127.0.0.1][1bda91c6][ExtensionHostConnection] <13422> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[10:46:09] Last EH closed, waiting before shutting down
Last EH closed, shutting down
[10:51:10] Last EH closed, shutting down
```

**Comment by klory** [comment] 2020-07-22 01:50
same problem for me, and deleting log files works `rm ~/.vscode-server/.*.log`

```
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

**Comment by mcswell** [comment] 2020-07-23 16:28
I had written
> This is a reproducible error on my system, in the sense that it happens every day. 
However, I am no longer able to reproduce it; it starts up fine now.  I did not make any changes on the remote, so maybe a change in VSC?  which updated to 1.47.2 today (although I don't believe I've had any problems since 1.47.1).

**Comment by leon-li1** [comment] 2020-07-23 16:38
> same problem for me, and deleting log files works `rm ~/.vscode-server/.*.log`
> 
> ```
> Version: 1.47.2
> Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
> Date: 2020-07-15T18:18:50.054Z
> Electron: 7.3.2
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 19.5.0
> ```

It works if I delete the log file each time I want to SSH, is that normal?

**Comment by roblourens** [comment] 2020-07-24 03:09
I identified a specific issue that @sisrfeng was seeing and asked for more info. Other people, please check the log file from the Remote-SSH output channel. If it has a message like what I pointed out in https://github.com/microsoft/vscode-remote-release/issues/2828#issuecomment-659069781 then it is the same issue, and please provide the extra info that I asked for there.

**Comment by mcswell** [comment] 2020-07-24 03:44
IIUC, this is the file you get when you choose 'Output' in VSE, and then in the drop-down choose 'Remote - SSH', correct?  not the file on the remote under ~/.vscode-server/.*.log.  And the msg you're looking for in that file is "Checking server status on port XYZ with wget", right?  If that's correct, I don't see the msg in that logfile (or any of the other logfiles I've checked).  But I guess that's to be expected (and not helpful), since I'm no longer experiencing the inability to connect...

**Comment by MarkoMFilip** [comment] 2020-08-07 07:22
Confirming that I have the same issue on VSCode version 1.47.3. However it only happens after computer restart.

**Comment by kk94wang** [comment] 2020-08-07 21:51
Same problem. Cannot log in the sever unless deleting the whole .vscode-server folder

**Comment by roblourens** [comment] 2020-08-08 22:06
Closing this as I described in https://github.com/microsoft/vscode-remote-release/issues/2828#issuecomment-663327942

**Comment by roblourens** [comment] 2020-08-08 22:07
People with remaining issues, please open a new issue with the log from the Remote-SSH output channel, and if you are having the exact issue I described above, with the extra info from https://github.com/microsoft/vscode-remote-release/issues/2828#issuecomment-659069781

**Closed by roblourens** 2020-08-08 22:06 UTC

**Comment by Sheridan-Tech** [comment] 2020-08-18 01:23
You could try this: https://github.com/Sheridan-Tech/Update_VScode

**Comment by MachoLikeBosomTo** [comment] 2020-08-21 01:30
> Same problem. Cannot log in the sever unless deleting the whole .vscode-server folder

更新Windows的VScode到最新版本，可以解决此问题。我今天就是这样！

**Comment by MachoLikeBosomTo** [comment] 2020-08-21 01:44
> Same problem. Cannot log in the sever unless deleting the whole .vscode-server folder

![image](https://user-images.githubusercontent.com/50037831/90842855-d9fa2080-e392-11ea-8ebb-5ef3afbb1d72.png)
然后更新Windows的VScode到最新版本，可以解决此问题。我今天就是这样！
