### ISSUE TITLE
Can't write the file '/etc/apt/sources.list'

### ISSUE THREAD

**Issue by ZhouJiatai** [microsoft/vscode-remote-release#3498] opened 2020-08-11 07:33 UTC
- VSCode Version: 1.47.3
- Local OS Version: 19041.388
- Remote OS Version: 4.4.0-19041-Microsoft
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1.Open WSL (Ubuntu 20.04 LTS), enter "code" plus enter.
2.Open the file (etc/apt/sources.list), edit this file and save it.
3.Then program said,
> 未能保存“sources.list”: 无法写入文件"vscode-remote://wsl+ubuntu/etc/apt/sources.list"(NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/etc/apt/sources.list')

Why is that? Why I can't save this file??? Please tell me or repair this bug.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2020-11-06 15:54
duplicate of https://github.com/microsoft/vscode-remote-release/issues/1688

**Closed by aeschli** 2020-11-06 15:54 UTC
Labels: wsl
