### ISSUE TITLE
Remote SSH extensions fails with connection timeout

### ISSUE THREAD

**Issue by rebeccaWeber8** [microsoft/vscode-remote-release#3359] opened 2020-07-13 11:24 UTC
Issue already discussed here #1721 is still happening to me! Previous conversation is closed.

- VSCode Version: 1.47.0; 2020-07-09
- Local OS Version: Windows 10, v1903
- Remote OS Version: CentOS 7
- Remote SSH v0.51.0
- Remote Extension/Connection Type: SSH

```
[12:16:08.061] Log Level: 1
[12:16:08.080] remote-ssh@0.51.0
[12:16:08.081] win32 x64
[12:16:08.085] SSH Resolver called for "ssh-remote+devserver", attempt 1
[12:16:08.087] SSH Resolver called for host: devserver
[12:16:08.087] Setting up SSH remote "devserver"
[12:16:08.136] Using commit id "d5e9aa0227e057a60c82568bf31c04730dc15dcd" and quality "stable" for server
[12:16:08.142] Install and start server if needed
[12:16:08.160] Checking ssh with "ssh -V"
[12:16:08.294] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[12:16:08.298] Using SSH config file "c:\path\to\.ssh\config-remote"
[12:16:08.298] Running script with connection command: ssh -T -D 56107 -F "c:\path\to\config-remote" devserver bash
[12:16:08.309] Terminal shell path: C:\windows\System32\cmd.exe
[12:16:40.308] Resolver error: Connecting with SSH timed out
[12:16:40.316] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"Timeout","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","gotUnrecognizedPrompt":"0","remoteInConfigFile":"1"},"measures":{"resolveAttempts":1,"retries":1}}
[12:16:40.319] ------
```

Steps to Reproduce:

1. install ssh remote and try to connect to remote server. it should be ok.
2. reboot system and try to connect again.

Does this issue occur when you try this locally?: no
Does this issue occur when you try this locally and all extensions are disabled?: no

I've been running into this over and over and over and over... through all versions of vscode I've been using, starting from 1.37 at least and insiders version as well. I've changed my laptop, this is still happening.
Workaround to make it works is to uninstall vscode and install again. Every time I reboot the laptop.

**Comment by Gizmotoy** [comment] 2020-07-27 21:20
Same issue here.  

`[13:54:35.883] Log Level: 2
[13:54:35.885] remote-ssh@0.51.0
[13:54:35.886] darwin x64
[13:54:35.887] SSH Resolver called for "ssh-remote+myhost", attempt 1
[13:54:35.888] SSH Resolver called for host: myhost
[13:54:35.888] Setting up SSH remote "myhost"
[13:54:35.891] Acquiring local install lock: /var/folders/0n/h4jg6b3s471bvxl41w8tp7j80000gn/T/vscode-remote-ssh-myhost-install.lock
[13:54:35.904] Looking for existing server data file at /Users/myname/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-myhost-91899dcef7b8110878ea59626991a18c8a6a1b3e-0.51.0/data.json
[13:54:35.906] Using commit id "91899dcef7b8110878ea59626991a18c8a6a1b3e" and quality "stable" for server
[13:54:35.917] Install and start server if needed
[13:54:35.961] Checking ssh with "ssh -V"
[13:54:35.976] > OpenSSH_8.1p1, LibreSSL 2.7.3
[13:54:35.980] askpass server listening on /var/folders/0n/h4jg6b3s471bvxl41w8tp7j80000gn/T/vscode-ssh-askpass-901930a4f51a079add2ff54441476b5a5439e456.sock
[13:54:35.980] Spawning local server with {"ipcHandlePath":"/var/folders/0n/h4jg6b3s471bvxl41w8tp7j80000gn/T/vscode-ssh-askpass-44762ebcfb9d6489b7d1f1f8ef7feee898738711.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61133","-o","ConnectTimeout=15","myhost"],"dataFilePath":"/Users/myname/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-myhost-91899dcef7b8110878ea59626991a18c8a6a1b3e-0.51.0/data.json"}
[13:54:35.980] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/0n/h4jg6b3s471bvxl41w8tp7j80000gn/T/vscode-ssh-askpass-901930a4f51a079add2ff54441476b5a5439e456.sock"}
[13:54:35.984] Spawned 45081
[13:54:36.095] > local-server> Spawned ssh: 45083
[13:54:36.100] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[13:54:52.990] Terminating local server
[13:54:52.991] Resolver error: Connecting with SSH timed out
[13:54:52.993] ------




[13:54:52.996] Local server exit: 15`

I updated VSCode to 1.47.3 and I stopped being able to use Remote-SSH.  It had been working flawlessly for many months.  Unfortunately I'm not 100% certain what version I updated from.  My Remote-SSH was at 0.51.0, and I get the above error.

What appears to be the underlying command: `ssh -v -T -D 61133 -o ConnectTimeout=15 myhost bash` does seem to work from a regular terminal on my MacOS host machine to my Ubuntu 18.04 client, but it takes awhile.  If I remove the `-o` it returns immediately.

Upon advice in other threads, I noticed that people said downgrading Remote-SSH to 0.49.0 fixed this issue for them.  I can confirm this does resolve the issue for me.  So I re-upgraded to 0.51.0 and it was broken again.

Happy to help track down the cause.

**Comment by roblourens** [comment] 2020-09-13 17:44
> does seem to work from a regular terminal on my MacOS host machine to my Ubuntu 18.04 client, but it takes awhile. If I remove the -o it returns immediately.

Can you explain some more about what you see? I assume it returns with an error since removing `-o` would make the command invalid.

Does setting `"remote.SSH.useLocalServer": false` fix it?

**Comment by Gizmotoy** [comment] 2020-09-15 04:09
> Can you explain some more about what you see? I assume it returns with an error since removing `-o` would make the command invalid.

I removed that whole option.
`ssh -v -T -D 61133 -o ConnectTimeout=15 myhost bash` would get take a long time and then exit (presumably hitting the timeout)

But if I then immediately ran
`ssh -v -T -D 61133 myhost bash` it would work fine.

If I then switch back to the version with `-o ConnectTimeout=15` it would fail again.  Unfortunately there does not appear to be a mechanism in the current configuration settings to simply not set this parameter at all (or maybe there is and I couldn't find it).

Using the `"remote.SSH.useLocalServer": false` setting did not resolve the issue.

I will note that since my original post, I can **_sometimes_** use 0.51.0.  Eventually it will break and I revert to 0.49.0 for a few days, and then I can go back to 0.55.0.  I have not identified what causes it to get into a bad state.

Unfortunately I also do not have much time on 0.55.0 or 0.54.0, having just been released in the past 2 days, to know if they're more stable or not.

**Comment by Gizmotoy** [comment] 2020-09-15 16:56
More specifically, this is what happens:

`ssh -v -T -D 54517 -o ConnectTimeout=60 myhost bash
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/username/.ssh/config
debug1: /Users/username/.ssh/config line 1: Applying options for myhost
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to myhost.local [myipv6%en20] port 22.
debug1: connect to address myipv6%en20 port 22: Operation timed out
debug1: Connecting to myhost.local [myipv6%en0] port 22.
debug1: connect to address myipv6%en20 port 22: Operation timed out`

Then if I run
`ssh -v -T -D 54517 myhost bash` it connects immediately.  It seems like the `-o ConnectTimeout=15` setting is breaking something, but it can't be removed from the connection string (min value is 1, no toggle to disable).

**Comment by roblourens** [comment] 2020-09-22 18:37
This is baffling to me, setting that option should not be breaking anything.

**Comment by roblourens** [comment] 2020-09-22 18:38
```
 ConnectTimeout
             Specifies the timeout (in seconds) used when connecting to the SSH server, instead of using the default
             system TCP timeout.  This timeout is applied both to establishing the connection and to performing the ini-
             tial SSH protocol handshake and key exchange.
```

???

**Closed** 2020-09-30 12:34 UTC
Labels: needs-more-info, ssh
