### ISSUE TITLE
Launch error with 0.159, solved by installing 0.158

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/vscode-remote-release#4459] opened 2021-02-12 08:29 UTC
- VSCode Version: 1.54.0-insiders
- Local OS Version: MacOS Big Sur 11.2.1 (Mac Mini M1)
- Remote OS Version: -
- Remote Extension/Connection Type: Remote-Container, Docker Desktop 3.1.0 with Docker Engine 20.10.3
Steps to Reproduce:

1. Updated Remote-Containers to 0.159
2. Start VSCode with a devcontainer.json present
3. None of the remote-containers commands work and in extension host log:
```
[2021-02-12 09:26:28.794] [exthost] [error] Activating extension ms-vscode-remote.remote-containers failed due to an error:
[2021-02-12 09:26:28.794] [exthost] [error] {"message":"Command failed: docker context show","stdout":{"type":"Buffer","data":[]},"stderr":{"type":"Buffer","data":[10,85,115,97,103,101,58,32,32,100,111,99,107,101,114,32,99,111,110,116,101,120,116,32,67,79,77,77,65,78,68,10,10,77,97,110,97,103,101,32,99,111,110,116,101,120,116,115,10,10,67,111,109,109,97,110,100,115,58,10,32,32,99,114,101,97,116,101,32,32,32,32,32,32,67,114,101,97,116,101,32,97,32,99,111,110,116,101,120,116,10,32,32,101,120,112,111,114,116,32,32,32,32,32,32,69,120,112,111,114,116,32,97,32,99,111,110,116,101,120,116,32,116,111,32,97,32,116,97,114,32,111,114,32,107,117,98,101,99,111,110,102,105,103,32,102,105,108,101,10,32,32,105,109,112,111,114,116,32,32,32,32,32,32,73,109,112,111,114,116,32,97,32,99,111,110,116,101,120,116,32,102,114,111,109,32,97,32,116,97,114,32,111,114,32,122,105,112,32,102,105,108,101,10,32,32,105,110,115,112,101,99,116,32,32,32,32,32,68,105,115,112,108,97,121,32,100,101,116,97,105,108,101,100,32,105,110,102,111,114,109,97,116,105,111,110,32,111,110,32,111,110,101,32,111,114,32,109,111,114,101,32,99,111,110,116,101,120,116,115,10,32,32,108,115,32,32,32,32,32,32,32,32,32,32,76,105,115,116,32,99,111,110,116,101,120,116,115,10,32,32,114,109,32,32,32,32,32,32,32,32,32,32,82,101,109,111,118,101,32,111,110,101,32,111,114,32,109,111,114,101,32,99,111,110,116,101,120,116,115,10,32,32,117,112,100,97,116,101,32,32,32,32,32,32,85,112,100,97,116,101,32,97,32,99,111,110,116,101,120,116,10,32,32,117,115,101,32,32,32,32,32,32,32,32,32,83,101,116,32,116,104,101,32,99,117,114,114,101,110,116,32,100,111,99,107,101,114,32,99,111,110,116,101,120,116,10,10,82,117,110,32,39,100,111,99,107,101,114,32,99,111,110,116,101,120,116,32,67,79,77,77,65,78,68,32,45,45,104,101,108,112,39,32,102,111,114,32,109,111,114,101,32,105,110,102,111,114,109,97,116,105,111,110,32,111,110,32,97,32,99,111,109,109,97,110,100,46,10]},"code":1}
```
4. Downgrade Remote-Containers to 0.158 and everything works again.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment] 2021-02-12 08:53
Marking as duplicate of #4456. Thanks.

**Closed by chrmarti** 2021-02-12 08:53 UTC
