### ISSUE TITLE
Open tabs are cleared after a connection lost error. I can't recover my open tabs after that.

### ISSUE THREAD

**Issue by raymelon** [microsoft/vscode-remote-release#2746] opened 2020-04-13 05:17 UTC
Issue Type: <b>Bug</b>

Hello,

I'm having connection issues lately. Problem is, I'm losing my open tabs when the network took longer to regain connection.

A simple auto reconnection is usually enough but when I reached presumably a timeout, my open tabs are lost and an error connection prompt message appears.

Steps to reproduce:

1. Disconnect network
2. Wait for the plugin to do a reconnection
3. Don't interrupt the reconnection loop until the plugin gives up. An error connecting prompt message will appear
4. All open tabs are lost.
5. No point of recovery. Manually connect back to remote and no open tabs recovered.

Note: I can't find a workspace file on the server so not sure where all the open tabs are recorded, at least to restore it manually or so.

Extension version: 0.51.0
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:44:52.965Z)
OS version: Linux x64 5.3.0-7625-generic
Remote OS version: Linux x64 3.10.0-1062.18.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3686)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.52GB (3.58GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ***|
|OS|Linux x64 3.10.0-1062.18.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz (2 x 2400)|
|Memory (System)|1.79GB (0.31GB free)|
|VM|100%|

**Comment by oroszwj** [comment] 2020-06-12 15:36
I also have this issue since I routinely connect to targets behind a VPN connection.  This is particularly frustrating since closing the window after all the tabs are lost still saves the workspace state so the tabs are still gone when restarting VS Code.  

The only thing I have found close to a workaround is to terminate all the VS Code processes with task manager so that the previous workspace state will be reloaded and tabs will be recovered on next launch, but obviously this intentional interference with disk I/O has it's own risks.

@raymelon, based on these observations, I suspect the workspace file is on the local machine rather than the remote target, but I have not confirmed this yet.

**Comment by raymelon** [comment] 2020-06-18 09:05
> I also have this issue since I routinely connect to targets behind a VPN connection. This is particularly frustrating since closing the window after all the tabs are lost still saves the workspace state so the tabs are still gone when restarting VS Code.
> 
> The only thing I have found close to a workaround is to terminate all the VS Code processes with task manager so that the previous workspace state will be reloaded and tabs will be recovered on next launch, but obviously this intentional interference with disk I/O has it's own risks.
> 
> @raymelon, based on these observations, I suspect the workspace file is on the local machine rather than the remote target, but I have not confirmed this yet.

@oroszwj I appreciate the additional observations on your end, thank you. I think it makes sense having the workspace files on the local machine, as it avoids conflict in workspaces when multiple people share directories on a remote environment. It gave me a hint to track the workspace files on my local machine to see how they behave during the reconnection process and so. I will try to share back any significant observation I will encounter.

**Comment by bamurtaugh** [comment] 2020-11-04 01:16
Possibly related/dupe: https://github.com/microsoft/vscode-remote-release/issues/3475 (although this came before 3475, we've been tracking 3475 as well).

**Closed** 2020-11-05 20:07 UTC
Labels: *duplicate, bug, ssh
