### ISSUE TITLE
WSL windows started with code-insiders . have generic labels in recents

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#827] opened 2019-06-26 12:27 UTC
Testing https://github.com/microsoft/vscode-remote-release/issues/789

When opening folders from within VS Code, the Recent folder item has the nice [WSL: SLES-12] style label. But when you open a WSL shell and run `code-insiders .`, the Recent item that comes from that is just [WSL]. You can see this in the two most recent items here:

![image](https://user-images.githubusercontent.com/38270282/60179553-3bba0b80-981e-11e9-8919-d47b4f94236b.png)

The remote indicator during when I had those two folders open was correct though (you can actually see the most recent one open in the background).

**Comment by aeschli** [comment] 2019-06-26 15:13
duplicate of #808

**Closed by aeschli** 2019-06-26 15:13 UTC

**Comment by alexr00** [comment] 2019-06-27 07:59
These weren't old entries though. I had just opened those from open folder.
