### ISSUE TITLE
Remote Connection Fails When there is a Bastion Host 

### ISSUE THREAD

**Issue by kathyu8** [microsoft/vscode-remote-release#321] opened 2019-05-14 21:30 UTC
- VSCode Version: Version 1.34.20-insider 
- Local OS Version: MacOS Mojave 10.14.4
- Remote OS Version: LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago

- Remote Extension/Connection Type: SSH/Docker/WSL
SSH
Steps to Reproduce:

1. I put my public key on the bastion host successfully.
2. Put in the config file the ConfigMaster and my own username and host, with alias Bastion_Host
3. Click on the extension and tried to connect

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Description:

My company uses a bastion host to connect to it's private instances. I did ssh certificates for between my local and the bastion host so I can login without a password, and then I intended to ssh to my private instance. I enabled the showLoginTerminal setting as suggested but I get the following error whenever I try to connect:

SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2242617374696f6e5f486f7374227d"
SSH Resolver called for host: Bastion_Host
Setting up SSH remote "Bastion_Host"
Using commit id "57b550c559b945eb9d871dbf2b2e4cb9e31e2551" and quality "insider" for server
Install and start server if needed

Installation already in progress...
461c4e6f-9fe3-4b12-b772-0a9846262235##24##
bash: no job control in this shell
"install" terminal command done
Received install output: bash: no job control in this shell
Failed to parse remote port from server output: bash: no job control in this shell
"

And there's no way to type in a second ssh for the private instance.

**Comment by kathyu8** [comment] 2019-05-14 21:32
Here's a screenshot when it's hanging on the wget command. 
![Screen Shot 2019-05-14 at 5 31 54 PM](https://user-images.githubusercontent.com/1657600/57733752-40f83800-766e-11e9-8219-057589f175f1.png)

**Comment by benliddicott** [comment] 2019-05-17 17:35
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/16

See the workaround I posted there.

**Comment by roblourens** [comment] 2019-05-19 20:54
Can you share your ssh config so I can see how the "bastion host" is set up?

**Comment by roblourens** [comment] 2019-05-19 20:56
Also could you just try again, making sure there is only one window open, and share the full log from "Remote - SSH"?

It seems like it thought another window was installing the server, and didn't retry for some reason. Those errors regarding job control are ok.

**Closed** 2019-05-26 21:02 UTC
Labels: needs-more-info
