### ISSUE TITLE
Windows mounted file in WSL can be opened in two editors through two paths and causes conflicts 

### ISSUE THREAD

**Issue by wanghc78** [microsoft/vscode-remote-release#666] opened 2019-06-12 17:38 UTC
- VSCode Version: VSCode insider 1.36.0-insider
- Local OS Version: Windows 10 1803
- Remote OS Version: WSL ubuntu 16.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1.  Prepare a C project, e.g. _example_, with _lib.c_ and _lib.h_. And put it in a windows folder. Make sure it can be accessed through _/mnt/c/somePaths/example_ in WSL.
2. Open this project with vscode/WSL remote.
3. Open a file through the Explorer, e.g. _lib.c_.  The editor will show its path is _lib.c_
4. Use `Alt+O` to  switch to the header file. The editor will open _lib.h_ as the WSL's mount path, like _/mnt/c/somePaths/example/lib.h`
5. Use the Explorer to open _lib.h_, and it will open in another editor, with the path _lib.h_.

It causes a lot of troubles like I wrote some code in one editor, but it cannot be visible in another editor. And one editor saves the file, and another editor cannot save the file due to conflicts.

Does this issue occur when you try this locally?: No. The file has only one path, the windows path.
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment] 2019-06-13 08:50
I tried to reproduce, but wasn't able. `Switch to header file` is contributed by the cpp extension. Maybe there's something special in that code. Moving to the cpp extension.

**Comment by sean-mcmanus** [comment] 2019-06-14 20:24
I also am not able to reproduce the bug (I don't know why). I don't see it open the "_/mnt/c/somePaths/example/lib.h"

If the Windows path of the source files has case-sensitivity enabled, then that is a known bug without extension that affects other stuff as well.

**Comment by wanghc78** [comment] 2019-06-17 07:11
Here is a screenshot for a C project (jerryscript https://github.com/jerryscript-project/jerryscript). You can see the same file is opened from two paths
- _jerry-core/include/jerryscript.h_
- _/mnt/d/workspace/IoT/jerry-core/include/jerryscript.h_

![jerry](https://user-images.githubusercontent.com/3319260/59584413-ca968d80-9092-11e9-83db-1574f0e34bdd.jpg)

Besides using Alt+O to flip the header, you can also use Ctrl+mouse click to track a file to open. For example, you can first open _jerry-main/main-unix-snapshot.c_, and click the `#include "jerryscript.h"` to open it with the absolute path. 

After that, you can use Ctrl+P to search the file, and it will be shown in two paths.
![jerry2](https://user-images.githubusercontent.com/3319260/59584762-be5f0000-9093-11e9-909a-f13e909ff19e.jpg)

I guess it is related to CPP extension. When I try this in a Node.JS project, and follow `require()` to open another js file, only the relative path in the project will be used, not the absolute path.

And if I use code in non-WSL mode, it works without any problem. For the same jerryscript project, it  only opens a file with the project's relative path.

**Comment by aeschli** [comment] 2019-06-17 07:25
Thanks @wanghc78 for the investigation and the writeup. It also appears to me that this is related to the CPP extension.
Let's continue the discussion in https://github.com/microsoft/vscode-cpptools/issues/3764.

I copy your comment in there...

**Closed** 2019-06-24 08:19 UTC
Labels: needs-more-info, wsl
