### ISSUE TITLE
Could not establish connection to "server". y.onDidWriteData is not a function.

### ISSUE THREAD

**Issue by ErikDahlof** [microsoft/vscode-remote-release#1419] opened 2019-09-16 10:02 UTC
Issue Type: <b>Bug</b>

Trying to connect to remote server using Remote - SSH but I keep getting the error message: Could not establish connection to "server". y.onDidWriteData is not a function. "server" is the name of my server. Used to work before but after I installed latest update it is no longer working. Tried restarting computer. Tried reinstalling Remote - SSH. Tried to uninstall VSCode and reinstall. Nothing works

Extension version: 0.46.0
VS Code version: Code - Insiders 1.39.0-insider (d157c2e941cae17acb79bf26a70bbfad732bdc83, 2019-09-16T06:04:26.115Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.57GB free)|
|Process Argv|-psn_0_356439|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by xelaos** [comment] 2019-09-16 11:35
I have the same problem. However, it still works with the normal version of vs code.

**Comment by evalufran** [comment] 2019-09-16 11:36
[10:57:39.525] remote-ssh@0.46.0
[10:57:39.525] win32 x64
[10:57:39.526] SSH Resolver called for "ssh-remote+ddserver", attempt 1
[10:57:39.527] SSH Resolver called for host: ddserver
[10:57:39.527] Setting up SSH remote "ddserver"
[10:57:39.618] Using commit id "d157c2e941cae17acb79bf26a70bbfad732bdc83" and quality "insider" for server
[10:57:39.622] Testing ssh with ssh -V
[10:57:39.777] ssh exited with code: 0
[10:57:39.778] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[10:57:39.778] Using SSH config file "C:\Users\Eva\remoteconfig.config"
[10:57:39.778] Running script with connection command: ssh -D 50411 -F C:\Users\Eva\remoteconfig.config ddserver bash
[10:57:39.782] Install and start server if needed
[10:57:39.785] "install" process failed: TypeError: y.onDidWriteData is not a function
[10:57:39.786] y.onDidWriteData is not a function
[10:57:39.786] ------

Which is the normal version?

**Comment by xelaos** [comment] 2019-09-16 12:17
Sorry, I meant the "blue" / not insiders edition of vs code at version 1.38.

**Comment by evalufran** [comment] 2019-09-16 12:24
are you able to connect to ur virtual machine using it?
I ve always used the insiders version

**Comment by prosenboim** [comment] 2019-09-16 12:43
> are you able to connect to ur virtual machine using it?
> I ve always used the insiders version

Yes, latest released version also supports remote extensions.

**Comment by evalufran** [comment] 2019-09-16 12:58
thank you all :)

**Comment by egamma** [comment] 2019-09-16 13:18
Duplicate of #1417

**Closed by egamma** 2019-09-16 13:18 UTC
