### ISSUE TITLE
Recycle Bin Support for WSL

### ISSUE THREAD

**Issue by shafayetejaman** [microsoft/vscode-remote-release#9116] opened 2023-10-19 19:11 UTC
WSL vs-code does not move the deleted files to the Windows trash bin, it deletes the files permanently.
It should move the files to the recycle bin because its vary common to delete files by mistake.

**Comment by aeschli** [comment] 2023-10-20 07:28
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/5615

We currently only offer 'Move to trashbin' if the underlying filesystem supports that. It would mean to invent our own variant of it.

**Closed by aeschli** 2023-10-20 07:28 UTC
