### ISSUE TITLE
SSH randomly disconnects since last update

### ISSUE THREAD

**Issue by AnthonyParkssonos** [microsoft/vscode-remote-release#3573] opened 2020-08-25 14:11 UTC
- VSCode Version: 1.48.1
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to SSH
2. Wait about 20 minutes to an 1 hour for random disconnection

Remote SSH disconnects all the time since the July 2020 update I received a few days ago. This is a major problem for me as all my development happens remotely. I will try moving to a previous version until this is resolved.

**Comment by AnthonyParkssonos** [comment] 2020-08-27 17:29
this is a regression. a downgrade to June 2020 release fixed the issue

**Comment by lvmingzhe** [comment] 2020-09-01 02:04
I meet the same problem.

**Comment by AnthonyParkssonos** [comment] 2020-09-01 16:57
i had better success with this when cpptools extension was disabled, but it basically makes vscode nothing more than an editor at this point.

**Comment by roblourens** [comment] 2020-09-13 17:47
Can you check whether it's any better with the August release?

If not, can you share the log from the Remote-SSH output channel for a time when you were disconnected, to see if it has some more info?

When it disconnects, is it able to reconnect?

**Comment by cshelpucla** [comment] 2020-09-15 21:26
As of right now August 2020 release still has this issue - I just spent 2 days fighting with it - and finally found this thread, downgraded to June 2020 and issue went away - I have Ubuntu on Linux box side with VS code running ssh remote to that box

**Comment by roblourens** [comment] 2020-09-22 18:38
Are you also using the cpptools extension?

**Comment by cshelpucla** [comment] 2020-09-22 18:47
nope node js development mostly no cpp

**Comment by Subratappt** [comment] 2020-10-05 16:33
With **VS code insider** it is performing somehow better than VS code. 
```
Version: 1.50.0-insider (user setup)
Commit: 0ecb64a2c8945dd1193967019f0734af539ca9c3
Date: 2020-10-02T11:16:33.984Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by roblourens** [comment] 2020-11-07 18:59
I can't reproduce a new issue, so I have to close this.

Here are some things that can cause disconnections
- Extensions or other processes using lots of CPU or memory
- Very large workspaces that cause VS Code's filewatcher process to use lots of memory
- Anything that disrupts the network connection between the local and remote machnes

**Closed by roblourens** 2020-11-07 18:59 UTC
Labels: ssh
