### ISSUE TITLE
Open in container fails

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode-remote-release#5992] opened 2021-12-03 14:21 UTC
Issue Type: <b>Bug</b>

Update VSCode today.

I see the following error on my Mac:
```
Command failed: docker-compose -f docker-compose.yml --profile * config
```

If I try to run the command on the cli, that fails too. But, with the following change, it works fine:
```
docker-compose -f docker-compose.yml --profile "*" config
```

Looks like the `*` is getting the expansion treatment on zsh when thit command is run.

Extension version: 0.205.2
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 6, 7|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|--crash-reporter-id 0dec9fd0-c8fd-4152-a33c-72a9d4647e00|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vsena315:30406435
pythonvs932:30405811
vscexrecpromptt2:30404948
vscop804:30404766
vscop940:30404999
vsrem710:30405998

```

</details>

**Comment by navneetkarnani** [comment] 2021-12-04 09:17
This bug, effectively, locks me out of starting devcontainer based environments from within VSCode.

Remote Container extension is at: v0.205.2

And I did not see an option to "update" it. Tried uninstalling and installing again. But stays there. 

I tried deleting the extension from the .vscode/extensions directory. Can see the v0.209.0 in the extension market place, but when i install it, i still see the 205.2 installed in the extensions directory.

**Comment by navneetkarnani** [comment] 2021-12-04 09:25
I tried downloading v0.209 and installing manually. See this error:
```Unable to install extension 'ms-vscode-remote.remote-containers' as it is not compatible with VS Code '1.62.3'.```

**Comment by chrmarti** [comment] 2021-12-07 08:25
Could you attach the full log?

- On `"*"`: Quotes are only needed when executing through a shell, the extension launches `docker-compose` directly without a shell. (The CLI parameters are passed as an array.)
- On newer versions: These currently require VS Code Insiders (can be installed alongside VS Code) and will be available with VS Code 1.63 when that is released.

**Comment by navneetkarnani** [comment] 2021-12-11 10:38
```
[2021-12-11T10:37:01.078Z] Start: Resolving Remote
[2021-12-11T10:37:01.079Z] Remote-Containers 0.205.2 in VS Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e).
[2021-12-11T10:37:01.090Z] Setting up container for folder or workspace: /Users/navneet/code/taxhelper/dev-server
[2021-12-11T10:37:01.091Z] Context: desktop-linux
[2021-12-11T10:37:01.095Z] Start: Check Docker is running
[2021-12-11T10:37:01.095Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2021-12-11T10:37:01.508Z] Stop (413 ms): Run: docker version --format {{.Server.APIVersion}}
[2021-12-11T10:37:01.508Z] Server API version: 1.41
[2021-12-11T10:37:01.508Z] Stop (413 ms): Check Docker is running
[2021-12-11T10:37:01.575Z] Start: Run: docker-compose version --short
[2021-12-11T10:37:01.958Z] Stop (383 ms): Run: docker-compose version --short
[2021-12-11T10:37:01.959Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=dev-server --filter label=com.docker.compose.service=backend
[2021-12-11T10:37:02.212Z] Stop (253 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=dev-server --filter label=com.docker.compose.service=backend
[2021-12-11T10:37:02.213Z] Start: Run: docker inspect --type container ae950d652fea
[2021-12-11T10:37:02.451Z] Stop (238 ms): Run: docker inspect --type container ae950d652fea
[2021-12-11T10:37:02.453Z] Start: Run: docker-compose -f /Users/navneet/code/taxhelper/dev-server/docker-compose.yml --profile * config
[2021-12-11T10:37:02.755Z] Stop (302 ms): Run: docker-compose -f /Users/navneet/code/taxhelper/dev-server/docker-compose.yml --profile * config
[2021-12-11T10:37:02.758Z] Command failed: docker-compose -f /Users/navneet/code/taxhelper/dev-server/docker-compose.yml --profile * config
```

**Comment by navneetkarnani** [comment] 2021-12-11 10:40
```
[2021-12-11T10:39:18.260Z] Remote-Containers 0.209.5 in VS Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e).
[2021-12-11T10:39:18.260Z] Start: Resolving Remote
[2021-12-11T10:39:18.305Z] Setting up container for folder or workspace: /Users/navneet/code/taxhelper/dev-server
[2021-12-11T10:39:18.306Z] Context: desktop-linux
[2021-12-11T10:39:18.311Z] Start: Check Docker is running
[2021-12-11T10:39:18.312Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2021-12-11T10:39:18.624Z] Stop (312 ms): Run: docker version --format {{.Server.APIVersion}}
[2021-12-11T10:39:18.625Z] Server API version: 1.41
[2021-12-11T10:39:18.626Z] Stop (315 ms): Check Docker is running
[2021-12-11T10:39:18.686Z] Start: Run: docker-compose version --short
[2021-12-11T10:39:19.064Z] Stop (378 ms): Run: docker-compose version --short
[2021-12-11T10:39:19.065Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=dev-server --filter label=com.docker.compose.service=backend
[2021-12-11T10:39:19.326Z] Stop (261 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=dev-server --filter label=com.docker.compose.service=backend
[2021-12-11T10:39:19.327Z] Start: Run: docker inspect --type container ae950d652fea
[2021-12-11T10:39:19.572Z] Stop (245 ms): Run: docker inspect --type container ae950d652fea
[2021-12-11T10:39:19.574Z] Start: Run: docker-compose -f /Users/navneet/code/taxhelper/dev-server/docker-compose.yml --profile * config
[2021-12-11T10:39:19.924Z] Stop (350 ms): Run: docker-compose -f /Users/navneet/code/taxhelper/dev-server/docker-compose.yml --profile * config
[2021-12-11T10:39:19.926Z] Command failed: docker-compose -f /Users/navneet/code/taxhelper/dev-server/docker-compose.yml --profile * config
```

**Comment by chrmarti** [comment] 2021-12-13 10:55
What do you get for `docker-compose version`?

You are using the `desktop-linux` context, is that intentional?

**Comment by dmartin** [comment] 2021-12-18 00:59
I was able to work around this by disabling "Use Docker Compose V2" in the Docker Desktop settings. So I think this comes down to a behavioral difference between legacy Python `docker-compose` and `docker compose` (v2).

**Comment by navneetkarnani** [comment] 2021-12-18 09:44
Docker Compose version v2.2.1

Yes, desktop-linux is intentional, because I want to use the one running on my local machine, and not the one pointed to sometimes, by the DOCKER_HOST variable. Most of the time, I work with remote docker host hosted on AWS / DigitalOcean, instead of running them locally.

**Comment by navneetkarnani** [comment] 2021-12-18 09:47
> I was able to work around this by disabling "Use Docker Compose V2" in the Docker Desktop settings. So I think this comes down to a behavioral difference between legacy Python `docker-compose` and `docker compose` (v2).

This should really not be a problem, because I am able to run the same command ( as in the logs ) on the commandline and it works as expected.

**Comment by navneetkarnani** [comment] 2021-12-18 12:02
I can also confirm, that turning off "V2" from the preferences does fix the issue.

**Comment by k0mmsussert0d** [comment] 2021-12-20 00:13
Just ran into this bug and, as expected, its origin seems to stem from recently released v2 of `docker-compose`. Unfortunately, developers behind it fail to provide actual backwards compatibility and v2 suffers from many other minor issues like that one, where expected behavior differs from the one observed with v1.

Given how unstable the tool is at the current state, I decided to switch back to v1 for now and wait for all the regression bugs to be hopefully resolved.

**Comment by chrmarti** [comment] 2021-12-22 09:05
We check with `docker-compose version --short` if we are using v2 and in that case add `--profile *` to adopt a change in behavior with Docker Compose v2: https://github.com/docker/compose/issues/8676.

I'm improving logging in Remote-Containers to track this down further.

**Comment by navneetkarnani** [comment] 2021-12-24 06:22
Some more info.

I have a "remote docker host" on AWS, that runs on AmazonLinux:2. And VSCode Remote container runs fine with the context set to point to "ssh://remote-host". I just tried running "docker compose version" on my local machine, and saw "2.2.1". When I ran "docker compose version" on the ssh console, the command failed. But the "docker-compose" command works there.

I also tried bringing up a "devcontainer" environment on the remote host, and that works perfectly.

So, my best guess is:
- If the context says its on an older version, then the fallback to "docker-compose" happens, and all is well.
- If the context says its on 2.x, the "docker compose config profiles *" command is run, and that fails. I am speculating the "*" is getting resolved by the shell in some way, or the command line is expecting a `'*'` literally, as mentioned in https://github.com/docker/compose/issues/8676#issuecomment-928000416

For now, I am falling back to docker-compose v1 and working normally. For both cases: context `default`, and context `desktop-linux`.

Hope this helps.

**Comment by chrmarti** [comment] 2021-12-24 08:18
@navneetkarnani Does this happen with every docker-compose.yml or just specific one? Could you append the one you are using? I can't reproduce the issue with Docker Desktop for Mac 4.3.2.

**Comment by navneetkarnani** [comment] 2021-12-24 09:04
I have added my "failing" environment to this repo:
https://github.com/navneetkarnani/test-vscode-compose

**Comment by navneetkarnani** [comment] 2021-12-24 09:21
Found the issue. 

Saw the error when I ran the command: 
`docker-compose -f docker-compose.yml --profile '*' config` 

on the terminal.

There is a change in behaviour between 1.2 and 2.x. The "default" network is no longer available in 2.x. Has to be explicitly defined. Leaving the code in the repo, for reference.

Removing "default" allows the compose command to run correctly.

**Comment by chrmarti** [comment] 2022-01-03 10:25
Thanks for posting the update. Closing as resolved.

**Closed by chrmarti** 2022-01-03 10:25 UTC
Labels: bug, containers
