### ISSUE TITLE
VS-Code does not read the already present hosts in ssh config

### ISSUE THREAD

**Issue by Mazorius** [microsoft/vscode-remote-release#6572] opened 2022-04-06 09:16 UTC
Hi,

I use SSH a long time and also use the Include feature, which means I separated the configurations in different files:

`~/.ssh/config` > contains the following command `Include ~/.ssh/config.d/*

Inside `~/.ssh/config.d/` I have many files with my hosts separated by service:

- `~/.ssh/config.d/service1`
- `~/.ssh/config.d/service2`
- `~/.ssh/config.d/service3`

VSCode Remote SSH does not provide an option to scan this and list all hosts in the remote explorer. I always need to use the quick connection because otherwise vscode starts to add new configurations in the `~/.ssh/config` file.

Is this a feature already planned or will this never come?

Thanks in advance.

**Comment by tanhakabir** [comment] 2022-04-06 18:14
Ah we have this longstanding issue where Include directives need to be at the top of the file: https://github.com/microsoft/vscode-remote-release/issues/4339

Closing this as a duplicate of that bug

**Closed by tanhakabir** 2022-04-06 18:14 UTC
Labels: ssh, needs more info
