### ISSUE TITLE
SSH not working for specific folder

### ISSUE THREAD

**Issue by yaniv-krol** [microsoft/vscode-remote-release#7554] opened 2022-11-21 08:28 UTC
I usually connect to our remote dev server with VSCode SSH, and after the connection is made I open the project's directory
in ~/dir1/dir2. This timeouts for some reason. Any other directory I tried works fine.

Things I tried:
Reinstalling VSCode
Downgrading ms-vscode-remote.remote-ssh version
Deleting ~/.vscode-server on remote
setting "remote.SSH.useLocalServer": false
Restarting my Windows machine

- VSCode Version: 1.73.1 (user setup)
- Local OS Version: Windows 10 OS Build 19044.2251
- Remote OS Version: CentOS Linux release 8.3.2011
- Remote Extension/Connection Type: SSH with VPN
- Logs:

```
[09:53:52.612] Log Level: 2
[09:53:52.615] remote-ssh@0.90.1
[09:53:52.616] win32 x64
[09:53:52.768] SSH Resolver called for "<my-server-address>", attempt 1
[09:53:52.772] "remote.SSH.useLocalServer": false
[09:53:52.775] "remote.SSH.showLoginTerminal": false
[09:53:52.777] "remote.SSH.remotePlatform": {"10.189.200.172":"linux","<my-server-address>":"linux","10.189.200.59":"linux","<my-server-address>":"linux"}
[09:53:52.777] "remote.SSH.path": undefined
[09:53:52.780] "remote.SSH.configFile": undefined
[09:53:52.781] "remote.SSH.useFlock": true
[09:53:52.782] "remote.SSH.lockfilesInTmp": false
[09:53:52.787] "remote.SSH.localServerDownload": auto
[09:53:52.789] "remote.SSH.remoteServerListenOnSocket": false
[09:53:52.792] "remote.SSH.showLoginTerminal": false
[09:53:52.795] "remote.SSH.defaultExtensions": []
[09:53:52.797] "remote.SSH.loglevel": 2
[09:53:52.800] "remote.SSH.enableDynamicForwarding": true
[09:53:52.802] "remote.SSH.enableRemoteCommand": false
[09:53:52.805] "remote.SSH.serverPickPortsFromRange": {}
[09:53:52.806] "remote.SSH.serverInstallPath": {}
[09:53:52.874] SSH Resolver called for host: <my-server-address>
[09:53:52.874] Setting up SSH remote "<my-server-address>"
[09:53:52.923] Using commit id "6261075646f055b99068d3688932416f2346dd3b" and quality "stable" for server
[09:53:52.947] Install and start server if needed
[09:53:52.991] Checking ssh with "ssh -V"
[09:53:53.456] > Op
[09:53:53.458] > enSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[09:53:53.479] Running script with connection command: ssh -T -D 61976 "<my-server-address>" bash
[09:53:53.490] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:54:10.495] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\ykrol\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\ykrol\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[09:54:10.516] ------
```

It seems similar to this recent issue: https://stackoverflow.com/questions/74451632/why-connecting-with-ssh-of-vs-code-i-cannot-open-a-specific-folder.

**Comment by yaniv-krol** [comment] 2022-11-21 09:24
A solution that worked for me is moving ~/dir/dir2 to ~/newdir/dir2 ... so now I open ~/newdir/dir2

**Comment by yaniv-krol** [comment] 2022-11-21 20:26
> Hello! I just wanted to clarify the behavior you are seeing, the error "Resolver error: Error: Connecting with SSH timed out" comes up just when you try and open that specific folder? 
Correct

> Could you try running `kill vscode server on host` from the command palette and see if that makes a difference?
Tried that too, no difference

**Comment by eleanorjboyd** [comment] 2022-11-22 18:55
As @jabbera correctly noted this is a duplicate of #7324. The fix is sent out on the newest version of VS Code insiders. Thanks!

**Closed by eleanorjboyd** 2022-11-22 18:55 UTC
Labels: ssh, info-needed
