### ISSUE TITLE
Show directory full paths in recents list 

### ISSUE THREAD

**Issue by stdcall** [microsoft/vscode-remote-release#8034] opened 2023-02-13 07:46 UTC
After VS Code update the remote explorer recents list began to cut directory paths to basename. This is inconvenient as I have multiple directories with the same basename under different paths on my remote machine. The full path is now shown after hovering item but it makes it slow to select a target.

**Comment by Mylesthemonster** [comment] 2023-02-16 01:15
I also ran into this problem and downgraded the Remote Explorer extension to v0.0.3 to bring back full path names. I too have many directories with the same name and hovering over is worse then the prior method.

**Comment by Lightborne** [comment] 2023-02-17 14:36
Jumping on here to say this is annoying for me as well.  Same problem as the previous two commenters - I have many workspace names that are the same, only differentiated by their hierarchy.

**Comment by eleanorjboyd** [comment] 2023-02-27 18:27
Can you include a screenshot? Which remotes is it effecting? Only remote-ssh or others?

**Comment by eleanorjboyd** [comment] 2023-02-27 18:28
Additionally you said it was a regression- so the most recent version that does not have this new change is 0.0.3?

**Comment by hensz** [comment] 2023-02-28 14:50
This is how it looks like on my machine (and I only opened two of my workspaces):
![remote recent list](https://user-images.githubusercontent.com/1984979/221889463-0ac21c1f-b117-4c2a-bb3b-513db0f87b28.png)

**Comment by Mylesthemonster** [comment] 2023-02-28 18:56
@eleanorjboyd Yes this is for ssh connections and for me anything newer then 0.0.3 removes the full path names, for me I only have [ 0.0.2, 0.0.3, 0.2.0 ] as installable other versions for the Remote Explorer extension 

Made some test dirs to show in an example:
0.2.0:
<img width="395" alt="Screenshot 2023-02-28 at 10 51 09 AM" src="https://user-images.githubusercontent.com/66516979/221950915-b05071b4-6f90-45be-bc6d-642aee264fc3.png">

0.0.3:
<img width="395" alt="Screenshot 2023-02-28 at 10 50 02 AM" src="https://user-images.githubusercontent.com/66516979/221950878-ca833c9d-d36e-495c-a680-00088668dcc4.png">

And as mentioned on 0.2.0 the only way to see the full path is to hover over and wait a sec for it to display. I have other ssh connections with 10's of parent folders with the same name so I've just downgraded all my extensions since that update removed the functionally.

**Comment by eleanorjboyd** [comment] 2023-02-28 21:11
Thank you for the detail! I am marking this as a bug and adding to the backlog!

**Comment by gongsunli** [comment] 2023-07-07 02:13
Hi, I have the same issue. Is there any update? Thanks.

**Comment by Mylesthemonster** [comment] 2023-07-07 03:00
@gongsunli Nope the latest 0.4.0 still doesn’t fix this, I’ve stayed on 0.0.3 with no issue.

**Comment by adiegoweb** [comment] 2023-07-23 05:59
Thanks to everyone, this is a small detail but annoying.
Issue still happening in 0.4.1

**Comment by hensz** [comment] 2023-11-07 20:39
Hi!
Are there any plans for this issue to be tackled? It was added to the backlog in February, now we have November. Can we expect that the backlog item will be worked on in the near future?

**Comment by McRoi88** [comment] 2023-11-10 07:52
![image](https://github.com/microsoft/vscode-remote-release/assets/111861421/aa36cfbd-f0c1-42b2-a921-b442866e0415)
yes please, FIX !!!!!!

**Closed** 2024-08-12 15:21 UTC
Labels: bug, ssh
