### ISSUE TITLE
Explorer doesn't update automatically

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/vscode-remote-release#3200] opened 2020-06-12 16:10 UTC
- VSCode Version: 1.46.0
- OS Version: 10.0.19041.0

Steps to Reproduce:

1. Open a project via `code . `or something else
2. Change branch on wsl

Does this issue occur when all extensions are disabled?: idn

**Comment by aeschli** [comment] 2020-06-16 08:26
What's the location that you open? Is it on `/mnt/c....' ?
Is it WSL1 or WSL2?

Can you follow the steps here to see if the watcher works?
https://github.com/microsoft/vscode-remote-release/issues/2310#issuecomment-614071151

**Comment by Mystic8b** [comment] 2020-06-16 10:27
1. It's symlink to /mnt/c

```
❯ ls -la | grep project
lrwxrwxrwx  1 mystic mystic    39 Apr 24 19:58 projects -> /mnt/c/Users/Mystic/Documents/Projects/
```

2. WSL2

```
PS C:\Users\Mystic> wsl.exe --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         2 
```

3. I hope I did everything right, here is the log, including after changing the git branch
![image](https://user-images.githubusercontent.com/35394377/84763522-041b1500-afd5-11ea-96a5-2deea30c0e80.png)

**Comment by aeschli** [comment] 2020-06-16 11:12
Thanks for the detailed info!
Is git running on the Windows side? (`which git`).

**Comment by Mystic8b** [comment] 2020-06-16 11:24
On wsl I have git for linux
```
❯ git --version
git version 2.25.1
```

**Comment by dragondove** [comment] 2020-07-02 03:24
On wsl2 without git has a similar problem.
steps to reproduce:
1. open a folder in /mnt/d/Study/c/test using vscode.
2. delete some files in d:\Study\c\test by windows exploerer.
3. return to vscode but the file list is not update automatically.

![QQ截图20200702112150](https://user-images.githubusercontent.com/24190403/86312895-55bed300-bc56-11ea-9d5b-ff9f095af294.png)

**Comment by aeschli** [comment] 2020-07-02 09:36
@dragondove That's https://github.com/microsoft/WSL/issues/4739. File events caused by window tools, don't seem to be properly propagated to WSL.
I don't know if there are also file event issues when the change comes from a Linux tool.

I think the advice is to avoid the `/mnt/` mounts and have your file in the WSL file system `/home/..`.
That will also give you a far better performance.

**Comment by Mystic8b** [comment] 2020-07-02 09:41
In any case, this is a problem and needs to be solved. Many people use symlink for their projects. Otherwise, it will not be much better than a regular virtual machine.

**Comment by dragondove** [comment] 2020-07-02 09:48
@aeschli  I see. Using linux tools like touch/rm performs properly. Files which are not mounted also performs properly.

**Comment by aeschli** [comment] 2020-11-10 10:21
duplicate of https://github.com/microsoft/vscode-remote-release/issues/3959

**Closed by aeschli** 2020-11-10 10:21 UTC
Labels: wsl
