### ISSUE TITLE
On Remote-Containers 0.139.1, I can confirm that I can now "Open in Container" to get a devcontainer running on WSL2 Ubuntu Docker. This is an improvement over erroring about Docker Desktop.

### ISSUE THREAD

**Issue by kevinsuedmersen** [microsoft/vscode-remote-release#4873] opened 2021-04-13 17:20 UTC
On Remote-Containers 0.139.1, I can confirm that I can now "Open in Container" to get a devcontainer running on WSL2 Ubuntu Docker. This is an improvement over erroring about Docker Desktop.

However, the "Attach Visual Studio Code" option (available under Microsoft's Docker extension tab) seems to NOOP now (previously it threw an error about Docker Desktop not installed). I suspect this feature is related to the Remote Explorer...

_Originally posted by @feynmanliang in https://github.com/microsoft/vscode-remote-release/issues/3534#issuecomment-686733084_

----------------------------------------------------------------------------------------------------

When I try to open a Folder in a devcontainer with the Remote-Containers Extension in VS Code, I am still getting the error `docker command was not found. make sure docker is installed`. I only installed docker inside WSL2 (Ubuntu 20.04) and on from an Ubuntu shell, I can run all docker commands, but it seems like VS Code is not using docker installed in WSL.

Following information might help:

```
docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
docker-compose --version
docker-compose version 1.29.0, build 07737305
```

Remote-Containers Extension Version: v0.166.1

```
uname -r
4.19.128-microsoft-standard
```

**Comment by brettbevers** [comment] 2021-04-13 20:52
I started having this same issue this morning. When Docker is running in my Ubuntu WSL2, then VS Code attempts to launch Docker from the host; when Docker is not running in Ubuntu, it attempts to launch Docker in Ubuntu. What is the root cause?

**Comment by brettbevers** [comment] 2021-04-13 20:58
Logs when Docker is running in Ubuntu:
[10 ms] Remote-Containers 0.163.2 in VS Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d).
[59 ms] Start: Resolving Remote
[61 ms] Setting up container for folder or workspace: \\wsl.localhost\Ubuntu-18.04\home\brettbevers\code\row-platform
[63 ms] Start: Check Docker is running
[63 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[69 ms] findLocalWindowsExecutable: Exectuable 'docker' not found on PATH 'C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\brett\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\bin;C:\Users\brett\AppData\Local\Programs\Microsoft VS Code\bin'.
[77 ms] spawn \\wsl.localhost\Ubuntu-18.04\home\brettbevers\code\row-platform\docker ENOENT
[80 ms] Docker returned an error code ENOENT, message: spawn \\wsl.localhost\Ubuntu-18.04\home\brettbevers\code\row-platform\docker ENOENT

Logs when Docker is not running in Ubuntu:
[7 ms] Remote-Containers 0.163.2 in VS Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d).
[20 ms] Start: Run: wsl -d Ubuntu-18.04
[286 ms] Start: Run: wsl -d Ubuntu-18.04
[415 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/brettbevers/code/row-platform' && test '-f' '/home/brettbevers/code/row-platform/.devcontainer/devcontainer.json'
[1743 ms] Start: Run: wsl -d Ubuntu-18.04
[1917 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/brettbevers/code/row-platform' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\brett\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.2\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\brett\AppData\Local\Programs\Microsoft VS Code\Code.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\brett\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.2\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-c396dc39902b260e884d08a1ecb6a9836e6256b3-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='1' docker 'version' '--format' '{{.Server.APIVersion}}'
[2001 ms] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by chrmarti** [comment] 2021-04-21 07:55
This looks like https://github.com/microsoft/vscode-remote-release/issues/4789. Could you try with Remote-Containers 0.169.0 or later? Currently requires VS Code Insiders: https://code.visualstudio.com/insiders/

**Comment by kevinsuedmersen** [comment] 2021-04-21 16:32
Hi @chrmarti thanks for your answer. Yes Using VS Code Insiders and remote-containers v0.169.0 works indeed!

**Closed** 2021-04-21 16:32 UTC
Labels: containers, needs-more-info
