### ISSUE TITLE
Unable to obtain new-added sudo permission even exit and re-ssh

### ISSUE THREAD

**Issue by FredySu** [microsoft/vscode-remote-release#9022] opened 2023-09-26 01:48 UTC
- VSCode Version: 1.70.2 (extension version v0.84.0)
- Local OS Version: windows 11
- Remote OS Version: ubuntu 18.04
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

Steps to Reproduce:

1. (Computer A) connect remote os with a common user account
2. (Computer B) add the user to sudo users
3. (Computer A) exit and re-ssh remote os
4. (Computer A) or close vscode and reopen it, and then ssh
5. Found still no sudo permission

I guess it may happened because even i close the connection, vscode did not disconnect

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No, with mysql instead

**Comment by kkm000** [comment] 2023-09-26 07:12
You need to kill the remote VS SSH host and reconnect to it. There's no need to close VSCode. When you close VSCode, the Code Server may linger on the host for a while (15 min?), in case you'll reconnect soon. In the command drop-down, select "Remote-SSH: Kill Current VS Code Server" (command id `opensshremotes.cleanCurrentRemoteServer`). There is also a similar command that first asks on which machine you want to kill the server, "Remote-SSH: Kill VS Code Server on Host..."  (`opensshremotes.cleanRemoteServer`). Unfortunately, it may list more hosts than you have in fact connected to. After killing the server on the host, connect to host again.

This is likely by design; I cannot imagine how VSCode extension can possibly handle it for you. Adding a user to a group have no effect on the current login on both Un*x-like OSes (Linux, Mac OS), as group membership is normally established during login, and then inherited by all processes spawned by each other. The server is logged on as you, so even when you reconnect, you do to the same server with the same security group membership. Verify that you in fact disconnected from the host completely using VSCode's Process Explorer (Help/Process Explorer); it has separate trees for Local, WSL, SSH and Tunnel connections, and shows all VSCode processes under your local login, and remote processes spawned by them. Look before and after, and make sure that the remote has gone from the SSH subtree. Then reconnect.

<details>

**<summary>Rare situation with advanced SSH config:</summary>**

If you're using a shared Control Master SSH connection to the host (see man ssh_config(5), the setting `ControlMaster` other than the default `no`), the Control Master connection is the only one that leads the login session, while other connections multiplex over the master connection, and their shells inherit identity token from the master connection. The connection may not close even if you disconnect all windows and kill all code servers in case `ControlPersist`≠`no`. In such a case, the control master connection must be closed too before restarting the VS server, by issuing the `ssh -O exit <host-name-or-alias>` command, with *exactly the same argument* as that which was given to the original `ssh` command; if you initially connected to `ssh wardrobe-6`,[^1] then `ssh -O exit wardrobe-6.local` may not work, even though the machine and port are exactly the same. This is because there are up to two additional levels of indirection done by SSH when resolving the *alias* from command line to the actual machine name (`Host`/`Match` clauses possibly changing `Hostname`; and optional canonicalisation, either configured or forced with the `Match` clause's `canonical` or `final` operators). Read the same manual, `ControlPath` setting: it must evaluate to the same value for `ssh -O exit` to find the right connection to close. The command will tell you whether it in fact closed the shared connection or not.

[^1]: Have I just revealed where my comm/computer closet is situated?
</details>

**Closed** 2023-09-26 07:40 UTC
Labels: ssh
