### ISSUE TITLE
Remote-SSH - configure remote host via ssh instead of wget or direct web request

### ISSUE THREAD

**Issue by bosskwei** [microsoft/vscode-remote-release#161] opened 2019-05-06 02:10 UTC
Hi,
Remote develop is really an exciting feature for vscode, but there is still a little work to be improved I think, that is configure / download on remote by ssh connection. This is really needed for some server behind a firewall.

So, current steps are:
1. Local (Windows) configure ssh pubkey authentication.
2. Connect to remote (Linux).
3. Wget binary from https://vscode.microsoft.com
4. Install extensions from https://vscode.microsoft.com
4. Remote-SSH connection finish, ready to work.

And these may be better:
1. same
2. same
3. Copy binary from local to remote by ssh connection.
4. Install extensions by ssh connection, through local (Win) networks
4. same

// end

Thanks

**Comment by mklemarczyk** [comment] 2019-05-06 08:13
This is very important issue. We can not work with this at all. All our servers are hosted in isolated network. Those servers does not have access to the Internet. The manual installation can be performed or deliver package from developer workstation.

Can you add an option to manually disable this update process at least? We want to check new extension and help making it stable.

**Comment by ekerazha** [comment] 2019-05-07 12:40
I tried to use Remote SSH on a local server. The server doesn't have Internet access for security reasons.

A Remote SSH job tries to download VS Code Server through wget, but it fails because there's no Internet connection.

PyCharm doesn't have this issue because the "server" part gets uploaded by the client and it's not downloaded from the Internet.

Can you provide a procedure to upload the required VS Code Server through the VS Code client instead of relying on the server's Internet connection? Internet access for the server should not be mandatory.

Thank you.

**Comment by thernstig** [comment] 2019-05-11 12:19
Isn't this a duplicate of https://github.com/microsoft/vscode-remote-release/issues/15, which was opened 4 days before this?

**Comment by eddy-geek** [comment] 2019-05-12 10:16
In #15 the local machine has no connectivity either. Also this one better
describes possible solutions. But, they are closely related indeed.

**Comment by atomgalaxy** [comment] 2019-06-07 11:24
I need this too.

**Comment by mbronni** [comment] 2019-06-07 14:01
Same for me, no internet connection on remote machine but on client one. There is also no root/sudoer user on remote.

**Comment by mightypenguin** [comment] 2019-06-13 15:26
Also struggling with this.
It would probably be enough if there were documented steps for manually performing the installation on the server with a zip file.

**Comment by magic-lantern** [comment] 2019-06-14 18:20
I also would love to have this feature - some remote servers I work with have no outbound Internet access. It would be great if there were a configuration option to download all necessary files via my local Internet and push to remote server via SSH, then install there.

Manual instructions would also work, but ideally the Remote-SSH tool would handle everything for the user.

**Comment by gturbo** [comment] 2019-06-18 10:16
Isn't it possible in the meantime to do a manual install of the needed components ?
retrieve files from desktop machine, copy to remote server and deploy them in the expected location.

Could you provide some hints in the faq.
I can help if someone gives me some hints.

**Comment by Argonaute** [comment] 2019-06-19 07:13
I know that Microsoft wants everyone to work in the cloud and if possible Azure, but it's not possible for many reasons.
This request is legitimate for many developers, but seems poorly taken into account in products like VSCode or VisualStudio.
It is currently a brake on the massive adoption of these products which, I admit, are very functional as long as we stay connected.

**Comment by avylove** [comment] 2019-06-19 21:06
I create #738 requesting the extension utilize a system installed vscode server, which would be a much cleaner solution and more enterprise-friendly.

**Comment by BHANA1** [comment] 2019-07-18 14:32
We are also in VERY high demand of being able to perform the necessary tooling install without internet access.

This is a common theme among larger companies especially in the aerospace industry, where vital lab assets are blocked for security reasons from receiving outside internet access.

Is there any possible work around to make this happen?  Any future insight on when a local standalone installation package could become available for the server side remoting tools?

We love the VS Code ecosystem and would love to stay there, but are limited  in our remote development capabilities until a stand alone installer is produced.

Thanks much.

**Comment by xgdgsc** [comment] 2019-07-18 14:57
From a user perspective, we don' t want to bother system administrators just for installing/updating an editor. I want everything installed inside my home.

**Comment by caffeineaddiction** [comment] 2019-07-18 22:49
imo there should be 2x client side config options.
  - wget as it is currently setup
  - `ssh -R port` is used to create dynamic socks proxy on host and reverse forwarded to server and server uses .js functionality to reproduce wget through the socks proxy

as a work around I have done the following:

Desktop `~/.ssh/config`
```
...

Host *
  RemoteForward 54321

...
```

Remote: `~/bin/wget` in which `~/bin` is added to `PATH` via .bashrc
```
#!/bin/bash
export LD_LIBRARY_PATH=$HOME/opt/lib/tsocks/
export TSOCKS_CONF_FILE=$HOME/opt/tsocks/tsocks.conf
$HOME/bin/tsocks wget $@
```

note `tsocks` binary has been scp-ed to `~/bin/tsocks` and `~/opt/tsocks/` has been created with `libtsocks.so` which is normally stored in `/usr/lib64/libtsocks.so`

This is a work around that allows me to have wget functionality with out messing with anything outside my profile to get it to work (eg: no root required ... even though I have it).

**Comment by educhana** [comment] 2019-07-22 21:02
This is key. Many remote servers are firewalled.

**Comment by bro3cat** [comment] 2019-07-28 12:53
And another difference to pycharm is , **_remote-ssh in pycharm could remote into a docker container ,but vscode could not._**

**Comment by Chuxel** [comment] 2019-07-28 15:08
> And another difference to pycharm is , remote-ssh in pycharm could remote into a docker container ,but vscode could not.

@bro3cat This is off topic for this issue, but check out the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension for that capability. See [here for details](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host) on connecting to a remote docker host if that's what you are looking to do.  Please open a separate issue if you're hitting problems so we can take a look.

**Comment by vinlyx** [comment] 2019-07-31 16:14
Same for me, remote server does not have internet connection due to security reason.

**Comment by tbennett6421** [comment] 2019-08-02 19:09
subscribed, this would make our lives so much easier developing services that run on remote hosts. Until then, we can't use this application

**Comment by nathanptackett** [comment] 2019-08-09 17:55
This is a needed feature for enterprise development!

**Comment by caffeineaddiction** [comment] 2019-08-09 18:06
> subscribed, this would make our lives so much easier developing services that run on remote hosts. Until then, we can't use this application

see my previous comment for temp work around

https://github.com/microsoft/vscode-remote-release/issues/161#issuecomment-513020780

**Comment by dlithio** [comment] 2019-08-12 16:54
If you can't get @caffeineaddiction's fix working [#161 comment](https://github.com/microsoft/vscode-remote-release/issues/161#issuecomment-513020780), another workaround was posted on [stackoverflow by aviso](https://stackoverflow.com/questions/56718453/ssh-with-vscode-without-internet/56781109#56781109). It was easy for me to get the stackoverflow solution working, but I suspect it will be a bit more of a pain in the long run than the `tsocks` method here due to vscode/extension updates likely needing manual intervention if not disabled. I just couldn't get `tsocks` up and running, so it was nice to have a second option.

**Comment by Chuxel** [comment] 2019-08-30 18:05
@roblourens Wouldn't the setting added for #15 resolve this as well?

**Comment by roblourens** [comment] 2019-08-30 21:59
Yes, I think it's a duplicate. 

Please try installing the nightly version of the ssh extension, then setting `"remote.SSH.allowLocalServerDownload": true`. This should cause it to download the extension on your local machine then copy it over to the host via scp. Please file issues if you have any problems.

**Closed by roblourens** 2019-08-30 21:59 UTC
Labels: feature-request, ssh

**Comment by nsgexo** [comment] 2019-09-09 09:13
"remote.SSH.allowLocalServerDownload": true is working nicely ! 
Thanks a lot!!
