### ISSUE TITLE
DevContainer does not start with extensions' pre-release v0.314.0

### ISSUE THREAD

**Issue by keckelt** [microsoft/vscode-remote-release#9060] opened 2023-10-04 07:00 UTC
* VSCode Version: 1.83.0-insider (e7e037083ff4455cf320e344325dacb480062c3c).
* Local OS Version:
  * Windows 11 22H2 (0.0.22621.2361)
  * WSL version: 1.2.5.0 (Kernel version 5.15.90.1)
* Remote OS Version: WSL is running Ubuntu 22.04.3 LTS
* Remote Extension/Connection Type: Containers (v0.314.0)
* Docker Desktop: 4.23.0 (120376)
* `docker --version`:  24.0.6, build ed223bc

---

Hi!
The devcontainer I used to work with can no longer be started due to the error below:

**Logs:**

```
[60 ms] Dev Containers 0.314.0 in VS Code 1.83.0-insider (e7e037083ff4455cf320e344325dacb480062c3c).
[59 ms] Start: Run: wsl -d Ubuntu -e wslpath -u \\wsl.localhost\Ubuntu\home\klaus\ws\loops
[725 ms] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74755c5c686f6d655c5c6b6c6175735c5c77735c5c6c6f6f7073222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f6b6c6175732f77732f6c6f6f70732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d@wsl%2Bubuntu/workspaces/loops'
    at r.j (vscode-file://vscode-app/c:/Users/klaus/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:645:11397)
    at async r.exists (vscode-file://vscode-app/c:/Users/klaus/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:645:13603)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/c:/Users/klaus/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1861:2796
```

and VS Code shows that I am disconnected from Dev Container

**Steps to Reproduce:**

1. Open [Project](https://github.com/jku-vds-lab/loops) in VS Code Insiders 
2. _Reopen in Container_ via the popup prompt

**What I Tried to Fix:** 

* Rebuild and Reopen (with and without cache)
* Removing all docker containers (`docker system prune -f`)
* Updating Docker (now `docker --version` Docker version 24.0.6, build ed223bc)
* Restarting WSL (`wsl --shutdown`)
* Rebooting the machine
* Restarting the WSL Network (`Restart-Service LxssManager`), as suggest on [StackOverflow](https://stackoverflow.com/a/73639692/2549748)
* Removing `.vscode-server-insiders` and `.vscode-remote-containers` folders in my WSL home directory
* Resetting Docker to factory defaults 

However, none of the steps above changed the error logged to above.

After I realized the devContainer starts in VS Code (stable), I switched the DevContainer extension to release version (v0.309.0). With the currently released version it does start!

As soon as I switch back to pre-release, starting the DevContainer fails again with the above error.

These are the extension releases I tried:
* v0.314.0 fails 🔴 
* v0.313.0 fails 🔴 
* v0.313.0 fails 🔴 
* v0.312.0 fails 🔴 
* v0.311.0 works ✅ 
* v0.309.0 works ✅ 

I could not find any release notes, but hope this helps tracking down the issue. Let me know if I can provide further help.

---

Does this issue occur when you try this locally?: No
~Does this issue occur when you try this locally and all extensions are disabled?: Yes/No~

**Comment by ontoneio** [comment] 2023-10-04 22:28
I too am encountering similar issues as above. Output from my logs:

```bash
[2023-10-04T21:57:01.391Z] Dev Containers 0.315.0 in VS Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d).
[2023-10-04T21:57:01.391Z] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\vscode\projects\web-cms
[2023-10-04T21:57:01.739Z] Stop (348 ms): Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\vscode\projects\web-cms
[2023-10-04T21:57:01.833Z] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74752d32322e30345c5c686f6d655c5c7673636f64655c5c70726f6a656374735c5c7765622d636d73222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f7673636f64652f70726f6a656374732f7765622d636d732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d@wsl%2Bubuntu-22.04/workspaces'
    at r.j (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:630:11395)
    at async r.exists (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:630:13602)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1855:2796
```

**Comment by connorwehrum** [comment] 2023-10-04 23:22
Hello! Getting similar issues on all containers, just won't build. It works fine on Windows itself, but as soon as I try on WSL it breaks.

```
The editor could not be opened due to an unexpected error: Unable to resolve resource vscode-remote://dev-
container%2B7b22686f737450617468223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74755c5c686f6d655c5c636f6
e6e6f7277656872756d5c5c7265706f735c5c746573745c5c6e657766756e63222c226c6f63616c446f636b6572223a66616c73652c
22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f636f6e6e6f7277656872756d2f7265706f
732f746573742f6e657766756e632f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656
d65223a227673636f64652d66696c65486f7374227d7d@wsl%2Bubuntu/workspaces/test/newfunc
```

Not getting any kind of console output, just simply tries to open the window and nothing happens. I don't think it even attempts to build the container.

Happening on a fresh Docker image from Azure Functions (`func host init newfunc --docker`)

![image](https://github.com/microsoft/vscode-remote-release/assets/125694861/8c21c921-3d8c-489a-8e7f-445c57c8fb8e)

**Dockerfile:**

```docker
# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/python:4-python3.10-appservice
FROM mcr.microsoft.com/azure-functions/python:4-python3.10

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY requirements.txt /
RUN pip install -r /requirements.txt

COPY . /home/site/wwwroot
```

**devcontainer.json:**
```json
{
	"name": "Existing Dockerfile",
	"build": {
		"context": "..",
		"dockerfile": "../Dockerfile"
	}
}
```

**extensions.json:**
```json
{
    "recommendations": [
        "ms-azuretools.vscode-azurefunctions"
    ]
}
```

**Comment by RhysP88** [comment] 2023-10-04 23:58
Downgrading to version v0.309.0 worked for me as well after I was receiving this error.

**Comment by enjibby** [comment] 2023-10-05 02:04
I also found that, in the most recent release, devcontainer projects that previous worked now failed to load, in particular that they showed "Disconnected from dev-container" in the remote section of the status bar with little visible information. I went digging through various output/log screens and eventually found the "ENOPRO: No file system provider found for resource 'vscode-remote://dev-container..." text that led me to this issue.

When I downgraded to v0.309.0 as per @connorwehrum, all was well with the world again. Thankyou for this temporary workaround, it is a lifesaver!

**Comment by ManfredLange** [comment] 2023-10-05 04:24
Looks as if this bug was "shipped" as part of version 0.315 despite it having been reported for the pre-release.

This bug is still present in 0.315 on Windows, WSL2, Docker, all on the latest stable version. I went back to 0.309.0 which resolved it (for the most part).

**Comment by rvodden** [comment] 2023-10-05 06:04
I'm seeing the exact same thing. Rolling back to 0.309 resolved it for me.

**Comment by mcanouil** [comment] 2023-10-05 09:51
FYI, I posted first on another issue but might be related to this one or a more general issue:
- https://github.com/microsoft/vscode-remote-release/issues/9064#issuecomment-1748506266

**Comment by chrmarti** [comment] 2023-10-05 12:01
Fixed in 0.315.1 and 0.317.0-pre-release. Please give one of these a try and let me know if you still see the `ENOPRO: No file system provider found for resource 'vscode-remote://dev-container...` error. Thanks!

**Closed by chrmarti** 2023-10-05 12:02 UTC
Labels: bug, containers, candidate

**Comment by rvodden** [comment] 2023-10-05 12:28
Fixed for me with 0.317.0 - thanks for turning that around so quickly!

**Comment by keckelt** [comment] 2023-10-05 14:52
v0.315.1 and v0.317.0 both work for me. Thank you ❤️

**Comment by akrizs** [comment] 2023-10-05 19:09
is there any difference when using a dockerfile, a image directly from the registry, or targetting a service specified in a docker-compose file? i'm getting this error, using docker-compose and targetting the dev container...

**Comment by enjibby** [comment] 2023-10-06 02:45
Excellent response time! 0.315.1 works for me.

**Comment by JNaranjo-Alcazar** [comment] 2023-10-06 07:49
which version of vscode are you using? 1.83.0 are not working with DEV Containers (0.315.1 or 0.317) for me 😢 
1.78.2 vscode and 0.309 dev containers is working for me

**Comment by keckelt** [comment] 2023-10-06 08:50
> which version of vscode are you using? 1.83.0 are not working with DEV Containers (0.315.1 or 0.317) for me 😢 

I'm using 1.84:
![image](https://github.com/microsoft/vscode-remote-release/assets/10337788/8b197062-f028-454f-8afe-2436b9abfaef)

**Comment by slawomir-kluz-openx** [comment] 2023-10-06 10:16
The issue still exists:
- VSCode Version: 1.83 (e7e037083ff4455cf320e344325dacb480062c3c)
- macOS 13.6 Darwin (22G120) Apple M1 Pro
- Docker Desktop: 4.24.0 (122432)
- Dev Containers: v0.317.0

**Comment by chrmarti** [comment] 2023-10-09 07:14
If you still see the `ENOPRO` issue with WSL: Make sure to rerun the initial command (like `Reopen in Container`, `Attach to Running Container`). The bug was that these created a non-working URI and opened VS Code on that, you might still have that URI in your recent folders history.

Note that there is another issue with 0.315.1 and 0.317.0 when connecting through a SSH server, see https://github.com/microsoft/vscode-remote-release/issues/9064#issuecomment-1749191392 for a workaround for that.

**Comment by Telcrome** [comment] 2023-10-09 09:16
Rollbacking to `v0.309.0` from `0.315.1` also fixed an error for me where the `localEnv` was always empty. I was using SSH.

**Comment by chrmarti** [comment] 2023-10-09 12:03
@Telcrome Continuing in #9081, thanks.

**Comment by kt-alt** [comment] 2023-10-10 21:01
I've tried .309 and also the prelease .318 but am still encountering ENOPRO error.

I am doing running my devcontainers remotely (ie vscode on laptop, devcontainers on server).  Not sure if that matters (ie some stuff needs fixing on the remote server).

Strangely there are a one or two really simple devcontainers that still work but most of the ones that matter for me don't.

Any suggestions to resolve?  I was going to try to recreate the devcontainers next, but this will be a bit of pain.

**Comment by duduribeiro** [comment] 2023-10-11 03:06
With VSCode 1.83.0 and DevContainers 0.318.0 pre-release didn't work for me. still receiving ENOPRO error. running devcontainers on laptop with Mac ARM

**Comment by chrmarti** [comment] 2023-10-11 06:32
@kt-alt @duduribeiro Could you file new issues with the log from such a failure? (`F1` > `Dev Containers: Show Container Log`) The ENOPRO often is just a follow-up error and does not include information about the root cause.

**Comment by kt-alt** [comment] 2023-10-12 07:25
You're right, there was a linting error that wasn't picked up by the editor that caused a build error.

After cleaning that up I'm able to load up the devcontainer again.

My bad.  Thanks for hint.

**Comment by eliasdjup** [comment] 2023-10-27 12:42
@chrmarti I still get this error with Dev Containers:0.315.1, Docker Desktop:4.24.2, VSCode 1.83.1, and using WSL2

devcontainer.json
```json
{
  "name": "example",
  "dockerFile": "Dockerfile",
  "forwardPorts": [8080],
}
```

Dockerfile
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0

ENV DOTNET_USE_POLLING_FILE_WATCHER=1 \
    DOTNET_CLI_TELEMETRY_OPTOUT=1

RUN apt-get update && apt-get install -y git curl terraform
```

Error when running Rebuild and Reopen in Container

`Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container`
