### ISSUE TITLE
markdown preview not woking properly

### ISSUE THREAD

**Issue by Subratappt** [microsoft/vscode-remote-release#1657] opened 2019-10-12 18:06 UTC
Issue Type: <b>Bug</b>

code formatting and styling in markdown preview is not working properly.
1.  Preview of file in local
![Screen Shot 2019-10-12 at 11 33 22 PM](https://user-images.githubusercontent.com/40207448/66705797-f546d900-ed48-11e9-9dac-0748d070e1eb.png)

2. Preview of file in Remote-SSH
![Screen Shot 2019-10-12 at 11 32 13 PM](https://user-images.githubusercontent.com/40207448/66705803-02fc5e80-ed49-11e9-9c4a-d0d79fde8584.png)

Extension version: 0.47.1
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 17.7.0
Remote OS version: Linux x64 3.10.0-957.27.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.59GB free)|
|Process Argv|-psn_0_360536|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Server18|
|OS|Linux x64 3.10.0-957.27.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (20 x 800)|
|Memory (System)|30.82GB (6.99GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment] 2019-10-15 03:27
Can you include the text of the file?

**Comment by Subratappt** [comment] 2019-10-15 03:41
> Can you include the text of the file?
> 
> Are you missing an extension that needs to be installed on the remote?


https://github.com/microsoft/vscode/issues/82439#issuecomment-541742094

**Comment by mjbvz** [comment] 2019-10-25 00:33
Duplicate of microsoft/vscode#82439. Please don't open the same issue in multiple repositories

**Closed by mjbvz** 2019-10-25 00:33 UTC
