### ISSUE TITLE
Install remote extensions from local sources

### ISSUE THREAD

**Issue by llowder** [microsoft/vscode-remote-release#2902] opened 2020-04-30 19:28 UTC
This is somewhere in between a bug report and a feature request.

When connecting to a remote host, it is possible to install the vscode-server from the local system, but then it tries to install extensions on the remote host from the internet, with no fallback to installing from the local computer.

the servers I am working with, do not have direct internet access, so I need to either be able to install from my local machine, or set up an in network mirror (for example using Artifactory or a local https based fileserver).

Being able to have it not even try to install from the net would be a nice thing as well.

**Comment by chrmarti** [comment] 2020-10-13 09:00
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/1399

**Closed by chrmarti** 2020-10-13 09:00 UTC
