### ISSUE TITLE
[Remote - Containers ] - Auto port forward only works for IPv4 address

### ISSUE THREAD

**Issue by rickardgranberg** [microsoft/vscode-remote-release#5551] opened 2021-09-06 14:15 UTC
- VSCode Version: 1.60.0
- Local OS Version: Windows_NT x64 10.0.19043
- Remote OS Version: Debian GNU/Linux 11 (bullseye)
- Remote Extension/Connection Type: Docker
- Logs:

Steps to Reproduce:

We're seeing this problem when running a simple web server application written in Go. Using the default "tcp" option to the Listen call, the auto forwarding fails. If we use "tcp4", it works. Please note that this is a regression. Prior to VSCode 1.60.0, this all worked fine!

The problem can be reproduced using nc/netcat:
1. Run: `nc -l 127.0.0.1 8080` inside the container - this auto forward port works fine. (i.e. it can be reached using http://localhost:8080 from local)
2. Run `nc -l :: 8080` inside the container - this auto forward port does not work. (i.e. it can not be reached using http://localhost:8080 from local)

**Comment by alexr00** [comment] 2021-09-20 13:39
@rickardgranberg I'm not familiar with netcat. I tried running `nc -l :: 8080` inside a container, but I get `::: forward host lookup failed: Unknown host`. Is there another simple way to repro the issue?

**Comment by rickardgranberg** [comment] 2021-09-24 06:29
> @rickardgranberg I'm not familiar with netcat. I tried running `nc -l :: 8080` inside a container, but I get `::: forward host lookup failed: Unknown host`. Is there another simple way to repro the issue?

I chose netcat as that would not require you to write any code, but an alternative way is to write a piece of code that starts a socket listen using the address `":<port>/tcp"`, for example `":8080/tcp"`. That same code with the local address of `"localhost:8080/tcp4`" or `"127.0.01:8080/tcp4"` will work fine, because that will only use the IPv4 address. I didn't manage to get a screenshot, but while hovering over the "Auto Forwarded" text in the "Ports" window, I can see that the address is forwarded as "0:0:0:0:0:0:0:0:8080"

**Comment by alexr00** [comment] 2021-09-24 07:52
@rickardgranberg thanks for the reply! This should be fixed in 1.60.2 now. Duplicate of https://github.com/microsoft/vscode-remote-release/issues/5613

**Closed by alexr00** 2021-09-24 07:52 UTC
Labels: containers, needs more info
