### ISSUE TITLE
Default Distro should be the first result in the distro selector

### ISSUE THREAD

**Issue by spersico** [microsoft/vscode-remote-release#3259] opened 2020-06-26 15:05 UTC
I use this extension mostly for web development with WSL2, which I believe is one of the most common cases.

So, it would be cool if the default distro is the first option in the menu, or to be able to just skip entirely this menu with some config, and just launch the default distro.
![image](https://user-images.githubusercontent.com/10502605/85868181-53650080-b7a0-11ea-8ef1-247cd047b8d6.png)

**Comment by aeschli** [comment] 2020-09-11 14:32
duplicate of #3606

**Closed by aeschli** 2020-09-11 14:32 UTC
Labels: wsl
