### ISSUE TITLE
can not rendering third-party extension's icon at activity bar

### ISSUE THREAD

**Issue by CFhM** [microsoft/vscode-remote-release#938] opened 2019-07-09 08:02 UTC
Issue Type: <b>Bug</b>

How to reproduce: just install the extensions mentioned below on WSL, open a c++ repo.

known extensions: GitLens, Bookmarks, C++ Intellisense(find all reference)

further more: the tiny bookmarks near line number which appears when you toggle a bookmark of your code can not be rendered either.

Screen Shots
![image](https://user-images.githubusercontent.com/26785781/60870011-9877e600-a262-11e9-9623-8050cac5d7ef.png)

Extension version: 0.38.8
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|15.88GB (7.37GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment] 2019-07-13 06:24
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/687

**Closed by roblourens** 2019-07-13 06:24 UTC
