### ISSUE TITLE
WSL fails strangely on startup

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-release#1970] opened 2019-12-04 13:53 UTC
Using WSL after waking my computer from sleep resulted in 

```
[2019-12-04 13:51:41.536] Resolving wsl+ubuntu, resolveAttempt: 1
[2019-12-04 13:51:41.652] Starting VS Code Server inside WSL (u)
[2019-12-04 13:51:41.653] Extension version: 0.41.2, Windows build: 19033. Multi distro support: available. WSL path support: enabled
[2019-12-04 13:51:41.864] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d u -e sh -c "[ -d ~/.vscode-server-insiders/bin/43e3581aa635406ada2d8138d7ee242ddabefc1c ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2019-12-04 13:51:41.961] Unable to detect if server is already installed: Error: Command failed: C:\WINDOWS\System32\wsl.exe -d u -e sh -c "[ -d ~/.vscode-server-insiders/bin/43e3581aa635406ada2d8138d7ee242ddabefc1c ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2019-12-04 13:51:41.961] Launching C:\WINDOWS\System32\wsl.exe -d u sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 43e3581aa635406ada2d8138d7ee242ddabefc1c insider .vscode-server-insiders 0  ' in c:\Users\dirkb\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.41.2
[2019-12-04 13:51:42.051] There is no distribution with the supplied name.
[2019-12-04 13:51:42.051] 
[2019-12-04 13:51:42.054] VS Code Server for WSL closed unexpectedly.
[2019-12-04 13:51:42.054] For help with startup problems, go to
[2019-12-04 13:51:42.054] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
```

**Comment by dbaeumer** [comment] 2019-12-04 13:53
Interesting is: `Unable to detect if server is already installed:`

**Comment by dbaeumer** [comment] 2019-12-04 13:54
Please also notice that the actual time is 2:54. So may be the WSL date / time bug is causing some strange behaviour.

**Comment by dbaeumer** [comment] 2019-12-04 13:58
Another hint: I have Docker running on top of a WSL 2 VM. May be this is causing problems in the detection.

**Comment by puco** [comment] 2019-12-04 13:59
For me the time is UTC, so that should not be the case. The problem is that the extension passes 'u' as distro name, even though it detects that (in your case) 'ubuntu' is your distribution name.

**Comment by puco** [comment] 2019-12-04 14:01
Duplicate of #1962 ?

**Comment by dbaeumer** [comment] 2019-12-04 14:17
Closing docker didn't help either.

**Comment by aeschli** [comment] 2019-12-04 14:23
found the issue. Published ms-vscode-remote.remote-wsl@0.41.3

**Comment by aeschli** [comment] 2019-12-04 14:24
dup of  #1962

**Closed by aeschli** 2019-12-04 14:23 UTC
