### ISSUE TITLE
WSL2 + Remote Containers -- failing to forward host ssh-agent

### ISSUE THREAD

**Issue by issacg** [microsoft/vscode-remote-release#3392] opened 2020-07-19 14:51 UTC
- VSCode Version: 1.47.2
- Local OS Version: 19041.388
- Remote OS Version:
- Remote Extension/Connection Type: WSL2 + Docker for Windows

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Based on the latest best practices outlined at https://code.visualstudio.com/blogs/2020/07/01/containers-wsl the optimal workflow of working with containers is Windows host <--> WSL2 <--> Docker  

Before setting that up, I'd been using the ssh-agent service in the windows host, and using remote containers bind mounted directly to the host, and everything worked just fine.

When setting that WSL2,  I set it up ssh-forwarding to WSL-land via `npiperelay` and the `SSH_AUTH_SOCK` environment variable, and that worked fine, too.

However, when using a remote container connection opened from the WSL2 remote as described in the above blog post, I'm suddenly unable to use the ssh-agent's keys (inside the "remote container")

From https://github.com/microsoft/vscode-remote-release/issues/106 it looks like the ssh agent forwarding magic is powered by https://github.com/ensody/ssh-agent-inject which I would expect to "just work" regardless of what I'm doing in WSL2 land since there's only one docker daemon, running in the host, and it should see the named pipe regardless of where I open a container from...

Any idea on what could be wrong?

**Comment by whefter** [comment] 2020-07-20 07:22
I am also having this issue. Running KeePass + KeeAgent in Windows, forwarded to WSL2 using `weasel-pageant`.

From what I can see it looks like the issue is that the Docker commands that are run by the extension to spin up the containers do not run inside a shell.
All methods of setting `SSH_AUTH_SOCK` inside WSL2 known to me rely on `.bashrc` or similar, which is then not executed since the commands do not run in a shell. SSH_AUTH_SOCK is set per-shell, much like SSH agent forwarding.
I'm not sure what side-effects running the commands inside a shell would cause.

It seems that a running `pageant` is also not forwarded when running Containers without WSL2, though perhaps this is due to my using KeeAgent and not `pageant`.
Perhaps forwarding a running `pageant` socket into the Containers, regardless of whether they are run from Windows or WSL2, would be a solution?

**Comment by Chuxel** [comment] 2020-08-05 17:14
Closing as a dupe of #2925 which should be resolved in insiders.  Feel free to reopen if you think this is in error.

**Closed by Chuxel** 2020-08-05 17:14 UTC
Labels: containers

**Comment by chrmarti** [comment] 2020-08-06 07:41
Fixed with #2925
