### ISSUE TITLE
ssh targets gone after recent update

### ISSUE THREAD

**Issue by elnotcho** [microsoft/vscode-remote-release#2529] opened 2020-03-11 16:17 UTC
Issue Type: <b>Bug</b>

Selecting Remote Explorer, or hitting SSH Targets 'refresh' gives error 

this.historyData[e].forEach is not a function

List of SSH targets is missing.  Recreated ~/.ssh/config file, and reverted extension but issue persists.  VSCode Insiders version is working  with remote ssh.

Extension version: 0.50.0
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment] 2020-03-11 19:04
Do you see that error with the latest version, or after reverting the extension?

**Comment by elnotcho** [comment] 2020-03-12 12:51
See it in latest, and after reverting.  Also tried removing extension and re-install.  Also removed VSCode and re-installed.  Same error persists.

**Comment by elnotcho** [comment] 2020-03-16 13:07
> 
> 
> See it in latest, and after reverting. Also tried removing extension and re-install. Also removed VSCode and re-installed. Same error persists.

Also, issue persists in older versions of extension.  Suspect that if I could completely remove vscode and extensions then re-install it would remedy.

**Comment by nstansby** [comment] 2020-03-17 00:46
Same problem; tried the complete VSCode uninstall / reinstall (and moved my .vscode folder out of the way while it was uninstalled).  Does **not** remedy the problem!

**Comment by chia56028** [comment] 2020-03-21 11:08
I got the same problem after update "Remote - SSH".
Can I revert to original vision???

**Comment by fredludlow** [comment] 2020-03-30 08:11
I've hit this bug too, and reverting to 0.49.0 doesn't work for me as it breaks things on the remote (it's a shared account on the remote and other devs are presumably using the latest version there? - anyway, another workaround below). 

However, I think the problem is due to an entry in my ssh config file (Users\%username%\.ssh\config) for which VSCode has generated some broken local data (the history data perhaps? :) ). My guess is there's a historyData object which maps Host entries in .ssh\config to an array and there's no check that the array isn't undefined before iterating over it.

Workaround: If I comment out this host or rename it (use an alias) it also works. i.e.

```
Host some-alias
    Hostname actual.host.address
    User some-user
    ...
```
becomes 
```
Host some-alias-fixed
     <everything else the same>
```

**Comment by elnotcho** [comment] 2020-03-30 13:25
> 
> 
> Edited slightly for clarity:
> 
> I've hit this bug too, and reverting to 0.49.0 doesn't work for me as it breaks things on the remote (it's a shared account on the remote and other devs are presumably using the latest version there? - anyway, another workaround below).
> 
> However, I think the problem is due to an entry in my ssh config file (Users%username%.ssh\config) for which VSCode has either generated some broken local data (the history data perhaps :) ) or not generated any data at all. (Actually, my guess is there's a historyData object which maps Host entries in .ssh\config to an array of history entries and there's no check that the array isn't undefined before iterating over it.)
> 
> Workaround: If I comment out this host or rename it (use an alias) it also works. i.e.
> 
> ```
> Host some-alias
>     Hostname actual.host.address
>     User some-user
>     ...
> ```
> 
> becomes
> 
> ```
> Host some-alias-fixed
>      <everything else the same>
> ```

Great workaround!  Works for me.  TY

**Comment by fredludlow** [comment] 2020-03-30 17:48
@elnotcho - should this be closed yet? I think it's still a bug (however we've all managed to do it, it's possible to get Code into a state which breaks in a hard-to-understand way).

**Comment by ahmednrana** [comment] 2020-04-09 08:57
> Edited slightly for clarity:
> 
> I've hit this bug too, and reverting to 0.49.0 doesn't work for me as it breaks things on the remote (it's a shared account on the remote and other devs are presumably using the latest version there? - anyway, another workaround below).
> 
> However, I think the problem is due to an entry in my ssh config file (Users%username%.ssh\config) for which VSCode has either generated some broken local data (the history data perhaps :) ) or not generated any data at all. (Actually, my guess is there's a historyData object which maps Host entries in .ssh\config to an array of history entries and there's no check that the array isn't undefined before iterating over it.)
> 
> Workaround: If I comment out this host or rename it (use an alias) it also works. i.e.
> 
> ```
> Host some-alias
>     Hostname actual.host.address
>     User some-user
>     ...
> ```
> 
> becomes
> 
> ```
> Host some-alias-fixed
>      <everything else the same>
> ```

For me its still not working. 
By the way the same file works for me in vs code insiders.

**Comment by jorymorrison** [comment] 2020-04-21 20:16
Also seeing this, on 0.51.0, 0.50.1, and 0.50.0. 

OpenSSH_for_Windows_8.1p1

Reverting to .49 fixed this for me.

**Comment by roblourens** [comment] 2020-08-03 04:04
Sorry for the late response here. I am not sure what the issue is. I pushed a change that works around it. It will be in the next "nightly" build of the extension, out in about 12 hours from now. It might not restore your old history but if you are seeing the error or not collecting history, it will fix that at least.

**Closed** 2020-11-10 00:53 UTC
Labels: bug, ssh

**Comment by roblourens** [comment] 2020-11-10 00:54
I think a change awhile ago to storing ssh target state was not handled correctly, but I haven't gotten reports of this in awhile, this should be resolved by now..
