### ISSUE TITLE
When I open vscode with Remote Development extensions, my cpu occupy nearly 100%

### ISSUE THREAD

**Issue by chriszhao001** [microsoft/vscode-remote-release#5583] opened 2021-09-14 02:03 UTC
- VSCode Version: 1.60.0
- Local OS Version: Windows 10 19042.1165
- Remote OS Version: WSL2  Ubuntu-20.04
- Remote Extension/Connection Type: WSL2
- Logs:

Steps to Reproduce:

1. Open vscode with Remote Development extensions and open a directory in WSL2
2. CPU occupy nearly 100%

Below is my computer task manager 
![image](https://user-images.githubusercontent.com/17903065/133182798-fb087536-fd25-4eca-9865-1216f3a36ed1.png)

and below is my wsl2 "top" command show
![image](https://user-images.githubusercontent.com/17903065/133181849-453b921e-ff5d-41da-a8f7-763935d79520.png)

After I close vscode also still open WSL2, every things seems OK.
![image](https://user-images.githubusercontent.com/17903065/133181992-f6c26bbf-d422-4d75-b398-3785cb88a91a.png)

![image](https://user-images.githubusercontent.com/17903065/133182023-5780185f-b3c2-454e-b762-19ea2c33f49f.png)

I have try many times to find what has happened, include:
uninstall all vscode extensions
reinstall vscode
reinstall WSL2
It now looks like when I run vscode and connect to WSL2 on my machine, there is a “node” task running continuously (when I use WSL1 it will show up in the task manager, when I upgrade to WSL2 it will show up in the top command in WSL2), taking up all the computing resources on my computer.

Please help. 
Thanks.

**Comment by bamurtaugh** [comment] 2021-09-28 23:59
Thanks for reporting @chriszhao001! I think we can close as a dupe of https://github.com/microsoft/vscode-remote-release/issues/5595. If this issue feels separate, please just let me know, and happy to discuss further.

**Closed by bamurtaugh** 2021-09-28 23:59 UTC
Labels: wsl
