### ISSUE TITLE
Remote connections fail with `405 Method not allowed` when user has `continue` flag in wgetrc

### ISSUE THREAD

**Issue by bbock** [microsoft/vscode-remote-release#6900] opened 2022-07-07 14:16 UTC
- VSCode Version: 1.68.1
- Local OS Version: Mac OS Monterey (12.4)
- Remote OS Version: Debian Linux Bookworm
- Remote Extension/Connection Type: SSH
- Logs:

```
[16:10:46.390] Server status check failed - waiting and retrying
[16:10:46.390] Terminating local server
[16:10:46.395] Local server exit: 15
[16:10:47.395] askpass server listening on /var/folders/64/wh718pd51t7cpjbpjwjtjs180000gn/T/vscode-ssh-askpass-bbb8b8577b953c50770c0a8bf8efeeda43047c07.sock
[16:10:47.396] Spawning local server with {"serverId":30,"ipcHandlePath":"/var/folders/64/wh718pd51t7cpjbpjwjtjs180000gn/T/vscode-ssh-askpass-ea3eb834dcc8ce002899a8ba54f3b4ad39820f0f.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","62824","-o","ConnectTimeout=15","ysop"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/bernhard/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-80c7666a-30d9c6cd9483b2cc586687151bcbcd635f373630-0.82.1/data.json"}
[16:10:47.396] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.850gjU2RCY/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/bernhard/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/bernhard/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/64/wh718pd51t7cpjbpjwjtjs180000gn/T/vscode-ssh-askpass-bbb8b8577b953c50770c0a8bf8efeeda43047c07.sock"}
[16:10:47.397] Spawned 67800
[16:10:47.563] > local-server-30> Spawned ssh, pid=67809
[16:10:47.567] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[16:10:47.581] > ready: 963ca492ea01
[16:10:47.587] > Linux 5.19.0-rc4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19~rc4-1~exp1 (2022-07-01)
[16:10:47.587] Platform: linux
[16:10:47.591] > /bin/zsh
[16:10:47.591] Shell: zsh
[16:10:47.591] Creating bash subshell inside "zsh"
[16:10:47.596] > bash version:  5.1.16(1)-release
[16:10:47.607] > 963ca492ea01: running
[16:10:47.631] > Acquiring lock on /home/bernhard/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/vscode-remote-lock.bernhard.30d9c6cd9483b2cc586687151bcbcd635f373630
[16:10:47.635] > Found existing installation at /home/bernhard/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630...
> Checking /home/bernhard/.vscode-server/.30d9c6cd9483b2cc586687151bcbcd635f373630.log and /home/bernhard/.vscode-server/.30d9c6cd9483b2cc586687151bcbcd635f373630.pid for a running server
[16:10:47.637] > Looking for server with pid: 7810
[16:10:47.648] > Found running server...
[16:10:47.648] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[16:10:47.655] > Checking server status on port 33385 with wget
[16:10:47.657] > http://127.0.0.1:33385/delay-shutdown: 2022-07-07 16:10:47 FEHLER 405: Method Not Allowed.
> 963ca492ea01: start
> exitCode==28==
> listeningOn==33385==
> osReleaseId==debian==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
[16:10:47.658] > 963ca492ea01: end
[16:10:47.659] Received install output: 
exitCode==28==
listeningOn==33385==
osReleaseId==debian==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
[16:10:47.659] Server status check failed - waiting and retrying
```

Steps to Reproduce:

1. create a file `~/.wgetrc` that contains the line `continue=on` on the remote
2. open a connection to remote. This works the first time, will fail subsequently
3. try to open a folder or re-connect to the remote

This can also be reproduced by manually calling `wget -c http://127.0.0.1:33385/delay-shutdown` (please note the `-c` flag for continuation).

Does this issue occur when you try this locally?: No

**Comment by eleanorjboyd** [comment] 2022-12-09 22:18
Hello! My name is Eleanor and I am the new maintainer for the Remote-SSH extension. Are you still experiencing this issue? Thanks

**Comment by Enzime** [comment] 2022-12-11 04:01
@eleanorjboyd I can still reproduce this issue using `Remote - SSH` on version `0.94.0`

**Comment by eleanorjboyd** [comment] 2022-12-12 15:47
From what I understand the continue flag allows the server to continue the downloading process instead of starting a duplicate of the same file? Is this correct? Could you clarify why this is useful to you for your setup so I can better understand your situation? Thanks!

**Comment by Enzime** [comment] 2022-12-12 22:37
@eleanorjboyd On the computer I want to SSH into, I use `wget` to download large files but I don't want to manually specify `--continue` each time I call `wget` so I added `continue=on` to `~/.wgetrc`. The easiest fix as far as I'm aware is to call `wget` with `--no-continue` from the VS Code extension which prevents the `405: Method Not Allowed`.

**Comment by bbock** [comment] 2022-12-13 17:07
Just to re-iterate on the comment by @Enzime : `continue=on` is a good default setting to continue interrupted downloads instead of restarting them. It works with a lot of web servers and - for any other use case I managed to find - does not harm: If a webserver providing downloads cannot support the continuation of downloads, it just starts again from the beginning. As far as I am aware, getting a `405 Method not allowed` is not a common response at all to this request.

**Comment by eleanorjboyd** [comment] 2022-12-15 19:30
Hello! Thank you for your clarifying comments here. We do not directly control our CDN and therefore do not set the rules there. For this reason, this task to allow this setting would be fairly large and out of scope for our current work.

**Comment by Enzime** [comment] 2022-12-15 23:35
@eleanorjboyd the fix required for this is not on the CDN side, all that is necessary is changing the extension code to use the flag `--no-continue` when running the program `wget` which would mean that it wouldn't trigger the `405: Method Not Allowed`.

**Comment by eleanorjboyd** [comment] 2022-12-19 19:04
Understood thanks for clarifying. We are looking into disabling wgetrc and curlrc due to errors like this and so it is connected to this issue here: https://github.com/microsoft/vscode-remote-release/issues/3906. I will re-open as a that as the solution we are looking for instead. Thanks

**Comment by joshspicer** [comment] 2024-07-22 19:02
While I couldn't repro this specific bug anymore, a relevant change (ignoring `wgetrc` configuration files) that may solve more general issues in this realm will land in the pre-release extension ~tomorrow.

More info: https://github.com/microsoft/vscode-remote-release/issues/3906#issuecomment-2243620716

**Closed by joshspicer** 2024-07-22 19:02 UTC
Labels: ssh

**Comment by joshspicer** [comment] 2024-07-24 21:06
I posted validation steps at the link below, which can be used to validate this issue as well:

https://github.com/microsoft/vscode-remote-release/issues/3906#issuecomment-2248896429

**Comment by connor4312** [comment] 2024-07-24 22:18
This probably changed with our move to a new CDN a few months ago. Perhaps the old CDN didn't support HEAD requests that wget might have used to implement continue (just spitballing)
