### ISSUE TITLE
Remote WSL - could not fetch remote environment

### ISSUE THREAD

**Issue by xiki808** [microsoft/vscode-remote-release#3500] opened 2020-08-11 15:35 UTC
Searched a lot with no successful result. Same issue as #3212 

- VSCode Version: 1.47.3
- OS Build: 19041.423
- OS Version: 2004

System is up to date ( Windows 10 Pro )

Steps to Reproduce:

1. Click on the Open a Remote Window in the status bar -> Remote WSL: New Window

![image](https://user-images.githubusercontent.com/8024321/89916868-6751ae00-dbf8-11ea-9194-4a5a4d22cba0.png)

OR

2. project with DockerFile -> from ubuntu ( 18.04 ) command: code .
3. After a while, while setting up the container: The window has crashed. Container logs as "Container started" on docker dash

![image](https://user-images.githubusercontent.com/8024321/89917805-8997fb80-dbf9-11ea-89b3-1dd050e4c901.png)

For more logs please let me know how I can provide more.

In ubuntu: uname -a

![image](https://user-images.githubusercontent.com/8024321/89917093-b13a9400-dbf8-11ea-8eac-02ca1c860ea8.png)

I updated the kernel manually by following instructions [here](https://github.com/microsoft/WSL/issues/5529#issuecomment-653625309). I downloaded and manually placed the kernel in the directory.

Please let me know if I need to provide more info.

**Comment by aeschli** [comment] 2020-08-24 06:53
Can you paste the full WSL log? (Command: Remote - WSL: Show Log)
What distro are you using? Does it happen with all distros?

Can you check if a shutdown of the distro helps (`wsl --shutdown`)?

**Comment by xiki808** [comment] 2020-08-24 14:55
It's working now, by disabling vEthernet (WSL) network adapter, which was connecting once I open the terminal window. There is still something that doesn't work, but not bothering me. 

When I open a project with a Dockerfile it asks me to open the docker container:
![image](https://user-images.githubusercontent.com/8024321/91059499-185d3d00-e62a-11ea-8bc2-3a2e50ba8710.png)

This does not work and gives the following errors:
![image](https://user-images.githubusercontent.com/8024321/91059556-2b700d00-e62a-11ea-8996-38af6df13738.png)

This is the Docker version I am running:
![image](https://user-images.githubusercontent.com/8024321/91059684-535f7080-e62a-11ea-80d6-5e23575b75df.png)

The container shows that it is running.

Below is the log for Remote - Containers
```[55 ms] Start: Resolving remote
[61 ms] Start: Run: wsl -d Ubuntu-18.04 -e wslpath -u \\wsl$\Ubuntu-18.04\home\xiki\projects\ha\core
[332 ms] Start: Run: wsl -d Ubuntu-18.04
[979 ms] Setting up container for folder or workspace: /home/xiki/projects/ha/core

[1242 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && test '-f' '/home/xiki/projects/ha/core/.devcontainer/devcontainer.json'
[1429 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && cat '/home/xiki/projects/ha/core/.devcontainer/devcontainer.json'
[1733 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && git 'rev-parse' '--show-toplevel'
[2042 ms] Start: Check Docker is running
[2042 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'info'
[2690 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl$\Ubuntu-18.04\home\xiki\projects\ha\core' '--filter' 'label=vsch.quality=stable'
[2990 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'inspect' '--type' 'container' 'b852f557409b'
[3301 ms] Start: Starting container
[3302 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'start' 'b852f557409b8ea4a222b09902d01c388cb51409b584741916ade51d4f7ed664'
[3909 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl$\Ubuntu-18.04\home\xiki\projects\ha\core' '--filter' 'label=vsch.quality=stable'
[4139 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'inspect' '--type' 'container' 'b852f557409b'
[4340 ms] Start: Inspecting container
[4340 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'inspect' '--type' 'container' 'b852f557409b8ea4a222b09902d01c388cb51409b584741916ade51d4f7ed664'
[4547 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'exec' '-i' '-u' 'root' '-e' 'VSCODE_REMOTE_CONTAINERS_SESSION=e334ac3e-7cd6-43ce-9cd9-8585080993e91598280493473' 'b852f557409b8ea4a222b09902d01c388cb51409b584741916ade51d4f7ed664' '/bin/sh'
[4566 ms] Start: Run in container: uname -m
[4835 ms] x86_64
[4835 ms] 
[4835 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[4839 ms] PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[4839 ms] 
[4840 ms] Start: Run in container: cat /etc/passwd
[4849 ms] Start: Setup shutdown monitor
[4872 ms] Forking shutdown monitor: c:\Users\daniel.scicluna\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-7e224ae5ae7075ee00ce31409e759130214a6ee1-sock singleContainer Info c:\Users\daniel.scicluna\AppData\Roaming\Code\logs\20200824T164731\exthost1\ms-vscode-remote.remote-containers
[4922 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && cat '/home/xiki/projects/ha/core/Dockerfile.dev'
[4924 ms] Start: Run in container: test -d /root/.vscode-server
[4977 ms] 
[4977 ms] 
[4977 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[4983 ms] 
[4983 ms] 
[4983 ms] Exit code 2
[4984 ms] Start: Run in container: test -d /root/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13
[4986 ms] 
[4987 ms] 
[4987 ms] Start: Launching Remote-Containers helper.
[4988 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && gpgconf '--list-dir' 'agent-extra-socket'
[5264 ms] Start: Run in container: gpgconf --list-dir agent-socket
[5269 ms] /root/.gnupg/S.gpg-agent
[5269 ms] 
[5269 ms] Start: Run in container: gpgconf --list-dir homedir
[5273 ms] /root/.gnupg
[5274 ms] 
[5274 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[5277 ms] 
[5278 ms] 
[5278 ms] Exit code 2
[5278 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[5281 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && cat '/root/.gitconfig'
[5300 ms] 
[5300 ms] 
[5300 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-6b9594c327a1f0cd074721cfd9131334e9255b54.js' >/tmp/vscode-remote-containers-6b9594c327a1f0cd074721cfd9131334e9255b54.js
[5300 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && gpgconf '--list-dir' 'homedir'
[5328 ms] 
[5328 ms] 
[5328 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-6b9594c327a1f0cd074721cfd9131334e9255b54.js' >/tmp/vscode-remote-containers-server-6b9594c327a1f0cd074721cfd9131334e9255b54.js
[5335 ms] 
[5335 ms] 
[5335 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'exec' '-i' '-u' 'root' '-e' 'REMOTE_CONTAINERS_SOCKETS=["/root/.gnupg/S.gpg-agent"]' '-e' 'REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-6b9594c327a1f0cd074721cfd9131334e9255b54.sock' 'b852f557409b8ea4a222b09902d01c388cb51409b584741916ade51d4f7ed664' '/root/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/node' '/tmp/vscode-remote-containers-server-6b9594c327a1f0cd074721cfd9131334e9255b54.js'
[5541 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /root/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/node /tmp/vscode-remote-containers-6b9594c327a1f0cd074721cfd9131334e9255b54.js $*; }; f' || true
[5550 ms] 
[5550 ms] 
[5551 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && cat '/root/.ssh/known_hosts'
[5607 ms] Start: Run in container: gpgconf --list-dir homedir
[5611 ms] /root/.gnupg
[5611 ms] 
[5611 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && cat '/root/.gnupg/pubring.kbx'
[5871 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[5874 ms] /root/.ssh/known_hosts exists
[5874 ms] 
[5874 ms] Exit code 1
[5875 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[5879 ms] 
[5880 ms] 
[5880 ms] Exit code 2
[5886 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
[5891 ms] 
[5891 ms] 
[5891 ms] Exit code 2
[5891 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink -f /proc/$pid/cwd ; xargs -0 < /proc/$pid/environ ; xargs -0 < /proc/$pid/cmdline ; } ; echo ; done 2>/dev/null
[5920 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && cat '/root/.gnupg/trustdb.gpg'
[5946 ms] Start: Run in container: /root/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/server.sh --disable-user-env-probe --use-host-proxy --port 0 --extensions-download-dir /root/.vscode-server/extensionsCache
[6142 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && gpg-connect-agent 'updatestartuptty' '/bye'
[6219 ms] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[6294 ms] IP Address: 172.17.0.2
[6300 ms] Extension host agent listening on 43801
[6300 ms] 

[6300 ms] Start: Run in container: echo 43801 >/root/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/.devport
[6301 ms] [14:48:20] Extension host agent started.
[6303 ms] 
[6303 ms] 
[6305 ms] Forwarding local port 43801 to container port 43801
[6365 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'exec' '-i' '-u' 'root' '-e' 'VSCODE_REMOTE_CONTAINERS_SESSION=e334ac3e-7cd6-43ce-9cd9-8585080993e91598280493473' 'b852f557409b8ea4a222b09902d01c388cb51409b584741916ade51d4f7ed664' '/root/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/node' '-e' '
[6366 ms] Start: Run: wsl -d Ubuntu-18.04 -e /bin/sh -c cd '/home/xiki/projects/ha/core' && docker 'exec' '-i' '-u' 'root' '-e' 'VSCODE_REMOTE_CONTAINERS_SESSION=e334ac3e-7cd6-43ce-9cd9-8585080993e91598280493473' 'b852f557409b8ea4a222b09902d01c388cb51409b584741916ade51d4f7ed664' '/root/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/node' '-e' '```

**Comment by xiki808** [comment] 2020-08-24 15:28
Ah well that is not really a solution, now I see what that network adapter does :) Without it I cannot connect to the net in WSL.

So back to square one.

Oh and I checked with the following distros:
- Ubuntu 18.04 LTS
- Ubuntu 20.04 LTS

This is the log I get when network adapter is enabled:

```
[2020-08-24 15:27:04.146] Resolving wsl+Ubuntu-20.04, resolveAttempt: 1
[2020-08-24 15:27:04.200] Starting VS Code Server inside WSL (Ubuntu-20.04)
[2020-08-24 15:27:04.200] Extension version: 0.44.4, Windows build: 19041. Multi distro support: available. WSL path support: enabled
[2020-08-24 15:27:04.319] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 -e sh -c "[ -d ~/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-08-24 15:27:04.468] Probing result: found
[2020-08-24 15:27:04.469] Server install found in WSL
[2020-08-24 15:27:04.469] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 3dd905126b34dcd4de81fa624eb3a8cbe7485f13 stable .vscode-server 0  ' in c:\Users\daniel.scicluna\.vscode\extensions\ms-vscode-remote.remote-wsl-0.44.4}
[2020-08-24 15:27:04.621] Setting up server environment: Looking for /home/xiki/.vscode-server/server-env-setup. Not found.
[2020-08-24 15:27:04.621] WSL version: 4.19.121-microsoft-standard Ubuntu-20.04
[2020-08-24 15:27:04.621] WSL2-shell-PID: 796
[2020-08-24 15:27:04.621] Starting server: /home/xiki/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/server.sh  --port=0 --use-host-proxy --enable-remote-auto-shutdown 
[2020-08-24 15:27:04.934] 
[2020-08-24 15:27:04.934] 
[2020-08-24 15:27:04.934] *
[2020-08-24 15:27:04.934] * Visual Studio Code Server
[2020-08-24 15:27:04.934] *
[2020-08-24 15:27:04.934] * Reminder: You may only use this software with Visual Studio family products,
[2020-08-24 15:27:04.934] * as described in the license https://aka.ms/vscode-remote/license
[2020-08-24 15:27:04.934] *
[2020-08-24 15:27:04.934] 
[2020-08-24 15:27:04.934] 
[2020-08-24 15:27:04.934] IP Address: 172.25.68.0
[2020-08-24 15:27:04.934] Extension host agent listening on 33877
[2020-08-24 15:27:04.934] 
[2020-08-24 15:27:04.934] 
[2020-08-24 15:27:04.934] [17:27:04] Extension host agent started.
[2020-08-24 15:27:04.949] Pinging 172.25.68.0:33877...
[2020-08-24 15:27:25.980] 172.25.68.0:33877 no response
[2020-08-24 15:27:25.981] WSL resolver response: ::1:33877
[2020-08-24 15:27:25.981] To debug connection issues, open a local browser on http://[::1]:33877/version
```

**Comment by DataCrusade1999** [comment] 2020-10-16 13:57
I am having this same issue!
My distro is: Ubuntu 20.04 LTS

**Comment by xiki808** [comment] 2020-10-16 14:54
Hey @DataCrusade1999, I got this working on another machine.

The first machine was my company's which had some Windows Security Protection configured on it and Kaspersky anti virus. I believe either of these was blocking the connection between windows and wsl.

**Comment by DataCrusade1999** [comment] 2020-10-16 16:41
@xiki808 I disabled the Kaspersky firewall but still, it shows the same error.

**Comment by chrmarti** [comment] 2020-10-20 13:35
@xiki808 Closing as upstream then, thanks.

@DataCrusade1999 Could you file a new issue?

**Closed by chrmarti** 2020-10-20 13:35 UTC
Labels: containers, wsl

**Comment by alexdonh** [comment] 2020-10-23 14:20
Not sure if its relevant to #2101 which was closed. I still get the handshake timeout with Kaspersky on. Disabling Kaspersky (or particularly, the Web Anti-virus option) does the trick though.

Would it be possible for a better solution without disabling Kaspersky? Is the root cause found?

**Comment by chrmarti** [comment] 2020-10-26 07:41
@alexdonh Can you add an exception to Kaspersky's Web Anti-Virus?

**Comment by alexdonh** [comment] 2020-10-27 18:07
> @alexdonh Can you add an exception to Kaspersky's Web Anti-Virus?

Can you show me how please?

**Comment by chrmarti** [comment] 2020-10-27 19:49
I don't, but there must be documentation from Kaspersky on this.

**Comment by carlosma155** [comment] 2020-11-04 15:50
> Can you paste the full WSL log? (Command: Remote - WSL: Show Log)
> What distro are you using? Does it happen with all distros?
> 
> Can you check if a shutdown of the distro helps (`wsl --shutdown`)?

I fix it with this, thanks

**Comment by ahmedalima** [comment] 2020-11-26 05:39
I restarted my laptop twice and worked for me!
