### ISSUE TITLE
Elevate rights on SSH remote

### ISSUE THREAD

**Issue by peterkappelt** [microsoft/vscode-remote-release#390] opened 2019-05-20 20:15 UTC
Hi,
this is more of a quick thought I have, but not a good idea for implementation yet.

Following scenario, I think it is quite typical:
* Remote server with SSH enabled. Root login is disabled for security reasons
* I can login with a generic account (let it call `operator`) that has the right to do `sudo`/ `su`
* I want to edit configuration files (`/etc/*`), of course this is only allowed by root

I'm thinking of some possibility to elevate the permissions of the file explorer/ text editor of Code, so that I log in using `operator` over SSH, but Code runs elevated as root through `sudo`.

However, I currently have no idea what the proper implementation could be for that.

It would be quite useful for administration purposes.

**Comment by roblourens** [comment] 2019-05-21 22:43
In a local window, if you try to save a file that the user doesn't have permissions to edit, vscode will prompt to retry with sudo. I assume the same works in a remote window. Have you tried?

**Comment by peterkappelt** [comment] 2019-05-22 04:25
Hi,

no - unfortunately not. At least not in VS Code for Windows (1.35.0-insider) being connected to an SSH remote. 

I tried saving a generic file to a directory without the necessary permissions: 
```Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/etc/test-config/vscode-test.file')```

I'm going to retry it on a Linux machine later. To be honest, I didn't event known about the existence of this feature for local environments 🤔

**Comment by TrevorSayre** [comment] 2019-05-27 14:37
I am mainly wanting this so I can edit files in `/etc/nginx`

When I edit a config file in, for example, `/etc/nginx/sites-available` and attempt to save, I get the error: 

```
Failed to save 'example': Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/etc/nginx/sites-available/example')
```

I am given the options to `Retry`, `Save As...`, or `Discard` with not obvious way to elevate permissions.

I am able to `code-insiders /etc/nginx`, but I am NOT able to `sudo code-insiders /etc/nginx` in an attempt to open an elevated permissions editor session as it says `sudo: code-insiders: command not found` which makes sense.

**Comment by egamma** [comment] 2019-05-28 06:39
@bpasero should elevation work in a remote context?

**Comment by bpasero** [comment] 2019-05-28 07:35
No.

Duplicate of https://github.com/microsoft/vscode/issues/48659

**Closed by bpasero** 2019-05-28 07:35 UTC
Labels: feature-request, ssh
