### ISSUE TITLE
remote-containers does not respect `~/.ssh/config`

### ISSUE THREAD

**Issue by guoquan** [microsoft/vscode-remote-release#2624] opened 2020-03-27 19:11 UTC
- VSCode Version: 

> Version: 1.43.2
> Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
> Date: 2020-03-24T07:34:57.037Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 19.3.0

- Local OS Version:

> macOS Catalina 10.15.3 (19D76)

- Remote OS Version:

> Linux --- 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Remote Extension/Connection Type: SSH/Docker

Steps to Reproduce:

1. setup `~/.ssh/config` (or even `/etc/ssh/ssh_config`)
```
Host jump
  HostName jump

Host host
  HostName host
  User username
  ProxyJump jump
```
where `username` is a different user than my local user and I need `jump` to access `host`.

2. setup `docker.host` in settings.json (user level for my case)
```
{
...,
    "docker.host":"ssh://host"
}
```

3. Test terminal access
```bash
DOCKER_HOST=ssh://host docker ps
# remote containers are expected to be listed
```
This would indicate my local docker is using a remote docker server while respecting my `~/.ssh/config` since I did not add `username` and proxy `jump` directly.

4. Test with vscode
Green button -> "Remote-Containers: Attach to Running Container..."
Nothing happens then. Further check at Developer Tools, the Console log shows:
```
mainThreadExtensionService.ts:65 [[object Object]]Timed out while waiting for handshake
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

mainThreadExtensionService.ts:66 Error: Timed out while waiting for handshake
	at Timeout._onTimeout (/Users/guoquan/.vscode/extensions/ms-vscode-remote.remote-containers-0.106.0/dist/extension.js:1)
	at listOnTimeout (internal/timers.js:531)
	at processTimers (internal/timers.js:475)
```

5. And, what I tried? 
I connected to a system-wide VPN that allows me to access `host` directly, the Developer Tools Console log changed to
```
[[object Object]]All configured authentication methods failed
```
And then change `docker.host` in settings.json to `"docker.host":"ssh://username@host"`, vscode can list my containers then.

So, I am assuming it is not just proxy jump problem or authentication problem.
I am thinking if it is the extension invoking docker in a way that it cannot access and respect `~/.ssh/config`.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No - leaving only remote-containers on enabled.

**Comment by chrmarti** [comment] 2020-10-13 12:19
This should be fixed.

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2481.

**Closed by chrmarti** 2020-10-13 12:19 UTC
