### ISSUE TITLE
Remote Explorer: Cannot remove 'other' container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1527] opened 2019-10-01 06:07 UTC
Remove doesn't work on the last container:
![image](https://user-images.githubusercontent.com/9205389/65938131-6968af00-e422-11e9-8a02-09d717024e92.png)

**Comment by chrmarti** [comment] 2019-10-01 06:09
Actually the container no longer exists. 'Refresh' doesn't work, somehow the view became stale.
Errors in the console:
```
[Extension Host] debugger listening on port 48572
extensionHost.ts:203 Extension Host
extensionHost.ts:204 Debugger attached.
log.ts:190  WARN UNRESPONSIVE extension host, 'ms-azuretools.vscode-docker' took 63% of 5308.271ms, saved PROFILE here: 'C:\Users\chrmarti\AppData\Local\Temp\exthost-8996a9.cpuprofile' Array(10)
console.ts:137 [Extension Host] DockerContext cache miss. (at v (c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:4411))
console.ts:137 [Extension Host] DockerContext cache hit. (at v (c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:4369))
notificationsAlerts.ts:40 Error removing container: (HTTP code 409) unexpected - removal of container fbca52f961563c8e944e303ecf0d532c257c168d98324b34b826de56ff035952 is already in progress
onDidNotificationChange @ notificationsAlerts.ts:40
notificationsAlerts.ts:38 Error: (HTTP code 404) no such container - No such container: d7885c6bf719eca0e5840c090690938b469ab68f5bb121badb8243c70f6de419 
	at c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:285235
	at c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:285198
	at m.buildPayload (c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:285208)
	at IncomingMessage.<anonymous> (c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:284708)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1092:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)
onDidNotificationChange @ notificationsAlerts.ts:38
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: (HTTP code 404) no such container - No such container: d7885c6bf719eca0e5840c090690938b469ab68f5bb121badb8243c70f6de419  (at t.startExtensionHostProcess.t.onMessage.process.on.t.catch.t (c:\Users\chrmarti\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:787:725))
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: (HTTP code 404) no such container - No such container: d7885c6bf719eca0e5840c090690938b469ab68f5bb121badb8243c70f6de419 	at c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:285235	at c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:285198	at m.buildPayload (c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:285208)	at IncomingMessage.<anonymous> (c:\Users\chrmarti\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.79.0\dist\extension.js:1:284708)	at IncomingMessage.emit (events.js:187:15)	at endReadableNT (_stream_readable.js:1092:12)	at process._tickCallback (internal/process/next_tick.js:63:19) (at t.startExtensionHostProcess.t.onMessage.process.on.t.catch.t (c:\Users\chrmarti\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:787:801))
t.log @ console.ts:137
[...]
```

**Comment by alexr00** [comment] 2019-10-01 10:31
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/1491

**Closed by alexr00** 2019-10-01 10:31 UTC
Labels: bug, containers
