### ISSUE TITLE
[Remote-SSH Bug]: Images are not render in the tooltip when using Remote-SSH version 0.110.1 from MacOS / Windows to Linux

### ISSUE THREAD

**Issue by caucbianca** [microsoft/vscode-remote-release#9867] opened 2024-05-09 15:05 UTC
**Setup**: VS Code 1.89 + Remote-SSH 1.110.1

**Steps to Reproduce**:
1. Create a Typescript file containing a TSDoc comment containing PNG icon
![Screenshot from 2024-05-09 17-49-44](https://github.com/microsoft/vscode-remote-release/assets/17355584/41d6e76f-2a35-4514-a989-d5f6e5aca2c5)
2. When I hover over TestClass, the tooltip will display a broken image regardless of the path used (absolute / relative)
![Screenshot from 2024-05-09 17-49-48](https://github.com/microsoft/vscode-remote-release/assets/17355584/6bdc85ac-0aed-44c3-9dec-155375b9c285)

Please note that I don't encounter this issue when using Remote-SSH 1.110.0 or another older version

**Comment by caucbianca** [comment] 2024-05-23 14:42
Is there any update regarding this, please?

**Comment by scharasse** [comment] 2024-06-12 15:55
In original post, correct version that does not have the issue is Remote-SSH **0.110.0** or older (not 1.110.0)

**Comment by gabrielBusuioc** [comment] 2024-07-08 07:37
Hi,

Is there any plan to address this issue in the near future? It affects my extension!

Thanks!

**Comment by mjbvz** [comment] 2024-08-05 18:30
Duplicate of https://github.com/microsoft/vscode/issues/97759

**Closed by mjbvz** 2024-08-05 18:30 UTC
Labels: ssh
