### ISSUE TITLE
Open WSL in the same window

### ISSUE THREAD

**Issue by Bu11etmagnet** [microsoft/vscode-remote-release#3214] opened 2020-06-18 10:14 UTC
(This is another way of achieving something similar to  #1673, namely: avoiding redundant, unused vscode windows. But if connecting the same window to a remote is possible, #1673 seems like a workaround).

The Remote-SSH has "Connect to host" and "Connect current window to host" commands. Remote-WSL has only "New Window" and "New Window using Distro".

Opening a remote in the existing window is much more convenient, because every time I opened a WSL connection in a new window, I immediately closed the originator window. I can't see the utility of keeping an unused window around.

**Comment by aeschli** [comment] 2020-11-10 13:24
duplicate of  #1673

**Closed by aeschli** 2020-11-10 13:24 UTC
Labels: feature-request, wsl
