### ISSUE TITLE
[Remote-SSH Bug]: Extensions ignore Server Install Path

### ISSUE THREAD

**Issue by janek202** [microsoft/vscode-remote-release#10289] opened 2024-09-19 08:57 UTC
I use Vscode 1.93.1 and Remote SSH v0.114.3.
As home directories in my company are shared between different hosts, I need to make the server path unique, using Server Install Path.

Recently I noticed a lot of issues with extensions, and I discovered the Extension engine always uses a path from home, ignoring my Server path:
  Lock '/home/$user/.vscode-server/data/User/workspaceStorage/$id/vscode.lock'

This leads to a ton of issues, with architecture mismatches, host settings being overridden and so on.
I tried to switch to a pre-release version, but it didn't help. I think it was working fine on 113.1, but I can't find it anymore, and I don't know how to downgrade it.

**Comment by joshspicer** [comment] 2024-09-26 17:30
This should be fixed in the latest release (dupe of https://github.com/microsoft/vscode-remote-release/issues/10255). Please feel free to re-open if you're seeing otherewise

**Closed by joshspicer** 2024-09-26 17:30 UTC
Labels: ssh
