### ISSUE TITLE
remote does not work if default shell is not bash

### ISSUE THREAD

**Issue by tmdag** [microsoft/vscode-remote-release#3442] opened 2020-07-30 03:00 UTC
My remote server uses tcsh as a default shell. Looks like remote is expecting bash by default and sending bash commands to tsch shell. is there a way to go around it ?

**Comment by Chuxel** [comment] 2020-07-30 13:48
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2509

**Closed by Chuxel** 2020-07-30 13:48 UTC
Labels: ssh
