### ISSUE TITLE
WSL:  Failed to Start VsCode in WSL. Resource temporarily available/

### ISSUE THREAD

**Issue by Patoski-patoski** [microsoft/vscode-remote-release#9811] opened 2024-04-23 12:16 UTC
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
Windows version: 10.0.19045.3803
VS Code version: 1.88
Remote OS: Ubuntu 22.04

![Visual Studio Code 23_04_2024 11_46_43](https://github.com/microsoft/vscode-remote-release/assets/76764297/59bea1d3-b596-49cf-a38f-00943545a6d9)

![Visual Studio Code 23_04_2024 11_47_29](https://github.com/microsoft/vscode-remote-release/assets/76764297/981a3f5e-f2fd-4966-b636-2d4b32779111)

![Welcome - Visual Studio Code 23_04_2024 12_03_26](https://github.com/microsoft/vscode-remote-release/assets/76764297/339b6ff8-0cc6-4902-a2b6-e878fac91629)

Steps to Reproduce:

1. Opened Vs code and click the `Remote` icon located bottom-left and Clicked the dropdown text `Open WSL`. Could not connect my Vscode server and Ubuntu.

2. Opened the Ubuntu terminal and type `code .` Log output

```
code .
Installing VS Code Server for Linux x64 (e170252f762678dec6ca2cc69aba1570769a5d39)
Downloading: 100%
Failed
--2024-04-23 13:04:15--  https://update.code.visualstudio.com/commit:e170252f762678dec6ca2cc69aba1570769a5d39/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 13.107.246.64, 13.107.213.64, 2620:1ec:bdf::64, ...
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|13.107.246.64|:443... failed: Resource temporarily unavailable.
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|13.107.213.64|:443... failed: Resource temporarily unavailable.
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|2620:1ec:bdf::64|:443... failed: Network is unreachable.
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|2620:1ec:46::64|:443... failed: Network is unreachable.
ERROR: Failed to download https://update.code.visualstudio.com/commit:e170252f762678dec6ca2cc69aba1570769a5d39/server-linux-x64/stable to /home/cdbpatoski/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39-1713873808.tar.gz
```

1. I've used VPN to ping  `update.code.visualstudio.com` with an output of 100% lost packets. However, my browser can open ` update.code.visualstudio.com`. only with a VPN.
2. I've crawled around the web to find similar bugs and but no solution.
     -   check [Stackoverflow 1](https://stackoverflow.com/questions/64108941/visual-studio-code-not-running-working-on-wsl-2?rq=3)
    - check [Stackoverflow 2](https://stackoverflow.com/questions/73037830/visual-studio-code-server-self-update-is-stuck)
3.  I've `rm -fr ~/.vscode-server/ 

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Patoski-patoski** [comment] 2024-04-23 12:45
FULL ERROR LOG
```

[2024-04-23 12:42:12.471] Extension version: 0.88.0
[2024-04-23 12:42:12.472] L10N bundle: undefined
[2024-04-23 12:42:12.656] authorityHierarchy: wsl+ubuntu-22.04
[2024-04-23 12:42:12.656] WSL extension activating for a local WSL instance
[2024-04-23 12:42:12.689] Resolving wsl+ubuntu-22.04, resolveAttempt: 1
[2024-04-23 12:42:12.689] WSL feature installed: true (dll path)
[2024-04-23 12:42:12.690] NodeExecServer run: C:\Windows\System32\wsl.exe --list --verbose
[2024-04-23 12:42:14.209] 1 distros found
[2024-04-23 12:42:14.212] Starting VS Code Server inside WSL (wsl1)
[2024-04-23 12:42:14.212] Windows build: 19045. Multi distro support: available. WSL path support: enabled
[2024-04-23 12:42:14.212] Scriptless setup: false
[2024-04-23 12:42:14.214] No shell environment set or found for current distro.
[2024-04-23 12:42:15.777] WSL daemon log file: 
[2024-04-23 12:42:15.789] Probing if server is already installed: if [ -d ~/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39 ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf 'alpine-'; fi; if [ -s ~/.vscode-server/bin/compatibilty-check ]; then printf 'legacy-'; fi; uname -m;
[2024-04-23 12:42:15.790] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu-22.04 -e sh -c if [ -d ~/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39 ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf 'alpine-'; fi; if [ -s ~/.vscode-server/bin/compatibilty-check ]; then printf 'legacy-'; fi; uname -m;
[2024-04-23 12:42:16.571] Probing result: x86_64
[2024-04-23 12:42:16.572] No server install found in WSL, needs linux-x64
[2024-04-23 12:42:16.572] Getting server from client side
[2024-04-23 12:42:16.573] Downloading VS Code Server stable - e170252f762678dec6ca2cc69aba1570769a5d39 into C:\Users\USER\AppData\Local\Temp\vscode-remote-wsl\stable\e170252f762678dec6ca2cc69aba1570769a5d39\vscode-server-stable-linux-x64.tar.gz.
[2024-04-23 12:42:37.244] Unable to download server on client side: Error: Request downloadRequest failed with message: connect ETIMEDOUT 13.107.213.64:443. Will try to download on WSL side.
[2024-04-23 12:42:37.246] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu-22.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" e170252f762678dec6ca2cc69aba1570769a5d39 stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=2851162849-3292888915-3262189602-3985940847 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
[2024-04-23 12:42:38.498] Setting up server environment: Looking for /home/cdbpatoski/.vscode-server/server-env-setup. Not found.
[2024-04-23 12:42:38.498] WSL version: 4.4.0-19041-Microsoft Ubuntu-22.04
[2024-04-23 12:42:38.498] Updating VS Code Server to version e170252f762678dec6ca2cc69aba1570769a5d39
[2024-04-23 12:42:38.498] Removing previous installation...
[2024-04-23 12:42:38.498] Installing VS Code Server for Linux x64 (e170252f762678dec6ca2cc69aba1570769a5d39)
[2024-04-23 12:42:38.498] Downloading:     
[2024-04-23 12:43:20.235] 100%
[2024-04-23 12:43:20.235] Failed
[2024-04-23 12:43:20.238] --2024-04-23 13:43:20--  https://update.code.visualstudio.com/commit:e170252f762678dec6ca2cc69aba1570769a5d39/server-linux-x64/stable
[2024-04-23 12:43:20.238] Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 13.107.213.64, 13.107.246.64, 2620:1ec:bdf::64, ...
[2024-04-23 12:43:20.238] Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|13.107.213.64|:443... 
[2024-04-23 12:43:40.949] failed: Resource temporarily unavailable.
[2024-04-23 12:43:40.949] Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|13.107.246.64|:443... 
[2024-04-23 12:44:01.426] failed: Resource temporarily unavailable.
[2024-04-23 12:44:01.426] Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|2620:1ec:bdf::64|:443... failed: Network is unreachable.
[2024-04-23 12:44:01.426] Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|2620:1ec:46::64|:443... failed: Network is unreachable.
[2024-04-23 12:44:01.426] ERROR: Failed to download https://update.code.visualstudio.com/commit:e170252f762678dec6ca2cc69aba1570769a5d39/server-linux-x64/stable to /home/cdbpatoski/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39-1713876158.tar.gz
[2024-04-23 12:44:01.428] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2024-04-23 12:44:06.493] Download in background is enabled
```

**Comment by Patoski-patoski** [comment] 2024-04-23 16:59
WE DID IT GUYS FINALLY😅
WSL is restored (switching Full time to Linux OS can wait another year😎)


![Welcome - e170252f762678dec6ca2cc69aba1570769a5d39  WSL_ Ubuntu-22 04  - Visual Studio Code 23_04_2024 17_33_32](https://github.com/microsoft/vscode-remote-release/assets/76764297/5f06daa0-6669-481e-bb22-52cbafd0092e)



**HERE IS A SUMMARY OF MY SOLUTIONS** 

To check if you already have the VS Code Server installed in your WSL environment, you can follow these steps:

1. Open your WSL terminal: Launch your WSL environment by opening a terminal in Windows and typing WSL or opening your preferred WSL terminal application (Recommends Powershell).

2. Navigate to the VS Code Server directory: The VS Code Server is normally installed in the ~/.vscode-server/bin directory. You can navigate to this directory by running:  `cd ~/.vscode-server/bin`

3. List the contents of the directory: Use the `ls` command to list the contents of the directory. This will show you all the installed versions of the VS Code Server. Each version will be in its directory named with a unique identifier, such as `e170252f762678dec6ca2cc69aba1570769a5d39.`
`ls -la`

4. Check for the specific version: If you're looking for a specific version of the VS Code Server, you can check if its directory exists by listing the contents of the ~/.vscode-server/bin directory and looking for the version identifier. For example, to check for version e170252f762678dec6ca2cc69aba1570769a5d39, you would run:

`ls ~/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39`

If the directory exists and contains files, then the specific version of the VS Code Server is installed.

By following these steps, you can determine whether the VS Code Server is already installed in your WSL environment and identify the version(s) installed. Else download a server here: [Download Vscode Server](https://github.com/coder/code-server/releases)


Now that we know that the Vscode server is Present in our system, We extract Manually.

To extract the contents of the VS Code Server .tar.gz file to the specific directory
` ~/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39`  in your WSL environment, follow these steps:

1. Open your WSL terminal: Launch your WSL environment by opening a terminal in Windows and typing wsl or opening your preferred WSL terminal application.

2. Create the target directory: Before extracting, ensure the target directory exists. Use the `mkdir` command with the `-p` option to create the necessary directories. Since the target directory is 
`~/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39`, you can create it with:
`mkdir -p ~/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39`
3. Extract the .tar.gz file: Use the tar command to extract the contents of the .tar.gz file to the target directory. 
   Assuming the downloaded file is named vscode-server-stable-linux-x64.tar.gz, the command would be:
`tar -zvxf vscode-server-stable-linux-x64.tar.gz -C ~/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/
`

This command breaks down as follows:

    -z: Decompress the archive using gzip.
    -v: Verbosely list the files processed.
    -x: Extract files from an archive.
    -f: Use archive file.
    -C: Change to directory before performing any operations.

4. Verify the extraction: After extraction, you can verify that the files were correctly placed in the target directory by listing the contents of the directory:
``ls ~/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/``

Now, you should have successfully extracted the VS Code Server to the specified directory in your WSL environment, allowing VS Code to use it for its operations

**Comment by aeschli** [comment] 2024-04-24 09:07
For the logs it seems your machine was not able to connect to the download server. It tried it from Windows as well asd from WSL.
Maybe you were offline, or connected to a network with connectivity problems?

Later the screenshot shows that the folder is there but the server script was missing. In that case the best is to `rm -r ~/.vscode-server/bin` and start again.

Closing this issue as this was caused by connectivity issues. There hasn't been any changes on out side recently.

**Closed by aeschli** 2024-04-24 09:07 UTC
Labels: wsl
