### ISSUE TITLE
support ssh from macOS to Windows

### ISSUE THREAD

**Issue by masyanru** [microsoft/vscode-remote-release#333] opened 2019-05-15 14:38 UTC
I set up an OpenSSH on Windows machine to work with pubkey authentication from macOS to Windows, but "Can't connect to winmachine: unreachable or not Linux x86_64". 

I just want to run powershell 5 code remotely from macOS in VSCode at windows machine without any pain. And I can't use "Enter-PSSession" from macOS inside VSCode because it requeries powershell core and connect to powershell core on Windows through ssh. It doesn't make any sense.

**Comment by mjbvz** [comment] 2019-05-17 00:39
Duplicate of #25

**Closed by mjbvz** 2019-05-17 00:39 UTC
