### ISSUE TITLE
Mac to Windows SSH via VSCode: Failed to parse remote port from server output

### ISSUE THREAD

**Issue by K-Tummalapalli-OH** [microsoft/vscode-remote-release#4282] opened 2021-01-08 18:58 UTC
- VSCode Version: 1.52.1 (Extension: Remote Development v0.20.0)
- Local OS Version: macOS Catalina 10.15.7
- Remote OS Version: Windows Server 2016 Standard SP0 64bit
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. ssh username@hostname.domain
2. enter password

OUTPUT:

```
[13:52:05.576] Log Level: 2
[13:52:05.578] remote-ssh@0.62.0
[13:52:05.578] darwin x64
[13:52:05.579] SSH Resolver called for "ssh-remote+watsecagent02.ds.ohnet", attempt 1
[13:52:05.579] "remote.SSH.useLocalServer": true
[13:52:05.579] "remote.SSH.sshPath": undefined
[13:52:05.579] "remote.SSH.sshConfigurationFile": undefined
[13:52:05.579] "remote.SSH.useFlock": true
[13:52:05.580] "remote.SSH.lockfilesInTmp": false
[13:52:05.580] "remote.SSH.localServerDownload": auto
[13:52:05.580] "remote.SSH.remoteServerListenOnSocket": false
[13:52:05.580] "remote.SSH.showLoginTerminal": false
[13:52:05.580] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[13:52:05.580] SSH Resolver called for host: watsecagent02.ds.ohnet
[13:52:05.580] Setting up SSH remote "watsecagent02.ds.ohnet"
[13:52:05.583] Acquiring local install lock: /var/folders/9j/53t4715d4xd1_r356vrhcb0w0000gn/T/vscode-remote-ssh-watsecagent02.ds.ohnet-install.lock
[13:52:05.591] Looking for existing server data file at /Users/krishna/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-watsecagent02.ds.ohnet-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json
[13:52:05.592] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[13:52:05.594] Install and start server if needed
[13:52:05.597] Checking ssh with "ssh -V"
[13:52:05.607] > OpenSSH_8.1p1, LibreSSL 2.7.3

[13:52:05.611] askpass server listening on /var/folders/9j/53t4715d4xd1_r356vrhcb0w0000gn/T/vscode-ssh-askpass-84ec9b987096bf9ab4e48840d15010032a145499.sock
[13:52:05.612] Spawning local server with {"ipcHandlePath":"/var/folders/9j/53t4715d4xd1_r356vrhcb0w0000gn/T/vscode-ssh-askpass-ef410b188b537f7a52ae164ca6163b4c1fbdefb0.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","57279","-o","ConnectTimeout=15","watsecagent02.ds.ohnet"],"dataFilePath":"/Users/krishna/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-watsecagent02.ds.ohnet-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json"}
[13:52:05.612] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/krishna/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/krishna/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/9j/53t4715d4xd1_r356vrhcb0w0000gn/T/vscode-ssh-askpass-84ec9b987096bf9ab4e48840d15010032a145499.sock"}
[13:52:05.614] Spawned 69844
[13:52:05.697] > local-server> Spawned ssh: 69845
[13:52:05.700] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[13:52:06.035] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:PwR/7O3tMwr9bzJcanRmgLgtt+AX0gEVLpI1XQD1MfY
[13:52:06.482] Got askpass request: {"request":"username@hostname's password:"}
[13:52:06.483] Showing password prompt
[13:52:06.484] Listening for interwindow password on /var/folders/9j/53t4715d4xd1_r356vrhcb0w0000gn/T/vscode-ssh-askpass-9753928794af85c6e8ad03ec2b58542b4dadeaca.sock
[13:52:06.484] Writing password prompt to globalState
[13:52:19.046] Got password response
[13:52:19.046] Interactor gave response: ***************
[13:52:19.047] Cleaning up other-window auth server
[13:52:19.196] stderr> Authenticated to hostname ([172.17.202.47]:22).
[13:52:19.349] stderr> shell request failed on channel 2
[13:52:19.350] > local-server> ssh child died, shutting down
[13:52:19.356] Local server exit: 0
[13:52:19.356] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:PwR/7O3tMwr9bzJcanRmgLgtt+AX0gEVLpI1XQD1MfY
Authenticated to watsecagent02.ds.ohnet ([172.17.202.47]:22).
shell request failed on channel 2

[13:52:19.357] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3debug1: Server host key: ecdsa-sha2-nistp256 SHA256:PwR/7O3tMwr9bzJcanRmgLgtt+AX0gEVLpI1XQD1MfYAuthenticated to hostname ([172.17.202.47]:22).shell request failed on channel 2
[13:52:19.357] Failed to parse remote port from server output
[13:52:19.364] Resolver error: Error: 
	at Function.Create (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:64276)
	at Object.t.handleInstallOutput (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:61061)
	at Object.t.tryInstallWithLocalServer (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:402931)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:308557
	at async Object.t.withShowDetailsEvent (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:403706)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:401486
	at async S (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:398276)
	at async Object.t.resolveWithLocalServer (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:401135)
	at async Object.t.resolve (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:312304)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:127:110280
[13:52:19.367] ------
```

Does this issue occur when you try this locally?: Yes/No (I'm able to SSH from terminal with same credentials)
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment] 2021-01-28 00:38
Looks like a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4276?

**Comment by Andrysky** [comment] 2021-01-28 05:17
> Looks like a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4276?

No

**Comment by zamarawka** [comment] 2021-01-29 17:09
faced with this issue =((

**Comment by roblourens** [comment] 2021-03-02 23:19
Sounds like https://github.com/microsoft/vscode-remote-release/issues/2475. Are you connecting to a windows remote? If so you can work around it by setting `"remote.SSH.useLocalServer": false`

**Closed** 2021-03-10 12:47 UTC
Labels: needs-more-info, ssh
