### ISSUE TITLE
Issue creating tunnel

### ISSUE THREAD

**Issue by Madslick** [microsoft/vscode-remote-release#541] opened 2019-06-01 00:06 UTC
Visual Studio Insiders Remote Development was working for me yesterday connecting to any of the connections listed in my C:\Users\joe\.ssh\config file using ssh keys. I can still use git bash and my ssh key to connect to those machines but today the remote-ssh extension has had trouble. This is the output. I've been connecting to linux hosts and I get the same remote-ssh extension error when I try to connect

I'm not sure why I get "stderr: Can't open user config file <path> Invalid Argument" because when I use git bash I can connect to my vagrant box with 

ssh -F C:/Users/joe/.ssh/config synesis-vagrant

remote-ssh@0.39.0
SSH Resolver called for "ssh-remote+synesis-vagrant"
SSH Resolver called for host: synesis-vagrant
Setting up SSH remote "synesis-vagrant"
Using commit id "2737cde4facc8411982862742f5c6cd3dabef323" and quality "insider" for server
Using SSH config file "C:\Users\joe\.ssh\config"
Install and start server if needed
> 
> Found existing installation at /root/.vscode-server-insiders/bin/2737cde4facc841
> 1982862742f5c6cd3dabef323...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> ab6463e5-e030-4e9c-8a32-6df972e7d7e5==37929==
> 
"install" terminal command done
Received install output: ab6463e5-e030-4e9c-8a32-6df972e7d7e5==37929==
Server is listening on port 37929
Using SSH config file "C:\Users\joe\.ssh\config"
Spawning tunnel with: ssh -F C:\Users\joe\.ssh\config synesis-vagrant -N -L localhost:58909:localhost:37929
Spawned SSH tunnel between local port 58909 and remote port 37929
Waiting for ssh tunnel to be ready
Tunnel(37929) stderr: Can't open user config file  C:\\Users\\joe\\.ssh\\config: Invalid argument

Could not establish tunnel to "synesis-vagrant" (Max wait time exhausted).
Could not establish tunnel to "synesis-vagrant" (Max wait time exhausted).

**Comment by smhc** [comment] 2019-06-01 03:22
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/535

**Comment by roblourens** [comment] 2019-06-03 20:41
This is fixed now, please update and try again

**Closed by roblourens** 2019-06-03 20:41 UTC
Labels: ssh

**Comment by Madslick** [comment] 2019-06-04 23:17
Confirmed, thanks!
