### ISSUE TITLE
Git only sees changes at the time VS Code opens

### ISSUE THREAD

**Issue by brentlblair** [microsoft/vscode-remote-release#6466] opened 2022-03-17 20:15 UTC
- VSCode Version: 1.62.2
- Local OS Version: Windows 11
- Remote OS Version: CentOS Linux 7
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. File watches sees current state of files when VS Code opens
2. Files watcher does not see any changes made after VS Code opens
3. I can only see new changes if I close and re-open VS Code

**Comment by tanhakabir** [comment] 2022-03-17 21:52
Could you share a gif with us of what you see?

**Comment by brentlblair** [comment] 2022-03-18 12:51
I modify the file, and save it, but VS Code doesn't notice the file has changed.  It used to update with a "M" status instantly.  I then restart the program and sign back in to the SSH session, and it sees that the file has been modified.  The recording is below.  Also, I don't see any errors from the watcher about a large files system.  
cat /proc/sys/fs/inotify/max_user_watches
8192
I am only watching about 4k files.

![Code_fAa6q4V9lS](https://user-images.githubusercontent.com/23214321/159005365-3cd3cf8c-a201-426b-9c96-27a7a32a9267.gif)

**Comment by brentlblair** [comment] 2022-03-24 18:19
Did the information I provided help, or did I miss something that you needed?

**Comment by tanhakabir** [comment] 2022-03-24 18:48
oh thanks for pinging me @brentlblair, I missed this somehow

**Comment by bpasero** [comment] 2022-03-25 06:02
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `Help | Toggle Developer Tools`
* select `Console`
* filter the output by typing `File Watcher` into the filter box
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323290-f3ba6470-dfed-4066-a19c-951395611738.png)

**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by bpasero** [comment] 2022-03-25 06:03
@brentlblair from your recording it seems the issue at hand is that the SCM changes (GIT) view does not update to show the change as outgoing, is that it?

**Comment by bpasero** [comment] 2022-03-25 16:30
@brentlblair ok so I am trying to figure out if this is a file watching issue or a git issue and so far it sounds to me this is a git issue because file events seem to work. 

To make sure file events work:
* open a file in the editor
* make a change with a different editor
* make sure the file has updated in the editor

If that works, then it sounds more like a git issue to me.

Are there any symbolic links involved? or maybe file path casing that is not the same as on disk?

**Comment by brentlblair** [comment] 2022-03-25 16:41
@bpasero This is not a file watching issue, it is git.  I updated directly on the remote system and when back to vs code, and the change was there in less than a second.

How can I troubleshoot git?  Is that part of this extension or is this an issue with git on the remote?
I don't think it has to do with the remove only because the git status of all files is correct when vscode loads.  It can't see changes that are made while it's open.  If I close and reopen vscode, it sees the git status changes made during the previous session.

There are no symbolic links and the case matches exactly.  I copied the path from the vscode log to a `cd` on the remote and it goes to the correct folder / directory.

**Comment by lszomoru** [comment] 2022-03-28 11:36
@brentlblair, I see that you are running VS Code `1.62.2` which we released in October 2021. 
Are you able to reproduce the same issue with the latest Stable and Insiders releases?

If you are able to reproduce the problem with the latest releases, could you please use the `Git: Set Log Level...` command from the command palette and set the log level to `Trace`. Then reload VS Code, connect to the remote, and make a change to a file so that you reproduce the issue with the file not showing up in the "Source Control" viewlet. After that could you please share the git extension logs which you can access by invoking the `Git: Show Git Output` command from the command palette. Thank you!

**Comment by lszomoru** [comment] 2022-03-28 19:27
@brentlblair, my bad, it looks like the log level needs to be set after you have connected to the remote:
1. Connect to the SSH remote
2. Open a folder that contains a git repository on the SSH remote
3. Invoke the `Git: Set Log Level...` command, and set the log level to `Trace`
4. Open a file from the workspace
5. Make a change to the file and save
6. Switch the SCM viewlet and see if the file appears
7. If file watching is working you should see something similar in the Git output channel
```
[2022-03-28T19:23:13.983Z] Log level changed to: Trace
[2022-03-28T19:23:18.131Z] [debug] [wt] Change: /Users/user1/Desktop/folder/src/GitPlayGround/file.ts
```

**Comment by brentlblair** [comment] 2022-03-28 19:57
@lszomoru It does not look like that changed anything.  I have attached a gif of what I did. When I saved the file, I didn't see any new entries in the logs
![Code_2V5OQsJ4vE](https://user-images.githubusercontent.com/23214321/160476836-5aef07cb-d819-43d4-a106-e04c03b2af79.gif)
.

**Comment by lszomoru** [comment] 2022-03-29 10:18
@brentlblair, thank you vey much. let me sync with @bpasero and get back to you with an action plan.

**Comment by bpasero** [comment] 2022-03-29 13:13
@brentlblair does it make a different when you disable your complicate `files.watcherExclude` settings?

**Comment by brentlblair** [comment] 2022-03-29 13:23
@bpasero No, it does not.  I removed the entire files.watcherExclude section from the settings.json file and restarted VS Code.  I then made a change to my test file, saved it, but the git status didn't change in VS Code.

**Comment by lszomoru** [comment] 2022-03-29 13:31
@brentlblair, in an effort to narrow down the problem can you please answer the following:
1. Does the same problem occur if you are opening a folder/workspace from your Windows machine without SSH?
2. Does the same problem occur for any folders/workspaces that you open from the remote machine?

**Comment by brentlblair** [comment] 2022-03-29 13:55
@lszomoru 1. It works correctly when I browse a local folder that is part of a git repository.   I make a change, and it shows modified status.
2. All of the folders in the workspace behave the same where the git status does not update over ssh during a session.  The git status of the files is only updated when the program / ssh session opens.  It worked correctly until a few months ago, but I don't know if it was a VS Code update or a SSH plugin update that broke it.

**Comment by lszomoru** [comment] 2022-03-29 18:46
@brentlblair, I am not sure if this is related but when using SSH, `git` is being executed on the SSH machine. It the log above I see that the git version on your SSH box is `1.8.3.1` which seems to be a version that was released in 2015. Could you please try upgrading the version of git () to the latest available version to see if that has any impact on your experience?

**Closed** 2022-04-01 13:39 UTC
Labels: ssh, needs more info, git
