### ISSUE TITLE
Git related highlighting / fading in VS Code explorer sidebar not working in symlinked folders

### ISSUE THREAD

**Issue by alamowo** [microsoft/vscode-remote-release#2924] opened 2020-05-04 06:18 UTC
- VSCode Version: 1.44.2
- Local OS Version: Windows 10 Pro Build 18363
- Remote OS Version: Ubuntu 18.04.4 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Create a folder in the windows filesystem (e.g. `C:\Users\username\the_folder`)
2. symlink the folder from the mounted drive in WSL to another place in WSL (e.g. `/home/wsl_user_name/the_folder -> /mnt/c/Users/username/the_folder`)
3. create a git repository in `the_folder` or in a subfolder of it (using git from WSL)
4. `cd /home/wsl_user_name/the_folder && code .`
5. look at the explorer sidebar of VS Code, nothing is highlighted, marked or faded
6. `cd /mnt/c/Users/username/the_folder && code .`
7. look at the explorer sidebar of VS Code, everything is fine

Does this issue occur when you try this locally?: Yes, on WSL
Does this issue occur when you try this locally and all extensions are disabled?: Yes, on WSL

Additional information:
Git integration of VS Code itself works just fine. 

![image](https://user-images.githubusercontent.com/12534520/80940344-ccb72700-8ddf-11ea-8e6f-d7d23a9efa37.png)

**Comment by aeschli** [comment] 2020-11-10 10:44
duplicate of https://github.com/microsoft/vscode-remote-release/issues/3959

**Closed by aeschli** 2020-11-10 10:44 UTC
Labels: wsl
