### ISSUE TITLE
WSL Error: "node: not found" when path have spaces

### ISSUE THREAD

**Issue by gjmv** [microsoft/vscode-remote-release#6465] opened 2022-03-17 18:28 UTC
I want to run in WSL, my real path have some spaces, and i have this error
```
/mnt/drive/wsl-ubuntu-home/user/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server: 12: /mnt
[2022-03-17 18:20:52.002] unidad/wsl-ubuntu-home/user/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/node: not found
```
/mnt/drive is a symlink to /mnt/f/Mi unidad/ (because of other issues with spaces)

Finally, i found that code-server file have this code

`ROOT=$(dirname $(dirname $(readlink -f $0)))`

I try to change it to 
`ROOT=$(dirname "$(dirname "$(readlink -f $0)")")`

Then starts to work.
I hope this helps someone

**Comment by chrissnell-okta** [comment] 2022-03-17 18:38
This is probably a duplicate of #6462

**Comment by bamurtaugh** [comment] 2022-04-18 20:40
Thanks for reporting. @gjmv are you still experiencing this / is this a dupe of #6462?

**Comment by gjmv** [comment] 2022-04-18 21:17
Hi, is not dupe of that.

In my case, is a issue with `~/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server` file, in line 10
`ROOT=$(dirname $(dirname $(readlink -f $0)))`

need to be quoted `ROOT=$(dirname "$(dirname "$(readlink -f $0)")")`

**Comment by aeschli** [comment] 2022-04-25 12:57
I verified that the latest version of the code-server script for Linux (as used in WSL) has the quotes: https://github.com/microsoft/vscode/blob/main/resources/server/bin/code-server-linux.sh#L10

**Closed by aeschli** 2022-04-25 12:57 UTC
Labels: wsl, needs more info
