### ISSUE TITLE
Additional features not applied

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-release#7411] opened 2022-10-25 11:29 UTC
Testing #7403

Following the test plan item flow, I additionally pick `fish` as an additional feature to add to my devcontainer...

![image](https://user-images.githubusercontent.com/22350/197761235-5d5d16aa-19ed-434a-a310-66ca1488d4e9.png)

But it doesn't seem like that did anything:

![image](https://user-images.githubusercontent.com/22350/197761537-1218de26-f50f-47b9-a7b3-54b4a5650177.png)

**Comment by joyceerhl** [comment] 2022-10-27 18:17
Still repros, I think this is not yet ready for verification since there hasn't been a new release since https://github.com/microsoft/vscode-remote-containers/pull/313

**Comment by rzhao271** [comment] 2022-10-28 17:31
Not sure if the feature is still unavailable.
I wasn't prompted to select additional features. Instead, the dev container just tried to build, and failed.
![Screenshot showing ls command failed when trying to build the container](https://user-images.githubusercontent.com/7199958/198697452-edec2a53-6b41-4b3a-bb15-43cea813dac9.png)

**Comment by joyceerhl** [comment] 2022-11-01 20:28
Still repros for me in v0.262.1

**Comment by chrmarti** [comment] 2022-11-02 08:29
@joyceerhl Could you provide steps to reproduce?

**Comment by joyceerhl** [comment] 2022-11-02 20:19
I followed the flow that Joao described with the latest Containers extension and created an Alpine container with the fish feature. After the container was created, fish was not on the path.

**Comment by chrmarti** [comment] 2022-11-28 15:31
Thanks, tracking as https://github.com/devcontainers/spec/issues/58. Closing as fixing the UI issue.

**Closed by chrmarti** 2022-11-28 15:31 UTC
Labels: bug, containers, info-needed
