### ISSUE TITLE
Make is easy for vscode remote SSH to change file to writable

### ISSUE THREAD

**Issue by mohdyusuf** [microsoft/vscode-remote-release#2961] opened 2020-05-08 22:35 UTC
While editing file (Windows 10 client) over remote SSH (Linux server), sometimes the file is locked (non writable).

I would have to open terminal and do chmod u+w <file> first before i can save.

Maybe if there is an easier way to make file writable by right clicking on the file tab to change mode?
I do see "Open in Terminal" option from right click on the file under workspace tree, but not on the file tab.

**Comment by Chuxel** [comment] 2020-06-09 01:21
This looks like a dupe of #3071. That has a bit more detail, so closing this in favor of the other one.

**Closed** 2020-06-09 01:21 UTC
Labels: *duplicate
