### ISSUE TITLE
Error while installing 'XML' extension. Please check the log for more details.

### ISSUE THREAD

**Issue by bcondict** [microsoft/vscode-remote-release#8116] opened 2023-02-28 19:31 UTC
Type: <b>Bug</b>

When i'm working on WSL, lately have been some troubles trying to download some extensions, problem says 'EACCES: EACCES: permission denied, rename'. Thing is neither the first nor the second file exists. 

Extension version: 0.75.3
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Connection to 'wsl+ubuntu-20.04' could not be established
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (2.44GB free)|
|Process Argv|--crash-reporter-id 873285eb-d58f-4e0f-a667-4045a4683acc|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu-20.04' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|Memory (System)|15.95GB (2.44GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
6233i204:30672705
vsccsb:30662443
pythonb192cf:30669361

```

</details>

**Comment by aeschli** [comment] 2024-12-13 09:27
I'm not able to reproduce. Do you still see this issue?

**Comment by aeschli** [comment] 2024-12-20 16:42
Closing, can not reproduce.

**Closed by aeschli** 2024-12-20 16:42 UTC
Labels: wsl
