### ISSUE TITLE
Enable offline install option?

### ISSUE THREAD

**Issue by mattbement** [Microsoft/vscode-remote-release#85] opened 2019-05-03 16:48 UTC
I can get remote-ssh to work and configured with all necessary extensions on one server.  I then want to be able to connect to another, identical server that has no external internet access.  Are there any offline installation options?

**Comment by Tyriar** [comment] 2019-05-03 17:23
Duplicate of https://github.com/Microsoft/vscode-remote-release/issues/15

**Closed by Tyriar** 2019-05-03 17:23 UTC
