### ISSUE TITLE
wget no proxy setting ignored

### ISSUE THREAD

**Issue by ziofat** [microsoft/vscode-remote-release#897] opened 2019-07-04 09:58 UTC
- VSCode Version:1.36.0
- Local OS Version:macos 10.14.5
- Remote OS Version:centos 7.2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect with remote ssh for the first time, initialize the remote server. Right now, the vscode server will output something like “Tunneling remote port 36368 to local port 36368”. With this window, everything is OK.
2. Create a .wgetrc file at `/root/`, with contents:
```
use_proxy=on
http_proxy=some proxy
https_proxy=some proxy
no_proxy="127.0.0.1,.local"
```
3. Note that the port vscode-server using is not public exposed, which means if using proxy to access it, it will return 502.
4. Reload VSCode window.
5. It will fail to connect with this error message: `Checking server status with wget http://127.0.0.1:36368/delay-shutdown: 2019-07-04 17:03:08 Error 502：Bad Gateway`.
6. Edit the .wgetrc file on remote server, turn off proxy.
7. Everything will work again.

My remote server is behind a corporation proxy, this is why I set a proxy for wget to download the vscode-server.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment] 2019-07-05 21:49
I'm just invoking wget in the normal way, so I'm not sure why it isn't reading your config file. Does it work if you hit that url with wget yourself in some terminal?

**Comment by ziofat** [comment] 2019-07-06 02:48
I used wget in terminal and it respected the no_proxy.

The wget invoked by vscode is reading my config file, but not understand the no_proxy setting.

**Comment by aaronbai** [comment] 2019-07-06 10:28
Stucking in the same problem.

**Comment by roblourens** [comment] 2019-07-06 18:41
Are you sure the quotes around `"127.0.0.1,.local"` are correct? Can you try removing them to check? That's what works for me

**Comment by ziofat** [comment] 2019-07-08 05:30
@roblourens, I removed no_proxy line and got same error.

**Comment by aaronbai** [comment] 2019-07-08 06:53
Found the Solution, just change `no_proxy="127.0.0.1,.local"` to `no_proxy=127.0.0.1,.local`, discards the quotes, that works for me. Give it a try. @ziofat

**Comment by roblourens** [comment] 2019-07-10 18:14
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/895

**Closed by roblourens** 2019-07-10 18:14 UTC
Labels: needs-more-info
