### ISSUE TITLE
Rebuild container command fails: Container is not running

### ISSUE THREAD

**Issue by mhofman** [microsoft/vscode-remote-release#107] opened 2019-05-04 02:01 UTC
Issue Type: <b>Bug</b>

Using the rebuild container command consistently fails.
It reloads the window and immediately complains that the operation failed.
The logs indicate that it's trying to perform `docker exec` commands on a container that is not running.

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T05:15:04.403Z)
OS version: Linux x64 4.19.26-03278-g71dc68f9c9d0
Fetching remote diagnostics for 'Dev Container: Node.js (current) & TypeScript' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 1, 0|
|Memory (System)|4.84GB (2.26GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

Fetching remote diagnostics for 'Dev Container: Node.js (current) & TypeScript' failed.
</details>Extensions: none

**Comment by mhofman** [comment] 2019-05-04 02:02
After manually reloading the window the container rebuilds properly.

**Comment by egamma** [comment] 2019-05-06 06:55
@mhofman please provide more information for how we can reproduce the problem, e.g, share your devcontainer.json/Dockerfile.

**Comment by mhofman** [comment] 2019-05-06 16:04
Any container I've tried really, including the example ones.
One thing I forgot to mention, the failure happens when I make a change to either the `devcontainer.json` or `Dockerfile`, and want to recreate the container based on those changes.

```
git clone https://github.com/Microsoft/vscode-remote-try-node
code-insider vscode-remote-try-node
```

This also fails as described above: https://github.com/mhofman/tc39-weakrefs-shim/tree/master/.devcontainer

**Comment by egamma** [comment] 2019-05-07 06:39
@mhofman 

>The logs indicate that it's trying to perform docker exec commands on a container that is not running.

Can you please attach the logs and also what is shown in the Dev Containers terminal.

**Comment by chrmarti** [comment] 2019-05-07 07:42
I think I have seen this, logs would be great. This could be the old container still being around when the resolver starts.

**Comment by egamma** [comment] 2019-05-07 07:44
>This could be the old container still being around when the resolver starts.

Good hint. @mhofman can you make sure you remove the container manually using the Docker command line before you rebuild.

**Comment by mhofman** [comment] 2019-05-07 10:31
Yeah I'm editing the container files from within the container, so it'd make sense that the container is still around. For the same reason I can't remove it since VSCode is currently using it.

I realize now this is more of a feature request: "be able to update dev container config from VSCode in remote mode".

**Comment by trondhindenes** [comment] 2019-05-07 10:39
Can repro this. It looks like the VSCode extension doesn't do a good enough job of checking that the debug container actually runs.

**Comment by egamma** [comment] 2019-05-07 10:46
@trondhindenes can you provide steps for how you can reproduce this?

I've just tried to rebuild the container of the vscode-remote-try-node example and it worked for me.

**Comment by egamma** [comment] 2019-05-07 10:46
@chrmarti could we check that the container has really shutdown once you removed it, before you start the rebuild?

**Comment by trondhindenes** [comment] 2019-05-07 10:50
Sometimes Docker for Windows ends up in a state where it's unable to set up the required publishing rules for publishing ports in a Docker container (this happens quite often on both mine and colleagues' computers). In this case, the container crashes so it doesn't run, but it still exists. I'll try and grab some logs/screenshots next time it happens.

**Comment by chrmarti** [comment] 2019-05-08 10:27
@trondhindenes That's a separate problem, I'll open an issue for it.

**Comment by chrmarti** [comment] 2019-05-08 15:18
@mhofman Could you retry with 0.51.0 of the Remote Containers extension? We have refined the checks during startup a bit.

**Comment by mhofman** [comment] 2019-05-09 03:23
Updated to the latest versions and rebuilding the container now seem to work fine :)

**Comment by chrmarti** [comment] 2019-05-09 06:09
Thanks! Closing as fixed.

**Closed by chrmarti** 2019-05-09 06:09 UTC
Labels: bug, containers
