### ISSUE TITLE
Extension icons missing in activity bar and other places

### ISSUE THREAD

**Issue by ShiftyMcCool** [microsoft/vscode-remote-release#1407] opened 2019-09-12 13:01 UTC
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL

About VS Code:
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Remote info:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

Steps to Reproduce:
1. Open VS Code connected to WSL remote
2. Icons on sidebar and in other areas like Source Control panel are invisible but buttons and tooltips still work

Does this issue occur when you try this locally?: Does not happen when using not-WSL projects
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No  N/A??

Let me know if you need any other info.

![image](https://user-images.githubusercontent.com/1320624/64785940-6ffab980-d53b-11e9-92b2-87217c25adc3.png)

**Comment by ShiftyMcCool** [comment] 2019-09-25 19:17
Some icons appear at random, but are missing again after restarting the app. If I notice a pattern I will comment here, but so far it seems completely random.

**Comment by Kai-Richardson** [comment] 2019-09-27 15:58
Hello, I'm experiencing this issue as well.

About VS Code:
Version: 1.39.0-insider (system setup)
Commit: b0d714d2de2886060e0904bf0cc774e0d70667cd
Date: 2019-09-26T09:07:24.281Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18990

uname -rv:
kernel: 4.19.67-microsoft-standard 
#1 SMP Sun Aug 18 13:37:54 UTC 2019

For me, sometimes the icons appear if you hover over the bar:
![2019-09-27_08-55-23](https://user-images.githubusercontent.com/49656058/65783415-922c3400-e104-11e9-8cdf-ad3818742f29.gif)

I noticed something strange in the webdev console.

```
Failed to load resource: net::ERR_INVALID_URL
vscode-remote-resource?path=%2Fhome%2Fcassini%2F.vscode-server-insiders%2Fbin%2Fb0d714d2de2886060e0904bf0cc774e0d70667cd%2Fextensions%2Fgit%2Fresources%2Ficons%2Fdark%2Frefresh.svg&tkn=b17cd3a4-53a6-4dc8-9d73-13285efe8bfd:1 Failed to load resource: net::ERR_INVALID_URL
vscode-remote-resource?path=%2Fhome%2Fcassini%2F.vscode-server-insiders%2Fextensions%2Fmhutchie.git-graph-1.16.0%2Fresources%2Fcmd-icon-dark.svg&tkn=b17cd3a4-53a6-4dc8-9d73-13285efe8bfd:1 Failed to load resource: net::ERR_INVALID_URL
vscode-remote-resource?path=%2Fhome%2Fcassini%2F.vscode-server-insiders%2Fbin%2Fb0d714d2de2886060e0904bf0cc774e0d70667cd%2Fextensions%2Fgit%2Fresources%2Ficons%2Fdark%2Fopen-file.svg&tkn=b17cd3a4-53a6-4dc8-9d73-13285efe8bfd:1 Failed to load resource: net::ERR_INVALID_URL
vscode-remote-resource?path=%2Fhome%2Fcassini%2F.vscode-server-insiders%2Fbin%2Fb0d714d2de2886060e0904bf0cc774e0d70667cd%2Fextensions%2Fgit%2Fresources%2Ficons%2Fdark%2Fclean.svg&tkn=b17cd3a4-53a6-4dc8-9d73-13285efe8bfd:1 Failed to load resource: net::ERR_INVALID_URL
vscode-remote-resource?path=%2Fhome%2Fcassini%2F.vscode-server-insiders%2Fbin%2Fb0d714d2de2886060e0904bf0cc774e0d70667cd%2Fextensions%2Fgit%2Fresources%2Ficons%2Fdark%2Fstage.svg&tkn=b17cd3a4-53a6-4dc8-9d73-13285efe8bfd:1 Failed to load resource: net::ERR_INVALID_URL
vscode-remote-resource?path=%2Fhome%2Fcassini%2F.vscode-server-insiders%2Fextensions%2Feamodio.gitlens-10.0.1%2Fimages%2Fdark%2Ficon-stash-save.svg&tkn=b17cd3a4-53a6-4dc8-9d73-13285efe8bfd:1 Failed to load resource: net::ERR_INVALID_URL
```

It seems like the icons are trying to load, but they have an invalid URL.

**Comment by alexandrudima** [comment] 2019-10-01 13:56
@Kai-Richardson Insiders was broken for a couple days and was fixed via #1502

@ShiftyMcCool Could you please try out Insiders?

**Comment by Kai-Richardson** [comment] 2019-10-01 16:57
Confirmed fixed on my machine.

Version: 1.39.0-insider (system setup)
Commit: 313ede61cbad8f9dc748907b3384e059ddddb79a
Date: 2019-10-01T07:29:05.652Z

**Comment by ShiftyMcCool** [comment] 2019-10-02 12:53
@alexandrudima After installing Insiders I noticed the same issues.  However, I was thinking about the "random" nature of this issue and decided to try a few things to narrow it down.  Long story short, I found that it's an issue with being behind my corporate proxy.  The "random" times that they were working was when I was coding from home outside the proxy or at the office on the open wi-fi. 

So far, I can't seem to get around this.  I added the proxy to VS Code settings but it has no effect.  I also set the http_proxy env variable in WSL to my corporate server with no luck.

At this point you can probably consider this closed since the issue is on my end.  

Thanks!

**Comment by alexandrudima** [comment] 2019-10-02 19:49
@ShiftyMcCool ahaa! Thanks very much for following through... I am not 100% sure if we should attempt to repro and it might improve with the recent changes from @aeschli where the resolver now returns `[::1]` and not the ip address of WSL...

So I would close this issue for now, and keep our eyes open in case other issues pop up, and then immediately ask them about proxies... If it turns out to be a common problem, we can then further investigate.

**Closed by alexandrudima** 2019-10-02 19:49 UTC
Labels: needs-more-info, remote
