### ISSUE TITLE
Unable to download VS Code server locally: Server returned 404

### ISSUE THREAD

**Issue by beeblebrox** [microsoft/vscode-remote-release#6806] opened 2022-06-09 22:51 UTC
## Env
`Mac OS Monterey Version 12.4, MacBook Pro, Intel Core I7`
```
Visual Code
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z (3 wks ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0
```
## Issue
This is the same issue as #6607 but that one is closed. Even if this is temporary it is blocking me now today again with the exact same issue and symptom after I updated to the May update.  Perhaps this is a CDN issue where if you are unlucky you're getting directed to a misconfigured server?

From the setup output:
```
[16:28:44.839] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/u/me/sfrtp/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5"}
[16:28:44.839] Downloading VS Code server locally...
[16:28:45.254] Resolver error: Error: Server returned 404
    at S (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:619:22872)
    at k.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:620:1592)
[16:28:45.259] ------
```
From the dev terminal on fetch of https://update.code.visualstudio.com/commit%3Ac3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/server-linux-x64/stable
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /commit%3Ac3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/server-linux-x64/stable</pre>
</body>
</html>
```
Going to the site without the `:` urlecoded works fine
https://update.code.visualstudio.com/commit:c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/server-linux-x64/stable
I think the main thing to note here is this behavior is on the local download of the file and possibly because the plugin will (properly) use the urlencoding due to the `:` symbol, and it is the remote server that can't handle it correctly. 

## Workaround??
**Is there** a place I can download the tar.gz manual as a workaround for now?

**Comment by beeblebrox** [comment] 2022-06-09 22:54
Additional, just in case it is a server issue maybe the dig on it will help?
```
➜  ~ dig update.code.visualstudio.com

; <<>> DiG 9.11.3-1ubuntu1.9-Ubuntu <<>> update.code.visualstudio.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12873
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;update.code.visualstudio.com.  IN      A

;; ANSWER SECTION:
update.code.visualstudio.com. 4 IN      CNAME   vscode-update.trafficmanager.net.
vscode-update.trafficmanager.net. 6 IN  CNAME   vscode-update-wus2.azurewebsites.net.
vscode-update-wus2.azurewebsites.net. 13 IN CNAME waws-prod-mwh-049.sip.azurewebsites.windows.net.
waws-prod-mwh-049.sip.azurewebsites.windows.net. 29 IN CNAME waws-prod-mwh-049-salt.westus2.cloudapp.azure.com.
waws-prod-mwh-049-salt.westus2.cloudapp.azure.com. 9 IN A 40.64.128.224

;; Query time: 332 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Jun 09 18:31:00 EDT 2022
;; MSG SIZE  rcvd: 284
```

**Comment by tanhakabir** [comment] 2022-06-10 06:14
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6804

**Closed by tanhakabir** 2022-06-10 06:14 UTC
Labels: ssh
