### ISSUE TITLE
use a wrong username to connect remote, version 0.50.0

### ISSUE THREAD

**Issue by tanganke** [microsoft/vscode-remote-release#2510] opened 2020-03-10 10:37 UTC
- VSCode Version: 1.43.0
- Local OS Version: Windows10
- Remote OS Version:CentOS8
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Update Remote-ssh extension to version 0.50
2.connect to my remote machine and i configed in C:\ProgramData\ssh\ssh_config (but not C:\Users\...) as

```
Host 10.0.0.8
    HostName 10.0.0.8
    User root
```

but instead of using root as the username, my windows system's username is used.
like ssh `windows username`@`remotehost`

**Comment by soul4soul** [comment] 2020-03-10 15:25
Seems like the same issue as #2512

**Comment by roblourens** [comment] 2020-03-16 18:49
Dupe of https://github.com/microsoft/vscode-remote-release/issues/2512

**Closed by roblourens** 2020-03-16 18:49 UTC
