### ISSUE TITLE
After Reopen in Container doing an Open Folder shows Dialog with Cannot reconnect

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-remote-release#6196] opened 2022-01-19 19:00 UTC
- VSCode Version: 1.64.0-insider (I tried on 1.63.2 also)
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu 20.04.3
- Remote Extension/Connection Type: Docker

- Logs:
[remoteContainers-2022-01-19T18-41.988Z.log](https://github.com/microsoft/vscode-remote-release/files/7899768/remoteContainers-2022-01-19T18-41.988Z.log)

Steps to Reproduce:

1. Unzip the issue.zip located here [issue.zip](https://github.com/microsoft/vscode-remote-release/files/7899890/issue.zip)
1. Open VS Code
2. Open the folder issue/customers/bintzpress/stack. This contains a .devcontainer.
3. Select Reopen in container (opens fine to the projects directory)
4. Select Open Folder and select wp-cli-fse-support or another folder
5. Everything seems to open fine but a few seconds later the error dialog appears saying Cannot reconnect (checking in docker shows containers have stopped)

This worked with previous versions. I can't find a previous version that works now though.

I only have the docker and remote containers extensions installed.

I am trying to do WordPress development using a Docker container to develop on. I use VS Code to connect and then switch to a folder having the git project I am working on. Switching folders allows me to use the Git functionality in VS Code.

**Comment by bintzpress** [comment] 2022-01-19 22:01
I just checked and this problem occurs on Ubuntu 21.10 also. Same behavior.

**Comment by chrmarti** [comment] 2022-01-20 15:55
The newlines in the `WORDPRESS_CONFIG_EXTRA` environment variable trigger a bug in our parsing with the side-effect of `docker-compose stop` being run when it should not. Maybe you can override that variable with the newlines removed as a workaround. I need to investigate a possible fix.

**Comment by bintzpress** [comment] 2022-01-20 22:16
Interesting. I would never have found that. Thanks for getting back to me.
I tried it and it worked. Thanks! Yes I can do environment variables on a
single line for now although for a WordPress multisite the line will be
really long, but that shouldn't be a problem except from a readability
standpoint.

Thanks again,
Brian Bintz
***@***.***

**Comment by chrmarti** [comment] 2023-12-14 16:36
Cannot reproduce anymore. Closing.

**Closed by chrmarti** 2023-12-14 16:36 UTC
Labels: bug, containers
