### ISSUE TITLE
GPG commit signing doesn't works in VSCode Server

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode-remote-release#6902] opened 2022-07-07 19:43 UTC
- VSCode Version: 1.69.0
- Local OS Version: Arch Linux
- Remote OS Version: Arch Linux
- Remote Extension/Connection Type: Server
- Logs:

Steps to Reproduce:

1. Enable force commit signing
2. Try to make a commit by pressing "Commit" button
3. See gpg error: `error: gpg failed to sign the data`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

This is happens because gpg tries to run pinentry to ask for password. While it is working on desktop vscode because gpg uses qt dialgog (`/usr/bin/pinentry-qt`), this obviously won't work for web environment. On web environment this issue probably can be solved by using pinentry-tty, but vscode currently has no mechanism to handle it.

**Comment by aeschli** [comment] 2022-07-08 09:12
Duplicate of https://github.com/microsoft/vscode/issues/130415

**Closed by aeschli** 2022-07-08 09:12 UTC
