### ISSUE TITLE
Folder settings does not work when using Remote SSH

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-remote-release#548] opened 2019-05-25 23:21 UTC
- VSCode Version: 1.35.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.17763
- Remote OS version: Linux x64 4.4.0-66-generic

### Steps to Reproduce:

Folder settings are NOT being returned by the vscode API when using Remote SSH,
i.e [`vscode.workspace.getconfiguration('python')`](https://code.visualstudio.com/api/references/vscode-api#workspace) does not return ["Workspace Folder configurations"](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration).

To reproduce,

1. Use remote SSH, then install Python extension on remote machine.
2. Have any setting in `.vscode/settings.json` file, and see that it has no influence. (Eg. Add setting `"python.pythonPath":"path/to/interpreter"` and see no interpreter is selected)

It breaks many core features of the python extension, like selecting the interpreter,
[vscode-python#5724: Selecting interpreter does not work when using Remote SSH connection](https://github.com/microsoft/vscode-python/issues/5724)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment] 2019-06-03 11:06
/duplicate

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/273

**Closed** 2019-06-03 11:06 UTC
Labels: *duplicate
