### ISSUE TITLE
Set default extensions for Remote - WSL

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-remote-release#3521] opened 2020-08-14 21:45 UTC
Now that we have Settings Sync, it would be very useful if we could have such a configuration key, just like all the other Remote extensions kind, even Codespaces.

![image](https://user-images.githubusercontent.com/29582865/90295379-345d2380-de5f-11ea-8bbf-026758fd61b6.png)

**Comment by aeschli** [comment] 2020-11-09 21:55
duplicate of #2704

**Closed by aeschli** 2020-11-09 21:55 UTC
Labels: feature-request, wsl
