### ISSUE TITLE
VSCode Remote WSL: unable to rename folder

### ISSUE THREAD

**Issue by eisber** [microsoft/vscode-remote-release#208] opened 2019-05-07 17:51 UTC
Issue Type: <b>Bug</b>

I tried to rename a folder with some files in it and it silently failed. When trying in the terminal inside VSCode, in WSL bash or Windows Explorer I get permission denied (another program accesses the folder). 

Extension version: 0.32.0
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:08:08.969Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (3.48GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment] 2019-05-08 07:13
Duplicate of https://github.com/Microsoft/WSL/issues/3395.

This will be addressed by WSL2!

**Comment by auchenberg** [comment] 2019-05-24 21:25
Re-opening, as this is still an issue in WSL1 and we may need to address this until WSL2 ships.

**Comment by egamma** [comment] 2019-05-27 14:30
@isidorn can you look into providing a better error message in this situation.

**Comment by isidorn** [comment] 2019-05-27 14:32
I think the issue here is that the error silently fails. Let me first look into if we can surface the error, and only then if we can provide a better one.

**Closed** 2019-06-24 12:56 UTC
Labels: upstream, wsl

**Comment by aeschli** [comment] 2019-07-04 09:09
There's now a new setting to swich to polling and avoid the 'can not rename' probem.
See https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace
