### ISSUE TITLE
"Opening Remote" spins indefinitely

### ISSUE THREAD

**Issue by mjrosengrant** [microsoft/vscode-remote-release#5213] opened 2021-06-16 14:01 UTC
Issue Type: <b>Bug</b>

Whenever I try to attach to a running docker container (WSL, application, devcontainer) a new window opens up, and the "Opening Remote" message in the corner spins endlessly.

I have a Ubuntu 20.04 WSL setup on my computer

Easiest way to reproduce:
1) Open VSCode
2)  Click the "Open a Remote Window Button
3) Select "New WSL Window"
4) Select a folder to  open, and then thats when the "Opening Remote" message appears

It doesn't seem to matter which folder I try to open. The folder lives on the WSL instance. I've been using this workflow for several months now, and it stopped working this week.

Similar issues occur when I have my application running, and I try to attach to the running container for debugging. So its not necessarily just the WSL instance. Other coworkers using Macs have not been able to replicate
 

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.28GB free)|
|Process Argv|--crash-reporter-id f1561075-1c15-4fc5-aa75-cf8450055d6a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999406279
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.4419
vsliveshare-audio|ms-|0.1.91

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30319631
vscorehov:30309549
vscod805cf:30301675
binariesv615cf:30321889

```

</details>

**Comment by aeschli** [comment] 2021-06-17 06:57
You see this in both when attaching to docker container` (Dev Containers extension) as well as opening a New WSL Window ?
Is the window stuck, or can you work as usual?
Anything in the WSL log? (command : Remote-WSL: Show Log)
To get even more logging:
- run command `Developer: Set Log Level...` Select `Trace`
- the open a remote window with the problem
- run command `Developer: Show Log..` , pick 'Window', 'Remote Server' and ' Remote Extension Host'

**Comment by mjrosengrant** [comment] 2021-06-17 14:38
The issue happens for both dev container extensions and WSL windows

In the logs, this is the message that repeats as the "Opening Remote "message spins
```
[2021-06-17 10:33:25.277] [renderer3] [error] Handler already set!: Error: Handler already set!
    at n.setHandler (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:5169)
    at u.registerListeners (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39805)
    at new u (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39603)
    at p._createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at new Y (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2455:27087)
    at p._createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3551
    at P._executor (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18550)
    at P.get value [as value] (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18743)
    at Object.get (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3652)
    at Dn.get isMultiSessionView [as isMultiSessionView] (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2463:3179)
    at new Dn (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2455:66272)
    at p._createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at L.createView (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:35407)
    at L.onDidAddViewDescriptors (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:36831)
    at file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:32748
    at n.fire (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at g.triggerOnDidAddVisibleViewDescriptors (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2466:9818)
    at g.onDidChangeContext (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2466:13965)
    at file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2466:6674
    at n.fire (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:59092
    at m.fire (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at m.fire (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:2784)
    at o.setContext (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:120700)
    at set (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:118989)
    at new u (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39758)
    at p._createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at new Y (file:///C:/Users/username/username/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2455:27087)
    at p._createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3551
    at P._executor (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18550)
    at P.get value [as value] (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18743)
    at Object.get (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:3652)
    at new i (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2395:10509)
    at p._createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at new dn (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:652:76362)
    at p._createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1371)
    at p.createInstance (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:625:790)
    at M.createEditorControl (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:26859)
    at M.createEditor (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:26474)
    at M.createEditor (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:174645)
    at M.create (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:741:185548)
    at D.renderBody (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2470:171603)
    at D.render (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:170:17773)
    at D.render (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2417:115309)
    at L.onDidAddViewDescriptors (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:36882)
    at L.create (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:33116)
    at O.create (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:54282)
    at ui.showComposite (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2417:106181)
    at ui.doOpenComposite (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2417:105036)
    at ui.openComposite (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2417:104551)
    at ui.doOpenPanel (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:68944)
    at ui.openPanel (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:69037)
    at file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:24532
    at async Promise.all (index 3)
    at async Object.G [as settled] (file:///C:/Users/username/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:21518)
```

**Comment by KinIcy** [comment] 2021-06-17 16:28
I'm also experiencing this issue for a couple of days. Some folders in my WSL stopped working. Whenever I open them, the `Opening Remote` message sping endlessly,

As a workaround, I can rename the folder I'm trying to open.

**Comment by aeschli** [comment] 2021-06-18 05:30
So you rename the folder, and then open works? Sounds like a problem restoring the views. That's also
@bpasero Is there a way to disable restoring of views or the view state of a folder?

Same stacktrace points as https://github.com/microsoft/vscode/issues/126339

**Comment by aeschli** [comment] 2021-06-18 05:38
Ah, now I see https://github.com/microsoft/vscode/issues/126339#issuecomment-862669116

@KinIcy @mjrosengrant Can you try the steps there and let me know if that also fixes the 'spinning indefinitely' issue ?

> navigate to folder %USERPROFILE%\AppData\Roaming\Code\User\workspaceStorage and delete the contents (notably state.vscdb) and then restart VSCode.

**Comment by bpasero** [comment] 2021-06-18 05:41
> Is there a way to disable restoring of views or the view state of a folder?

Not unless you delete the SQLite DB for that workspace, the path is printed when you log the storage contents from F1.

Related feature request: https://github.com/microsoft/vscode/issues/22613

**Comment by KinIcy** [comment] 2021-06-18 06:25
@aeschli just tried that, now the folder opens normally

**Comment by aeschli** [comment] 2021-06-18 09:23
Thanks for trying. 
I mark this issue a duplicate of https://github.com/microsoft/vscode/issues/126339

**Closed by aeschli** 2021-06-18 09:23 UTC
Labels: needs more info

**Comment by mjrosengrant** [comment] 2021-06-18 17:23
Confirming that clearing workspaceStorage solved my issue. Thanks for your help! 😁
