### ISSUE TITLE
WebView port mapping not working under Remote SSH

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-remote-release#3362] opened 2020-07-14 01:11 UTC
- VSCode Version: 1.47.0, 1.48.0-insider
- Local OS Version: macOS 10.15.5, Ubuntu 20.04
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Not sure if it is an issue of Remote-SSH or VSCode. So I already raised an issue there: https://github.com/microsoft/vscode/issues/102449 which originates from https://github.com/Ikuyadeu/vscode-R/issues/380.

To summarize, the following extension code is used to create the WebView.

```typescript
function showBrowser(url: string, title: string, viewer: string | boolean) {
    console.info(`[showBrowser] uri: ${url}, viewer: ${viewer}`);
    if (viewer === false) {
        env.openExternal(Uri.parse(url));
    } else {
        const port = parseInt(new URL(url).port);
        const panel = window.createWebviewPanel(
            'browser',
            title,
            {
                preserveFocus: true,
                viewColumn: ViewColumn[String(viewer)],
            },
            {
                enableScripts: true,
                retainContextWhenHidden: true,
                portMapping: [
                    {
                        extensionHostPort: port,
                        webviewPort: port,
                    },
                ],
            });
        panel.webview.html = getBrowserHtml(url);
    }
    console.info('[showBrowser] Done');
}

function getBrowserHtml(url: string) {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    html, body {
        height: 100%;
        padding: 0;
        overflow: hidden;
    }
  </style>
</head>
<body>
    <iframe src="${url}" width="100%" height="100%" frameborder="0" />
</body>
</html>
`;
}
```

1. Call `showBrowser("http://127.0.0.1:22784/library/base/html/get.html", "title", "Active")` shows blank WebView.
2. Then call `showBrowser("http://127.0.0.1:22784/library/base/html/get.html", "title", false)` opens a local web browser page which shows correctly.
3. Then call `showBrowser("http://127.0.0.1:22784/library/base/html/get.html", "title", "Active")` again and the WebView shows correctly too.

It looks like the WebView port mapping is not enabled upon creation even though I specify `portMapping`.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Chuxel** [comment] 2020-07-14 13:42
//cc: @mjbvz

**Comment by renkun-ken** [comment] 2020-07-21 04:32
Any updates on this? It looks like extensions that rely on WebView port mapping are completely broken.

**Comment by renkun-ken** [comment] 2020-07-27 23:55
@rpodcast confirms that the same problem also occurs in development container. Then it seems that the port mapping problem is not only limited to SSH.

@Chuxel @mjbvz

**Comment by Chuxel** [comment] 2020-07-28 02:02
@mjbvz Should this be closed in favor of the VS Code issue? (https://github.com/microsoft/vscode/issues/102449)

**Comment by mjbvz** [comment] 2020-07-28 04:42
duplicate of https://github.com/microsoft/vscode/issues/102449

**Closed by mjbvz** 2020-07-28 04:42 UTC
Labels: ssh
