### ISSUE TITLE
Remote Container on Remote Host

### ISSUE THREAD

**Issue by cemendil** [microsoft/vscode-remote-release#2478] opened 2020-03-04 09:34 UTC
- VSCode Version: 1.42.1
- Local OS Version: Windows 7
- Remote OS Version: CentOS Linux release 7.6.1810 (Core)
- Remote Extension/Connection Type: Docker via SSH tunnel

VS Code :
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

172.18.12.12 is a CentOS Linux with : 

docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false

1. Open SSH tunnel in GIT bash, for examples
C:\Users\xxxx\AppData\Local\Programs\Git\usr\bin\ssh -i C:\Users\xxxx\ssh\id_rsa -NL localhost:23750:/var/run/docker.sock user@172.18.12.12
Check that SSH tun is OPEN

2. Edit settings.json and add "docker.host": "tcp://localhost:23750"

3. Open Remote Explorer "Containers"
List of containers is correctly 

4. Left click on any container, and select "Show Details" : OK
5. Left click on any container, and select "Inspect" : OK
6. Left click on any container, and select "Inspect" : KO (no logs appears in terminal)
7. Left click on any container, and select "Attache in New Window" : KO

[166 ms] Start: Check Docker is running
[250 ms] Start: Inspecting container
[378 ms] Start: Run in container: uname -m
[385 ms] Start: Run in container: cat /etc/passwd
[392 ms] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
        at doWrite (_stream_writable.js:413:19)
        at writeOrBuffer (_stream_writable.js:401:5)
        at Socket.Writable.write (_stream_writable.js:301:11)
        at c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.1\dist\extension.js:1:83504
        at c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.1\dist\extension.js:1:83868

The 2 first command seems to be ok, but the process always stop here.

**Comment by cemendil** [comment] 2020-03-10 12:08
Please, help !

**Comment by chrmarti** [comment] 2020-10-13 13:28
Should be working now.

Duplicate of #2481

**Closed by chrmarti** 2020-10-13 13:28 UTC
