### ISSUE TITLE
vscode-server on Windows not work with Git bash

### ISSUE THREAD

**Issue by pingu8007** [microsoft/vscode-remote-release#6302] opened 2022-02-08 02:16 UTC
- VSCode Version: 1.64.0 (user setup) / 5554b12acf27056905806867f251c859323ff7e9
- Local OS Version: Windows_NT x64 10.0.19044
- Remote OS Version: Windows_NT x64 10.0.19044
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Remote-SSH onto Windows machine with vscode standalone installed (*1)
2. Open Git bash in terminal panel
3. Execute `code`/`code --wait` inside terminal
4. Expecting open new editor tab but nothing happen

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

By running `printenv` I can confirm vscode-server is added to `PATH`, but the package downloaded doesn't contains **sh executable** `code` (not `code.cmd`) since it's a Windows machine. And Git bash doesn't pickup the `code.cmd` under vscode-server but fallback to vscode standalone's `code` (*1). This result another vscode instance been started.

*1: Haven't test with windows machine without vscode standalone installed. It should complaint command not found in such case.
*2: First found when I doing `git rebase -i`, and it turn out affecting ALL git command that bring up editor.

**Comment by pingu8007** [comment] 2022-02-08 02:25
A workaround is executing `code.cmd` everywhere explicitly. It works for both Git bash and any git command requiring editor.

```gitconfig
[core]
  editor = code.cmd --wait
```

**Comment by tanhakabir** [comment] 2022-02-08 06:04
Seems like a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6289? @aeschli

**Comment by pingu8007** [comment] 2022-02-08 06:12
> Seems like a duplicate of #6289? @aeschli

Probably not. The `remote-cli` part is present, fyi.
![image](https://user-images.githubusercontent.com/8936513/152928551-33cacce9-35ba-44a4-af9b-a51147a90021.png)

**Comment by pingu8007** [comment] 2022-02-08 06:38
To summing up,

- `code.cmd` is called in `cmd`/`pwsh` because Windows looking up extensions defined in `$PATHEXT`
- `code` is called in `bash` because it require filename been full matched
- Both shell can work on local Windows because vscode standalone contains both `code.cmd` and `code`
- Only `cmd`/`pwsh` works on remote Windows because vscode-server-win32 contains `code.cmd` only.

**Comment by aeschli** [comment] 2022-02-08 08:17
This is not a regression, right? You suggest that we add a `remote-cli/code` shell script to the windows code-server build so `code` can be opened out of a Git bash.

**Comment by pingu8007** [comment] 2022-02-08 08:46
No, it's not a regression. I open this issue before diving into it, and it turns out a edge case that I don't known who should response for it.

If you can add the necessary shell script, then everything works. If you think it's out of scope, however, this issue should have enough information for others, too. So it's up to you.

**Comment by lszomoru** [comment] 2022-03-01 15:33
> This is not a regression, right? You suggest that we add a remote-cli/code shell script to the windows code-server build so code can be opened out of a Git bash.

@aeschli, who would own making this change?

**Comment by aeschli** [comment] 2022-03-01 15:36
@lszomoru That would be me.

**Closed** 2022-12-15 14:06 UTC
Labels: feature-request
