### ISSUE TITLE
Error in Remote-Containers: Open Folder in Container

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#4137] opened 2020-12-04 16:07 UTC
Run `Remote-Containers: Open Folder in Container` and select a folder that doesn't have a devcontainer.json

Get the error:
Command 'Remote-Containers: Open Folder in Container...' resulted in an error (Cannot read property 'forceNewWindow' of null)

**Comment by RMacfarlane** [comment] 2020-12-04 16:28
Duplicate of https://github.com/microsoft/vscode/issues/111898

**Closed by RMacfarlane** 2020-12-04 16:28 UTC
