### ISSUE TITLE
WSL integration does not work with kernel that includes ext4 encryption

### ISSUE THREAD

**Issue by evertheylen** [microsoft/vscode-remote-release#2106] opened 2019-12-29 00:22 UTC
I hope you like weird bugs 😅 

- VSCode Version: 1.41.1
- Local OS Version: 10.0.19536.1000
- Remote OS Version: Arch (rolling release, up to date at time of writing)
- Remote Extension/Connection Type: WSL2

Steps to Reproduce:

1. Start VSCode
2. "Remote-WSL: New Window"
3. Errors show up: "Could not fetch remote environment" and "Failed to connect to the remote extension host server (Error: connect ECONNREFUSED 127.0.0.1:40127)" (note that the port number differs each time, which is expected AFAIK)

On the standard microsoft kernel `4.19.84-microsoft-standard` this works. However, I use my own kernel that I compiled following [this guide](https://gist.github.com/cerebrate/d40c89d3fa89594e1b1538b2ce9d2720). I just use the Microsoft settings and enable ext4 encryption (which otherwise works well btw). With this kernel, it fails as described above. The weird part is that when I recompile without ext4 encryption (literally just a single line in `.config`), WSL integration _does_ work. So to summarize:
  - Microsoft provided kernel works.
  - Self-compiled kernel with Microsoft settings works.
  - Self-compiled kernel with Microsoft settings and also `CONFIG_EXT4_ENCRYPTION=y` does *not* work.

Here is also the log: [wsl-log.txt](https://github.com/microsoft/vscode-remote-release/files/4007559/wsl-log.txt).

Things of note:
  - Remove `.vscode-server` from my Arch home directory and try again --> no change
  - Use VSCode Insiders (1.42.0) --> no change
  - I only have one WSL distribution (Arch), there is no confusion possible.
  - My self-built kernels are about ~8MB, while the Microsoft provided kernel is ~56 MB, unsure where the extra 48MB is coming from
  - As the log suggests, I tried to open a browser (under Windows) on `http://127.0.0.1:40127/version`, but it can not connect. _However_, I can manually run `/home/evert/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/server.sh --port=0`, and then connecting _does_ work (and I can see the commit hash under `/version`, as expected). I don't know how I can tell VSCode to connect to a specific port though.

Because of the last point, I don't see it as a kernel issue. I guess custom kernels are not "officially supported", but I'd think a weird bug like this may be indicative of a deeper problem somewhere.

**Comment by aeschli** [comment] 2019-12-30 11:19
I have no experience with customized WSL distros, no I'm probably not of a big help.

All looks fine in the log. Very strange that things work when you manually start the server.

As seen in the log. `Remote - WSL` extension starts `C:\WINDOWS\System32\wsl.exe -d Arch sh -c 'env && VSCODE_WSL_DEBUG_INFO=true "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 26076a4de974ead31f97692a0d32f90d735645c0 stable .vscode-server 0  ' in c:\Users\Evert\.vscode\extensions\ms-vscode-remote.remote-wsl-0.41.6` from the Windows side.

Can try that from a Windows command prompt to see if you can still connect to it? No startup scripts are invoked. Maybe that's the difference when you start the server by hand.

Maybe you want to move this issue to the WSL repo. I hope the WSL guys can help you to understand what can cause connectivity issues when making changes to the kernel.

**Comment by evertheylen** [comment] 2020-01-24 21:44
Sorry for the late answer, and thanks a lot for the response. I was wondering if [this issue](https://github.com/microsoft/WSL/issues/4769) might have been involved somehow, but sadly it did not fix it. I'll give it one more try myself (that command is a good starting point) and move the issue to the WSL repo if needed.

**Comment by evertheylen** [comment] 2020-01-24 22:07
Ok so that was rather quick. I managed to get it working by adding a `--host=0.0.0.0` option in the script that is placed at `.vscode-server/bin/<commit hash>/server.sh`, like so:
```
"$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" --host=0.0.0.0 "$@"
```
I'll try to figure out how this could ever be influenced by a custom kernel tomorrow. I tried to be extremely rigorous in my previous tests with various kernels (tried each kernel _at least_ 2 times), but maybe something still escaped my attention since it sure doesn't seem related to ext4 encryption.

**Comment by evertheylen** [comment] 2020-01-25 09:29
It seems like I can't find a difference between the various kernels, so at least this makes it less likely to be a kernel issue and more like a "proper" VSCode Remote bug. I still require the "0.0.0.0" trick, which is weird since version 19551 I can start whatever I want on localhost and it will work.

**Comment by aeschli** [comment] 2020-11-09 20:31
Closing the issue as this seems to be caused by the custom kernel and no other users have run into this.

**Closed by aeschli** 2020-11-09 20:31 UTC
Labels: wsl
