### ISSUE TITLE
Remote-Containers: Create Container Configuration File command doesn't exist

### ISSUE THREAD

**Issue by jzngdt** [microsoft/vscode-remote-release#851] opened 2019-06-27 14:38 UTC
Issue Type: <b>Bug</b>

The commnads 
>Remote-Containers Create Container Configuration File
>Remote-Containers Reopen Folder in Container 
do not exist in Insiders nor production version of VS Code as descibed in the documentation  at quick-start-open-a-folder-in-a-container.
What else has changed since the document was uploaded?
Doesn't anyone  update changes to the containers commands for Docker or Windows?

Extension version: 0.64.0
VS Code version: Code - Insiders 1.36.0-insider (b7265738444f1eee05762341b4361ee6452a4154, 2019-06-27T05:22:06.378Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Chuxel** [comment] 2019-06-27 15:00
Dupe of #853

**Closed by Chuxel** 2019-06-27 15:00 UTC
