### ISSUE TITLE
How to install vs code server when SSH host doesn't have access to internet?

### ISSUE THREAD

**Issue by RobCannon** [microsoft/vscode-remote-release#1228] opened 2019-08-22 16:20 UTC
Is there a way to get the vs code server installed when the server I am SSHing to doesn't have access to the internet?  It would be great if the download was done from the computer running VS Code and the install was pushed to the SSH host via scp.  This would be great for WSL and containers, also.  It would eliminate the proxy setups that I can't get to work in those environments.

**Comment by egamma** [comment] 2019-08-22 18:28
Duplicate of #15

**Closed by egamma** 2019-08-22 18:28 UTC
