### ISSUE TITLE
Allow commands to be appended to ssh connection command through the ssh config

### ISSUE THREAD

**Issue by Nosferican** [microsoft/vscode-remote-release#2808] opened 2020-04-21 21:15 UTC
I would like to be able to execute some command to modify the shell returned by the SSH command.
For example,
```
ssh user@cluster.domain.edu ijob -A MyAccount -p MyPartition -t 01:00:00
```
should return the shell in the interactive Slurm job just as
```
ssh user@cluster.domain.edu ijob -A MyAccount -p MyPartition -t 01:00:00 -pty -u /bin/bash
```
does. When setting up a remote connection the SSH command does not register the appended commands in the SSH config file.
```
Host Cluster
  HostName cluster.domain.edu
  User my_id
  IdentityFile ~/.ssh/id_rsa
```
It should have something like
```
Host Cluster
  HostName cluster.domain.edu
  User my_id
  IdentityFile ~/.ssh/id_rsa
  Command ijob -A MyAccount -p MyPartition -t 01:00:00
```

Related: https://github.com/microsoft/vscode-remote-release/issues/141 , https://github.com/microsoft/vscode-remote-release/issues/1722

**Comment by Nosferican** [comment] 2020-05-14 11:04
Current workaround is to have them in your `~/.bashrc`.

**Comment by mcusi** [comment] 2020-11-04 17:33
Hey this would be really helpful! thanks

**Comment by roblourens** [comment] 2020-11-06 21:57
Thanks for the issue, I would call it a duplicate of the issues you linked

**Closed by roblourens** 2020-11-06 21:57 UTC
Labels: feature-request, ssh
