### ISSUE TITLE
Can't open VS Code Server for WSL; closed unexpectedly

### ISSUE THREAD

**Issue by danylchuk** [microsoft/vscode-remote-release#2273] opened 2020-01-31 12:37 UTC
Logs from terminal:
[2020-01-31 12:30:33.533] Resolving wsl+ubuntu-18.04, resolveAttempt: 1
[2020-01-31 12:30:33.611] Starting VS Code Server inside WSL (Ubuntu-18.04)
[2020-01-31 12:30:33.611] Extension version: 0.41.7, Windows build: 19555. Multi distro support: available. WSL path support: enabled
[2020-01-31 12:30:33.766] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-18.04 -e sh -c "[ -d ~/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-01-31 12:30:43.882] Unable to detect if server is already installed: Error: Command failed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-18.04 -e sh -c "[ -d ~/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-01-31 12:30:43.882] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2020-01-31 12:30:43.882] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu-18.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 26076a4de974ead31f97692a0d32f90d735645c0 stable .vscode-server 0  ' in c:\Users\ME\.vscode\extensions\ms-vscode-remote.remote-wsl-0.41.7
[2020-01-31 12:30:53.995] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[2020-01-31 12:30:53.996] VS Code Server for WSL closed unexpectedly.
[2020-01-31 12:30:53.996] For help with startup problems, go to
[2020-01-31 12:30:53.996] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips

**Comment by AdamVig** [comment] 2020-01-31 22:01
Duplicate of #2272.

**Closed** 2020-02-01 01:01 UTC
