### ISSUE TITLE
Remote Development / SSH - Not detecting venv?

### ISSUE THREAD

**Issue by flz** [microsoft/vscode-remote-release#353] opened 2019-05-17 16:43 UTC
Issue Type: <b>Bug</b>

I'm connected to a server via SSH and despite having a "venv" directory in my workspace, I can't pick it up in the Python Environment list.

Extension version: 0.14.0
VS Code version: Code - Insiders 1.34.20-insider (e83e24a0c9225becd7341e56952177a20d5d4629, 2019-05-15T18:03:46.296Z)
OS version: Darwin x64 18.5.0
Remote OS version: Linux x64 4.18.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 12, 7|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|-psn_0_2433618|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: hassio|
|OS|Linux x64 4.18.0-17-generic|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (1 x 3690)|
|Memory (System)|3.85GB (0.29GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment] 2019-05-20 07:57
Duplicate of #368

**Closed by egamma** 2019-05-20 07:57 UTC

**Comment by flz** [comment] 2019-05-25 04:56
I don't actually think this is the same issue.

The venv doesn't even appear in the list for me. #368 mentions that the venv is selected but not activated in the terminal.

**Comment by flz** [comment] 2019-05-25 05:11
Actually, please ignore. The venv in that directory was generated on a different machine. Generating a new (local) one works fine. I'm now facing the same issue as #368.
