### ISSUE TITLE
"execvp(3) failed: Permission denied" when launching a terminal

### ISSUE THREAD

**Issue by voidtrance** [microsoft/vscode-remote-release#5444] opened 2021-08-11 19:05 UTC
Issue Type: <b>Bug</b>

When attempting to launch a terminal while connected to a SSH remote host, I get the error "execvp(3) failed: Permission denied" and the terminal window immediately closes.

Steps to reproduce:
1. Open VS Code and connect to a remote host.
2. Attempt to open a terminal with Ctrl-`

The error happens whether a project folder is open or not. Closing the connection and reconnecting does not help.

Extension version: 0.65.7
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.13.8-200.fc34.x86_64
Restricted Mode: No
Remote OS version: Linux x64 5.8.18-100.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2282)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.34GB (0.24GB free)|
|Process Argv|--unity-launch --crash-reporter-id 35df2b9f-b579-4770-ac29-83524a8e1958|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|SSH: huayra|
|OS|Linux x64 5.8.18-100.fc31.x86_64|
|CPUs|Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz (12 x 1200)|
|Memory (System)|31.04GB (8.16GB free)|
|VM|0%|
</details>

**Comment by voidtrance** [comment] 2021-08-18 14:52
Using the guide from [https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch](https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch), I enabled tracing as per [https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging).

However, neither the 'Remove Extension Host' nor the 'Remove Extension Server' logs provided any actionable information as to why I am getting the permission error.

What I did notice is that the server log is saying that VSCode is trying to launch:
```
wget --version > /dev/null\nif [ $? -eq 0 ]\nthen\n\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata-Flavor:Google' -O - http://metadata.google.internal/computeMetadata/v1/instance/id\nelse\n\tcurl --version > /dev/null\n\tif [ $? -eq 0 ]\n\tthen\n\t\tcurl --connect-timeout 7 -s --header='Metadata-Flavor:Google' http://metadata.google.internal/computeMetadata/v1/instance/id\n\tfi\nfi\nexit 0
```

When I copy/paste that command into a terminal opened on the remote host and attempt to run it as:
```
sh -c "wget --version > /dev/null\nif [ $? -eq 0 ]\nthen\n\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata-Flavor:Google' -O - http://metadata.google.internal/computeMetadata/v1/instance/id\nelse\n\tcurl --version > /dev/null\n\tif [ $? -eq 0 ]\n\tthen\n\t\tcurl --connect-timeout 7 -s --header='Metadata-Flavor:Google' http://metadata.google.internal/computeMetadata/v1/instance/id\n\tfi\nfi\nexit 0"
```
I get `sh: /dev/nullnif: Permission denied`

**Comment by bamurtaugh** [comment] 2021-08-24 21:46
Closing as a dupe of https://github.com/microsoft/vscode/issues/124968

cc @Tyriar @meganrogge if you think this is a separate issue, please let me know!

**Closed by bamurtaugh** 2021-08-24 21:46 UTC
Labels: ssh
