### ISSUE TITLE
Fails to initialize when the SSH server account uses Fish shell

### ISSUE THREAD

**Issue by adam-erickson** [microsoft/vscode-remote-release#404] opened 2019-05-21 18:45 UTC
Visual Studio Code fails to connect to OpenSSH server when the server user account is set to Fish shell by default. Here is the output:

```
SSH Resolver called for "servername-remote+servername"
SSH Resolver called for host: servername
Setting up SSH remote "servername"
Using commit id "4ca38ce5584d7cd67b43522vx3322vxdj32rfscssef129628" and quality "insider" for server
Install and start server if needed
> fish: Expected a string, but instead found a redirection
> cat << 'EOF' > $INSTALL_SCRIPT
>      ^
"install" terminal command done
Received install output:      ^
Failed to parse remote port from server output:      ^
```

Please add a conditional statement to check for the shell using the `$SHELL` variable and select the install script based on the return value at the end of the path. For Fish shell and maybe others `$0` does not return information about the shell. The output of `$SHELL` should be something like `/bin/fish` or `/bin/bash`.

- VSCode Version: v1.3.5.0-insider
- Local OS Version: N/A
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. Remote SSH - Connect to Host...
2. Fail to connect
3. No profit

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by egamma** [comment] 2019-05-21 20:29
Duplicate of #33

**Closed by egamma** 2019-05-21 20:29 UTC
