### ISSUE TITLE
Sockets and RemoteCommand

### ISSUE THREAD

**Issue by NicolasGoeddel** [microsoft/vscode-remote-release#6711] opened 2022-05-12 08:08 UTC
Issue Type: <b>Bug</b>

Hi,

in my `.ssh/config` I got this Host:
```
Host dev-deploy
        User ngoeddel
        Hostname 10.99.99.10
        ForwardAgent yes
        Compression no
        RemoteCommand sudo su deployment
        RequestTTY force
```
I also set this option in the settings:
```json
"remote.SSH.remoteServerListenOnSocket": true
```
Now when I create a remote connection it seems that the `RemoteCommand` in `.ssh/config` is ignored because VSCode now runs as user `ngoeddel` and also opens a socket with that same user. I am not able to do anything as user `deployment` because of I/O errors.

Extension version: 0.80.0
VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:39:22.915Z)
OS version: Linux x64 5.13.0-39-generic snap
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-348.20.1.el8_5.x86_64
Remote OS version: Linux x64 5.4.0-77-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 3|
|Memory (System)|46.72GB (12.54GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id b2593f3e-9557-49e2-9af2-00d7326bd657|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: imonepu6-mgmt|
|OS|Linux x64 4.18.0-348.20.1.el8_5.x86_64|
|CPUs|AMD Opteron 23xx (Gen 3 Class Opteron) (4 x 2493)|
|Memory (System)|3.65GB (0.87GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev-deploy|
|OS|Linux x64 5.4.0-77-generic|
|CPUs|Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz (2 x 2992)|
|Memory (System)|1.94GB (0.13GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by tanhakabir** [comment] 2022-05-12 15:12
Yeah unfortunately this is the case for now. I have on my backlog to investigate this #6086.

Closing as a duplicate of #6086

**Closed by tanhakabir** 2022-05-12 15:12 UTC
Labels: ssh
