### ISSUE TITLE
Can someone tell me what the situation is？

### ISSUE THREAD

**Issue by XKMar** [microsoft/vscode-remote-release#2540] opened 2020-03-13 08:01 UTC
unable to connect to remote after update to version 0.50.0, if version downgraded to 0.49.0 it works，but, the SSH TARGETS arise a lot of numbers which cannot be remove or open.
![image](https://user-images.githubusercontent.com/22143746/76601140-43a01400-6543-11ea-9d23-0b3578a9b47e.png)

Best regards

**Comment by roblourens** [comment] 2020-08-03 04:06
Sorry for the slow response. I'm not sure what happened here, but if you remove those entries and connect to a new remote, do you see new history entries showing up? Or are they all numbers?

**Comment by roblourens** [comment] 2020-10-28 17:21
Closing as duplicate of https://github.com/microsoft/vscode-remote-release/issues/2529

**Closed by roblourens** 2020-10-28 17:21 UTC
Labels: bug, ssh
