### ISSUE TITLE
SSH: built-in languages disabled

### ISSUE THREAD

**Issue by daiyam** [microsoft/vscode-remote-release#5856] opened 2021-11-10 16:14 UTC
Hi,

Some built-in languages are disabled with the message `This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in 'SSH: arch' to enable.`

![Screen Shot 2021-11-10 at 5 05 07 PM](https://user-images.githubusercontent.com/587742/141148924-b94737d0-ef8e-4631-95c9-b2663e72b625.png)

I've tried with previous versions of VSCode and Remote SSH and deleting `.vscode-server`. I tried to add the extensions into `remote.SSH.defaultExtensions`. I can't figure out where the problem is happening.

- VSCode Version: 1.62.1
- Local OS Version: MacOS
- Remote OS Version: Arch Linux
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by tanhakabir** [comment] 2021-11-10 18:20
Hmm that's strange. @roblourens or @sandy081 do you have an idea why language extensions would be disabled?

@daiyam could you also post here the log you see on the Remote-SSH output channel?

**Comment by daiyam** [comment] 2021-11-10 18:53
Here log from the output of `Remote - SSH`: [client.log](https://github.com/microsoft/vscode-remote-release/files/7515110/client.log)
The log from the log file in `.vscode-server`: [server.log](https://github.com/microsoft/vscode-remote-release/files/7515115/server.log)

Here my config:
```
"remote.SSH.remotePlatform": {
  "arch": "linux"
},
```

The error in `server.log` seems to be related to my shell environment which is `fish` but it did work before.

This issue has been an on and off with each updates

**Comment by tanhakabir** [comment] 2021-11-10 18:56
Hmm `resolving shell environment failed Error: Unable to resolve your shell environment:` could be fixed by https://github.com/microsoft/vscode/issues/136791

Would you be able to try connecting with VS Code Insiders?

**Comment by daiyam** [comment] 2021-11-10 20:28
`v1.63.0-insider`: isn't working
`v1.60.0-insider`: is working

both with `remote-ssh-v0.66.0`

**Comment by sandy081** [comment] 2021-11-11 13:30
I cant repro it and they shall be running on the local side and not on remote side. Can you please try to repro it by running vscode on a fresh user data directory?

**Comment by pelayog** [comment] 2021-11-13 16:07
I didn't find this issue and I've opened one related at [microsoft/vscode:#137117](https://github.com/microsoft/vscode/issues/137117) with some extra info (and some failed attempts to fix it)

I can't reproduce it running a new portable instance of vscode, which is the workaround I'm using to work just now.

**Comment by daiyam** [comment] 2021-11-13 16:42
@pelayog Thanks for confirming that I'm not the only one having this issue :wink:

**Comment by daiyam** [comment] 2021-11-13 19:11
After a long investigation, I found out that the issue is due to the extension `Control Snippets` and when any snippets have been disabled (with the UI `> Control Snippets`).
With `VSCode v1.60.2`, no issue.
With `v1.61.2`, `v1.62.0` and `v1.62.2`, the issue is there.

@pelayog Are you using that extension?

**Comment by pelayog** [comment] 2021-11-15 08:03
@daiyam Mm, nope, not that extension. But I do have PHP Language Features extension disabled -in order to use intelephense properly.

At the end, I guess is, at least, related: disabling built-in features throught that extension or manually.

**Comment by tanhakabir** [comment] 2022-08-16 23:32
There hasn't been any activity on this issue for awhile and it there doesn't seem to be a consistent repro. @pelayog  or @daiyam please let me know if you're still seeing this issue in a new issue and for now I'll close this one out

**Closed by tanhakabir** 2022-08-16 23:32 UTC
Labels: ssh, info-needed
