### ISSUE TITLE
Remote Containers error with Azure DevOps repos

### ISSUE THREAD

**Issue by yalaas** [microsoft/vscode-remote-release#3031] opened 2020-05-21 20:36 UTC
- VSCode Version: 1.45.1
- Local OS Version: Windows 10
- Remote OS Version: Linux (Ubuntu 16.04)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Start VS Code and run "Remote-Containers: Open Repository in Container" from the Command Palette
2. Enter an Azure DevOps repo full remote URL {https://{account}.visualstudio.com/{project name}/_git/{repo name}}
3. Select the volume for the cloned repo
4. Enter the target folder name. Notice that the default target folder name is "_git" not the repo name as you usaully is when using github repositories
5.  Observe the error while building the dev container:
**
[6526 ms] Start: Run in container: cat /workspaces/test/.devcontainer/devcontainer.json 2>/dev/null
[6531 ms] Start: Run in container: test -f /workspaces/test/.devcontainer/Dockerfile
[6533 ms] 
[6533 ms] 
[6533 ms] Start: Run: docker exec 5f1fe6579c661bcbd5f67f012f36be7f71bded45238f9524ebc309992f563134 docker build -f /workspaces/test/.devcontainer/Dockerfile -t vsc-_git-61b905e1c8190687b11694a7615578df /workspaces/test/.devcontainer
invalid argument "vsc-_git-61b905e1c8190687b11694a7615578df" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
[7183 ms] Start: Run: docker rm -f 5f1fe6579c661bcbd5f67f012f36be7f71bded45238f9524ebc309992f563134
[7185 ms] Command failed: docker exec 5f1fe6579c661bcbd5f67f012f36be7f71bded45238f9524ebc309992f563134 docker build -f /workspaces/test/.devcontainer/Dockerfile -t vsc-_git-61b905e1c8190687b11694a7615578df /workspaces/test/.devcontainer
[7940 ms] Remote-Containers server terminated (code: 137, signal: null).
**
 
Docker is complaining about the tag passed to the build command:
"-t vsc-_git-61b905e1c8190687b11694a7615578df"

It seems the extension is parsing "_git" as the repo name and that might be the issue. 

Here is the used URL format for reference:
https://{account}.visualstudio.com/{account name}/_git/{repo name}

**Comment by egamma** [comment] 2020-06-30 11:00
The extension currently does not understand Azure DevOps and parses it incorrectly, that results in an incorrect label, that makes the build step fail. The repository is properly cloned.

**Comment by ntziolis** [comment] 2020-07-11 14:12
Any update? This our key use case and we are blocked blocked from using this functionality at all at this time

**Comment by interrobrian** [comment] 2020-09-22 15:42
Has anybody managed to find a workaround for this?

**Comment by ntziolis** [comment] 2020-09-27 17:04
@egamma Can you link to the code / repo that handles parsing the git urls and I'm happy to take a stab at making this work.

**Comment by egamma** [comment] 2020-09-29 06:33
@ntziolis thanks for offering help but pls see https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source.

**Comment by ntziolis** [comment] 2020-09-29 10:28
@egamma Its a shame, anyone in particular we can annoy to change this at least for portions of the code. Given MS is asking devs to rely on these remote tool + MS hard earn new cred with os devs it seems like this is a step in the wrong direction.

**Comment by ntziolis** [comment] 2021-03-12 04:58
Any update on this and if this is going to land in March as currently planned?

This is getting rather critical for us. With Visual Code Spaces retired and github code spaces still in closed beta not being able to easily spin up a container with source access on a remote host is a key feature missing. In fact we are currently trialing Apache Che and are contemplating move away from vscode because of it since it doesn't fit our all dev happens in dev containers credo anymore. This would be a great shame since we really really loved using vscode.

**Comment by egamma** [comment] 2021-03-21 17:49
Closing as a duplicate of #2620 that has been fixed.

**Closed by egamma** 2021-03-21 17:49 UTC
Labels: bug, containers, plan-review
