### ISSUE TITLE
webview.html not work in new version in remote-ssh mode

### ISSUE THREAD

**Issue by TianQinS2** [microsoft/vscode-remote-release#8254] opened 2023-03-24 03:19 UTC
```javascript
workPanel = vscode.window.createWebviewPanel(
            'workNormal',
            'work',
            vscode.ViewColumn.Beside,
            {
                enableScripts: true, 
                retainContextWhenHidden: true,
                localResourceRoots: [context.extensionUri]
            }
        );

        workPanel.webview.html = `<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="Content-Security-Policy" content="default-src 'none';">
            <title>Cat Coding</title>
        </head>
        <body>
            <img src="https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif" width="300" />
        </body>
        </html>`;
        console.log(workPanel.webview.html);
 ```
> 1.  workPanel.webview.html =''' is right in local mode, but not work in remote-ssh mode.
> 2. This problem occurred in recent versions, previous version is normal.
> 3. It likes an empty webview, not load html content, and small probability normal.

**Comment by TianQinS2** [comment] 2023-03-24 03:25
NetWork
Right：
index.html!id=xxxx
fake.html?id=xxxx
// js css

Now:
Only
index.html!id=xxxx

**Comment by TianQinS2** [comment] 2023-03-24 03:28
Basically unable to load, occasionally normal in remote-ssh mode.
Always normal in local mode.

**Comment by TianQinS2** [comment] 2023-03-24 10:12
It sames all extension use webview have the same problem.
But there are no problems on some computers.

**Comment by eleanorjboyd** [comment] 2023-03-24 19:33
Hello! Could you please send your remote-ssh logs? You can find the logs by going to `view` in the menu bar, then selecting `output`, and finally once the bottom window pops up select  `remote-ssh` from the dropdown on the right. Thanks!

Additionally can you clarify which versions of both remote-ssh and vscode it used to work on? Finally when you say "occasionally" that it doesn't work on normal what do you mean by normal?

**Comment by TianQinS2** [comment] 2023-03-27 03:15
Remote-ssh logs is normal, and same as the old version.
```txt
[11:10:51.256] Remote server is listening on 43491
[11:10:51.256] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":43491},"osReleaseId":"debian","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-oCE6bbjMiV/agent.17194","display":"","tmpDir":"/run/user/3104","platform":"linux","connectionToken":"a11aaa11-111a-11aa-11aa-a11111a1a111"},"serverStartTime":1305,"installUnpackCode":""}
[11:10:51.260] Starting forwarding server. localPort 52127 -> socksPort 52124 -> remotePort 43491
[11:10:51.261] Forwarding server listening on 52127
[11:10:51.262] Waiting for ssh tunnel to be ready
[11:10:51.263] Tunneled 43491 to local port 52127
[11:10:51.264] Resolved "ssh-remote+测试" to "127.0.0.1:52127"
[11:10:51.265] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-oCE6bbjMiV/agent.17194" "/run/user/3104/vscode-ssh-auth-sock-106310547"
[11:10:51.265] Using cwd: vscode-remote://ssh-remote%2B%E6%B5%8B%E8%AF%95/
[11:10:51.265] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/3104/vscode-ssh-auth-sock-106310547"}
[11:10:51.266] [Forwarding server 52127] Got connection 0
[11:10:51.275] ------




[11:10:51.276] > 
[11:10:51.293] [Forwarding server 52127] Got connection 1
[11:10:51.866] [Forwarding server 52127] Got connection 2
[11:10:55.055] [Forwarding server 52127] Got connection 3
[11:10:56.689] "Update SSH_AUTH_SOCK" terminal command done
```

**Comment by TianQinS2** [comment] 2023-03-27 03:22
Webview is create success, but workPanel.webview.html seams fail.
I tried many extensions with webview in many computers, the results are the same.

**Comment by mjbvz** [comment] 2023-03-27 16:08
Duplicate of https://github.com/microsoft/vscode/issues/178191

**Closed by mjbvz** 2023-03-27 16:08 UTC
Labels: ssh, info-needed
