### ISSUE TITLE
Allow for Default Environment Variable Value in `${localEnv:...}` and `${containerEnv:...}`

### ISSUE THREAD

**Issue by celestialorb** [microsoft/vscode-remote-release#1108] opened 2019-08-06 11:25 UTC
I wasn't able to find anything suggesting this was possible, nor did it seem to work when I tried it myself.

I'd like to see the ability to specify a default value for local environment variable values in the `runArgs` property of the `devcontainer.json` file. I'm trying to use the value of a local env var to determine the filesystem source of a bind mount into the remote environment container, or default to a named volume if the variable does not exist.

I propose the ability to use the standard way of defining a default value for a shell/environment variable, with the `<variable-name>:-<default-value>`. I have tried this and it does not seem to work. An example is shown below for the `runArgs` property of the `devcontainer.json` file.

```json
"runArgs": [
    "-v", "${env:DOES_NOT_EXIST:-name-of-volume-or-default-path}:/path/in/container/filesystem",
],
```

**Comment by MShekow** [comment] 2021-11-09 16:20
We also would need this feature. What exactly is meant by "out of scope"?

**Comment by chrmarti** [comment] 2021-11-10 08:32
"out of scope" because we never got to consider doing this. Reopening to reconsider.

**Comment by MShekow** [comment] 2021-11-10 09:58
Thank you for reopening this ticket. Since the issue is quite old, having just consulted the [docs](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_variables-in-devcontainerjson), I suppose it makes sense to have this default-value mechanism implemented for `localEnv` and `containerEnv`, e.g. to be able to define something like `${localEnv:DOES_NOT_EXIST:-some default value}`.

**Comment by firdacz** [comment] 2022-05-03 18:34
Not just `runArgs` but everywhere - e.g. in `launch.json`:
```
"serverpath": "${env:jlink:"c:\Program Files (x86)\SEGGER\JLink_V..."}/JLinkGDBServerCL.exe",
"armToolchainPath": "${env:gnuarm:"c:\devel\gnuarm"}/bin",
```
...would probably need to be quoted (if containing `:` ...for future extensions, e.g. list of alternatives - checked for *exists*? I myself have that toolchain on either `D:` or `E:`, using company/home PC)

**Comment by botspaces** [comment] 2022-05-13 22:07
This issue has been migrated to devcontainers/spec#29

**Closed** 2022-05-13 22:08 UTC
Labels: containers, feature-request, spec-transfer
