### ISSUE TITLE
Remote-SSH spawns window

### ISSUE THREAD

**Issue by sleighsoft** [microsoft/vscode-remote-release#325] opened 2019-05-14 14:23 UTC
Version: 1.34.20-insider (user setup)
Commit: 57b550c559b945eb9d871dbf2b2e4cb9e31e2551
Date: 2019-05-10T17:36:45.765Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

I am currenltly trying out the Remote SSH extension on the insider build.
One thing I noticed when establishing a connection to a server is that VSCode spawn a new external ssh window which is completely black and empty.
![grafik](https://user-images.githubusercontent.com/9438971/57705568-7a2baa80-7664-11e9-8e0f-e93cd74bb693.png)

Closing it results in a reconnect after 5 seconds and a new window being spawned.
Closing VSCode does not close that window.

**Comment by lars18th** [comment] 2019-05-15 06:56
Hi,

I feel this is the same ussue as #230.

**Comment by sleighsoft** [comment] 2019-05-15 10:33
Nothing fancy

Host name
    HostName <IP>
    User <user>
    Port 22
    IdentityFile <path_to_priv_key>

@lars18th Looks related.

**Comment by sleighsoft** [comment] 2019-07-03 08:24
Switched to Windows 10 Native OpenSSH from git-with-openssh which can be installed from "additional packages" and now no new windows open up.

**Comment by lars18th** [comment] 2019-07-03 08:35
> Switched to Windows 10 Native OpenSSH from git-with-openssh which can be installed from "additional packages" and now no new windows open up.

I use the native Win32 OpenSSH too, but the PowerShell (official) version in a Windows 7 machine.
https://github.com/PowerShell/openssh-portable

I feel your problem is related to the `git-with-openssh` version that you use.
In this case I suggest to close this issue, as the problem isn't related to the Remote-SSH extension.

**Closed** 2019-07-03 08:47 UTC
