### ISSUE TITLE
node process is running at full CPU

### ISSUE THREAD

**Issue by JakobRohrhirsch** [microsoft/vscode-remote-release#3398] opened 2020-07-20 15:56 UTC
Issue Type: <b>Bug</b>

Whenever I connect to my Ubuntu-20.04 WSL a process called "node" from .vscode-server/bin/somealphanumericcode is using one CPU core at 100%.

Extension version: 0.44.4
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.84GB (8.35GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment] 2020-09-09 20:49
duplicate of https://github.com/microsoft/vscode-remote-release/issues/3244

**Closed by aeschli** 2020-09-09 20:49 UTC
Labels: bug, wsl
