### ISSUE TITLE
Remote developing

### ISSUE THREAD

**Issue by yiwc** [microsoft/vscode-remote-release#6370] opened 2022-02-20 11:16 UTC
using the newest vscode (macos,Version: 1.64.2 (Universal)), would fail in using ssh remote to a new remote host.

the error is ,"code not found". I guess sth is wrong with the server side setup.

<img width="301" alt="Screenshot 2022-02-20 at 11 04 24 PM" src="https://user-images.githubusercontent.com/44794635/154849092-ef4f4b82-6d78-45e2-99b6-8179e83e9cb2.png">

## tempo solution

after uninstalling the newest vscode, and installing the previous version (Version: 1.63.2 (Universal)) of vscode, it would works fine.  (should do `rm -r ./vscode-server`)
<img width="308" alt="Screenshot 2022-02-20 at 11 09 53 PM" src="https://user-images.githubusercontent.com/44794635/154849358-ae2eda7b-7dd2-45ab-ac0a-32e9922c9cda.png">

**Comment by tanhakabir** [comment] 2022-02-22 16:07
This is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6289

**Closed by tanhakabir** 2022-02-22 16:07 UTC
Labels: triage-needed
