### ISSUE TITLE
Set up `code` command line usage in external terminal

### ISSUE THREAD

**Issue by mprobst** [microsoft/vscode-remote-release#3983] opened 2020-11-09 09:23 UTC
Using VS Code in the integrated terminal, e.g. to `code some/local/file` or use `code -w` is very nice.

I prefer using a native terminal emulator on my local system though (iTerm, with support for tmux).

I understand I can get `code` etc work in the command line by setting up `VSCODE_IPC_HOOK_CLI` and  and making sure I run something like `$HOME/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/bin/code`.  I can set that up by first opening the built in terminal, then copying those environment variables into my external terminal.

That's very inconvenient though. Maybe there could be a way to set this up in a remote terminal that's more straight forward?

**Comment by rhyek** [comment] 2020-12-07 03:35
I'm setting up a new dev environment using a mini-pc as my permanent host for all programming-related workloads and am going to be remote-sshing in for coding every time, but for new projects (short or long-lived) my workflow starts off with me opening up an external terminal (iTerm2), doing the initial project setup there (`npm init -y`, etc) and loading up a vscode instance using `code .` in that same terminal as my final step before I start coding.

iTerm2 allows setting custom commands for starting a new terminal session per profile configuration. Maybe have a `--remote` option so that you can ssh into the remote host via vscode and that would set everything up. For example, I could have an iTerm2 profile called `minipc-dev` and its startup command could be something like `code --remote user@host` and that would either use `user@host` if previously setup within vscode or run an initial process similar to `add new host`.

**Comment by rhyek** [comment] 2020-12-12 17:48
For my particular use case (two trusted hosts over a local network) I set up this bash function in my .zshrc on my mini-pc that does what I need:
```bash
function vscode {
  ssh macbook "/usr/local/bin/code --remote ssh-remote+minipc $(readlink -m $1)"
}
```
So from a terminal on my macbook I can run for example `vscode /path/to/folder_or_file` in my remote server (minipc) over ssh and it will itself ssh back into my macbook and run `code --remote` (mentioned [here](https://github.com/microsoft/vscode-remote-release/issues/656#issuecomment-584209378)) which will open up a file or folder back in my minipc on a local (macbook) vscode window.

It works perfectly. It can be used in an external terminal or even inside an integrated vscode terminal and it works the same as using `code` in the latter case with a very small delay (< 1s).

This is not a replacement for what is being asked for in this issue, but can serve as a workaround for some.

**Comment by aeschli** [comment] 2022-12-15 15:19
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2763

**Closed by aeschli** 2022-12-15 15:19 UTC
