### ISSUE TITLE
Other git clients experience "Failed to rename lock file..." when vscode is open with this plugin.

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/vscode-remote-release#3046] opened 2020-05-26 14:46 UTC
- VSCode Version: 1.45.1
- Local OS Version: Windows 10 2004
- Remote OS Version: Ubuntu 18.04.4 LTS (Bionic Beaver)
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Clone a repo on windows
2. Open a wsl prompt in that folder (`mnt/.../...`)
3. launch code using `code .`
4. Try a git operation in Tower or GitKraken and get errors all around:

![image](https://user-images.githubusercontent.com/4173387/82914509-e297b200-9f6f-11ea-8b99-8295a80431b9.png)
![image](https://user-images.githubusercontent.com/4173387/82914566-f7744580-9f6f-11ea-80d1-92055e9f6263.png)

Close vscode and all the issues go away.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment] 2020-06-03 15:10
duplicate of https://github.com/microsoft/vscode-remote-release/issues/903

**Closed by aeschli** 2020-06-03 15:10 UTC
Labels: wsl
