### ISSUE TITLE
ssh connect a center management node then ssh connect the worker node that I need 

### ISSUE THREAD

**Issue by zhan0903** [microsoft/vscode-remote-release#159] opened 2019-05-06 00:33 UTC
- VSCode Version: code-insiders 1.34
- Local OS Version: MacOs
- Remote OS Version: center management node Linux Redhat7.5; the worker node I need Redhat7.3
- Remote Extension/Connection Type: SSH/Docker/WSL: SSH

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

Usually I firstly ssh the center management node then ssh one worker node. When I try VS code remote SSH to connect the worker node, VS Code gets stuck in the step of the "Opening Remote". No error messages. I can use VS Code remote connect the center management node and I can use my local terminal to ssh the worker node.

**Comment by xuexcy** [comment] 2019-05-13 11:34
I have the same problem.  A(local machine installed vscode) -> B(management node for security ) -> C(remote node for work),  I need ssh from A to B by password, and then ssh from B to C(or other remote node) by another password.  I can run a shell script in terminal to connect to C by typing password twice. 
    How can I use this shell script in vscode？ How can people customized their own ssh connection steps.

**Comment by roblourens** [comment] 2019-05-19 21:16
Can you explain what you mean by "center management node"?

Can you share the log from the "Remote - SSH" output channel?

**Comment by zhan0903** [comment] 2019-05-20 00:11
> Can you explain what you mean by "center management node"?
> 
> Can you share the log from the "Remote - SSH" output channel?

"Center management node"  is kinda of management node, which maintains a list of available nodes and the user can choose which one to ssh. The "Remote-SSH" output log no error message, the vs code just gets stuck in the "opening remote" process(the previous  steps such as "downloading with wget initializing vs code server" seems to work fine, no error messages.) 
![1A7324E6-DDBD-4201-B7F0-994EA8E9D974](https://user-images.githubusercontent.com/4834562/57990196-a2ddf500-7ae7-11e9-9d10-560eae3c882c.png)

**Comment by roblourens** [comment] 2019-05-20 01:55
That's the terminal, can you click the Output tab and select "Remote - SSH" in the dropdown and share that log?

**Comment by zhan0903** [comment] 2019-05-20 05:44
> That's the terminal, can you click the Output tab and select "Remote - SSH" in the dropdown and share that log?

Thanks. Below is the log output:
```
SSH Resolver called for "ssh-remote+atlas1"
SSH Resolver called for host: atlas1
Setting up SSH remote "atlas1"
Using commit id "6ac87465f297a9068bf767f45d6f372fc5697de9" and quality "insider" for server
Install and start server if needed
> bash: no job control in this shell
> Found existing installation...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> 0fde86d9-029a-4198-97d4-d4f8419e29ba==36987==
"install" terminal command done
Received install output: 0fde86d9-029a-4198-97d4-d4f8419e29ba==36987==
Server is listening on port 36987
Spawning tunnel with: ssh  atlas1 -L localhost:11887:localhost:36987 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 11887 and remote port 36987
Waiting for ssh tunnel to be ready
Tunneling remote port 36987 to local port 11887
Resolving "ssh-remote+atlas1" to "localhost:11887", attempt: 1
> channel 3: open failed: administratively prohibited: open failed
> channel 4: open failed: administratively prohibited: open failed
> channel 5: open failed: administratively prohibited: open failed
"SSH Tunnel" terminal command done
SSH tunnel command completed unexpectedly
```

**Comment by roblourens** [comment] 2019-05-20 17:55
> channel 3: open failed: administratively prohibited: open failed

It looks like TCP forwarding may be disabled on the SSH remote, is that possible? This is controlled by the `AllowTcpForwarding` option on the server.

**Comment by zhan0903** [comment] 2019-05-21 06:50
> > channel 3: open failed: administratively prohibited: open failed
> 
> It looks like TCP forwarding may be disabled on the SSH remote, is that possible? This is controlled by the `AllowTcpForwarding` option on the server.

I tried to check the `AllowTcpForwarding` option in file ` /etc/ssh/sshd_config` on the server, but unfortunately, I am not a root user and don't have the permission to open it.

**Comment by roblourens** [comment] 2019-05-21 16:51
There was another issue reported with a setup where someone is assigned to a random node each time they start a new ssh connection. This is an issue for us because it takes multiple ssh connections to set up and connect to the vscode server. Is that the case for you? I didn't understand at first but you might be describing the same.

https://github.com/microsoft/vscode-remote-release/issues/297

**Comment by zhan0903** [comment] 2019-05-22 07:07
> There was another issue reported with a setup where someone is assigned to a random node each time they start a new ssh connection. This is an issue for us because it takes multiple ssh connections to set up and connect to the vscode server. Is that the case for you? I didn't understand at first but you might be describing the same.
> 
> #297

Thanks. In my case, I use the node's IP for ssh connection, which is fixed, so it is not random. The center node(maintain the available worker nodes' name) and the worker node have different IP addresses.

**Comment by roblourens** [comment] 2019-05-22 18:01
So you connect directly to a worker node's IP address? I don't see how the center node is involved then.

If you mean that you connect to the center node's IP address then are you still being assigned a random worker node?

**Comment by zhan0903** [comment] 2019-05-23 10:34
> So you connect directly to a worker node's IP address? I don't see how the center node is involved then.
> 
> If you mean that you connect to the center node's IP address then are you still being assigned a random worker node?

I mean I can ssh the worker directly by its IP address or by its name(in most cases, by its names). Usually, users firstly ssh the center node and then choose one available worker node(not random, if too many users on that worker node then it can't be connected, we need to select another one) to connect(ssh).

**Comment by roblourens** [comment] 2019-05-23 18:44
Ok it sounds like this issue a dupe of #297 then. As a workaround, you might try setting a worker node's IP directly in your ssh config.

**Closed by roblourens** 2019-05-23 18:44 UTC
Labels: needs-more-info, ssh

**Comment by zhan0903** [comment] 2019-05-23 23:20
> Ok it sounds like this issue a dupe of #297 then. As a workaround, you might try setting a worker node's IP directly in your ssh config.

Thanks.  I can ssh the worker directly by its IP address in my Macbook terminal, but I can't set it up through VS remote(VS remote get stuck) even though I use the IP address too.
