### ISSUE TITLE
Allow tasks to run on local integrated terminal in dev container vs code instance 

### ISSUE THREAD

**Issue by g-kartik** [microsoft/vscode-remote-release#7942] opened 2023-02-01 05:57 UTC
When trying to run a task in a dev container instance of vs code, there is no way to configure it to run on **local integrated terminal** instead of the container's own shell.

This feature would be very helpful to create tasks which require access to the host machine's packages.

In my case, I am trying to run `docker attach` command to attach the output of the container to the terminal to see it's real time logs. But it is trying to find docker command inside the container, so it fails.

In `runOptions.runOn` we should have option for `IntegratedLocalTerminal`

**Comment by chrmarti** [comment] 2023-02-02 08:35
You can get access to the host Docker daemon from within the container by adding the following to your `devcontainer.json`:
```json
	"features": {
		"ghcr.io/devcontainers/features/docker-outside-of-docker:1": {}
	}
```

This will install the Docker CLI in the dev container and mount the Docker daemon socket into the container. You will need to rebuild the dev container after adding this.

Does that work for you?

**Comment by chrmarti** [comment] 2023-02-02 14:20
Not sure, @alexr00 ?

Alternatively you could install the Docker CLI into the container and mount the local Docker socket when you create the container to get access to the Docker daemon form within the container. (That's what the `docker-outside-of-docker` feature does.)

**Comment by alexr00** [comment] 2023-02-02 15:10
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/168

**Closed by alexr00** 2023-02-02 15:10 UTC
Labels: containers, info-needed
