### ISSUE TITLE
Reopen in container does not work if the `.devcontainer` folder is hidden

### ISSUE THREAD

**Issue by mrexodia** [microsoft/vscode-remote-release#9436] opened 2024-01-25 11:18 UTC
- VSCode Version: 1.85.2
- Local OS Version: Sonoma 14.2.1 (23C71)
- Remote OS Version: N/A
- Remote Extension/Connection Type: Containers

- Logs: N/A

Steps to Reproduce:

1. Create a folder with a devcontainer configured in it
2. Add the following to `.vscode/settings.json`:

```
 "files.exclude": {
        "**/.devcontainer": true,
```

3. Trigger the 'reopen in container' action from the command palette, it will show this message:

> Dev Container configuration '.devcontainer/devcontainer.json' file already exists.

The expected behavior is to reopen the folder in the container.

My use case for hiding files is that I am doing a workshop and I want people to only see relevant folders.

**Comment by lnay** [comment] 2024-02-01 16:07
+1, I accidentally created a duplicate of this earlier.

Here's my essay about why this is an issue:

It's possible that the current behaviour is technically to spec, since the description for "files.exclude" says:

*"Configure [glob patterns](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) for excluding files and folders. For example, the File Explorer decides which files and folders to show or hide based on this setting. [...]"*

but it's incredibly non-obvious that "excluding" here means affecting dev container builds too.

Given the many other issues posted with this pop-up message but with different causes, this is an incredibly frustrating to come across.

Anecdotally, I have had trouble convincing a different project author to remove this particular setting because they were insistent that it was "purely cosmetic".

**Comment by mrexodia** [comment] 2024-02-01 17:40
Yeah, as stated my use case is a workshop where it’s confusing for beginners to see all the dotfiles and folders necessary to set up their environment…

**Comment by chrmarti** [comment] 2024-12-13 11:40
This appears to work now.

**Closed by chrmarti** 2024-12-13 11:40 UTC
Labels: containers
