### ISSUE TITLE
vscode+wsl+oraclelinux "No shell environment set or found for current distro"

### ISSUE THREAD

**Issue by osde8info** [microsoft/vscode-remote-release#7768] opened 2022-12-24 22:08 UTC
VSCODE
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

WSL
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2364

ORACLE LINUX
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: OracleServer
Description:    Oracle Linux Server release 8.7
Release:        8.7
Codename:       n/a

- Logs:
[2022-12-24 21:51:08.349] No shell environment set or found for current distro.
[2022-12-24 21:51:09.253] WSL Daemon exited with code 0
[2022-12-24 21:51:09.253] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips

Steps to Reproduce:

1. open vscode
2. connect to wsl (oracle 8)
3. clone a repo from github
4. open folder
5. CRASHES with "No shell environment set or found for current distro."

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No/DontKnow

Workaround 
run terminal first 
open wsl tab 
run $ code . 
then click vscode clone

**Comment by osde8info** [comment] 2022-12-24 22:15
but then get these errors when using workaround

```
bash: which: line 1: syntax error: unexpected end of file
bash: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
```

**Comment by osde8info** [comment] 2022-12-24 22:16
and now the SSH port mapping tab has disappeared :(

**Comment by aeschli** [comment] 2024-10-30 15:44
Duplicate of https://github.com/microsoft/vscode/issues/163564

**Closed by aeschli** 2024-10-30 15:44 UTC
Labels: wsl
