### ISSUE TITLE
WSL-extension causes high cpu load?

### ISSUE THREAD

**Issue by Abeautifulsnow** [microsoft/vscode-remote-release#4892] opened 2021-04-16 02:52 UTC
* Issue Type: Performance

* Extension Name: remote-wsl

* Extension Version: 0.54.6

* OS Version: win10

* CPU Info: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)

* VS Code version: 1.55.2

> Details

When I connect ubuntu system through remote-wsl extension in vscode, the  `node` process loaded cpu source very high(about 30% occupied). This has affected my experence when I code the project and slow down the system...

**Comment by bamurtaugh** [comment] 2021-04-19 23:08
Hi @Abeautifulsnow - I see the title of your issue and the starting sentence mentions Remote-WSL, but the listed extension name is Remote-SSH. Are you experiencing this slowdown with Remote-SSH or Remote-WSL (based on the extension version number listed, it seems like it would be Remote-SSH)? 

If this is for Remote-SSH, seems like possible dupe of https://github.com/microsoft/vscode-remote-release/issues/4887.

**Comment by Abeautifulsnow** [comment] 2021-04-20 06:52
> Hi @Abeautifulsnow - I see the title of your issue and the starting sentence mentions Remote-WSL, but the listed extension name is Remote-SSH. Are you experiencing this slowdown with Remote-SSH or Remote-WSL (based on the extension version number listed, it seems like it would be Remote-SSH)?
> 
> If this is for Remote-SSH, seems like possible dupe of #4887.

Sorry, my bad...😅Actually, I'm now experiencing the slowdown problem with Remote-WSL(I can't solve this problem), and the high cpu loaded caused my PC's fans to spin wildly and make a lot of noise...😢 And it also affected the normal work of vscode such as: when I hover over a function name, the pop-up windows displays the info: `loading...`

**Comment by bamurtaugh** [comment] 2021-04-20 16:22
Thanks for the update. Are you using WSL1 or WSL2? And what distro? Has the slowdown just started (or after any updates/changes), or have you always experienced slow performance with Remote-WSL? 

There are a few related issues: https://github.com/microsoft/vscode-remote-release/issues/3244, https://github.com/microsoft/vscode-remote-release/issues/3171, https://github.com/microsoft/vscode-remote-release/issues/4649, https://github.com/microsoft/vscode-remote-release/issues/2919.

**Comment by aeschli** [comment] 2021-04-22 14:34
Can you install a tool like `top` and find out more which process is CPU load.

`top -ibcn1 -w512` will show you the active processes including the command line.

**Comment by Abeautifulsnow** [comment] 2021-04-23 07:36
@aeschli @bamurtaugh Thanks for your help and reply sincerely... 😓The problem seems to be gone now(I don't know how and why...). My PC was self-update automatically yesterday, and I stumbled on realizing that node process no longer consumes lots of cpu(So weird)...

> Update some infos...
1. I'm now using WSL1.
2. The sub-linux distro is ubuntu 18.04.
3. The case of slowdown just started some days ago(maybe half a month, not too long).

**Closed** 2021-04-25 07:14 UTC
Labels: needs-more-info, wsl
