### ISSUE TITLE
Remote-SSH extension v0.86.2022081615 breaks Remote-SSH

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-remote-release#7081] opened 2022-08-17 15:48 UTC
Type: <b>Bug</b>

Updating to version 2022081615 or 2022081715 breaks RemoteSSH, producing an error about how Remote-SSH extension failed to start because "Remote Explorer" extension is disabled.

Extension version: 0.85.2022081615
VS Code version: Code - Insiders 1.71.0-insider (dced70bbf36d3c53c08e791da1791ac7fc42519b, 2022-08-10T05:17:53.560Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.02GB free)|
|Process Argv|--crash-reporter-id 1ec82b55-0019-4497-ac0d-5453a1fdb689|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Ballz|
|OS|Linux x64 5.15.0-46-generic|
|CPUs|Intel(R) Xeon(R) Gold 6330N CPU @ 2.20GHz (56 x 2200)|
|Memory (System)|251.58GB (237.94GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by tanhakabir** [comment] 2022-08-17 15:55
Working on the fix right now!

**Comment by tanhakabir** [comment] 2022-08-17 16:11
This should be fixed now. Let me know if it's still broken for you!

**Comment by anatolyburakov** [comment] 2022-08-18 12:23
@tanhakabir  i do not see the new version released yet, so latest version of extension still doesn't work for me.

**Comment by tanhakabir** [comment] 2022-08-18 15:07
Hm just to verify which versions of the Remote SSH extension and Remote Explorer extension do you have installed?

**Comment by tanhakabir** [comment] 2022-08-18 16:10
Sorry about this could you try again with the SSH extension version `0.85.2022081816`?

**Comment by tanhakabir** [comment] 2022-08-18 16:12
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/7084

**Closed** 2022-08-18 16:15 UTC
Labels: ssh, info-needed

**Comment by anatolyburakov** [comment] 2022-08-19 09:24
@tanhakabir  yep, works now, thanks!
