### ISSUE TITLE
remote.SSH.allowLocalServerDownload not being resepcted in 0.47.2 or nightly 2019.12.12.12480

### ISSUE THREAD

**Issue by mbrownnycnyc** [microsoft/vscode-remote-release#2085] opened 2019-12-23 16:45 UTC
- VSCode Version: 1.40.2
- Local OS Version: Windows 10
- Remote OS Version: NAME="Red Hat Enterprise Linux Server";VERSION="7.7 (Maipo)"
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Try to connect to a machine without proxy credentials with the Remote-SSH extension.

Does this issue occur when you try this locally?: Not applicable.
Does this issue occur when you try this locally and all extensions are disabled?: Did not try.

I have a target server that I am connecting to with Remote-SSH.  Following `wget`'s attempt to download the VS Code server, I receive an error:

````
[15:27:02.729] remote-ssh@0.47.2
[15:27:02.729] win32 x64
[15:27:02.733] SSH Resolver called for "ssh-remote+xxxx", attempt 1
[15:27:02.733] SSH Resolver called for host: root@TARGETHOSTNAME
[15:27:02.733] Setting up SSH remote "TARGETHOSTNAME"
[15:27:02.835] Using commit id "f359dd69833dd8800b54d458f6d37ab7c78df520" and quality "stable" for server
[15:27:02.839] Testing ssh with ssh -V
[15:27:03.053] ssh exited with code: 0
[15:27:03.054] Got stderr from ssh: OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
[15:27:03.060] Running script with connection command: ssh -T -D 14700 root@TARGETHOSTNAME bash
[15:27:03.063] Install and start server if needed
[15:27:03.068] Terminal shell path: C:\Windows\System32\cmd.exe
[15:27:03.980] > 
[15:27:03.980] Got some output, clearing connection timeout
[15:27:18.409] > root@TARGETHOSTNAME's password:
[15:27:19.386] > 
[15:27:28.166] > 
> 
[15:27:28.627] > 2ded42c88cfe: running
> 
[15:27:28.701] > Acquiring lock on /root/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/vscode-remote-lock.f359dd69833dd8800b54d458f6d37a
> b7c78df520
> Installing to /root/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520...
> Downloading with wget
[15:27:28.735] > 
> 
[15:27:35.670] > wget download failed
> 
> 
[15:27:35.705] > XDG_SESSION_ID=10
> SELINUX_ROLE_REQUESTED=
> SHELL=/bin/bash
> SSH_CLIENT=192.168.0.50 14706 22
> SELINUX_USE_CURRENT_RANGE=
> QTDIR=/usr/lib64/qt-3.3
> QTINC=/usr/lib64/qt-3.3/include
> QT_GRAPHICSSYSTEM_CHECKED=1
> USER=root
> VSCODE_AGENT_FOLDER=/root/.vscode-server
> PATH=/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
> MAIL=/var/mail/root
> PWD=/root/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520
> LANG=en_US.UTF-8
> KDEDIRS=/usr
> SELINUX_LEVEL_REQUESTED=
> HOME=/root
> SHLVL=2
> LOGNAME=root
> QTLIB=/usr/lib64/qt-3.3/lib
> SSH_CONNECTION=192.168.0.50 14706 192.168.1.10 22
> XDG_DATA_DIRS=/root/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/0
> QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
> _=/usr/bin/printenv
> OLDPWD=/root
> Trigger client server download
> VSCODE_ARCH==x64==
> 2ded42c88cfe__trigger_vscode_server_download__
> Waiting for client to transfer server archive...
> Waiting for /root/.vscode-server/bin/f359dd69833dd8800b54d458f6d37ab7c78df520/vscode-scp-done.flag and vscode-server-linux-x64.tar.gz
>  to exist
> 
[15:27:35.706] Got request to download on client for x64
[15:27:35.719] Resolver error: Failed to download VS Code Server: HTTP 407 - Proxy Authentication Required
[15:27:35.720] ------
````

I have the following as my `settings.json`:
````
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.acceptSuggestionOnCommitCharacter": false,
    "remote.SSH.allowLocalServerDownload": true,
    "remote.SSH.showLoginTerminal": true,
    "git.ignoreLegacyWarning": true
}
````

It appears that `remote.SSH.allowLocalServerDownload` is not being respected.

Why would this be?  Is this option not honored in the case of a proxy failure as noted above?

To be clear... this has nothing to do with support for proxy auth.

As I expected, tcp/443 traffic dst 104.42.72.153 (block owned by MSFT) from the target remote-ssh server:

![image](https://user-images.githubusercontent.com/991809/71262146-0a258700-230d-11ea-9e9c-bc1f7bdb355a.png)

Is this enough proof that the extension is not properly honoring the `remote.SSH.allowLocalServerDownload` setting?

**Comment by roblourens** [comment] 2019-12-30 18:12
I've pushed a fix for #1903 (that's why it's closed) which is now in the Nightly version of this extension. Here's my interpretation of the log: it tried to download the server on the remote, failed with no useful output apparently, then correctly fell back to trying to download on the local side:

> Got request to download on client for x64

and failed with this result:

> HTTP 407 - Proxy Authentication Required

So the setting is respected correctly, and if you try with the latest nightly version of the extension, then it may work for you, and that's why I thought this was a dupe of #1903. But I'm not sure what your tcpdump result is showing. I guess that you got no result from our server before it timed out?

Even with that setting, which is true by default, it will attempt to download from the remote before falling back to the local. Maybe that's not what you expected.

**Comment by mbrownnycnyc** [comment] 2019-12-31 17:38
Thanks @roblourens !  I'll test the nightly when I arrive back at the office.  What you described is interesting, and I'll more carefully review output before drawing my own conclusions.  In regards to the behaviour, I would think that it would attempt a local download (on the VScode client) first then fail back to a remote download (on the connected to host/VScode server).

Thanks and have a happy new year.

**Comment by sergei3000** [comment] 2020-01-14 14:18
I'm not sure if this was the fix that worked for me, but now the remote development feature started working for all my remote servers in Insiders (and not yet in the main app). This feature used to fail on some of those servers before this fix.

**Comment by roblourens** [comment] 2020-01-14 15:59
Will close this unless I hear differently from @mbrownnycnyc

**Closed by roblourens** 2020-01-14 15:59 UTC
Labels: needs-more-info
