### ISSUE TITLE
SSH port forwarding from remote host other than 127.0.0.1

### ISSUE THREAD

**Issue by garaboncias** [microsoft/vscode-remote-release#4919] opened 2021-04-21 08:22 UTC
SSH port forward from other then 127.0.0.1 remote host is not working, but port forward configuration suggest that it should work for example with 10.10.10.10. You can see that Vscode recognize remote process which I want to forward. With SSH command It can be forwarded:
```ssh <remote_server> -L2443:172.55.0.1:2443```
![Screenshot 2021-04-21 at 10 19 49](https://user-images.githubusercontent.com/2393180/115521130-2338a200-a28b-11eb-827a-aaaa7538f935.png)

This ticket is try to reopen an other ticket: https://github.com/microsoft/vscode/issues/113763

- VSCode Version:1.55.2
- Local OS Version: MacOs 10.15.7
- Remote OS Version: Debian 10
- Remote Extension/Connection Type: SSH
- Logs: I checked The "Remote-SSH:Show logs" But there is no information about port forwarding in the logs

Steps to Reproduce:

1. Start remote session
2. Add a port forward configuration with host, which is not the 127.0.0.1

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by alexr00** [comment] 2021-04-23 13:09
duplicate of https://github.com/microsoft/vscode/issues/113763

**Closed by alexr00** 2021-04-23 13:09 UTC

**Comment by garaboncias** [comment] 2021-04-23 14:57
Why this suggestion is there if it's not working?
![Screenshot 2021-04-21 at 10 19 49](https://user-images.githubusercontent.com/2393180/115890099-df919400-a454-11eb-8ad5-4f5cc7b43bce.png)
