### ISSUE TITLE
remote ssh can't connect - Server installation process already in progress 

### ISSUE THREAD

**Issue by kybom** [microsoft/vscode-remote-release#2507] opened 2020-03-10 02:24 UTC
- VSCode Version: 1.43.0
- remote-ssh Version:  0.50.0
- Local OS Version: windows10 1909
- Remote OS Version: ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Update latest vscode and remote-ssh,and reload vscode
2. open remote folder 
vscode output:
```
[09:52:12.633] Log Level: 2
[09:52:12.636] remote-ssh@0.50.0
[09:52:12.637] win32 x64
[09:52:12.638] SSH Resolver called for "ssh-remote+test90", attempt 1
[09:52:12.639] SSH Resolver called for host: test90
[09:52:12.639] Setting up SSH remote "test90"
[09:52:12.642] Acquiring local install lock: C:\Users\sma\AppData\Local\Temp\vscode-remote-ssh-test90-install.lock
[09:52:12.654] Looking for existing server data file at c:\Users\sma\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-test90-78a4c91400152c0f27ba4d363eb56d2835f9903a\data.json
[09:52:12.654] Using commit id "78a4c91400152c0f27ba4d363eb56d2835f9903a" and quality "stable" for server
[09:52:12.655] Install and start server if needed
[09:52:12.657] Checking ssh with "ssh -V"
[09:52:12.691] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:52:12.691] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[09:52:12.725] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:52:12.726] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[09:52:12.767] > OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
[09:52:12.769] askpass server listening on \\.\pipe\vscode-ssh-askpass-429874e21720a1aa2c5e157ab42a85dd406ae87a-sock
[09:52:12.769] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-1c04b125e0c94a914cf2864b38564dd0220af430-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","9516","test90"],"dataFilePath":"c:\\Users\\sma\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-test90-78a4c91400152c0f27ba4d363eb56d2835f9903a\\data.json"}
[09:52:12.769] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\sma\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\sma\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\sma\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-429874e21720a1aa2c5e157ab42a85dd406ae87a-sock"}
[09:52:12.774] Spawned 17740
[09:52:12.850] > local-server> Spawned ssh: 7188
[09:52:12.876] stderr> OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
[09:52:12.900] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:hjik4eW6ta5f8QfY17Ew8fCSMaMs3wSJDxuhbnOCUMU
[09:52:12.918] stderr> Authenticated to 192.168.130.90 ([192.168.130.90]:22).
[09:52:13.461] > Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-41-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Tue Mar 10 09:52:14 CST 2020
> 
>   System load:  0.68               Processes:            269
>   Usage of /:   19.2% of 78.24GB   Users logged in:      0
>   Memory usage: 15%                IP address for ens33: 192.168.130.90
>   Swap usage:   0%
> 
>  * Latest Kubernetes 1.18 beta is now available for your laptop, NUC, cloud
>    instance or Raspberry Pi, with automatic updates to the final GA release.
> 
>      sudo snap install microk8s --channel=1.18/beta --classic
> 
>  * Multipass 1.1 adds proxy support for developers behind enterprise
>    firewalls. Rapid prototyping for cloud operations just got easier.
> 
>      https://multipass.run/
> 
>  * Canonical Livepatch is enabled.
>    - All available patches applied.
> 
> 21 packages can be updated.
> 0 updates are security updates.
> 
> Your Hardware Enablement Stack (HWE) is supported until April 2023.
[09:52:13.486] > ready: bf498b68ec99
[09:52:13.492] > Linux 5.3.0-41-generic #33~18.04.1-Ubuntu SMP Mon Feb 17 12:51:52 UTC 2020
[09:52:13.492] Platform: linux
[09:52:13.504] > bf498b68ec99: running
[09:52:13.518] > Acquiring lock on /home/sma/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.sma.78a4c91400152c0f27ba4d363eb56d2835f9903a
[09:52:13.520] > \ln /home/sma/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.sma.78a4c91400152c0f27ba4d363eb56d2835f9903a.target /home/sma/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.sma.78a4c91400152c0f27ba4d363eb56d2835f9903a
[09:52:13.522] > Installation already in progress...
> bf498b68ec99##24##
[09:52:13.522] Received install output: bf498b68ec99##24##
[09:52:13.523] Server installation process already in progress - waiting and retrying
[09:52:13.523] Terminating local server
[09:52:13.523] stderr> ln: failed to create hard link '/home/sma/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.sma.78a4c91400152c0f27ba4d363eb56d2835f9903a': File exists
[09:52:13.529] Local server exit: null
[09:52:14.526] askpass server listening on \\.\pipe\vscode-ssh-askpass-d90a061e3805eb169645b16717c01875a2a2bf63-sock
[09:52:14.526] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-745bacebf51ed117503de26e0ca9787d89d43d60-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","9516","test90"],"dataFilePath":"c:\\Users\\sma\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-test90-78a4c91400152c0f27ba4d363eb56d2835f9903a\\data.json"}
[09:52:14.526] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\sma\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\sma\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\sma\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-d90a061e3805eb169645b16717c01875a2a2bf63-sock"}
[09:52:14.531] Spawned 39048
[09:52:14.606] > local-server> Spawned ssh: 46428
[09:52:14.632] stderr> OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
[09:52:14.656] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:hjik4eW6ta5f8QfY17Ew8fCSMaMs3wSJDxuhbnOCUMU
[09:52:14.669] stderr> Authenticated to 192.168.130.90 ([192.168.130.90]:22).
[09:52:15.149] > Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-41-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
```

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by kmalloc** [comment] 2020-03-10 02:40
the same issue here, and I figured out a way to fix it by removing the hardlink.

> [09:52:13.523] stderr> ln: failed to create hard link '/home/sma/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.sma.78a4c91400152c0f27ba4d363eb56d2835f9903a': File exists

**Comment by kybom** [comment] 2020-03-10 02:49
> the same issue here, and I figured out a way to fix it by removing the hardlink.
> 
> > [09:52:13.523] stderr> ln: failed to create hard link '/home/sma/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.sma.78a4c91400152c0f27ba4d363eb56d2835f9903a': File exists

Thanks,it works for me.
I remove the file  and the target file.

**Comment by DucNguyenPTIT** [comment] 2020-03-10 02:52
I have the same issue, though the log is a bit different

`[11:50:13.863] Log Level: 2
[11:50:13.936] remote-ssh@0.50.0
[11:50:13.936] win32 x64
[11:50:13.939] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22646f7444617461446576536572766572227d", attempt 1
[11:50:13.939] SSH Resolver called for host: dotDataDevServer
[11:50:13.939] Setting up SSH remote "dotDataDevServer"
[11:50:13.949] Acquiring local install lock: D:\Users\000001A00APTE\AppData\Local\Temp\vscode-remote-ssh-dotDataDevServer-install.lock
[11:50:14.171] Looking for existing server data file at d:\Users\000001A00APTE\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-dotDataDevServer-78a4c91400152c0f27ba4d363eb56d2835f9903a\data.json
[11:50:14.172] Using commit id "78a4c91400152c0f27ba4d363eb56d2835f9903a" and quality "stable" for server
[11:50:14.174] Install and start server if needed
[11:50:14.179] Checking ssh with "ssh -V"
[11:50:15.159] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[11:50:15.160] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[11:50:16.001] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[11:50:16.001] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[11:50:19.540] > OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[11:50:19.543] askpass server listening on \\.\pipe\vscode-ssh-askpass-1e0edd8781e3525f350cbf4ab46c4dfafe7147bc-sock
[11:50:19.544] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-a1f8e5372ec83b7244737a3c3260353386cce56f-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","62311","dotDataDevServer"],"dataFilePath":"d:\\Users\\000001A00APTE\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-dotDataDevServer-78a4c91400152c0f27ba4d363eb56d2835f9903a\\data.json"}
[11:50:19.544] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"d:\\Users\\000001A00APTE\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"D:\\Users\\000001A00APTE\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_MAIN":"d:\\Users\\000001A00APTE\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.50.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-1e0edd8781e3525f350cbf4ab46c4dfafe7147bc-sock"}
[11:50:19.636] Spawned 5504
[11:50:19.941] > local-server> Spawned ssh: 7256
[11:50:20.320] stderr> OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[11:50:20.693] stderr> /bin/sh: line 0: exec: C:Program: not found
[11:50:20.693] stderr> kex_exchange_identification: Connection closed by remote host
[11:50:20.718] > local-server> ssh child died, shutting down
[11:50:21.065] Local server exit: 0
[11:50:21.066] Received install output: OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
/bin/sh: line 0: exec: C:Program: not found
kex_exchange_identification: Connection closed by remote host

[11:50:21.067] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019/bin/sh: line 0: exec: C:Program: not foundkex_exchange_identification: Connection closed by remote host
[11:50:21.067] Failed to parse remote port from server output
[11:50:21.068] Resolver error: 
[11:50:21.071] ------`

**Comment by ROGERDJQ** [comment] 2020-03-10 03:42
same issue， still working on it

**Comment by ROGERDJQ** [comment] 2020-03-10 03:45
> > the same issue here, and I figured out a way to fix it by removing the hardlink.
> > > [09:52:13.523] stderr> ln: failed to create hard link '/home/sma/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.sma.78a4c91400152c0f27ba4d363eb56d2835f9903a': File exists
> 
> Thanks,it works for me.
> I remove the file and the target file.

thanks, it works

**Comment by roblourens** [comment] 2020-03-10 03:57
So you saw this but did you have multiple windows trying to log in at the same time or something like that?

@DucNguyenPTIT I have no idea where your issue is coming from.

`/bin/sh: line 0: exec: C:Program: not found`

What if you set `"remote.SSH.useLocalServer": false`, does that work with the latest extension version?

**Comment by DucNguyenPTIT** [comment] 2020-03-10 04:21
> So you saw this but did you have multiple windows trying to log in at the same time or something like that?
Even with one window I still can't log in

> What if you set `"remote.SSH.useLocalServer": false`, does that work with the latest extension version?
I've tried as you said and it kept retrying connection for several times

**Comment by roblourens** [comment] 2020-03-10 04:41
Could you open a new issue with the full log from that last attempt?

**Comment by DucNguyenPTIT** [comment] 2020-03-10 05:13
@roblourens 
Sorry, I tried setting `"remote.SSH.useLocalServer": false` again and now it works with the latest version

**Comment by lunedam-git** [comment] 2020-03-10 12:16
Was having the same issue with latest remote-SSH (0.50.0). Could connect OK to CentOS boxes but the one Ubuntu box I have just wasn't connecting. Set 'remote.SSH.useLocalServer' to false as suggested and things started working again. Thanks @roblourens

**Comment by roblourens** [comment] 2020-03-11 05:10
@DucNguyenPTIT thanks, still thinking about your issue, do you have some non-standard shell set as your default local shell, or something like that?

@lunedam-git would appreciate if you try again with that setting enabled, and create a new issue with the log from the Remote-SSH output channel. I've identified a few issues but I want to make sure I get yours.

**Comment by DucNguyenPTIT** [comment] 2020-03-11 05:16
> do you have some non-standard shell set as your default local shell, or something like that?

@roblourens 
I don't think so, I only use bash or powershell as my default shell

**Comment by lunedam-git** [comment] 2020-03-11 12:25
@roblourens 

[12:06:16.753] Log Level: 2
[12:06:16.754] remote-ssh@0.50.0
[12:06:16.754] darwin x64
[12:06:16.757] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22616e7977686572652d6170692d444556227d", attempt 1
[12:06:16.757] SSH Resolver called for host: REMOTE-HOST
[12:06:16.757] Setting up SSH remote "REMOTE-HOST"
[12:06:16.760] Acquiring local install lock: /var/folders/tt/w03n09pn17qdrrz5psfbjxr80000gn/T/vscode-remote-ssh-REMOTE-HOST-install.lock
[12:06:16.762] Looking for existing server data file at /Users/smg/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-REMOTE-HOST-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[12:06:16.764] Using commit id "78a4c91400152c0f27ba4d363eb56d2835f9903a" and quality "stable" for server
[12:06:16.765] Install and start server if needed
[12:06:16.769] Checking ssh with "ssh -V"
[12:06:16.791] > OpenSSH_7.9p1, LibreSSL 2.7.3
[12:06:16.793] askpass server listening on /var/folders/tt/w03n09pn17qdrrz5psfbjxr80000gn/T/vscode-ssh-askpass-a5d42b4f76c232618ae646bf8b954f0492fbbb1e.sock
[12:06:16.794] Spawning local server with {"ipcHandlePath":"/var/folders/tt/w03n09pn17qdrrz5psfbjxr80000gn/T/vscode-ssh-askpass-10f691a9b9eb5b0ef59ee5ef9811d541b4524741.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","49665","-o","ConnectTimeout=15","REMOTE-HOST"],"dataFilePath":"/Users/smg/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-REMOTE-HOST-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json"}
[12:06:16.794] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/smg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/smg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/tt/w03n09pn17qdrrz5psfbjxr80000gn/T/vscode-ssh-askpass-a5d42b4f76c232618ae646bf8b954f0492fbbb1e.sock"}
[12:06:16.799] Spawned 967
[12:06:16.925] > local-server> Spawned ssh: 968
[12:06:16.938] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[12:06:17.108] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:3MrE2APXXXR43T5miuTg8dEpUkJG3BRHF4cc0svRAWo
[12:06:17.265] stderr> Authenticated to xxx.xx.xx.xxx ([xxx.xx.xx.xxx]:22).
[12:06:17.423] > Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-174-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   Get cloud support with Ubuntu Advantage Cloud Guest:
>     http://www.ubuntu.com/business/services/cloud
> 
> 150 packages can be updated.
> 4 updates are security updates.
> 
> New release '18.04.4 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> This is REMOTEHOST server
[12:06:17.443] > ready: d23a08733da2
[12:06:17.468] > Linux 4.4.0-174-generic #204-Ubuntu SMP Wed Jan 29 06:41:01 UTC 2020
[12:06:17.469] Platform: linux
[12:06:17.519] stderr> bash: line 1: ]: command not found
[12:06:17.521] > d23a08733da2: running
[12:06:17.522] stderr> bash: line 2: syntax error near unexpected token `then'
[12:06:17.522] stderr> bash: line 2: `  then'
[12:06:17.523] stderr> -sh: 4: function: not found
[12:06:17.523] stderr> -sh: 20: [[: not found
[12:06:17.524] stderr> -sh: 83: Syntax error: "(" unexpected (expecting "then")
[12:06:17.525] stderr> Transferred: sent 14608, received 3848 bytes, in 0.3 seconds
[12:06:17.525] stderr> Bytes per second: sent 56366.3, received 14847.9
[12:06:17.527] > local-server> ssh child died, shutting down
[12:06:17.533] Local server exit: 0
[12:06:17.533] Received install output: OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:3MrE2APXXXR43T5miuTg8dEpUkJG3BRHF4cc0svRAWo
Authenticated to xxx.xx.xx.xxx ([xxx.xx.xx.xxx]:22).
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-174-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

150 packages can be updated.
4 updates are security updates.

New release '18.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


This is REMOTEHOST server
ready: d23a08733da2
Linux 4.4.0-174-generic #204-Ubuntu SMP Wed Jan 29 06:41:01 UTC 2020
bash: line 1: ]: command not found
d23a08733da2: running
bash: line 2: syntax error near unexpected token `then'
bash: line 2: ` then'
-sh: 4: function: not found
-sh: 20: [[: not found
-sh: 83: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 14608, received 3848 bytes, in 0.3 seconds
Bytes per second: sent 56366.3, received 14847.9

[12:06:17.534] Stopped parsing output early. Remaining text: OpenSSH_7.9p1, LibreSSL 2.7.3debug1: Server host key: ecdsa-sha2-nistp256 SHA256:3MrE2APXXXR43T5miuTg8dEpUkJG3BRHF4cc0svRAWoAuthenticated to xxx.xx.xx.xxx ([xxx.xx.xx.xxx]:22).Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-174-generic x86_64) * Documentation:  https://help.ubuntu.com * Management:     https://landscape.canonical.com * Support:        https://ubuntu.com/advantage  Get cloud support with Ubuntu Advantage Cloud Guest:    http://www.ubuntu.com/business/services/cloud150 packages can be updated.4 updates are security updates.New release '18.04.4 LTS' available.Run 'do-release-upgrade' to upgrade to it.This is REMOTEHOST serverready: d23a08733da2Linux 4.4.0-174-generic #204-Ubuntu SMP Wed Jan 29 06:41:01 UTC 2020bash: line 1: ]: command not foundd23a08733da2: runningbash: line 2: syntax error near unexpected token `then'bash: line 2: `  then'-sh: 4: function: not found-sh: 20: [[: not found-sh: 83: Syntax error: "(" unexpected (expecting "then")Transferred: sent 14608, received 3848 bytes, in 0.3 secondsBytes per second: sent 56366.3, received 14847.9
[12:06:17.534] Failed to parse remote port from server output
[12:06:17.536] Resolver error: 
[12:06:17.542] ------

**Comment by lunedam-git** [comment] 2020-03-11 12:38
@roblourens sorry! Neglected to submit new issue as requested. Now done with [2528](https://github.com/microsoft/vscode-remote-release/issues/2528)

**Comment by zao** [comment] 2020-03-12 21:20
> So you saw this but did you have multiple windows trying to log in at the same time or something like that?

@roblourens I just ran into the same issue as the reporter when my installation upgraded to 1.43.
It had two windows with Remote: SSH to the same host and one local window.

The first window was taking a long time doing _something_ while setting up the upgraded remote server bits, while the second one retried until popping some UI to close or retry the remote.

My remote is like the reporter's on 18.04, my home directory is on a somewhat slow NFS mount.

Future attempts to connect even with one window still failed until manually removing the mentioned hardlink, after which the installation appears to have completed and is usable, but I'm not sure about its integrity.

**Comment by assadniang** [comment] 2020-03-13 14:27
> the same issue here, and I figured out a way to fix it by removing the hardlink.
> 
> > [09:52:13.523] stderr> ln: failed to create hard link '/home/sma/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.sma.78a4c91400152c0f27ba4d363eb56d2835f9903a': File exists

Thanks, had the same issue after upgrading, google brought me here.
Remove the file, and restarted VSCODE, which worked!

**Comment by roblourens** [comment] 2020-03-13 22:49
@DocNguyenPTIT now tracking your issue in https://github.com/microsoft/vscode-remote-release/issues/2546

Is everyone with this issue using NFS? Does `"remote.SSH.lockfilesInTmp": true` help?

**Comment by zao** [comment] 2020-03-15 04:23
I can unfortunately not reproduce this to test that setting - as I didn't save the previously broken state and after successfully upgrading there's nothing to upgrade.

For what it's worth, I haven't been able to get multiple remote sessions to clash when doing initial installations of the server code, the second one neatly waits for the first to complete there in the couple of attempts I've done.

**Comment by roblourens** [comment] 2020-03-15 04:32
Closing this as a dupe of https://github.com/microsoft/vscode-remote-release/issues/2518

**Closed by roblourens** 2020-03-15 04:32 UTC
Labels: needs-more-info

**Comment by zao** [comment] 2020-03-16 13:01
I had something which resembled this wedge now as I got back to work and it tried connecting to the machine in question, where several of the windows popped the same kind of failure dialog as before.

I set `"remote.SSH.lockfilesInTmp": true`, exited, and restarted and it seemed to connect fine. Whether this actually means anything or if it was just blind luck and a different problem that looked like the one, I don't know.

Sorry for not being able to give any useful information.

**Comment by f4tq** [comment] 2020-04-08 01:04
I happened upon this link searching for the hard link error which I too have but...  
In my case, I am using a fresh vagrant/Virtual Box with Ubuntu 16.04 to debug bpf issues.
At first Remote SSH *worked* because I was *not* sharing a folder into the VM i.e. I was using default vagrant user. Once I created a user within the vm to match my host user name's id, I halted the VM and added the shared folder to act as the Guest's home (so I can do backups).  Voila, both the ssh password loop and the hard link issue appeared.  
Switching back to the 'vagrant' user, no shared folder -> it works!
It would also explain why ` "remote.SSH.lockfilesInTmp": true,` works since /tmp is not shared.
Hope that helps someone...

**Comment by sfsccn** [comment] 2020-04-15 14:33
I had the same issue after VS Code upgraded from 1.44 to 1.44.1. Remote SSH was working before the upgrade. After the upgrade it failed with the "failed to create hard link" error.  Setting `remote.SSH.useLocalServer` from true to false did not fix it.

What fixed it was deleting this file (after backing it up):

`$HOME/.vscode-server/bin/<long id>/vscode-remote-lock.<username>.<long id>`

After that, I could connect normally, even with `remote.SSH.useLocalServer=true`.

**Comment by xpirad** [comment] 2020-04-21 06:33
> I had the same issue after VS Code upgraded from 1.44 to 1.44.1. Remote SSH was working before the upgrade. After the upgrade it failed with the "failed to create hard link" error. Setting `remote.SSH.useLocalServer` from true to false did not fix it.
> 
> What fixed it was deleting this file (after backing it up):
> 
> `$HOME/.vscode-server/bin/<long id>/vscode-remote-lock.<username>.<long id>`
> 
> After that, I could connect normally, even with `remote.SSH.useLocalServer=true`.
> 
> **Remote OS**: Ubuntu 19.10

Yes! i tried it and it worked!! Thanks!!
