### ISSUE TITLE
Remote Explorer shows only ssh targets

### ISSUE THREAD

**Issue by ramgesg** [microsoft/vscode-remote-release#1847] opened 2019-11-14 12:04 UTC
Issue Type: <b>Bug</b>

Remote Explorer displays only SSH Targets, WSL & Container is missing, even if  the same is selected from the top dropdown. It only shows SSH Targets

Extension version: 0.17.0
VS Code version: Code - Insiders 1.41.0-insider (eccf417b72fc0a632ec2cbd7855a681cdb8c81fa, 2019-11-14T09:50:04.822Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (21.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment] 2019-11-14 16:00
@ramgesg I think I've seen this too, but when I reload the issue resolves. When I saw the issue, I think I had the window open for a while before going to the Remote Explorer. Do you remember if you also had the window open for a while before opening the remote explorer?

**Comment by ramgesg** [comment] 2019-11-15 08:19
@alexr00, it happens immediately, yes on reload, it temporarily fixes the issue. But once the IDE is closed and reopened. what ever was selected (say for example: WSL Targets) before closing seems to be stuck with.

**Comment by alexr00** [comment] 2019-11-15 09:06
I can't reproduce the issue when running out of sources, but I can see what's going wrong. I pushed a change that I think will help. We'll try out the next insiders build and see.

**Comment by ramgesg** [comment] 2019-11-18 06:44
@alexr00, The change that has been pushed think it solved the initial report. But there is a redundent tab of SSH Targets now :( 
![image](https://user-images.githubusercontent.com/26381563/69030228-ed8beb80-09fc-11ea-94d1-0bd5e2c37035.png)

Version: 1.41.0-insider (user setup)
Commit: fe03510f9e9fb269ca35da0ea600dd95279fa2b7
Date: 2019-11-18T05:31:02.684Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by alexr00** [comment] 2019-11-18 08:48
I can see it too. Looking at a fix.

**Comment by alexr00** [comment] 2019-11-18 08:58
Looks like an ordering issue. Tested and pushed a fix.

**Comment by ramgesg** [comment] 2019-11-18 14:35
The issue has been resolved in the Insiders release. Thanks @alexr00  for the help!

**Comment by alexr00** [comment] 2019-11-18 15:53
Thanks for verifying the fix!

**Closed** 2019-11-19 10:50 UTC
Labels: bug, verified
