### ISSUE TITLE
Remote SSH forwards all ports

### ISSUE THREAD

**Issue by rijenkii** [microsoft/vscode-remote-release#4185] opened 2020-12-14 04:40 UTC
Issue Type: <b>Bug</b>

After a recent update VSCode started forwarding all ports that are opened on the remote machine by the user that is running the server -- before it just forwarded the ports that I have opened through the built-in terminal.
That in itself is not a much of a problem, until I try to connect to `localhost` -- then:
* VSCode forwards all opened ports;
* notices that some new ports have just opened (the ones that it just forwarded);
* forwards them;
* notices new opened ports;
* forwards them

ad infinitum.

Extension version: 0.62.0
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 6.3.9600
Remote OS version: Linux x64 5.9.13-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.24GB free)|
|Process Argv|--crash-reporter-id b6c3bdcb-22b1-44b3-8ebf-87535db9be29|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 90.189.172.126|
|OS|Linux x64 5.9.13-arch1-1|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 1220)|
|Memory (System)|5.69GB (3.54GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30233463
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30233462
pythonvspyt600:30228411
vsjup459cf:30229594

```

</details>

**Comment by alexr00** [comment] 2020-12-17 09:28
@rijenkii could you share a screenshot of the Ports view (by default it's in the Remote Explorer activity in the sidebar)? I want to make sure I understand what you're describing.

**Comment by rijenkii** [comment] 2020-12-17 09:51
@alexr00 here
![изображение](https://user-images.githubusercontent.com/5338332/102471659-0cd5cc00-4088-11eb-84ba-17ee6f858ac6.png)

**Comment by alexr00** [comment] 2020-12-22 10:21
@rijenkii I'm not able to reproduce this issue. 

> until I try to connect to localhost 

What exactly are you doing to connect to localhost?

I tried to repro with the simple Microsoft/vscode-remote-try-node sample repo. My steps:
1. Connect to an SSH remote
2. Run `node server.js`, which runs a server listeniner on 3000
3. See that 3000 is auto forwarded
4. Open localhost:3000 in the browser

**Comment by rijenkii** [comment] 2020-12-22 11:26
I have just reproduced this on a fresh install of Debian 10 with a fresh installed VSCode downloaded from code.visualstudio.com

<details>
<summary>Screenshots of steps</summary>

![20201222-181907](https://user-images.githubusercontent.com/5338332/102883582-d252a180-4482-11eb-82b3-a844aa75dc1d.png)

![20201222-181917](https://user-images.githubusercontent.com/5338332/102883580-d1ba0b00-4482-11eb-9ffa-2ec70d838cdc.png)

![20201222-181926](https://user-images.githubusercontent.com/5338332/102883578-d1217480-4482-11eb-8d20-b24497929316.png)

![20201222-181930](https://user-images.githubusercontent.com/5338332/102883577-d1217480-4482-11eb-93ca-714139f103a2.png)

![20201222-181938](https://user-images.githubusercontent.com/5338332/102883573-cff04780-4482-11eb-961c-c509d2f87e07.png)

</details>

<details> 
<summary>Result</summary>

![20201222-182207](https://user-images.githubusercontent.com/5338332/102883732-13e34c80-4483-11eb-89f1-1f0e0a8dcf1d.png)

</details>

**Comment by alexr00** [comment] 2020-12-22 11:45
Thanks, that clarifies things. I can repro.

**Comment by alexr00** [comment] 2020-12-24 10:55
Fixed by https://github.com/microsoft/vscode/commit/0b1892f877e0f842ec3af08d8ee0c4cf914b8bf8

**Closed by alexr00** 2020-12-24 10:55 UTC
Labels: bug, remote-explorer
