### ISSUE TITLE
Can't connect to <my-remote-host>: unreachable or not Linux x86_64 (execvp(3) failed.: No such file or directory )

### ISSUE THREAD

**Issue by ieipi** [microsoft/vscode-remote-release#628] opened 2019-06-10 09:45 UTC
- VSCode Version: 1.35.0
- Local OS Version: macOS 10.12.6
- Remote OS Version: Linux 3.10.0-327.ali2012.alios7.x86_64
- Remote Extension/Connection Type: SSH/Docker/WSL: SSH

Steps to Reproduce:
1.connections->remotehost->connect to host in new window
2.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes
![17_44_51__06_10_2019](https://user-images.githubusercontent.com/472043/59187208-80e80780-8ba7-11e9-914c-2cfea2a4262a.jpg)

**Comment by magic-lantern** [comment] 2019-06-10 17:52
This appears to be a duplicate of #590 - @ieipi, can you provide additional details or verify if your bug has the same issue as reported by users on bug #590?

**Comment by ieipi** [comment] 2019-06-19 10:04
there is another error message:
does it mean i need to change shell version, if so, how to change?

The terminal process command 'sh -c 'ssh -o ConnectTimeout=15  "dingx_39" bash << 'EOSSH'
uname -sm
EOSSH
exit 0'' failed to launch (exit code: 1)

**Comment by roblourens** [comment] 2019-09-16 01:15
Is this still an issue?

**Closed** 2019-09-23 01:52 UTC
Labels: needs-more-info, ssh
