### ISSUE TITLE
key passphrase periodically removed from keyring

### ISSUE THREAD

**Issue by moredanphysics** [microsoft/vscode-remote-release#6404] opened 2022-03-01 17:21 UTC
I use vscode on ArchLinux with remote-ssh which uses my GPG authentication subkey to access my remote machine via my local gpg-agent. Connection works well: vscode connects to my gpg-agent and pinentry asks me for the key passphrase and saves it in my local keyring. However, some time later (few seconds or up to an hour; no obvious trigger such as git pull or push etc) vscode removes the passphrase from the keyring and i'm then obviously prompted again for the passphrase. Has anyone encountered this?

I stopped using the gnome-keyring and tried a dedicated keepassxc database using the secret services functionality in keepassxc. That's nice because now I get a prompt before deletion of the passphrase and I just refuse deletion. After the refusal, everything carries on working fine! But I don't understand why vscode tries to remove the passphrase in the first place. Is there a timeout (clear the passphrase for security reasons?) that I can configure somewhere? 

- VSCode Version: 1.6.4 (also happens with vscode-insiders)
- Local OS Version: 5.16.11-arch1-1
- Remote OS Version: 3.10.0-1160.el7.x86_64
- Remote Extension/Connection Type: SSH
- Logs: Nothing shows up at the moment when the passphrase is re-requested

Steps to Reproduce:
1. I run vscode with the following command: GPG_AGENT_INFO=(gpgconf --list-dirs agent-socket):0:1 /usr/bin/code
2. Connect with key via gpg-agent and save key passphrase in local keyring
3. Watch the keyring like a hawk and eventually vscode seems to delete the passphrase

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by DanJohnsonCERN** [comment] 2022-03-01 21:10
I see what you mean, but from what I understood of that issue, the focus was on disconnection. I never saw any evidence of being disconnected, and if I refuse to re-enter the passphrase then there is no problem in vscode and it all works as if there had never been a prompt.

What's weird here, that I didn't see described there, is that vscode is actively manipulating the keyring and removing a passphrase!

**Comment by CrfzdPQM6** [comment] 2022-05-25 10:22
Just to update this issue, I'm still seeing the problem with Visual Studio Code - Insiders 1.65.0-insider

**Comment by roblourens** [comment] 2022-12-06 17:20
Sorry, I'm not sure what the issue is, but I'm sure that vscode is not deleting keys from your gpg agent.

**Comment by CrfzdPQM6** [comment] 2022-12-06 17:44
Hi @roblourens thanks for commenting, but you were a bit dismissive. How do you know? That's exactly what seems to have been happening.

**Comment by roblourens** [comment] 2022-12-12 06:00
I know that Remote-SSH isn't doing that. @lszomoru, can you think of any reason that the git gpg support would cause a passphrase to be removed from the keyring?

> I ended up moving my keyring inside another password manager which would prompt me before allowing any edits. Using this setup I can deny vscode access to my keyring unless I know why it's asking for it. 

@CrfzdPQM6 If this setup enables you to prove that vscode is attempting to delete the passphrase, I'd be interested to hear more

**Comment by CrfzdPQM6** [comment] 2022-12-16 17:16
This is happening a lot to me at the moment (multiple times today) with a particular set of repositories in one vscode window. Is there a way to debug queries to the keychain so that I can identify the calls that delete the key? It seems to delete my ssh key when stored within my keychain. 

I'm not 100% sure that it's not another rogue application, but the problem only seems to be present when I have a particular vscode window open.

**Comment by roblourens** [comment] 2022-12-16 19:53
I wonder what extensions you have installed and whether this still happens if you disable them all? I don't even see anywhere that we use `GPG_AGENT_INFO` in the vscode codebase

**Comment by CrfzdPQM6** [comment] 2022-12-16 20:02
Interesting thought. My money's on the remote/SSH development extensions. I've removed them; let's see how it goes.

**Comment by roblourens** [comment] 2022-12-16 20:32
I don't think Remote-SSH is doing this either, but it might still be an issue that only happens in a remote window

**Comment by CrfzdPQM6** [comment] 2022-12-16 20:44
It's happening in a non-remote window, though... (in fact none of my open windows are remote)

**Comment by roblourens** [comment] 2022-12-19 17:47
Optimistically assigning to @lszomoru since I think the git extension is the most likely candidate?

**Comment by CrfzdPQM6** [comment] 2022-12-19 21:02
Interesting. I set dbus-monitor running and immediately navigated to my vscode window that I suspect. After 1 second on that window, I went back to keepassxc and saw that the gpg key had been removed from my keepassxc keyring. There's 1500 lines of text in the log, and I can't identify vscode amongst them, but the timing was too close for it to be anything else. And amongst those lines I do see what looks like a deletion request:
method call time=1671483368.434655 sender=:1.704 -> destination=org.freedesktop.secrets serial=9 path=/org/freedesktop/secrets/collection/KP_<redacted>; interface=org.freedesktop. Secret.Item; member=Delete

**Comment by CrfzdPQM6** [comment] 2022-12-19 21:04
> Optimistically assigning to @lszomoru since I think the git extension is the most likely candidate?

My instinct is that it's connected to git. The behaviour happens in a window to a folder containing maybe 10 different git repositories in it, and authentication to the gitlab server happens with my GPG authentication subkey.

**Comment by roblourens** [comment] 2022-12-19 22:08
Do you know how to interpret this? `sender=:1.704`

**Comment by lszomoru** [comment] 2022-12-20 08:08
@TylerLeonhardt, is it fair to assume that VS Code can only interact with the keyring though `keytar`? As far as I know, the `vscode.git` extension does not have any dependencies on `keytar` so I am not sure whether the `vscode.git` extension can remove a key from the keyring. I believe that the only "component" that uses `keytar` are the two authentication extensions (GitHub, Microsoft).

**Comment by TylerLeonhardt** [comment] 2023-01-11 02:02
> is it fair to assume that VS Code can only interact with the keyring though `keytar`?

Yes that's correct. VS Code core only interacts with the keychain through `keytar`.

Obviously, an extension being an open playing field... could use:

* The SecretStorage API: which tells vscode to manage secrets... but it uses keytar under the hood
* `keytar` directly and use it however (keep in mind, we do [shim keytar ](https://github.com/microsoft/vscode/blob/2c03fff8d19cb63abf3955ee27702bdf930908d2/src/vs/workbench/api/common/extHostRequireInterceptor.ts#L201)when an extension does this)
* Run some CLI that could interact with the keychain

**Comment by CrfzdPQM6** [comment] 2023-09-02 10:28
I've continued to have problems with keys being removed from the system keyring, though I've been struggling to prove to myself that this is actually vscode! However, following a recent vscode update, I got this message as soon as I opened a big repository:
> An OS keyring couldn't be identified for storing the encryption related data in your current desktop environment. Open the troubleshooting guide to address this or you can use weaker encryption that doesn't use the OS keyring

Here's a screenshot of the dialog that contained this message:
(https://ibb.co/LQ4CKdT)

Any ideas for ways I can trace down what aspect of vscode (or my extensions to it) is interacting with my system to want to play with the keyring when certain repositories are open? I certainly use ssh keys (through my keyring) to authenticate repository access, but I'm not aware of what would be using this authentication in the background or attempting to manipulate the keyring.

**Comment by CrfzdPQM6** [comment] 2023-09-02 10:33
For what it's worth, the link it points me to is https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues

**Comment by TylerLeonhardt** [comment] 2023-09-05 18:55
> Any ideas for ways I can trace down what aspect of vscode (or my extensions to it) is interacting with my system to want to play with the keyring when certain repositories are open?

At this point, there is no code in VS Code or built-in extensions that directly interacts with your keyring. We now use a feature of electron (which really turns around and calls Chromium) to encrypt & decrypt strings using a key stored in your keyring. In other words, VS Code no longer has the ability to arbitrarily write/delete keys in your keyring.

That message that you see is a result of the switch away from keytar, to using this Electron API. In the next version of VS Code, 1.83, we will no longer even ship a shim for keytar...
https://github.com/microsoft/vscode/pull/192224

With that said, if you still think it's something in the VS Code realm, then it must be an extension that you installed, in which case, you can try disabling the ones you're suspicious of and see if the issue remains.

**Closed** 2024-12-20 10:21 UTC
Labels: ssh, under-discussion
