### ISSUE TITLE
Edge debugging over remoting results in void(0) is not a constructor

### ISSUE THREAD

**Issue by OneCyrus** [microsoft/vscode-remote-release#8302] opened 2023-03-31 09:04 UTC
- VSCode Version: 1.77
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: SSH + Codespaces

- Logs: couldn't find a log with this error

Steps to Reproduce:

This happens over SSH remoting and codespaces. It works when debugging local (not over a remoting extension)

We use a config like this:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Edge",
      "request": "launch",
      "type": "msedge",
      "url": "http://localhost:35285",
      "webRoot": "${workspaceFolder}",
      "preLaunchTask": "VITE"
    }
  ]
}
```
when starting the debugging action it shows this error:
![image](https://user-images.githubusercontent.com/7747800/229075853-54524f91-5aea-461d-94bb-97675c71b59c.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by OneCyrus** [comment] 2023-03-31 09:07
looks like other have the same issue since the latest update:
https://stackoverflow.com/questions/75894025/vs-code-debug-with-chrome-spitting-out-weird-error-after-no-change-unable-to-la
https://twitter.com/karamem0/status/1641612656309334016

**Comment by joyceerhl** [comment] 2023-03-31 22:50
Possible duplicate of https://github.com/microsoft/vscode-js-debug/issues/1628?

**Comment by connor4312** [comment] 2023-04-01 00:22
It's a duplicate.

This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). I will also propose it for a recovery release next week.

**Closed by connor4312** 2023-04-01 00:22 UTC
Labels: ssh
