### ISSUE TITLE
VS code does not support FreeBSD for remote editing

### ISSUE THREAD

**Issue by dyeske** [microsoft/vscode-remote-release#1730] opened 2019-10-23 16:26 UTC
VS code does not appear to support FreeBSD for remote editing.  I have observed how this works on Linux and it appears that MS code initializes a nodejs instance on the remote server to implement this feature.   I am unable to find the source code that implements this remote agent.  I would like remote editing to work with FreeBSD.  I would be happy to help implement this functionality because it is needed for my day to day work.  I have implemented about 40 FreeBSD ports over the last 20 years.

**Comment by roblourens** [comment] 2019-10-25 18:54
The remote code is not open source unfortunately. This would depend on https://github.com/microsoft/vscode/issues/74857

**Comment by dyeske** [comment] 2019-10-30 21:30
The remote code is not open source or the remote code simply hasn't been compiled on FreeBSD?  I see this issue https://github.com/microsoft/vscode/issues/74857.  Is there additional code besides electron that needs to be ported?  If it is not open source can it be fixed with a NDA?

**Comment by roblourens** [comment] 2019-10-30 22:02
It depends on https://github.com/microsoft/vscode/issues/74857, and I don't think there is any other code that would have to be ported.

**Comment by mike-pt** [comment] 2019-12-13 12:27
So does that mean the remote server also is based of electron? I assumed this was the GUI only and vscode server would be something else but, of course, since its closed source it's hard to tell.

There is this btw: https://github.com/tagattie/FreeBSD-VSCode so sounds like if the patches referred here could be added upstream maybe it would do it... or at least one step further.

**Comment by Chuxel** [comment] 2020-03-24 15:47
Hey folks - This is likely not the right place to track this topic since really this is a dupe of https://github.com/microsoft/vscode-remote-release/issues/727 and https://github.com/microsoft/vscode/issues/74857.

There currently is no official version of VS Code for FreeBSD which is why this extension does not work.  Beyond Code - OSS, a full Microsoft VS Code distribution would be needed which is tracked by https://github.com/microsoft/vscode/issues/74857.  Let's centralize in this issue since that's where the changes would have to happen.

**Closed by Chuxel** 2020-03-24 15:47 UTC
Labels: feature-request

**Comment by davidchisnall** [comment] 2020-03-25 16:51
@roblourens / @Chuxel, so the server is using the entire electron stack (not even just nodejs, which has worked on FreeBSD for a long time), but an entire web browser?  That sounds like a long-term problem.  There are a load of non-x86 places where I'd love to see the ssh remote work where a simple daemon could run easily buy expecting a full V8 stack is hard.
