### ISSUE TITLE
.git not recognized

### ISSUE THREAD

**Issue by verneriheikkila** [microsoft/vscode-remote-release#679] opened 2019-06-13 15:36 UTC
Issue Type: <b>Bug</b>

when i connect to a folder with git initialized with WSL it doenst recognize it and just says "no source control providers registered."

Extension version: 0.38.0
VS Code version: Code - Insiders 1.36.0-insider (d04b5d2eb16c156e24dbf44010c315d968694bd6, 2019-06-13T05:19:34.516Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

**Comment by egamma** [comment] 2019-06-13 15:44
Duplicate of #671

**Closed** 2019-06-13 15:44 UTC
