### ISSUE TITLE
Replace SSH (nightly) build with a pre-release extension

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#5973] opened 2021-12-01 01:01 UTC
We can replace our custom Nightly build logic with a pre-release extension. See https://github.com/microsoft/vscode/issues/138068

**Comment by tanhakabir** [comment] 2021-12-08 16:00
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6010

**Closed by tanhakabir** 2021-12-08 16:00 UTC
Labels: ssh, feature-request
