### ISSUE TITLE
vscode remote on wsl2 stops working after kernel 4.19.121 is installed

### ISSUE THREAD

**Issue by jaysonsantos** [microsoft/vscode-remote-release#3222] opened 2020-06-19 11:00 UTC
- VSCode Version: 1.46.1
- Local OS Version: windows 10 2004 - insider preview 20150.1000
- Remote OS Version:  ubuntu 20.04 4.19.121-microsoft-WSL2-standard
- Remote Extension/Connection Type: SSH/Docker/WSL wsl2

Steps to Reproduce:

1. try to connect on the remote host with wsl

When trying to connect to WSL after the new update, the node app on the remote host listens only on ipv6 but the local one tries to connect to 127.0.0.1.
A temporary solution would be using localhost as it can also be resolved as ipv6.

```
ion to get more help information.
~/p/g/devops ❯❯❯ lsof -p $(pgrep node)  
COMMAND   PID   USER   FD      TYPE DEVICE SIZE/OFF             NODE NAME
node    10721 jayson  cwd       DIR  0,107     4096 2251799813750642 /mnt/c/Users/santo/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.3
node    10721 jayson  rtd       DIR   8,48     4096                2 /
node    10721 jayson  txt       REG   8,48 43680144           278690 /home/jayson/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node
node    10721 jayson  mem       REG   8,48   294232           118619 /home/jayson/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node_modules/spdlog/build/Release/spdlog.node
node    10721 jayson  mem       REG   8,48   101320            11485 /usr/lib/x86_64-linux-gnu/libresolv-2.31.so
node    10721 jayson  mem       REG   8,48    31176            11401 /usr/lib/x86_64-linux-gnu/libnss_dns-2.31.so
node    10721 jayson  mem       REG   8,48    51832            11403 /usr/lib/x86_64-linux-gnu/libnss_files-2.31.so
node    10721 jayson  mem       REG   8,48  2029224            11116 /usr/lib/x86_64-linux-gnu/libc-2.31.so
node    10721 jayson  mem       REG   8,48   157224            11473 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
node    10721 jayson  mem       REG   8,48   104984            11226 /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
node    10721 jayson  mem       REG   8,48  1369352            11353 /usr/lib/x86_64-linux-gnu/libm-2.31.so
node    10721 jayson  mem       REG   8,48  1952928            11525 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
node    10721 jayson  mem       REG   8,48    40040            11489 /usr/lib/x86_64-linux-gnu/librt-2.31.so
node    10721 jayson  mem       REG   8,48    18816            11155 /usr/lib/x86_64-linux-gnu/libdl-2.31.so
node    10721 jayson  mem       REG   8,48   191472            11000 /usr/lib/x86_64-linux-gnu/ld-2.31.so
node    10721 jayson    0r     FIFO   0,11      0t0           132521 pipe
node    10721 jayson    1w     FIFO   0,11      0t0           132522 pipe
node    10721 jayson    2w     FIFO   0,11      0t0           132523 pipe
node    10721 jayson    3u  a_inode   0,12        0            14957 [eventpoll]
node    10721 jayson    4r     FIFO   0,11      0t0           130448 pipe
node    10721 jayson    5w     FIFO   0,11      0t0           130448 pipe
node    10721 jayson    6r     FIFO   0,11      0t0           130449 pipe
node    10721 jayson    7w     FIFO   0,11      0t0           130449 pipe
node    10721 jayson    8u  a_inode   0,12        0            14957 [eventfd]
node    10721 jayson    9u  a_inode   0,12        0            14957 [eventpoll]
node    10721 jayson   10r     FIFO   0,11      0t0           117726 pipe
node    10721 jayson   11w     FIFO   0,11      0t0           117726 pipe
node    10721 jayson   12u  a_inode   0,12        0            14957 [eventfd]
node    10721 jayson   13u  a_inode   0,12        0            14957 [eventpoll]
node    10721 jayson   14r     FIFO   0,11      0t0           130450 pipe
node    10721 jayson   15w     FIFO   0,11      0t0           130450 pipe
node    10721 jayson   16u  a_inode   0,12        0            14957 [eventfd]
node    10721 jayson   17r      CHR    1,3      0t0             1027 /dev/null
node    10721 jayson   18u     IPv6 130461      0t0              TCP *:37467 (LISTEN)
node    10721 jayson   21w      REG   8,48      308           278702 /home/jayson/.vscode-server/data/logs/20200619T115212/remoteagent.log
node    10721 jayson   22r  a_inode   0,12        0            14957 inotify
```

you can see it here as ipv6 `node    10721 jayson   18u     IPv6 130461      0t0              TCP *:37467 (LISTEN)`
and from powershell this happens:
```
curl 127.0.0.1:37467
curl: (7) Failed to connect to 127.0.0.1 port 37467: Connection refused
```
but using localhost it works

```
curl localhost:37467 -v
* Rebuilt URL to: localhost:37467/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 37467 (#0)
> GET / HTTP/1.1
> Host: localhost:37467
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain
< Date: Fri, 19 Jun 2020 10:58:47 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
<
Not found* Connection #0 to host localhost left intact
```

on vscode side, this is the message `Failed to connect to the remote extension host server (Error: connect ECONNREFUSED 127.0.0.1:37467)`

the same problem happens on vscode-insiders

**Comment by aeschli** [comment] 2020-06-22 07:56
The problem was that the new kernel version uses a different version name format (4.19.121-microsoft- WSL2- standard). The WSL - Remote extension failed to detect that its WSL2 distro, would not connect to it through the WSL2-VM IP (or, as fallback, the IPv6 localhost) but localhost (as for WSL1)

On Friday I published an update of the Remote-WSL extension (0.44.4) that improves the WSL1/WSL2 check. That fixes that the remote window can be opened again out of VSCode using the remote indicator (status bar, left) or from command or the recent menu.

The latest VSCode-insiders build has the fix for the code-insider script, so that starting out of a WSL shell should also work again.

Duplicate of #3212

**Closed by aeschli** 2020-06-22 07:56 UTC
Labels: wsl2
