### ISSUE TITLE
terminal get stuck on starting... 

### ISSUE THREAD

**Issue by kortik425** [microsoft/vscode-remote-release#2384] opened 2020-02-19 00:24 UTC
Issue Type: <b>Bug</b>
POSSIBLY RELATED TO: https://github.com/microsoft/vscode-remote-release/issues/2313
1. Open a project with VSCode,
2. Open the terminal within VSCode
3. Close VSCode
4. Open VSCode again, it should now open it with the terminal, and with the terminal stuck on "starting..." without actually starting.

Extension version: 0.42.3
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (4.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-16.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|       Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2501)|
|Memory (System)|7.86GB (4.83GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment] 2020-02-22 21:02
I'll close as a duplicate of #2313 until we learn more

**Closed by roblourens** 2020-02-22 21:02 UTC
Labels: ssh
