### ISSUE TITLE
Vscode keeps requesting password

### ISSUE THREAD

**Issue by mbakker96** [microsoft/vscode-remote-release#6485] opened 2022-03-22 11:15 UTC
When I press 'connect to host' it ask me to fill in the password. After I do that it request again my password and it keeps getting into this loop. I'm because of that unable to connect to my remote computer. I checked my password or creating a ssh session via iterm. Both are correct. 

```
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0
```

- VSCode Version: 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1)
- Local OS Version: macOS 12.2
- Remote OS Version: macOS 12.3
- Remote Extension/Connection Type: SSH
- Logs:

```
[12:13:25.078] Log Level: 2
[12:13:25.079] remote-ssh@0.76.1
[12:13:25.079] darwin x64
[12:13:25.082] SSH Resolver called for "ssh-remote+192.168.1.207", attempt 1
[12:13:25.082] "remote.SSH.useLocalServer": true
[12:13:25.083] "remote.SSH.path": undefined
[12:13:25.083] "remote.SSH.configFile": undefined
[12:13:25.083] "remote.SSH.useFlock": true
[12:13:25.083] "remote.SSH.lockfilesInTmp": false
[12:13:25.083] "remote.SSH.localServerDownload": auto
[12:13:25.083] "remote.SSH.remoteServerListenOnSocket": false
[12:13:25.083] "remote.SSH.showLoginTerminal": false
[12:13:25.084] "remote.SSH.defaultExtensions": []
[12:13:25.086] "remote.SSH.loglevel": 2
[12:13:25.086] "remote.SSH.enableDynamicForwarding": true
[12:13:25.086] "remote.SSH.enableRemoteCommand": false
[12:13:25.086] "remote.SSH.serverPickPortsFromRange": {}
[12:13:25.086] "remote.SSH.serverInstallPath": {}
[12:13:25.097] SSH Resolver called for host: 192.168.1.207
[12:13:25.097] Setting up SSH remote "192.168.1.207"
[12:13:25.101] Acquiring local install lock: /var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-remote-ssh-d60181e0-install.lock
[12:13:25.103] Looking for existing server data file at /Users/martijn/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d60181e0-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json
[12:13:25.104] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[12:13:25.108] Install and start server if needed
[12:13:25.116] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
[12:13:25.116] Checking ssh with "ssh -V"
[12:13:25.123] > OpenSSH_8.6p1, LibreSSL 2.8.3

[12:13:25.127] askpass server listening on /var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-71fe062c2f162f0368fc3de368472e6cb6e47e97.sock
[12:13:25.127] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-adf66bcc1ab384292a4817551e24f536b6c8d95a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50489","-o","ConnectTimeout=15","192.168.1.207"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/martijn/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d60181e0-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json"}
[12:13:25.127] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.ely9M7sfFr/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-71fe062c2f162f0368fc3de368472e6cb6e47e97.sock"}
[12:13:25.129] Spawned 18126
[12:13:25.274] > local-server-1> Spawned ssh, pid=18128
[12:13:25.278] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[12:13:25.315] stderr> debug1: Server host key: ssh-ed25519 SHA256:pnxzVACuufKYRhKAHtS7sGVGdcWoweGzfU6hXpoKTLw
[12:13:25.499] Got askpass request: {"request":"(martijn@192.168.1.207) Password:"}
[12:13:25.499] Showing password prompt
[12:13:25.500] Listening for interwindow password on /var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-1d31afc3af84cfb47bf9b397ff346baa571c2a69.sock
[12:13:25.500] Writing password prompt to globalState
[12:13:29.538] Got password response
[12:13:29.538] Interactor gave response: ***************
[12:13:29.539] Cleaning up other-window auth server
[12:13:29.753] stderr> Authenticated to 192.168.1.207 ([192.168.1.207]:22).
[12:13:29.785] > ready: 07967936a0a1
[12:13:29.791] > Darwin 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
[12:13:29.791] Platform: macOS
[12:13:29.794] > /bin/zsh
[12:13:29.794] Shell: zsh
[12:13:29.794] Creating bash subshell inside "zsh"
[12:13:29.802] > bash version:  3.2.57(1)-release
[12:13:29.816] > 07967936a0a1: running
[12:13:29.831] > Acquiring lock on /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
[12:13:29.833] > \ln /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.target /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
[12:13:29.836] stderr> ln: /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1: File exists
[12:13:29.837] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 07967936a0a1: start
> exitCode==24==
> listeningOn====
> osReleaseId==Darwin==
> arch==x86_64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 07967936a0a1: end
[12:13:29.837] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[12:13:29.837] Server installation process already in progress - waiting and retrying
[12:13:29.837] Terminating local server
[12:13:29.842] Local server exit: 15
[12:13:30.842] askpass server listening on /var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-33df2fa10ec80c64ed40bd2e9f1e5c0b05eacbc2.sock
[12:13:30.843] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-5829b8cc789f45323b24abfcee85a7b5bad3cdef.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50489","-o","ConnectTimeout=15","192.168.1.207"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/martijn/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d60181e0-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json"}
[12:13:30.843] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.ely9M7sfFr/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-33df2fa10ec80c64ed40bd2e9f1e5c0b05eacbc2.sock"}
[12:13:30.844] Spawned 18134
[12:13:30.973] > local-server-2> Spawned ssh, pid=18136
[12:13:30.976] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[12:13:31.012] stderr> debug1: Server host key: ssh-ed25519 SHA256:pnxzVACuufKYRhKAHtS7sGVGdcWoweGzfU6hXpoKTLw
[12:13:31.189] Got askpass request: {"request":"(martijn@192.168.1.207) Password:"}
[12:13:31.190] Showing password prompt
[12:13:31.190] Listening for interwindow password on /var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-ba0528a64b2c9d69d650830c31cfab14b173bb36.sock
[12:13:31.190] Writing password prompt to globalState
[12:13:32.643] Got password response
[12:13:32.644] Interactor gave response: ***************
[12:13:32.644] Cleaning up other-window auth server
[12:13:32.879] stderr> Authenticated to 192.168.1.207 ([192.168.1.207]:22).
[12:13:32.909] > ready: 07967936a0a1
[12:13:32.913] > Darwin 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
[12:13:32.913] Platform: macOS
[12:13:32.915] > /bin/zsh
[12:13:32.916] Shell: zsh
[12:13:32.916] Creating bash subshell inside "zsh"
[12:13:32.921] > bash version:  3.2.57(1)-release
[12:13:32.934] > 07967936a0a1: running
[12:13:32.949] > Acquiring lock on /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
[12:13:32.951] > \ln /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.target /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
[12:13:32.953] stderr> ln: /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1: File exists
[12:13:32.954] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 07967936a0a1: start
> exitCode==24==
> listeningOn====
> osReleaseId==Darwin==
> arch==x86_64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 07967936a0a1: end
[12:13:32.954] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[12:13:32.954] Server installation process already in progress - waiting and retrying
[12:13:32.954] Terminating local server
[12:13:32.958] Local server exit: 15
[12:13:33.959] askpass server listening on /var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-621a1789170a5c4c35ac912ccf11fd998d861e14.sock
[12:13:33.959] Spawning local server with {"serverId":3,"ipcHandlePath":"/var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-86d6fb547615002ab752628aae822d4bf6e30c1d.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50489","-o","ConnectTimeout=15","192.168.1.207"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/martijn/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d60181e0-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json"}
[12:13:33.959] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.ely9M7sfFr/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-621a1789170a5c4c35ac912ccf11fd998d861e14.sock"}
[12:13:33.960] Spawned 18143
[12:13:34.084] > local-server-3> Spawned ssh, pid=18145
[12:13:34.087] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[12:13:34.121] stderr> debug1: Server host key: ssh-ed25519 SHA256:pnxzVACuufKYRhKAHtS7sGVGdcWoweGzfU6hXpoKTLw
[12:13:34.312] Got askpass request: {"request":"(martijn@192.168.1.207) Password:"}
[12:13:34.312] Showing password prompt
[12:13:34.313] Listening for interwindow password on /var/folders/qs/m23gkndj17s06yjdg9hxhs7r0000gn/T/vscode-ssh-askpass-569e5f431a81d09c47e920ced65cbb9e92ca280b.sock
[12:13:34.313] Writing password prompt to globalState
```

Steps to Reproduce:

1. Connect to host in Current window
2. Fill in password 

Steps I have done:
[x] Reinstall vscode localy
[x] Ssh via terminal, works perfect
[x] Remove host from config file
[x] remove ~/.vscode

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by mbakker96** [comment] 2022-03-23 08:18
Both did something, but I'm still unable to connect to the computer. after killig the vs code server on the host I got the error message 'something went wrong'. After adding `remote.SSH.useLocalServer:false` I got the option to choose the host OS. In my case that is MacOS

```
[09:14:18.772] Log Level: 2
[09:14:18.774] remote-ssh@0.76.1
[09:14:18.774] darwin x64
[09:14:18.777] SSH Resolver called for "ssh-remote+192.168.1.207", attempt 1
[09:14:18.778] "remote.SSH.useLocalServer": false
[09:14:18.778] "remote.SSH.showLoginTerminal": false
[09:14:18.778] "remote.SSH.remotePlatform": {}
[09:14:18.778] "remote.SSH.path": undefined
[09:14:18.779] "remote.SSH.configFile": undefined
[09:14:18.779] "remote.SSH.useFlock": true
[09:14:18.779] "remote.SSH.lockfilesInTmp": false
[09:14:18.779] "remote.SSH.localServerDownload": auto
[09:14:18.779] "remote.SSH.remoteServerListenOnSocket": false
[09:14:18.779] "remote.SSH.showLoginTerminal": false
[09:14:18.782] "remote.SSH.defaultExtensions": []
[09:14:18.782] "remote.SSH.loglevel": 2
[09:14:18.782] "remote.SSH.enableDynamicForwarding": true
[09:14:18.782] "remote.SSH.enableRemoteCommand": false
[09:14:18.782] "remote.SSH.serverPickPortsFromRange": {}
[09:14:18.782] "remote.SSH.serverInstallPath": {}
[09:14:18.796] SSH Resolver called for host: 192.168.1.207
[09:14:18.796] Setting up SSH remote "192.168.1.207"
[09:14:18.804] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[09:14:18.810] Install and start server if needed
[09:14:23.656] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
[09:14:23.656] Checking ssh with "ssh -V"
[09:14:23.664] > OpenSSH_8.6p1, LibreSSL 2.8.3

[09:14:23.667] Running script with connection command: ssh -T -D 53235 -o ConnectTimeout=15 '192.168.1.207' bash
[09:14:24.308] > (martijn@192.168.1.207) Password:
[09:14:24.309] Got some output, clearing connection timeout
[09:14:24.310] Showing password prompt
[09:14:29.471] Got password response
[09:14:29.471] "install" wrote data to terminal: "***************"
[09:14:29.487] > 
[09:14:29.711] > acf83da01026: running
[09:14:29.729] > Acquiring lock on /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
> \ln /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.target /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.martijn.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
[09:14:29.737] > Found existing installation at /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1...
> Checking /Users/martijn/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log and /Users/martijn/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.pid for a running server
> Looking for server with pid: 49324
[09:14:29.791] > Starting server with command... /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/Users/martijn/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log" < /dev/null
> printenv:
>     SHELL=/bin/zsh
>     TMPDIR=/var/folders/96/z6j5mh5x4cdb3dn9fzhjc_hr0000gp/T/
>     SSH_CLIENT=10.10.10.101 53238 22
>     USER=martijn
>     VSCODE_AGENT_FOLDER=/Users/martijn/.vscode-server
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin
>     PWD=/Users/martijn
>     LANG=en_GB.UTF-8
>     SHLVL=1
>     HOME=/Users/martijn
>     LOGNAME=martijn
>     SSH_CONNECTION=10.10.10.101 53238 192.168.1.207 22
>     _=/usr/bin/printenv
[09:14:29.801] > Removing old logfile at /Users/martijn/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log
> Spawned remote server: 50593
> Waiting for server log...
[09:14:29.845] > Waiting for server log...
[09:14:29.883] > Waiting for server log...
[09:14:29.919] > Waiting for server log...
[09:14:29.960] > Waiting for server log...
[09:14:29.998] > Waiting for server log...
[09:14:30.035] > Waiting for server log...
[09:14:30.077] > Waiting for server log...
[09:14:30.112] > Waiting for server log...
[09:14:30.150] > Waiting for server log...
[09:14:30.187] > Waiting for server log...
[09:14:30.224] > Waiting for server log...
[09:14:30.261] > Waiting for server log...
[09:14:30.302] > Waiting for server log...
[09:14:30.339] > Waiting for server log...
[09:14:30.375] > Waiting for server log...
[09:14:30.416] > Waiting for server log...
[09:14:30.452] > Waiting for server log...
[09:14:30.489] > Waiting for server log...
[09:14:30.529] > Waiting for server log...
[09:14:30.569] > Waiting for server log...
[09:14:30.609] > Waiting for server log...
[09:14:30.647] > Waiting for server log...
[09:14:30.685] > Waiting for server log...
[09:14:30.726] > Waiting for server log...
[09:14:30.764] > Waiting for server log...
[09:14:30.804] > Waiting for server log...
[09:14:31.141] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:14:31.366] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:14:31.389] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:14:31.408] > Waiting for server log...
[09:14:31.438] > Waiting for server log...
[09:14:31.474] > Waiting for server log...
[09:14:31.514] > Waiting for server log...
[09:14:31.553] > Waiting for server log...
[09:14:31.588] > Waiting for server log...
[09:14:31.631] > Waiting for server log...
[09:14:31.666] > Waiting for server log...
[09:14:31.705] > Waiting for server log...
[09:14:31.749] > Waiting for server log...
[09:14:31.787] > Waiting for server log...
[09:14:31.824] > Waiting for server log...
[09:14:31.866] > Waiting for server log...
[09:14:31.907] > Waiting for server log...
[09:14:31.948] > Waiting for server log...
[09:14:31.988] > Waiting for server log...
[09:14:32.031] > Waiting for server log...
[09:14:32.070] > Waiting for server log...
[09:14:32.114] > Waiting for server log...
[09:14:32.153] > Waiting for server log...
[09:14:32.190] > Waiting for server log...
[09:14:32.232] > Waiting for server log...
[09:14:32.270] > Waiting for server log...
[09:14:32.308] > Waiting for server log...
[09:14:32.347] > Waiting for server log...
[09:14:32.389] > Waiting for server log...
[09:14:32.427] > Waiting for server log...
[09:14:32.467] > Waiting for server log...
[09:14:32.505] > Waiting for server log...
[09:14:32.540] > Waiting for server log...
[09:14:32.580] > Waiting for server log...
[09:14:32.616] > Waiting for server log...
[09:14:32.657] > Waiting for server log...
[09:14:32.697] > Waiting for server log...
[09:14:32.737] > Waiting for server log...
[09:14:32.773] > Waiting for server log...
[09:14:32.814] > Waiting for server log...
[09:14:32.853] > Waiting for server log...
[09:14:32.890] > Waiting for server log...
[09:14:32.930] > Waiting for server log...
[09:14:32.965] > Waiting for server log...
[09:14:32.998] > Waiting for server log...
[09:14:33.037] > Waiting for server log...
[09:14:33.080] > Waiting for server log...
[09:14:33.120] > Waiting for server log...
[09:14:33.164] > Waiting for server log...
[09:14:33.200] > Waiting for server log...
[09:14:33.238] > Waiting for server log...
[09:14:33.275] > Waiting for server log...
[09:14:33.314] > Waiting for server log...
[09:14:33.353] > Waiting for server log...
[09:14:33.391] > Waiting for server log...
[09:14:33.433] > Waiting for server log...
[09:14:33.474] > Waiting for server log...
[09:14:33.513] > Waiting for server log...
[09:14:33.553] > Waiting for server log...
[09:14:33.590] > Waiting for server log...
[09:14:33.631] > Waiting for server log...
[09:14:33.668] > Waiting for server log...
[09:14:33.705] > Waiting for server log...
[09:14:33.747] > Waiting for server log...
[09:14:33.787] > Waiting for server log...
[09:14:33.832] > Waiting for server log...
[09:14:33.865] > Waiting for server log...
[09:14:33.904] > Waiting for server log...
[09:14:33.946] > Waiting for server log...
[09:14:33.987] > Waiting for server log...
[09:14:34.027] > Waiting for server log...
[09:14:34.065] > Waiting for server log...
[09:14:34.104] > Waiting for server log...
[09:14:34.148] > Waiting for server log...
[09:14:34.186] > Waiting for server log...
[09:14:34.224] > Waiting for server log...
[09:14:34.267] > Waiting for server log...
[09:14:34.304] > Waiting for server log...
[09:14:34.338] > Waiting for server log...
[09:14:34.375] > Waiting for server log...
[09:14:34.414] > Waiting for server log...
[09:14:34.454] > Waiting for server log...
[09:14:34.490] > Waiting for server log...
[09:14:34.526] > Waiting for server log...
[09:14:34.564] > Waiting for server log...
[09:14:34.607] > Waiting for server log...
[09:14:34.646] > Waiting for server log...
[09:14:34.681] > Waiting for server log...
[09:14:34.714] > Waiting for server log...
[09:14:34.754] > Waiting for server log...
[09:14:34.797] > Waiting for server log...
[09:14:34.839] > Waiting for server log...
[09:14:34.871] > Waiting for server log...
[09:14:34.907] > Waiting for server log...
[09:14:34.948] > Waiting for server log...
[09:14:34.986] > Waiting for server log...
[09:14:35.022] > Waiting for server log...
[09:14:35.059] > Waiting for server log...
[09:14:35.100] > Waiting for server log...
[09:14:35.139] > Waiting for server log...
[09:14:35.175] > Waiting for server log...
[09:14:35.215] > Waiting for server log...
[09:14:35.252] > Waiting for server log...
[09:14:35.288] > Waiting for server log...
[09:14:35.333] > Waiting for server log...
[09:14:35.367] > Waiting for server log...
[09:14:35.408] > Waiting for server log...
[09:14:35.447] > Waiting for server log...
[09:14:35.481] > Waiting for server log...
[09:14:35.522] > Waiting for server log...
[09:14:35.564] > Waiting for server log...
[09:14:35.599] > Waiting for server log...
[09:14:35.638] > Waiting for server log...
[09:14:35.681] > Waiting for server log...
[09:14:35.714] > Waiting for server log...
[09:14:35.752] > Waiting for server log...
[09:14:35.792] > Waiting for server log...
[09:14:35.833] > Waiting for server log...
[09:14:35.874] > Waiting for server log...
[09:14:35.915] > Waiting for server log...
[09:14:35.957] > Waiting for server log...
[09:14:36.000] > Waiting for server log...
[09:14:36.041] > Waiting for server log...
[09:14:36.081] > Waiting for server log...
[09:14:36.122] > Waiting for server log...
[09:14:36.165] > Waiting for server log...
[09:14:36.198] > Waiting for server log...
[09:14:36.238] > Waiting for server log...
[09:14:36.273] > Waiting for server log...
[09:14:36.314] > Waiting for server log...
[09:14:36.350] > Waiting for server log...
[09:14:36.389] > Waiting for server log...
[09:14:36.426] > Waiting for server log...
[09:14:36.466] > Waiting for server log...
[09:14:36.503] > Waiting for server log...
[09:14:36.547] > Waiting for server log...
[09:14:36.581] > Waiting for server log...
[09:14:36.619] > Waiting for server log...
[09:14:36.656] > Waiting for server log...
[09:14:36.697] > Waiting for server log...
[09:14:36.732] > Waiting for server log...
[09:14:36.771] > Waiting for server log...
[09:14:36.812] > Waiting for server log...
[09:14:36.848] > Waiting for server log...
[09:14:36.885] > Waiting for server log...
[09:14:36.927] > Waiting for server log...
[09:14:36.965] > Waiting for server log...
[09:14:37.004] > Waiting for server log...
[09:14:37.047] > Waiting for server log...
[09:14:37.089] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log at /Users/martijn/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log >>>
[09:14:37.104] > /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server: line 10: python: command not found
> usage: dirname string [...]
> usage: dirname string [...]
> /Users/martijn/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server: line 13: /node: No such file or directory
> <<< End of server log
> acf83da01026: start
> exitCode==32==
> listeningOn====
> osReleaseId==Darwin==
> arch==x86_64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==8000==
> acf83da01026: end
[09:14:37.105] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==8000==

[09:14:37.107] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:585975)
	at p (/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:579824)
	at Object.t.handleInstallOutput (/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:583109)
	at Object.t.tryInstall (/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:681846)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:644486
	at async Object.t.withShowDetailsEvent (/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:647831)
	at async Object.t.resolve (/Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:645565)
	at async /Users/martijn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:722872
[09:14:37.114] ------




[09:14:38.327] "install" terminal command done
[09:14:38.329] Install terminal quit with output: 
```

**Comment by tanhakabir** [comment] 2022-03-23 22:03
Looks like a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6442

**Closed by tanhakabir** 2022-03-23 22:03 UTC
Labels: ssh, needs more info

**Comment by mbakker96** [comment] 2022-03-24 06:10
my MacBook indeed says that he can't find commando python, but python3 works. Will try to fix it today and if fixed than I will close this issue.
