### ISSUE TITLE
Alpine container support broken in latest VS Code Insiders

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#983] opened 2019-07-16 20:38 UTC
- VSCode Version: 1.37.0-insider 
- Commit: 8e0f348413f4f616c23a88ae30030efa85811973
- Local OS Version: Windows and macOS
- Remote OS Version: Alpine 3.9, 3.10
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Open a folder with the following `.devcontainer.json` in it in VS Code Containers

    ```json
    {
        "image": "alpine"
    }
    ```

**Expected:** Container starts
**Actual:** Container fails looking for a library in the `spdlog` node.js library.

Full log:
```
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.9.3
PRETTY_NAME="Alpine Linux v3.9"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
Run: docker cp c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616:/etc/passwd -
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 test -d /root/.vscode-server-insiders
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.copyGitConfigMarker' ; } 2> /dev/null
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 test -d /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973
Installing VS Code Server for commit 8e0f348413f4f616c23a88ae30030efa85811973
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 /bin/sh -c apk info | grep -e '^libstdc++$' || apk update && apk add libstdc++
libstdc++
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
OK: 325 MiB in 49 packages
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 mkdir -p /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973_1563308740543
Run: docker cp C:\Users\clantz\AppData\Local\Temp\vsch\8e0f348413f4f616c23a88ae30030efa85811973\vscode-server-linux-alpine.tar.gz c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616:/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973_1563308740543
Run: docker exec -w /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973_1563308740543 c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 tar --no-same-owner -xf vscode-server-linux-alpine.tar.gz --strip-components 1
Run: docker exec -w /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973_1563308740543 c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 rm vscode-server-linux-alpine.tar.gz
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 mv -n /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973_1563308740543 /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 test -d /root/.vscode-server-insiders/extensions
Run: docker exec c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
Run: docker exec -w / -u 0 c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 /bin/sh -c command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { command -v code-insiders >/dev/null 2>&1 && code-insiders --gitCredential $*; }; f' || true
Run: docker exec -w /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973 -e SHELL=/bin/ash -e VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/server.sh --disable-user-env-probe --port 0


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


{ errorCode: 'load',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ],
  detail:
   Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/node_modules/spdlog/build/Release/spdlog.node)
       at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at Module.patchedRequire [as require] (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
       at require (internal/modules/cjs/helpers.js:20:18)
       at bindings (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/node_modules/bindings/bindings.js:112:48)
       at Object.<anonymous> (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/node_modules/spdlog/index.js:3:35)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at Module.patchedRequire [as require] (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
       at require (internal/modules/cjs/helpers.js:20:18)
       at t.load (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/out/vs/loader.js:16:247)
       at e.load (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/out/vs/loader.js:13:587)
       at i (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/out/vs/loader.js:28:371)
       at Object.errorback (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/out/vs/loader.js:28:492)
       at e.triggerErrorback (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/out/vs/loader.js:13:952)
       at /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/out/vs/loader.js:13:657
       at ReadFileContext.callback (/root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973/out/vs/loader.js:16:617)
       at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) }
IP Address: 172.17.0.5
webview server listening on 41733
Extension host agent listening on 37515
Run: docker exec -w /root/.vscode-server-insiders/bin/8e0f348413f4f616c23a88ae30030efa85811973 c5d4ef8b16f2d6005791d3ca13c96ff5b3e993443c1e525254dbd6687f5bd616 /bin/sh -c echo 37515 >.devport
Segmentation fault
```

// cc: @kieferrm @aeschli

**Comment by Chuxel** [comment] 2019-07-16 21:38
Pretty sure this means that there's a regression in `spdlog` that means the Alpine (and possibly ARM) binaries are missing.

**Comment by aeschli** [comment] 2019-07-17 08:02
I ran into the same issue when trying to get WSL Remote running on Alpine.

**Comment by aeschli** [comment] 2019-07-17 10:57
Version: 1.37.0-insider Commit: 9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904 Date: 2019-07-09T05:25:53.187Z: No spdlog warning but still the Segmentation fault

**Comment by aeschli** [comment] 2019-07-17 11:40
Same with 1.36 builds: 
Version: 1.36.0-insider Commit: 0f3794b38477eea13fb47fbe15a42798e6129338 Date: 2019-07-03
Version: 1.36.0-insider: Commit: e80dd4f217db6e230d311a87fdf4276f740f6445, Date: 2019-06-25

No spdlog warning but failing with the Segmentation fault when the server connects.

I'm on Ubuntu 18.04.2 LTS,  Docker version 18.09.7, build 2d0083d
Maybe Alpine never worked on Linux? 
Also reported with https://github.com/microsoft/vscode-remote-release/issues/799

**Comment by Chuxel** [comment] 2019-07-17 14:42
@aeschli Did you install Docker using the official instructions?  (They don't tell you to use Ubuntu's version.)

**Comment by Chuxel** [comment] 2019-07-17 14:58
@aeschli This version works on windows:

Version: 1.36.0-insider (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T08:00:29.662Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment] 2019-07-17 15:31
I followed the official instructions, my version is (still) Docker version 18.09.7, build 2d0083d

With Version: Version: 1.37.0-insider Commit: 3456ef3aaaf6132eada921a53e8291b928c4d530 Date: 2019-07-12
- segmentation fault when running `"image": "alpine"`
- all good when running `"image": "node:alpine"`

With Version: 1.37.0-insider, Commit: 8fa811108f0f0524c473020ef57b6620f6c201e1, Date: 2019-07-12
- spdlog errors & segmentation fault when running `"image": "alpine"`
- spdlog errors & segmentation fault when running `"image": "node:alpine"`

It seems we have 2 separate issues:
- general issue with running `"image": "alpine"` on Ubuntu
- regression since 8fa811108f0f0524c473020ef57b6620f6c201e1

I will look into the regression with @joaomoreno tomorrow.

**Comment by Chuxel** [comment] 2019-07-17 15:33
@aeschli Yeah it sounds like it - strange. I typically switch between macOS and Windows locally and mainly use Ubuntu in VMs, so I hadn't seen that.  Not sure if Christof repro'd it before vacation.

**Comment by joaomoreno** [comment] 2019-07-18 09:11
This was a build refactoring consequence. Fixed by https://github.com/microsoft/vscode/commit/b43e1aba594ca05ab53fdafed50dd18f2eff25a4

**Closed by joaomoreno** 2019-07-18 09:11 UTC
Labels: bug, containers

**Comment by Chuxel** [comment] 2019-07-18 17:58
Confirmed working in today's insider's build on Windows.

Version: 1.37.0-insider (user setup)
Commit: fd5985489982fe14381dd56e6f0b29c53d5f991b
Date: 2019-07-18T14:11:10.247Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

@joaomoreno Would it make sense to reopen #799 given the Alpine 3.10 issue on Linux?

**Comment by aeschli** [comment] 2019-07-25 09:52
I created https://github.com/microsoft/vscode-remote-release/issues/1026 for the Alpine 3.10 issue on Linux
