### ISSUE TITLE
workspaceFolder no longer accepts VS Code workspace files

### ISSUE THREAD

**Issue by AngellusMortis** [microsoft/vscode-remote-release#4239] opened 2020-12-28 18:20 UTC
- VSCode Version: 1.52.1
- Local OS Version: Arch Linux
- Remote OS Version: Debian Stretch I think? (remote OS should not matter, but it was the official Python 2.7 Docker container)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Set `workspaceFolder` to the path for a VS Code `.code-workspace` file.
2. Add a `postCreateCommand`, `postAttachCommand`, or `postStartCommand`

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

This started happening only with a newer version of VS Code (1.52 most likely, I cannot remember what version I was on before, but I usually update in a somewhat timely manner). Previously, if `workspaceFolder` was actually set to `.code-workspace` file, it would open the workspace after attaching VS Code, now it just does not work. It looks like it is because it is setting the `-w` option (working dir) on docker so now it actually _must_ be a real directory. This was a nice hack to allow for multi-root workspaces inside of Docker containers. The only two folders we had in our workspace was the main app (`/app`) and a extra Docker Compose only mount for the Docker file (`/docker`) so the workspace was only to give easy access to the Docker files.

**Comment by chrmarti** [comment] 2021-01-04 16:22
That must have worked by chance. We want to investigate opening a workspace using a devcontainer.json property in https://github.com/microsoft/vscode-remote-release/issues/3665.

What should work: Place a `.devcontainer/devcontainer.json` in the folder where the `.code-workspace` file is stored and make sure all workspace folders are contained in that same folder (possibly in subfolders). This only works if the `.code-workspace` file exists on the local filesystem.

Closing as duplicate of the above issue.

**Closed by chrmarti** 2021-01-04 16:22 UTC
Labels: containers
