### ISSUE TITLE
`Workspace does not exist` when opening tunnel on root

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#8212] opened 2023-03-16 14:30 UTC
Ubuntu 22.10

- use the cli to start tunnel service `code-insiders tunnel service install`
- service is installed and prompts: `Open this link in your browser https://insiders.vscode.dev/tunnel/aeschli-VirtualBox`

Open this link. vscode.dev opens with error dialog
![image](https://user-images.githubusercontent.com/6461412/225648892-5c111076-98c9-419a-adfa-a575cfcff3f0.png)

Open the link with a slash at the end (`https://insiders.vscode.dev/tunnel/aeschli-VirtualBox/`)

Now it works and vscode.dev shows the content of the root file system

I suspect the error is in the remote-tunnel extension when creating the workspace path out of the browser location

**Comment by aeschli** [comment] 2023-03-16 14:36
Very likely related:
- on the `Workspace does not exist` dialog, press `cancel`
- press the `Open Folder` dialog
- select a folder from the folder picker
- the window reloads but again shows the same error dialog

**Comment by connor4312** [comment] 2023-03-16 18:33
This was caused by https://github.com/microsoft/vscode-dev/pull/840, which removed the ability of router extensions to open empty workspaces. It affects tunnels on vscode.dev, blocking flow of connecting to a new remote tunnel via the Remote Explorer, since then you land on a broken workspace and also can't open folders.

@joaomoreno it looks like the underlying code path that PR was fixing something that the "profile" route already fixed by explicitly returning a workspace in `tmp://` -- should the PR just be reverted?

**Comment by joaomoreno** [comment] 2023-03-20 13:47
@connor4312 The problem is that the issue the PR fixed can always come back from any other route. The PR fixes it for good, according to @bpasero's summary: https://github.com/microsoft/vscode-dev/issues/812#issuecomment-1406198813

Why is this workspace "broken"? Can't the feature work on these `tmp:` workspaces?

**Comment by connor4312** [comment] 2023-03-20 15:45
We want an empty workspace still connected to the remote so that "Open Folder" and other management actions work. It seems like `tmp` doesn't get resolved in remote workspaces. Fixing that would could also work, though I didn't dive into why that was. It seemed like setting the workspace to `undefined` was the more "proper" way to signify an empty workspace.

**Comment by connor4312** [comment] 2023-03-21 19:01
The issue is that vscode has a [`RemoteInvalidWorkspaceDetector`](https://github.com/microsoft/vscode/blob/a9ba2e73ecbd3f7d5124e425950bc94bf2f157be/src/vs/workbench/contrib/remote/common/remote.contribution.ts#L82) which is generating this error for remote workspaces. With the PR, VS Code will always try to open `tmp:///default.code-workspace`. This doesn't actually exist, but no error is shown, at least in most cases

![image](https://user-images.githubusercontent.com/2230985/226713749-c1dac918-8c07-4ced-a7b9-469a4383c921.png)

So from this we should probably either:

- Have a way for router extensions to properly return empty workspaces (still my preferred route), or
- Add some special casing in the `RemoteInvalidWorkspaceDetector` to allow things in the `tmp` workspace

**Closed** 2023-03-21 22:13 UTC
Labels: bug, important
