### ISSUE TITLE
Issue attaching VS code to a docker container

### ISSUE THREAD

**Issue by altjx** [microsoft/vscode-remote-release#4893] opened 2021-04-16 03:33 UTC
- VSCode Version: 1.55.2
- Local OS Version: macOS Big Sur 11.2.3
- Remote OS Version: Amazon Linux 2
- Remote Extension/Connection Type: SSH/Docker/WSL: Remote Containers v0.166.1 / connecting via SSH with a docker container on the remote server
- Logs: Error running command remote-containers.attachToRunningContainerFromViewlet: Running the contributed command: 'remote-containers.attachToRunningContainerFromViewlet' failed.. This is likely caused by the extension that contributes remote-containers.attachToRunningContainerFromViewlet.

Steps to Reproduce:

1. Open VS Code 
2. Connect to a remote host via SSH
3. In the "Docker" extension, find the docker container that's currently running
4. Right click the docker container -> Attach Visual Studio Code
5. The little prompt comes up (as if you're hitting cmd + shift + p) and quickly goes away, followed by the error

I haven't been able to reproduce this on my Ubuntu 20.04 server, so I'm wondering if this is actually something related to the OS. The error message indicates that this is likely caused by the extension, howeverr.

[Here's another issue ](https://github.com/microsoft/vscode-remote-release/issues/1831)that seems to be related to mine, but theirs was closed since it didn't provide enough information

**Comment by chrmarti** [comment] 2021-04-16 06:40
Could you append the log? (`F1` > `Remote-Containers: Show Log`)

**Comment by altjx** [comment] 2021-04-16 12:55
Ahh, I see @chrmarti. I'm getting this:

```
[3 ms] Remote-Containers 0.166.1 in VS Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d).
[11492 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[11600 ms] 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[11601 ms] Start: Run: docker ps -q
[34237949 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[34238073 ms] 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[34238075 ms] Start: Run: docker ps -q
```

I'm actually root on the server and docker is indeed running. Any thoughts?

**Comment by altjx** [comment] 2021-04-16 18:47
I was able to get this working. I had to open a folder on the remote server, and _then_ attach VS code to a container. I guess the extension was trying to use docker locally until I connected to a remote folder.

**Comment by abidrahmank** [comment] 2021-04-17 08:45
Hi @altjx I ran into the same issue. My log shows following:

```
[299706 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[299751 ms] findLocalWindowsExecutable: Exectuable 'docker' not found on PATH 'C:\Program Files (x86)\Common File........'
```
VSCode : 1.55.2
My local OS : Windows 10
My remote OS : Ubuntu 18.04

What do you mean by `I had to open a folder on the remote server, and then attach VS code to a container` ? 
I opened a directory in remote server and I still see the same error. Let me know if I am missing something here.

**Comment by chrmarti** [comment] 2021-04-22 09:05
@abidrahmank Try `File` > `Open Folder` in the Remote-SSH window and then retry attaching to the container.

This is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4913. Continuing tracking there.

**Closed by chrmarti** 2021-04-22 09:05 UTC
Labels: containers, needs-more-info
