### ISSUE TITLE
Check defaultExtensions on every connection

### ISSUE THREAD

**Issue by Morgy93** [microsoft/vscode-remote-release#855] opened 2019-06-27 16:48 UTC
Probably somehow related to #463 or maybe my feature request is their problem :b 
ANYWAY

I'd like have `remote.SSH.defaultExtensions` checked on every connection, not once during server install on the remote host.

That would make it possible for me to use my default extensions and my co-workers to have their own default extensions installed if they connect to the same remote host.

**Comment by roblourens** [comment] 2019-10-16 04:53
Dupe of https://github.com/microsoft/vscode-remote-release/issues/463

**Closed by roblourens** 2019-10-16 04:53 UTC
Labels: feature-request, ssh
