### ISSUE TITLE
Remote SSH doesn't start when default shell of target is PowerShell (non-Windows)

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-release#5051] opened 2021-05-13 16:03 UTC
- VSCode Version: 1.56.2
- Local OS Version: macOS
- Remote OS Version: macOS
- Remote Extension/Connection Type: SSH
**- Shell: PowerShell**
- Logs:

```
[08:59:43.473] stderr> Authenticated to localhost ([::1]:22).
[08:59:43.852] > PowerShell 7.2.0-daily20210513.1
> Copyright (c) Microsoft Corporation.
> 
> https://aka.ms/powershell
> Type 'help' to get help.
[08:59:44.556] >  tyleonha ~ 
> ❯❯❯
[08:59:44.582] > echo 'ready: 8a2397a12c32'
[08:59:44.588] > ready: 8a2397a12c32
[08:59:44.617] >  tyleonha ~ 
> ❯❯❯
[08:59:44.618] > uname -rsv
[08:59:44.635] > Darwin 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64
[08:59:44.635] Platform: macOS
[08:59:44.655] >  tyleonha ~ 
> ❯❯❯
[08:59:44.656] > bash
[08:59:44.672] stderr> /bin/bash: line 1: syntax error near unexpected token `then'
[08:59:44.672] stderr> /bin/bash: line 1: `then'
[08:59:44.694] >  USAGE  tyleonha ~ 
> ❯❯❯
[08:59:44.695] > function mainScriptWrapper {
[08:59:44.696] > >> 
[08:59:44.697] > >> 
[08:59:44.698] > echo "8a2397a12c32: running"
> >> 
[08:59:44.698] > 
[08:59:44.698] > >> 
[08:59:44.699] > #
> >> 
[08:59:44.700] > # Setup
> >> 
[08:59:44.700] > #
> >> 
[08:59:44.701] > VSC_TMP="${XDG_RUNTIME_DIR:-`echo /tmp`
[08:59:44.701] > }"
> >> 
[08:59:44.702] > COMMIT_ID="054a9295330880ed74ceaedda236253b4f39a335"
> >> 
[08:59:44.702] > EXTENSIONS=""
> >> 
[08:59:44.714] > TELEMETRY=""
> >> 
[08:59:44.714] > export VSCODE_AGENT_FOLDER=$HOME/.vscode-server
> >> 
[08:59:44.715] > ALLOW_CLIENT_DOWNLOAD="1"
> >> 
[08:59:44.715] > FORCE_CLIENT_DOWNLOAD="0"
> >> 
[08:59:44.716] > now=`date +%s`
> >> 
[08:59:44.717] > SERVER_LISTEN_FLAG=--port=0
> >> 
[08:59:44.717] > UNPACK_RESULT=
> >> 
[08:59:44.718] > DID_LOCAL_DOWN
[08:59:44.718] > LOAD=0
> >> 
[08:59:44.719] > DOWNLOAD_T
[08:59:44.719] > IME=
> >> 
[08:59:44.719] > INSTALL_TIME=
> >> 
[08:59:44.720] > EXT_INSTALL_TIME=
> >> 
[08:59:44.720] > SERVER_STA
[08:59:44.721] > RT_TIME=
> >> 
[08:59:44.721] > CONNECTION_TOKEN=
> >> 
[08:59:44.722] > 
[08:59:44.722] > >> 
[08:59:44.723] > VSCH_DIR="
[08:59:44.723] > $VSCODE_AGENT_FOLDER/bin/$COMMIT_ID"
> >> 
[08:59:44.723] > VSCH_LOG
[08:59:44.723] > FILE="$VSCODE_AGENT_FOLDER/.$COMMIT_ID.log"
> >> 
[08:59:44.724] > VSCH_PIDF
[08:59:44.724] > ILE="$VSCODE_AGENT_FOLDER/.$COMMIT_ID.pid"
> >> 
[08:59:44.724] > VSCH_TOKENFILE="$VSCO
[08:59:44.724] > DE_AGENT_FOLDER/.$COMMIT_ID.token"
> >> 
[08:59:44.725] > 
[08:59:44.725] > >> 
[08:59:44.726] > fail_with_exitcode() {
> >> 
[08:59:44.727] > 	echo "8a2397a12c32: start"
> >> 
[08:59:44.727] > 	echo "exitCode==$1=="
> >> 
[08:59:44.728] > 	echo_common_results
> >> 
[08:59:44.729] > 	echo "8a2397a12c32: end"
> >> 
[08:59:44.729] Received install output: "
>> 	echo "exitCode==$1=="
>> 	echo_common_results
>> 	echo "
[08:59:44.730] Failed to parse remote port from server output
[08:59:44.730] Terminating local server
[08:59:44.732] Resolver error: Error: 
	at Function.Create (/Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:64641)
	at Object.t.handleInstallOutput (/Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:63284)
	at Object.e [as tryInstallWithLocalServer] (/Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:294035
	at async Object.t.withShowDetailsEvent (/Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:405329)
	at async /Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384890
	at async E (/Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (/Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384517)
	at async Object.t.resolve (/Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:295505)
	at async /Users/tyleonha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:127:110530
[08:59:44.736] ------
```

Steps to Reproduce:

1. Use PowerShell as your default shell on macOS
2. Use Remote - SSH where the server address is just localhost

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by TylerLeonhardt** [comment] 2021-05-13 16:05
if I `chsh -s /bin/zsh` everything works fine.

**Comment by roblourens** [comment] 2021-05-13 16:11
Why did it complain about bash syntax _before_ I sent over the bash script?

```
[08:59:44.656] > bash
[08:59:44.672] stderr> /bin/bash: line 1: syntax error near unexpected token `then'
[08:59:44.672] stderr> /bin/bash: line 1: `then'
```

everything after that is ok, then it looks like it just gives up at some random point.

It will probably work if you set `"remote.SSH.useLocalServer": false`

**Comment by TylerLeonhardt** [comment] 2021-05-13 16:31
Yes that did the trick! Could it be a quoting issue?

**Comment by roblourens** [comment] 2021-05-13 17:21
It probably has something to do with powershell not properly passing through stdin to the bash subshell. Another shell, I think csh has a similar issue.

**Comment by roblourens** [comment] 2021-05-13 17:21
I'll close it as a dupe of https://github.com/microsoft/vscode-remote-release/issues/2509, I think it is the same class of issue. Thanks for the additional data point.

**Closed by roblourens** 2021-05-13 17:21 UTC
Labels: bug
