### ISSUE TITLE
Programmatically launched ShellExecution tasks use UI-side shell executable instead of remote shell executable

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-remote-release#5157] opened 2021-06-09 16:52 UTC
- VSCode Version: 1.56.2
- Local OS Version: Windows 10 Enterprise 21H1 build 19043.10052
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/WSL Remote-SSH 0.65.4, Docker extension 1.13.0

Steps to Reproduce: see [Docker extension issue 2945](https://github.com/microsoft/vscode-docker/issues/2945) for repro steps.

Does this issue occur when you try this locally?: No, this is remote-specific
Does this issue occur when you try this locally and all extensions are disabled?: n/a

### More Info
The "pull image" command, implemented by Docker extension, runs `docker pull` command in a shell task. [The relevant code is here](https://github.com/microsoft/vscode-docker/blob/main/src/utils/executeAsTask.ts#L20). 

The problem is, when using Remote-SSH connection to a remote host, this task attempts to use the UI-side shell executable (`cmd.exe`), as opposed to what the `SHELL` variable points to on the remote host (`/bin/bash`).

**Comment by bmartin** [comment] 2021-06-10 19:04
I'm connecting from Windows to linux and after upgrading VSCode today I see failure like:

The terminal process failed to launch: Path to shell executable "bash" is not a file of a symlink.

My Debian linux remote certainly supports bash, but I do not have bash on the path on Windows locally, so this is consistent.

**Comment by bmartin** [comment] 2021-06-10 19:09
BTW, I was able to work around this by setting this in my workspace settings.json file:

```json
"terminal.integrated.automationShell.linux": "/bin/bash"
```
That was not needed before VSCode 1.57.0.

**Comment by alexr00** [comment] 2021-06-14 12:15
@karolz-ms and/or @bmartin can you share any `task` and `terminal` settings you have set? I'm not able to reproduce this issue.

**Comment by karolz-ms** [comment] 2021-06-14 21:15
I cannot reproduce this anymore with VS Code 1.57.0 either. 

@bmartin can you confirm you are still seeing the error, and that it is related to Docker operations (push/pull image etc)?

**Comment by alexr00** [comment] 2021-06-15 12:16
@karolz-ms thanks for confirming. I'm going to close this issue, but if @bmartin says otherwise we can re-open.

**Closed by alexr00** 2021-06-15 12:16 UTC
Labels: needs-more-info, tasks

**Comment by bmartin** [comment] 2021-06-15 16:35
Seems like there is no way to add a comment after it is closed.

**Comment by bmartin** [comment] 2021-06-15 16:54
I imagine this email is going into a blackhole. If anybody sees this, the
issue is definitely still happening. I'll open a new bug report because I
can no longer comment on the existing issue.

**Comment by karolz-ms** [comment] 2021-06-15 16:59
@bmartin I can see your comments about the issue still reproducing, and so is probably @alexr00, but I think opening a new issue is a good idea, since I have not seen the error you quoted, and also it is not clear to me what are the repro steps for the error you are seeing. So please make sure to include those--thank you!
