### ISSUE TITLE
Remote-SSH Plugins whether support unix system?

### ISSUE THREAD

**Issue by Allen1218** [microsoft/vscode-remote-release#4973] opened 2021-04-28 07:08 UTC
##  Remote-SSH Plugins whether support unix system?
For example : HP Itanium?

Because, I use remote-SSH plugin to connect Unix system with WIN10, connection fail.
Could you reply me?

 thanks!

**Comment by bamurtaugh** [comment] 2021-04-29 19:25
Closing as a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4976.

**Closed by bamurtaugh** 2021-04-29 19:25 UTC
Labels: ssh
