### ISSUE TITLE
WSL: Defaults to using /bin/bash

### ISSUE THREAD

**Issue by KSiig** [microsoft/vscode-remote-release#718] opened 2019-06-17 16:15 UTC
- Remote Extension/Connection Type: SSH/Docker/**_WSL_**

As the title says, the extension defaults to using /bin/bash to start the server in WSL. This is fine most of the time, since many people use Ubuntu. However if someone uses Alpine, which doesn't have bash installed by default, the extension will end up timing out. Using /bin/sh should solve this issue.

**Comment by redblue9771** [comment] 2019-06-17 17:56
I have the same problem. I have been using Alpine before the remote development mode, because it is small and free to install in other partitions.  Now I have to use Ubuntu as WSL.

**Comment by redblue9771** [comment] 2019-06-18 05:54
#54 VS Code seems to be ready to support this feature.

**Comment by egamma** [comment] 2019-06-19 06:35
Depends on Alpine support of the VS Code Server.

**Comment by aeschli** [comment] 2019-07-10 20:09
duplicate of #952

**Closed by aeschli** 2019-07-10 20:09 UTC
Labels: feature-request
