### ISSUE TITLE
dev container is not working

### ISSUE THREAD

**Issue by Alexander770** [microsoft/vscode-remote-release#5490] opened 2021-08-23 10:42 UTC
I am trying to dev inside container based on attached zip file.
[python-spark-pi.zip](https://github.com/microsoft/vscode-remote-release/files/7031164/python-spark-pi.zip)
VScode is not stable. It does not work although few times I did succeed to run **pi.py** file without changing the code
Reported Exception: Java gateway process exited before sending its port number

I do succeed to run the code inside container when I do it straight without VScode.

Thanks for help
Alexander
alex.hazan@gmail.com

**Comment by chrmarti** [comment] 2021-08-23 11:50
This issue seems to be specific to the tools you are using. Please check https://github.com/jupyter/jupyter/issues/248 or similar issues to see if these help.

**Comment by Alexander770** [comment] 2021-08-23 12:45
Thanks

I noticed that times it worked the command prompt in container CLI was
different. It included workspace name and some weird numbers. The prompt is
sh-5.0$ and it does not work. What should I check to solve it?

**Comment by chrmarti** [comment] 2021-08-24 14:44
jupyter/jupyter#248 suggests that JAVA_HOME might not be set. Closing as the issue seems to originate from other tools than the Remote-Containers extension.

**Closed by chrmarti** 2021-08-24 14:44 UTC
Labels: containers, needs more info

**Comment by Alexander770** [comment] 2021-08-24 20:26
Is it possible that if I specify containerUser=root inside
devcontainer.json the problem is solved?

**Comment by chrmarti** [comment] 2021-08-25 09:04
Yes, the root account might have other environment variables set (if these are the root cause).
