### ISSUE TITLE
connect ECONNREFUSED ::1:35117

### ISSUE THREAD

**Issue by yixiangfeng** [microsoft/vscode-remote-release#2082] opened 2019-12-23 02:03 UTC
Issue Type: <b>Bug</b>

connect ECONNREFUSED ::1:35117)

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.19536
Fetching remote diagnostics for 'WSL: Ubuntu' failed: connect ECONNREFUSED ::1:35117

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.85GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/c/Users/yikca --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: connect ECONNREFUSED ::1:35117
</details>Extensions: none

**Comment by AdamVig** [comment] 2019-12-23 21:31
Possible duplicate of #2060.

**Comment by es50678** [comment] 2019-12-24 02:05
reverting to 10.0.19041.1 worked for me.

```
windows settings -> windows update -> pause updates(or turn off fast ring) 
-> recovery -> Go back to the previous version of windows 10
```

https://github.com/microsoft/vscode-remote-release/issues/2060 links to https://github.com/microsoft/WSL/issues/4769 where I found the suggestion to update. So it seems this is an issue with windows insider preview build Windows 10 Pro Insider Preview Build 19536.rs_prerelease.191211-1446 (WSL 2 Enabled). The issue has `fixinbound` tagged so hopefully it won't be too long before an update is released

**Comment by cmeiklejohn** [comment] 2019-12-27 23:12
Confirm, just started experiencing this on build 19536.rs_prerelease.191211-1446 today.

**Comment by cmeiklejohn** [comment] 2019-12-27 23:37
Also reverted.

**Comment by dgmdevelopment** [comment] 2019-12-28 17:07
Oddly, reverting to 19041.1 didn't seem to work for me, but found temporary solution of editing the hosts file and putting in the IP address of your WSL2 distro. 
```
    #127.0.0.1 localhost
    YOUR IP HERE localhost
```
If your VM or computer restarts the IP will change of course.  Then you will have to edit again.  I can live with this until fix is dropped. Hope it helps!

**Comment by aeschli** [comment] 2019-12-30 12:00
dup of #2060.

**Closed by aeschli** 2019-12-30 12:00 UTC
