### ISSUE TITLE
Can't see build log in Remote-Containers

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#5614] opened 2021-09-20 16:23 UTC
- VSCode Version:

Version: 1.61.0-insider (user setup)
Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
Date: 2021-09-20T07:28:25.574Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22458

- Local OS Version: Windows 11
- Remote Extension/Connection Type: Remote-Containers

Steps to Reproduce:

1. I wanted to test the updates for https://github.com/microsoft/vscode-dev-containers/pull/1059, so I did a `git clone https://github.com/eitsupi/vscode-dev-containers.git`, opened the R folder, and reopened in dev container
2. This image takes quite some time to build, and we're discussing changes since last time after 5-10 minutes, the build would error out. I clicked on the log to track progress with the new build, but I don't see anything:

![image](https://user-images.githubusercontent.com/25310137/134037360-eadbd78b-3875-47b8-b725-1697678dae84.png)

I clicked through the various output channels, but they didn't seem relevant:

![image](https://user-images.githubusercontent.com/25310137/134037700-d553d9ff-9c2f-45d1-93fb-72ad42536579.png)

3. As I was typing this report, the image failed to build, meaning progress was made on the build, although I couldn't track it in the log

![image](https://user-images.githubusercontent.com/25310137/134037881-0c3ad20e-ef5d-46cb-94b9-a5fee53abc94.png)

I've [previously been able to see](https://github.com/microsoft/vscode-dev-containers/issues/1032#issue-987933792) output while building this definition.

**Comment by chrmarti** [comment] 2021-09-21 07:09
Duplicate of https://github.com/microsoft/vscode/issues/133442

**Closed by chrmarti** 2021-09-21 07:09 UTC
Labels: containers
