### ISSUE TITLE
Running tasks in a container produces folder not found exit code 1 

### ISSUE THREAD

**Issue by erinxocon** [microsoft/vscode-remote-release#757] opened 2019-06-20 23:43 UTC
- VSCode Version: Version 1.36.0-insider (1.36.0-insider)
- Local OS Version: macOS 10.14.5 (18F132)
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

This happened to me today when I updated to the latest VS code insiders.

Steps to Reproduce:

1. Open folder in container
2. Run any task

Does this issue occur when you try this locally?: I can't test this as I don't have any of the deps installed for this project on my mac, just docker.
Does this issue occur when you try this locally and all extensions are disabled?: N/A

Associated information:
Terminal Output from running task
```
> Executing task: cd web; ./docker/web/wait-for-postgres.sh dev python ./manage.py runserver_plus 0.0.0.0:8000 <

execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1

Press any key to close the terminal.
```

tasks.json (I use this to start the django services when I don't want debug mode)
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run Server",
            "type": "shell",
            "command": [
                "cd web;",
                "./docker/web/wait-for-postgres.sh",
                "dev",
                "python",
                "./manage.py",
                "runserver_plus 0.0.0.0:8000"
            ],
            "group": "none",
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "problemMatcher": []
        }
    ]
}
```

**Comment by erinxocon** [comment] 2019-06-20 23:46
I should also note that no matter what the command is it fails with the same error.  I tried a `python -c "import sys; print(sys.version)"`

**Comment by erinxocon** [comment] 2019-06-20 23:52
Here is a very high level overview of the root directory in docker 

```
root@de5e2f5fb2f8:/structureforge# tree --matchdirs web -L 1
web
├── Dockerfile
├── Dockerfile.stage
├── Pipfile
├── Pipfile.lock
├── README.md
├── __pycache__
├── ansible
├── backup_scripts
├── conftest.py
├── core
├── docker
├── docker-compose.yml
├── locale
├── manage.py
├── pytest.ini
├── python_vendor
├── reports
├── restore_db_from_backup.sh
├── stage
├── stations
├── structureforge
├── tasks
└── vendors
```

And my `devcontainer.json`
```
// See https://aka.ms/vscode-remote/devcontainer.json for format details.
{
    "name": "Structureforge",
    "context": "..",
    "service": "forgeweb",
    "dockerComposeFile": ["docker-compose.yml"],
    "workspaceFolder": "/structureforge",
    "extensions": ["ms-python.python"],
    "shutdownAction": "stopCompose",
    "postCreateCommand": "cd web; pipenv install --dev"
}
```

**Comment by Chuxel** [comment] 2019-06-20 23:53
@erinxocon Ok, one thing we saw before was that having the wrong shell can cause issues that sound like this.  https://github.com/microsoft/vscode-remote-release/issues/220#issuecomment-490374437

One improvement that just landed in insiders is Remote - Containers now pays attention to /etc/passwd  so you don't have to set SHELL anymore (#521).  I'm wondering if that somehow caused a problem with your container.

Does the shell script have a `#!/bin/bash` in it? Otherwise it might be using an alternate shell.

//cc: @chrmarti

**Comment by erinxocon** [comment] 2019-06-21 00:02
@Chuxel The script I'm trying to run does indeed have a shebang of `/bin/bash`

From my global settings in case it matters:

```
{ ...    
    "docker.attachShellCommand.linuxContainer": "/bin/bash",
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.rightClickBehavior": "copyPaste",
    "terminal.external.osxExec": "iTerm2.app",
    "terminal.integrated.fontFamily": "'OperatorMonoSSm Nerd Font'",
    "terminal.integrated.scrollback": 10000,
    "terminal.integrated.fontSize": 15,
...}
```

I don't have anything overriding it in the remote settings or the workspace settings.  I'm also not setting any `SHELL` command in the docker file I'm using to create the environment.

**Comment by Chuxel** [comment] 2019-06-21 00:04
>I should also note that no matter what the command is it fails with the same error. I tried a python -c "import sys; print(sys.version)" 

Yeah I missed the above statement in my response as well.  What does this give you in the container:

`cat /etc/passwd | grep root` (changing root for whatever user you are in the container itself)

**Comment by erinxocon** [comment] 2019-06-21 00:06
```
root@d7227324ec18:/structureforge# cat /etc/passwd | grep root
root:x:0:0:root:/root:/bin/bash
```

**Comment by erinxocon** [comment] 2019-06-21 00:08
I'm on my way home now, but when I get there I am going to try and repro this with a much simpler project and see if it is code or something in my settings somewhere that is changing something.  Just so weird, tasks have been working great up until the most recent update!

**Comment by Chuxel** [comment] 2019-06-21 00:14
Sounds good - you can also try to run a super simple task to see if that works. e.g.
```
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello"
        }
```

**Comment by erinxocon** [comment] 2019-06-21 02:39
@Chuxel no dice :( 

```
> Executing task: echo Hello <

execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

**Comment by Chuxel** [comment] 2019-06-21 02:50
Yeah that pretty much means VS Code can't find `/bin/bash` for some reason -- which is odd if you're able to get into a terminal.  What is the base image? `python:3`?

**Comment by chrmarti** [comment] 2019-06-21 05:30
(`"terminal.integrated.shell.linux"` does not change the task's shell.)

Try adding the following to your task:
```
            "options": {
                "shell": {
                    "executable": "/bin/bash"
                }
            },
```

**Comment by chrmarti** [comment] 2019-06-21 07:38
(I'm told that `"terminal.integrated.shell.linux"` *should* change it too, it just doesn't work for the remote setup currently, we're investigating.)

**Comment by alexr00** [comment] 2019-06-21 07:40
I can repro with the Ubuntu 18.04 & Git image from Reopen in Container.

**Comment by alexr00** [comment] 2019-06-21 07:47
@Tyriar `getDefaultShellAndArgs` is returning powershell.exe on Linux.

**Comment by alexr00** [comment] 2019-06-21 09:34
Issue is caused by two problems/changes:
- The API for checking if remote 
- Terminal uses local platform in `getDefaultShellAndArgs`

Fixes coming!

**Comment by erinxocon** [comment] 2019-06-21 17:06
Ya'll are amazing.

**Comment by cyliang** [comment] 2019-06-24 12:09
Hi, I also encounter this issue. Is there an expected time for the fix to be available in the Insider? Thanks.

**Comment by alexr00** [comment] 2019-06-24 14:35
We just merged the second part of the fix in. It will be working again in the next insiders build!

**Closed by alexr00** 2019-06-24 14:35 UTC
Labels: Tasks, containers
