### ISSUE TITLE
WSL: Problems connecting with zsh

### ISSUE THREAD

**Issue by nc-dtan** [Microsoft/vscode-remote-release#77] opened 2019-05-03 11:48 UTC
- VSCode Version: 1.34.0-insider
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Follow the guide here #63155 in order to install insider, remote development and remote wsl for the insider version of VS code
2. from cmd: `>wsl`
3. from wsl: `$ cd to/place/where/there/is/code`
4. `$ code-insiders .` (insiders opens up as expected)
5. Click on `Remote-WSL: New Window`. This hangs for about a minute and I get the error shown in the figure below.

![image](https://user-images.githubusercontent.com/35059703/57135530-ffcc7200-6da9-11e9-8c7d-01a68797b7e8.png)

Has anyone seen a similar error? Or have some suggestions to resolve this?
I already tried running cmd as administrator with the same result.

**Comment by a2975667** [comment] 2019-05-03 14:56
Not sure if its the same issue #27

**Comment by wsargent** [comment] 2019-05-04 04:26
Same: if I comment out `exec zsh` from .bashrc then VS Code comes up.

**Comment by aeschli** [comment] 2019-05-06 06:59
duplicate of #27

**Closed by aeschli** 2019-05-06 06:59 UTC
Labels: wsl
