### ISSUE TITLE
Remote SSH broken on zsh remotes

### ISSUE THREAD

**Issue by AprilArcus** [microsoft/vscode-remote-release#6377] opened 2022-02-23 20:46 UTC
VS Code Remote Workspaces (SSH) dies with a zsh parse error after successfully authenticating to a remote computer running zsh as its default shell.

This problem manifested for me on the morning of Wednesday, 2022-23-02. There were no changes to my local or remote configuration.

I ensured that my zsh setup files in both `$HOME` and `/etc` were empty before filing this issue.

- VSCode Version: 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326)
- Local OS Version: macOS 12.2.1 (arm64)
- Remote OS Version: Linux 5.15.15-1rodete1-amd64 #1 SMP Debian 5.15.15-1rodete1 (2022-01-20)
- Remote Extension/Connection Type: SSH
- Logs:

```
[12:41:49.410] Log Level: 2
[12:41:49.410] remote-ssh@0.74.0
[12:41:49.410] darwin arm64
[12:41:49.412] SSH Resolver called for "ssh-remote+cloudtop", attempt 1
[12:41:49.412] "remote.SSH.useLocalServer": true
[12:41:49.412] "remote.SSH.path": undefined
[12:41:49.412] "remote.SSH.configFile": undefined
[12:41:49.412] "remote.SSH.useFlock": true
[12:41:49.412] "remote.SSH.lockfilesInTmp": false
[12:41:49.412] "remote.SSH.localServerDownload": auto
[12:41:49.412] "remote.SSH.remoteServerListenOnSocket": false
[12:41:49.412] "remote.SSH.showLoginTerminal": false
[12:41:49.412] "remote.SSH.defaultExtensions": []
[12:41:49.412] "remote.SSH.loglevel": 2
[12:41:49.412] "remote.SSH.enableDynamicForwarding": true
[12:41:49.412] "remote.SSH.enableRemoteCommand": false
[12:41:49.413] "remote.SSH.serverPickPortsFromRange": {}
[12:41:49.413] "remote.SSH.serverInstallPath": {}
[12:41:49.418] SSH Resolver called for host: cloudtop
[12:41:49.418] Setting up SSH remote "cloudtop"
[12:41:49.419] Acquiring local install lock: /var/folders/gl/4s8nm1gd205ccq_r2s0t7rmr00p6_n/T/vscode-remote-ssh-4d914a09-install.lock
[12:41:49.420] Looking for existing server data file at /Users/ril/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4d914a09-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json
[12:41:49.420] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[12:41:49.422] Install and start server if needed
[12:41:49.423] PATH: /Users/ril/.nodenv/shims:/opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/ril/.pyenv/shims:/Users/ril/.rbenv.shims:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/opt/findutils/libexec/gnubin:/opt/homebrew/opt/gawk/libexec/gnubin:/opt/homebrew/opt/gnu-indent/libexec/gnubin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/opt/homebrew/opt/grep/libexec/gnubin:/opt/homebrew/opt/gsed/libexec/gnubin:/opt/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
[12:41:49.423] Checking ssh with "ssh -V"
[12:41:49.436] > OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021

[12:41:49.438] askpass server listening on /var/folders/gl/4s8nm1gd205ccq_r2s0t7rmr00p6_n/T/vscode-ssh-askpass-05fb00453713fd5cfe989e7bbf2bbaed39d23149.sock
[12:41:49.438] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/gl/4s8nm1gd205ccq_r2s0t7rmr00p6_n/T/vscode-ssh-askpass-ace1b1f50544f3879c0a0f6f3d1fef9d279aebb0.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52764","cloudtop"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/ril/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4d914a09-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json"}
[12:41:49.438] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.l7pPktv0Mi/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/ril/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/ril/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/gl/4s8nm1gd205ccq_r2s0t7rmr00p6_n/T/vscode-ssh-askpass-05fb00453713fd5cfe989e7bbf2bbaed39d23149.sock"}
[12:41:49.439] Spawned 18794
[12:41:49.498] > local-server-1> Spawned ssh, pid=18811
[12:41:49.510] stderr> OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
[12:41:49.789] > ready: 84f94299cb40
[12:41:49.834] > Linux 5.15.15-1rodete1-amd64 #1 SMP Debian 5.15.15-1rodete1 (2022-01-20)
[12:41:49.834] Platform: linux
[12:41:49.885] stderr> bash: line 1: syntax error near unexpected token `done'
[12:41:49.885] stderr> bash: line 1: `done'
[12:41:49.885] stderr> zsh: parse error near `}'
```

Steps to Reproduce:

1. set the default shell of your remote system to `zsh`
2. connect to your remote system.

**Comment by tanhakabir** [comment] 2022-02-23 20:58
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6341

This is fixed in the pre-release version of the Remote SSH extension and will be released in stable next week along with the VS Code release.

Please try the pre-release version of the extension!

**Closed by tanhakabir** 2022-02-23 20:58 UTC
