### ISSUE TITLE
Copies of vscode-server installed on school servers take up excessive storage and RAM

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-remote-release#6429] opened 2022-03-09 20:41 UTC
I've talked to multiple professors who have students using remote development extensions, but have mentioned that there are difficulties with it when multiple students are on the same school server. 

A professor at Duke mentioned that his students are all working on the same server/clusters, and any student who uses vscode ends up with a huge copy of vscode-server installed in their local/home directory, taking up massive disk space and RAM. It can be up to several hundred MB. It's manageable with 5-10 students, but he has larger classes of 140 students and if they were all doing this, it'd become too much resource use. 

Another prof at CMU said a similar thing happens for his students, and is unclear about how often vscode-server needs to be downloaded. He's concerned about this because often students have a disk quote per user, so he wants to understand what's being stored.

**Comment by bamurtaugh** [comment] 2022-03-09 20:51
> difficulties with it when multiple students are on the same school server
> copy of vscode-server installed in their local/home directory, taking up massive disk space and RAM

Based on the title + first line, my impression was there is concern over VS Code Server occupying space on school servers. But based on the second line, I'd love some clarity - is the server also taking up room on students' local machines? Is the space concern over both local and remote space and compute restrictions, or just one?

**Comment by zackw** [comment] 2022-03-10 00:49
Hi, I'm one of the faculty at CMU who has observed a problem with vscode-server taking up ridiculous amounts of space.

The precise problem that I know about is:  Students are using the "[remote - ssh](https://code.visualstudio.com/docs/remote/ssh)" extension to work with files stored on a university-administered Linux-based compute cluster.  Each student has a 2GiB disk quota on this cluster.  The plugin creates a directory called `.vscode-server` in each student's home directory on the cluster.  The contents of this directory grow as the students work on their assignments, apparently _without limit_, and eventually exhaust the disk quota, at which point the plugin stops working and we have to instruct the students to access the cluster via another method and delete the `.vscode-server` directory.  (Often, the students that like VSCode tend to rely on its built-in terminal window and have no idea how to use an independent ssh client, so this is lots of extra work for course staff.)

I don't know what VSCode keeps in this directory, and I don't know if it will _always_ eventually grow to consume all available space, or if some particular pattern of usage is required. It might also be relevant that the students' home directories on the cluster are hosted on [AFS](https://www.openafs.org/) (specifically the OpenAFS implementation), which has some peculiarities relative to other Unixy file systems.

I haven't been using VSCode myself but I am happy to install it and do some experiments if that would be helpful.

**Comment by zackw** [comment] 2022-03-10 00:52
@bamurtaugh As far as I know, the original bug title was more accurate -- this is a problem with excessive storage consumption on remote servers, not on the machine where VSCode is running.  I think "local/home directory" was meant to refer to the per-user home directory assigned to each student _on_ the remote.

**Comment by adhilton** [comment] 2022-03-10 18:45
I'm the one who mentioned this from Duke, and the problem is similar with what @zackw mentioned.    I teach one programming class (C++) wtih about 140 students, and a handful of students who use VSCode.  I also teach a ~45 person programming camp (Python for incoming Data Science Masters students) where the people in charge of that program would like us to switch to VSCode.   We also have some larger classes that I dont teach, including our intro Python programming + numerical methods in Python class which is in the 200-300 range per semester.

One other thing I'll note is that there is massive inefficiency in the replication of common code across all the different students' installs.   Any student who uses VSCode gets a copy of the server installed in the .vscode-server in their own home directory, which is 175MB.  That means that with multiple students, you need a lot of disk space just to hold many copies of the same code:
  45 students ->  ~8GB
  140 students -> ~25 GB
  300 students -> ~50 GB
If a student installs an extension, that gets done in their own home directory also.    To test this out, I just installed two extensions: C++, rainbow brackets  and now the install in my home directory is 351MB, so basically doubling the numbers above.  And note that this is before the storage grows with use over time that zackw described.     

At the same time, just connecting to the server (before even opening a file or installing any extensions) results in 3 "node" processes running on the server, using 70MB, 58MB, and 40MB of memory respectively (resident set size, as reported by top)---so about 168MB of memory *per student* just to get started.  With the 2 extensions installed, this increased to 119MB + 72MB + 41 MB = ~232MB. 

I then opened one existing C++ file (28 lines long, nothing fancy).  Now I see 5 node processes in top, with resident set size memory usage of 119MB + 116MB + 83MB + 47MB + 41MB  = 406MB RAM.  I also see cpptools and cpptools-srv at another 130MB + 60MB of RAM.   

That means that we are looking at about 600MB of RAM per student.  For 45 students, that works out to about 28 GB of RAM just for running VSCode.  So if I got 32GB on the server, it would be tight, and 64GB comfortable (as there is other stuff running, like the grading infrastructure).   That means for larger classes, we are looking at 128GB or 256 GB or RAM.

Fortunately, opening a second file seems to have a much smaller additional memory footprint than opening the first.   However, after opening two files, and making small changes to one of them, the disk space usage of my vscode-server directory has increased to 424MB.    So the growth over time that zack mentioned is apparently pretty fast.

**Comment by zackw** [comment] 2022-03-10 23:25
Yikes, I had no idea this was also a RAM consumption issue.  The cluster I'm talking about is big enough that it hasn't been an issue so far (10 machines * 24GB RAM each / approx 250 students per semester = ~1G per student, and they're not all trying to run VSCode at the same time) but it easily *could* become an issue with a bit of unbalanced load.

**Comment by zackw** [comment] 2022-03-10 23:47
Just to put some concrete numbers on things, one of the larger projects my students are expected to do for my course involves roughly 600kB of `.c` and `.h` files.  Most of this is test code that we give them; the amount of code they need to *write* for the assignment is on the order of 500 lines, or 12kB.

If I run `ctags` on all those files, I get a 44kB index file.

I suggest that a *reasonable* amount of space for `.vscode-server` to consume would be on the same order of magnitude as what `ctags` indexes take: no more than 7.5% or so of the size on disk of all the source code in each project visited using the editor.  Fixed-size overhead -- do I understand correctly that the plugin currently has to store in `.vscode-server` a set of programs that it uses to manipulate files on the remote host? -- should be limited to a few hundred kB at most.

But the highest priority should be to fix whatever is making the directory grow without bound.  That's got to be a plain old bug, right?

**Comment by bamurtaugh** [comment] 2022-03-11 17:57
Hi @zackw @adhilton 👋, it's great to meet you! Thank you for the deeper context, and it's really exciting to hear about the interest in and usage of VS Code in the classroom.

> do I understand correctly that the plugin currently has to store in .vscode-server a set of programs that it uses to manipulate files on the remote host

To touch on this and other questions on what the VS Code Server is: The execution of certain commands are moved to a remote server to enable your local VS Code instance to interact with remote machines. The VS Code Server is quickly installed by VS Code when you connect to a remote endpoint and can host extensions that interact directly with the remote workspace, machine, and file system.

The Server's version needs to be compatible with the version of the VS Code client, thus it must be installed and maintained by each individual install of VS Code + the Remote Development extensions.

There is greater info [in our docs](https://code.visualstudio.com/docs/remote/faq#_how-do-the-remote-development-extensions-work).

> That means that we are looking at about 600MB of RAM per student.

Thanks for sharing this and the other perf numbers.

[We generally require](https://code.visualstudio.com/docs/supporting/requirements) at least 1 GB RAM to run VS Code. As we've explored in [other remote performance discussions](https://github.com/microsoft/vscode-remote-release/issues/3728#issuecomment-700763795), VS Code is running extensions, indexing, and many other options on the remote machine in order to provide the full experience. That's what makes the experience so full featured, but it means that it requires more resources than just connecting via a file share. 

Mentioned in the [Remote-SSH readme](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh): While 1 GB RAM is required (similar to the [hardware requirements](https://code.visualstudio.com/docs/supporting/requirements) for VS Code), at least 2 GB RAM and a 2-core CPU is recommended.

> But the highest priority should be to fix whatever is making the directory grow without bound. That's got to be a plain old bug, right?

It sounded like the directory is growing as the students do more, i.e.: "The contents of this directory grow as the students work on their assignments." This would generally make sense to me, as new files, extensions, etc will be added to the remote. Would you be interested in a user setting for how much space the experience may occupy? I am not sure if that'd be feasible (cc @aeschli for thoughts), and it is also worth noting that limiting what's installed could cause the experience not to work.

Please let me know if I've missed anything, or if you have other thoughts, feedback, or questions. Thank you!

**Comment by bamurtaugh** [comment] 2022-03-11 20:04
> How often does the version change?
> I could also imagine a privileged program that could download whatever versions are requested along with extensions and make them available to users, possibly expiring + deleting old versions when unused for long enough.

To ensure we're on the same page: The VS Code Server is a component of the Remote Development extensions and is managed by a VS Code client. It's installed and updated automatically by VS Code when it connects to an endpoint. The user does not need to manage these Server updates (i.e. you may see a new version of the Server installing automatically when connecting to your remote). 

I think a command that could help is **Remote-SSH: Uninstall VS Code Server from host** ([info](https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-up-the-vs-code-server-on-the-remote)). It'll clean up everything that the Remote-SSH extension installs, killing any running Server processes and removing their code.

Also based on [this issue](https://github.com/microsoft/vscode-remote-release/issues/726) and [this comment](https://github.com/microsoft/vscode-remote-release/issues/5955#issuecomment-990136815): there may be 5 or less previous versions of vscode in the .vscode-server/bin folder. If there are more than 5 in each student's folder, that is a bug?

I don't believe there a set schedule for when the Server will / must update, but generally VS Code Stable releases monthly (with typically a couple patch releases), and there may be a new version of the Server around this cadence.

> I don't know how quickly you all purge cached state when it hasn't been used

What data would you want to be purged?

**Comment by adhilton** [comment] 2022-03-11 20:20
> To ensure we're on the same page: The VS Code Server is a component of the Remote Development extensions and is managed by a VS Code client. It's installed and updated automatically by VS Code when it connects to an endpoint. The user does not need to manage these Server updates (i.e. you may see a new version of the Server installing automatically when connecting to your remote).

Yes, I realize that is the case right now, and is part of the problem.  The current setup means that if there are 100 students using VSCode, there are 100 (identical) copies of the code installed on the server: one in each student's home directory.  That makes a lot of wasted disk space.     If there were a means for a centralized install, it would save a ton of disk space.

> What data would you want to be purged?

I don't really know what you all keep, but you had mentioned in a previous comment that it makes sense that the data storage grows over time as new files and such are added.   If students have moved on to homework 2, then any caches, indexes, etc for homework 1 can be dropped.    I sadly don't have any thing concrete to look at at the moment---when we are low on disk space the first thing I do is rm -rf /home/*/.vscode*  which I did at the end of last semester, so I don't have any actual student directories available at the moment to look at.

**Comment by bamurtaugh** [comment] 2022-03-11 21:22
> If there were a means for a centralized install, it would save a ton of disk space.

Thanks for the input! Does it seem like `remote.SSH.serverInstallPath` (context [overall here](https://github.com/microsoft/vscode-remote-release/issues/472) and [more specifically here](https://github.com/microsoft/vscode-remote-release/issues/472#issuecomment-972142006)) would help?

I'd love to know if [**Remote-SSH: Uninstall VS Code Server from Host....**](https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-up-the-vs-code-server-on-the-remote) would help at all too.

**Comment by adhilton** [comment] 2022-03-11 21:30
I believe that would need its functionality split into a couple parts (like "serverBinPath" and "serverDataPath") so that there is one place for common binaries (not writeable by typical users) and one place for per-user data (writeable/owned by the student).

**Comment by bamurtaugh** [comment] 2022-03-11 21:36
cc @tanhakabir for thoughts too

**Comment by zackw** [comment] 2022-03-12 16:50
It seems to me that we're talking about three different problems at once.

Problem 1 is that the baseline requirement for CPU and RAM on remote servers is _just too large_.  This

> 1 GB RAM is required [for the SSH plugin], at least 2 GB RAM and a 2-core CPU is recommended.

would be reasonable _on the client_, which is probably a single-user workstation of some sort, but it is absolutely not reasonable in any remote server environment I have ever encountered. This is an absolute deal-breaker for us. The compute cluster is sized to have enough CPU and RAM for all the actual project programs; we'd have to quadruple, or more, its capacity to accommodate this as well. I said earlier that we hadn't noticed problems, but the more accurate thing to say would have been that I didn't _know_ all the intermittent load problems we've been having were the SSH plugin's fault.

If you can't somehow cut this down to __less than ten megabytes of RAM__ (hard upper limit!) and __less than 5% of one core__ (average usage), I'm going to have to start _forbidding_ the use of VSCode in my class.

----

Problem 2 is that the baseline disk space requirement for the SSH plugin, on the remote, is _also_ too large.  Again, hundreds of megs of installation are reasonable for a single-user workstation but _not_ for any sort of shared storage.  As I said earlier, each student has a 2GB disk quota, so five installations of the server, at 200 MB each (what is the actual number?) would already be half of that.

This could be _mitigated_ by deduplicating shared files across users (in fact, I vaguely remember reading that AFS does this automatically, which is probably the only reason why the university's sysadmins aren't already making a stink about VSCode's storage consumption) but a feature to permit a shared installation of the binaries is only a mitigation.

I don't understand why the plugin needs to install so much stuff on the remote. Files could be accessed and updated using standard utilities that are probably already present (e.g. `rsync`). Indexing on the remote makes sense, but that should be a tiny executable (`ctags` is 148kB on disk) that doesn't need to change very often. [LSP](https://microsoft.github.io/language-server-protocol/) servers might also want to have something on the remote, but again I would expect those to be tiny and not need to change very often. Monthly updates, costing hundreds of megabytes each? Please explain what is even _in_ there, I don't get it.

----

Finally, problem 3 is that the _variable_ disk space requirement (i.e. files written as a side effect of actually _using_ the plugin to work on stuff, rather than part of the installation) seems to be proportional to _time in use_, rather than to the total size of all files edited.  I could be wrong about that; it could also be that it _is_ proportional to the amount of data being edited, but the proportionality constant is so large that it rapidly exhausts that 2GB disk quota anyway.  But that seems ridiculous, given that each student project amounts to only a couple thousand lines of code, the majority of which is tests that they probably won't even look at.  VSCode would have to be chewing up _orders of magnitude_ more space for its indexes than the actual code occupies, and it seems like that would have been noticed and fixed a long time ago.

**Comment by bamurtaugh** [comment] 2022-03-14 16:08
I appreciate both of your thoughts and insights here.

On the topic of storage: it's possible to create symlinks from the VS Code Server bin folder to a common location.

Regarding RAM: running the server on the remote host, with operations like language support and code and search indices, is surprisingly large. If IntelliSense isn't as much of a concern, a solution like rsync to the local machine would work. There are also options in VS Code like https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs. There is additional info about SSHFS and rsync and in [our docs](https://code.visualstudio.com/docs/remote/ssh#_working-with-local-tools).

**Comment by sauergeek** [comment] 2022-06-16 19:21
I'm one of the system administrators for the Tufts University Department of Computer Science.  After several professors started actively recommending their students use VSCode, we've seen all of the problems mentioned by zackw, plus one more: memory exhaustion due to server-side SSH processes not exiting.

The particular problem we've found is that the server-side processes started by the SSH plugin do not exit unless the student exits VSCode perfectly.  If they just close their laptop, or otherwise lose network connectivity to the server, the server-side processes will never exit unless killed by something outside of VSCode.  Enough of these will hang or crash the server.

As for space consumption, I recently did a survey of how much space VSCode artifacts were taking up in our user home directory volumes.  Our total storage used for non-faculty home directories is 1,656 Gb.  Of that, ~/.vscode-server (across all non-faculty accounts) takes up 512 Gb, and ~/.cache/vscode-cpptools takes up another 126 Gb, for a total of 638 Gb -- or 38% of our total home directory storage.  None of the VSCode artifacts are actual student code; it's all metadata and plugins.  The amount of space used here is ludicrous.

About half of what's in ~/.vscode-server is plugins.  I will join the bandwagon for centralizing plugins.  In particular, I think that using the centralized plugins should be the default behavior: if that central location has the plugin, it should be used by default.  (I would also like to have a switch to disable users being able to put plugins in their home directory, but the simple step of defaulting to the central install will mitigate a lot of this.)

**Comment by rhalkyard** [comment] 2022-08-23 22:55
Just chiming in that this issue doesn't only impact large shared-system use cases, either. I'd been using vscode-remote to edit configuration files and work on a small C++ project on an embedded system with tight disk-space constraints. I kept on running out of disk space, and it turns out that my ~/.vscode-server directory had grown to 2.5 gigabytes.

I can appreciate that all the interactive features of VS Code come at a price of disk space and RAM usage, but multiple gigabytes for a fairly minimal and lightly-used remote stub strikes me as frankly unreasonable.

**Comment by 9999years** [comment] 2022-08-23 23:17
Does VS Code not differentiate between “editing files on a remote machine via SSH” and “running the VS Code engine / tools on a remote machine via SSH”?

**Comment by bamurtaugh** [comment] 2022-08-23 23:41
To ensure performance, the Remote Development extensions, including Remote-SSH, will run certain VS Code extensions remotely. The architecture of these extensions involving the VS Code Server means certain tools will be run on the remote machine. I think an extension like https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs might be more suitable if you'd just prefer to access the remote files.

**Comment by hschultz1960** [comment] 2022-10-13 09:24
I am a senior systems architect at a small software firm. Our developers face the same problems as described in excellent detail in this thread, only we are not remotely accessing a university super-computer cluster, but on a much more common smaller Linux VM with finite CPU and storage resources.
As for the excessive disk storage consumption: I've learned that the VS code remote server in fact is a full-fledged Node.js engine, and all the GUID numbered directories found under the `.vscode-server` directory contains identical node binaries, modules and extensions, taking up ~200 MB disk space for each installation. Additionally, I have found, that _every day_ I start a remote session, a new installation is created on the remote server. 
To @bamurtaugh suggestion about limiting the number of persisted installs (currently fixed at 5), it begs the question: WHY do you need to keep multiple copies? What are old copies ever used for? Wouldn't it be enough to just check if updates are available, and only then download new code as needed.

**Comment by bakaleks** [comment] 2022-11-15 13:24
> The particular problem we've found is that the server-side processes started by the SSH plugin do not exit unless the student exits VSCode perfectly. If they just close their laptop, or otherwise lose network connectivity to the server, the server-side processes will never exit unless killed by something outside of VSCode. The leftover processes won't get reused, either: next the student opens their laptop or starts VSCode again, it'll start new processes. Enough leftover processes will hang or crash the server.

I'm seeing the same problem as @sauergeek - thousands of stale processes like this inside dev-container slowly eating up RAM:
```
~/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/node /tmp/vscode-remote-containers-server-6e81165b48f04d1fa0680fcca389c1765453ee23.js
```
We are using SSH + Dev Containers combo. Earlier when we were using "Local Docker" mode instead of ssh-mode the problem was not that critical because dev-container was shut down when user closed VSCode. Now however with the new and recommended SSH-based dev container setup the dev container is not shut down automatically, so those node processes are not recycled.

**Comment by james-at-klik** [comment] 2022-11-15 23:04
> thousands of stale processes like this inside dev-container slowly eating up RAM

I am experiencing something similar. The vscode-server processes consumed so many resources that they took down a website. I had to get my hosting provider to intervene.

For every file I had open with the SSH connection, it appeared to increase memory usage on the server by 200MB!

I found that disabling the "@builtin TypeScript" extension removed this extra memory burden for each file - brought it down to a flat ~100MB for any number of open files.

Hope this information helps!

**Comment by Rlee719** [comment] 2022-11-30 07:53
My ~/.vscode-server directory on the server side takes more than 200G disk space. No idea what's happening. 

![image](https://user-images.githubusercontent.com/29767467/204738497-f0d49021-2542-4968-800d-04b9ce8f04b2.png)

**Comment by karnauskas** [comment] 2023-07-19 17:30
I have a similar issue, .vscode-server directory keeps growing. My understanding is that vscode (and remote ssh plugin) is checking for a new version of vscode-server and downloading it, without doing any cleanup job – leaving old versions of vscode-server on a server, even if it's not going to be used anymore. 

```
~/.vscode-server/bin$ du -sh *
163M	660393deaaa6d1996740ff4880f1bad43768c814
162M	695af097c7bd098fbf017ce3ac85e09bbc5dda06
163M	74f6148eb9ea00507ec113ec51c489d6ffb4b771
161M	b3e4e68a0bc097f0ae7907b217c1119af9e03435
164M	e344f1f539a80912a0e9357cec841f36ce97a4e2
```

**Comment by ElliotNB** [comment] 2023-08-09 23:36
@bamurtaugh This issue was a major problem for our company as well. We had a near-incident in production where this extension contributed to rapid and unanticipated growth in disk space and memory usage. We've had to ban our engineers from using this extension to connect to our production systems.

There's simply no reason that a VSCode extension (especially one with the modest goal of editing files on a remote server) should consume this level of disk and memory resources. As others have pointed out above, this extension creates five copies of a large node project in the `.vscode-server/bin` folder -- over 8,000 individual files. From my perspective, that is complete madness.

**Comment by ElliotNB** [comment] 2023-08-10 00:02
@eleanorjboyd Is this issue on the development roadmap for this extension? It's a wonderfully helpful extension and we would love to resume using it.

**Comment by sauergeek** [comment] 2023-11-27 18:29
We've started seeing a new issue this semester: some VSCode Node processes are getting enormous VIRT in top, which suggests something allocating vast amounts of memory without using it.  But to my eye, they look like system lockups waiting to happen.  An example from this morning:

3364117 [student]   20   0   32.7g  54928  43860 R 199.7   0.3  13224:53 code    
3364056 [student]   20   0 1122.5g 199504 149080 S   0.0   1.2   0:03.33 code    

Both of these -- and three other 32 Gb processes owned by the same user -- are all sitting on the same 16 Gb machine.  Linux's optimistic allocation is in part at fault for this, but why is Node ever asking for a _terabyte_?!  Particularly when it's using 200 Mb, and can't have ever used even two percent of that requested memory without bringing the computer to a rather abrupt halt?

In the few cases where I've contacted the student to ask what might be causing it, they were uniformly baffled.  I even had one exit VSCode, delete everything on the server side, and fire it up again -- and promptly got vast overallocation again.

**Comment by ElliotNB** [comment] 2023-11-30 22:51
@roblourens @eleanorjboyd Just curious -- is a fix for the disk space consumption on the roadmap?

**Comment by caleskog** [comment] 2023-12-29 12:42
> The particular problem we've found is that the server-side processes started by the SSH plugin do not exit unless the student exits VSCode perfectly. If they just close their laptop, or otherwise lose network connectivity to the server, the server-side processes will never exit unless killed by something outside of VSCode. The leftover processes won't get reused, either: next the student opens their laptop or starts VSCode again, it'll start new processes. Enough leftover processes will hang or crash the server.

@sauergeek Did you find a solution to the problem with the growing number of vscode-server processes?

For me it is not the disk space that is the problem, but the sheer number of running processes that does not exit when closing the remote connection. I use a combination of Remote -- SSH and Dev Containers in an old Ubuntu server. The problem I have is that the server sometimes gets unusable due to the number of node and cpptools processes that are never removed.

**Comment by sauergeek** [comment] 2024-01-04 20:00
@caleskog No solution, just a workaround.  We have a process reaper running hourly on all our hosts.  If it finds VSCode processes running without an affiliated sshd from the same user, it kills them.  I can provide the code if you like, though you'll have to tune it for your own systems.

**Comment by caleskog** [comment] 2024-01-05 12:35
@sauergeek Yes, that would be great! For now, I just manually connect with SSH to remove the running node processes, but your workaround seems way better.

**Comment by sauergeek** [comment] 2024-01-05 19:39
After two attempts to figure out how to get the file into a public repository (it won't let me upload the file in the web interface, and it won't let me password auth over HTTPS, and I can't be arsed to set up SSH keys for this), and discovering I can't attach it in this discussion, I've given up and put it on our web server.  Grab the code from https://www.eecs.tufts.edu/code/vscode-reaper.pl

**Comment by sauergeek** [comment] 2024-01-05 19:50
...finally figured out why the GUI upload wouldn't work: I was missing Still More Scripting, which I've now enabled.  https://github.com/sauergeek/vscode-reaper also works.

**Comment by briangreenery** [comment] 2024-05-18 18:04
I just deleted a 12 GB `.vscode-server` directory. Is it possible for this issue to be prioritized? It is my biggest problem using this extension.

**Comment by ConnerAiken** [comment] 2024-10-24 17:58
@briangreenery @sauergeek  @caleskog 

ChatGPT provided a good approach/idea, utilize `sshd_conf` to initialize a bash script on SFTP login to clear the folder, leaving it in-tact for the remainder of the connection.

# Running a Command on SFTP Connection in CentOS
When connecting via SFTP on CentOS, .bashrc or .bash_profile won't be executed since they are invoked only for interactive shell sessions. To clear a folder (e.g., .vscode-server) upon SFTP connection but leave it intact for the rest of the session, you can use the ForceCommand directive in sshd_config. Below are the steps to set this up:

## Step 1: Edit the sshd_config File
Open the sshd_config file using a text editor:
```
bash 
sudo vi /etc/ssh/sshd_config 
```
Add the following block to match your user (caiken in this example):
bash 
Match User caiken
    ForceCommand internal-sftp
    PermitTunnel no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    PermitTTY no
    ForceCommand /usr/local/bin/sftp-init.sh
```

## Step 2: Create the Custom Script
Create a custom script that runs your desired command and then starts the SFTP server. In this example, the script clears the .vscode-server folder and launches the sftp-server.

Create the script file:
```
bash 
sudo vi /usr/local/bin/sftp-init.sh 
```

Add the following content to the script:
```
bash 
#!/bin/bash
rm -rf /home/caiken/.vscode-server
exec /usr/libexec/openssh/sftp-server
```

## Step 3: Make the Script Executable
Give execution permissions to the script:
```
bash 
sudo chmod +x /usr/local/bin/sftp-init.sh
```

## Step 4: Restart the SSH Service
To apply the changes, restart the SSH service:
```
bash 
sudo systemctl restart sshd
```

Now, every time you connect via SFTP, the .vscode-server folder will be cleared, and the SFTP session will proceed as usual.

**Comment by joshspicer** [comment] 2024-12-12 23:00
/duplicate https://github.com/microsoft/vscode-remote-release/issues/7963

**Closed** 2024-12-12 23:01 UTC
Labels: *duplicate, ssh, remote, performance
