### ISSUE TITLE
[Code Server] M1 mac (arm64) download and runs x86 code server and terminal inside it is also run as x86 architecture

### ISSUE THREAD

**Issue by seonglae** [microsoft/vscode-remote-release#6963] opened 2022-07-18 11:58 UTC
- VSCode Version: 1.69.1
- Local OS Version: Windows 11
- Remote OS Version: 12.4 Monterey
- Remote Extension/Connection Type: Server
- Logs:
![image](https://user-images.githubusercontent.com/27716524/179505019-6e7a5b2f-ed50-4148-ac9f-901d05f5586a.png)

Steps to Reproduce:

1. `wget -O- https://aka.ms/install-vscode-server/setup.sh | sh` on m1 mac
2. Can install & run the server
3. I can access to the server does not work normally
![image](https://user-images.githubusercontent.com/27716524/179505656-9bced44b-0245-4ea0-b9a8-7f403273e488.png)
4. Weirdly, this terminal is definetely in m1 mac but node process shows architecture as `x86`
5. This is normally cannot be a problem but I use `napi-rs` and `node-addon-api` which build binary that has dependency on specific architecture.
6. My build command makes arm64 binary while node process's arch variable is x86. That makes my process not working.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by connor4312** [comment] 2022-07-19 16:41
Thanks for the issue! What does `uname -m` print? This may be the same as https://github.com/microsoft/vscode-remote-release/issues/6946

**Comment by seonglae** [comment] 2022-07-20 01:38
@connor4312 
![image](https://user-images.githubusercontent.com/27716524/179876771-1a4d6a40-d00c-44ad-91f5-f1bda1708d0b.png)

<img width="267" alt="image" src="https://user-images.githubusercontent.com/27716524/179876793-dd4bfbed-b7b7-466a-8410-2b62926a3f5d.png">

In vscode server terminal (web), x86_64
In native terminal, arm64

**Comment by tanhakabir** [comment] 2022-07-20 15:31
Thanks @seonglae! Yep this is a duplicate of #6946

**Comment by connor4312** [comment] 2022-07-20 17:00
This should be fixed later today, note that you'll need to run the setup script again

**Closed by connor4312** 2022-07-20 17:00 UTC
Labels: needs more info, code-server
