### ISSUE TITLE
Certain remote-container commands are not working as intended when clone in volume

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#3295] opened 2020-07-01 03:07 UTC
Testing #3265

Scenario I:

* Clone in volume
* Click `Dev Container..` status bar icon
* `Remote-Containers: Open Folder in Container` does nothing

Scenario II:

* Clone in volume
* Command Palette > `Remote-Containers: Reopen in container`, nothing happens
*. Not sure if this is intended under this context, if not a notification should be shown for invalid command

**Comment by chrmarti** [comment] 2020-07-01 07:41
Fixing `Open Folder in Container`. The `Reopen in Container` case might need a context to only activate in the 'inspect volume' case. Moving to you @egamma .

**Comment by egamma** [comment] 2020-09-23 09:18
duplicate of https://github.com/microsoft/vscode-remote-release/issues/3144

**Closed by egamma** 2020-09-23 09:18 UTC
Labels: bug, containers
