### ISSUE TITLE
Failed to connect. Is Docker running? Error: Request timed out

### ISSUE THREAD

**Issue by majksner** [microsoft/vscode-remote-release#4800] opened 2021-04-01 11:51 UTC
Issue Type: <b>Bug</b>

Hi,

After update to Code 1.55 "Remote - Containers" extension is stopped working correctly. I can't connect to remote Docker via context any more. By reverting to Code 1.54.3 I can see containers showing up but I don't have option "Attach Visual Studio Code", but if I downgrade "Remote - Containers" extension to 0.163.1 (Code 1.54.3) I can see "Attach Visual Studio Code" again when I do right-click on the running container. Reverting extension in Code 1.55 didn't help. 

Extension version: 0.166.0
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:07:58.402Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

microsoft/vscode-docker#2831

**Comment by chrmarti** [comment] 2021-04-01 15:34
Duplicate of https://github.com/microsoft/vscode/issues/120354

**Closed by chrmarti** 2021-04-01 15:34 UTC
Labels: containers
