### ISSUE TITLE
Port attributes "visibility"

### ISSUE THREAD

**Issue by emindeniz99** [microsoft/vscode-remote-release#6145] opened 2022-01-09 13:58 UTC
Hello,
On GitHub workspaces, I want to automatically open a port with public visibility to test with Postman without auth.

At this documentation, visibility field is not exist.
https://github.com/microsoft/vscode-docs/blob/main/docs/remote/devcontainerjson-reference.md#port-attributes

![image](https://user-images.githubusercontent.com/44745432/148685199-9c73520e-69d5-47cc-9863-40e5796821d0.png)

I have searched it, I can not any info(existing issues) with this field.

**Comment by alexr00** [comment] 2022-12-07 14:57
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6363

**Closed** 2022-12-07 14:58 UTC
Labels: *duplicate, feature-request, remote-explorer
