### ISSUE TITLE
remote develop with ssh protocol and zsh, get a bad math expression error

### ISSUE THREAD

**Issue by ifooth** [microsoft/vscode-remote-release#6408] opened 2022-03-03 07:27 UTC
remote develop with ssh protocol and zsh, but failed to establish the connection. Here is the error log

![Xnip2022-03-03_11-43-44](https://user-images.githubusercontent.com/1853121/156516657-4d07d376-e21a-49b7-b51e-8b07b850b758.png)

**Comment by tanhakabir** [comment] 2022-03-03 23:04
What version of Remote SSH extension are you using? Could you try using 76.1?

**Comment by ifooth** [comment] 2022-03-04 06:14
## vscode
![image](https://user-images.githubusercontent.com/1853121/156709871-14aa1373-50a7-402b-b9f9-cc137ea7837f.png)

## extensions
![image](https://user-images.githubusercontent.com/1853121/156709813-0af1c1c4-9d39-431d-aac2-7560454756f7.png)

**Comment by tanhakabir** [comment] 2022-03-04 17:41
Could you please copy and paste the entire log here? Instead of screenshots

**Comment by ifooth** [comment] 2022-03-06 01:46
sure
## vscode
```
Version: 1.64.2 (Universal)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```

## extensions
```
aaron-bond.better-comments@2.1.0
alefragnani.project-manager@12.5.0
asciidoctor.asciidoctor-vscode@2.9.5
BazelBuild.vscode-bazel@0.5.0
budparr.language-hugo-vscode@1.3.1
bungcip.better-toml@0.3.2
caarlos0.language-prometheus@0.1.2
coolbear.systemd-unit-file@1.0.6
dirk-thomas.vscode-lark@0.1.0
eriklynd.json-tools@1.0.2
geddski.macros@1.2.1
golang.go@0.31.1
GrapeCity.gc-excelviewer@4.0.50
heptio.jsonnet@0.1.0
idleberg.applescript@0.21.1
idleberg.openvpn@0.2.3
igochkov.vscode-ebnf@1.0.3
ionceflorin.copy-current-file-path@0.0.3
joaompinto.asciidoctor-vscode@2.8.0
LaurentTreguier.rpm-spec@0.3.2
lextudio.restructuredtext@173.0.0
mikestead.dotenv@1.0.1
mohd-akram.vscode-html-format@0.0.4
mrorz.language-gettext@0.2.0
ms-azuretools.vscode-docker@1.20.0
ms-kubernetes-tools.vscode-kubernetes-tools@1.3.6
ms-python.python@2022.2.1924087327
ms-python.vscode-pylance@2022.3.0
ms-toolsai.jupyter@2022.1.1301854968
ms-toolsai.jupyter-keymap@1.0.0
ms-toolsai.jupyter-renderers@1.0.6
ms-vscode-remote.remote-containers@0.224.2
ms-vscode-remote.remote-ssh@0.76.1
ms-vscode-remote.remote-ssh-edit@0.76.1
ms-vscode-remote.remote-wsl@0.64.2
ms-vscode-remote.vscode-remote-extensionpack@0.21.0
octref.vetur@0.35.0
p26frqxxfmwrzekd6c6fcty5kipjkr3gaeejzpkyy42p5udjkjyq.copyplaintext@1.1.5
redhat.vscode-commons@0.0.6
redhat.vscode-yaml@1.4.0
ronnidc.nunjucks@0.3.0
Rubymaniac.vscode-direnv@0.0.2
shd101wyy.markdown-preview-enhanced@0.6.2
sidneys1.gitconfig@2.0.1
TabNine.tabnine-vscode@3.5.26
technosophos.vscode-helm@0.4.0
tommorris.mako@0.2.0
trixnz.vscode-lua@0.12.4
Tyriar.sort-lines@1.9.1
vscode-icons-team.vscode-icons@11.10.0
vthiery.prettify-selected-json@1.0.3
wholroyd.jinja@0.0.8
XadillaX.viml@1.0.1
zhouronghui.propertylist@0.0.2
```

**Comment by tanhakabir** [comment] 2022-03-07 03:00
Sorry the Remote-SSH logs. You can get them with these instructions: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by richardzhu** [comment] 2022-03-09 06:33
Also running into this issue.

**Comment by tanhakabir** [comment] 2022-03-09 07:45
@richardzhu could you share your Remote SSH logs?

**Comment by phord** [comment] 2022-03-14 23:24
Getting logs is tricky because a modal dialog pops up from vscode complaining about the connection failure. This dialog prevents copying the logs.  If you click the "Something else" button, it goes away and the logs can be selected.

In my case, the problem went away when I clicked the "Switch to Pre-release Version" and it went to `v0.77.2022031115`
I was also on `0.76.1` before.

```
[16:15:26.563] Log Level: 2
[16:15:26.568] remote-ssh@0.76.1
[16:15:26.569] linux x64
[16:15:26.641] SSH Resolver called for "ssh-remote+vm", attempt 1
[16:15:26.646] "remote.SSH.useLocalServer": true
[16:15:26.647] "remote.SSH.path": undefined
[16:15:26.654] "remote.SSH.configFile": undefined
[16:15:26.655] "remote.SSH.useFlock": true
[16:15:26.655] "remote.SSH.lockfilesInTmp": false
[16:15:26.658] "remote.SSH.localServerDownload": auto
[16:15:26.658] "remote.SSH.remoteServerListenOnSocket": false
[16:15:26.659] "remote.SSH.showLoginTerminal": true
[16:15:26.660] "remote.SSH.defaultExtensions": []
[16:15:26.665] "remote.SSH.loglevel": 2
[16:15:26.666] "remote.SSH.enableDynamicForwarding": true
[16:15:26.666] "remote.SSH.enableRemoteCommand": false
[16:15:26.667] "remote.SSH.serverPickPortsFromRange": {}
[16:15:26.667] "remote.SSH.serverInstallPath": {}
[16:15:26.717] SSH Resolver called for host: vm
[16:15:26.718] Setting up SSH remote "vm"
[16:15:26.726] Acquiring local install lock: /tmp/vscode-remote-ssh-4049c22c-install.lock
[16:15:26.736] Looking for existing server data file at /home/phord/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4049c22c-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json
[16:15:26.738] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[16:15:26.760] Install and start server if needed
[16:15:26.775] PATH: /home/phord/.local/bin:/home/phord/bin:/home/phord/.cargo/bin:/home/phord/.local/bin:/home/phord/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[16:15:26.775] Checking ssh with "ssh -V"
[16:15:26.817] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020

[16:15:26.847] askpass server listening on /run/user/1000/vscode-ssh-askpass-170cd62005cd463e47a9e316de67f701b166f0ab.sock
[16:15:26.847] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-5b312f9eb66a7eb6df9295206355b35417f97e41.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","40897","-o","ConnectTimeout=15","vm"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/phord/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4049c22c-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json"}
[16:15:26.848] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/zsh","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-170cd62005cd463e47a9e316de67f701b166f0ab.sock"}
[16:15:26.863] Spawned 3350907
[16:15:27.166] > local-server-1> Spawned ssh, pid=3350917
[16:15:27.175] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
[16:15:27.385] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:IzooKkTGHCHkDaQGYA5wxV/peAkZ4oqtJd+wCZvULqE
[16:15:27.693] stderr> Authenticated to dev-phord.dev.purestorage.com ([10.7.57.22]:22).
[16:15:28.019] > Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-144-generic x86_64)
> 
>  * Super-optimized for small spaces - read how we shrank the memory
>    footprint of MicroK8s to make it the smallest full K8s around.
> 
>    https://ubuntu.com/blog/microk8s-memory-optimisation
> 
>  * Canonical Livepatch is available for installation.
>    - Reduce system reboots and improve kernel security. Activate at:
>      https://ubuntu.com/livepatch
> 
> 59 updates can be applied immediately.
> 1 of these updates is a standard security update.
> To see these additional updates run: apt list --upgradable
> 
> New release '20.04.4 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> *** System restart required ***
>      _                       _                   _ 
>   __| | _____   __     _ __ | |__   ___  _ __ __| |
>  / _` |/ _ \ \ / /____| '_ \| '_ \ / _ \| '__/ _` |
> | (_| |  __/\ V /_____| |_) | | | | (_) | | | (_| |
>  \__,_|\___| \_/      | .__/|_| |_|\___/|_|  \__,_|
>                       |_|                          
> *******************************************************
> This machine is managed by puppet
> *******************************************************
> Ubuntu 18.04.5 LTS
> Host: kvm
> CPUs: 40
> RAM: 125.91 GB
> Virtual: true
> Datacenter: c7
> Puppet Branch: puppet5
> Puppetfile: default
> Puppet Modules:
>     -- docker-ce - Managed
>     -- pure::dev - Ubuntu 18.04 - puppet5 branch
[16:15:28.033] > Executing .profile
[16:15:28.054] > ready: 4e03b338a017
[16:15:28.094] > Linux 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021
[16:15:28.095] Platform: linux
[16:15:28.135] > /bin/bash
[16:15:28.136] Shell: bash
[16:15:28.232] > 4e03b338a017: running
[16:15:28.243] stderr> cat: '/usr/libx32/libstdc++.so.6'$'\n''/usr/lib/x86_64-linux-gnu/libstdc++.so.6'$'\n''/usr/lib32/libstdc++.so.6': No such file or directory
[16:15:28.246] > Missing GLIBCXX >= 3.4.18!
> Found versions 
[16:15:28.251] stderr> mainScriptWrapper:185: bad math expression: operand expected at `*100 +  '
[16:15:28.255] stderr> Transferred: sent 19220, received 5252 bytes, in 0.6 seconds
[16:15:28.255] stderr> Bytes per second: sent 34635.8, received 9464.5
[16:15:28.261] > local-server-1> ssh child died, shutting down
[16:15:28.271] Local server exit: 0
[16:15:28.273] Received install output: local-server-1> Spawned ssh, pid=3350917
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:IzooKkTGHCHkDaQGYA5wxV/peAkZ4oqtJd+wCZvULqE
Authenticated to dev-phord.dev.purestorage.com ([10.7.57.22]:22).
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-144-generic x86_64)

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

59 updates can be applied immediately.
1 of these updates is a standard security update.
To see these additional updates run: apt list --upgradable

New release '20.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


*** System restart required ***
     _                       _                   _ 
  __| | _____   __     _ __ | |__   ___  _ __ __| |
 / _` |/ _ \ \ / /____| '_ \| '_ \ / _ \| '__/ _` |
| (_| |  __/\ V /_____| |_) | | | | (_) | | | (_| |
 \__,_|\___| \_/      | .__/|_| |_|\___/|_|  \__,_|
                      |_|                          
*******************************************************
This machine is managed by puppet
*******************************************************
Ubuntu 18.04.5 LTS
Host: kvm
CPUs: 40
RAM: 125.91 GB
Virtual: true
Datacenter: c7
Puppet Branch: puppet5
Puppetfile: default
Puppet Modules:
    -- docker-ce - Managed
    -- pure::dev - Ubuntu 18.04 - puppet5 branch
Executing .profile
ready: 4e03b338a017
Linux 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021
/bin/bash
4e03b338a017: running
cat: '/usr/libx32/libstdc++.so.6'$'\n''/usr/lib/x86_64-linux-gnu/libstdc++.so.6'$'\n''/usr/lib32/libstdc++.so.6': No such file or directory
Missing GLIBCXX >= 3.4.18!
Found versions 
mainScriptWrapper:185: bad math expression: operand expected at `*100 +  '
Transferred: sent 19220, received 5252 bytes, in 0.6 seconds
Bytes per second: sent 34635.8, received 9464.5
local-server-1> ssh child died, shutting down

[16:15:28.279] Failed to parse remote port from server output
[16:15:28.286] Resolver error: Error: 
	at Function.Create (/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:586041)
	at Object.t.handleInstallOutput (/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:584693)
	at Object.e [as tryInstallWithLocalServer] (/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:625033)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:644084
	at async Object.t.withShowDetailsEvent (/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:647831)
	at async /home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:623505
	at async b (/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:620011)
	at async Object.t.resolveWithLocalServer (/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:623120)
	at async Object.t.resolve (/home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:645441)
	at async /home/phord/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:722872
[16:15:28.321] ------

```

**Comment by tanhakabir** [comment] 2022-03-16 17:21
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6341

**Closed** 2022-03-16 17:20 UTC
Labels: ssh, needs more info
