### ISSUE TITLE
Remote container stops working since recent Windows update

### ISSUE THREAD

**Issue by andyli** [microsoft/vscode-remote-release#4853] opened 2021-04-08 13:33 UTC
- VSCode Version:
```
Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21354
```

- Local OS Version:
```
Edition	Windows 10 Pro
Version	Dev
Installed on	‎2021-‎04-‎08
OS build	21354.1
Experience	Windows 10 Feature Experience Pack 321.7601.0.3
```

- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: Docker (using Docker for Win, Docker Engine v20.10.5 with the WSL2 based engine)

Steps to Reproduce:

1. Clone the repo at https://github.com/hkssprangers/hkssprangers.git (Commit `f094746a980142e4e337a376c18aa982920131a9` at the time of writing.) in a WSL2 location (e.g. `\\wsl.localhost\Ubuntu\home\andy\workspace`.
2. Open the directory in VS Code and select "Reopen in container"
3. Error message appears: 
```
[2021-04-08T13:27:22.764Z] [PID 11728] [6 ms] Remote-Containers 0.166.1 in VS Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f).
[2021-04-08T13:27:22.965Z] [PID 11728] [207 ms] Start: Resolving Remote
[2021-04-08T13:27:22.966Z] [PID 11728] [208 ms] Setting up container for folder or workspace: \\wsl.localhost\Ubuntu\home\andy\workspace\hkssprangers
[2021-04-08T13:27:22.968Z] [PID 11728] [210 ms] Start: Check Docker is running
[2021-04-08T13:27:22.968Z] [PID 11728] [210 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[2021-04-08T13:27:23.163Z] [PID 11728] [405 ms] Server API version: 1.41
[2021-04-08T13:27:23.215Z] [PID 11728] [457 ms] Start: Run: docker-compose version --short
[2021-04-08T13:27:23.655Z] [PID 11728] [897 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=hkssprangers_devcontainer --filter label=com.docker.compose.service=workspace
[2021-04-08T13:27:23.900Z] [PID 11728] [1142 ms] Start: Run: docker-compose -f \\wsl.localhost\Ubuntu\home\andy\workspace\hkssprangers\.devcontainer\docker-compose.yml config --services
[2021-04-08T13:27:24.461Z] [PID 11728] [1703 ms] workspace
mysql
[2021-04-08T13:27:24.461Z] [PID 11728] [1703 ms] 
[2021-04-08T13:27:24.462Z] [PID 11728] [1704 ms] Start: Run: docker events --format {{json .}} --filter event=start
[2021-04-08T13:27:24.475Z] [PID 11728] [1717 ms] Start: Run: docker-compose --project-name hkssprangers_devcontainer -f \\wsl.localhost\Ubuntu\home\andy\workspace\hkssprangers\.devcontainer\docker-compose.yml up -d --build
[2021-04-08T13:27:24.546Z] [PID 11728] 
[2021-04-08T13:27:25.108Z] [PID 11728] Creating hkssprangers_devcontainer_workspace_1 ...
Creating hkssprangers_devcontainer_mysql_1     ...
[2021-04-08T13:27:25.139Z] [PID 11728] 
Creating hkssprangers_devcontainer_workspace_1 ... error
Creating hkssprangers_devcontainer_mysql_1     ...

ERROR: for hkssprangers_devcontainer_workspace_1  Cannot create container for se
rvice workspace: \\wsl.localhost\Ubuntu\home\andy\workspace\hkssprangers%!(EXTRA
Creating hkssprangers_devcontainer_mysql_1     ... error

ERROR: for hkssprangers_devcontainer_mysql_1  Cannot create container for servic
e mysql: \\wsl.localhost\Ubuntu\home\andy\workspace\hkssprangers\dev\initdb%!(EX
TRA string=is not a valid Windows path)

ERROR: for workspace  Cannot create container for service workspace: \\wsl.local
host\Ubuntu\home\andy\workspace\hkssprangers%!(EXTRA string=is not a valid Windo
ws path)

ERROR: for mysql  Cannot create container for service mysql: \\wsl.localhost\Ubu
ntu\home\andy\workspace\hkssprangers\dev\initdb%!(EXTRA string=is not a valid Wi
ndows path)
ERROR: Encountered errors while bringing up the project.
[2021-04-08T13:27:25.205Z] [PID 11728] [2447 ms] Command failed: docker-compose --project-name hkssprangers_devcontainer -f \\wsl.localhost\Ubuntu\home\andy\workspace\hkssprangers\.devcontainer\docker-compose.yml up -d --build
```

I noticed the WSL location changed from `\\wsl\Ubuntu\...` to `\\wsl.localhost\Ubuntu\...` in the recent Windows update. Not sure if it's the problem.

**Comment by andyli** [comment] 2021-04-10 10:50
My workaround is to open it using the "old" path (`\\wsl$`), which still works.

1. `cd \\wsl$\Ubuntu\home\andy\workspace\charleywong\.devcontainer`
2. `docker-compose up`
3. Open VS Code, select the Docker tab, and then attach vscode to the container.

**Comment by andyli** [comment] 2021-04-11 09:58
The root cause will most likely be fixed in https://github.com/docker/for-win/issues/10786

It would be great if vscode can implement a workaround though. e.g. by using `\\wsl$` path.

**Comment by mauve** [comment] 2021-04-11 19:24
Related to https://github.com/microsoft/vscode/issues/120846

**Comment by chrmarti** [comment] 2021-04-12 20:54
Please give Remote-Containers 0.167.0 a try. That currently requires VS Code Insiders available here: https://code.visualstudio.com/insiders/

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4789.

**Closed by chrmarti** 2021-04-12 20:54 UTC

**Comment by andyli** [comment] 2021-04-13 06:09
Just tried Remote-Containers 0.167.0 with VS Code Insiders and it worked well. Thanks!
