### ISSUE TITLE
Terminal Not Opening Up

### ISSUE THREAD

**Issue by ananthrn** [microsoft/vscode-remote-release#565] opened 2019-06-05 17:54 UTC
Issue Type: <b>Bug</b>

Terminal doesn't open. I used the command pallete. 

Extension version: 0.41.0
VS Code version: Code - Insiders 1.35.0-insider (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T00:11:00.788Z)
OS version: Darwin x64 18.2.0
Remote OS version: Linux x64 4.4.0-143-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|-psn_0_249917|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: apdev2|
|OS|Linux x64 4.4.0-143-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (48 x 2500)|
|Memory (System)|184.85GB (10.31GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment] 2019-06-05 20:56
Please include more details about exactly what you tried

**Comment by ananthrn** [comment] 2019-06-05 23:58
I used the Remote-SSH extension. 

Using the command pallete (CMD+Shift+P), I clicked on Open New Terminal. There was no response, no new terminal opened.

**Comment by imbdb** [comment] 2019-06-06 05:56
Facing this issue.
But If I open a new terminal by clicking plus then the second terminal works fine.

**Comment by imbdb** [comment] 2019-06-06 06:01
![screenshot-github com-2019 06 06-11-27-15](https://user-images.githubusercontent.com/3460775/59010309-75ff4100-884e-11e9-8768-62aa12dfdfa5.png)
Its stuck and won't open

![screenshot-newtab-2019 06 06-11-28-54](https://user-images.githubusercontent.com/3460775/59010317-78fa3180-884e-11e9-8827-668674cb13f0.png)
Its second terminal and it works fine.

**Comment by byzantic** [comment] 2019-06-13 12:56
I also have this issue, with Code version 1.35.1

I am trying to use the Remote-SSH extension in order to work on a remote CentOS server (CentOS 7.6).
I have set up the SSH keys, and the connection appears to work fine; browsing and eting files works OK.

However, attempting to start a terminal just leads to the '..starting' message reported by @imbdb above. In my case, though, starting a second terminal does not succeed.

I can start an ssh terminal session from the command prompt outside of code without any problem.

One thing I did worry about was that my shell on the remote is csh rather than bash, but changing this using chsh did not help. In any case, I think that if that were the problem, remote-ssh would not work at all?

**Comment by eduarmreyes** [comment] 2019-06-18 19:13
This is what I am experiencing.

I open VS Code using the Remote - WSL extension and when I try to open a terminal this shows up.

![image](https://user-images.githubusercontent.com/3196685/59712502-574c6300-91db-11e9-96fb-2befe2ddb8ef.png)

The error says `The terminal process terminated with exit code: 1` and my default shell is

![image](https://user-images.githubusercontent.com/3196685/59712559-76e38b80-91db-11e9-9f4f-01b5b7765d4a.png)

Without the extension, everything works fine.

**Comment by roblourens** [comment] 2019-06-18 21:29
@eduarmreyes your issue looks like https://github.com/microsoft/vscode-remote-release/issues/590

**Comment by eduarmreyes** [comment] 2019-06-21 00:21
> @eduarmreyes your issue looks like #590

Thank you, that was exactly it.

**Comment by nagos** [comment] 2019-07-13 12:02
I have issue similar to @byzantic with WSL (Ubuntu).
Without remote extension WSL terminal opens fine.
But when i connected to WSL, terminal is stuck in "starting" stete, no errors displayed.

In my case terminal does not work, if directory is open on startup.

Steps to reproduce:
1. Close folder in vscode, and restart
2. Start vscode, without connection to WSL
![1](https://user-images.githubusercontent.com/183965/61171320-b5702a00-a57e-11e9-89ed-526e0059a9de.png)
3. Open WSL folder from Recent tab
![2](https://user-images.githubusercontent.com/183965/61171324-ba34de00-a57e-11e9-8cff-9849116542e0.PNG)
4. Open terminal, it works.
![3](https://user-images.githubusercontent.com/183965/61171325-bc973800-a57e-11e9-90d1-72356b1f0a12.PNG)
5. Close vscode, without closing terminal
6. Run vscode, it will automaticaly open folder, terminal does not work anymore.
![4](https://user-images.githubusercontent.com/183965/61171356-1d267500-a57f-11e9-8032-51c618273e53.PNG)
7. File-close folder
8. open from recent, get an error
"WSL Daemon exited with error code 0"
![5](https://user-images.githubusercontent.com/183965/61171358-244d8300-a57f-11e9-9fa7-22d71b3e6b12.PNG)

It was tested on clean windows 10 install in virtualbox.

**Comment by Tyriar** [comment] 2019-07-26 23:47
/duplicate https://github.com/microsoft/vscode-remote-release/issues/1031

**Closed by Tyriar** 2019-07-26 23:47 UTC
Labels: bug

**Comment by byzantic** [comment] 2019-08-12 08:22
Sorry, but this doesn't seem fixed. Behaviour in release 1.37.0 has changed, though.

As before, I can start a remote-SSH session, and the editor works OK. That is, I can see remote files in the filesystem browser, edit files, etc. However, when attempting to start the terminal, this fails immediately with the error message:

"The terminal process command '/bin/bash' failed to launch (exit code: {2})"

My conclusion is that there were probably two interrelated bugs causing my issue, and that it is different from #1031

**Comment by Tyriar** [comment] 2019-08-12 16:59
@byzantic please create a new issue
