### ISSUE TITLE
Support opening a remote file or folder from the VS Code commandline.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode-remote-release#1372] opened 2019-09-05 14:38 UTC
I find the remote extensions extremely useful.  Thanks for providing them!  Here's something that would make them even more useful.

Currently, to open a remote file I must open VS Code and then (in the UI) select a remote host/environment and then select a file/folder/workspace to open.  I'd like to be able to do that using the VS Code CLI as well.

From the terminal we (users) can open VS Code for a file or folder (with a number of useful options, as well as manage extensions and other similar operations).  It would be helpful to be able to open a *remote* file or folder using that same CLI.

Examples:

* SSH: open a file on a remote host
   * `code --ssh my-host path/to/file`
   * (or maybe `code ssh://my-host/path/to/file` or `code ssh://my-host:path/to/file`)
* WSL
   * `code --wsl path/to/file`
* open a new window for a remote
   * `code --ssh my-host`
   * (or maybe `code ssh://my-host`)

VS Code already has the ability to directly open a remote folder without any user intervention, as evidenced by how it will go straight to a remote folder if it was open the last time I closed VS Code.  So it would be nice to do the same thing by providing the remote host & filename to the `code` CLI rather than having it read from some data store.

**Comment by ericsnowcurrently** [comment] 2019-09-05 14:40
I expect this would require that VS Code allow extensions to extend its CLI.  See https://github.com/microsoft/vscode/issues/80409.

**Comment by egamma** [comment] 2019-09-09 17:27
Duplicate of #585

**Closed by egamma** 2019-09-09 17:27 UTC
