### ISSUE TITLE
Add the ability to open a folder in a remote container directly rather than having to open it locally first

### ISSUE THREAD

**Issue by nerdo** [microsoft/vscode-remote-release#3202] opened 2020-06-15 13:08 UTC
I'd like to see the ability to open a folder directly in its remote container instead of having to open it locally and either wait for the prompt to open it in the container or to explicitly run the command from the palette.

Ideally it could be a command-line argument like
```
code --in-container path/to/workspace
```

**Comment by tschaub** [comment] 2020-06-29 23:03
@chrmarti - it looks like this could be marked as a duplicate of #2761 (or vice versa).

**Comment by chrmarti** [comment] 2020-06-30 06:37
Thanks @tschaub. Duplicate of #2761.

**Closed by chrmarti** 2020-06-30 06:37 UTC
Labels: containers, feature-request
