### ISSUE TITLE
Terminal remains in "Starting" state on slow connections

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#1031] opened 2019-07-25 16:04 UTC
Issue Type: <b>Bug</b>

Working over a slow (really slow) network connection, terminals don't restore correctly when re-opening a workspace.

1) Connect to the network through a slow connection
2) Connect to a SSH box, open a folder, open a terminal
3) Close window
4) Reopen window
-> Terminal remains in "Starting"

It seems the terminal is still sensitive to timing in this case.

Extension version: 2019.7.31140
VS Code version: Code - Insiders 1.37.0-insider (36e08fed41272d1ff0d73d9b3a540b0a052ecef4, 2019-07-24T19:56:39.504Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.18.0-1018-azure

**Comment by Tyriar** [comment] 2019-07-26 17:47
I think I know's causing this now, might be a duplicate of https://github.com/microsoft/vscode-remote-release/issues/565

**Comment by Tyriar** [comment] 2019-07-26 23:28
Ok I think this is happening when MainThreadTerminalService takes 5+ seconds to be created because of https://github.com/microsoft/vscode/blob/76799f477d67d1df97b2e630a9c4ed7800a05638/src/vs/workbench/contrib/terminal/common/terminalService.ts#L139-L143

**Comment by Tyriar** [comment] 2019-07-26 23:49
Tested my fix by delaying https://github.com/microsoft/vscode/blob/76799f477d67d1df97b2e630a9c4ed7800a05638/src/vs/workbench/api/browser/mainThreadTerminalService.ts#L72 by 15 seconds.

**Closed** 2019-07-26 23:49 UTC
Labels: bug
