### ISSUE TITLE
Remote-SSH: Fail to install VS-Code Server

### ISSUE THREAD

**Issue by Pubec** [microsoft/vscode-remote-release#3858] opened 2020-10-15 13:02 UTC
- VSCode Version: 1.50.1  - CommitID: d2e414d9e4239a252d1ab117bd7067f125afd80a
- OS Version: Microsoft Windows 10 Home Insider Preview

Steps to Reproduce:

1. Remote-SSH: Connect to Host (Host is Ubuntu 20.04.1 LTS) - Fails
or
1. Manually download from _[https://update.code.visualstudio.com/commit:d2e414d9e4239a252d1ab117bd7067f125afd80a/server-linux-x64/stable](https://update.code.visualstudio.com/commit:d2e414d9e4239a252d1ab117bd7067f125afd80a/server-linux-x64/stable)_
2. Copy file to remote host under _~/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/_
3. Extract: `tar -xvzf vscode-server-linux-x64.tar.gz --strip-components 1`

Step 3 fails with: _tar: Skipping to next header_ _tar: Exiting with failure status due to previous errors_
After step 3, there is no **server.sh** file.

Does this issue occur when all extensions are disabled?: Yes

Followed instruction after failing many times: [https://medium.com/@debugger24/installing-vscode-server-on-remote-machine-in-private-network-offline-installation-16e51847e275](https://medium.com/@debugger24/installing-vscode-server-on-remote-machine-in-private-network-offline-installation-16e51847e275)

**Comment by roblourens** [comment] 2020-10-16 23:39
Thanks for trying it manually. Do you maybe have an old version of `tar` installed?

**Comment by Pubec** [comment] 2020-10-17 06:05
> 
> 
> Thanks for trying it manually. Do you maybe have an old version of `tar` installed?

I have tried updating it but the error still persists. I have updated and upgraded all packages, but uncompressing still fails. I have tried with tar version 1.30 and 1.32.

**Comment by DProvinciani** [comment] 2020-10-19 18:22
Facing the same issue since I got the update to `1.50.1` last week. I tried manually by doing...

```
wget -O vscode-server-linux-x64.tar.gz https://update.code.visualstudio.com/commit:d2e414d9e4239a252d1ab117bd7067f125afd80a/server-linux-x64/stable

tar zxvf vscode-server-linux-x64.tar.gz
vscode-server-linux-x64/
vscode-server-linux-x64/package.json
vscode-server-linux-x64/extensions/
vscode-server-linux-x64/extensions/ms-vscode.js-debug-companion/
vscode-server-linux-x64/extensions/ms-vscode.js-debug-companion/package.json
vscode-server-linux-x64/extensions/ms-vscode.js-debug-companion/README.md
vscode-server-linux-x64/extensions/ms-vscode.js-debug-companion/out/
vscode-server-linux-x64/extensions/ms-vscode.js-debug-companion/out/extension.js
tar: Skipping to next header
tar: Archive base-256 value is out of off_t range
tar: Exiting with failure status due to previous errors
```

The tar seems to be corrupted.

**Comment by roblourens** [comment] 2020-11-05 18:02
Closing as dupe of https://github.com/microsoft/vscode-remote-release/issues/3396

Is it possible that you have an old version of tar installed?

**Closed by roblourens** 2020-11-05 18:02 UTC
Labels: needs-more-info
