### ISSUE TITLE
> Installing...  Downloading with wget   Connection to closed by remote host

### ISSUE THREAD

**Issue by sky92zwq** [microsoft/vscode-remote-release#287] opened 2019-05-11 09:24 UTC
- VSCode Version:1.34.0-insider (system setup)
- Local OS Version:win7
- Remote OS Version: linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
 I hide the  ip
1.config file:
Host xx.xx.xx.xx
    HostName xx.xx.xx.xx
    User root
2.
SSH Resolver called for "ssh-remote+xx.xx.xx.xx"
SSH Resolver called for host: xx.xx.xx.xx
Setting up SSH remote "xx.xx.xx.xx"
Using commit id "473af338e1bd9ad4d9853933da1cd9d5d9e07dc9" and quality "insider" for server
Install and start server if needed
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> 
> Authorized users only. All activities may be monitored and reported.
> 
> bash: no job control in this shell
> 
> Installing...
> Downloading with wget
> 
> Connection to xx.xx.xx.xx closed by remote host.
> 
"install" terminal command done
Received install output: Connection to xx.xx.xx.xx  closed by remote host.
Failed to parse remote port from server output: Connection to xx.xx.xx.xx  closed by remote host.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by sky92zwq** [comment] 2019-05-13 11:02
i think  it is the same problem with 
#15

**Comment by egamma** [comment] 2019-05-13 12:48
Duplicate of #15, thanks @sky92zwq

**Closed by egamma** 2019-05-13 12:48 UTC
Labels: *duplicate, ssh
