### ISSUE TITLE
Can't connect using the Aarch64 (ARM64v8) Server in Oracle Cloud

### ISSUE THREAD

**Issue by Bryceed** [microsoft/vscode-remote-release#6300] opened 2022-02-07 20:47 UTC
- VSCode Version: 1.64.0 (user setup)
- Local OS Version: Windows 11 (Windows_NT x64 10.0.22000)
- Remote OS Version: Oracle Linux 7.9 aarch64 (RHEL Server release 7.9, Maipo) - Default Image
- Remote Extension/Connection Type: Extension "Remote - SSH" v0.70.0
- Logs: ↓↓

<details>
  <summary><b>SSH Remote Log</b></summary>

```
[16:44:11.380] Log Level: 2
[16:44:11.387] remote-ssh@0.70.0
[16:44:11.387] win32 x64
[16:44:11.391] SSH Resolver called for "ssh-remote+xxxxxxxxxxxx4e616d65223a224f7261636c65c2a041524dc2a05365xxxxxxxxxxxx, attempt 1
[16:44:11.394] "remote.SSH.useLocalServer": false
[16:44:11.395] "remote.SSH.showLoginTerminal": false
[16:44:11.396] "remote.SSH.remotePlatform": {"144.xxx.xxx.xxx":"linux","168.138.243.221":"linux","144.xxx.xxx.xxx":"linux","Oracle ARM Server":"linux"}
[16:44:11.397] "remote.SSH.path": undefined
[16:44:11.398] "remote.SSH.configFile": undefined
[16:44:11.398] "remote.SSH.useFlock": true
[16:44:11.399] "remote.SSH.lockfilesInTmp": false
[16:44:11.400] "remote.SSH.localServerDownload": auto
[16:44:11.400] "remote.SSH.remoteServerListenOnSocket": false
[16:44:11.401] "remote.SSH.showLoginTerminal": false
[16:44:11.401] "remote.SSH.defaultExtensions": []
[16:44:11.402] "remote.SSH.loglevel": 2
[16:44:11.403] "remote.SSH.serverPickPortsFromRange": {}
[16:44:11.403] "remote.SSH.enableDynamicForwarding": true
[16:44:11.404] "remote.SSH.serverInstallPath": {}
[16:44:11.404] SSH Resolver called for host: Oracle ARM Server
[16:44:11.404] Setting up SSH remote "Oracle ARM Server"
[16:44:11.505] Using commit id "5554b12acf27056905806867f251c859323ff7e9" and quality "stable" for server
[16:44:11.518] Install and start server if needed
[16:44:11.533] Checking ssh with "ssh -V"
[16:44:11.589] > O
[16:44:11.590] > penSSH_for_Wi
[16:44:11.590] > ndows_
[16:44:11.591] > 8
[16:44:11.591] > .1p1, LibreSSL 3.0.2

[16:44:11.604] Running script with connection command: ssh -T -D 52501 "Oracle ARM Server" bash
[16:44:11.613] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:44:12.075] > ]0;C:\WINDOWS\System32\cmd.exe
[16:44:12.076] Got some output, clearing connection timeout
[16:44:12.199] > Warning: Permanently added '144.xxx.xxx.xxx' (ECDSA) to the list of known hosts.
[16:44:12.400] > cb1c707f9f56: running
[16:44:12.437] > Acquiring lock on /home/opc/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/vscode-remote-lock.opc.5554b12acf27056905806867f251c859323ff7e9
> Found existing installation at /home/opc/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9...
> Checking /home/opc/.vscode-server/.5554b12acf27056905806867f251c859323ff7e9.log and /home/opc/.vscode-server/.5554b12acf27056905806867f251c859323ff7e9.pid for a running server
> Looking for server with pid: 13933
[16:44:12.451] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
[16:44:12.468] > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status on port 41135 with wget
> cb1c707f9f56: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==41135==
> osReleaseId==ol==
> arch==aarch64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==xxxxxxxx-1aa1-1aa1-a1a1-xxxxxxxxxxxx==
[16:44:12.471] > 
> cb1c707f9f56: end
[16:44:12.472] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==41135==
osReleaseId==ol==
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==xxxxxxxx-1aa1-1aa1-a1a1-xxxxxxxxxxxx==

[16:44:12.473] Remote server is listening on 41135
[16:44:12.473] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":41135},"osReleaseId":"ol","arch":"aarch64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"a1aa1aaa-1aa1-1aa1-a1a1-111a111a11a1"},"installUnpackCode":""}
[16:44:12.473] ** Note: Support for architecture "aarch64" is in preview **
[16:44:12.480] Starting forwarding server. localPort 52504 -> socksPort 52501 -> remotePort 41135
[16:44:12.481] Forwarding server listening on 52504
[16:44:12.482] Waiting for ssh tunnel to be ready
[16:44:12.486] [Forwarding server 52504] Got connection 0
[16:44:12.489] Tunneled 41135 to local port 52504
[16:44:12.489] Resolved "ssh-remote+xxxxxxxxxxxx4e616d65223a224f7261636c65c2a041524dc2a05365xxxxxxxxxxxx" to "127.0.0.1:52504"
[16:44:12.503] ------




[16:44:12.535] [Forwarding server 52504] Got connection 1
[16:44:12.574] [Forwarding server 52504] Got connection 2

```
\* IP and (probably a) connection identifier was partially censored for security reasons

</details>

![image](https://user-images.githubusercontent.com/42657376/152865184-f05dc3b8-56df-468c-8142-519eab581b05.png)

Steps to Reproduce:

1. Adding the Host configuration and try to connect it
2. Getting the errors "Could not fetch remote enviroment" and "Failed to connect to the remote extension host server (Error: Refused to connect to unsupported server)" with the buttons `Open Developer Tools` and `Open in browser`
2.1 After click on "Open in browser" always returns the same code: "5554b12acf27056905806867f251c859323ff7e9"

I spend a time looking for similiar issues with ARM64 (like #60, #6200 and #3248) but none of these solved this problem. I remember that I can be able to connect into another server (with same settings on oracle cloud) but I think that I've selected another system image, probably some "Non-Oracle version", but I deleted it.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment] 2022-02-08 04:59
From your logs I see the connection being successful `[16:44:12.574] [Forwarding server 52504] Got connection 2
` 

Are you sure these are the same logs that produce that notification?

And does your remote meet these specifications? https://code.visualstudio.com/docs/remote/linux

**Comment by Bryceed** [comment] 2022-02-08 13:54
Hi, thanks for reply

**Q: Are you sure these are the same logs that produce that notification?**
A: Yes, this print was taken right after I paste the log here, same session (but every sessing happens the same thing)

**Q: And does your remote meet these specifications?**
A: It's a modified version made by Oracle to run the RHEL Server in a Aarch64 processor, I don't know if this applies to specifications or not, since this is a port from the x86 and use the version 7.9 (_and everything works exactly the same, just remote are having this problem_).

> [...] However, if you are using a non-standard configuration or downstream distribution of Linux, you may run into issues. This document provides information on requirements as well as tips to help you get up and running even if your configuration is only community-supported. [...] - https://code.visualstudio.com/docs/remote/linux
> <details><summary>Screenshot</summary><img src="https://user-images.githubusercontent.com/42657376/153000396-741bd3c2-5433-4795-8dc6-e1895066fcfa.png" /></details>
>
**Additional:** It display's me on the right side bar to select the remote folder, but, when I click on it, it just display my user home folder (locally, not from the remote), and opens my local folder as well.
<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/42657376/153000049-9e10eac5-7bd2-4c74-be60-e9e00fd0321c.png" />
</details>

**Comment by titianqx** [comment] 2022-02-18 08:12
same issue.
is that because i use oracle linux 8 on arm64?
[https://code.visualstudio.com/docs/remote/linux](https://code.visualstudio.com/docs/remote/linux)

**Comment by Bryceed** [comment] 2022-02-18 08:21
One "solution" that I found in the meantime, is to install aaPanel (_an open-source "cPanel" for aarch64-based processors_) and use it as a file explorer/editor and terminal. 

*I'm still having the same problem to use VSCode.

**Comment by tanhakabir** [comment] 2022-03-16 17:47
Could you share what you see in `/home/opc/.vscode-server/.5554b12acf27056905806867f251c859323ff7e9.log` and see if there are any errors in Dev Tools (command Toggle Dev Tools)

**Comment by alexdima** [comment] 2022-03-17 15:37
The error message `Refused to connect to unsupported server` indicates that the server failed to sign the challenge the client sends it in the initial handshake. This can happen if `vsda` fails to load on the remote server.  Unfortunately we are currently swallowing all errors related to loading up `vsda` [here](https://github.com/microsoft/vscode/blob/c56ff000d4327d5f674bbdbd269e3045c0ac017c/src/vs/server/node/remoteExtensionHostAgentServer.ts#L275-L276). I can improve the code to surface the `vsda` loading error, but ultimately this looks to be an environmental problem (i.e. the native node module `vsda` fails to load in this server environment).

cc @deepak1556 for ideas.

**Comment by alexdima** [comment] 2022-03-17 15:49
I've pushed a change via https://github.com/microsoft/vscode/commit/72169d1bfb74c317c0e6529e3a30a3970f87249f to improve logging in this case and log the `vsda` loading error in the server logs. Tomorrow's insiders will contain the change and it can be used to get a better understanding of what exactly is failing on the server.

**Comment by deepak1556** [comment] 2022-03-18 04:34
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2998 given this is seen on RHEL 7

To confirm, please try the following on the server 

```
> /home/opc/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/node
> require('vsda') // this will throw an error
```

Don't have any easy workarounds for now than for the user to install a newer gcc toolchain on the machine and specify it on the `LD_LIBRARY_PATH` so that the `GLIBCXX` requirements are met https://github.com/microsoft/vscode-remote-release/issues/2998#issuecomment-729590951. I started working on a concrete solution from our side for intel x64 platform https://github.com/microsoft/vscode/pull/142023, have plans to address the arm flavors soon.

**Closed by deepak1556** 2022-03-18 04:34 UTC
Labels: bug, ssh
