### ISSUE TITLE
VSCode becomes unusable when started while offline after an update is auto-installed

### ISSUE THREAD

**Issue by pluma** [microsoft/vscode-remote-release#5104] opened 2021-05-27 14:59 UTC
Issue Type: <b>Bug</b>

1. Have VSCode open with a WSL Remote workspace while online.
2. Wait for VSCode to find a new release and auto-download it in the background.
3. Exit VSCode and wait for VSCode to auto-update itself.
4. Go offline.
5. Reopen VSCode with a WSL Remote workspace.
6. Wait for the attempt to download the new Remote server in WSL times out.

Actual result:
VSCode tells me WSL is broken and won't let me edit my files. I'm filled with sadness because I now can't use VSCode anymore.

Expected result:
VSCode falls back to the old Remote server and logs a nagging message letting me know it's outdated. I'm filled with joy because I can still use VSCode without having to find a way to go online.

Extension version: 0.56.3
VS Code version: Code - Insiders 1.57.0-insider (a18ea9c9ec25c59e599ba3c2eb668315546dd269, 2021-05-26T05:14:06.346Z)
OS version: Windows_NT x64 10.0.21387
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.09GB free)|
|Process Argv|--crash-reporter-id 9a38bbe1-3cab-4c14-a142-51c3f2d146e0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3095)|
|Memory (System)|7.77GB (1.48GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805cf:30301675

```

</details>

**Comment by bamurtaugh** [comment] 2021-06-07 22:28
Thanks for reporting @pluma.

It's not possible to run an older server with a new client. So when you see the download, it's already too late if your client has been updated.

What we would need is that the normal VSCode updater also downloads the required servers are the same time. For that we would have the know what servers are needed (x64, amd, ...).

I'm going to close this as a duplicate of https://github.com/microsoft/vscode-remote-release/issues/3839. If I've misunderstood any part of your issue, please just let me know. Thank you!

**Closed by bamurtaugh** 2021-06-07 22:28 UTC
Labels: wsl
