### ISSUE TITLE
When opening a WSL terminal, could we set the user to login with

### ISSUE THREAD

**Issue by jchomarat** [microsoft/vscode-remote-release#3691] opened 2020-09-18 09:10 UTC
Hello,

It would be nice to set at the extension level which user to use when login to WSL.
If I look at the logs of the extension:

`
2020-09-18 07:14:43.023] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d bash.20.04 -e sh -c "[ -d ~/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
`
it would be nice to add the -u argument at the wsl.exe level.

I know we can set default user in the Linux, but, sometimes I want to user other account.

Best;

**Comment by aeschli** [comment] 2020-11-06 15:35
duplicate of https://github.com/microsoft/vscode-remote-release/issues/286

**Closed by aeschli** 2020-11-06 15:35 UTC
Labels: wsl
