### ISSUE TITLE
SSH Option "StrictHostKeyChecking" Is Ignored.

### ISSUE THREAD

**Issue by ooobii** [microsoft/vscode-remote-release#6839] opened 2022-06-17 22:09 UTC
- VSCode Version: May 2022 (v1.68)
- Local OS Version: Windows 11 (Build 22000.739)
- Remote OS Version: Ubuntu 20.04 LTS
- Remote Extension/Connection Type: SSH
- Logs:
```
[17:46:52.720] Log Level: 2
[17:46:52.721] remote-ssh@0.82.1
[17:46:52.721] win32 x64
[17:46:52.730] SSH Resolver called for "ssh-remote+[REDACTED].local", attempt 1
[17:46:52.730] "remote.SSH.useLocalServer": false
[17:46:52.731] "remote.SSH.showLoginTerminal": false
[17:46:52.731] "remote.SSH.remotePlatform": {"[REDACTED].local":"linux"}
[17:46:52.733] "remote.SSH.path": undefined
[17:46:52.733] "remote.SSH.configFile": undefined
[17:46:52.733] "remote.SSH.useFlock": true
[17:46:52.733] "remote.SSH.lockfilesInTmp": false
[17:46:52.733] "remote.SSH.localServerDownload": auto
[17:46:52.733] "remote.SSH.remoteServerListenOnSocket": false
[17:46:52.734] "remote.SSH.showLoginTerminal": false
[17:46:52.734] "remote.SSH.defaultExtensions": []
[17:46:52.734] "remote.SSH.loglevel": 2
[17:46:52.734] "remote.SSH.enableDynamicForwarding": true
[17:46:52.734] "remote.SSH.enableRemoteCommand": false
[17:46:52.735] "remote.SSH.serverPickPortsFromRange": {}
[17:46:52.735] "remote.SSH.serverInstallPath": {}
[17:46:52.749] SSH Resolver called for host: [REDACTED].local
[17:46:52.749] Setting up SSH remote "[REDACTED].local"
[17:46:52.765] Using commit id "30d9c6cd9483b2cc586687151bcbcd635f373630" and quality "stable" for server
[17:46:52.768] Install and start server if needed
[17:46:52.770] Checking ssh with "ssh -V"
[17:46:52.805] > OpenSSH_for_Windows_8.1p1, 
[17:46:52.806] > LibreSSL 3.0.2

[17:46:52.809] Running script with connection command: ssh -T -D 17239 "[REDACTED].local" bash
[17:46:52.811] Terminal shell path: C:\Windows\System32\cmd.exe
[17:46:53.005] > ]0;C:\Windows\System32\cmd.exe
[17:46:53.005] Got some output, clearing connection timeout
[17:46:53.064] > @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[17:46:53.072] > @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
> Someone could be eavesdropping on you right now (man-in-the-middle attack)!
> It is also possible that a host key has just been changed.
> The fingerprint for the ECDSA key sent by the remote host is
> SHA256:HuMVivzvdBFyluipSxx5Sc+9PDg+sQjm2POv7kOfQn4.
> Please contact your system administrator.
> Add correct host key in C:\\Users\\oobi/.ssh/known_hosts to get rid of this message.
> Offending ECDSA key in C:\\Users\\oobi/.ssh/known_hosts:13
> Password authentication is disabled to avoid man-in-the-middle attacks.
> Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
> Port forwarding is disabled to avoid man-in-the-middle attacks.
[17:46:53.073] "install" process failed: Error: Port forwarding is disabled
[17:46:53.073] Resolver error: Error: Port forwarding is disabled
	at Function.Create (c:\Users\oobi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.82.1\out\extension.js:1:585157)
	at d.onData (c:\Users\oobi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.82.1\out\extension.js:1:547433)
	at c:\Users\oobi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.82.1\out\extension.js:1:659837
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
[17:46:53.077] ------
```
### Steps to Reproduce:

**Preface:** This issue takes place with a virtual machine that can be deleted & re-created using automated scripts. The host key of the remote machine is guaranteed to change each time it is destroyed & re-created, so disabling the SSH host key verification allows VS code to connect to it without verifying the identity of the machine.

1. Connect to remote service outside of VSCode (so that the host key is stored in the SSH `known_hosts` file).
2. Create a remote host entry in the user scoped SSH config file:
```
Host DevEnv
  User vagrant
  HostName [REDACTED].local
```
3. Destroy the virtual machine.
4. Re-provision the virtual machine
5. Alter the .ssh config for the remote host to disable host key checking:
```diff
Host DevEnv
  User vagrant
  HostName [REDACTED].local
+  StrictHostKeyChecking no
```
6. Attempt to reconnect to the same remote host.

#### Expected Results
VSCode should mimic the behavior exhibited in Windows Terminal: The error message `WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!` is still visible, but the connection is not aborted.

#### Actual Results
VSCode detects this error message, and aborts the startup of `vscode-server`.

#### See Also
A bug report was already submitted at #2626, but was closed due to lack of response of the reporter. 

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by ooobii** [comment] 2022-06-17 22:17
#### Work Around Discovered
You can add an option for using a specific Known Hosts file in the SSH config for the host:
```diff
Host DevEnv
  User vagrant
  HostName [REDACTED].local
  StrictHostKeyChecking no
+  UserKnownHostsFile NUL

```
Honestly, this can probably be closed, because it is normal behavior for SSH to block remote port forwarding if the host key verification failed (even with strict host key checking is set to "no")...

**Comment by tanhakabir** [comment] 2022-06-20 04:15
Closing since this is expected behavior from SSH

**Closed by tanhakabir** 2022-06-20 04:15 UTC
Labels: ssh
