### ISSUE TITLE
wsl ubuntu 18.04 - unable to open code from /home but works from /mnt/c

### ISSUE THREAD

**Issue by githanna** [microsoft/vscode-remote-release#2909] opened 2020-04-29 16:42 UTC
- VSCode Version: 1.44.2
- OS Version: (WIN10) wsl ubuntu 18.04

Steps to Reproduce:

1. `cd ~` 
2. `code .`
3. nothing happens
4. `cd /mnt/c/`
5. `code .`
6. code opens

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment] 2020-05-01 14:41
Can you try `code . --verbose`?

**Comment by dharrison2010** [comment] 2020-05-01 19:04
Same issue here...
--verbose returns:
Invoking: /mnt/c/Users/<user_name>/AppData/Local/Programs/Microsoft VS Code/Code.exe resources/app/out/cli.js --verbose --folder-uri=vscode-remote://wsl+Ubuntu/mnt/c --remote=wsl+Ubuntu in /mnt/c/Users/<user_name>/AppData/Local/Programs/Microsoft VS Code

**Comment by dharrison2010** [comment] 2020-05-01 22:17
Funny thing...it works fine on my laptop, but not desktop.

**Comment by aeschli** [comment] 2022-12-15 13:51
I'm not able to reproduce. Closing the issue. Speak up if this is still a problem.

**Closed by aeschli** 2022-12-15 13:51 UTC
