### ISSUE TITLE
Remote-WSL does not work anymore after upgrade 

### ISSUE THREAD

**Issue by Coyote139** [microsoft/vscode-remote-release#1637] opened 2019-10-09 21:07 UTC
After upgrade to VC Code 1.39, Remote-WSL does not work correctly anymore. It was working fine with version 1.38.1. No change were made on the computer or in VS Code configuration or extensions.

After a while (less than 10 seconds) the following error window pops up. When trying to reload the window, the same error is popping up again and again.

![image](https://user-images.githubusercontent.com/43541530/66519689-1361ce80-eae8-11e9-949c-e5c492bc6824.png)

Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

WSL Remote 0..39.9

Windows 10 Pro Version 1903

WSL 1 - Ubuntu 18.04 LTS

**Comment by ahernandez-allegion** [comment] 2019-10-10 19:12
I've reported the same issue: https://github.com/microsoft/vscode-remote-release/issues/1646

**Comment by aeschli** [comment] 2019-10-14 12:43
marking as duplicate of #1646

**Closed by aeschli** 2019-10-14 12:43 UTC
