### ISSUE TITLE
[Feature Request] Add .devcontainer to the existing project in a more better way

### ISSUE THREAD

**Issue by kmehant** [microsoft/vscode-remote-release#634] opened 2019-06-10 16:22 UTC
#### Issue
Adding **.devcontainer** from git repo is not a clean and easy way for all developers.

#### Context
I have some points which we can implement in **visual studio code - insiders** as part of remote development. 
* Create a library of dev container definitions like **vs-code extensions** 
* Access the library through **visual studio code - insiders** directly without the present way of getting that from the git repo.
* Adding **.devcontainer** should be made as simple as adding vs-code extensions.
* On adding **.devcontainer** should trigger opening the project in the container.

**Comment by kmehant** [comment] 2019-06-11 04:21
@Chuxel  Thanks a lot for the explanation. I just missed a few features and now I am super happy that things are present already.

**Comment by kmehant** [comment] 2019-06-11 04:22
>That said, is there something it is not covering that you would like to see? Or are you hoping that the list would update the moment a merge is happening? (Right now the list is updated every release, but that's not the ultimate goal.)

@Chuxel 
I had little concern about this! I thought **vscode-dev-container** repo has got a CI pipeline to push the merged definitions immediately into the list on **vscode-insiders**. It would be nice if  **vscode-insiders** could fetch all the definitions from GitHub rather being hardcoded and added to the list on releases. The reason is there might be continuous fixes made to the definitions on GitHub and would be great if they are immediately reflected in production 😃

**Comment by egamma** [comment] 2019-06-11 08:46
>It would be nice if vscode-insiders could fetch all the definitions from GitHub rather being hardcoded and added to the list on releases. The reason is there might be continuous fixes made to the definitions on GitHub and would be great if they are immediately reflected in production 

pls see https://github.com/microsoft/vscode-remote-release/issues/425

**Comment by egamma** [comment] 2019-06-12 20:36
closing as a duplicate of #425

**Closed by egamma** 2019-06-12 20:36 UTC
Labels: containers, feature-request
