### ISSUE TITLE
Can't open container over tunnel

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#9135] opened 2023-10-25 22:44 UTC
Testing #9123

- Connect to tunnel, open folder with a devcontainer config
- Run "Reopen in container"
- Nothing happens
- This log entry is added each time, but nothing else

```
[10784 ms] Dev Containers 0.319.0 in VS Code 1.84.0-insider (18b7f75a9fab40499744c2e9c6ba9af64d5c6744).
[10783 ms] Start: Run: powershell -NoProfile -Command -
[10827 ms] Start: Run in host: echo $env:userprofile
[15371 ms] C:\Users\roblou
[15373 ms] 
[38262 ms] Start: Run: powershell -NoProfile -Command -
[38384 ms] Start: Run in host: echo $env:userprofile
[40595 ms] C:\Users\roblou
[40596 ms] 
```

**Comment by chrmarti** [comment] 2023-10-26 07:28
Make sure you are using the latest Insiders version for the CLI you start the tunnel with. (This looks like a bug that was only fixed with this Tuesday's Insiders.)

**Comment by roblourens** [comment] 2023-10-27 04:19
Nope, same thing with today's version

**Comment by chrmarti** [comment] 2023-10-27 09:12
Cannot reproduce. Just to be sure: The CLI you run `code-insiders tunnel` with is at the latest version?

**Comment by roblourens** [comment] 2023-10-30 19:12
Yes

**Comment by chrmarti** [comment] 2023-10-31 08:18
Remote-Tunnels is at the latest pre-release version I guess?

**Comment by chrmarti** [comment] 2023-10-31 10:37
Seeing this with the last Remote-Tunnels stable version (1.4.3). That doesn't have some of the bug fixes we need for Dev Containers. Could you retry with with the latest pre-release?

**Closed** 2023-11-07 12:27 UTC
Labels: bug, containers, info-needed
