### ISSUE TITLE
How to pass external binaries as docker build context to dockerfile

### ISSUE THREAD

**Issue by xerothermic** [microsoft/vscode-remote-release#1989] opened 2019-12-06 19:31 UTC
I have a use case where I need to copy private libraries as artifacts to my docker image. I see in the devcontainer.json we can specify context, but AFAICT, it can only refer to files that are also check in to the git repository. Currently, these binary artifacts are store either in Azure storage blob or Azure DevOps build artifact.

What is the recommended way to pass binary files for Dockerfile to consume?

One way I can see this work is if we support PreCreCommand like in #1045 so we can pull down the necessary files before invoking docker build. Any other suggestion?

**Comment by chrmarti** [comment] 2019-12-10 10:33
The Dockerfile's `ADD` instruction supports URLs. The `"context"` property should be able to point outside the Git repository's folders, have you tried that?

**Comment by xerothermic** [comment] 2019-12-12 23:06
Hi @chrmarti,

Yes, I know ADD instruction supports URL, but the file I want to retrieve requires authentication (from Azure storage blob). I'm thinking to use SAS Token to download specific artifacts but am unsure how to pass secret to the devcontainers

**Comment by chrmarti** [comment] 2019-12-13 08:23
#46 tracks the request for supporting build args and multi-stage builds.

Also check if pointing the context at a download folder would work for you.

Closing as duplicate of #46.

**Closed by chrmarti** 2019-12-13 08:23 UTC
Labels: containers, needs-more-info
