### ISSUE TITLE
terminals are unresponsive inside devcontainer

### ISSUE THREAD

**Issue by binarybox** [microsoft/vscode-remote-release#7964] opened 2023-02-03 14:59 UTC
Type: <b>Bug</b>

Since I updated to the new Version today every time when I want to open a terminal session in a devcontainer it takes around 5 minutes until it is open. 
First it is just blank and shows the error message "The connection to the terminal's pty host process is unresponsive, the terminals may stop working." and after around 5 minutes it opens.

When a Terminal session is open and I want to open another one, the connection to the first is also disconnected until the second one appears (also after around 5 minuts). 

I tried this also in the devcontainer example files and got the same error. Only with the node javascript and typescript it worked quickly. 

Extension version: 0.275.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 5.15.91-1-MANJARO
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.91-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.14GB (22.54GB free)|
|Process Argv|--unity-launch --crash-reporter-id 3b07ca01-c7f3-4ae1-a77a-98045fa2ee89|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: PiConDevContainer|
|OS|Linux x64 5.15.91-1-MANJARO|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2300)|
|Memory (System)|31.14GB (22.55GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30657576
89544117:30613380
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

**Comment by chrmarti** [comment] 2023-02-03 15:17
Does downgrading to Dev Containers 0.266.1 make it work again? (`F1` > `Extensions: Install Specific Version Of Extension...` and the rebuild the container with that.)

**Comment by kinghat** [comment] 2023-02-03 21:06
when i got back to `0.266.1` its basically the same thing but if i just let it hang when trying to run my tasks, it eventually worked itself out :man_shrugging: something is clearly wrong with the new version of extension or docker though.

**Comment by g-kartik** [comment] 2023-02-03 23:20
I am too getting the error `The connection to the terminal's pty host process is unresponsive, the terminals may stop working.` on attaching vs code to a running container.

Dev container version 0.275

Vs code details 
```
Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:29:17.766Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.15.91-1-MANJARO
Sandboxed: Yes
```

**Comment by alastair87** [comment] 2023-02-05 00:34
I'm on Fedora 37 and for me it works fine if I use moby-engine (Docker 20.x) from the Fedora repos but I get the error described using Docker 23.0 from the upstream.

```
Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:29:17.766Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.1.9-200.fc37.x86_64
Sandboxed: No
```

**Comment by alastair87** [comment] 2023-02-05 00:35
It does not happen on another up-to-date Ubuntu 22.04 machine running Docker 23.0 (that I don't have access to just now).

**Comment by alastair87** [comment] 2023-02-05 00:46
I wonder if the backing filesystem may be implicated - the Fedora system is using overlay2 backed by BTRFS, whilst the Ubuntu one is EXT4.

**Comment by chrmarti** [comment] 2023-02-06 07:43
There might be multiple issues here, lets track the one resulting in the `The connection to the terminal's pty host process is unresponsive, the terminals may stop working` notification here. This might be an issue with VS Code 1.75 since downgrading to the previous stable release of the Dev Containers extension didn't make it work. Could someone check if downgrading to VS Code 1.74 makes it work again? (To rule out the Docker update is causing this. That seems to be rolling out concurrently.)

Another issue triggered by a recent Docker update is tracked in https://github.com/microsoft/vscode-remote-release/issues/7958 and appears to be an issue with Docker itself.

**Comment by binarybox** [comment] 2023-02-06 08:00
Downgrading to 1.74.3 resolves the issue.

**Comment by ludovic-vaugeois-lumapps** [comment] 2023-02-06 08:23
I use F37 too, and I have to keep to a lower docker version, and a lower code version (1.74.3 instead of 1.75.0). Otherwise I've been having all sorts of Docker crashes, lost containes and "The connection to the terminal's pty host process is unresponsive, the terminals may stop working" from Code.

**Comment by kinghat** [comment] 2023-02-07 03:58
on F37 KDE Spin, downgrading vscode(to below) and necessary extensions, alleviates the issue.

> Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.1.9-200.fc37.x86_64
Sandboxed: No

**Comment by interob** [comment] 2023-02-07 11:35
> Downgrading vscode to 1.74.3 resolves the issue.

Same here; I am on Manjaro:
```
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.1.9-1-MANJARO
Sandboxed: No
```

Running 1.75, I observe the following in VS Code Terminal panel:

- the "Dev Containers" terminal is not named, its label remains blank. Sometimes that terminal works (shows output), some times not. Still, the local containers seems to be running fine
- any additional terminal I try to open does not respond and eventually gives the "The connection to the terminal's pty host process is unresponsive, the terminals may stop working." error

**Comment by meganrogge** [comment] 2023-02-08 17:01
@deepak1556 could it be related to the node-pty update?

**Comment by deepak1556** [comment] 2023-02-09 01:13
@meganrogge yeah the comments seem to point to the update as cause. I will have a look at it.

**Comment by deepak1556** [comment] 2023-02-13 04:40
I tried with the following devcontainer configuration from Ubuntu 22.04 host and the terminal opens up fine.

```
{
	"name": "Node.js",
	"image": "mcr.microsoft.com/devcontainers/javascript-node:0-18",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {}
	}
}
```

Can users facing the issue share their devcontainer configuration to help us repro the issue, thanks!

**Comment by kinghat** [comment] 2023-02-13 04:46
> I tried with the following devcontainer configuration from Ubuntu 22.04 host and the terminal opens up fine.
> 
> ```
> {
> 	"name": "Node.js",
> 	"image": "mcr.microsoft.com/devcontainers/javascript-node:0-18",
> 	"features": {
> 		"ghcr.io/devcontainers/features/node:1": {}
> 	}
> }
> ```
> 
> Can users facing the issue share their devcontainer configuration to help us repro the issue, thanks!

you can try from my repos devcontainer: https://github.com/kinghat/tabbed-card/blob/main/.devcontainer/devcontainer.json

ive only tested from fedora 37 though.

**Comment by deepak1556** [comment] 2023-02-13 06:44
I was able to confirm the issue when running the configuration https://github.com/microsoft/vscode-remote-release/issues/7964#issuecomment-1427333464 on Fedora 37 host.

**Comment by julian-poidevin-switchess** [comment] 2023-02-13 10:09
Having the same issue on `Linux 6.1.11-arch1-1 x86_64` with VSCode `1.75.1` and `ms-vscode-remote.remote-containers` `v0.275.1`

![image](https://user-images.githubusercontent.com/115158522/218429508-8342ea83-1991-4895-9634-d0a9dbea8f47.png)

**Comment by julian-poidevin-switchess** [comment] 2023-02-13 10:27
I can also confirm **not having** the issue with VSCode `1.74.3` and `ms-vscode-remote.remote-containers` `v0.266.1`.

**Comment by BerriJ** [comment] 2023-02-13 13:44
Having the same issue:

```
Version: 1.76.0-insider
Commit: f718f1ace394dba4255774ac3f1c9321f629f8ff
Date: 2023-02-13T05:29:38.257Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.1.11-arch1-1
Sandboxed: Yes
```

Using [this](https://github.com/BerriJ/devenv/blob/master/.devcontainer/devcontainer.json) container.

**Comment by deepak1556** [comment] 2023-02-13 13:55
Thanks everyone for the inputs, I was able to narrow down the issue in our dependent module. I will update here once a fix has been rolled out.

**Closed** 2023-02-13 17:23 UTC
Labels: bug

**Comment by deepak1556** [comment] 2023-02-13 17:46
Fix will be available with our nightly insiders build https://code.visualstudio.com/insiders from tomorrow PST

**Comment by IgnisDa** [comment] 2023-02-14 10:37
@deepak1556 When will it be available on the stable channel?

**Comment by jimmyw** [comment] 2023-02-25 21:49
Hi.

Im getting this bug. Tried the insiders release too wont help.

I did some digging, its a bash process that takes 100% CPU:
`/home/jimmy/workspace -1 -1 1 /bin/bash --init-file /vscode/vscode-server/bin/linux-x64/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh`

I did strace on it, and got this in a loop:

```
close(394121089)                        = -1 EBADF (Bad file descriptor)
close(394121090)                        = -1 EBADF (Bad file descriptor)
close(394121091)                        = -1 EBADF (Bad file descriptor)
close(394121092)                        = -1 EBADF (Bad file descriptor)
close(394121093)                        = -1 EBADF (Bad file descriptor)
close(394121094)                        = -1 EBADF (Bad file descriptor)
close(394121095)                        = -1 EBADF (Bad file descriptor)
close(394121096)                        = -1 EBADF (Bad file descriptor)
close(394121097)                        = -1 EBADF (Bad file descriptor)
close(394121098)                        = -1 EBADF (Bad file descriptor)
close(394121099)                        = -1 EBADF (Bad file descriptor)
close(394121100)                        = -1 EBADF (Bad file descriptor)
close(394121101)                        = -1 EBADF (Bad file descriptor)
close(394121102)                        = -1 EBADF (Bad file descriptor)
close(394121103)                        = -1 EBADF (Bad file descriptor)
close(394121104)                        = -1 EBADF (Bad file descriptor)
close(394121105)                        = -1 EBADF (Bad file descriptor)
close(394121106)                        = -1 EBADF (Bad file descriptor)
close(394121107)                        = -1 EBADF (Bad file descriptor)
close(394121108)                        = -1 EBADF (Bad file descriptor)
close(394121109)                        = -1 EBADF (Bad file descriptor)
close(394121110)                        = -1 EBADF (Bad file descriptor)
close(394121111)                        = -1 EBADF (Bad file descriptor)
close(394121112)                        = -1 EBADF (Bad file descriptor)
close(394121113)                        = -1 EBADF (Bad file descriptor)
close(394121114)                        = -1 EBADF (Bad file descriptor)
close(394121115)                        = -1 EBADF (Bad file descriptor)
close(394121116)                        = -1 EBADF (Bad file descriptor)
close(394121117)                        = -1 EBADF (Bad file descriptor)
close(394121118)                        = -1 EBADF (Bad file descriptor)
close(394121119)                        = -1 EBADF (Bad file descriptor)
close(394121120)                        = -1 EBADF (Bad file descriptor)
close(394121121)                        = -1 EBADF (Bad file descriptor)
```
Not sure if this helps.

**Comment by deepak1556** [comment] 2023-02-27 01:52
@jimmyw what version of insiders did you test with ? `code-insiders --version`

**Comment by jimmyw** [comment] 2023-02-27 15:14
@deepak1556 Sorry, my bad. I tried the insider's version of the extension and not vscode

With: 
` code-insiders --version
1.76.0-insider
ead95b4a7014d12ddcb2dd6ddcb16e73f1e4cd67
x64
`

And Devcontainer `v0.281.0`

I can confirm it works.

**Comment by davormilutinovic** [comment] 2023-03-02 12:43
Still having problems with 1.76.0. Reverted back to 1.74.3 and everything working fine. Terminal is responsive again, not waiting for additional 30+ seconds for prompt to show after each command, even simple echo one.

**Comment by interob** [comment] 2023-03-10 22:19
Same here: solved in 1.76.1

Version: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:31:31.010Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.1.12-1-MANJARO
Sandboxed: No

**Comment by legendarylion** [comment] 2023-03-11 13:58
Updating **did not resolve** this issue for me, downgrading back to 1.74 is the only method that seems to work:

Version: 1.76.1 (system setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to reproduce: 

1. Remote-SSH: Connect to Host...
2. Console reads (multiple):  Restarting the terminal because the connection to the shell process was lost... 
3. Toast warning throws: The connection to the terminal's pty host process is unresponsive, the terminals may stop working.

**Comment by fsinisi90** [comment] 2023-03-14 12:49
It doesn't work for me on macOS Monterey (12.6) even with the latest VS Code or VS Code Insiders.

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/12814926/225005474-8cdd7f4d-c3d1-4533-869f-7ef9e0a05aac.png">

```
Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/12814926/225005310-fa23b398-b530-428d-af27-c7a7a3ddbedf.png">

```
Version: 1.77.0-insider (Universal)
Commit: bbe8e872dc7c8899eb80bc4b650a6f090f4bc952
Date: 2023-03-14T05:23:55.404Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

System specs:

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2,4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  System Firmware Version:	1731.140.2.0.0 (iBridge: 19.16.16067.0.0,0)
  OS Loader Version:	540.120.3~22
```

**Comment by fsinisi90** [comment] 2023-03-20 15:14
@deepak1556

**Comment by cwittweg** [comment] 2023-03-23 09:06
Same here with:

`Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:53:46.528Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes`

Weirdly the issue only appears on certain remotes while on others the terminal works flawlessly.
