### ISSUE TITLE
Remote container "Cannot reconnect. Please reload the window" - Error confirming to extension

### ISSUE THREAD

**Issue by cj-clifton** [microsoft/vscode-remote-release#3835] opened 2020-10-12 03:57 UTC
When using the Remote Containers extension to run a workspace in a Docker container I get the message "Cannot reconnect. Please reload the window" sometimes after 5 minutes of the container being open and sometimes after hours. 
I have also experienced this with multiple workspaces.
I've tried reinstalling code, docker and the remote-container extension and have also removed all extensions except remote-containers.

In the ms-vscode-remote.remote-containers shutdownMonitor log file I get the message:
```
[2020-10-12T03:40:55.113Z] [PID 10702] [109955 ms] Error confirming to extension: Error: connect ECONNREFUSED /run/user/1000/vscode-remote-containers-cacdd8f74cbe6fcc23f72d9078af300e3716c623.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
```

The remoteContainers log file just has this (and then nothing below it)
```
[2020-10-12T03:40:38.829Z] [PID 10396] [93671 ms] [03:40:38] [::ffff:127.0.0.1][f3e4b624][ExtensionHostConnection] <117> Extension Host Process exited with code: null, signal: SIGABRT.
[2020-10-12T03:40:43.861Z] [PID 10396] [98703 ms] Start: Run: docker exec -i -u engineering -e VSCODE_REMOTE_CONTAINERS_SESSION=c1fc33aa-a48b-4a59-9496-2e6b6fa8577a1602473944614 525ad0ff42ee3d6e2da9f6f07b5496535bc482aa393deaf27e8a1df74c5c7d03 /home/engineering/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/node -e 
```

- VSCode Version: 1.50.0
- Local OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: Docker

Does this issue occur when you try this locally?: No (as its about the container disconnecting)

**Comment by s-hood** [comment] 2020-10-12 05:24
Update: It's recently happened twice while trying to set keyboard shortcuts (with the container open), however it has definitely happened in the past while not editing shortcuts..

**Comment by chrmarti** [comment] 2020-10-12 08:20
It is not clear why the Remote Extension Host process terminates with SIGABRT. Does the container run low on memory?

**Comment by s-hood** [comment] 2020-10-12 09:27
No it terminates even when idle with no processes running

**Comment by s-hood** [comment] 2020-10-13 01:09
Another occurance with some additional logs in `renderer1.log`:
```
[2020-10-12 12:12:50.063] [renderer1] [error] ENOENT: no such file or directory, scandir '/usr/share/code/resources/app/extensions': Error: ENOENT: no such file or directory, scandir '/usr/share/code/resources/app/extensions'
    at file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:585:531
    at async Promise.all (index 0)
    at async E.scanExtensions (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:585:779)
[2020-10-12 12:16:58.209] [renderer1] [info] [remote-connection][ExtensionHost][e2642…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-10-12 12:16:58.210] [renderer1] [info] [remote-connection][ExtensionHost][e2642…][reconnect] waiting for 5 seconds before reconnecting...
[2020-10-12 12:16:58.233] [renderer1] [info] [remote-connection][Management   ][35fd4…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-10-12 12:16:58.244] [renderer1] [info] [remote-connection][Management   ][35fd4…][reconnect] waiting for 5 seconds before reconnecting...
[2020-10-12 12:17:03.210] [renderer1] [info] [remote-connection][ExtensionHost][e2642…][reconnect] resolving connection...
[2020-10-12 12:17:03.251] [renderer1] [info] [remote-connection][Management   ][35fd4…][reconnect] resolving connection...
[2020-10-12 12:17:03.252] [renderer1] [info] [remote-connection][ExtensionHost][e2642…][reconnect] A promise cancelation error occurred while trying to reconnect, will try again...
[2020-10-12 12:17:03.252] [renderer1] [info] [remote-connection][ExtensionHost][e2642…][reconnect] waiting for 5 seconds before reconnecting...
[2020-10-12 12:17:03.301] [renderer1] [error] [remote-connection][Management   ][35fd4…][reconnect] An unknown error occurred while trying to reconnect, since this is an unknown case, it will be treated as a permanent error! Will give up now! Error:
[2020-10-12 12:17:03.301] [renderer1] [error] Error: Container no longer exists.
    at e.resolveAuthority (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4610:8)
    at async F._resolveAuthorityAgain (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5380:9)
[2020-10-12 12:17:03.551] [renderer1] [error] A system error occurred (ENOENT: no such file or directory, open '/usr/share/code/resources/app/out/vs/workbench/contrib/output/common/outputLinkComputer.js'): Error: ENOENT: no such file or directory, open '/usr/share/code/resources/app/out/vs/workbench/contrib/output/common/outputLinkComputer.js'
[2020-10-12 12:17:08.253] [renderer1] [error] [remote-connection][ExtensionHost][e2642…][reconnect] permanent failure occurred while running the reconnecting loop.
[2020-10-12 12:17:12.244] [renderer1] [error] command 'remote-containers.reopenLocally' not found: Error: command 'remote-containers.reopenLocally' not found
    at u._tryExecuteCommand (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4267:713)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4267:594
```
* Note that first one is 4 minutes before the second so probably unrelated?


Followed by an error in shutdownMonitor.log
```
[2020-10-12T04:17:13.346Z] [PID 22863] [1848618 ms] Start: Run: docker exec -i -u engineering 525ad0ff42ee3d6e2da9f6f07b5496535bc482aa393deaf27e8a1df74c5c7d03 /bin/sh
[2020-10-12T04:17:13.355Z] [PID 22863] [1848627 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink -f /proc/$pid/cwd ; xargs -0 < /proc/$pid/environ ; xargs -0 < /proc/$pid/cmdline ; } ; echo ; done 2>/dev/null
[2020-10-12T04:17:13.404Z] [PID 22863] [1848676 ms] Unexpected error: Shell server terminated (code: 1, signal: null)

Error: No such container: 525ad0ff42ee3d6e2da9f6f07b5496535bc482aa393deaf27e8a1df74c5c7d03
```

I'll set the log level to trace and see if there's more info next time it happens.

**Comment by chrmarti** [comment] 2020-10-13 05:55
There is `Error: Container no longer exists.` in the log, can you check if the container is still there next time this happens?

**Comment by s-hood** [comment] 2020-10-13 06:47
Yep the container is still there when I check via Docker. I can also close the "Please reload the window" message and immediately "reopen in container" which reconnects me without having to rebuild the container or anything.

**Comment by s-hood** [comment] 2020-10-14 00:27
```
[2020-10-13 22:20:43.154] [renderer1] [info] [remote-connection][ExtensionHost][7c003…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-10-13 22:20:43.154] [renderer1] [info] [remote-connection][ExtensionHost][7c003…][reconnect] waiting for 5 seconds before reconnecting...
[2020-10-13 22:20:48.154] [renderer1] [info] [remote-connection][ExtensionHost][7c003…][reconnect] resolving connection...
[2020-10-13 22:20:48.154] [renderer1] [info] [remote-connection][ExtensionHost][7c003…][reconnect] connecting to localhost:36251...
[2020-10-13 22:20:48.420] [renderer1] [error] [remote-connection][ExtensionHost][7c003…][reconnect][localhost:36251] received error control message when negotiating connection. Error:
[2020-10-13 22:20:48.421] [renderer1] [error] Error: Connection error: Unknown reconnection token.
    at D (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1910:228)
    at file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1902:926
    at c.fire (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
    at fire (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:454:878)
    at t.PersistentProtocol._receiveMessage (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:459:969)
    at file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:459:67
    at c.fire (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
    at g.acceptChunk (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:452:306)
    at file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:451:657
    at Socket.t (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:461:515)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[2020-10-13 22:20:48.426] [renderer1] [error] [remote-connection][ExtensionHost][7c003…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2020-10-13 22:20:48.426] [renderer1] [error] Error: Connection error: Unknown reconnection token.
    at D (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1910:228)
    at file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1902:926
    at c.fire (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
    at fire (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:454:878)
    at t.PersistentProtocol._receiveMessage (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:459:969)
    at file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:459:67
    at c.fire (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
    at g.acceptChunk (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:452:306)
    at file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:451:657
    at Socket.t (file:///snap/code/47/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:461:515)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
``

**Comment by chrmarti** [comment] 2020-10-14 08:34
`Unknown reconnection token.` could indicate that the VS Code Server restarted and the window now tries to connect with a token that is not known anymore. Do you have a second VS Code window connecting to the same container? That would be one way to explain a restart of the VS Code Server (if that is indeed the cause for the error).

**Comment by s-hood** [comment] 2020-10-14 09:40
@chrmarti Nope, just the one window using the container.

**Comment by chrmarti** [comment] 2020-11-16 14:49
Could you attach your Dockerfile and devcontainer.json?

**Comment by cj-l** [comment] 2020-11-17 02:30
Dockerfile:
```
FROM nvidia/cuda:10.1-cudnn7-devel

LABEL "maintainer"=""
LABEL "version"="0.0"

ARG INSTALL_ZSH="false"
ARG UPGRADE_PACKAGES="false"
ARG INSTALL_OH_MYS="false"

ARG USERNAME=engineering
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV LANG C.UTF-8

COPY library-scripts/*.sh /tmp/library-scripts/

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "${INSTALL_OH_MYS}" \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts

RUN rm -rf /var/lib/apt/lists/* \
    /etc/apt/sources.list.d/cuda.list \
    /etc/apt/sources.list.d/nvidia-ml.list

RUN apt-get update && \
    ${APT_INSTALL} \
    build-essential \
    apt-utils \
    ca-certificates \
    wget \
    git \
    vim \
    libssl-dev \
    curl \
    unzip \
    unrar \
    # pdftotext dependencies
    gcc \
    python3-dev \
    build-essential \
    libpoppler-cpp-dev \
    pkg-config

USER engineering

ARG CONDA_INSTALL_PATH=/home/${USERNAME}/miniconda3
ENV PATH=${CONDA_INSTALL_PATH}/bin:${PATH}

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p ${CONDA_INSTALL_PATH} && \
    rm ~/miniconda.sh && \
    ${CONDA_INSTALL_PATH}/bin/conda clean -tipsy && \
    echo ". ${CONDA_INSTALL_PATH}/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find ${CONDA_INSTALL_PATH}/ -follow -type f -name '*.a' -delete && \
    find ${CONDA_INSTALL_PATH}/ -follow -type f -name '*.js.map' -delete && \
    ${CONDA_INSTALL_PATH}/bin/conda clean -afy

RUN ${CONDA_INSTALL_PATH}/bin/conda create -n changepath python=3.7.3

RUN ${CONDA_INSTALL_PATH}/bin/conda install -n changepath -y cudatoolkit=10.1
RUN /bin/bash -c "source activate changepath && pip install tensorflow==2.3.0 "
RUN /bin/bash -c "source activate changepath && pip install pytest pytest-cov "
RUN /bin/bash -c "source activate changepath && pip install ipykernel " # for vscode ipykernel

EXPOSE 6006 8888
```

devcontainer.json
```
{
    "name": "changepath-development",
    "dockerFile": "Dockerfile",
    "runArgs": [
        "--gpus",
        "all",
        "--name=changepath-development"
    ],
    "forwardPorts": [
        6006,
        8888
    ],
    "extensions": [
        "ms-python.vscode-pylance",
        "ms-python.python",
        "njpwerner.autodocstring",
        "yzhang.markdown-all-in-one",
        "ms-python.vscode-pylance"
    ],
    "settings": {
    	"files.watcherExclude": {
            "**/changepath/data/**": true
        }
    },
    "postCreateCommand": [
        "bash",
        ".devcontainer/postcreate/install.sh",
        "changepath-workspace",
        "changepath"
    ],
    "remoteUser": "engineering",
}
```

install.sh
```
#!/bin/sh
source activate $2 && pip install -e /workspaces/$1/$2/
echo "Installed libraries into required conda env"
```

**Comment by chrmarti** [comment] 2020-11-17 08:03
I assume you are using the NVIDIA Container Toolkit. Not sure how that affects how the container is run.

**Comment by cj-l** [comment] 2020-11-17 10:48
Yep using that toolkit. Will test it with a Dockerfile that doesn't use NVIDIA's.

**Comment by cj-l** [comment] 2020-11-22 11:41
I have tried building my dockerfile with `FROM python:3.8` rather than the NVIDIA one above and still get the 'Cannot Reconnect' error after running a 3/4 hour process.

**Comment by eburmicz** [comment] 2020-12-05 11:38
I get the same error consistently after 1 minute of  my container being up and no clear error sign.

**Comment by chrmarti** [comment] 2020-12-07 07:59
@eburmicz Could you append the log (`F1` > `Remote-Containers: Show Log`) from when it fails and your `devcontainer.json`, `Dockerfile` and maybe `docker-compose.yml`?

**Comment by StefanBrand** [comment] 2021-03-25 10:22
A symptom that I have observed is that the "Test: Python" panel freezes and commands are not reflected in the list anymore (e.g. when I press "Run All Tests", no spinning wheel appears and test results are not annotated to the respective tests in the list.

When I close VSCode and start it again, I cannot connect to the container anymore. ("Cannot reconnect. Please reload the window") Reloading the window does not help, btw; the VSCode still cannot reconnect.


-    VSCode Version: 1.54.3
-    Local OS Version: Ubuntu 20.04.1 LTS
-    Remote Extension/Connection Type: Docker

**Comment by chrmarti** [comment] 2021-03-25 16:22
@StefanBrand Could you append the log (`F1` > `Remote-Containers: Show Log`) from when it fails and your `devcontainer.json`, `Dockerfile` and maybe `docker-compose.yml`?

**Comment by cj-l** [comment] 2021-03-26 00:50
Monitoring this for some time now the issue for me seems most correlated with running lengthy processes through the Python Interactive Window that print lots of output. If I instead run these processes in a python terminal the container and vs code seem much happier

**Comment by StefanBrand** [comment] 2021-03-29 11:26
> @StefanBrand Could you append the log (`F1` > `Remote-Containers: Show Log`) from when it fails and your `devcontainer.json`, `Dockerfile` and maybe `docker-compose.yml`?

`Remote-Containers: Show Log` did not work (nothing happened when clicking on it). Therefore I closed the remote connection and ran `Remote-Containers: Show Previous Log`.

### Log

[remoteContainers-2021-03-29T09-24-50.761Z.log](https://github.com/microsoft/vscode-remote-release/files/6221333/remoteContainers-2021-03-29T09-24-50.761Z.log)


### `devcontainer.json`
```
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.101.1/containers/docker-existing-dockerfile
{
    "name": "project",
    "dockerComposeFile": [
        "../docker-compose.yml",
        "docker-compose.extend.yml"
    ],
    "service": "project",
    //"runServices": ["project"],
    "workspaceFolder": "/srv/service",
    // Set *default* container specific settings.json values on container create.
    "settings": {
        "terminal.integrated.shell.linux": null,
        "python.linting.enabled": true,
        "python.linting.pylintEnabled": true
    },
    // Add the IDs of extensions you want installed when the container is created.
    "extensions": [
        "ms-python.python",
        "cameron.vscode-pytest",
        "tombonnike.vscode-status-bar-format-toggle",
        "ms-python.vscode-pylance",
        "eamodio.gitlens",
        "mishkinf.goto-next-previous-member"
    ],
    //"runArgs": [
    //	"--env-file",
    //	"test_environment.env"
    //],
    // Use 'forwardPorts' to make a list of ports inside the container available locally.
    // "forwardPorts": [],
    // Uncomment the next line to run commands after the container is created - for example installing git.
    //"postCreateCommand": "python3 -m pip install rope",
    // Uncomment when using a ptrace-based debugger like C++, Go, and Rust
    // "runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ],
    // Uncomment to use the Docker CLI from inside the container. See https://aka.ms/vscode-remote/samples/docker-in-docker.
    // "mounts": [ "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind" ],
    // Uncomment to connect as a non-root user. See https://aka.ms/vscode-remote/containers/non-root.
    "remoteUser": "root"
}
```

### `Dockerfile`
```
FROM python:3.9.1

WORKDIR /srv/service

ENV DJANGO_SETTINGS_MODULE project.settings

RUN apt-get update && apt-get install -y python3-gdal

ADD another_project another_project
ADD requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

USER www-data

CMD ["./migrate_and_run_gunicorn.sh"]

ADD . .
```

### `docker-compose.yml`

```
version: "3.7"
services:
    project:
        build: .
        ports:
        - 8000:8000
        volumes:
        - .:/srv/service
        - ./test_data/metainfo.yaml:/srv/service/metainfo.yaml
        environment:
          DB_USER: "user"
          DB_DATABASE: "db"
          DB_PASSWORD: "supersecret"
          DB_HOST: "db"
          DB_SCHEMA: "test"
        depends_on: ["db"]
        command:
        - "bash"
        - "-c"
        - >-
          while !</dev/tcp/db/5432; do echo 'waiting for db'; sleep 1; done;
          ./manage.py migrate ;
          ./manage.py insert_dummy_data ;
          gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --reload --env DJANGO_DEBUG=True

    db:
        image: postgis/postgis:13-3.1
        environment:
          POSTGRES_USER: "user"
          POSTGRES_PASSWORD: "supersecret"
          POSTGRES_DB: "db"
```

### `docker-compose.extend.yml`

```
version: "3.7"
services:
    project:
        command: /bin/sh -c "while sleep 1000; do :; done"
```

**Comment by pmh722** [comment] 2021-08-11 19:51
> Monitoring this for some time now the issue for me seems most correlated with running lengthy processes through the Python Interactive Window that print lots of output. If I instead run these processes in a python terminal the container and vs code seem much happier

I have EXACTLY the same problem. Long running script with lots of output. Works fine in REPL if I truncate the data. Works fine in terminal with full data. Consistently crashes in REPL with full data.

**Comment by OmkarMehta** [comment] 2021-08-11 21:14
I have the same issue. I tried reinstalling vs code, built new containers. But, the problem exists.

**Comment by chrmarti** [comment] 2021-08-12 08:48
@alexdima You mentioned heavy work loads could block the server process for so long that the client would detect a disconnection. I wonder if that's what's happening here.

@pmh722 Are the outputs that seem to trigger this text in the terminal or image files or something else?

**Comment by StefanBrand** [comment] 2021-08-18 08:13
I was able to gather this interesting log from `Log (Window)`:

```
[2021-08-18 10:02:12.880] [renderer2] [info] [remote-connection][Management   ][b0afa…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2021-08-18 10:02:12.881] [renderer2] [error] {"isTrusted":true}
[2021-08-18 10:02:12.882] [renderer2] [info] [remote-connection][Management   ][b0afa…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-08-18 10:02:12.883] [renderer2] [info] [remote-connection][Management   ][b0afa…][reconnect] resolving connection...
[2021-08-18 10:02:13.019] [renderer2] [error] [remote-connection][Management   ][b0afa…][reconnect] A RemoteAuthorityResolverError occurred while trying to reconnect. Will give up now! Error:
[2021-08-18 10:02:13.020] [renderer2] [error] Error: Container is no longer running.
    at br.resolveAuthority (vscode-file://vscode-app/snap/code/71/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1583:8088)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async tl._resolveAuthorityAgain (vscode-file://vscode-app/snap/code/71/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2905:6307)
```

Using `docker ps` I can see that VSCode starts the containers (find `docker-compose.yml` in [this comment above](https://github.com/microsoft/vscode-remote-release/issues/3835#issuecomment-809302298)), but they are down when the "Cannot reconnect." message appears.

Starting the containers with `docker-compose -f docker-compose.yml -f .devcontainer/docker-compose.extend.yml up` works just fine and they stay up:

```
CONTAINER ID   IMAGE                    COMMAND                  CREATED              STATUS              PORTS                                 NAMES
5ee84e5c8716   project      "/bin/sh -c 'while s…"   About a minute ago   Up About a minute   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp       project_project_1
e8cb2f13866b   postgis/postgis:13-3.1   "docker-entrypoint.s…"   24 hours ago         Up About a minute   5432/tcp                           project_db_1
```

**Comment by howar31** [comment] 2022-03-13 08:43
I still have this issue now.  And it happened so constantly that I cannot even work with devcontainer.

**Comment by drod3763** [comment] 2022-03-22 15:41
This affects me as well. Seems like its within minutes of starting the container. Sometimes multiple times, it will reload and reconnect and then disconnect again quickly.

**Comment by chrmarti** [comment] 2022-03-23 08:12
@howar31 @drod3763 Could you open new issues with all details (versions, logs)? There is a chance you are seeing different problems than discussed here. Thanks.

**Comment by david-engelmann** [comment] 2022-10-18 15:24
Still struggling with this daily, should I open a new issue?

**Comment by chrmarti** [comment] 2023-12-12 13:55
Never got to the bottom of this, please open new issues for a fresh start if this is still a problem. Thanks.

**Closed by chrmarti** 2023-12-12 13:55 UTC
Labels: bug, containers, plan-review
