### ISSUE TITLE
Remote server temp files take up too much space and can't be removed

### ISSUE THREAD

**Issue by slikts** [microsoft/vscode-remote-release#8769] opened 2023-07-28 07:08 UTC
- VSCode Version: 1.18
- Local OS Version: Windows 11
- Remote OS Version: WSL Ubuntu
- Remote Extension/Connection Type: WSL

![image](https://github.com/microsoft/vscode-remote-release/assets/137872/2f605d8f-f8fc-430b-99d7-79a8ffd81858)

The accumulated remote server temp files are taking up 36 GB, and most users would probably be caught unaware by this.

**Comment by slikts** [comment] 2023-07-29 16:35
I deleted the temp files, and today they're back with a vengeance are taking up 95 GB.

![image](https://github.com/microsoft/vscode-remote-release/assets/137872/80494324-0a19-43fa-b74b-88bf8bb48110)

**Comment by aeschli** [comment] 2023-12-18 15:15
duplicate of https://github.com/microsoft/vscode-remote-release/issues/9036

**Closed by aeschli** 2023-12-18 15:15 UTC
Labels: wsl
