### ISSUE TITLE
Cannot connect to remote host on Mac

### ISSUE THREAD

**Issue by msaito3** [microsoft/vscode-remote-release#613] opened 2019-06-08 12:34 UTC
Issue Type: <b>Bug</b>

Cannot connect to remote host.

Reproducing Procedure：
1. choose Remote-SSH: Connect to Host...
2. enter remote host name
- I entered "micro1" that is a Ubuntu18 host
3. Some dialog appeared around right bottom of window for a moment.
- not remote host connection
- I don't understand what happened (no error message)

NOTE:
I can connect to "micro1" host on VSCode terminal.

OS: macOS 10.14.5
VSCode version 1.35.0

Extension version: 0.15.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (5.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MotoX450** [comment] 2019-06-17 04:44
Duplicate of #24

**Comment by roblourens** [comment] 2019-06-19 02:37
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Closed** 2019-06-26 03:19 UTC
Labels: needs-more-info
