### ISSUE TITLE
The missing extension icons in side bar

### ISSUE THREAD

**Issue by penghl** [microsoft/vscode-remote-release#924] opened 2019-07-08 02:14 UTC
Issue Type: <b>Bug</b>

1. Open VS Code from remote, for me, it is wsl.
2. Then the third party extension icons in side bar are missed.
3. Open the developer tools, it logs that serveral errors are occurred, for example: 'Fail to load resource: vscode-remote://wsl:ubuntu-18.04/home/hlp/.vscode-server/extensions/alefragnani.bookmarks-10.4.4/images/bookmark-activity-bar.svg net::ERR_NOT_IMPLEMENTED'.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by walkafwalka** [comment] 2019-07-09 06:01
I am getting the same issue.

Error:
```
GET vscode-remote://wsl%2Bubuntu/home/awalker/.vscode-server-insiders/bin/4f3262dd1bba349e5be1e415a60874662da2c038/extensions/git/resources/icons/dark/clean.svg net::ERR_NOT_IMPLEMENTED
```
VSCode:
```
Version: 1.37.0-insider (user setup)
Commit: 4f3262dd1bba349e5be1e415a60874662da2c038
Date: 2019-07-08T23:49:44.487Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18932
```
WSL:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by pography** [comment] 2019-07-09 13:20
This is happening to me as well. Potentially a duplicate of #687 

Icons appears when first opening a window and disappear when connected to WSL. Affects third-party extension icons in activity bar and version control icons within the sidebar.

**Comment by walkafwalka** [comment] 2019-07-09 22:13
@pography, I think you are right. @jrieken, I pasted a bit more details on my environment and the error and am willing to provide any more details to get this working.

**Comment by misolori** [comment] 2019-07-09 22:37
Yea, this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/687

**Closed by misolori** 2019-07-09 22:37 UTC
