### ISSUE TITLE
Remote Explorer shows no Containers using SSH

### ISSUE THREAD

**Issue by KitKat7** [microsoft/vscode-remote-release#2489] opened 2020-03-07 11:38 UTC
I'm using vscode-remote for developing inside a container on a remote Docker host using SSH, following the instruction [a-basic-remote-example](https://code.visualstudio.com/docs/remote/containers-advanced#_a-basic-remote-example).

However, on the **Remote Explorer** bar, there is nothing showed in the **"Containers", "Details (Containers)" and "Forwarded ports" views**. The Remote Explorer Bar icon spins forever as the same mentioned in https://github.com/microsoft/vscode-remote-release/issues/2028#issue-537886694 and https://github.com/microsoft/vscode-remote-release/issues/1935#issuecomment-561187205 (Windows).

**Attach to Running Containers...** works, and iIcan attach the containers on my remote Docker host using SSH and find the remote docker information in the Docker bar, but just nothing in the Remote Explorer bar. This issue appears both on mac OS and Ubuntu 18.04.

A workaround is to use an [SSH tunnel](https://code.visualstudio.com/docs/remote/troubleshooting#_using-an-ssh-tunnel-to-connect-to-a-remote-docker-host). But directly using SSH is more convenient.

---

- VSCode Version: 1.43.0-insider or 1.42.1
- Local OS Version: mac OS 10.15.3 or Ubuntu 18.04
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Set `"docker.host":"ssh://your-remote-user@your-remote-machine-fqdn-or-ip-here"` in the `settings.json` and reload the window.
2. Click the **Remote Explorer** icon on the activity bar and select to show the **Containers** view.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment] 2020-10-13 13:25
Should be working now.

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2481

**Closed by chrmarti** 2020-10-13 13:25 UTC
