### ISSUE TITLE
Remote URI Handler does not work for files

### ISSUE THREAD

**Issue by anuragbanerjee** [microsoft/vscode-remote-release#4333] opened 2021-01-21 01:53 UTC
`vscode://vscode-remote/ssh-remote+myRemoteHostname/some/remote/path/folder/`
The result is a VSCode window with the remote folder open. Works as expected.

`vscode://vscode-remote/ssh-remote+myRemoteHostname/some/remote/path/file.txt`
It attempts to open the file as a folder (you can tell in the explorer panel & window titlebar), but then shortly fails to open the file. It connects to the remote host successfully and I can use CMD+O to open the file, but it did not open on launch like how it does with folders in the first example.

I'm using vscode-remote-ssh extension version v0.62.0. I noticed another user commenting similar issues on this related issue https://github.com/microsoft/vscode-remote-release/issues/656#issuecomment-601421405

**Comment by roblourens** [comment] 2021-01-21 05:50
I think this won't currently work because we need to know the window's workspace folder path before it opens, and here we would have to connect in order to check whether the target is a file or folder first. Would be nice if it did though.

**Comment by aeschli** [comment] 2021-01-21 08:24
Duplicate of https://github.com/microsoft/vscode/issues/108257

**Closed by aeschli** 2021-01-21 08:24 UTC
Labels: ssh
