### ISSUE TITLE
SSH connection without TCPforwarding

### ISSUE THREAD

**Issue by alu0100990539** [microsoft/vscode-remote-release#6008] opened 2021-12-07 11:27 UTC
Hello, I tried to conect via ssh to my host but I can´t enable TCP Forwarding (the contract of hosting don´t let modify the /etc/ssh/sshd_config file, where "AllowTCPforwarding" is "no")...

How can I connect via ssh with VSCode?

Thanks.

**Comment by tanhakabir** [comment] 2021-12-07 16:45
Sorry this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/92

**Closed by tanhakabir** 2021-12-07 16:45 UTC
Labels: ssh
