### ISSUE TITLE
Settings for all SSH hosts (Host *) cause VSCode to not parse include files

### ISSUE THREAD

**Issue by gjulianm** [microsoft/vscode-remote-release#5933] opened 2021-11-22 14:32 UTC
- VSCode Version: 1.62.0 (Universal)
- Local OS Version: macOS Mojave 10.14.6
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH
- Logs: N/A

Steps to Reproduce:

1. Create a ~/.ssh/config file
2. Add an `Include X` line with SSH hosts on that file, VSCode correctly shows all hosts in the Remote Explorer Window.
3. Add a `Host *` entry in ~/.ssh/config, for example:

``` 
Host *
	ControlMaster auto
	ControlPath /tmp/%r@%h:%p
```

4. See how all hosts present in the included files disappear in the Remote Explorer window. They can still be used to connected through the command palette. Also, hosts present in ~/.ssh/config still appear in the window too.

**Comment by tanhakabir** [comment] 2021-12-10 20:54
Hm I'm not reproducing this. what does your full config look like?

```
Include ./sandbox
Include ./azure

Host *
	ControlMaster auto
	ControlPath /tmp/%r@%h:%p

Host second
  HostName 147.182.250.143
  User root
```

And I do see the hosts from `sandbox` and `azure` in the list of Hosts to connect to

**Comment by biyiklioglu** [comment] 2021-12-12 21:22
You can try swapping the order of  `Include `and `Host *` lines.

```
Host *
	ControlMaster auto
	ControlPath /tmp/%r@%h:%p

Include ./sandbox
Include ./azure

Host second
  HostName 147.182.250.143
  User root
```
 should not work in your case.

Placing the `Include `  line(s) after the `Host *`  directive might not be a desired behavior but it somehow works with the standard OpenSSH utilities.

**Comment by gjulianm** [comment] 2021-12-13 10:45
I can confirm what @biyiklioglu said, the problem is apparently in the order of `Host *` and `Include` lines. Swapping the order in my case made it work again.

**Comment by tanhakabir** [comment] 2021-12-13 18:27
Ah I see, this is actually a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4339 where Includes seem to only work at the top of the file.

I'll close this issue to track progress there and see if I have some time this month to tackle it.

**Closed by tanhakabir** 2021-12-13 18:27 UTC
Labels: bug, ssh, needs more info
