### ISSUE TITLE
Remote connection never starts any login or interactive shells, so it's impossible to update environment variables (for instance, so code server has correct PATH and DOTNET_ROOT)

### ISSUE THREAD

**Issue by bavis-m** [microsoft/vscode-remote-release#6627] opened 2022-04-18 22:03 UTC
- VSCode Version: 1.66.2
- Local OS Version: 10.0.19044 Build 19044
- Remote OS Version: Slackware 14.2+ (linux kernel 5.10.28)
- Remote Extension/Connection Type: SSH
- Logs: https://pastebin.com/J6wr7vXB

Steps to Reproduce:
1. Setup an SSH remote.
2. Connect to your remote without code server already running
3. Logs show the extensions invokes ssh as such: `ssh -T -D 1472 HOSTNAME bash`, which runs bash as a *non-login, non-interactive* shell. This prevents *any* startup files from being sourced. (Some versions of bash are supposed to be able to 'detect' ssh and turn on a login shell automatically, but this behaviour can't be relied on, and doesn't seem to happen in my environment)

This extension should run bash as `bash --login` to enable the appropriate environments, or allow for some sort of custom configuration to setup the dotnet environment.

**Comment by bamurtaugh** [comment] 2022-04-18 22:48
Thanks for filing. I believe this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/1671? If so, we can close this issue and track there.

**Comment by bavis-m** [comment] 2022-04-18 23:14
Sounds good, I searched the issue but somehow missed the 2nd page of
results.

**Closed** 2022-04-18 23:14 UTC
Labels: ssh, needs more info
