### ISSUE TITLE
Google Cloudshell with remote ssh: Failed to parse remote port from server output

### ISSUE THREAD

**Issue by kis87988** [microsoft/vscode-remote-release#6419] opened 2022-03-05 00:44 UTC
- VSCode Version: 1.65.0
- Local OS Version: Mac OS Montery
- Remote OS Version: Google cloudshell
- Remote Extension/Connection Type: SSH
- Logs:
```log
[16:35:59.247] Log Level: 2
[16:35:59.248] remote-ssh@0.76.1
[16:35:59.248] darwin x64
[16:35:59.255] SSH Resolver called for "ssh-remote+cloudshell", attempt 1
[16:35:59.256] "remote.SSH.useLocalServer": true
[16:35:59.256] "remote.SSH.path": undefined
[16:35:59.257] "remote.SSH.configFile": undefined
[16:35:59.257] "remote.SSH.useFlock": true
[16:35:59.257] "remote.SSH.lockfilesInTmp": false
[16:35:59.257] "remote.SSH.localServerDownload": off
[16:35:59.258] "remote.SSH.remoteServerListenOnSocket": false
[16:35:59.258] "remote.SSH.showLoginTerminal": false
[16:35:59.258] "remote.SSH.defaultExtensions": []
[16:35:59.258] "remote.SSH.loglevel": 2
[16:35:59.259] "remote.SSH.enableDynamicForwarding": true
[16:35:59.259] "remote.SSH.enableRemoteCommand": false
[16:35:59.259] "remote.SSH.serverPickPortsFromRange": {}
[16:35:59.259] "remote.SSH.serverInstallPath": {}
[16:35:59.275] SSH Resolver called for host: cloudshell
[16:35:59.276] Setting up SSH remote "cloudshell"
[16:35:59.282] Acquiring local install lock: /var/folders/4q/12345/T/vscode-remote-ssh-682a4d30-install.lock
[16:35:59.288] Looking for existing server data file at /Users/login_user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-682a4d30-12345-0.76.1/data.json
[16:35:59.289] Using commit id "12345" and quality "stable" for server
[16:35:59.292] Install and start server if needed
[16:35:59.301] PATH: /Users/login_user/google-cloud-sdk/bin:/Users/login_user/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Users/login_user/.local/bin:/usr/local/opt/fzf/bin
[16:35:59.302] Checking ssh with "ssh -V"
[16:35:59.316] > OpenSSH_8.6p1, LibreSSL 2.8.3

[16:35:59.323] > OpenSSH_8.6p1, LibreSSL 2.8.3

[16:35:59.328] askpass server listening on /var/folders/4q/12345/T/vscode-ssh-askpass-12345.sock
[16:35:59.349] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/4q/12345/T/vscode-ssh-askpass-12345.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51836","-o","ConnectTimeout=30","cloudshell"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/login_user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-682a4d30-12345-0.76.1/data.json"}
[16:35:59.349] Local server env: {"SSH_AUTH_SOCK":"/var/folders/4q/12345/T//ssh-LcfqtONFpXWb/agent.4040","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.oENXQoWHRj/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/4q/12345/T/vscode-ssh-askpass-12345.sock"}
[16:35:59.350] Spawned 70539
[16:35:59.458] > local-server-1> Spawned ssh, pid=70542
[16:35:59.467] stderr> Pseudo-terminal will not be allocated because stdin is not a terminal.
[16:35:59.472] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[16:36:01.706] stderr> debug1: Server host key: ssh-rsa SHA256:12345
[16:36:02.125] stderr> Authenticated to cloudshell (via proxy).
[16:36:02.399] > Welcome to Cloud Shell! Type "help" to get started.
> To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
[16:36:02.441] > ready: aa4c7bf72142
[16:36:02.475] > Linux 5.10.90+ #1 SMP Sat Feb 12 10:05:14 UTC 2022
[16:36:02.475] Platform: linux
[16:36:02.508] > /bin/bash
[16:36:02.508] Shell: bash
[16:36:02.618] > aa4c7bf72142: running
[16:36:02.659] stderr> cat: '/lib/x86_64-linux-gnu/libstdc++.so.6'$'\n''/lib32/libstdc++.so.6': No such file or directory
[16:36:02.659] stderr> mainScriptWrapper:185: bad math expression: operand expected at `*100 +  '
[16:36:02.661] stderr> Transferred: sent 19512, received 4828 bytes, in 0.5 seconds
[16:36:02.661] stderr> Bytes per second: sent 36589.3, received 9053.6
[16:36:02.662] > Missing GLIBCXX >= 3.4.18!
> Found versions 
> local-server-1> ssh child died, shutting down
[16:36:02.666] Local server exit: 0
[16:36:02.666] Received install output: local-server-1> Spawned ssh, pid=70542
Pseudo-terminal will not be allocated because stdin is not a terminal.
OpenSSH_8.6p1, LibreSSL 2.8.3
Authenticated to cloudshell (via proxy).
Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
ready: aa4c7bf72142
Linux 5.10.90+ #1 SMP Sat Feb 12 10:05:14 UTC 2022
/bin/bash
aa4c7bf72142: running
cat: '/lib/x86_64-linux-gnu/libstdc++.so.6'$'\n''/lib32/libstdc++.so.6': No such file or directory
mainScriptWrapper:185: bad math expression: operand expected at `*100 +  '
Transferred: sent 19512, received 4828 bytes, in 0.5 seconds
Bytes per second: sent 36589.3, received 9053.6
Missing GLIBCXX >= 3.4.18!
Found versions 
local-server-1> ssh child died, shutting down

[16:36:02.667] Failed to parse remote port from server output
[16:36:02.669] Resolver error: Error: 
	at Function.Create (/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:586041)
	at Object.t.handleInstallOutput (/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:584693)
	at Object.e [as tryInstallWithLocalServer] (/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:625033)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:644084
	at async Object.t.withShowDetailsEvent (/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:647831)
	at async /Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:623505
	at async b (/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:620011)
	at async Object.t.resolveWithLocalServer (/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:623120)
	at async Object.t.resolve (/Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:645441)
	at async /Users/login_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:722872
[16:36:02.676] ------

```

Steps to Reproduce:

1. I config my ssh config with the following
```
Host cloudshell
    ProxyCommand ~/google-cloud-sdk/bin/gcloud cloud-shell ssh --ssh-flag='-W localhost:22'
    LocalForward 8888 127.0.0.1:8888
    LocalForward 3000 127.0.0.1:3000
    LocalForward 8000 127.0.0.1:8000
    User google_username
    IdentityFile ~/.ssh/google_compute_engine
    StrictHostKeyChecking no
```
2. use VScode to connect over

Note: This work when the `Remote - SSH` version is v 74.0, but not working on v76.0.0 or v76.0.1

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: no

**Comment by tanhakabir** [comment] 2022-03-07 19:28
Potentially a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6407

Could you try using https://github.com/microsoft/vscode-remote-release/issues/6407#issuecomment-1061034572

**Comment by roblourens** [comment] 2022-03-07 21:14
Maybe slightly different than #6407 - in this case, we found mlutiple 'libstdc++' when searching in `/sbin/ldconfig -p`. Then our script broke at `mainScriptWrapper:185: bad math expression: operand expected at `*100 +  '`, which I don't fully understand, can you tell me what you get for `ldd --version | head -n1`?

Or is it different if you connect through ssh, type `bash`, and run `ldd --version | head -n1`?

**Comment by kis87988** [comment] 2022-03-10 22:45
@roblourens ,
I tried. and here is the result

```
$ bash
cloudshell:~$ ldd --version | head -n1
ldd (Debian GLIBC 2.31-13+deb11u2) 2.31
cloudshell:~$
```

**Comment by kis87988** [comment] 2022-03-10 22:54
> Potentially a duplicate of #6407
> 

> Could you try using [#6407 (comment)](https://github.com/microsoft/vscode-remote-release/issues/6407#issuecomment-1061034572)

@tanhakabir, The customized version seems to works. Is this a bug?

**Comment by tanhakabir** [comment] 2022-03-10 22:59
It looks like you had the same bug then! The fix was just merged today and will be released in tomorrow's pre-release version of Remote SSH. Eventually the fix will be out in the next stable release (end of the month/early April)

**Closed by tanhakabir** 2022-03-10 22:59 UTC
Labels: ssh, needs more info
