### ISSUE TITLE
Is it possible for VSCode using Remote-WSL to read directly from Windows?

### ISSUE THREAD

**Issue by ZZYSonny** [microsoft/vscode-remote-release#1180] opened 2019-08-16 11:38 UTC
Since most file from WSL (perhaps except for files on ftp client on WSL?) can be directly read from Windows by a small translation, will it be possible to use it to enhance performance? Here are some possible enhancement.
`
/mnt/c/directory = C:\directory
/directory=C:\Users\USERNAME\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs    (For ubuntu 18.04)
`

1. Starting up remote server often takes several seconds and meanwhile user can't open any file. With this mechanism, user can probably open some file without server running.

2. Recycle bin support.

3. Better IO speed because it doesn't go through WSL? Although the current IO speed is enough for file browsing.

**Comment by WSLUser** [comment] 2019-08-16 16:57
The Plan9 server is required to access files in WSL from Windows. This is the case for both WSL1 and WSL2.

**Comment by egamma** [comment] 2019-08-20 10:06
@WSLUser is correct, this is by design, closing.

**Closed by egamma** 2019-08-20 10:06 UTC
Labels: *as-designed
