### ISSUE TITLE
Unable to using "code" command in remote console

### ISSUE THREAD

**Issue by qsazx874** [microsoft/vscode-remote-release#6357] opened 2022-02-18 03:02 UTC
- VSCode Version:
> 版本: 1.64.2 (user setup)
提交: f80445acd5a3dadef24aa209168452a3d97cc326
日期: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043 

- Local OS Version:
> 版本	Windows 10 企业版
版本号	21H1
安装日期	‎2021/‎6/‎28
操作系统内部版本	19043.1081
体验	Windows Feature Experience Pack 120.2212.3530.0 

- Remote OS Version:
> Ubuntu 16.04 LTS 

- Remote Extension/Connection Type: 
> SSH 

- Logs:
 > use "env" to print shell environment, The "PATH" line have not include .vscode-server bin path 

LC_PAPER=zh_CN.UTF-8
XDG_SESSION_ID=31
LC_ADDRESS=zh_CN.UTF-8
TERM_PROGRAM=vscode
LC_MONETARY=zh_CN.UTF-8
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=172.21.4.136 56768 22
TERM_PROGRAM_VERSION=1.64.2
LC_NUMERIC=zh_CN.UTF-8
USER=gezhengyang
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_TELEPHONE=zh_CN.UTF-8
ARMLMD_LICENSE_FILE=/pkg/qct/software/arm/RVDS/5.01bld94/license.dat
PATH=/home/gezhengyang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
MAIL=/var/mail/gezhengyang
QT_QPA_PLATFORMTHEME=appmenu-qt5
LC_IDENTIFICATION=zh_CN.UTF-8
PWD=/home/gezhengyang/.vscode-server/bin
LANG=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
HOME=/home/gezhengyang
SHLVL=5
VSCODE_GIT_ASKPASS_MAIN=/home/gezhengyang/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/git/dist/askpass-main.js
LANGUAGE=zh_CN:zh:en_US:en
LOGNAME=gezhengyang
VSCODE_GIT_IPC_HANDLE=/run/user/1001/vscode-git-b6b632bd02.sock
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
SSH_CONNECTION=172.21.4.136 56768 172.21.100.86 22
VSCODE_IPC_HOOK_CLI=/run/user/1001/vscode-ipc-96ff73b2-bc20-489c-95d1-8ff88c6ff5e7.sock
LESSOPEN=| /usr/bin/lesspipe %s
BROWSER=/home/gezhengyang/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/bin/helpers/browser.sh
VSCODE_GIT_ASKPASS_NODE=/home/gezhengyang/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node
GIT_ASKPASS=/home/gezhengyang/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/extensions/git/dist/askpass.sh
XDG_RUNTIME_DIR=/run/user/1001
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_TIME=zh_CN.UTF-8
COLORTERM=truecolor
LC_NAME=zh_CN.UTF-8
OLDPWD=/home/gezhengyang
_=/usr/bin/env

Steps to Reproduce:

1.open remote ssh project
2.type "code +filename" command in remote terminal shell

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment] 2022-02-18 16:47
And which version of the SSH extension are you using?

**Comment by tanhakabir** [comment] 2022-02-18 17:32
@aeschli I think you've seen similar issues in the past. Was there a cause or solution you know about?

**Comment by bskaggs** [comment] 2022-02-20 17:16
Instead of adding the `remote-cli` directory directly to your PATH, I recommend setting this function in your `~/.bashrc` or `~/.zshrc` file on your remote machine:

```
code() {
    "$(ls -t --directory -- ~/.vscode-server/bin/* | head -n 1)/bin/remote-cli/code" "$@"
}
```

Now, when type `code ...` in a remote session, it will always use the `code` command in the githash directory with the most recent modification time.

**Comment by aeschli** [comment] 2022-02-21 15:10
Do you have `"terminal.integrated.inheritEnv": false` in your settings? If yes, then this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6289

**Comment by qsazx874** [comment] 2022-02-21 16:42
> Do you have `"terminal.integrated.inheritEnv": false` in your settings? If yes, then this is a duplicate of #6289

i checked, it's "ture" in the usr config.

**Comment by qsazx874** [comment] 2022-02-21 16:54
> Do you have `"terminal.integrated.inheritEnv": false` in your settings? If yes, then this is a duplicate of #6289

ALL LOG:
[00:49:52.641] Log Level: 1
[00:49:52.642] remote-ssh@0.74.0
[00:49:52.642] win32 x64
[00:49:52.661] SSH Resolver called for "ssh-remote+simcom86", attempt 1
[00:49:52.661] "remote.SSH.useLocalServer": false
[00:49:52.661] "remote.SSH.showLoginTerminal": false
[00:49:52.661] "remote.SSH.remotePlatform": {"simcom":"linux","simcom86":"linux","simcom81":"linux"}
[00:49:52.661] "remote.SSH.path": undefined
[00:49:52.662] "remote.SSH.configFile": undefined
[00:49:52.662] "remote.SSH.useFlock": true
[00:49:52.662] "remote.SSH.lockfilesInTmp": false
[00:49:52.662] "remote.SSH.localServerDownload": auto
[00:49:52.662] "remote.SSH.remoteServerListenOnSocket": false
[00:49:52.662] "remote.SSH.showLoginTerminal": false
[00:49:52.662] "remote.SSH.defaultExtensions": []
[00:49:52.662] "remote.SSH.loglevel": 1
[00:49:52.663] "remote.SSH.enableDynamicForwarding": true
[00:49:52.663] "remote.SSH.enableRemoteCommand": false
[00:49:52.663] "remote.SSH.serverPickPortsFromRange": {}
[00:49:52.663] "remote.SSH.serverInstallPath": {}
[00:49:52.666] SSH Resolver called for host: simcom86
[00:49:52.667] Setting up SSH remote "simcom86"
[00:49:52.688] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[00:49:52.691] Install and start server if needed
[00:49:52.694] Checking ssh with "ssh -V"
[00:49:52.725] > OpenSSH_for_Windows_8
[00:49:52.725] > .1p1, LibreSSL 3.0.2

[00:49:52.729] Running script with connection command: ssh -T -D 62692 simcom86 bash
[00:49:52.731] Terminal shell path: C:\Windows\System32\cmd.exe
[00:49:53.936] "install" terminal received data: "[2J[m[H]0;C:\Windows\System32\cmd.exe[?25h"
[00:49:53.937] Got some output, clearing connection timeout
[00:49:54.268] "install" terminal received data: "7d49e9e0aa79: running"
[00:49:54.464] "install" terminal received data: "Acquiring lock on /home/gezhengyang/.vscode-server/bin/f80445acd5a3dadef24aa2091
68452a3d97cc326/vscode-remote-lock.gezhengyang.f80445acd5a3dadef24aa209168452a3d
97cc326[K"
[00:49:54.472] "install" terminal received data: "Found existing installation at /home/gezhengyang/.vscode-server/bin/f80445acd5a3
dadef24aa209168452a3d97cc326...[K"
[00:49:54.488] "install" terminal received data: "Checking /home/gezhengyang/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc
326.log and /home/gezhengyang/.vscode-server/.f80445acd5a3dadef24aa209168452a3d9
7cc326.pid for a running server[K
Looking for server with pid: 17240[K"
[00:49:54.560] "install" terminal received data: "Found running server..."
[00:49:54.566] "install" terminal received data: "[K
*[K
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*[K
[K
Checking server status on port 45901 with wget[K"
[00:49:54.576] "install" terminal received data: "[25l7d49e9e0aa79: start     
SSH_AUTH_SOCK====       
DISPLAY====[13X
webUiAccessToken====    
listeningOn==45901==    
osReleaseId==ubuntu==   
arch==x86_64==[10X
tmpDir==/run/user/1001==
platform==linux==       
unpackResult====        
didLocalDownload==0==   
downloadTime====        [30;17H[?25h
installTime====
extInstallTime====
serverStartTime====
connectionToken==aaaa1a1a-a111-1a11-a111-111111aaaa11==
7d49e9e0aa79: end"
[00:49:54.577] Received install output:      
SSH_AUTH_SOCK====       
DISPLAY====
webUiAccessToken====    
listeningOn==45901==    
osReleaseId==ubuntu==   
arch==x86_64==
tmpDir==/run/user/1001==
platform==linux==       
unpackResult====        
didLocalDownload==0==   
downloadTime====        
installTime====
extInstallTime====
serverStartTime====
connectionToken==aaaa1a1a-a111-1a11-a111-111111aaaa11==

[00:49:54.577] Remote server is listening on 45901
[00:49:54.577] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":45901},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1001","platform":"linux","connectionToken":"aaaa1a1a-a111-1a11-a111-111111aaaa11"},"installUnpackCode":""}
[00:49:54.579] Starting forwarding server. localPort 62697 -> socksPort 62692 -> remotePort 45901
[00:49:54.580] Forwarding server listening on 62697
[00:49:54.580] Waiting for ssh tunnel to be ready
[00:49:54.580] Tunneled 45901 to local port 62697
[00:49:54.580] Resolved "ssh-remote+simcom86" to "127.0.0.1:62697"
[00:49:54.581] Updating terminal environments: {}
[00:49:54.581] [Forwarding server 62697] Got connection 0
[00:49:54.585] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"ubuntu","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"success"},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":1924,"timing.preSshTime":70,"timing.establishSshTime":1537,"timing.scriptTime":1846}}
[00:49:54.587] ------




[00:49:54.632] [Forwarding server 62697] Got connection 1
[00:49:54.652] [Forwarding server 62697] Got connection 2
[00:49:59.736] TELEMETRY: {"eventName":"extraInfo","properties":{"remoteCloud":""},"measures":{}}
[00:52:55.095] "install" terminal received data: " "

**Comment by aeschli** [comment] 2022-02-21 21:02
From `BROWSER=/home/gezhengyang/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/bin/helpers/browser.sh` we can see that the code that added the remote-cli PATH and set BROWSER has been run.

The question is, where was the PATH replaced with values that no longer contain our `remote-cli` path.

**Comment by qsazx874** [comment] 2022-02-23 02:11
> From `BROWSER=/home/gezhengyang/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/bin/helpers/browser.sh` we can see that the code that added the remote-cli PATH and set BROWSER has been run.
> 
> The question is, where was the PATH replaced with values that no longer contain our `remote-cli` path.

I found root cause:  /etc/bash.bashrc

before:
> export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 

fixed after:
> export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$PATH

the **bash.bashrc** flushes  PATH env variables

**Comment by aeschli** [comment] 2022-02-23 07:50
ok, great, that explains it. Closing the issue then.

**Closed by aeschli** 2022-02-23 07:50 UTC
Labels: ssh, needs more info
