### ISSUE TITLE
Firebase tools and Dev Container: The web page (localhost:5000) never loaded

### ISSUE THREAD

**Issue by RaheutRahwana** [microsoft/vscode-remote-release#9842] opened 2024-05-03 04:33 UTC
- VSCode Version: 1.89.0 Linux x64 6.1.0-20-amd64 snap
- Local OS Version: Debian GNU/Linux 12
- Remote OS Version: Debian GNU/Linux 11
- Remote Extension/Connection Type: Containers

- Logs: https://pastebin.com/raw/ssmMV5YW

Steps to Reproduce:

Create a Firebase web project if you don't have one already.

1. Open VS Code and create a new folder.
2. Add a `Node.js & JavaScript` Dev Container configuration file.
3. Reopen the folder in the container.
4. Once everything is set up, run the command `npm install -g firebase-tools`.
5. Run the command `firebase login` and follow in browser.
6. Run the command `firebase init` and follow the prompts.
7. Run the command `firebase serve`.
8. Follow the URL provided, and you'll notice that the page does not load as expected.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment] 2024-05-03 06:03
Is firebase running on port 5000? The log shows `ECONNREFUSED 127.0.0.1:5000`.

What do you get when running `netstat -l` in the container?

**Comment by RaheutRahwana** [comment] 2024-05-03 08:00
> Is firebase running on port 5000? The log shows `ECONNREFUSED 127.0.0.1:5000`.

Yes, the Firebase Hosting run on port 5000.

> What do you get when running `netstat -l` in the container?
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost:44353         0.0.0.0:*               LISTEN     
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     385573   /home/node/.gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     386790   /tmp/vscode-git-bf89df8c55.sock
unix  2      [ ACC ]     STREAM     LISTENING     387077   /tmp/vscode-ipc-ab9ed8a4-62f6-4732-9981-964b4aa436df.sock
unix  2      [ ACC ]     STREAM     LISTENING     383726   /tmp/vscode-remote-containers-ipc-b2bda113-e9ec-4c44-a0b1-899fecbcec1b.sock
unix  2      [ ACC ]     STREAM     LISTENING     385564   /tmp/vscode-ssh-auth-b2bda113-e9ec-4c44-a0b1-899fecbcec1b.sock
unix  2      [ ACC ]     STREAM     LISTENING     385565   /tmp/.X11-unix/X2
unix  2      [ ACC ]     STREAM     LISTENING     385921   /tmp/vscode-ipc-a269198b-db8a-4c76-ba81-9bb66a11879a.sock
```

**Comment by alexr00** [comment] 2024-05-07 08:35
Closing as a duplicate of https://github.com/microsoft/vscode-remote-release/issues/7029

**Closed by alexr00** 2024-05-07 08:35 UTC
Labels: containers, info-needed
