### ISSUE TITLE
Test: DnD should fail when dragging folders from vscode to local

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-remote-release#816] opened 2019-06-25 18:57 UTC
Testing #664

I'm aware folder is not supported yet, but currently dragging folder from vscode to local would create a blank file of the same name. I suggest showing an error notification.

**Comment by isidorn** [comment] 2019-06-26 07:51
The issue here is when to show the error.
Because when you start dragging is too early since you might drop it inside vscode somewhere, and when you drop it outside of vscode it is no longer in our control. Chrome takes care of it and we have no control over how it handles (creates a blank file).

Due to that closing as designed since I do not know how to fix.
Let me know if you have some suggestion and I can reopen

**Closed by isidorn** 2019-06-26 07:51 UTC
