### ISSUE TITLE
Failed to unzip vscode server tar

### ISSUE THREAD

**Issue by Dark-Hippo** [microsoft/vscode-remote-release#3396] opened 2020-07-20 14:08 UTC
- 1.47.2
- Windows 10 2004
- Ubuntu server 16.04
- SSH

Steps to Reproduce:

1. Attempt to connect to remote host via "Connect Current Window to Host"

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

When attempting to connect to the remote server via an entry in the `.ssh/config` file:

```
Host tim
    HostName tomatoes123
    User tom
```

Results in error message:

```
[14:49:59.032] > Server did not start successfully. Full server log at /home/tom/.vscode-server/.17299e413d5590b14ab0340ea477cdd86ff13daf.log >>>
> /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/server.sh: 12: /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/server.sh: /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/node: not foun
```

An `ls -a` of the relevant directory shows: LICENSE, node_modules, out, package.json, product.json and server.sh, but no node.

When connecting directly (without using the entry in `.ssh/config` the error message seems to occasionally change to a Segmentation Fault one.

I've tried running the "Kill VS Code Server on Host" and reconnecting several times, but to no avail.

Full console output is:

```[14:49:47.813] Log Level: 2
[14:49:47.819] remote-ssh@0.51.0
[14:49:47.819] win32 x64
[14:49:47.821] SSH Resolver called for "ssh-remote+tim", attempt 1
[14:49:47.821] SSH Resolver called for host: tim
[14:49:47.821] Setting up SSH remote "tim"
[14:49:48.119] Using commit id "17299e413d5590b14ab0340ea477cdd86ff13daf" and quality "stable" for server
[14:49:48.120] Install and start server if needed
[14:49:48.123] Checking ssh with "ssh -V"
[14:49:48.213] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[14:49:48.215] Using SSH config file "C:\Users\tom\.ssh\config"
[14:49:48.215] Running script with connection command: ssh -T -D 62856 -F "C:\Users\tom\.ssh\config" tim bash
[14:49:48.221] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:49:48.557] > tom@tomatoes123's password:]0;C:\WINDOWS\System32\cmd.exe
[14:49:48.557] Got some output, clearing connection timeout
[14:49:48.566] > tom@tomatoes123's password:
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[14:49:52.942] > 
[14:49:53.153] > 444623b32c50: running
[14:49:53.200] > Acquiring lock on /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/vscode-remote-lock.tom.17299e413d5590b14ab0340ea477cdd86ff13daf
[14:49:53.206] > \ln /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/vscode-remote-lock.tom.17299e413d5590b14ab0340ea477cdd86ff13daf.target /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/vscode-remote-lock.tom.17299e413d55
> 90b14ab0340ea477cdd86ff13daf
[14:49:53.215] > Installing to /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf...
> 444623b32c50%%1%%
> Downloading with wget
[14:49:55.274] > Download complete
> 444623b32c50%%2%%
[14:49:55.406] > tar: Skipping to next header
[14:49:55.417] > tar: Exiting with failure status due to previous errors
[14:49:55.423] > WARNING: tar exited with non-0 exit code
> WARNING: /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/node doesn't exist. Download/untar may have failed.
[14:49:55.437] > XDG_SESSION_ID=217
> SHELL=/bin/bash
> SSH_CLIENT=10.0.11.32 62858 22
> USER=tom
> VSCODE_AGENT_FOLDER=/home/tom/.vscode-server
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> MAIL=/var/mail/tom
> PWD=/home/tom
> LANG=en_GB.UTF-8
> HOME=/home/tom
> SHLVL=2
> LANGUAGE=en_GB:en
> LOGNAME=tom
> SSH_CONNECTION=10.0.11.32 62858 10.0.11.33 22
> XDG_RUNTIME_DIR=/run/user/1000
> _=/usr/bin/printenv
> OLDPWD=/home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf
[14:49:55.460] > Starting server with command... /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/tom/.vscode-server/.17299e413d5590b14ab0340ea477cdd86ff13daf.log" < /de
> v/null
> Waiting for server log...
[14:49:55.959] > Waiting for server log...
[14:49:56.477] > Waiting for server log...
[14:49:56.992] > Waiting for server log...
[14:49:57.500] > Waiting for server log...
[14:49:58.009] > Waiting for server log...
[14:49:58.514] > Waiting for server log...
[14:49:59.017] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[14:49:59.032] > Server did not start successfully. Full server log at /home/tom/.vscode-server/.17299e413d5590b14ab0340ea477cdd86ff13daf.log >>>
> /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/server.sh: 12: /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/server.sh: /home/tom/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/node: not foun
> d
> <<< End of server log
> 444623b32c50##32##
[14:49:59.032] Received install output: 444623b32c50##32##
[14:49:59.033] Resolver error: The VS Code Server failed to start
[14:49:59.036] ------




[14:49:59.245] > 
[14:49:59.541] "install" terminal command done
[14:49:59.541] Install terminal quit with output: 
[14:58:49.000] ConfigFileWatcher: start watching file:///c%3A/Users/tom/.ssh/config
[14:58:49.001] ConfigFileWatcher: adding save listener
[14:58:49.002] ConfigFileWatcher: adding close listener
[14:58:49.057] ConfigFileWatcher: closing untitled:Untitled-1
```

**Comment by Dark-Hippo** [comment] 2020-07-22 09:33
Managed to fix the issue myself by getting someone to send me the contents of the `/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf` folder from their machine and replacing my local one with theirs.

**Comment by mtsr** [comment] 2020-07-23 19:38
I think this should be reopened. I have the same problem and copying from another machine seems a finicky workaround...

**Comment by Dark-Hippo** [comment] 2020-07-28 12:31
> I think this should be reopened. I have the same problem and copying from another machine seems a finicky workaround...
> 
> Debian 10 64-bit on VirtualBox VM on Windows 10 Host. Cleanly installed machine, only sshd, standard utitilities, vim and sudo installed.
> 
> MacOS client.

Fair point, I guess I am pretty lucky in that I can get someone to send me across the files.

I've also just had the same issue, but now complaining that it can't find `server.sh` file after an update.

**Comment by Dark-Hippo** [comment] 2020-07-28 13:36
Tried the same trick again, copying files from someone else's machine, except this time the error I'm getting is complaining about not being able to find the `server.sh` file even though an `ls` shows it.

So now I'm completely stumped.

**Comment by Dark-Hippo** [comment] 2020-07-28 13:51
Right, managed to fix the issue myself by copies files from someone else's machine, though this time had to copy them one by one until it worked as copying everything kept causing it to fail.

I'm leaving this open though as it's a stupid solution to the problem and clearly not sustainable.

**Comment by roblourens** [comment] 2020-07-28 22:52
Seems like it's failing to install? Can you try wiping out the installation (Run the "Uninstall VS Code Server from host" command) then try again, and share the full log from the Remote-SSH output channel?

**Comment by roblourens** [comment] 2020-07-28 22:54
Oh never mind, I see this

> [14:49:55.406] > tar: Skipping to next header
> [14:49:55.417] > tar: Exiting with failure status due to previous errors
> [14:49:55.423] > WARNING: tar exited with non-0 exit code

Is the `.tar.gz` still in place after this for you to examine? Might it be corrupted? Do you have a proxy or something that might be interfering with the download?

Or do you have a really old version of tar on your path for some reason?

**Comment by Dark-Hippo** [comment] 2020-09-01 08:18
> Oh never mind, I see this
> 
> > [14:49:55.406] > tar: Skipping to next header
> > [14:49:55.417] > tar: Exiting with failure status due to previous errors
> > [14:49:55.423] > WARNING: tar exited with non-0 exit code
> 
> Is the `.tar.gz` still in place after this for you to examine? Might it be corrupted? Do you have a proxy or something that might be interfering with the download?
> 
> Or do you have a really old version of tar on your path for some reason?

Sorry for the very delayed response. I'm running tar 1.28 (I'm using Ubuntu 16.04 and can't update... I know, don't get me started, company politics).

The problem as far as debugging this goes is that I use it at work, so if it fails, I don't have time to wait for responses to this thread to help solve the issue, I need it fixed so I can work, which is why I've been using hacky work arounds (getting the files from someone else to get around the issue).

**Comment by mtsr** [comment] 2020-09-01 11:01
In my case, turns out the VM software I was running was broken. After that was fixed, I got it to work.

**Comment by Dark-Hippo** [comment] 2020-09-03 09:29
> In my case, turns out the VM software I was running was broken. After that was fixed, I got it to work.

@mtsr Interesting, what VM software were you using and how was it broken?

**Comment by roblourens** [comment] 2020-11-10 00:48
I've had a few of these issues with failing to unzip the tar, and I haven't figured anything out except one case that involved a very old version of tar. This is now logged. My other guess is that a proxy is corrupting/modifying the downloaded binary.

I can also try to verify the download against the checksum.

**Comment by roblourens** [comment] 2020-11-12 19:39
Closing as dupe of https://github.com/microsoft/vscode-remote-release/issues/3365

**Closed by roblourens** 2020-11-12 19:39 UTC
Labels: bug, ssh
