### ISSUE TITLE
Include directive in ssh config under Host directive not supported

### ISSUE THREAD

**Issue by cheasy** [microsoft/vscode-remote-release#4339] opened 2021-01-22 08:42 UTC
Issue Type: <b>Bug</b>

1. In .ssh/config, define an include directory

```
### Global options
Host *
	# omitted

Include config.d/*
```

2. Create a Host definition in an included file, e.g. config.d/doesNotShow
```
Host doesNotShow
   Hostname   127.0.0.1
   # user, key, ... omitted

```
3. Host does not show up in the config file editor, nor in the host list for remote-ssh. 

Extension version: 0.62.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by roblourens** [comment] 2021-03-02 23:44
It works at the top of the file, but not the bottom. Pretty sure that used to work. Filed https://github.com/cyjake/ssh-config/issues/42

**Comment by roblourens** [comment] 2021-03-03 04:27
It was pointed out in https://github.com/cyjake/ssh-config/issues/42#issuecomment-789371766 that the Include is parsed under `Host` declarations. I guess I could pull them out of `Host *`, but it's not really clear how to handle it in general. What you probably want is the Include at the top of the file though because it will stop working if you add a different host between it and `Host *`.

**Comment by beardedfool** [comment] 2021-03-16 13:42
@roblourens 

I think this previously worked (and should?) but it doesn't now

Host *
StrictHostKeyChecking no
Include conf.d\* (or conf.d/*)

In fact wildcards don't seem to be working for me at the top of the file either.
Just to note that giving the full(er) path with wildcard doesn't help 
e.g. c:\users\XXX\.ssh\conf.d/*

Is this connected or a different bug?

**Comment by roblourens** [comment] 2021-03-16 19:33
The extension doesn't interpret your ssh config file, only ssh does

**Comment by beardedfool** [comment] 2021-03-16 21:58
Surely it does to populate the Remote Explorer > SSH Targets list?
That's what was working previously with wildcards but now is 

- blank if I use a wildcard
- blank if I include _below_ the Host* line to the config file path (without a wildcard)
- ok is I include _above_ the Host* line to the config file path (without a wildcard)

**Comment by roblourens** [comment] 2021-03-16 23:01
Sorry I misunderstood what you were saying is not working. The first thing you said (Include below a Host entry) is what this issue is for. The only thing that I expect to work right now is an Include at the top of the file.

> blank if I use a wildcard

Is this below a Host line?

**Comment by beardedfool** [comment] 2021-03-17 18:12
My apologies, I wasn't clear. Trying to find the right issue(s) and not doing it very well. Appreciate the wildcard is then a seperate issue, are you aware of an open bug for that?

The wildcard doesn't work either above or below the host entry in the sense that entries don't show up on Remote Explorer > SSH Targets list?
That's on 1.54.3 vscode and either nightly or stable version of Remote ssh, for me at least. 
It did before, I think, for include\conf.d\* both above and below Host* but it's possible I may be misremembering that.

**Comment by roblourens** [comment] 2021-03-17 20:41
I am also just confusing myself because I was thinking I'd implemented wildcards for Include in general, but I have not: https://github.com/microsoft/vscode-remote-release/issues/2446

**Comment by stefansedich** [comment] 2021-06-23 23:02
I see something weird when adding hosts with an existing ssh config file that uses an include, initiall I have the following:

### ~/.ssh/config
```
Include ~/.ssh/config2
```

### ~/.ssh/config2
```
Host foo2
  HostName foo2
```

I add a new host through the UI saving to my config file and now `~/.ssh/config` gets saved as:

```
Include ~/.ssh/config2
Host foo
  User foo

Host foo2
  HostName foo2
```

For some reason it duplicates the contents of my include into the config file itself...

**Comment by guillemglez** [comment] 2021-11-05 09:38
A quick (partial) fix for this could be supporting multiple files in configuration value `remote.SSH.configFile`.

**Comment by eleanorjboyd** [comment] 2022-12-08 18:24
Since this issue got a bit long, I wanted to summarize it here for future reference. Our desired behavior for the "include" keyword as follows:

- If the include statement is at the top of the config, then it will be parsed and displayed in the selection dropdown
- if the include statement is nested under a host, it will not be included in the dropdown unless the host it is nested under is `host *`
- When the extension is used any "include" files will stay separate and not be duplicated into the base config file.

For this involved in this issue, does that summary seem correct? Anything to add? The next step will be trying to reproduce these errors on the newest version of the extension so if anyone is still experiencing this issue please let me know as that will support the fact it is an ongoing problem.

Thanks!

**Comment by beardedfool** [comment] 2022-12-08 21:51
**Currently:**
Ssh targets are shown in remote explorer if the include is first in the .ssh/config file
```
Include conf.d/*
Host *
   StrictHostKeyChecking no
```
but not if below a host key
```
Host *
Include conf.d/*
   StrictHostKeyChecking no
```
It should as per https://github.com/cyjake/ssh-config/issues/42#issuecomment-789371766
and
https://www.freebsd.org/cgi/man.cgi?ssh_config(5)

FYI you can still ssh to the targets from CLI (cmd or *nix) in either case so the include is working properly there, just not in the remote explorer list.

**Future state**
I agree with two of your statements, this one is harder and hoping someone more knowleable will come along or that man page will help (see sections on host, match and patterns) and suggest the implementation matches that spec.

"if the include statement is nested under a host, it will not be included in the dropdown unless the host it is nested under is host *"

That works for my cases but
A) Does it have to be under a Host * to be valid? i.e. Not sure Host * is required
B) I think this is valid ssh config
```
host server1 server2
IdentityFile keyfile
```
This identifies those two servers as using that key and ssh server1 or ssh server2 would work from cmd assuming dns resolved the hostname despite the hostname not being specifically identified.
Just mention it as could be interesting to represent that in remote explorer as it's not as simple as 1 Host and Hostname per server in the normal way e.g.

```
Host server1
  Hostname server1
  IdentityFile keyfile
  
Host server2
  Hostname server2
  IdentityFile keyfile
```
I'm not sure if that's a design decision for the remote explorer or in the spec (?) 

_Lastly_
For history I think this ticket got a bit confused as
1) previously the wildcards didn't work but they do now - in the limited way above
2) I think there was a temporary bug where they didn't appear in remote explorer but now do as above
2) Multiple related tickets -. #2446 #65 #5662 and probably others.

**Comment by eleanorjboyd** [comment] 2023-01-20 17:57
copied from [this issue](https://github.com/microsoft/vscode-remote-release/issues/7427). Make sure to check comments as edge cases.

> FYI @eleanorjboyd I had an Include as the only line in my ssh_config, but it wasn't being parsed correctly because of the comment:
> Include config.d/* # comment

**Comment by zzh1996** [comment] 2023-02-09 02:51
> * if the include statement is nested under a host, it will not be included in the dropdown unless the host it is nested under is `host *`

This is wrong. Here's a valid config:

`~/.ssh/config`

```
Host A
...
Host B
...
Include config2
```

`~/.ssh/config2`

```
Host C
...
```

There is no *nesting* in ssh config files. The `Host` keyword just means that "please use this host(s) until the next Host or Match keyword appears".

Anyway, why do you care about the location of the `Include` statement at all? Why don't you just parse the config file from top to bottom and process `Include`s recursively? This is very simple and respects the man pages.

**Comment by Grummfy** [comment] 2023-06-27 09:51
@zzh1996 regarding wildcard there is an issue over there: https://github.com/microsoft/vscode-remote-release/issues/2997

But totally agree a proper parsing would have solve all of this, instead of assuming elements

**Comment by J-Siu** [comment] 2023-07-06 06:28
Following from @beardedfool comment [above](https://github.com/microsoft/vscode-remote-release/issues/4339#issuecomment-1343419069): 

> **Currently:** Ssh targets are shown in remote explorer if the include is first in the .ssh/config file
> 
> ```
> Include conf.d/*
> Host *
>    StrictHostKeyChecking no
> ```
>
> ...

I am not able to get it working with `Include` line at the top of `~/.ssh/config`. My `~/.ssh/config` has not host entry, only `Include`. No ssh target shown in drop down.

Just want to confirm if this is the current status?

**Comment by jonathan-vb-cf** [comment] 2023-07-06 07:22
Include is working but the wildcard in host not...

**Comment by J-Siu** [comment] 2023-07-06 09:33
@jonathan-vb-cf 

> Include is working but the wildcard in host not...

`Include` is not working on two MacOS laptop:

- MachBook Air M2
- MacOS 13.4.1 (22F82)

- MachBook Air 2015 (Intel)
- MacOS 12.6.7

VSCode version are the same:
- VSCode Version: 1.79.2 (Universal)
- Remote - SSH v0.102.0

The include file `~/.ssh/conf.d/test.conf`:

```
host test01
  hostname <an ip address>
```

With both relative and absolute path `Include` in ~/.ssh/config:

```
Include conf.d/*
```

```
Include conf.d/test.conf
```

```
Include /Users/js/.ssh/conf.d/*
```

```
Include /Users/js/.ssh/conf.d/test.conf
```

The `config` file only has the single line of `Include`.

`ssh test01` works correctly from command line. But `test01` is not showing in the drop down host list.

**Comment by beardedfool** [comment] 2023-07-06 09:36
Just to confirm, is your Include statement the first line or the config
file?

**Comment by J-Siu** [comment] 2023-07-06 09:42
@beardedfool 
> Just to confirm, is your Include statement the first line or the config file?
> […](#)

Yes, and it is the only line.

![Screenshot 2023-07-06 at 5 39 26 AM](https://github.com/microsoft/vscode-remote-release/assets/3171920/5c56525a-d8ce-449a-81ae-ca6fae684f47)
![Screenshot 2023-07-06 at 5 39 35 AM](https://github.com/microsoft/vscode-remote-release/assets/3171920/7427fa45-9956-4dd0-a912-956bc9f00dcb)

**Comment by arrrgi** [comment] 2023-08-23 04:46
@bamurtaugh or @eleanorjboyd - could you please confirm whether this has moved into a future milestone?

**Comment by bamurtaugh** [comment] 2023-08-23 16:22
Thanks for the ping @arrrgi. If/when this issue is moved into a future milestone, we typically update the assigned Milestone on GitHub to the month we're planning to work on it, so you should be able to see the latest reflected there. And if we have any other updates, we'll be sure to share them in this issue. Thanks for following up with us, we appreciate folks' continued interest and patience.

**Closed** 2024-05-31 19:32 UTC
Labels: bug, ssh, plan-review

**Comment by roblourens** [comment] 2024-05-31 20:51
It's a little confusing how to handle this since Includes that are under any Host directive are actually nested under that directive, even if it's not indented. I've implemented this to resolve any Includes that are under any Host with a `*` in the name. I think that should give the behavior that people generally expect. This is coming in June.
