### ISSUE TITLE
Disallow some ports from Remote development port forwarding (SSH)

### ISSUE THREAD

**Issue by ishaan-puniani** [microsoft/vscode-remote-release#3843] opened 2020-10-13 09:52 UTC
Sometimes it is required that certain ports should not be forwarded. like application is running locally on certain port should serve locally without going through Reverse SSH Port Forwarding. 

For example. I am using Remote Machine as server (application running at 8080). and for web client development on my local machine which is served on port 3000. 

I do not want to forward port 3000 so I delete it manually. since there is hot reloading and hot restart mechanism in the client most of the time it get forwarded automatically. so There should be provision to blacklist 3000 from being forwarded and application will be served from local machine.

**Comment by s0** [comment] 2020-10-13 17:10
I would like this,

I have another use case myself. I'm using this plugin to ssh do a different user locally where I do my development on my linux machine, I have 2 reasons for doing this, mostly security:

* Preventing access to confidential (company) files from my main user account without an additional password.
* Requiring i'm logged-in as the other user for docker development (I've added the other user to the `docker` group, and avoid doing that for my own user for increased security).

Automatic port-forwarding is now preventing me from running various things from inside the interactive terminal as vscode and the process in question are on the same machine and end up battling for the same port.

I would also love a way to simply disable the automatic port-forwarding.

**Comment by thisiswhereitype** [comment] 2020-11-02 16:32
Does anyone have a workaround, this issue, imo makes other software unusable in the scenarios described above.

**Comment by ishaan-puniani** [comment] 2020-11-11 00:02
@thisiswhereitype noops. I need to a separate ssh into new bash window to start the application. Really very tricky to not use the terminal in vscode itself.

**Comment by gameolive-studio** [comment] 2020-11-15 01:26
Same issue for us as well, Just we are using docker setup instead. Always need to kill the port forwarding to 4200 while developing games locally and server running on docker remotely,

**Comment by PavelSosin-320** [comment] 2020-11-15 06:16
In all cases, the filtering of ports has to be consistent with Linux firewall iptables and Docker / Podman configuration capabilities. 
In all cases the **interval**! iptables -A INPUT -p tcp –dport 30000:20000 -j ACCEPT is supported or Podman and Docker run --expose (range) option but the blacklist will require a separate rule or not supported at all. Both Docker and Podman are heavily dependent on the Linux firewall.  **White list Interval** is a commonly used solution and has direct support. Multiple intervals are allowed but the blacklist can be above runtime capability or inconsistent in implementation.

**Comment by ishaan-puniani** [comment] 2020-11-15 11:25
Hey @PavelSosin-320 , I am not sure if I got your point precisely here. The problem the I am facing here is in VSCode terminal if I start a remote project and then start a local project in another window of VSCode the port used in local is automatically added to the forwarding list of the Remote Project. 
First: I didn't see the point for forwarding it automatically.
Second: There is no option to stop forwarding local port / disabling port forwarding either.
(if you remove it from forwarding list it will appear again when you restart the local application or if you are using hot-reload/restart configurations)

For me personally,  if you can suggest any way to disable automatic port forwarding for all ports and making it manually would be sufficient. If blacklisting is really tricky to achieve.

For Ref: 
  
![image](https://user-images.githubusercontent.com/2558553/99183616-67080800-273d-11eb-8b93-ac311a880277.png)

**Comment by Garima-Kaila** [comment] 2020-11-23 23:09
Same problematic issue with Angular App and NodeJs backend when debugging on the server.

**Comment by PavelSosin-320** [comment] 2020-11-24 06:41
The issue is incompatibility. The CNI ContainerNetworkingInterface is a part of CNCF. It has adopted in scores of projects and has commonly understandable meta language. Tons of portable code that make all necessary manipulations with infrastructures like OS networking configuration, firewall tuning, protocols filtering, and portable configuration persistence. It doesn't support blacklists but supports published port ranges according to user privileges. So, the blacklist will be a non-portable feature. Somebody has to write code that will do everything (!!!) that CNI implementation does if the network-related configuration is simply sent to CNI. Every time when you use --expose 80 or --publish 8080:80 Docker, Podman, Kubernetes on Cloud, Intel and ARM do all the necessary works.

**Comment by ishaan-puniani** [comment] 2020-11-25 00:15
@PavelSosin-320 You might be absolutely right, still I didn't find any solution for my issue here.  Is it possible for you to share a snippet that will be helpful for me to get rid of the issue mentioned in https://github.com/microsoft/vscode-remote-release/issues/3843#issuecomment-727554507.

And as I mentioned it is not about blacklisting some ports, It is more about avoiding automatic port forwarding (which was working fine in previous releases) Or having a feature that allows skipping the port forwarding for specific ports.

**Comment by ishaan-puniani** [comment] 2020-11-25 00:54
I found another similar request at https://github.com/microsoft/vscode-remote-release/issues/4046#issue-746357633

**Comment by PavelSosin-320** [comment] 2020-11-26 11:06
If you use more than 1 remote machine how do you define your blacklist, per server? Ignore is better than blacklist but if you are working in an enterprise behind you is staying security specialist and whisper in your ears - "Please, restrict the attack face in your application". An attacker also knows how to write randomizers. Server firewall allows creation only certain rule types and there is no "blacklist" type. Every port client needs its own drop rule. Open-end ranges are not supported.
Generally speaking, the creation of the portable network configuration is hardly possible, for example, due to the lack of the "privileged ports" concept in Windows. I think that having a network configuration file per machine is more convenient. Look at your Windows: it has separated %USERPROFILE%\AppData\Local and \Roaming. plus global \ApplicationData. Docker replicates its configuration in every place, \AppData\Local for user client and global \ApplicationData for the server.  The network state is in Roaming - this is its native place. It is very easy to add a machine creating or copying a new config file.

**Comment by ishaan-puniani** [comment] 2020-11-26 23:41
(Y) +100 for adding feature to ignore ports for automatic port-forwarding :)

**Comment by PavelSosin-320** [comment] 2020-12-06 06:23
At least, the blacklist can be empty in any scenario. **The minimal content of the blacklist is IANA port registry ranges.** Microsoft registers the port used by Microsoft products in this registry as well-known ports. The "private users" have to use only private dynamic ports range during the development and keep their hands out of registered and well-known ports to avoid conflicts with infrastructure configuration like default firewall configurations made and deployed by company IT. In the range of private ports, users can do what is needed for development. Otherwise, every developer has to be also an IT professional.

**Comment by PavelSosin-320** [comment] 2020-12-06 17:05
The universal solution is knowing IANA port ranges and using any proxy or revers-proxy that shifts port from the IANA registered or well-known range to the private range. In this range, nothing will be in use unless the user took it himself. Any proxy means socat in linux, [nodejs tcp proxy.](https://www.npmjs.com/package/node-tcp-proxy. ). Firewalls and Proxy are used by professional IT always in pair. Any Container infra has Proxy out-of-the-box for such cases..Any load balancer is suitable too: Nginx, Traefic, ....

**Comment by thisiswhereitype** [comment] 2020-12-11 16:50
I don't know how it's related but the November vscode update seems to resolve this for my case, instead it opens the `file://` which comes first in the terminal output instead of any `http://`

**Comment by ishaan-puniani** [comment] 2020-12-12 08:55
So, I am not sure how it get solved for you.. coz opening up file:// is incorrect in many cases when you have strict CORS rules in the application.

**Comment by PavelSosin-320** [comment] 2020-12-12 10:06
The solution for CORS for debug purposes is chrome.exe --disable-web-security. Anyway, the developer must obey both IANA recommendations and CORS security sending the corresponding header to make the application internet-friendly.

**Comment by alexr00** [comment] 2021-03-03 11:39
With the `remote.portsAttributes` setting you can `ignore` ports from auto forwarding. I think that should solve your request.

Don't forget that you can set setting in your remote user settings too if you want that setting to be different for different remotes.
Additionally, if it makes sense to share your configuration with other who use your repo, you can set the setting in the workspaces settings. https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings

**Closed by alexr00** 2021-03-03 11:39 UTC
Labels: feature-request, plan-review, ssh
