### ISSUE TITLE
Can't connect to remote if default shell is not /bin/bash

### ISSUE THREAD

**Issue by sehoffmann** [microsoft/vscode-remote-release#3897] opened 2020-10-23 13:16 UTC
- VSCode Version: 1.50.1
- Local OS Version: Ubuntu 20.04 LTS 
- Remote OS Version: Ubuntu 18.04.5 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote via ssh, which does not have `/bin/bash` as default shell (in my case: `/bin/sh`)
2. Connection attempt fails with:

```
ready: 658a54595928
Linux 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020
bash: line 1: SCH_DIR/server.sh: No such file or directory
bash: line 2: syntax error near unexpected token `then'
bash: line 2: `	then'
-sh: 4: function: not found
658a54595928: running
-sh: 23: [[: not found
-sh: 86: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 15044, received 3436 bytes, in 0.5 seconds
Bytes per second: sent 30876.8, received 7052.2

[15:13:30.345] Stopped parsing output early. Remaining text: OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f  31 Mar 2020debug1: Server host key: ecdsa-sha2-nistp256 SHA256:SNEFa3yjSWjPPWI4POUU302dx1AJIT1gLwa5ArcF+4IAuthenticated to 192.168.1.9 ([192.168.1.9]:22).Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-47-generic x86_64) * Documentation:  https://help.ubuntu.com * Management:     https://landscape.canonical.com * Support:        https://ubuntu.com/advantage * Canonical Livepatch is available for installation.   - Reduce system reboots and improve kernel security. Activate at:     https://ubuntu.com/livepatch33 packages can be updated.4 updates are security updates.New release '20.04.1 LTS' available.Run 'do-release-upgrade' to upgrade to it.Your Hardware Enablement Stack (HWE) is supported until April 2023.*** System restart required ***ready: 658a54595928Linux 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020bash: line 1: SCH_DIR/server.sh: No such file or directorybash: line 2: syntax error near unexpected token `then'bash: line 2: `	then'-sh: 4: function: not found658a54595928: running-sh: 23: [[: not found-sh: 86: Syntax error: "(" unexpected (expecting "then")Transferred: sent 15044, received 3436 bytes, in 0.5 secondsBytes per second: sent 30876.8, received 7052.2
[15:13:30.345] Failed to parse remote port from server output
[15:13:30.363] Resolver error: Error: 
	at Function.Create (/home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130564)
	at Object.t.handleInstallOutput (/home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:127671)
	at Object.t.tryInstallWithLocalServer (/home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /home/sh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[15:13:30.366] ------
```
The issue was resolved on my site by running `chsh -s /bin/bash`, however, in general, VS Code should detect if the default shell is not what it assumes/requires and execute any scripts directly through the shell of its choice.

**Comment by eddieHRS** [comment] 2020-10-26 03:16
Hi, I  got same problem like this. Only a little difference.
My Local OS Version: macOS  10.15.6
unfortunately, running `chsh -s /bin/bash ` does not work for me.

**Comment by ffyoko** [comment] 2020-10-29 04:01
Remote SSH runs script with the following connection command: ssh -T -D 65493 -F "C:\Users\XXXX\.ssh\config" bastion bash, which is generated automatically and seems to be unadjustable, and the parameter at the end is 'bash'

**Comment by rrowe629** [comment] 2020-10-30 08:46
The remote instance (actually a docker container) to which I was connecting defaulted to /bin/sh as the shell. Tried running chsh -s /bin/bash for that user and it did not change the shell. Deleted the user and recreated the user with /bin/bash as the shell and ... it worked!

**Comment by Chuxel** [comment] 2020-11-10 19:03
@roblourens is this a dupe of https://github.com/microsoft/vscode-remote-release/issues/2509?

**Comment by roblourens** [comment] 2020-11-11 01:21
I thought this issue wouldn't exist with `sh` as the default. I need to investigate

**Comment by roblourens** [comment] 2020-11-22 22:03
I can't repro any issue if I set my default shell to sh, and the script should be sh-compatible anyway.

I just had another issue that looked similar, where the error was on a piece of code that looks randomly truncated, and the cause was a `sleep` in the user's bashrc, could that be the case here too?

If not, can you share the full log from the Remote-SSH output channel?

**Closed** 2020-11-30 12:39 UTC
Labels: bug, needs-more-info, plan-review, ssh
