### ISSUE TITLE
VSCode must be started in a specific way to attach to running containers

### ISSUE THREAD

**Issue by illeatmyhat** [microsoft/vscode-remote-release#1116] opened 2019-08-07 17:47 UTC
- VSCode Version: 1.37-insider
- Local OS Version: OSX 10.14.6
- Remote OS Version: N/A
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open VSCode using OSX's Spotlight
2. Open Developer Tools and notice that `process.env` has been preloaded with default values
    - `process.env.PATH` is `"/usr/bin:/bin:/usr/sbin:/sbin"` (docker is located at /usr/local/bin/docker`)
    - `process.env.SHELL` is `"/usr/local/bin/bash"` (doesn't exist)
3. `>Remote-Containers: Attach to Running Container...`
    - Displayed Error: `Docker version 17.06.1 or later required`
    - Actual Error: `/bin/sh: docker: command not found`

It also fails if VSCode is opened using Finder.

Steps to Resolve:

1. Open VSCode using the Terminal `open /Applications/Visual\ Studio\ Code\ -\ Insiders.app`
2. Open Developer Tools and notice that `process.env` has been preloaded using `~/.bash_profile`
3. `>Remote-Containers: Attach to Running Container...` -- Works

**Comment by roblourens** [comment] 2019-08-09 21:55
@Tyriar ?

**Comment by Tyriar** [comment] 2019-08-10 03:06
The local window environment that you're quoting shouldn't impact the container environment at all. I think the problem is because /bin/sh is hardcoded in a lot of places in the containers extension.

**Comment by Tyriar** [comment] 2019-08-10 03:08
@illeatmyhat if this your own container? Could you create a symlink for /bin/sh to a shell in the Dockerfile?

**Comment by illeatmyhat** [comment] 2019-08-10 03:20
The container has nothing to do with it.
The extension simply cannot find the docker executable unless the editor is opened using the terminal and inherits its environment.
Obviously, if it can't find the docker executable, then it isn't going to be able to attach to any containers.

**Comment by Tyriar** [comment] 2019-08-10 03:32
Oh ok, I misunderstood.

That works fine for me because `/bin/sh` exists. I don't know why it doesn't on your system but you can check your available shells by running `cat /etc/shells`, then you should symlink one like this `ln -s /bin/bash /bin/sh` (it must be POSIX compatible so google that if you're not sure)

**Comment by illeatmyhat** [comment] 2019-08-10 06:13
Right, the issue is already solved for me, but the point is that this will occur on any system running a reasonably modern OSX. An opaque and frankly misleading error isn't the best introduction.

**Comment by chrmarti** [comment] 2019-08-13 10:52
@illeatmyhat Could you create a shell script with `code --verbose` in it and launch that from Finder / Spotlight? What entries to you get in the terminal window containing 'getUnixShellEnvironment'?

**Comment by chrmarti** [comment] 2019-08-13 10:54
Actually, using a shell script might work around the issue. Could you also check that the problem still exists when starting with the shell script launched from Finder / Spotlight?

**Comment by Tyriar** [comment] 2019-08-13 15:34
@chrmarti I get the impression something was wrong with @illeatmyhat's setup as `/bin/sh` was missing, maybe we should just add a better error message for that case as suggested?

**Comment by illeatmyhat** [comment] 2019-08-13 17:04
@Tyriar Since VSCode looks for `/usr/local/bin/bash` at startup, doing `ln -s /bin/bash /usr/local/bin/bash` is enough to fix the issue.
`/bin/sh` is not missing; it's a fallback in case `/usr/local/bin/bash` is missing.
I've checked many of my coworker's machines, and their bash executable is located at `/bin/bash`.

@chrmarti I ran VSCode in verbose mode without the bash symlink and I don't see any log entries containing `getUnixShellEnvironment`

**Comment by chrmarti** [comment] 2019-08-14 14:04
@illeatmyhat Why is your SHELL environment variable set to a path that does not exist?

**Comment by illeatmyhat** [comment] 2019-08-14 14:24
@chrmarti VSCode seems to think that's the default for OSX users. There doesn't seem to be a setting to change it. `terminal.integrated.shell.osx` only applies to the terminal plugin.

**Comment by Tyriar** [comment] 2019-08-14 14:57
@illeatmyhat is `$SHELL` set to `/bin/false` by your admins?

https://github.com/microsoft/vscode/blob/994e1315c09a6d92e57adf8cb9d386f5b30b4b3f/src/vs/workbench/contrib/terminal/node/terminal.ts#L40-L43

**Comment by illeatmyhat** [comment] 2019-08-14 15:31
@Tyriar $SHELL was actually set to /usr/local/bin/bash, and after some searching I had found that the login shell for my user account must have been set in the system settings by some update. Fixed it using [these instructions](https://apple.stackexchange.com/a/163802/337531)

**Comment by chrmarti** [comment] 2019-08-14 15:56
Closing with that, thanks.

**Closed by chrmarti** 2019-08-14 15:56 UTC
Labels: containers
