### ISSUE TITLE
Can not connect to remote through Remote-SSH Extension after latest update

### ISSUE THREAD

**Issue by catexis** [microsoft/vscode-remote-release#964] opened 2019-07-12 09:59 UTC
Can not connect to remote host through Remote-SSH extension after latest updates. Reinstall extension or VSCode did not help.

- VSCode Version:
```
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```
- Remote OS Version:
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1.  Install `VSCode 1.36.1`
2.  Install `Remote-SSH 0.44.1`

I get this output in console:  
```bash
remote-ssh@0.44.1
win32 x64
SSH Resolver called for "ssh-remote+work_ubu", attempt 1
SSH Resolver called for host: work_ubu
Setting up SSH remote "work_ubu"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Using SSH config file "C:\Users\kalashnikov\.ssh\config"
Install and start server if needed
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
> 
> write: Connection refused
> 
> Попытка записи в несуществующий канал.
> 
"install" terminal command done
Received install output: Попытка записи в несуществующий канал.
Failed to parse remote port from server output: Попытка записи в несуществующий канал.

------

```

![Code_2019-07-12_14-53-08](https://user-images.githubusercontent.com/25275990/61120023-788c3080-a4b5-11e9-9ea8-3de3af70fded.png)

**Comment by sakuragiyuuto** [comment] 2019-07-12 11:17
I also have the similar problem.
VSCode Version and Remote OS version are same as above.
In my case, 
I could not connect to guest OS on VirtualBox, 
but I can connect to host OS.
When I connect with ssh provided by Windows,
both can be connected.

ssh config is as follows:
```
# On VirtualBox
Host test_vscode
    HostName localhost
    user hello
    IdentityFile ~/.ssh/id_rsa
    port 22222

# On native(hostname is fake.)
Host test_n
    Hostname exmaple.com
    user hello
    IdentityFile ~/.ssh/id_ecdsa
    port 22
```
Maybe, I guess that the code around the port doesn't work well.

**Comment by bcronje** [comment] 2019-07-12 11:22
Similar issue on my side, same versions. SSH connection used to take around max 5 seconds to open folder, as of today it takes around 40 seconds to load.

**Comment by roblourens** [comment] 2019-07-12 15:36
@bcronje please open a new issue.

I don't know what the problem could be. "after latest updates" do you mean vscode update or the extension update?

Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by ostanislaw** [comment] 2019-07-12 19:58
I faced the same issue #961. It seems it is independent of the VS Code version 1.36.0 or 1.36.1. I've seen the same on latest and also previous version of vscode stable. After downgrade to 0.44.0 it is fine with 1.36.1.

**Comment by roblourens** [comment] 2019-07-12 23:48
I am not sure what's going on. Thanks for testing with downgrading. Could someone try with the nightly version of the ssh extension and share the log from the Remote-SSH output channel?

**Comment by catexis** [comment] 2019-07-13 02:47
Thank you, @ostanislaw - it's help for me. Now i have two opened terminals: with bash and with ssh tunnel. Is it correct?  
![Code_2019-07-13_07-33-46](https://user-images.githubusercontent.com/25275990/61165959-cc902700-a540-11e9-8293-0aad0dc8b038.png)

**Comment by ostanislaw** [comment] 2019-07-13 05:48
@catexis it seems you have connected properly. I don't remember if any SSH Tunnel shell was on the list in my case.

**Comment by sakuragiyuuto** [comment] 2019-07-13 06:36
@roblourens Thank you for your response.
Is version 0.44.2 the nightly version of the ssh extension? 
If this version is not, can you tell me how to install nightly version?

<details>
<summary>Remote - SSH version</summary>
<pre>
<code>
Name: Remote - SSH
Id: ms-vscode-remote.remote-ssh
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 0.44.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
</code>
</pre>
</details>

In case of version 0.44.2, I can connected to Both servers.
Remote - SSH output is as follows:

<details>
<summary>OUTPUT</summary>
<pre>
<code>
remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+test_vscode", attempt 1
SSH Resolver called for host: test_vscode
Setting up SSH remote "test_vscode"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "test_vscode" bash
Install and start server if needed
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Enter passphrase for key 'C:\Users\sakuragi/.ssh/id_rsa': 
> Enter passphrase for key 'C:\Users\sakuragi/.ssh/id_rsa':
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Running remote connection script
> 
> Found existing installation at /home/hello/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529...
> 
> SSH_CONNECTION=10.0.2.2 58362 10.0.2.15 22
> LANG=en_US.UTF-8
> XDG_SESSION_ID=7
> USER=hello
> PWD=/home/hello
> HOME=/home/hello
> SSH_CLIENT=10.0.2.2 58362 22
> MAIL=/var/mail/hello
> SHELL=/bin/bash
> SHLVL=2
> 
> LANGUAGE=en_US:en
> 
> VSCODE_AGENT_FOLDER=/home/hello/.vscode-server
> 
> LOGNAME=hello
> 
> XDG_RUNTIME_DIR=/run/user/1000
> 
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> 
> _=/usr/bin/printenv
> 
> 
> Starting server...
> 
> Waiting for server log...
> 
> 
> Waiting for server log...
> 
> 
> Waiting for server log...
> 
> 
> Waiting for server log...
> 
> 
>  
> 
> 
> *
> 
> * Reminder: You may only use this software with Visual Studio family products,
> 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> 
> *
> 
> 
> 
> 
> 2463c880-8002-4264-a278-b680572547a4==40883==39943==
> 
> 
"install" terminal command done
Received install output: 2463c880-8002-4264-a278-b680572547a4==40883==39943==
Server is listening on port 40883
Running script with connection command: "ssh" -L 127.0.0.1:40883:127.0.0.1:40883     "test_vscode" bash
Spawning tunnel with: type "C:\Users\sakuragi\AppData\Local\Temp\vscode-linux-multi-line-command-test_vscode-936298268.sh" | "ssh" -L 127.0.0.1:40883:127.0.0.1:40883     "test_vscode" bash
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Enter passphrase for key 'C:\Users\sakuragi/.ssh/id_rsa': 
> Enter passphrase for key 'C:\Users\sakuragi/.ssh/id_rsa':
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> Connected to SSH Host - Please do not close this terminal
> 
Spawned SSH tunnel between local port 40883 and remote port 40883
Waiting for ssh tunnel to be ready
Tunneling remote port 40883 to local port 40883
Resolved "ssh-remote+test_vscode" to "127.0.0.1:40883"
------
</code>
</pre>
</details>

**Comment by iamjrock** [comment] 2019-07-13 12:09
Same issue here on VS Code insiders 1.37.0.  I would like to downgrade the remote-ssh extension to 0.44.0 until it is fixed.

However, all of my Extensions are not showing, presumably because many of them plus various settings files are located on the remote (that can't be connected to):

![image](https://user-images.githubusercontent.com/38854392/61171411-b7031780-a5a9-11e9-9c6a-82f640cd8693.png)

Given this, does anyone know how I go about downgrading the remote-ssh Extension?

**Comment by catexis** [comment] 2019-07-13 12:40
@iamjrock you can do this:  
![Code_2019-07-13_17-39-05](https://user-images.githubusercontent.com/25275990/61171738-4ce07780-a595-11e9-8c25-a49d2fafcd98.png)

**Comment by iamjrock** [comment] 2019-07-13 12:44
Thx for replying @catexis, appreciated.

Unfortunately when I select the Extensions icon (your step 1) the Extensions are not listed.

It is empty as per my image in the earlier post (note: in latest Insiders the icons have changed).

**Comment by iamjrock** [comment] 2019-07-13 12:56
@roblourens, could this be related to the following recent "Improve finding SSH" [enhancement](https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_36.md#improve-finding-ssh)?

**Comment by iamjrock** [comment] 2019-07-13 14:28
OK, managed to get my extensions to show and upgrading the remote-ssh extension to v0.44.2 seems to have fixed the issue for me.  Now connecting to the remote as usual.

**Comment by roblourens** [comment] 2019-07-13 18:52
> upgrading the remote-ssh extension to v0.44.2 seems to have fixed the issue for me

Good to hear. It must have been related to the other fix I made for 0.44.2 although I'm not sure how. Can anyone else try the latest and let me know if it helps?

**Comment by GreenRobot777** [comment] 2019-07-14 16:48
I have the same error on v0.44.2 right now.

![image](https://user-images.githubusercontent.com/14993551/61186602-83032180-a691-11e9-8c1b-b28dcfb895f7.png)

my config:
```
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host roboteam
    HostName 46.229.212.5
    User roboteam-git
Host new2bas
    HostName margaret.timeweb.ru
    User new2bas
```

output:
```
remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+new2bas", attempt 1
SSH Resolver called for host: new2bas
Setting up SSH remote "new2bas"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.5p1, without OpenSSL
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "new2bas" bash
Install and start server if needed
> 
> key_load_public: invalid format
> 
> Unable to negotiate with 92.53.96.151 port 22: no matching host key type found.
> Their offer: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256
> Попытка записи в несуществующий канал.
> 
"install" terminal command done
Received install output: Попытка записи в несуществующий канал.
Failed to parse remote port from server output: Попытка записи в несуществующий канал.

------
```

**Comment by roblourens** [comment] 2019-07-14 17:12
@GreenRobot777 you are seeing a different issue. Guessing the problem is with

> `without OpenSSL`

**Comment by ostanislaw** [comment] 2019-07-15 05:15
remote-ssh 0.44.2 issue fixed for me

**Comment by JennieJi** [comment] 2019-07-23 14:14
![2019-07-23 22_12_09-Welcome](https://user-images.githubusercontent.com/1913045/61719270-30afb800-ad97-11e9-8032-979da6708333.png)
mine cannot work in either 0.44.2 or 0.44.0

**Comment by roblourens** [comment] 2019-07-23 18:27
Closing this as some say it is fixed. @JennieJi you can open a new issue.

**Closed by roblourens** 2019-07-23 18:27 UTC
Labels: needs-more-info, ssh

**Comment by JennieJi** [comment] 2019-07-24 01:54
oh ok
