### ISSUE TITLE
vscode-server `wget` fetch does not work on IPv6 only machines

### ISSUE THREAD

**Issue by grakkpl** [microsoft/vscode-remote-release#5588] opened 2021-09-15 01:25 UTC
- VSCode Version: 1.60.1 (Universal)
- Local OS Version: MacOS
- Remote OS Version: CentOS8
- Remote Extension/Connection Type: SSH
- Logs:

```
[14:32:55.073] > Acquiring lock on /home/sharatk/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/vscode-remote-lock.sharatk.83bd43bc519d15e50c4272c6cf5c1479df196a4d
[14:32:55.075] > Installing to /home/sharatk/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d...
[14:32:55.078] > 1a42a9bc05dc%%1%%
[14:32:55.080] > Downloading with wget
[14:32:55.445] > wget download failed
>
> printenv:
```

Steps to Reproduce:

1. Find a IPv6 only machine/disable IPv4 on our remote host 
2. Try connecting VSCode using SSH remote plugin
3. wget fetch will fail

Tried with curl manually too - the vscode-server host does not expose an IPv6 address

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment] 2021-09-28 22:54
Thanks for reporting! Closing as a dupe of https://github.com/microsoft/vscode-remote-release/issues/2355 - if I've missed something, please just let me know.

**Closed by bamurtaugh** 2021-09-28 22:54 UTC
Labels: ssh
