### ISSUE TITLE
RequestTTY does not modify the -T flag

### ISSUE THREAD

**Issue by vincent-van-hoef** [microsoft/vscode-remote-release#6078] opened 2021-12-17 11:32 UTC
The default ssh command from the extension seems to be fixed to `ssh -T ...`. Changing the RequestTTY options in the ssh config file to one of "yes", "no", "auto" or "force" does not change the flag (I'm under the impression it should; might be wrong here).

As a consequence I get a `Pseudo-terminal will not be allocated because stdin is not a terminal. `error. Running the ssh command manually with the `-t` flag does connect me to the server.

Seems to be referenced before here: #5683

Thanks!

**Comment by tanhakabir** [comment] 2021-12-17 15:59
To clarify:

> Running the ssh command manually with the -t flag does connect me to the server.

This means if you use terminal or PowerShell, you're able to connect to the remote with a `-t` flag but not `-T`?

**Comment by vincent-van-hoef** [comment] 2021-12-17 19:08
Sorry, that was a bit unclear. Indeed, connecting from a terminal to the remote server with `-t` works, while `-T` results in the error about the pseudo terminal.

**Comment by tanhakabir** [comment] 2022-02-08 03:08
Sorry I realize I had forgotten to reply here. 

With `-T` we're preventing the remote from allocating pseudo terminals. We need to do this to ensure that the VS Code server is set up properly on the remote.

With `-t` you're actually requesting for the remote to use a pseudo terminal. Does your server then need pseudo terminals to successfully connect and interact with them? What happens if you don't set `-T` nor `-t`?

**Comment by heroboy** [comment] 2022-02-10 06:38
I have same issue. I can't connect with '-T'.
Here is the output
```
[14:34:35.259] Log Level: 1
[14:34:35.262] remote-ssh@0.70.0
[14:34:35.262] win32 x64
[14:34:35.263] SSH Resolver called for "ssh-remote+20.0.0.229", attempt 1
[14:34:35.264] "remote.SSH.useLocalServer": false
[14:34:35.267] "remote.SSH.showLoginTerminal": true
[14:34:35.268] "remote.SSH.remotePlatform": {}
[14:34:35.268] "remote.SSH.path": undefined
[14:34:35.268] "remote.SSH.configFile": undefined
[14:34:35.268] "remote.SSH.useFlock": true
[14:34:35.269] "remote.SSH.lockfilesInTmp": false
[14:34:35.269] "remote.SSH.localServerDownload": auto
[14:34:35.269] "remote.SSH.remoteServerListenOnSocket": false
[14:34:35.270] "remote.SSH.showLoginTerminal": true
[14:34:35.270] "remote.SSH.defaultExtensions": []
[14:34:35.270] "remote.SSH.loglevel": 1
[14:34:35.271] "remote.SSH.serverPickPortsFromRange": {}
[14:34:35.271] "remote.SSH.enableDynamicForwarding": true
[14:34:35.271] "remote.SSH.serverInstallPath": {}
[14:34:35.272] SSH Resolver called for host: 20.0.0.229
[14:34:35.272] Setting up SSH remote "20.0.0.229"
[14:34:35.311] Using commit id "d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03" and quality "stable" for server
[14:34:35.315] Install and start server if needed
[14:34:36.840] Checking ssh with "ssh -V"
[14:34:36.876] > OpenSSH_for_Window
[14:34:36.876] > s_8.1p1, LibreSSL 3.0.2

[14:34:36.880] Remote command length: 6110/8192 characters
[14:34:36.880] Running script with connection command: ssh -T -D 57648 "20.0.0.229" powershell
[14:34:36.883] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:34:37.319] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[14:34:37.319] Got some output, clearing connection timeout
[14:34:37.342] "install" terminal received data: "[25l[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[H[?25h"
```
And here is what happened when connect in the command line:
```

C:\Users\heroboy\.ssh>ssh -T 20.0.0.229
WHrCg@b g
```

**Comment by pedroilidio** [comment] 2022-04-18 16:21
I have the same issue here. My use case is that I want to be able to automatically attaching to a screen after connecting to the host, which I could perfectly achieve outside vscode with the configurations:

**Comment by maxencefaldor** [comment] 2023-04-01 16:58
I have the same issue here, I would like to use tmux with the following ssh config file:

Host host
        HostName <host>
        User <user>
        RemoteCommand tmux new-session -As project
        RequestTTY force

but VSCode connects using: ssh -v -T -D 52289 -o ConnectTimeout=15 host
instead of using -t flag, resulting in an error.

How can I change the behavior of VSCode to connect using : ssh -v -t -D 52289 -o ConnectTimeout=15 host
which works?

**Comment by SouthOfAsia** [comment] 2023-04-24 06:16
I am experiencing the same issue. I want to use VSCode to connect to my server,which system is Windows Server 2012.
When I use `ssh -T Administrator@xxx.xxx.xx.xx`, the shell returns `WHrCg@b g`. 
However, when I use `ssh Administrator@xxx.xxx.xx.xx`, it returns the correct output. I believe that the -T option might have confused me.

**Comment by SouthOfAsia** [comment] 2023-04-24 09:38
> I am experiencing the same issue. I want to use VSCode to connect to my server,which system is Windows Server 2012. When I use `ssh -T Administrator@xxx.xxx.xx.xx`, the shell returns `WHrCg@b g`. However, when I use `ssh Administrator@xxx.xxx.xx.xx`, it returns the correct output. I believe that the -T option might have confused me.

Is not ‘-t’ makes error
I update my Server‘s Powershell Version 4.0 to 5.0 and it works.

**Comment by adamfitz** [comment] 2023-05-11 04:35
I am experiencing the same issue, where I am not able to open a remote ssh session to my target server (linux) because vscode is forcing the use of the `-T` flag.

I tested the following connection string from my client and confirmed I get the same connection error as I get when testing from vscode:

`"C:\windows\System32\OpenSSH\ssh.exe" -T -D 61757 "$target_server"`

When I remove the `-T` flag the connection works as expected.

Also I can see the ssh config parameters `RemoteCommand` and `RequestTTY` are simply ignored by vscode so I am unable to use this as a workaround.

Is there any option/setting to allow the user to change this behavior and remove the `-T` flag from the connection string or force a TTY as a workaround?

**Comment by paperdave** [comment] 2023-12-16 00:41
haven't verified but a potential way to reproduce this may be to install debian 12.2 and switch your user's shell to fish, `ssh -T` no longer works on that user.

is there a reason we cannot make `-T` vs `-t` configurable, and also detect a hang to make this error easier for users to deal with.

**Comment by jcarpinelli-bdai** [comment] 2024-03-13 13:34
I see `RemoteCommand` is experimentally supported. That's great! I hope it is possible to add `RequestTTY` support as well. Some shells, like `nushell`, require TTY. Right now, to use non-standard shells like `nushell`, I believe users can also disable the "Use Local Server" option of the Remote SSH extension; that seems to cause VSCode to request a TTY for each terminal.

**Comment by YourGraceQI** [comment] 2024-07-11 09:28
I am facing the same issue, while vs remote ssh keep adding the -T flag, adding RequestTTY doesn't help, and RemoteCommand also do nothing, anyone can help?

**Comment by iamsiita** [comment] 2024-08-12 09:07
vscode keeps adding `-T` flag even after adding `RequestTTY force`.
vscode continues to add `-T` flag  even if the "Use Local Server" option is turned off.
 Is there a way to disable the `-T` flag? If not, will it be added in the future?

**Comment by ManiaciaChao** [comment] 2024-08-15 12:25
Same here. My case is to connect to a server which is bebind a jump server, with option `ProxyJump`
`ssh hostname` works but not for `ssh -T hostname`.

**Comment by roblourens** [comment] 2024-08-15 18:41
I think this issue is a dupe of https://github.com/microsoft/vscode-remote-release/issues/7558#issuecomment-2239919384 that I didn't realize we had. Yes, that new setting is right, please try it out and give feedback in the other issue, thanks

**Closed by roblourens** 2024-08-15 18:41 UTC
Labels: bug, ssh
