### ISSUE TITLE
shutdownAction stopCompose does not stop in 0.262.3 (but works on 0.255.4)

### ISSUE THREAD

**Issue by jsedano-emobg** [microsoft/vscode-remote-release#7754] opened 2022-12-20 18:26 UTC
- VSCode Version: 1.74.1
- Local OS Version: MacOS Ventura 13.0.1
- Remote OS Version:
- Remote Extension/Connection Type: Dev Containers
- Dev Container version: works with 0.255.4; fails with 0.262.3 and higher

Looks like the shutdownAction=stopCompose in .devcontainer.json is not stopping the containers.

Steps to Reproduce:

0. Verify what containers are running (docker container ls)
1. Open VSCode and use "Clone in named container volume". Clone this repo: git@gitlab.com:javier-sedano/hormiga.git (but other private work-related repos fail as well)
2. Wait until the environment is ready and verify what containers are running. Verify that there is a container running for the project (hormiga_devcontainer_hormiga_1)
3. Close VSCode.
4. Check whether the container hormiga_devcontainer_hormiga_1 is stopped... after a few seconds it should be automatically stopped, but it is not.

**Comment by jsedano-emobg** [comment] 2022-12-20 18:35
Sorry, more details: I am using Rancher Desktop 1.7.0

I do not know if it happens on Windows
I do not know if it happens with Docker Desktop

**Comment by chrmarti** [comment] 2022-12-30 08:37
Normally there is a log in `F1` > `Dev Containers Developer: Show All Logs...` for the shutdown monitor, but I need to fix the file lookup for that first, sorry about that. Could you append the last log after this failed listed in `ls /Users/chrmarti/Library/Application\ Support/Code/logs/*/window*/exthost/ms-vscode-remote.remote-containers/shutdownMonitor-*.log` when run from a terminal?

**Comment by jsedano-emobg** [comment] 2022-12-30 09:58
Hello,

  well... I do not know if the F1 thing is enough, because this happens when I close VSCode. No longer there's a VSCode where to press F1 ;-) (or maybe I am misunderstanding you).

The log (tested with the latest version v0.266.1):

```
javier.sedano@MacBook-Pro-de-admeis ~ % cat "`ls /Users/javier.sedano/Library/Application\ Support/Code/logs/*/window*/exthost/ms-vscode-remote.remote-containers/shutdownMonitor-*.log | tail -1`"
[2022-12-30T09:48:18.073Z] Starting monitor process...
[2022-12-30T09:48:18.079Z] Received message: [{"type":"configure","sequence":0,"options":{"cwd":"/","dockerCLI":"docker","dockerComposeCLI":{"version":"2.14.0","cmd":"docker-compose","args":[]},"env":{"ELECTRON_RUN_AS_NODE":"1","MallocNanoZone":"0","USER":"javier.sedano","COMMAND_MODE":"unix2003","__CFBundleIdentifier":"com.microsoft.VSCode","PATH":"/Users/javier.sedano/.rd/bin:/Users/javier.sedano/.nvm/versions/node/v14.19.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/javier.sedano/Library/Application Support/JetBrains/Toolbox/scripts","LOGNAME":"javier.sedano","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.xKK7VfrUn9/Listeners","HOME":"/Users/javier.sedano","SHELL":"/bin/zsh","TMPDIR":"/var/folders/fj/r7rg8dlj02v1q3_tpvylyn8w0000gp/T/","__CF_USER_TEXT_ENCODING":"0x1F6:0x0:0x0","XPC_SERVICE_NAME":"application.com.microsoft.VSCode.17383109.17383115","XPC_FLAGS":"0x0","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_CWD":"/","VSCODE_NLS_CONFIG":"{\"locale\":\"en-gb\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_CODE_CACHE_PATH":"/Users/javier.sedano/Library/Application Support/Code/CachedData/e8a3071ea4344d9d48ef8a4df2c097372b0c5161","VSCODE_IPC_HOOK":"/Users/javier.sedano/Library/Application Support/Code/1.74.2-main.sock","VSCODE_PID":"45046","SHLVL":"0","PWD":"/","OLDPWD":"/","NVM_DIR":"/Users/javier.sedano/.nvm","NVM_CD_FLAGS":"-q","NVM_BIN":"/Users/javier.sedano/.nvm/versions/node/v14.19.1/bin","NVM_INC":"/Users/javier.sedano/.nvm/versions/node/v14.19.1/include/node","_":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","DISPLAY":"1","SSH_ASKPASS":"/Users/javier.sedano/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/scripts/ssh-askpass.sh","SSH_ASKPASS_REQUIRE":"force","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/javier.sedano/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/common/sshAskpass.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/fj/r7rg8dlj02v1q3_tpvylyn8w0000gp/T/ssh-askpass-28745364df108b99f4647e714955caacced64b90.sock","DOCKER_CONTEXT":"default"},"containerId":"310512a4285625d365ee69298a5ded75c02b03efb3ce9881215a245cd8eafe1c","user":"root","sessionId":"6869b0b2-527f-4a3a-b51c-d105590add461672393693126","shutdownAction":"stopCompose","projectName":"pam-theme_devcontainer","composeFiles":["/workspaces/pam-theme/.devcontainer/docker-compose.yml"],"buildContainerRunArgs":["run","-d","--mount","type=volume,src=vsc-remote-containers,dst=/workspaces","-v","/var/run/docker.sock:/var/run/docker.sock","vsc-volume-bootstrap","sleep","infinity"],"service":"pam-theme","logLevel":2,"delay":10000}}]
[2022-12-30T09:48:19.377Z] Received message: [{"type":"configure","sequence":1,"options":{"cwd":"/","dockerCLI":"docker","dockerComposeCLI":{"version":"2.14.0","cmd":"docker-compose","args":[]},"env":{"ELECTRON_RUN_AS_NODE":"1","MallocNanoZone":"0","USER":"javier.sedano","COMMAND_MODE":"unix2003","__CFBundleIdentifier":"com.microsoft.VSCode","PATH":"/Users/javier.sedano/.rd/bin:/Users/javier.sedano/.nvm/versions/node/v14.19.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/javier.sedano/Library/Application Support/JetBrains/Toolbox/scripts","LOGNAME":"javier.sedano","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.xKK7VfrUn9/Listeners","HOME":"/Users/javier.sedano","SHELL":"/bin/zsh","TMPDIR":"/var/folders/fj/r7rg8dlj02v1q3_tpvylyn8w0000gp/T/","__CF_USER_TEXT_ENCODING":"0x1F6:0x0:0x0","XPC_SERVICE_NAME":"application.com.microsoft.VSCode.17383109.17383115","XPC_FLAGS":"0x0","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_CWD":"/","VSCODE_NLS_CONFIG":"{\"locale\":\"en-gb\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_CODE_CACHE_PATH":"/Users/javier.sedano/Library/Application Support/Code/CachedData/e8a3071ea4344d9d48ef8a4df2c097372b0c5161","VSCODE_IPC_HOOK":"/Users/javier.sedano/Library/Application Support/Code/1.74.2-main.sock","VSCODE_PID":"45046","SHLVL":"0","PWD":"/","OLDPWD":"/","NVM_DIR":"/Users/javier.sedano/.nvm","NVM_CD_FLAGS":"-q","NVM_BIN":"/Users/javier.sedano/.nvm/versions/node/v14.19.1/bin","NVM_INC":"/Users/javier.sedano/.nvm/versions/node/v14.19.1/include/node","_":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","DISPLAY":"1","SSH_ASKPASS":"/Users/javier.sedano/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/scripts/ssh-askpass.sh","SSH_ASKPASS_REQUIRE":"force","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/javier.sedano/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/common/sshAskpass.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/fj/r7rg8dlj02v1q3_tpvylyn8w0000gp/T/ssh-askpass-28745364df108b99f4647e714955caacced64b90.sock","DOCKER_CONTEXT":"default"},"containerId":"310512a4285625d365ee69298a5ded75c02b03efb3ce9881215a245cd8eafe1c","user":"root","sessionId":"6869b0b2-527f-4a3a-b51c-d105590add461672393693126","shutdownAction":"stopCompose","projectName":"pam-theme_devcontainer","composeFiles":["/workspaces/pam-theme/.devcontainer/docker-compose.yml"],"buildContainerRunArgs":["run","-d","--mount","type=volume,src=vsc-remote-containers,dst=/workspaces","-v","/var/run/docker.sock:/var/run/docker.sock","vsc-volume-bootstrap","sleep","infinity"],"service":"pam-theme","logLevel":2,"delay":10000}}]
[2022-12-30T09:48:53.622Z] Received message: [{"type":"cleanup"}]
[2022-12-30T09:48:53.623Z] Cleaning up after 35550 ms...
[2022-12-30T09:48:53.623Z] Delaying for 10000 ms.
[2022-12-30T09:49:03.627Z] Start: Run in container: /bin/sh
[2022-12-30T09:49:03.633Z] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[2022-12-30T09:49:03.814Z] Stop (181 ms): Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[2022-12-30T09:49:03.816Z] Start: Run: docker run -d --mount type=volume,src=vsc-remote-containers,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[2022-12-30T09:49:04.150Z] Stop (334 ms): Run: docker run -d --mount type=volume,src=vsc-remote-containers,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[2022-12-30T09:49:04.150Z] Start: Run in container: docker-compose --project-name pam-theme_devcontainer -f /workspaces/pam-theme/.devcontainer/docker-compose.yml stop -t 0
[2022-12-30T09:49:04.251Z] Stop (101 ms): Run in container: docker-compose --project-name pam-theme_devcontainer -f /workspaces/pam-theme/.devcontainer/docker-compose.yml stop -t 0
[2022-12-30T09:49:04.251Z] Start: Run: docker rm -f 5e03df6499462175540956af84252d737248db88db42ffde4855b7da2040c750
[2022-12-30T09:49:04.466Z] Stop (215 ms): Run: docker rm -f 5e03df6499462175540956af84252d737248db88db42ffde4855b7da2040c750
[2022-12-30T09:49:04.466Z] Unexpected error: Command failed: docker-compose --project-name pam-theme_devcontainer -f /workspaces/pam-theme/.devcontainer/docker-compose.yml stop -t 0
javier.sedano@MacBook-Pro-de-admeis ~ % 
```

**Comment by superlevure** [comment] 2023-02-14 08:57
`shutdownAction` is still not being executed for me on:

```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (5 days ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 19.6.0
Sandboxed: No
```

**Comment by jsedano-emobg** [comment] 2023-02-16 12:03
I have just tested with 0.275.1 and it still fails to shut down the container.

Looks like at least reopening the project will reuse the container, so the reopening of the project does not fail. But it is wasting resources in the background (at least in my scenario, where I work with quite a few projects opening and closing them for a quick peer-review with a colleague, and very rarely reboot).

**Comment by jsedano-emobg** [comment] 2023-03-24 07:28
Any advance on this topic?

**Comment by chrmarti** [comment] 2023-03-24 07:55
@jsedano-emobg The log shows a command failing, could you rerun that from the terminal to see if that works or shows additional output?
```
docker-compose --project-name pam-theme_devcontainer -f /workspaces/pam-theme/.devcontainer/docker-compose.yml stop -t 0
```

**Comment by jsedano-emobg** [comment] 2023-03-24 11:10
Sorry... how can I run this command?

If I run it inside the devcontainer... am I killing myself? Then, I will see no log, right?

If I run it outside the devcontainer... I cannot access /workspaces/pam-theme/.devcontainer/docker-compose.yml because /workspace/ is the path inside the container.

Or maybe you want me to run it inside and then dump [my equivalent to] `/Users/chrmarti/Library/Application\ Support/Code/logs/*/window*/exthost/ms-vscode-remote.remote-containers/shutdownMonitor-*.log`?

**Comment by chrmarti** [comment] 2023-04-05 07:41
You are right, you actually cannot run it. It is run inside a temporary container, we need to add more logging to track this down.

**Comment by xenoliss** [comment] 2023-04-05 09:50
Hey there, facing similar issues. 

- The "Open Folder in Container" is only starting the selected container instead of starting all the containers associated with the compose file. It happens regardless of the "depends_on" property of the compose file.
- Closing VSCode does not stop any containers of the compose file (even the one associated with the workspace keeps running).

Versions:
- Dev Containers extension:  0.288.0
- Docker Desktop:  4.17.1 (101757)

**Comment by chrmarti** [comment] 2023-04-06 07:17
@xenoliss Is this when using the `Clone Repository in Container Volume` command or with a local folder?

**Comment by xenoliss** [comment] 2023-04-06 10:24
@chrmarti Yes I'm facing this issue after using `Clone Repository in Container Volume` but I don't think that's linked to this directly. You can also view the problem by:

1. Create a new dev container within vscode
2. Select "Node.js & Mongo DB"

![image](https://user-images.githubusercontent.com/33523487/230348327-02991217-ae0c-4a62-b96d-81c7f289d558.png)

3. Let the workspace load in vs code and then close vs code
4. **Notice that eventhoug vscode is closed, the compose stack is still running**

![image](https://user-images.githubusercontent.com/33523487/230348908-b8229495-73cf-403e-bb50-5c9172602ed3.png)

**Comment by xenoliss** [comment] 2023-04-07 09:59
@chrmarti adding to my previous message about `sutdownAction` not working as expected.

I also mentioned [here](https://github.com/microsoft/vscode-remote-release/issues/7754#issuecomment-1497216928) that :

> * The "Open Folder in Container" is only starting the selected container instead of starting all the containers associated with the compose file. It happens regardless of the "depends_on" property of the compose file.

I managed to have a reproductible PoC about that:

1. Create a new dev container within vscode
2. Select "Node.js & Mongo DB"
3. Wait for the workspace to load and then update the `docker-compose.yml` file and comment the line `network_mode: service:db`
4. Rebuild the container to take into account the change (Ctrl+Shit+P > `Rebuild Container`)
5. In Docker desktop, notice that only the "app" container has been rebuilt. And while I'm not sure about why this is the case, it seems to be the origin of the problem.

![image](https://user-images.githubusercontent.com/33523487/230588839-351ffd3d-74c2-4140-acea-e4367401e533.png)

6. Come back in vs code and close the remote connection (Ctrl+Shift+P > `Close Remote Connection`)
7. In Docker Desktop, stop the compose stack manually by clicking the "Stop" button: 
8. 
9. aaa
10. aaa

**Comment by akutruff** [comment] 2023-04-07 17:39
+1 here

```
[2023-04-07T17:34:04.947Z] Received message: []
[2023-04-07T17:34:31.961Z] Received message: [{"type":"cleanup"}]
[2023-04-07T17:34:31.962Z] Cleaning up after 88096 ms...
[2023-04-07T17:34:31.962Z] Delaying for 10000 ms.
[2023-04-07T17:34:41.975Z] Start: Run in container: /bin/sh
[2023-04-07T17:34:42.006Z] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[2023-04-07T17:34:42.268Z] Stop (262 ms): Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[2023-04-07T17:34:42.269Z] Start: Run: docker run -d --mount type=volume,src=planner-69ea4d48b87f12a7f608ce286c91c1233d20a4909d5e75bb6b799f7f21a56e99,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[2023-04-07T17:34:43.149Z] Stop (880 ms): Run: docker run -d --mount type=volume,src=planner-69ea4d48b87f12a7f608ce286c91c1233d20a4909d5e75bb6b799f7f21a56e99,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[2023-04-07T17:34:43.150Z] Start: Run in container: docker-compose --project-name planner_devcontainer -f /workspaces/planner/.devcontainer/docker-compose.yml stop -t 0
[2023-04-07T17:34:43.475Z] Stop (325 ms): Run in container: docker-compose --project-name planner_devcontainer -f /workspaces/planner/.devcontainer/docker-compose.yml stop -t 0
[2023-04-07T17:34:43.475Z] Start: Run: docker rm -f 3a5148ee93b10cb68c24cb2542ad79dd5bd27a6b488e65a76ddf9205b6a7cf03
[2023-04-07T17:34:44.064Z] Stop (589 ms): Run: docker rm -f 3a5148ee93b10cb68c24cb2542ad79dd5bd27a6b488e65a76ddf9205b6a7cf03
[2023-04-07T17:34:44.064Z] Unexpected error: Command failed: docker-compose --project-name planner_devcontainer -f /workspaces/planner/.devcontainer/docker-compose.yml stop -t 0

```

**Comment by SmallhillCZ** [comment] 2023-04-12 08:03
+1 on
- VSCode Version: 1.77.2
- Local OS Version: Windows 11, build 22624.1546
- Remote OS Version: Docker Desktop 4.18.0 (Docker Engine 20.10.24) in WSL2

```
[2023-04-12T07:39:42.609Z] Stop (614 ms): Run: docker rm -f 45068142321b766286763f90387f5f852a107399dd8c0937e533f29694bbf277
[2023-04-12T07:39:42.609Z] Unexpected error: Command failed: docker-compose --project-name interni-sekce_devcontainer -f /workspaces/interni-sekce/.devcontainer/docker-compose.yml stop -t 0
```

**Comment by SmallhillCZ** [comment] 2023-04-12 08:26
Noticed one thing in the startup, it is testing which docker compose version is used (the old one with dash or the new one with dash):
```
[9263 ms] Start: Resolving Remote
[9272 ms] Start: Run: docker-compose version --short
[9276 ms] Start: Run: docker compose version --short
[9357 ms] Docker Compose version: 2.12.2
```

And in the `vsc-volume-bootstrap` container (run devcontainer and close VSC during startup leaves this container behind, which is also an issue) running the closing docker-compose fails:

```
/ # docker-compose --project-name tjn-data-portal_devcontainer -f /workspaces/tjn-data-portal/.devcontainer/docker-compo
se.yml stop -t 0
/bin/sh: docker-compose: not found
```

And in version 0.255.4 the old docker-compose is present in the vsc-volume-bootstrap container:
```
/ # docker compose --version
Docker version 20.10.11, build dea9396e184290f638ea873c76db7c80efd5a1d2
/ # docker-compose --version
docker-compose version 1.28.0, build unknown
/ # 
```

**Closed** 2023-04-13 10:04 UTC
Labels: bug, containers

**Comment by jsedano-emobg** [comment] 2023-05-09 09:18
Using VSCode 1.78.0 and DevContainers 0.292.0 I can confirm the problem does not show up anymore.

**Comment by xenoliss** [comment] 2023-05-10 13:04
I'm on VsCode 1.78.1 and DevContainers v0.292.0, I can only confirm that closing now correctly shut down the docker compose stack. 

However the "Open Folder In Container" feature, when used on a container that is part of a compose stack, does still not load the whole compose stack. Only the dev container is opened.
