### ISSUE TITLE
VSC Insiders unable to connect to WSL server

### ISSUE THREAD

**Issue by afernando79** [microsoft/vscode-remote-release#1972] opened 2019-12-04 10:24 UTC
Issue Type: <b>Bug</b>

Start VSC Insiders (within Windows)
Open folder
Bottom left Reopen folder in WSL

Results:
[2019-12-04 10:09:04.286] Resolving wsl+ubuntu, resolveAttempt: 1
[2019-12-04 10:09:05.324] Starting VS Code Server inside WSL (u)
[2019-12-04 10:09:05.324] Extension version: 0.41.2, Windows build: 18362. Multi distro support: available. WSL path support: enabled
[2019-12-04 10:09:06.308] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d u -e sh -c "[ -d ~/.vscode-server-insiders/bin/<local folder here>] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2019-12-04 10:09:08.338] Unable to detect if server is already installed: Error: Command failed: C:\WINDOWS\System32\wsl.exe -d u -e sh -c "[ -d ~/.vscode-server-insiders/bin/<local folder here> ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2019-12-04 10:09:08.339] Launching C:\WINDOWS\System32\wsl.exe -d u sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" <local folder here> insider .vscode-server-insiders 0  ' in c:\Users\andrew.fernando\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.41.2
[2019-12-04 10:09:09.701] There is no distribution with the supplied name.
[2019-12-04 10:09:09.701] 
[2019-12-04 10:09:09.703] VS Code Server for WSL closed unexpectedly.
[2019-12-04 10:09:09.703] For help with startup problems, go to
[2019-12-04 10:09:09.704] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tip

It appears the name of the distribution is being truncated to "u" instead of "ubuntu". Running 'C:\WINDOWS\System32\wsl.exe -d u -e sh -c "[ -d ~/.vscode-server-insiders/bin/<local folder here>] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"' fails with above error even from a command prompt.

Running 'C:\WINDOWS\System32\wsl.exe -d ubuntu -e sh -c "[ -d ~/.vscode-server-insiders/bin/<local folder here>] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"' is successful.

Could this be some sort of indexing the first character of the string instead of an array (assuming it would expect to get a list of distributions from which it would select the first).

VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:40:39.806Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (3.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>Extensions: none

**Comment by aeschli** [comment] 2019-12-05 10:40
This was a bug in the extension, not related to an update of VSCode. Sorry for the trouble.
Extensions are tested for updates every 12h, unless you open the extensions viewlet.
I agree that for this case polling more often would be ideal.

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/1962

**Closed by aeschli** 2019-12-05 10:40 UTC

**Comment by envp** [comment] 2020-01-19 04:24
This is still occuring on:

```
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by aeschli** [comment] 2020-01-21 09:02
@envp Please file a new issue with the full content of the WSL log.
