### ISSUE TITLE
Unable to attach vscode to a running container on a remote server

### ISSUE THREAD

**Issue by scribblepad** [microsoft/vscode-remote-release#4994] opened 2021-05-02 02:59 UTC
I'm trying to attach vscode to a tensorflow container running on a remote server (connected via jump server).
I can ssh to the server using vscode remote ssh. I can view the containers running on the left navigation pane and also attach shell. But when I try to attach visual studio code the running container, nothing happens.

- VSCode Version: 1.55.2
- Local OS Version: Windows 10 19.09
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/WSL : SSH then docker
- Logs:
 [23 ms] Remote-Containers 0.166.1 in VS Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d).
[3138284 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[3559000 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[3776287 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[5239557 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[5751694 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[5862894 ms] Start: Run: docker version --format {{.Server.APIVersion}}

Steps to Reproduce:

1. Connect to remote node using remote ssh
2. Make sure ssh config file has both jumpserver and the compute server details (proxy command)
3. Open a python file in the server using vscode. (this is to establish the connection is gone through correctly)
4. Now click on the docker on the left
5. select the container, right click and select attach visual studio code
6. Now, it doesn't attach the vscode

![image](https://user-images.githubusercontent.com/75389751/116800577-15bfbb00-aac8-11eb-9fbf-bc4ddea78c20.png)

**Comment by chrmarti** [comment] 2021-05-03 10:21
What's the command line to ssh into the server? Does that require any password/passphrase to connect?

**Comment by scribblepad** [comment] 2021-05-03 15:54
I use the config file, I've created ssh keys and added it to jumpserver and computeserver. But for some reason it still asks the password for jumpserver.

**config file:**

Host *
    ServerAliveInterval 60
    PubkeyAuthentication yes

Host jumpserver
    Hostname x.x.x.x
    User user
    ForwardX11 yes
    IdentityFile path\.ssh\id_rsa

Host computeserver
    HostName y.y.y.y
    User user
    IdentityFile path\.ssh\id_rsa
    ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -l user x.x.x.x -W %h:%p

**Comment by scribblepad** [comment] 2021-05-06 17:56
hey @chrmarti did you get a chance to check this?

**Comment by chrmarti** [comment] 2021-05-07 07:54
Have you tried replacing `x.x.x.x` in ProxyCommand with `jumpserver`? I'm not sure ssh will use the jumpserver config the way you have it now.

**Comment by scribblepad** [comment] 2021-05-07 10:39
@chrmarti Yes I tried to do that, replacing x.x.x.x in ProxyCommand with jumpserver. But vscode throws the following error,
"ssh: Could not resolve hostname **jumpserver**: No such host is known."

If I'm connecting to compute nodes using any ssh client, I always mention like you had suggested. But vscode doesn't resolve hostname so had to change to what works with vscode.

**Comment by chrmarti** [comment] 2021-05-10 07:12
What is your ssh version? (`ssh -V`)

**Comment by scribblepad** [comment] 2021-05-25 22:12
@chrmarti any updates on this?

**Comment by chrmarti** [comment] 2021-05-26 07:32
Can you try the following from the command line (PowerShell):
```
$env:DOCKER_HOST='ssh://computeserver'
docker ps
```

**Comment by scribblepad** [comment] 2021-06-05 19:49
@chrmarti 

Below is the output from powershell

CONTAINER ID   IMAGE                                      COMMAND   CREATED       STATUS      PORTS                              NAMES
0e2a2f711a14   tensorflow/tensorflow:latest-gpu-jupyter   "bash"    4 weeks ago   Up 8 days   8888/tcp, 0.0.0.0:9000->9000/tcp   test

**Comment by scribblepad** [comment] 2021-06-05 19:53
@chrmarti 
when I connect to vscode remote, I can see the container running, but unable to attach shell or attach visual studio code
![image](https://user-images.githubusercontent.com/75389751/120903777-c3fdd980-c60d-11eb-847f-a91e21be21f4.png)


Error when trying to attach shell:

![image](https://user-images.githubusercontent.com/75389751/120903719-65386000-c60d-11eb-8d58-387b38270f3a.png)

Error when trying to attach vscode:

![image](https://user-images.githubusercontent.com/75389751/120903736-80a36b00-c60d-11eb-80af-f1b21dcde265.png)

**Comment by scribblepad** [comment] 2021-06-05 19:55
@chrmarti Should I create a new issue and link this one or can you reopen this as the issue is not resolved.

**Comment by chrmarti** [comment] 2021-06-07 07:27
Do you get the 'no running containers' dialog while connected with Remote-SSH? If so, make sure to open a folder first (tracked as https://github.com/microsoft/vscode-remote-release/issues/4913).

**Comment by scribblepad** [comment] 2021-06-07 12:57
@chrmarti Thanks for the response. After opening a folder first, I can attach a running container to a shell fine but attaching a running container to a vscode still errors out. I think it fails at the **bold** line below trying to cat /etc/passwd

Error from the log:
[10614 ms] Start: Run: docker inspect --type container bb98f278f517f304bc6c908a001a976358a946a88be76dee36eef949f241efee
[16137 ms] Start: Run in container: /bin/sh
[16205 ms] Start: Run in container: uname -m
**[22151 ms] Start: Run in container: cat /etc/passwd**
[22152 ms] Stdin closed!
[22157 ms] Shell server terminated (code: 1, signal: null)

command [ssh -- computeserver docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh_exchange_identification: read: Connection reset
ssh_exchange_identification: Connection closed by remote host

**Comment by chrmarti** [comment] 2021-06-08 06:57
That seems to be an issue with the SSH server's configuration. See, e.g., https://phoenixnap.com/kb/fix-connection-reset-by-peer-ssh-error for suggestions on how to address these.

**Comment by scribblepad** [comment] 2021-06-09 07:28
@chrmarti I checked the ssh servers config it looks correct.

I tried to follow this [https://github.com/microsoft/vscode-remote-release/issues/4072](url)
Looking at the container logs its similar to the original issue. Getting the same error during the Get.


**[2021-06-09T07:10:38.265Z] error during connect: Get "http://docker/v1.24/containers/03fc8e1ef794999bfac2b5235ed2dfb9c713fbac306ca6ca15e36b152935854f/json"**: command [ssh -- computeserver docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh_exchange_identification: read: Connection reset
ssh_exchange_identification: Connection closed by remote host

**Comment by scribblepad** [comment] 2021-06-09 17:07
Just to want to make sure I'm doing the right steps,

On vscode
1. Connect to remote host (it connects without requiring password)
2. I open a folder in remote machine
3. Select docker extension on the left pane (it shows all the containers, images on the remote machine)
4. ctrl+shift+p , attach to a running container or right click on the container and attach visual studio code. (attaching to containers shell works fine)

**Comment by chrmarti** [comment] 2021-06-11 11:30
That looks good. Apparently the ssh connection works when using Remote-SSH.

Does the following work (in PowerShell on your local machine)?
```
$env:DOCKER_HOST='ssh://computeserver'
docker ps
```
And what's the configuration in `~/.ssh/config` for `computeserver`?

**Comment by scribblepad** [comment] 2021-06-13 21:18
@chrmarti yes, it works on powershell too. vscode is a really useful IDE and it would be good If I can figure out how to attach it the container as all my work is run on a remote server and in containers.

>> docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS          PORTS                              NAMES
8f84c1efa30b   tensorflow/tensorflow:latest-gpu-jupyter   "bash"                   11 seconds ago   Up 11 seconds   8888/tcp, 0.0.0.0:9000->9000/tcp   tf-test

**config file:**

Host *
	ServerAliveInterval 60
	PubkeyAuthentication yes

Host jumpserver
	Hostname x.x.x.x
	User user
	ForwardX11 yes
	IdentityFile \path\.ssh\id_rsa

Host computeserver
	HostName y.y.y.y
	User user
	IdentityFile \path\.ssh\id_rsa
	ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -l user jumpserver -W %h:%p

**Comment by chrmarti** [comment] 2021-06-14 09:00
Sorry, missed that you answered that before. Could you try getting the update for SSH. That should now be available through Windows Update: https://github.com/PowerShell/Win32-OpenSSH/issues/1693#issuecomment-829520885

**Comment by scribblepad** [comment] 2021-06-15 23:58
@chrmarti Mine is a corp Windows OS, so wouldn't be able to get the windows update manually.
Any other workarounds without the windows update?

My current version:
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

**Comment by PavelSosin-320** [comment] 2021-06-16 05:14
Yet other +++ for the running VSCode server via Systemd Unit: Do [Run container using systemd unit](https://www.jetbrains.com/help/youtrack/standalone/run-docker-container-as-service.html) add all needed dependencies like VSCode.service, Network.target, sshd.service, copy to the proper directory and everything will work out-of-the-box. Some Linux distros require manual creation of "differential" sshd user to enable the creation of sshd session slice automatically without root remote login.

**Comment by chrmarti** [comment] 2021-06-16 05:52
@scribblepad Running low on ideas. Since it works from the command line and with Remote-SSH, I would expect it to work with Remote-Containers too. Maybe try `docker inspect` from your local machine:
```
$env:DOCKER_HOST='ssh://computeserver'
docker ps
docker inspect <container id>
```
Also check the SSH server versions on the jumpserver and the computeserver.

**Comment by GoingMyWay** [comment] 2021-10-17 02:13
It seems it cannot connect the remote on macOS M1. My localhost is macOS, remote machine Linux. Docker version on macOS M1: 20.10.8. 

![image](https://user-images.githubusercontent.com/9346460/137607781-787fd7f6-8567-4f90-880a-c343a5b3bf43.png)


The following is the error log

```
[15687 ms] Remote-Containers 0.202.4 in VS Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63).
[15687 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[24724 ms] 
[24724 ms] error during connect: Get "http://docker.example.com/v1.24/version": command [ssh -- 155.69.145.109 docker system dial-stdio] has exited with exit status 1, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
Usage:  docker system COMMAND

Manage Docker

Commands:
  df          Show docker disk usage
  events      Get real time events from the server
  info        Display system-wide information
  prune       Remove unused data

Run 'docker system COMMAND --help' for more information on a command.
```

**Comment by lacraig2** [comment] 2022-01-05 18:58
I had this issue on vscode 1.63.2 running on maOS 11.6.2 MBP 2019 model. Reloading the workspace seems to have fixed it.

**Comment by Dovermore** [comment] 2022-03-02 22:59
I have the same issue.
Working machine: MacbookPro 2018, Host machine: Linux
It's possible for me to attach terminal, but I am getting the same error when attaching VScode to it.

**Comment by chrmarti** [comment] 2022-03-07 08:48
@Dovermore Could you open a new issue with the details of what is not working? This issue is currently stalled as we don't have enough insight into how to proceed and there is a chance that yours has a different cause.

**Comment by Dovermore** [comment] 2022-03-07 09:30
I did some debugging myself and found out what's wrong in my case. **The deploy script container I am using disabled admin privilege**. This causes vscode extension to fail at some sort of create directory command. I couldn't recall what exact command the extension is trying to run.

It is also very very random how you can see this message. It took me repeated tries of closing and reopening vscode in order to see this message. In most cases, the extension will just fail loading and a small pop up on the bottom right says extension failed with the message:
`command [ssh -- computeserver docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh_exchange_identification: read: Connection reset
ssh_exchange_identification: Connection closed by remote host`
But in some rare cases, a new window will be opened, and you can briefly glimpse the issues when it tries to load container.

I hope these are helpful.

**Comment by chrmarti** [comment] 2022-03-07 11:21
@Dovermore How did you 'disable admin privilege'? Thanks.

**Comment by Dovermore** [comment] 2022-03-07 11:27
@chrmarti by that I mean run `docker run` with `-u` option. You can specify a user ID and group id to disable admin for any connected users.

**Comment by Louis-Riel** [comment] 2022-05-07 01:00
@Dovermore I can confirm this. I docker-compose a bunch of containers, and I cannot connect vscode to running containers when said container is running with the ```user: someuser:somegroup``` directive, lowering it's privs within the container. 

When vscode tries to connect, it tries to install the vscode tooling in /root, and then fails expectedly with:
```
Command in container failed: mkdir -p /root/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898_1651883277247
```
That makes it a difficult problem to solve. /root is pretty much the only ***home*** directory that you can rely on. If the user is not root, then it's home folder's location can not be assumed or inferred easily/consistently. I guess maybe /tmp could be a candidate, but the shivers are running down my spine just thinking about the potential issues there.

The only option I see is to have a ```Attach VSCode to container (needs restart)``` type thing for containers detected as running unprivileged, and have it
- Stop the container
- Modify the image to have a volume for the tooling
- Start the container
- Dump the tooling

But the cleanup would be a terrible mess. Like maybe there could be a visual indicator in the docker sidebar to show the containers that are in ***debug mode*** with a right-clicky to remove ***debug mode***. 

It's a bit of a chicken/egg conundrum, although that one has been resolved by now. Chicken. 

A super dirty, nasty, inconsiderate workaround to this issue is to
```
docker exec -u 0 influxdb bash -c "chmod 777 /root"
```
Which will make /root world readable/writable, and so allow vscode to put it's tooling in no problem. The potential issue, that will absolutely happen, is that during one of those troublesome prod deployments with all the gremlins in the wires, someone will do that in prod, and set the stage for the next enterprising technologist looking for lateral movement.

**Comment by chrmarti** [comment] 2022-05-09 07:50
We use the container user's home folder as given in the container's `/etc/passwd`. Setting the `HOME` environment variable on the container would override it.

**Closed** 2022-05-16 12:37 UTC
Labels: containers, needs more info
