### ISSUE TITLE
vscode remote-ssh can't connect server 

### ISSUE THREAD

**Issue by jianh1994** [Microsoft/vscode-remote-release#147] opened 2019-05-05 02:04 UTC
![image](https://user-images.githubusercontent.com/40174987/57187131-35459c80-6f1d-11e9-87f9-76cf78eb948a.png)

**Comment by RMacfarlane** [comment] 2019-05-05 15:11
Duplicate of https://github.com/Microsoft/vscode-remote-release/issues/97. Please install `realpath` on the machine you are trying to connect to

**Closed by RMacfarlane** 2019-05-05 15:11 UTC
