### ISSUE TITLE
Port forwarding:  Port forward section initial empty

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#2238] opened 2020-01-28 19:06 UTC
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode-remote-release/issues/2195.

1) close the Remote Explorer and reload the window
2) run `npx http-server -p 9876` on the ssh box
3) open the Remote Explorer

-> The `Forwarded Ports` section only shows `Forward a Port...` placeholder.
**Note**: This does not always happens. So, this is a timing issue.

Extension version: 2020.1.38400
VS Code version: Code - Insiders 1.42.0-insider (c4b6a6b537de49a734d0eedea06152ea37dfdb6a, 2020-01-28T05:34:51.242Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure

**Comment by alexr00** [comment] 2020-01-29 09:21
duplicate of https://github.com/microsoft/vscode/issues/89428

**Closed** 2020-01-29 09:21 UTC
Labels: *duplicate
