### ISSUE TITLE
sligtly faulty target path for .vs-code-server on host, stalls connection indefinitly

### ISSUE THREAD

**Issue by Apsylem** [microsoft/vscode-remote-release#5472] opened 2021-08-18 08:46 UTC
The issue appeared after the last update of vs-code

The folder name on the server is : 

.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8
but vs-code tries to scp something to :
                                                                                         * position of difference
.vscode-server/bin/379476f0e13988d90fab105c5c19e7abcc8b1dea8

this stalls the connection attempt forever

related issues : #2792,  #3139

i could not fix this by uninstalling the VS-Code Server, or killing host connection, or removing of the folder. The Manual copy suggested in #2792 seems to be the only way. Is there a better way ? 

- VSCode Version:1.59.0
- Local OS Version: Microsoft Windows 11 Pro Version 10.0.22000 Build 22000
- Remote OS Version: Ubuntu 18.04.5 LTS
- Remote Extension/Connection Type: SSH
- Logs:
```
[10:23:09.903] Log Level: 2
[10:23:09.911] remote-ssh@0.65.7
[10:23:09.911] win32 x64
[10:23:09.913] SSH Resolver called for "ssh-remote+172.30.5.140", attempt 1
[10:23:09.913] "remote.SSH.useLocalServer": false
[10:23:09.914] "remote.SSH.showLoginTerminal": false
[10:23:09.915] "remote.SSH.remotePlatform": {"172.30.5.153":"linux","172.30.5.140":"linux","172.30.5.141":"linux"}
[10:23:09.915] "remote.SSH.path": undefined
[10:23:09.915] "remote.SSH.configFile": undefined
[10:23:09.916] "remote.SSH.useFlock": true
[10:23:09.916] "remote.SSH.lockfilesInTmp": false
[10:23:09.916] "remote.SSH.localServerDownload": auto
[10:23:09.917] "remote.SSH.remoteServerListenOnSocket": false
[10:23:09.917] "remote.SSH.showLoginTerminal": false
[10:23:09.917] "remote.SSH.defaultExtensions": []
[10:23:09.918] "remote.SSH.loglevel": 2
[10:23:09.918] SSH Resolver called for host: 172.30.5.140
[10:23:09.918] Setting up SSH remote "172.30.5.140"
[10:23:09.947] Using commit id "379476f0e13988d90fab105c5c19e7abc8b1dea8" and quality "stable" for server
[10:23:09.954] Install and start server if needed
[10:23:09.999] Checking ssh with "ssh -V"
[10:23:10.047] > OpenSSH_for_Windows_8.1p1, 
[10:23:10.047] > LibreSSL 3.0.2
[10:23:10.052] Running script with connection command: ssh -T -D 53354 "172.30.5.140" bash
[10:23:10.054] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:23:10.332] > ]0;C:\WINDOWS\System32\cmd.exe
[10:23:10.332] Got some output, clearing connection timeout
[10:23:10.647] > alexander@172.30.5.140's password: 
[10:23:10.648] Showing password prompt
[10:24:14.593] Got password response
[10:24:14.594] "install" wrote data to terminal: "*********"
[10:24:14.616] > 
[10:24:15.103] > 1dc3bcce090c: running
[10:24:15.154] > Acquiring lock on /home/alexander/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/vscode-remote-lock.alexander.379476f0e13988d90fab105c5c19e7abc8b1dea8
[10:24:15.185] > Installing to /home/alexander/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8...
> 1dc3bcce090c%%1%%
> Downloading with wget
[10:24:15.201] > wget download failed
> wget: Host-Adresse »update.code.visualstudio.com« kann nicht aufgelöst werden
> printenv:
>     SSH_CONNECTION=192.168.117.9 53356 172.30.5.140 22
>     LANG=de_DE.UTF-8
>     XDG_SESSION_ID=1360
>     USER=alexander
>     PWD=/home/alexander/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8
>     HOME=/home/alexander
>     SSH_CLIENT=192.168.117.9 53356 22
>     MAIL=/var/mail/alexander
>     SHELL=/bin/bash
>     SHLVL=2
>     VSCODE_AGENT_FOLDER=/home/alexander/.vscode-server
>     LOGNAME=alexander
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1006/bus
>     XDG_RUNTIME_DIR=/run/user/1006
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     _=/usr/bin/printenv
>     OLDPWD=/home/alexander
> Trigger local server download
> 1dc3bcce090c:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/alexander/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc
> c8b1dea8==
[10:24:15.205] > 1dc3bcce090c:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/alexander/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc
> c8b1dea8/vscode-scp-done.flag and vscode-server.tar.gz to exist
[10:24:15.205] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/alexander/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abcc8b1dea8"}
[10:24:15.206] Downloading VS Code server locally...
[10:24:15.215] > 
> 
[10:24:21.225] Downloaded VS Code server to c:\Users\Alexa\AppData\Local\Temp\42c090f8-f04a-4948-ac4a-e6e8afaf83d5
[10:24:21.228] Renamed VS Code server to c:\Users\Alexa\AppData\Local\Temp\vscode_server_1629275061225\vscode-server.tar.gz
[10:24:21.235] Checking ssh with "ssh -V"
[10:24:21.326] > O
[10:24:21.326] > penSSH_for_Windows_8.1p1, LibreSSL 3.0.2
[10:24:21.332] Testing scp with "scp"
[10:24:21.405] scp exited with code: 1
[10:24:21.405] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[10:24:21.406] Copying file to remote with scp "vscode-server.tar.gz" "vscode-scp-done.flag" "172.30.5.140":"/home/alexander/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abcc8b1dea8"
[10:24:21.407] Using cwd: file:///c%3A/Users/Alexa/AppData/Local/Temp/vscode_server_1629275061225
[10:24:21.407] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:24:21.711] > ]0;C:\WINDOWS\System32\cmd.exe
[10:24:22.071] > alexander@172.30.5.140's password: 
[10:24:22.071] Showing password prompt
[10:24:33.434] Got password response
[10:24:33.435] "Copy server to host" wrote data to terminal: "*********"
[10:24:33.462] > 
[10:24:33.895] > scp: /home/alexander/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abcc8b1dea8: No such file or directory
[10:24:35.189] "Copy server to host" terminal command done
[10:28:15.354] > 
```

Steps to Reproduce:

1. I could not reproduce this error

**Comment by bamurtaugh** [comment] 2021-08-24 22:53
I think this is a dupe of https://github.com/microsoft/vscode-remote-release/issues/5303. If it seems like something different, please just let me know, and happy to discuss further.

**Closed by bamurtaugh** 2021-08-24 22:53 UTC
Labels: ssh
