### ISSUE TITLE
Remote-Containers suddenly stopped working with an error about bogus screen size

### ISSUE THREAD

**Issue by razermackham** [microsoft/vscode-remote-release#3522] opened 2020-08-15 02:35 UTC
Command 'Remote-Containers: Open Folder in Container...' resulted in an error (Shell server terminated (code: 1, signal: null)

    your 131072x1 screen size is bogus. expect trouble
    your 131072x1 screen size is bogus. expect trouble

VSCode Version: 1.48.0
OS: Windows_NT x64 10.0.19041
Container: https://github.com/microsoft/vscode-remote-try-rust.git
Remote Extension/Connection Type: WSL: Ubuntu-20.04

I don't know what might have changed my "screen size" nor how to fix.
I found this issue, but it's supposedly fixed:
https://github.com/Microsoft/vscode/issues/35798

Repro steps:
1. From Ubuntu bash: `cd ~/vscode-remote-try-rust; code .`
(This used to bring up a prompt to open in container, but now it doesn't)
2. Remote-Containers: Open Folder in Container...
(Error pops up)

**Comment by chrmarti** [comment] 2020-08-18 10:16
@razermackham Could you try Remote-Containers 0.135.0 (you will need VS Code Insiders to get that version: https://code.visualstudio.com/insiders/) and let me know if you still see this issue?

**Comment by chrmarti** [comment] 2020-08-19 07:38
Duplicate of #3525

**Closed by chrmarti** 2020-08-19 07:38 UTC
Labels: bug, containers
