### ISSUE TITLE
multiple developers on the same commit id of vscode-server cannot connect at the same time

### ISSUE THREAD

**Issue by yfengBTI** [microsoft/vscode-remote-release#4940] opened 2021-04-23 20:35 UTC
- VSCode Version: tested on 1.52.1, 1.55.2
- Local OS Version: Windows 10 21H1 19043.928
- Remote OS Version: Windows Server 2016 1607 14393.4169
- Remote Extension/Connection Type: SSH
- Logs:
```log
[16:23:46.790] "install" terminal received data: "
Acquiring lock on C:\Users\me\.vscode-server\bin\ea3859d4ba2f3e577a159bc91e3074c5d85c0523\vscode-remote-lock.ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Looking for existing server in C:\Users\me\.vscode-server\bin\ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Found installed server
Server with ea3859d4ba2f3e577a159bc91e3074c5d85c0523 is already running."
[16:23:48.035] "install" terminal received data: "Server did not start successfully. Full server log at C:\Users\me\.vscode-server\.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log >>>
"
[16:23:48.042] "install" terminal received data: ""
[16:23:48.151] "install" terminal received data: "cat : Cannot find path 
'C:\Users\me\.vscode-server\.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log' because it does not exist.
```

Steps to Reproduce:

1. Colleague connects to host
2. I start my connection
3. If my vscode-server commit id is the same as my colleagues, my remote vscode-server would not start. 

Note that the extension would try to cat the log in my folder, but it's not there because the running server is on my colleague's home directory.

Workaround:

If we use different version of the vscode-remote extension, the problem goes away.
Our hack workaround is to replace `$commitId = '${r}'` with `$commitId = '${r}-${require("os").userInfo().username}'` in `extension.js`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment] 2021-04-26 23:31
I think this sounds like https://github.com/microsoft/vscode-remote-release/issues/4556?

**Comment by yfengBTI** [comment] 2021-04-26 23:51
> I think this sounds like #4556?

It does look similar.
In my issue above, I have both the `Server ... is already running` and followed by `Cannot find path ... because it does not exist` for the log file.

In #4556, only the 2nd log entry is found.
Maybe the OP there can try the workaround and see if it works?

**Comment by bamurtaugh** [comment] 2021-04-29 18:26
The OP in https://github.com/microsoft/vscode-remote-release/issues/4556 verified the workaround solves the issue (although not ideal long term for their use case), so I think we can close this issue as a dupe of that one since they have the same root cause. We can track over in https://github.com/microsoft/vscode-remote-release/issues/4556.

**Closed by bamurtaugh** 2021-04-29 18:26 UTC
Labels: ssh
