### ISSUE TITLE
all those spawned "docker exec ..." processes should run from a shell

### ISSUE THREAD

**Issue by scalpel4k** [microsoft/vscode-remote-release#2826] opened 2020-04-24 18:03 UTC
We have to do a few preparations in our docker containers before we can give access to the developer. This works well for docker run, because we can overwrite the entrypoint.
However, soon after devcontainer starts the container, a couple of docker exec processes are being spawned that will basically run a command in an "unprepared" container context (our /etc/profile and/or /etc/bash.bashrc are completely ignored and it doesn't see any ENV settings). I think these are mostly node processes.
This could easily be avoided if docker exec would run its command through a shell (like when using "postCreateCommand" - and no issue #2201 is not the solution for this issue).

thx Michi

**Comment by PavelSosin-320** [comment] 2020-04-24 19:02
This is a known problem in standalone docker containers: OS boot sequence doesn't exist. Kubernetes solves it via lifecycle hooks of pods : [Lifecycle hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) 
There are several solutions that exist like tiny [tiny](https://github.com/krallin/tini). Up to MS to adopt one.

**Comment by Chuxel** [comment] 2020-04-24 19:31
We are also looking at https://github.com/microsoft/vscode-remote-release/issues/2772 as a more generic way to run a script on startup.  Using an ENTRYPOINT is the usual trick - this is what the updated Docker-in-Docker definition does: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-in-docker

**Comment by Chuxel** [comment] 2020-04-24 19:35
@chrmarti Should we consider this a dupe of #2772?

**Comment by scalpel4k** [comment] 2020-04-24 19:50
@Chuxel if I understand #2772 correctly, this is what we're already doing with "overrideCommand": false. This works for starting the container, but as I said, the problem lies in the subsequent docker exec calls that the plugin is starting after the container was started.

for instance:

Start: Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=44795d3f-c9fb-4388-a102-19d73a37b0f01587757615921 bac4fe3b4e8158cdf91fb1fe3eeb8e146f74d4813a1cb35418edf6a6075c8697 /root/.vscode-server-insiders/bin/2225d77536d12fea2eda04930f431a5eb0930bba/node -e

If it would call something like "docker exec /bin/bash -c node -e" instead of "docker exec node -e" I would be quite happy.

**Comment by PavelSosin-320** [comment] 2020-04-25 04:53
Actually, Docker documentation says:
_Specify an init process
You can use the --init flag to indicate that an init process should be used as the PID 1 in the container. Specifying an init process ensures the usual responsibilities of an init system, such as reaping zombie processes, are performed inside the created container.

The default init process used is the first docker-init executable found in the system path of the Docker daemon process. This docker-init binary, included in the default installation, is backed by tini._
I.e. everybody should trust only in their own root process defined by --init docker run option.
Docker is not supposed to run OS or Shell - it is an abuse of Docker to run several EXECs in parallel. As a part of the service component architecture, Docker container must start service at the end of the initialization sequence and this service will serve client requests. When somebody needs more than one service than several containers must be started and share the same workspace via Volume mapping. Docker EXEC can never be used safely for communication with the running containers because of it's not obligatory to provide locking mechanism as an OS extension for every base image.

**Comment by scalpel4k** [comment] 2020-04-25 06:29
@PavelSosin-320 I don't know if we're talking the same language? It's not me who is running these `docker exec` commands that I've mentioned, it's actually what remote container is doing!!! I can't do anything about that, it's how the remote container extension works.

And as you said, `--init` is about PID 1 (which in my case is catatonit and not tini) and that doesn't help when my container gets "hijacked" by `docker exec` calls.

BTW thanks for the hint with the lifecycle hooks in Kubernetes, I might need that for other use cases ...

**Comment by chrmarti** [comment] 2020-04-27 10:01
@scalpel4k Why and how do you need to customize how the `docker exec`s are run?

**Comment by scalpel4k** [comment] 2020-04-28 06:58
> @scalpel4k Why and how do you need to customize how the `docker exec`s are run?

We need to run into `/etc/profile` and/or `/etc/bash.bashrc` to intialize the container properly, e.g. setting corporate proxies if the container is run in our network and other things.
I think it should be no problem to run `docker exec /bin/bash -c node -e` or whatever.

**Comment by makeable** [comment] 2020-05-04 12:46
Also banging against this issue. The environment of the user isnt being initialised - and as such vscode-server is being launched with wrong PATH (among others), meaning that you need to manually configure env vars in devcontainer.json that are already present in the user profile in the container.

I'm working around - but it seems like it should be ompletely unnecessary to do this.

**Comment by makeable** [comment] 2020-05-05 03:27
I second something like this. Its frustrating not being able to source env vars in the IDE (for launch config, etc) that exist in the container users profile - it has bitten me on many occasions.

**Comment by koonpeng** [comment] 2020-08-20 10:36
Upvoting this as well. For my use case, I'm trying to do ros development in the container, ros commonly requires you to source a script to set up the environment variables, this works for `docker run` because the container uses an entrypoint to source the script but vscode uses `docker exec` to start the remote process instead. Having a way to set up the env for the vscode process would be really helpful.

**Comment by chrmarti** [comment] 2020-08-20 12:38
@koonpeng You could try using `"userEnvProbe"` in the devcontainer.json to source the default shell's startup script, the environment variables of that will then be passed on to the VS Code Server process. (This is currently limited the default shell's startup scripts.)

**Comment by koonpeng** [comment] 2020-08-21 01:04
Thanks! I added `"userEnvProbe": "loginInteractiveShell"` and source the script in `/etc/profile` and vscode picks up all the env variables. All vscode subprocesses like the terminal, task runner etc all inherit the envs, maybe this can work for @scalpel4k's use case as well?

**Comment by bamurtaugh** [comment] 2020-10-23 21:17
Hey @scalpel4k, do you think the ideas mentioned above would be able to help with your use case?

**Closed** 2020-10-31 12:25 UTC
Labels: containers, needs-more-info
