### ISSUE TITLE
After 1.58 version, "shutdownAction": "stopCompose" not working in devcontainer

### ISSUE THREAD

**Issue by surrynet** [microsoft/vscode-remote-release#5321] opened 2021-07-09 15:34 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58
- OS Version: ubuntu 20.04 kernel-5.4.0-77-generic

**Comment by chrmarti** [comment] 2021-07-16 14:17
Fixed in 0.188.0 (currently requires VS Code Insiders). Could someone seeing this verify the fix in that version? I'm considering to also fix it for VS Code 1.58.

**Comment by clementguillot** [comment] 2021-07-16 18:48
@chrmarti I can confirm that the issue is perfectly fixed using VS Code 1.59.0-insider w/ Remote - Container v0.188.0 Preview.

**Comment by chrmarti** [comment] 2021-07-20 08:57
Released for VS Code 1.58 with Remote-Containers 0.187.1.

**Closed** 2021-07-20 09:00 UTC
Labels: bug, containers

**Comment by jefftriplett** [comment] 2021-07-21 01:48
I can confirm that this now works when `runServices` is empty. 

Otherwise, only the services in `runServices` are stopped once VS Code is exited. I tested this both on macOS today and had a remote developer try it on Windows and we both experienced the same issue.

**Comment by alexr00** [comment] 2021-08-04 16:31
Just spent > 30 minutes trying to figure out how to verify this. No luck.

**Comment by jefftriplett** [comment] 2021-08-05 00:14
@alexr00 I can confirm that works >99% of the time. 

I occasionally have a postgres database that stays up, but I'm not convinced that's a VS Bug because running `docker compose down` doesn't always stop it either.

**Comment by alexr00** [comment] 2021-08-05 07:29
@jefftriplett thanks for testing it!
