### ISSUE TITLE
put button delete in item of ssh target

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode-remote-release#5092] opened 2021-05-23 16:56 UTC
Issue Type: <b>Feature Request</b>

... to delete once ssh target.
![simplescreenrecorder-2021-05-23_13 02 43](https://user-images.githubusercontent.com/38570195/119270029-b0438380-bbc8-11eb-945d-913170d21ff2.gif)
 

Extension version: 2021.5.29700
VS Code version: Code - Insiders 1.57.0-insider (4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5, 2021-05-21T05:13:19.775Z)
OS version: Linux x64 4.19.0-16-amd64

**Comment by bamurtaugh** [comment] 2021-05-26 17:06
Thanks for the issue @AlexandroGonSan!

I believe this is a /duplicate of https://github.com/microsoft/vscode-remote-release/issues/3438.

**Closed** 2021-05-26 17:06 UTC
Labels: *duplicate, ssh
