### ISSUE TITLE
VSCode Remote SSH disconnects if login shell is Fish

### ISSUE THREAD

**Issue by iblazhko** [microsoft/vscode-remote-release#4146] opened 2020-12-07 09:48 UTC
- VS Code Version: 1.53.0-exploration
- Local OS Version: macOS BigSur 11.0.1 (Apple M1)
- Remote OS Version: Debian 10 (MX Linux 19.3 x86_64)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

0. Server: Install [Fish Shell](https://fishshell.com) `sudo apt update && sudo apt install fish`
1. Server: Change login shell to Fish via `chsh -s /usr/bin/fish username`
2. Client (VS Code): `Remote-SSH: Connect to host`

At first, connection is established successfully:

```
[07:00:16.341] > Linux dev-box 5.8.0-3-amd64 #1 SMP Debian 5.8.14-1~mx19+2 (2020-10-25) x86_64
> No mail.
```

(2nd line is a Fish prompt)

But after a few seconds there is an error 

```
[07:00:32.554] Terminating local server
[07:00:32.566] Resolver error: Error: Connecting with SSH timed out
[07:00:32.568] Local server exit: 15
```

Full client log:

```
[07:00:15.368] Log Level: 1
[07:00:15.369] remote-ssh@0.58.0
[07:00:15.369] darwin arm64
[07:00:15.370] SSH Resolver called for "ssh-remote+dev-box", attempt 1
[07:00:15.370] "remote.SSH.useLocalServer": true
[07:00:15.370] "remote.SSH.sshPath": undefined
[07:00:15.370] "remote.SSH.sshConfigurationFile": undefined
[07:00:15.370] "remote.SSH.useFlock": true
[07:00:15.370] "remote.SSH.lockfilesInTmp": false
[07:00:15.370] "remote.SSH.localServerDownload": auto
[07:00:15.370] "remote.SSH.remoteServerListenOnSocket": false
[07:00:15.370] "remote.SSH.showLoginTerminal": false
[07:00:15.370] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[07:00:15.371] SSH Resolver called for host: dev-box
[07:00:15.371] Setting up SSH remote "dev-box"
[07:00:15.372] Acquiring local install lock: /var/folders/xw/3d8ppqw12wd559tmlt21zddc0000gn/T/vscode-remote-ssh-dev-box-install.lock
[07:00:15.427] Looking for existing server data file at /Users/dev-user/Library/Application Support/Code - Exploration/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-dev-box-32570a22cce64af05302826be2175050663a1c93-0.58.0/data.json
[07:00:15.427] Using commit id "32570a22cce64af05302826be2175050663a1c93" and quality "exploration" for server
[07:00:15.428] Install and start server if needed
[07:00:15.430] Checking ssh with "ssh -V"
[07:00:15.487] > OpenSSH_8.1p1, LibreSSL 2.7.3

[07:00:15.496] askpass server listening on /var/folders/xw/3d8ppqw12wd559tmlt21zddc0000gn/T/vscode-ssh-askpass-51b5458f2a2aca043694d45152f82a9b55b5bbe1.sock
[07:00:15.496] Spawning local server with {"ipcHandlePath":"/var/folders/xw/3d8ppqw12wd559tmlt21zddc0000gn/T/vscode-ssh-askpass-9a4d07aef161469eb261d6b7ffd1462039ddbb7e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","55280","-o","ConnectTimeout=15","dev-box"],"dataFilePath":"/Users/dev-user/Library/Application Support/Code - Exploration/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-dev-box-32570a22cce64af05302826be2175050663a1c93-0.58.0/data.json"}
[07:00:15.497] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/dev-user/.vscode-exploration/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Exploration.app/Contents/Frameworks/Code - Exploration Helper (Renderer).app/Contents/MacOS/Code - Exploration Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/dev-user/.vscode-exploration/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/xw/3d8ppqw12wd559tmlt21zddc0000gn/T/vscode-ssh-askpass-51b5458f2a2aca043694d45152f82a9b55b5bbe1.sock"}
[07:00:15.548] Spawned 3848
[07:00:15.640] > local-server> Spawned ssh: 3849
[07:00:15.642] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[07:00:15.642] stderr> debug1: Reading configuration data /Users/dev-user/.ssh/config
[07:00:15.642] stderr> debug1: /Users/dev-user/.ssh/config line 1: Applying options for *
[07:00:15.642] stderr> debug1: /Users/dev-user/.ssh/config line 6: Applying options for dev-box
[07:00:15.642] stderr> debug1: Reading configuration data /etc/ssh/ssh_config
[07:00:15.642] stderr> debug1: /etc/ssh/ssh_config line 47: Applying options for *
[07:00:15.647] stderr> debug1: Connecting to dev-box [192.168.2.101] port 22.
[07:00:15.663] stderr> debug1: fd 5 clearing O_NONBLOCK
[07:00:15.663] stderr> debug1: Connection established.
[07:00:15.664] stderr> debug1: identity file /Users/dev-user/.ssh/IB-MacMini type 0
[07:00:15.664] stderr> debug1: identity file /Users/dev-user/.ssh/IB-MacMini-cert type -1
[07:00:15.664] stderr> debug1: Local version string SSH-2.0-OpenSSH_8.1
[07:00:15.664] stderr> debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debian-10+deb10u2
[07:00:15.664] stderr> debug1: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
[07:00:15.664] stderr> debug1: Authenticating to dev-box:22 as 'dev-user'
[07:00:15.666] stderr> debug1: SSH2_MSG_KEXINIT sent
[07:00:15.666] stderr> debug1: SSH2_MSG_KEXINIT received
[07:00:15.666] stderr> debug1: kex: algorithm: curve25519-sha256
[07:00:15.666] stderr> debug1: kex: host key algorithm: ecdsa-sha2-nistp256
[07:00:15.666] stderr> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[07:00:15.667] stderr> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[07:00:15.667] stderr> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
[07:00:15.677] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:pPYvQ7vlVnqfnIksGs1t2V2oP6dqwr3hoDWC16vlmr0
[07:00:15.682] stderr> debug1: Host 'dev-box' is known and matches the ECDSA host key.
[07:00:15.682] stderr> debug1: Found key in /Users/dev-user/.ssh/known_hosts:6
[07:00:15.686] stderr> debug1: rekey out after 134217728 blocks
[07:00:15.687] stderr> debug1: SSH2_MSG_NEWKEYS sent
[07:00:15.687] stderr> debug1: expecting SSH2_MSG_NEWKEYS
[07:00:15.687] stderr> debug1: SSH2_MSG_NEWKEYS received
[07:00:15.687] stderr> debug1: rekey in after 134217728 blocks
[07:00:15.687] stderr> debug1: Will attempt key: /Users/dev-user/.ssh/IB-MacMini RSA SHA256:1EjzUxmkYl8xLa5zYPHaLdOeVBzA66FfB8h5tSVeV9M explicit agent
[07:00:15.687] stderr> debug1: SSH2_MSG_EXT_INFO received
[07:00:15.687] stderr> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
[07:00:15.688] stderr> debug1: SSH2_MSG_SERVICE_ACCEPT received
[07:00:15.697] stderr> debug1: Authentications that can continue: publickey,password
[07:00:15.697] stderr> debug1: Next authentication method: publickey
[07:00:15.697] stderr> debug1: Offering public key: /Users/dev-user/.ssh/IB-MacMini RSA SHA256:1EjzUxmkYl8xLa5zYPHaLdOeVBzA66FfB8h5tSVeV9M explicit agent
[07:00:15.698] stderr> debug1: Server accepts key: /Users/dev-user/.ssh/IB-MacMini RSA SHA256:1EjzUxmkYl8xLa5zYPHaLdOeVBzA66FfB8h5tSVeV9M explicit agent
[07:00:16.290] stderr> debug1: Authentication succeeded (publickey).
[07:00:16.290] stderr> Authenticated to dev-box ([192.168.2.101]:22).
[07:00:16.290] stderr> debug1: Local connections to LOCALHOST:55280 forwarded to remote address socks:0
[07:00:16.290] stderr> debug1: Local forwarding listening on ::1 port 55280.
[07:00:16.290] stderr> debug1: channel 0: new [port listener]
[07:00:16.290] stderr> debug1: Local forwarding listening on 127.0.0.1 port 55280.
[07:00:16.290] stderr> debug1: channel 1: new [port listener]
[07:00:16.290] stderr> debug1: channel 2: new [client-session]
[07:00:16.290] stderr> debug1: Requesting no-more-sessions@openssh.com
[07:00:16.290] stderr> debug1: Entering interactive session.
[07:00:16.290] stderr> debug1: pledge: network
[07:00:16.340] stderr> debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
[07:00:16.340] stderr> debug1: Remote: /home/dev-user/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
[07:00:16.340] stderr> debug1: Remote: /home/dev-user/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
[07:00:16.340] stderr> debug1: Sending environment.
[07:00:16.340] stderr> debug1: Sending env LC_CTYPE = en_US.UTF-8
[07:00:16.341] > Linux dev-box 5.8.0-3-amd64 #1 SMP Debian 5.8.14-1~mx19+2 (2020-10-25) x86_64
> No mail.
[07:00:32.554] Terminating local server
[07:00:32.566] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/dev-user/.vscode-exploration/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:82387)
	at Timeout._onTimeout (/Users/dev-user/.vscode-exploration/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:276370)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
[07:00:32.568] Local server exit: 15
[07:00:32.570] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"Timeout","exitCodeLabel":"","osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1"},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":17187,"timing.preSshTime":127}}
[07:00:32.571] ------
```

Server log (from `/var/log/auth.log`):

```
Dec  7 07:14:27 dev-box sudo: dev-user : TTY=pts/2 ; PWD=/home/dev-user ; USER=root ; COMMAND=/usr/bin/tail -1000 /var/log/auth.log
Dec  7 07:14:27 dev-box sudo: pam_unix(sudo:session): session opened for user root by dev-user(uid=0)
Dec  7 07:14:31 dev-box sudo: pam_unix(sudo:session): session closed for user root
Dec  7 07:15:11 dev-box sshd[7030]: Accepted publickey for dev-user from 192.168.2.129 port 55529 ssh2: RSA SHA256:1EjzUxmkYl8xLa5zYPHaLdOeVBzA66FfB8h5tSVeV9M
Dec  7 07:15:11 dev-box sshd[7030]: pam_unix(sshd:session): session opened for user dev-user by (uid=0)
Dec  7 07:15:14 dev-box sudo: dev-user : TTY=unknown ; PWD=/home/dev-user ; USER=root ; COMMAND=/usr/bin/lsof /var/lib/dpkg/lock /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/cache/apt/archives/lock
Dec  7 07:15:14 dev-box sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec  7 07:15:14 dev-box sudo: pam_unix(sudo:session): session closed for user root
Dec  7 07:15:28 dev-box sshd[7044]: Received disconnect from 192.168.2.129 port 55529:11: disconnected by user
Dec  7 07:15:28 dev-box sshd[7044]: Disconnected from user dev-user 192.168.2.129 port 55529
Dec  7 07:15:28 dev-box sshd[7030]: pam_unix(sshd:session): session closed for user dev-user
```

I can `ssh` into that server from terminal just fine, here is the environment from `ssh` session if that helps:

```
> set

CMD_DURATION 2250
COLUMNS 175
EMC_CMD emc
EMC_EDITOR nano
FISH_VERSION 3.0.2
HOME /home/dev-user
IFS \n\ \t
LANG en_GB.UTF-8
LINES 50
LOGNAME dev-user
LS_COLORS 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=…
MAIL /var/mail/dev-user
PATH '/usr/local/bin'  '/usr/bin'  '/bin'  '/usr/games'
PWD /home/dev-user
SHELL /usr/bin/fish
SHLVL 1
SPACEFISH_PROMPT_ORDER 'time'  'user'  'dir'  'host'  'git'  'docker'  'rust'  'has…
SSH_CLIENT '192.168.2.129 55124 22'
SSH_CONNECTION '192.168.2.129 55124 192.168.2.101 22'
SSH_TTY /dev/pts/2
TERM xterm-256color
USER dev-user
VIRTUAL_ENV_DISABLE_PROMPT 1
XDG_RUNTIME_DIR /run/user/1000
XDG_SESSION_CLASS user
XDG_SESSION_ID 165
XDG_SESSION_TYPE tty
...
```

Same version of VSCode Remote SSH works fine with the same server if I change login shell from `fish` to `bash` or `zsh`.

**Comment by bamurtaugh** [comment] 2020-12-10 01:20
Seems like this might be related / a duplicate of https://github.com/microsoft/vscode-remote-release/issues/2509?

**Comment by iblazhko** [comment] 2020-12-10 08:48
Could indeed be the same problem as #2509, and `"remote.SSH.useLocalServer": false` workaround mentioned there works for me.

So would be happy to close this one.

**Comment by bamurtaugh** [comment] 2020-12-10 17:31
Sounds good, thanks for the additional info @iblazhko!

**Closed by bamurtaugh** 2020-12-10 17:31 UTC
Labels: ssh
