### ISSUE TITLE
Remote SSH stops working when JS file is opened.

### ISSUE THREAD

**Issue by SishirW** [microsoft/vscode-remote-release#5558] opened 2021-09-08 10:17 UTC
Whenever I try to open JS file from my host using Remote SSH, "reconnection to host" starts to appear.  I am not able to connect to SSH through any other means when reconnecting appears. This problem lasts for about an hour. And if I have a website hosted in the server, the server is down and we can't access the server.
![image](https://user-images.githubusercontent.com/35773743/132491582-b571b08e-919f-4fd6-be24-00bac5aab229.png)
```
[16:01:40.176] Log Level: 2
[16:01:40.179] remote-ssh@0.65.7
[16:01:40.180] win32 x64
[16:01:40.208] SSH Resolver called for "ssh-remote+20.198.2.169", attempt 1
[16:01:40.209] "remote.SSH.useLocalServer": false
[16:01:40.209] "remote.SSH.showLoginTerminal": false
[16:01:40.210] "remote.SSH.remotePlatform": {"20.198.2.169":"linux"}
[16:01:40.210] "remote.SSH.path": undefined
[16:01:40.210] "remote.SSH.configFile": undefined
[16:01:40.210] "remote.SSH.useFlock": true
[16:01:40.211] "remote.SSH.lockfilesInTmp": false
[16:01:40.211] "remote.SSH.localServerDownload": auto
[16:01:40.211] "remote.SSH.remoteServerListenOnSocket": false
[16:01:40.211] "remote.SSH.showLoginTerminal": false
[16:01:40.211] "remote.SSH.defaultExtensions": []
[16:01:40.212] "remote.SSH.loglevel": 2
[16:01:40.212] SSH Resolver called for host: 20.198.2.169
[16:01:40.212] Setting up SSH remote "20.198.2.169"
[16:01:40.243] Using commit id "e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff" and quality "stable" for server
[16:01:40.249] Install and start server if needed
[16:01:40.256] Checking ssh with "ssh -V"
[16:01:40.321] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[16:01:40.328] Running script with connection command: ssh -T -D 64134 "20.198.2.169" bash
[16:01:40.331] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:01:40.704] > 
[16:01:40.705] Got some output, clearing connection timeout

```

**Comment by lustremedia** [comment] 2021-09-08 13:17
Also possibly duplicate of: https://github.com/microsoft/vscode-remote-release/issues/5555

**Comment by bamurtaugh** [comment] 2021-09-28 18:03
Thanks for reporting @SishirW. As @lustremedia points out, there was another issue that could've been surfacing as this. Are you still experiencing this? If so, could you please share your version of VS Code and Remote-SSH, and the type of local and remote OS?

**Comment by tanhakabir** [comment] 2021-10-18 17:03
Closing this issue for now due to inactivity! @lustremedia please let us know if the linked issue doesn't provide a fix for you!

**Closed by tanhakabir** 2021-10-18 17:03 UTC
Labels: ssh, needs more info
