### ISSUE TITLE
unstable connection, node process cost a lot when running du command

### ISSUE THREAD

**Issue by wohenbushuang** [microsoft/vscode-remote-release#2797] opened 2020-04-20 04:10 UTC
- VSCode Version: 1.44.2
- Local OS Version: Win10

> 版本: 1.44.2 (user setup)
提交: ff915844119ce9485abfe8aa9076ec76b5300ddd
日期: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

- Remote OS Version: Ubuntu18
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to SSH host, for me as root
1. Run `du` command to print the size of a folder with many files and large disk usage. Maybe you can try with `du /`
1. A `node` process will rise a high CPU usage in `top`, which causing the connection unstable. It will ask you to re-connect and enter the password again and again and again, even after `du` command has finished. Besides, when there are other processes running on the remote host with a high memory usage, it might cause a `Out Of Memory`, the host become unreachable, and make Linux to kill the running process. The connection will return stable only after reload the VS Code window a long time later.
1. I've tried to kill the `node` process, and it will lead to the connection failed immediately, then ask to reload the VS Code window.
1. I've tried with Putty for above operation, and everything was fine, so the problem should be in VS Code not my host.
1. For reference, my host is 2Core 4G RAM on cloud service, without other apps working during the test.

Does this issue occur when you try this locally?: No, I tried with Putty and everything was fine
Does this issue occur when you try this locally and all extensions are disabled?: Don't know, I believe it's irrelevant.

**Comment by thomasthorsen** [comment] 2020-04-21 07:47
For what it is worth I am having similar issues on a similar setup (Win10 Pro, Ubuntu 18.04 VM on same machine (using Hyper-V virtual machines), connected with Remote-SSH). Sometimes there is a node process going all-out on the target (100% cpu), and the only remedy seems to be to kill everything (e.g. restart the remote) and restart VSCode and connect over. This happens quite rarely though (every few days).

However, I think there are two aspects of this. One is the rampant node process, but even when that doesn't happen, if I put the remote under load, typically due to building code in multiple threads, the connection to the remote in vscode becomes unstable according to vscode and the UI is locked and pending a reconnect which interrupts workflow drastically. When this happens I always monitor the remote with a putty connection where I run top to see what is going on, and this connection has no problems and update top ui just fine, showing the build processes running fine. Often vscode can successfully reconnect fine, but the interruption damage is done.

Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment] 2020-11-06 00:43
Closing as dupe of https://github.com/microsoft/vscode-remote-release/issues/1257#issuecomment-650054228

**Closed by roblourens** 2020-11-06 00:43 UTC
Labels: ssh
