### ISSUE TITLE
Extension gets stuck while opening a docker-composer based container

### ISSUE THREAD

**Issue by andreagrandi** [microsoft/vscode-remote-release#221] opened 2019-05-04 12:47 UTC
Hi everyone,

I'm using Docker on OSX, the latest insiders build of VSCode and I've installed the extension to connect to containers.

Our application already has a Docker configuration and in particular a `docker-compose.yml` file.

When I open the project I choose:

1) Reopen folder in container
2) VSCode detects I already have a Docker configuration and aske me if I want to use the `Dockerfile`, `Dockerfile.test` or `docker-compose.yml`.
3) I choose `docker-compose.yml` and it starts running the containers but it gets stuck at this point:

<img width="1088" alt="Screenshot 2019-05-04 14 38 01" src="https://user-images.githubusercontent.com/636391/57179205-7a18f700-6e7b-11e9-8886-f54f1910e873.png">

How can I fix this?

p.s: I've tried also other methods like attaching to the existing running container, but it doesn't do what I need.

**Comment by chrmarti** [comment] 2019-05-08 06:20
@andreagrandi Is the `"service"` in the devcontainer.json set to an existing service in the docker-compose.yml? (Could be #102.)

@StephenWeatherford We are using microsoft/vscode-remote-release for most issues. You can transfer issues for Remote Development there. Thanks!

**Comment by andreagrandi** [comment] 2019-05-08 09:28
> @bpasero Should this be filed in the https://github.com/Microsoft/vscode-dev-containers/ repo's issues? It's not our extension's functionality.

it probably should! I do apologise for filling this into the wrong repository, I think I clicked on the wrong extension GitHub link, but it's definitely an issue related to the `vscode-dev-containers` repo

**Comment by andreagrandi** [comment] 2019-05-08 09:29
> @andreagrandi Is the `"service"` in the devcontainer.json set to an existing service in the docker-compose.yml? (Could be #102.)

I will need to check this later, I'm unable to do it right now but I took note, thanks for your reply in the mean time

**Comment by andreagrandi** [comment] 2019-05-08 22:04
> @andreagrandi Is the `"service"` in the devcontainer.json set to an existing service in the docker-compose.yml? (Could be #102.)
> 

I finally had time to try again. So, first of all I ran `docker-compose config --services` to get the list of services. The main service is called (I need to rename it to something else for sensitive reasons) `myservice` and it was missing from `.devcontainer.json` so 

1) I added it like this:

```
{
	"dockerComposeFile": "docker-compose.yml",
	"service": "myservice",
	"workspaceFolder": "/",
	"extensions": []
}
```
2) I saved

3) I reopened the project again with `code-insiders .` from the project folder

4) it detects it's a docker/container project and ask me to "Reopen in container", I accept

5) it hangs again :/

Is there anything else I can try?

**Comment by chrmarti** [comment] 2019-05-09 05:45
Could you retry making sure you are running 0.51.0 (or later) of the Remote Containers extension and when it hangs check what the `"com.docker.compose.project"` and `"com.docker.compose.service"` labels are? (Run `docker inspect <container id/name> | grep compose` to see the compose labels.)

**Comment by chrmarti** [comment] 2019-05-09 19:34
@andreagrandi That seems to be a different problem than the one you first reported. Could you close the window, then check that the containers stopped and then open the window again?

**Comment by chrmarti** [comment] 2019-05-10 08:11
@andreagrandi When you can reproduce the original problem: I have added tracing output in the latest version (0.52.0). You can enable it with `F1` > `Developer: Set Log Level...` > `Trace` and then reload the window (and/or rebuild the container). You should then see additional log output in the Dev Containers terminal when the container is started. Please post that here (obviously scrub private information).

**Comment by andreagrandi** [comment] 2019-05-10 16:02
> @andreagrandi That seems to be a different problem than the one you first reported. Could you close the window, then check that the containers stopped and then open the window again?

Hi, sorry it took me a bit longer to reply because I was travelling. I'm a bit lost though... why do you say it's a different issue? I genuinely don't understand what's the difference. Please keep in mind that 1) the behaviour is the same "then I choose Retry, it reloads and it gets stuck again." (so it hangs) and 2) I remember (but I'm not 100% sure) to have seen that error you see in the screenshot even the first time, but I didn't make it in time to save it.

I've a somehow positive update by the way: I asked my colleague @slafs to try on his own machine and he didn't experience the bug, for him everything worked correctly. Consider we both use a Mac, same version of Docker, he just installed VSCode and of course he tried with the same project as me.

I still haven't figured out why it works for him and not for me.

I will do the additional test you asked to me after upgrading to the 0.52 version of the extension, thanks for your patience and for your help in the mean time.

Cheers

**Comment by andreagrandi** [comment] 2019-05-10 16:10
> @andreagrandi When you can reproduce the original problem: I have added tracing output in the latest version (0.52.0). You can enable it with `F1` > `Developer: Set Log Level...` > `Trace` and then reload the window (and/or rebuild the container). You should then see additional log output in the Dev Containers terminal when the container is started. Please post that here (obviously scrub private information).

I've enabled the "Trace" log level, restarted VSCode and tried to "Reopen in container" but I don't see any additional error in the Terminal. It just hangs :/

The only difference is when you manually stop all the containers with `docker-compose stop` and then you let VSCode "Reopen in Container" and restart the containers. That's when I also get the other error you see above.

**Comment by andreagrandi** [comment] 2019-05-11 16:15
@chrmarti I have another great news! I rebuilt my Docker image locally, using the command: `docker build -t ourcompany/myseervice .` and I retried everything from scratch. This time it worked just like it worked to my colleague.

I don't know if this has to be considered a "workaround" and there is still a situation when it will fail for others or if you prefer to close the issue.

I leave this up to you to decide and I'm still available to provide more information (p.s: I still haven't able to collect those "trace" you told me because it wasn't showing any additional information).

**Comment by chrmarti** [comment] 2019-05-14 16:22
Closing this issue for now. Let us know if you see this again.

**Comment by diegoduncan21** [comment] 2019-06-26 13:31
same here, it just happend with one project, with another one it works perfectly. I've tried rebuild image like @andreagrandi without luck.

![Selection_005](https://user-images.githubusercontent.com/1647454/60183637-0c46d700-97fd-11e9-86f3-9ba72aab853f.png)

remote container info:
```
Name: Remote - Containers
Id: ms-vscode-remote.remote-containers
Description: Open any folder inside (or mounted into) a container and take advantage of Visual Studio Code's full feature set.
Version: 0.64.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
```
vscode insider information.
```
Version: 1.36.0-insider
Commit: 41691474e5fa22a279d49fc4b58af66bc11ce41b
Date: 2019-06-26T05:15:30.401Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-52-generic
```

**Comment by chrmarti** [comment] 2019-06-26 13:55
Does it work when you do `docker-compose up` yourself? What events do you get doing `F1` > `Developer: Set Log Level...` > `Trace` and then reload the window (search for `startEventSeen`?

**Comment by diegoduncan21** [comment] 2019-06-26 15:14
> Does it work when you do `docker-compose up` yourself? What events do you get doing `F1` > `Developer: Set Log Level...` > `Trace` and then reload the window (search for `startEventSeen`?

Yes it does, inclusive when it stuck.

Im using alpine image, buy with another project too, and it works.

the logs here:

```
Setting up container for folder: /home/d/ws/crm-service
Run: docker-compose -f /home/d/ws/crm-service/docker-compose.yml config --services
crm_service
Run: docker-compose --project-name crm-service -f /home/d/ws/crm-service/docker-compose.yml up -d --build
Building crm_service
Step 1/11 : FROM python:3.6-alpine3.8
 ---> b6bfe2b71f9d
Step 2/11 : RUN apk update && apk add mariadb-dev jpeg-dev zlib-dev gcc musl-dev libxml2-dev libxslt-dev gettext git
 ---> Using cache
 ---> 5612231bf59b
Step 3/11 : ADD . /base
 ---> Using cache
 ---> 55e33ac182f1
Step 4/11 : RUN pip install -r /base/requirements/local.txt
 ---> Using cache
 ---> cefd6c4a95ee
Step 5/11 : WORKDIR /base
 ---> Using cache
 ---> 5dc8c9242793
Step 6/11 : RUN mkdir /logs
 ---> Using cache
 ---> bf86a6a0e024
Step 7/11 : RUN touch /logs/info.log
 ---> Using cache
 ---> 6a1fff9397be
Step 8/11 : RUN touch /logs/debug.log
 ---> Using cache
 ---> a790b8eaff86
Step 9/11 : ENV DJANGO_SETTINGS_MODULE=settings.local
 ---> Using cache
 ---> d2101f9899b2
Step 10/11 : VOLUME ["/base/media", "/base/static"]
 ---> Using cache
 ---> b5683142d8af
Step 11/11 : EXPOSE 8003
 ---> Using cache
 ---> 9fe0d19472d0

Successfully built 9fe0d19472d0
Log: startEventSeen#data {"status":"tag","id":"sha256:9fe0d19472d0e3c17e18182b32671f711f578e3b5e7fe8055b6a4191a8ee6c13","Type":"image","Action":"tag","Actor":{"ID":"sha256:9fe0d19472d0e3c17e18182b32671f711f578e3b5e7fe8055b6a4191a8ee6c13","Attributes":{"name":"crmservice_crm_service:latest"}},"scope":"local","time":1561561729,"timeNano":1561561729440041086}
Successfully tagged crmservice_crm_service:latest
Creating crmservice_crm_service_1 ... 
Log: startEventSeen#data {"Type":"volume","Action":"create","Actor":{"ID":"3503f330dede01c58158d7ee445dd3512ca697039a5c5b75f38878cea86f6efd","Attributes":{"driver":"local"}},"scope":"local","time":1561561729,"timeNano":1561561729561201389}
Log: startEventSeen#data {"Type":"volume","Action":"create","Actor":{"ID":"5ddfe5c7c08d73a1d294c9611e0998a4c721f6512a990de3327a639027901f4a","Attributes":{"driver":"local"}},"scope":"local","time":1561561729,"timeNano":1561561729562137913}
Log: startEventSeen#data {"status":"create","id":"ea70d8e4d5733a3a38e461f5edd9e0cd2c5ee7fb4d0092dce635b967fbdef34d","from":"crmservice_crm_service","Type":"container","Action":"create","Actor":{"ID":"ea70d8e4d5733a3a38e461f5edd9e0cd2c5ee7fb4d0092dce635b967fbdef34d","Attributes":{"com.docker.compose.config-hash":"b547f13c667c503cb9b88c98d6585e98944cd4674e5a0e2d5203d414053371fd","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"crmservice","com.docker.compose.service":"crm_service","com.docker.compose.version":"1.18.0","image":"crmservice_crm_service","name":"crmservice_crm_service_1"}},"scope":"local","time":1561561729,"timeNano":1561561729590999388}
Log: startEventSeen#data {"Type":"network","Action":"disconnect","Actor":{"ID":"11ea7b0e6af42254908c2de12601caeccac783816ee761d50bc2ac79ed8f5513","Attributes":{"container":"ea70d8e4d5733a3a38e461f5edd9e0cd2c5ee7fb4d0092dce635b967fbdef34d","name":"shared","type":"bridge"}},"scope":"local","time":1561561729,"timeNano":1561561729608638050}
Log: startEventSeen#data {"Type":"network","Action":"connect","Actor":{"ID":"11ea7b0e6af42254908c2de12601caeccac783816ee761d50bc2ac79ed8f5513","Attributes":{"container":"ea70d8e4d5733a3a38e461f5edd9e0cd2c5ee7fb4d0092dce635b967fbdef34d","name":"shared","type":"bridge"}},"scope":"local","time":1561561729,"timeNano":1561561729680397014}
Log: startEventSeen#data {"Type":"volume","Action":"mount","Actor":{"ID":"3503f330dede01c58158d7ee445dd3512ca697039a5c5b75f38878cea86f6efd","Attributes":{"container":"ea70d8e4d5733a3a38e461f5edd9e0cd2c5ee7fb4d0092dce635b967fbdef34d","destination":"/base/media","driver":"local","propagation":"","read/write":"true"}},"scope":"local","time":1561561729,"timeNano":1561561729684157060}
Log: startEventSeen#data {"Type":"volume","Action":"mount","Actor":{"ID":"5ddfe5c7c08d73a1d294c9611e0998a4c721f6512a990de3327a639027901f4a","Attributes":{"container":"ea70d8e4d5733a3a38e461f5edd9e0cd2c5ee7fb4d0092dce635b967fbdef34d","destination":"/base/static","driver":"local","propagation":"","read/write":"true"}},"scope":"local","time":1561561729,"timeNano":1561561729684193980}
Log: startEventSeen#data {"status":"start","id":"ea70d8e4d5733a3a38e461f5edd9e0cd2c5ee7fb4d0092dce635b967fbdef34d","from":"crmservice_crm_service","Type":"container","Action":"start","Actor":{"ID":"ea70d8e4d5733a3a38e461f5edd9e0cd2c5ee7fb4d0092dce635b967fbdef34d","Attributes":{"com.docker.compose.config-hash":"b547f13c667c503cb9b88c98d6585e98944cd4674e5a0e2d5203d414053371fd","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"crmservice","com.docker.compose.serv
Creating crmservice_crm_service_1 ... done
```

**Comment by chrmarti** [comment] 2019-06-27 07:10
There is a change in Docker Compose 1.21.0 that would explain it (https://github.com/docker/compose/pull/5788). Could you check which version of Docker Compose you have and if it is < 1.21, update to the latest (or at least 1.21)?

**Comment by diegoduncan21** [comment] 2019-06-27 12:25
Hi @chrmarti. it was that, i update docker-compose from 1.18.0 to 1.24.0 and it works now. Thank you so much.

**Comment by chrmarti** [comment] 2019-06-27 13:37
Adding a version check similar to the one we have for Docker. @Chuxel Should we mention in the documentation that Docker Compose 1.21.0 or later is required when working with that?

**Comment by chrmarti** [comment] 2019-06-27 13:43
Actually, that is only a year old (https://github.com/docker/compose/releases/tag/1.21.0), we might lock out a few users with that limitation when it only affects project folders with hyphen or underscore in their folder name. We could also try to handle both cases.

**Comment by Chuxel** [comment] 2019-06-27 15:16
@chrmarti Yeah we should add that.  I've noticed some of the distros include outdated docker-compose in their packages.  We might actually want to trap and error now that we know this actually causes problems.

**Closed** 2019-07-02 11:07 UTC
Labels: bug, containers
