### ISSUE TITLE
initializeCommand: Unclear how this can be portable

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#4753] opened 2021-03-24 13:23 UTC
Testing #4721

The test item states that the path to the script should use slashes (not backslashes) to be portable.

I wonder how the path can be portable given that path needs to contain `.bat` and `.cmd` on Windows. I first thought that we can leave `.bat` and `.cmd` away, but that didn't work.

**Comment by aeschli** [comment] 2021-03-24 13:23
![image](https://user-images.githubusercontent.com/6461412/112317607-834c2080-8cac-11eb-82cf-a6d1953253a5.png)

**Comment by chrmarti** [comment] 2021-03-25 14:22
Paths relative to the workspace folder using slashes as separators work after fixing #4738. Marking as duplicate of that.

**Closed by chrmarti** 2021-03-25 14:22 UTC
Labels: bug, containers
