### ISSUE TITLE
Remote server doesn't start on insiders without pre-release extension

### ISSUE THREAD

**Issue by benedikt-mayer** [microsoft/vscode-remote-release#6325] opened 2022-02-11 11:21 UTC
- VSCode Version: 1.65.0-insider (user setup) Commit: bb221a61d29deabd99ee9431736d04f2175cb596
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Version: CentOS Linux 7
- Remote Extension/Connection Type: SSH
- Logs: 
```
server.sh is being replaced by 'bin/code-server-insiders'. Please migrate to the new command and adopt the following new default behaviors:
* connection token is mandatory unless --without-connection-token is used
* host defaults to `localhost`
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Do you accept the terms in the License Agreement?
```

Steps to Reproduce:

1. Install VS Code Insiders
2. Use the regular non pre-release version of Remote-SSH

The VS Code server then fails to start with the above logs.

Using the Pre-Release Remote-SSH extension fixes the problem.

**Comment by niderhoff** [comment] 2022-02-11 12:29
duplicate of #6321

**Comment by roblourens** [comment] 2022-02-11 19:34
https://github.com/microsoft/vscode-remote-release/issues/6328

**Closed by roblourens** 2022-02-11 19:34 UTC
Labels: ssh
