### ISSUE TITLE
File locking not working with AFS home directory

### ISSUE THREAD

**Issue by malmaud** [microsoft/vscode-remote-release#540] opened 2019-05-31 22:36 UTC
- VSCode Version: 1.35.0 (2737cde4facc8411982862742f5c6cd3dabef323)
- Local OS Version: 10.4.4
- Remote OS Version: Ubuntu 16.0.4
- Remote Extension/Connection Type: SSH

I'm trying to open an SSH session with a host that previously worked (the host is called 'melville'). Eventually a dialog opens that says "Could not establish connection to "melville". The "Remote- SSH" output pane is displaying the following:

```
remote-ssh@0.39.0
SSH Resolver called for "ssh-remote+melville"
SSH Resolver called for host: melville
Setting up SSH remote "melville"
Using commit id "2737cde4facc8411982862742f5c6cd3dabef323" and quality "insider" for server
Install and start server if needed
> Installation already in progress...
> e8c95ce6-b93c-43b8-a6b3-fb870516379d##24##
"install" terminal command done
Received install output: e8c95ce6-b93c-43b8-a6b3-fb870516379d##24##
Server installation process already in progress - waiting and retrying 1
> Installation already in progress...
> e8c95ce6-b93c-43b8-a6b3-fb870516379d##24##
"install" terminal command done
Received install output: e8c95ce6-b93c-43b8-a6b3-fb870516379d##24##
Server installation process already in progress - waiting and retrying 2
> Installation already in progress...
> e8c95ce6-b93c-43b8-a6b3-fb870516379d##24##
"install" terminal command done
Received install output: e8c95ce6-b93c-43b8-a6b3-fb870516379d##24##
Server installation process already in progress - waiting and retrying 3
...
```

**Comment by malmaud** [comment] 2019-05-31 22:41
I solved this by manually deleting `$HOME/.vscode-server-insiders` from the host. Not sure if you want this issue closed though since I don't know how it got into this corrupted state to begin with.

**Comment by malmaud** [comment] 2019-05-31 22:44
Actually, once I clicked 'Open folder' after the successful connection, the 'Open folder' dialog has a progress bar under it that never terminates and eventually the window refreshes on its own and the connection fails, bringing me back to the state in my original post.

**Comment by malmaud** [comment] 2019-05-31 22:48
OK, I think that has something to do with the fact that I have a `.profile` file in my home directory on the host that changes the `$HOME` environment variable to a new directory.

**Comment by malmaud** [comment] 2019-05-31 23:28
Actually, that doesn't seem relevant - even if I get rid of that, this problem persists. It seems maybe related to the home directory being an AFS mount. If I change my home directory to a local directory, everything works fine.

**Comment by roblourens** [comment] 2019-06-13 01:34
It sounds likely that `flock` is not working correctly on AFS...

**Comment by achalddave** [comment] 2019-07-21 13:46
I was able to solve this by killing all vscode processes on the server:

`pkill -u ${USER} -f vscode`

**Comment by roblourens** [comment] 2019-07-23 17:54
This is probably the same as issues I've had with NFS. Can you try installing the latest _nightly_ version of the extension and set `"remote.SSH.lockfilesInTmp": true`?

**Comment by malmaud** [comment] 2019-07-25 14:58
I'm not personally in a position to test this anymore, but happy for someone else to take up the mantle.

**Comment by ZhongxiaYan** [comment] 2019-07-27 06:50
I actually happen to be from the same institute as @malmaud and had the same AFS issue. I can confirm that @roblourens lockfilesInTmp: true does work!!! Thank you so much!!!

**Comment by roblourens** [comment] 2019-07-27 17:45
Wonderful, thanks for trying it. I will close this as a duplicate of the other NFS locking issues.

**Closed by roblourens** 2019-07-27 17:45 UTC
Labels: bug, needs-more-info, ssh

**Comment by JokerSeven** [comment] 2019-08-06 02:52
Hi, @roblourens . Can you tell me where to set "remote.SSH.lockfilesInTmp": true ? I can't find "remote.SSH.lockfilesInTmp" in vscode settings. Thanks!

**Comment by roblourens** [comment] 2019-08-06 16:21
Make sure you are using the nightly version of the extension

**Comment by JokerSeven** [comment] 2019-08-07 07:44
Thanks for your reply
