### ISSUE TITLE
It's unsafe to expose ports to 0.0.0.0 rather than 127.0.0.1 in remote server

### ISSUE THREAD

**Issue by WangLei1993** [microsoft/vscode-remote-release#1016] opened 2019-07-23 15:54 UTC
- VSCode Version: e1d3dd53d17fb1529a002e4d6fb066db0a0bd385
- Local OS Version: Darwin x64 18.6.0
- Remote OS Version: Ubuntu 18.10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect remote as common steps 
2. after using netstat command, we can see two ports are exposing to 0.0.0.0 rather than 127.0.0.1. But one port is used with ssh tunnel and it only connected with 127.0.0.1 address. And another one may connected as same as the first because we only use ssh in vscode remote.

I think it is dangerous to expose ports to 0.0.0.0 if not necessary, this will lead to attacks from hackers. May it can be changed to 127.0.0.1.

**Comment by roblourens** [comment] 2019-07-23 18:43
I don't see this, can you explain in detail?

**Comment by WangLei1993** [comment] 2019-07-24 03:14
First, my vscode version info:

> Version: 1.37.0-insider
> Commit: e1d3dd53d17fb1529a002e4d6fb066db0a0bd385
> Date: 2019-07-23T05:21:39.758Z
> Electron: 4.2.5
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Darwin x64 18.6.0

Second, we can see some info in "Remote SSH" output when we connect to remote as common steps:

<img width="1184" alt="sc_20190724103539" src="https://user-images.githubusercontent.com/7637623/61760757-26c19f80-adff-11e9-9ba8-7869f23c55d5.png">


And Now, we check the remote server:

![image](https://user-images.githubusercontent.com/7637623/61760815-5b355b80-adff-11e9-83d3-2fa8721de22f.png)

![image](https://user-images.githubusercontent.com/7637623/61760826-61c3d300-adff-11e9-8c4b-aeba991455e2.png)

We can find that vscode node server listen on :::39790 and :::42731. The 39790 port is mapped to local 39790 port by ssh tunnel and it is only connected with 127.0.0.1:39902 and 127.0.0.1:39904 by ssh tunnel on server. I can't find which process to use the another port 42731 for the time being. But if it is used by ssh tunnel as the 39790 port, it may also be connected with 127.0.0.1.

So I think it is unnecessary to listen port on 0.0.0.0, and it's better to 127.0.0.1. It‘s dangerous for exposing ports to 0.0.0.0 because I can connect to 39790 and 42731 from another machine. If I am a hacker, I may to do something with it. For another reason, we just use ssh to remote server for edit, it may not to use other  0.0.0.0:xx port to be connected except for ssh port.

**Comment by roblourens** [comment] 2019-07-24 04:09
I see what you are saying, thanks. The server is currently designed to be connected to in different ways including WSL and Containers where we will just connect to that port directly from outside, but maybe we can restrict it when it's started by the ssh extension.

**Comment by tamuratak** [comment] 2019-07-24 06:01
Related to #291.

**Comment by roblourens** [comment] 2019-07-24 21:05
I think this is a dupe of https://github.com/microsoft/vscode-remote-release/issues/291, thanks

**Comment by roblourens** [comment] 2019-07-24 21:06
I will close the other one since this got assigned

**Comment by zao** [comment] 2019-07-25 14:02
Please note that #291 had additional feedback in that listening on just localhost is not sufficiently secure for servers that have multiple users, like cluster login nodes or shared department servers.

**Comment by alexandrudima** [comment] 2019-07-29 19:56
Pushed changes for the server

**Closed** 2019-08-19 04:37 UTC
Labels: feature-request, ssh

**Comment by alexandrudima** [comment] 2019-08-28 12:19
Verified by running `sudo lsof -i`. I think this is correct now, as I see `localhost:42017`

![image](https://user-images.githubusercontent.com/5047891/63855074-d65dd480-c99e-11e9-80b9-46c833f15b87.png)
