### ISSUE TITLE
Remote - WSL: open editors shows an absolute path for the welcome page 

### ISSUE THREAD

**Issue by liuyji** [microsoft/vscode-remote-release#1181] opened 2019-08-16 14:01 UTC
Edit: see annotated screenshot below https://github.com/microsoft/vscode-remote-release/issues/1181#issuecomment-522945435

- Local OS Version: Windows 10 1903
- Remote Extension/Connection Type: WSL

I install this extension only because VS Code's strongly recommand and never used it. About after VS Code upgrade to 1.37(I'm not very sure), I find VS Code Welcome page has a strange name and in 1.37.1 it still not fixed. Before I report an issue to VS Code I saw [this:](https://github.com/microsoft/vscode/issues/78664). I tried to disable all my extensions and find things be OK. And by enum I find this extension makes this problem.

**Comment by liuyji** [comment] 2019-08-16 14:03
![图片](https://user-images.githubusercontent.com/43626829/63173004-87946e80-c071-11e9-8c8f-727f21cfcdba.png)
I copied the picture of issue I mentioned before here. The origin name of Welcom page is just "Welcome".

**Comment by egamma** [comment] 2019-08-20 10:02
![image](https://user-images.githubusercontent.com/172399/63338018-51d9d900-c342-11e9-921d-960b30b17e25.png)

**Comment by isidorn** [comment] 2019-08-20 12:55
I can not reproduce this for dev containers. I also can not reproduce for local.
@aeschli are we doing something special for WSL

![Screenshot 2019-08-20 at 14 53 51](https://user-images.githubusercontent.com/1926584/63348818-59a57780-c35a-11e9-8b69-6d2ce91e6677.png)

**Comment by aeschli** [comment] 2019-08-20 13:13
WSL doesn't do anything special, but I speculate it's because the local window runs on Windows? There seems to be some special code just for the Welcome page.

**Comment by isidorn** [comment] 2019-08-20 13:23
fyi @chrmarti 
@aeschli if you get it on your machine let me know and we can look into together.

**Comment by liuyji** [comment] 2019-08-22 17:03
This can be always reproduce in my computer, Windows 1903 with VS Code 1.37.1 and last version of Remote-WSL.
1. Disable all extensions, things are ok.
2. Enable Remote-WSL, close all folders open in VS Code, then close VS Code and reopen it, Welcome page will show automatically with an absolute path.

If you open welcome page through Help -> Welcome, this issue will not happen. It's only happens on the automatically shown welcome page.

**Comment by isidorn** [comment] 2019-08-23 10:42
This should be fixed via https://github.com/microsoft/vscode/commit/b9ccfc4b3fa4fe32991e02f5767cfe093292717b
@liuyji can you please try VS Code insiders from monday and let us know if you still see it. Thanks!

**Closed** 2019-08-30 10:52 UTC
Labels: needs-more-info
