### ISSUE TITLE
Devcontainers MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by Dzivo** [microsoft/vscode-remote-release#8515] opened 2023-05-19 13:02 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

```
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

Steps to Reproduce:

1. Create new AzureDevops Repository with devcontainer script defined
2.  Open VIsual Studio Code
3. Press F1 to open commands 
4. Select `Clone repository in named container volume`
5. Copy repository url 
6. Use default settings 

Error: 

```
[3641 ms] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /workspaces/LibertasApp --id-label vsch.local.repository=https://enumsoftware@dev.azure.com/enumsoftware/LibertasApp/_git/LibertasApp --id-label vsch.local.repository.volume=vsc-remote-containers-libertas-app --id-label vsch.local.repository.folder=LibertasApp --id-label devcontainer.config_file=/workspaces/LibertasApp/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/LibertasApp/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-b5043b98-25d0-45aa-8cca-489d6ba8f549.json --mount-workspace-git-root true
[3807 ms] node:internal/modules/cjs/loader:1029
[3807 ms]   throw err;
[3807 ms]   ^
[3808 ms] Error: Cannot find module '/root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/spec-node/devContainersSpecCLI.js'
[3808 ms]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
[3808 ms]     at Function.Module._load (node:internal/modules/cjs/loader:871:27)
[3808 ms]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[3808 ms]     at node:internal/main/run_main_module:22:47 {
[3808 ms]   code: 'MODULE_NOT_FOUND',
[3808 ms]   requireStack: []
[3808 ms] }
[3826 ms] Exit code 1
[3826 ms] Start: Run: docker rm -f 2e1698aae7c27a6acc9ffe06f7cad0737e6f37d09445721f7eccf1916e808d0e
[3827 ms] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /workspaces/LibertasApp --id-label vsch.local.repository=https://enumsoftware@dev.azure.com/enumsoftware/LibertasApp/_git/LibertasApp --id-label vsch.local.repository.volume=vsc-remote-containers-libertas-app --id-label vsch.local.repository.folder=LibertasApp --id-label devcontainer.config_file=/workspaces/LibertasApp/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/LibertasApp/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-b5043b98-25d0-45aa-8cca-489d6ba8f549.json --mount-workspace-git-root true
```

This used to happen a long time ago now it started happening again with new version of VS Code.

Also this does not happen when trying to run reopen in container but than commands like ng serve and npm install are way to slow

**Comment by akutruff** [comment] 2023-05-22 13:19
FYI: I just got this too.  Moving to pre-release also appears to have fixed it.

**Comment by Dzivo** [comment] 2023-05-22 16:33
@chrmarti i dont think so it doesnt work on both of my computers and it started working after i updated to prerelease version. Also i have mention in another report that the login is not user friendly i usually need to manually change .gitconfig before i can clone repository in named container. Its really a shame since devcontainers definitely changed the way i develop. I can easily switch computers and have everything setup really fast.

If you need more info or a share screen session feel free to contact me

**Comment by ddrinka** [comment] 2023-05-22 19:27
Our repro device has an expired subscription of Norton Antivirus still installed.  I'm curious if others do as well.

**Comment by Dzivo** [comment] 2023-05-23 09:09
@ddrinka i dont and i have never used Northon only win defender

**Comment by bjoernstachmann0007** [comment] 2023-05-23 12:19
mine is a managed device with installed virus protection

**Comment by chrmarti** [comment] 2023-05-23 12:22
0.292.0 stable and 0.293.0 pre-release don't have any differences in this area of the code which makes me wonder if there is a race condition.

Could you:
- Make sure it still occurs with 0.292.0 (this will also move the image tag to the corrupted image).
- Then run `docker run vsc-volume-bootstrap find /root/.vscode-remote-containers` and post the output here.
- Locally check if the missing file exists: ` dir ~\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node`

**Comment by nbering** [comment] 2023-05-24 10:57
I have Anti-Virus, but it's report shows no hits of any kind in the last 30 days.

**Comment by chrmarti** [comment] 2023-05-25 07:40
Could you:
- Make sure it still occurs with 0.292.0 (this will also move the image tag to the corrupted image).
- Then run `docker run vsc-volume-bootstrap find /root/.vscode-remote-containers` and post the output here.
- Locally check if the missing file exists: ` dir ~\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node`

**Comment by joeleeyk** [comment] 2023-05-25 09:58
@chrmarti 

I have the same problem with everyone and moving to 0.293.0 pre-release solved the problem. I moved to 0.292.0 make sure it fails and did a docker run as you suggested output:

/root/.vscode-remote-containers
/root/.vscode-remote-containers/dist
/root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0
/root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/scripts
/root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist
/root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/node_modules
/root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/node_modules/vscode-dev-containers
/root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/node_modules/vscode-dev-containers/container-features
/root/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/spec-node

 This is the output of the same docker run but on 0.293.0:

/root/.vscode-remote-containers
/root/.vscode-remote-containers/dist
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/package.json
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/scripts
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/scripts/updateUID.Dockerfile
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/node_modules
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/node_modules/vscode-dev-containers
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/node_modules/vscode-dev-containers/container-features
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/node_modules/vscode-dev-containers/container-features/homebrew-debian.sh
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/node_modules/vscode-dev-containers/container-features/feature-scripts.env
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/node_modules/vscode-dev-containers/container-features/devcontainer-features.json
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/node_modules/vscode-dev-containers/container-features/install.sh
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/node_modules/vscode-dev-containers/container-features/fish-debian.sh
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node
/root/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js

I hope it helps.

**Comment by chrmarti** [comment] 2023-06-01 09:26
Fix is in the Dev Containers extension 0.294.0-pre-release. Thanks.

**Closed by chrmarti** 2023-06-01 09:26 UTC
Labels: bug, containers

**Comment by TylerLeonhardt** [comment] 2023-06-01 17:19
Hi folks, can you verify for us that 0.294.0-pre-release fixes the problem for you?

**Comment by joeleeyk** [comment] 2023-06-01 19:23
Hi, @TylerLeonhardt I am on 0.294.0 now and the problem is fixed for me

**Comment by haughtm** [comment] 2023-06-06 11:33
Hi, @TylerLeonhardt, switching to 0.294-0 also resolved the issue for me.
