### ISSUE TITLE
Incorrect GLIBC Version Detection in WSL2 Environments with Development GLIBC Versions

### ISSUE THREAD

**Issue by josenobile** [microsoft/vscode-remote-release#9394] opened 2024-01-17 04:12 UTC
- **VSCode Version**: 1.86.0-insider (Commit 2c8f29174a63b3ace3d00ad0028c7dc7ed9853b8)
- **Local OS Version**: Windows 11 Home Insider Preview, Version 23H2, OS Build 26020.1000
- **Remote OS Version**: Fedora Linux 40 (Container Image Prerelease) on WSL2
- **Remote Extension/Connection Type**: WSL

- **Logs**: 
```
[2024-01-17 03:25:26.058] Extension version: 0.81.8
[2024-01-17 03:25:26.059] L10N bundle: undefined
[2024-01-17 03:25:26.073] authorityHierarchy: wsl+fedora
[2024-01-17 03:25:26.073] WSL extension activating for a local WSL instance
[2024-01-17 03:25:26.105] Resolving wsl+fedora, resolveAttempt: 1
[2024-01-17 03:25:26.106] NodeExecServer run: C:\WINDOWS\System32\wsl.exe --status
[2024-01-17 03:25:26.253] WSL feature installed: true (wsl --status)
[2024-01-17 03:25:26.253] NodeExecServer run: C:\WINDOWS\System32\wsl.exe --list --verbose
[2024-01-17 03:25:26.394] 1 distros found
[2024-01-17 03:25:26.395] Starting VS Code Server inside WSL (wsl2)
[2024-01-17 03:25:26.395] Windows build: 26020. Multi distro support: available. WSL path support: enabled
[2024-01-17 03:25:26.395] Scriptless setup: false
[2024-01-17 03:25:26.396] No shell environment set or found for current distro.
[2024-01-17 03:25:26.894] WSL daemon log file: 
[2024-01-17 03:25:26.898] Probing if server is already installed: if [ -d ~/.vscode-server-insiders/bin/2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf alpine-; fi; uname -m
[2024-01-17 03:25:26.899] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d fedora -e sh -c if [ -d ~/.vscode-server-insiders/bin/2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf alpine-; fi; uname -m
[2024-01-17 03:25:27.588] Probing result: install-found x86_64
[2024-01-17 03:25:27.588] Server install found in WSL
[2024-01-17 03:25:27.592] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d fedora sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b insider code-server-insiders .vscode-server-insiders --host=127.0.0.1 --port=0 --connection-token=2785660737-632319537-3301132405-495353486 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
[2024-01-17 03:25:30.070] Setting up server environment: Looking for /root/.vscode-server-insiders/server-env-setup. Not found.
[2024-01-17 03:25:30.070] WSL version: 6.1.21.2-microsoft-standard-WSL2+ fedora
[2024-01-17 03:25:30.070] WSL-shell-PID: 707
[2024-01-17 03:25:30.070] Node executable: /root/.vscode-server-insiders/bin/2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b/node
[2024-01-17 03:25:30.070] Starting server: /root/.vscode-server-insiders/bin/2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b/bin/code-server-insiders --host=127.0.0.1 --port=0 --connection-token=2785660737-632319537-3301132405-495353486 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all
[2024-01-17 03:25:30.127] Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc.so.6
[2024-01-17 03:25:30.127] Error: Missing required dependencies. Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information.
[2024-01-17 03:25:30.128] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2024-01-17 03:25:30.134] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d fedora -e kill 707
[2024-01-17 03:25:42.178] Download in background is enabled
```

**Steps to Reproduce:**

1. Install a development release of GLIBC (e.g., version 2.38.9000) in a WSL2 environment.
2. Connect to the WSL2 environment using VS Code with the WSL extension.
3. Observe the warning message indicating a missing GLIBC version, despite having a newer version installed.

**Issue Description:**
The `check-requirements.sh` script in the Visual Studio Code WSL extension fails to correctly identify the installed GLIBC version in WSL2 environments when a development version of GLIBC is used. This results in a misleading warning about a missing GLIBC version, even though a newer version is installed.

**Current Behavior:**
The script uses a `sed` command to parse the GLIBC version from the output of `/usr/lib64/libc.so.6 --version`. However, the current pattern only matches stable release formats and fails for development releases, leading to a false warning about missing GLIBC >= 2.28.

**Expected Behavior:**
The script should correctly identify the GLIBC version regardless of whether it is a stable or development release.

**Proposed Solution:**
Modify the `sed` command in `check-requirements.sh` to accommodate the version format of development releases. A suggested modification is:

Replace:
```sh
libc_version=$($libc_real_path --version | sed -n 's/.*stable release version \([0-9]\+\.[0-9]\+\).*/\1/p')
```

With:
```sh
libc_version=$($libc_real_path --version | sed -n 's/.*release version \([0-9]\+\.[0-9]\+\).*$/\1/p')
```

This change will allow the script to correctly parse both stable and development release version numbers.

**Does this issue occur when you try this locally?:** Not applicable
**Does this issue occur when you try this locally and all extensions are disabled?:** Not applicable

**Additional Context:**
Upon editing the check-requirements.sh script to correctly parse the GLIBC version, the issue is resolved, indicating that the problem lies within the script's logic. This issue appears to have been introduced in the latest version of Visual Studio Code - Insiders.

**Comment by SimonCahill** [comment] 2024-01-17 08:41
I'm currently experiencing a similar issue with a remote Ubuntu box.

Calling the script directly results in the following:

```
/home/simon/.vscode-server-insiders/cli/servers/Insiders-2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b.staging/server/bin/code-server-insiders --version
/usr/lib/x86_64-linux-gnu/libc.so.6
/home/simon/.vscode-server-insiders/cli/servers/Insiders-2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b.staging/server/bin/helpers/check-requirements.sh: 85: /usr/lib/x86_64-linux-gnu/libc.so.6: Permission denied

Warning: Missing GLIBC >= 2.28! from /usr/lib/x86_64-linux-gnu/libc.so.6
Error: Missing required dependencies. Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information.
```

I currently have installed: `libc6 is already the newest version (2.37-0ubuntu2.2).`

**Comment by deepak1556** [comment] 2024-01-17 08:44
@SimonCahill sorry about that, the issue you are facing should be addressed in next insiders release with https://github.com/microsoft/vscode/commit/aed5f4d65d2dbfda2c98abd7eb371751016838ab

As a sanity test can you modify the changes in the script from that commit and see if it resolves the issue.

**Comment by SimonCahill** [comment] 2024-01-17 08:46
@deepak1556 Yes, I've tried modifying the script, but because VS Code tries to re-download the server each time, the modifications are removed again.

**Comment by deepak1556** [comment] 2024-01-17 08:59
@josenobile thanks for detailed issue description, I would like to test the fix locally. How can I get the fedora 40 prerelease installed for WSL ?

**Comment by deepak1556** [comment] 2024-01-17 09:00
@SimonCahill insiders with the specified fix has been released, can you update the client and try again.

**Comment by SimonCahill** [comment] 2024-01-17 09:11
Trying it now. Will report back

**Comment by SimonCahill** [comment] 2024-01-17 09:20
@deepak1556 I've added a comment to the commit you referenced. Compiling a small C program or calling `strings` and grepping for `version` could yield the results you were looking for, instead of attempting to call a shared library.

I'd wager that the vast majority of SOs don't have a `_start()` function defined, unlike Windows with it's `DllMain()` or what that was called.

**Comment by deepak1556** [comment] 2024-01-17 11:02
Was able to setup Fedora 40 WSL from docker image and confirmed the fix. Issue will be addressed in tomorrows' insiders.

**Closed** 2024-01-17 11:18 UTC
Labels: bug, code-server
