### ISSUE TITLE
[Remote-SSH] Orphan "remote extension host agent" processes

### ISSUE THREAD

**Issue by Cu3PO42** [microsoft/vscode-remote-release#276] opened 2019-05-10 09:28 UTC
After opening a connection to a remote server and closing the window immediately, processes related to the extension host remain alive. In particular, they are:

```
sh /root/.vscode-remote/bin/d6aa8eaf30c71df32d4543290675808440def630/server.sh --disable-telemetry --port=0
 `- /root/.vscode-remote/bin/d6aa8eaf30c71df32d4543290675808440def630/node /root/.vscode-remote/bin/d6aa8eaf30c71df32d4543290675808440def630/out/remoteExtensionHostAgent.js --disable-telemetry --port=0
    `- /root/.vscode-remote/bin/d6aa8eaf30c71df32d4543290675808440def630/node /root/.vscode-remote/bin/d6aa8eaf30c71df32d4543290675808440def630/out/remoteExtensionHostAgent.js --disable-telemetry --port=0
```

However, there are 10 copies of the inner-most/leaf process running with the exact same parameters which I omitted for brevity.

This seems similar to #258 and #262, however the orphan processes seem different, so I opened a new issue.

- VSCode Version: 1.34.20-insider
- Local OS Version: macOS 10.13.6 (17G6030)
- Remote OS Version: Fedora 30 (Server)
- Remote Extension/Connection Type: SSH, plugin version 0.36.0

Steps to Reproduce:

1. Connect to remote server using the remote extension; no need to open any folder
2. Close VSCode after the connection was established

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

This is an entirely fresh install of VSCode Insiders. The only extension I installed is the Remote - SSH extension. I have also never used the remote with an earlier version of the remote plugin.

------------

Unrelated to this issue, I'm very excited for the possibilities opened up by this (group of) plugin(s) and want to thank you all for the great work done here!

**Comment by harmic** [comment] 2019-06-06 01:00
I'm seeing the same problem. The remoteExtensionHostAgent does not exit on the remote machine when I close vscode. Sometimes there are additional processes under that.

```
sh /home/itk/.vscode-server-insiders/bin/0284236851a94b116f468345f6e98688a737015d/server.sh --port=0
  └─node /home/itk/.vscode-server-insiders/bin/0284236851a94b116f468345f6e98688a737015d/out/remoteExtensionHostAgent.js --port=0
      └─10*[{node}]

sh /home/itk/.vscode-server-insiders/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/server.sh --port=0
  └─node /home/itk/.vscode-server-insiders/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/out/remoteExtensionHostAgent.js --port=0
      ├─node /home/itk/.vscode-server-insiders/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/out/bootstrap-fork --type=extensionHost--uriTransformerPath=/home/itk/.vscode-server-insiders/bin/553cfb2c2
      │   └─13*[{node}]
      ├─node /home/itk/.vscode-server-insiders/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/out/bootstrap-fork --type=watcherService
      │   └─9*[{node}]
      └─10*[{node}]

sh /home/itk/.vscode-server-insiders/bin/5c65d9bfa4c56538150d7f3066318e0db2c6151f/server.sh --port=0
  └─node /home/itk/.vscode-server-insiders/bin/5c65d9bfa4c56538150d7f3066318e0db2c6151f/out/remoteExtensionHostAgent.js --port=0
      └─10*[{node}]

```
vscode was not running when the above printout was taken.

What is the expected behavior here - is that process supposed to exit when vscode disconnects, or is it intended to run indefinitely?

Also worth noting that the different processes appear to be relating to different versions of the remote server (ie. each one has a different UUID as part of the path).  I could not be 100% sure this is always the case but in the cases I have checked lately it appears to be.

**Comment by harmic** [comment] 2019-06-06 01:04
Just found #203 which seems to be the same problem.

**Comment by roblourens** [comment] 2019-06-07 17:53
Closing as dupe of https://github.com/microsoft/vscode-remote-release/issues/203

**Closed by roblourens** 2019-06-07 17:53 UTC
Labels: bug, remote
