### ISSUE TITLE
the terminal shell path "cmd.exe" does not exist

### ISSUE THREAD

**Issue by maricoxu** [microsoft/vscode-remote-release#1452] opened 2019-09-22 06:25 UTC
Issue Type: <b>Bug</b>

Just follow Remote-SSH, and launch marico-machine in the targets of Remote extensions

Extension version: 0.46.1
VS Code version: Code - Insiders 1.39.0-insider (8b6e0efc0a98639085fabeb5226a516785424796, 2019-09-19T03:15:21.720Z)
OS version: Windows_NT x64 6.1.7601
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3109)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.95GB (4.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

Fetching remote diagnostics for 'SSH' failed.
</details>

**Comment by maricoxu** [comment] 2019-09-23 13:04
any help??  on win10 I can connect to my server successfully, and on my another  computer with win7, it failed with terminal shell path

**Comment by roblourens** [comment] 2019-09-27 15:38
Is cmd.exe not on your PATH? What if you type `cmd.exe` in a terminal?

**Comment by roblourens** [comment] 2019-10-01 03:54
Dupe of https://github.com/microsoft/vscode-remote-release/issues/1479

**Closed by roblourens** 2019-10-01 03:54 UTC
Labels: needs-more-info
