### ISSUE TITLE
Visual Studio code SSH, abnormal behaviors with the terminal and conda.

### ISSUE THREAD

**Issue by ShiroKL** [microsoft/vscode-remote-release#1675] opened 2019-10-11 14:01 UTC
- VSCode Version: 1.39.1
- OS Version: windows 10

Steps to Reproduce:

1.  Install visual studio code.
2. Connect on ssh on an linux distribution where conda is installed.
3. launch the command "conda" . The error message is "conda : command not found" using the terminal bash ( "bin/bash" ). If I use putty conda work well with the bash terminal. 

Does this issue occur when all extensions are disabled?: I can not disable all extensions, otherwise I could not use SSH

**Comment by roblourens** [comment] 2019-10-15 22:32
This sounds like a duplicate of https://github.com/microsoft/vscode-remote-release/issues/1671

**Closed by roblourens** 2019-10-15 22:32 UTC
