### ISSUE TITLE
Stuck on "Opening Remote..."

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-remote-release#195] opened 2019-05-07 07:34 UTC
- VSCode Version: 1.34.0-insider (user setup)
- Local OS Version: Windows 10 Enterpries, version 1709, OS Build 16299.1004
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote SSH host in a new Window

I have an ssh config with similar to this:
```sh
Host vm
        HostName 10.10.10.10
```

I can do an `ssh vm` from Windows PowerShell without any trouble. The user on Windows is the same as in my vm. It is using key based authentication, with no passphrase set.

When I try to open this with `Remote-SSH: Connect to Host...` it shows the notification for a short while but then in the lower-left it just gets stuck at "Opening Remote...". No notifications, no nothing.

I've tried searching for existing issues and I've read all documentation in regards to Remote development, but found no clue as to what I might be doing wrong.

**Comment by schmic** [comment] 2019-05-07 08:18
I have the same setup and found out that the `Host` part is used instead of the `Hostname` for the ssh connection.

**Comment by jbelien** [comment] 2019-05-07 08:26
I had the same issue, have a look at the VS Code Terminal (`CTRL + J`), in my case it was asking for the password (or the SSH key passphrase).

**Comment by thernstig** [comment] 2019-05-07 09:32
I could not find anything under `CTRL+J`, in which panel should I look? If I open the TERMINAL it just says `1: Starting...` in the drop-down to the right. As far as I am aware I have no passphrase, also considering I do not need to supply one if I use the normal `ssh` command from Windows PowerShell. Just to make absolutely sure, I checked this also according to https://security.stackexchange.com/a/129727. So I am fairly sure I do not have a passphrase set.

**Comment by egamma** [comment] 2019-05-07 09:49
@jbelien can you pls open the 'Output' panel at the bottom and switch to the 'Remote - SSH' output and include what is shown here.

**Comment by jbelien** [comment] 2019-05-07 09:59
@egamma Unfortunately, I just tried and can't seem to reproduce the "issue" I had.

Since then I enabled `"remote.SSH.showLoginTerminal": true` and everything is working fine since then.

**Comment by egamma** [comment] 2019-05-07 10:11
@jbelien thanks for following up. Just checked and the use of `showLoginTerminal` is documented https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods. I'm therefore closing this issue.

**Comment by thernstig** [comment] 2019-05-07 11:01
@egamma I was the one to open the issue and it seems you closed it due to a comment by @jbelien, but we do not share the same issue.

I did however enable the logging and this is the output I get:

```sh
SSH Resolver called for "ssh-remote+vm"
SSH Resolver called for host: vm
Setting up SSH remote "vm"
Using commit id "daf71423252a707b8e396e8afa8102b717f8213b" and quality "insider" for server
Install and start server if needed
> ...redacted...
> New release '18.04.2 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> 
> bash: cannot set terminal process group (68554): Inappropriate ioctl for device
> bash: no job control in this shell
> 
> tput: No value for $TERM and no -T specified
> tput: No value for $TERM and no -T specified
> tput: No value for $TERM and no -T specified
> 
> Found existing installation...
> 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> c931a42f-ebc8-4c45-a515-5d976ab928af==32873==
> 
"install" terminal command done
Received install output: c931a42f-ebc8-4c45-a515-5d976ab928af==32873==
Server is listening on port 32873
Spawning tunnel with: ssh  vm -L localhost:31784:localhost:32873 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 31784 and remote port 32873
Waiting for ssh tunnel to be ready
> ...redacted...
Tunneling remote port 32873 to local port 31784
Resolving "ssh-remote+vm" to "localhost:31784", attempt: 1
> channel 3: open failed: administratively prohibited: open failed
> channel 4: open failed: administratively prohibited: open failed
> 
> channel 5: open failed: administratively prohibited: open failed
> Connected to SSH Host - Please do not close this terminal
> 
```

**Comment by thernstig** [comment] 2019-05-07 11:47
I found that enabling the sshd config `AllowTcpForwarding` fixed the issue. I think this should be documented somewhere.

**Comment by egamma** [comment] 2019-05-07 12:02
>I found that enabling the sshd config AllowTcpForwarding fixed the issue. I think this should be documented somewhere.

@chuxel candiate tips & tricks material

**Comment by egamma** [comment] 2019-05-07 12:02
reopening and labelling as a doc issue.

**Comment by thernstig** [comment] 2019-05-07 13:45
A note if the docs get an update: It was the output `channel 3: open failed: administratively prohibited: open failed` that indicated I needed to set `AllowTcpForwarding yes` (I actually believe `AllowTcpForwarding local` should be enough though, but never tested).

**Comment by shanehou** [comment] 2019-05-08 04:50
`AllowTcpForwarding yes` doesn't solve it.
Am I required to restart sshd?

**Comment by thernstig** [comment] 2019-05-08 06:40
> `AllowTcpForwarding yes` doesn't solve it.
> Am I required to restart sshd?

Yes, a change to sshd config always require a restart. Try a `sudo service sshd reload` or a `sudo service sshd restart` if the former does not work. (Or any of the other many variants depending on Linux OS)

**Comment by thernstig** [comment] 2019-05-08 18:42
@Defite That is not the same error I as reported. As you can see here https://github.com/microsoft/vscode-remote-release/issues/195#issuecomment-490033262 my error is about `channel 3: open failed: administratively prohibited: open failed`. That problem was for me solved by setting `AllowTcpForwarding yes`

**Comment by Chuxel** [comment] 2019-05-08 20:40
@egamma This has been added to docs. I think the broader TCP forwarding question (which is what this property turns on) is covered under #92.

**Closed by Chuxel** 2019-05-08 20:40 UTC
Labels: ssh
