### ISSUE TITLE
remote SSH issue

### ISSUE THREAD

**Issue by nitinsea** [microsoft/vscode-remote-release#2893] opened 2020-04-29 14:04 UTC
Issue Type: <b>Bug</b>

i am trying to connect to linux pc which is in corporate network. we use split tunnel vpn. i think because of this it is not connecting.

Extension version: 0.51.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rzhao271** [comment] 2020-11-05 22:07
Closing for now. Feel free to reply if the issue is still showing up on the latest version (preferably tested with latest Insiders edition).

**Closed by rzhao271** 2020-11-05 22:07 UTC
Labels: bug, needs-more-info, ssh
