### ISSUE TITLE
Mechanism to pass arguments to docker command

### ISSUE THREAD

**Issue by edmcman** [microsoft/vscode-remote-release#4985] opened 2021-04-29 15:59 UTC
Because of weird proxy settings I have to use, I need to use `docker --network=host` to allow the container to reach the internet.  It would be nice to have a setting for the remote container extension that allows me to specify such arguments.  Without this, most container builds fail because they cannot access internet resources.

**Comment by bamurtaugh** [comment] 2021-04-29 20:54
Closing as I believe this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/3545. If I've misunderstood the request/any differences here, please just let me know.

**Closed by bamurtaugh** 2021-04-29 20:54 UTC
Labels: containers
