### ISSUE TITLE
Enable docker buildkit via env variables

### ISSUE THREAD

**Issue by nenadfilipovic** [microsoft/vscode-remote-release#4708] opened 2021-03-20 22:03 UTC
- VSCode Version: 1.54.3
- Local OS Version: elementary 5.1.7
- Remote OS Version: Debian 10 Buster
- Remote Extension/Connection Type: Docker

I have project that I am developing inside container and I want to enable docker buildkit on it, after reading some issues on this topic like: https://github.com/microsoft/vscode-remote-release/issues/1409 I still can't solve this. This is the list of things I have tried so far.

- Set `DOCKER_BUILDKIT=1` in `.env` file = does not work
- Set `expose DOCKER_BUILDKIT=1` inside `initializeCommand` on `.devcontainer.json` = does not work
- Set `DOCKER_BUILDKIT=1` inside `.vscode` folder in `settings.json` under `terminal.integrated.env.linux` = does not work
- Reference local `DOCKER_BUILDKIT` inside `.devcontainer.json` in `remoteEnv` = does not work, env will be available inside started container but it is not available during build

- Set `expose DOCKER_BUILDKIT=1` in bash and after that run `code` = works, container start building with buildkit
- Set `docker buildx install` inside `initializeCommand` on `.devcontainer.json` = works but I really don't like this way because it sets it as default
- Set `expose DOCKER_BUILDKIT=1` in .bashrc = works

Interesting thing is that I can set `COMPOSE_PROFILES` var inside `.env` and compose reads it without problem but it doesn't want to read other docker vars.

What would probably work best for my use case is a way to enable buildkit for this project but it should not force user to store env variables to their .config or .profile or to force them to use buildx as default.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment] 2021-03-22 09:27
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/1409

**Closed by chrmarti** 2021-03-22 09:27 UTC
Labels: containers
