### ISSUE TITLE
Remote - Containers does not suppotrt `ssh://...` as DOCKER_HOST

### ISSUE THREAD

**Issue by igorbb** [microsoft/vscode-remote-release#1719] opened 2019-10-24 16:31 UTC
- VSCode Version: 1.39.2
- Local OS Version: Ubuntu 18.04
- Remote OS Version:Ubuntu 18.04
- Remote Extension/Connection Type: Docker

The docker and remote extension does not accept ssh// protocol for DOCKER_HOST.

Steps to Reproduce:

1.Setup a env where DOCKER_HOST use a ssh//... instead of tcp://...
2.Open vs-code
3.Install Docker and Remote - Containers extensiosn
4. Re-star vs-code
5. Click on Docker on the side panel.
6 Notice Falied to connect erros - `Error: DOCKER_HOST env variable should be something like tcp://localhost:1234`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No -  Docker and Remote are needed.

might be related to #636

**Comment by Chuxel** [comment] 2019-10-24 17:57
Yes, this is a dupe of #636 - the upstream looks like it may have unblocked us here, but we'd need to verify.

**Closed by Chuxel** 2019-10-24 17:57 UTC
