### ISSUE TITLE
vscode token cannot overwrite existing file

### ISSUE THREAD

**Issue by chuachen** [microsoft/vscode-remote-release#6446] opened 2022-03-09 15:04 UTC
Does this issue occur when all extensions are disabled?: No, I just enable Remote-SSH to connect to a remote server.

- VS Code Version: 1.64.2
- OS Version: macOS Monterey 12.2.1 (21D62)

Steps to Reproduce:
1. connect with a remote server.

Failure Log:

```
[22:29:33.839] Log Level: 2
[22:29:33.840] remote-ssh@0.76.1
[22:29:33.840] darwin x64
[22:29:33.843] SSH Resolver called for "ssh-remote+remote-server-name-1", attempt 1
[22:29:33.844] "remote.SSH.useLocalServer": true
[22:29:33.844] "remote.SSH.path": undefined
[22:29:33.844] "remote.SSH.configFile": undefined
[22:29:33.844] "remote.SSH.useFlock": true
[22:29:33.844] "remote.SSH.lockfilesInTmp": false
[22:29:33.844] "remote.SSH.localServerDownload": auto
[22:29:33.844] "remote.SSH.remoteServerListenOnSocket": false
[22:29:33.844] "remote.SSH.showLoginTerminal": true
[22:29:33.845] "remote.SSH.defaultExtensions": []
[22:29:33.845] "remote.SSH.loglevel": 2
[22:29:33.845] "remote.SSH.enableDynamicForwarding": false
[22:29:33.845] "remote.SSH.enableRemoteCommand": false
[22:29:33.845] "remote.SSH.serverPickPortsFromRange": {}
[22:29:33.845] "remote.SSH.serverInstallPath": {}
[22:29:33.855] SSH Resolver called for host: remote-server-name-1
[22:29:33.855] Setting up SSH remote "remote-server-name-1"
[22:29:33.858] Acquiring local install lock: /var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-remote-ssh-466bc7f5-install.lock
[22:29:33.860] Looking for existing server data file at /Users/chuachen/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-466bc7f5-f80445acd5a3dadef24aa209168452a3d97cc326-0.76.1/data.json
[22:29:33.861] Found local server running: {"remoteListeningOn":{"port":34412},"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","tmpDir":"/run/user/615227","platform":"linux","connectionToken":"1aa1a1a1-11aa-1a1a-a111-aa1aaa11a11a","pid":15801,"ipcHandlePath":"/var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-ssh-askpass-9cc4c211f38deb0579f9d469e28103e74fbc129a.sock","socksPort":57007,"startupTime":1646835638490}
[22:29:33.864] Server delay-shutdown request failed: connect ECONNREFUSED /var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-ssh-askpass-9cc4c211f38deb0579f9d469e28103e74fbc129a.sock
[22:29:33.864] Existing server's health check failed, will start a new one
[22:29:33.864] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[22:29:33.867] Install and start server if needed
[22:29:33.869] PATH: /anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin
[22:29:33.869] Checking ssh with "ssh -V"
[22:29:33.876] > OpenSSH_8.6p1, LibreSSL 2.8.3

[22:29:33.878] askpass server listening on /var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-ssh-askpass-e44141fcbbf0c3bb757fd7f91a842d799c7cb6af.sock
[22:29:33.879] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-ssh-askpass-3446218408c85000adc2a3a91116492562946f1b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","57280","-o","ConnectTimeout=15","remote-server-name-1"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/chuachen/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-466bc7f5-f80445acd5a3dadef24aa209168452a3d97cc326-0.76.1/data.json"}
[22:29:33.879] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.Y9q0N7bpAZ/Listeners","SHELL":"/bin/bash","DISPLAY":"/private/tmp/com.apple.launchd.uyP4ANk79T/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Users/chuachen/Desktop/other/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-ssh-askpass-e44141fcbbf0c3bb757fd7f91a842d799c7cb6af.sock"}
[22:29:33.880] Spawned 17813
[22:29:34.003] > local-server-1> Spawned ssh, pid=17817
[22:29:34.006] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[22:29:35.655] stderr> Authenticated to remote-server-name-1 ([1.8.2.1]:22).
[22:29:36.357] > ready: 58c9ab92
[22:29:36.539] > Linux 3.10
[22:29:36.539] Platform: linux
[22:29:36.705] > /bin/bash
[22:29:36.709] Shell: bash
[22:29:36.894] > 58c9aab79825: running
[22:29:36.920] > Acquiring lock on /users/chuachen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/vscode-remote-lock.chuachen.f80445acd5a3dadef24aa209168452a3d97cc326
[22:29:36.923] > Found existing installation at /users/chuachen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326...
> Checking /users/chuachen/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log and /users/chuachen/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.pid for a running server
[22:29:36.924] > Looking for server with pid: 20220
[22:29:36.953] > Starting server with command... /users/chuachen/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/users/chuachen/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log" < /dev/null
> printenv:
**[22:29:36.960] > Removing old logfile at /users/chuachen/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log
[22:29:36.961] stderr> -bash: line 497: /users/chuachen/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.token: cannot overwrite existing file
[22:29:37.062] > Spawned remote server: 44271
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[22:29:37.062] stderr> -bash: line 513: /users/chuachen/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.pid: cannot overwrite existing file**
[22:29:37.085] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> 58c9aab79825: start
> webUiAccessToken====
> listeningOn==41368==
> osReleaseId==rhel==
> arch==x86_64==
> tmpDir==/run/user/615227==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==117==
> connectionToken==a1111111-a111-111a-aaa1-a1111a1aaaaa==
> 58c9aab79825: end
[22:29:37.086] Received install output: 
webUiAccessToken====
listeningOn==41368==
osReleaseId==rhel==
arch==x86_64==
tmpDir==/run/user/615227==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==117==
connectionToken==a1111111-a111-111a-aaa1-a1111a1aaaaa==

[22:29:37.086] Remote server is listening on 41368
[22:29:37.086] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":41368},"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","tmpDir":"/run/user/615227","platform":"linux","connectionToken":"a1111111-a111-111a-aaa1-a1111a1aaaaa"},"serverStartTime":117,"installUnpackCode":""}
[22:29:37.087] Persisting server connection details to /Users/chuachen/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-466bc7f5-f80445acd5a3dadef24aa209168452a3d97cc326-0.76.1/data.json
[22:29:37.089] Starting forwarding server. localPort 57284 -> socksPort 57280 -> remotePort 41368
[22:29:37.090] Forwarding server listening on 57284
[22:29:37.090] Waiting for ssh tunnel to be ready
[22:29:37.093] Tunneled 41368 to local port 57284
[22:29:37.093] Resolved "ssh-remote+remote-server-name-1" to "127.0.0.1:57284"
[22:29:37.094] [Forwarding server 57284] Got connection 0
[22:29:37.098] ------




[22:29:37.114] [Forwarding server 57284] Got connection 1
[22:29:37.266] Failed to set up socket for dynamic port forward to remote port 41368: Socket closed. Is the remote port correct?
**[22:29:37.284] Failed to set up socket for dynamic port forward to remote port 41368: Socket closed. Is the remote port correct?**
```

**Comment by tanhakabir** [comment] 2022-03-16 18:05
Are you able to manually delete the .token file as the user you ssh into? It's odd the script seems to think you don't have sufficient permissions.

Do you have anything special det up in your .bashrc file?

**Comment by chuachen** [comment] 2022-03-17 02:08
tried delete the .token file, also tried remove all .vscode-server, still didn't work.
there is no any suspect the .bashrc.
I also tried re-gen the ssh key. My MAC laptop can access remote-server, vscode also can ssh the remote-server.
also tried re-install Remote-SSH in my MAC laptop and upgrade the vscode client version in my MAC laptop. 
Any service or server running in the remote-server I need to re-install/restart besides remove the dir .vscode-server?
all file in vscode-server has been recreated, why I have not permissions?

**Comment by tanhakabir** [comment] 2022-03-17 17:48
Just to clarify are you able successfully run `rm /users/chuachen/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.token` from your shell on the remote with the same logged in user?

**Comment by chuachen** [comment] 2022-03-18 01:51
Thanks tanhakabir.

Yes, I can. 
vscode client can "ssh remote-server-name" successfully, but finally, it cannot take the token?

CHUACHEN-MAC:~ chuachen$  ssh remote-server-name

remote-server$  rm ~/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.token 
remote-server$ 
remote-server$   exit
logout
Connection to remote-server-name closed.
CHUACHEN-MAC:~ chuachen$

**Comment by chuachen** [comment] 2022-03-18 02:11
From the vscode log, vscode client can "ssh remote-server-name" successfully, but why vscode cannot takeover the token?
[09:50:36.576] stderr> **Authenticated** to remote-server-name ([Server_IP]:22).

Can we try this way to check if vscode can read and write in the remote server? if we can, please tell me how to do it in vscode.
echo "hello" > ~/.vscode-server/tmp
ls -la ~/.vscode-server/tmp
cat ~/.vscode-server/tmp

**Comment by tanhakabir** [comment] 2022-03-21 18:29
> Thanks tanhakabir.
> 
> Yes, I can. vscode client can "ssh remote-server-name" successfully, but finally, it cannot take the token?
> 
> CHUACHEN-MAC:~ chuachen$ ssh remote-server-name
> 
> remote-server$ rm ~ / .vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.token remote-server$ remote-server$ exit logout Connection to remote-server-name closed. CHUACHEN-MAC:~ chuachen$

Sorry could you try to delete the file not through the vscode client but yourself manually in a shell?

**Comment by chuachen** [comment] 2022-03-22 00:34
> > Thanks tanhakabir.
> > Yes, I can. vscode client can "ssh remote-server-name" successfully, but finally, it cannot take the token?
> > CHUACHEN-MAC:~ chuachen$ ssh remote-server-name
> > remote-server$ rm ~ / .vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.token remote-server$ remote-server$ exit logout Connection to remote-server-name closed. CHUACHEN-MAC:~ chuachen$
> 
> Sorry could you try to delete the file not through the vscode client but yourself manually in a shell?

I tried that delete the file in another shell not in vscode. didn't work.
Actually, I don't know how to keep the remote server shell in vscode.
Do you know how to keep the shell in vscode?
if yes, I'd like to try below commands:
1. who
2. echo "hello" > ~/.vscode-server/tmp
3. ls -la ~/.vscode-server/tmp
4. cat ~/.vscode-server/tmp

**Comment by tanhakabir** [comment] 2022-03-22 19:42
It sounds like you have some weird permissions issues with the files generated by the server. I can't troubleshoot any further until you're able to resolve why you can't ssh into your remote through another shell and delete the token file. 

If you can get the connecting user able to do that in a separate shell then we can troubleshoot further how to get VS Code working.

**Comment by chuachen** [comment] 2022-03-23 01:20
Hi tanhakabir,
Sorry, no, you have not got my point. let me clarify it.
I am able to ssh remote server in another shell and deleted it.
and then use vscode to connect the remote server, the result is the same. vscode can ssh to the remote server, and can create the token, but also failed to overwrite it.
Thanks very much!

**vscode log:**

[09:15:12.576] stderr> **Authenticated** to remote-server-name ([Server_IP]:22).
[09:15:13.531] Platform: linux
[09:15:13.697] > /bin/bash
[09:15:13.698] Shell: bash

> printenv:
>     MANPATH=:/usr/share/man:/usr/man
>     SHELL=/bin/bash

[09:15:13.927] stderr> rm: cannot remove '/users/chuachen/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.token': No such file or directory
[09:15:13.928] stderr> -bash: line 497: /users/chuachen/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.token: cannot overwrite existing file
[09:15:14.041] > Removing old logfile at /users/chuachen/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log
> Spawned remote server: 45593
> Waiting for server log...

**Comment by chuachen** [comment] 2022-03-24 00:25
Hi tanhakabir,
Is it a new like Remote-SSH extension?
Could you guide me how to download and use it?
I cannot open the link in Chrome and Safari with error msg "This site can’t be reached".

**Comment by tanhakabir** [comment] 2022-03-24 00:29
Sorry try this link: https://1drv.ms/u/s!Art4fdsu4NidiWiyheVXXPwlIsW_ which should let you download a vsix.

Then you can uninstall the Remote SSH extension you already have installed on VS Code and use the side menu to install this vsix instead:
![image](https://user-images.githubusercontent.com/12758612/159818375-3437cd2e-e95c-4088-b26e-25f603a32a21.png)

**Comment by chuachen** [comment] 2022-03-24 00:57
Hi tanhakabir,
still cannot access the link.
Is it in onedrive?
I cannot access onedrive currently https://onedrive.live.com.
Could you please share it in another way?

**Comment by tanhakabir** [comment] 2022-03-24 16:07
[remote-ssh-0.76.101.vsix.zip](https://github.com/microsoft/vscode-remote-release/files/8343329/remote-ssh-0.76.101.vsix.zip)
 
Try this?

**Comment by chuachen** [comment] 2022-03-24 21:51
Hi tanhakabir,
I can download this and install it.  but got below error message, looks there is syntax error.

[05:36:02.511] stderr> Authenticated to remote-server-name ([IP]:22).
[05:36:03.418] Platform: linux
[05:36:03.586] > /bin/bash
[05:36:03.601] Shell: bash
[05:36:03.601] Creating bash subshell inside "bash"
[05:36:03.769] > bash version:  4.2.46(2)-release
[05:36:03.818] > bash version:  4.2.46(2)-release
[05:36:03.868] > bash version:  4.2.46(2)-release
[05:36:03.921] > bash version:  4.2.46(2)-release
[05:36:03.951] > Spawned remote server: 
> Waiting for server log...
[05:36:03.951] stderr> bash: line 513: syntax error near unexpected token `|'
[05:36:03.951] stderr> bash: line 513: `	$VSCH_SERVER_SCRIPT --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown $PORT_FLAG $TELEMETRY $SERVER_LISTEN_FLAG $EXTENSIONS --connection-token-file $VSCH_TOKENFILE &>| "$VSCH_LOGFILE" < /dev/null &'
[05:36:03.951] stderr> -bash: line 5: : No such file or directory
[05:36:03.951] stderr> cat: : No such file or directory
[05:36:03.980] stderr> cat: : No such file or directory
[05:36:03.981] > Waiting for server log...
[05:36:04.013] stderr> cat: : No such file or directory
[05:36:04.014] > Waiting for server log...
[05:36:11.952] stderr> bash: elapsed: command not found
[05:36:11.952] stderr> -bash: line 23: syntax error near unexpected token `}'
[05:36:11.952] stderr> -bash: line 23: `}'
[05:36:11.953] stderr> Transferred: sent 18632, received 30420 bytes, in 9.4 seconds
[05:36:11.953] stderr> Bytes per second: sent 1973.7, received 3222.3
[05:36:11.954] > local-server-1> ssh child died, shutting down
[05:36:11.959] Local server exit: 0
[05:36:11.959] Received install output: local-server-1> Spawned ssh, pid=62728
OpenSSH_8.6p1, LibreSSL 2.8.3
debug1: Server host key: ssh-ed25519 SHA256:ppWeZGPpoDi0IxEPnQH/AcbJdAxgoziI97JlKJo

Waiting for server log...
bash: elapsed: command not found
-bash: line 23: syntax error near unexpected token `}'
-bash: line 23: `}'
Transferred: sent 18632, received 30420 bytes, in 9.4 seconds
Bytes per second: sent 1973.7, received 3222.3
local-server-1> ssh child died, shutting down

[05:36:11.960] Failed to parse remote port from server output
[05:36:11.962] Resolver error: Error: 
	at Function.Create (/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:586041)
	at Object.t.handleInstallOutput (/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:584693)
	at Object.e [as tryInstallWithLocalServer] (/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:625037)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:644074
	at async Object.t.withShowDetailsEvent (/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:647821)
	at async /Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:623509
	at async b (/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:620015)
	at async Object.t.resolveWithLocalServer (/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:623124)
	at async Object.t.resolve (/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:645431)
	at async /Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/extension.js:1:722864

**Comment by tanhakabir** [comment] 2022-03-24 22:02
What does the top part of your logs look like?

**Comment by chuachen** [comment] 2022-03-24 22:06
Please check this, thanks.

[05:43:23.423] Log Level: 2
[05:43:23.427] remote-ssh@0.76.101
[05:43:23.427] darwin x64
[05:43:23.435] SSH Resolver called for "ssh-remote+remote-server-name", attempt 1
[05:43:23.437] "remote.SSH.useLocalServer": true
[05:43:23.437] "remote.SSH.path": undefined
[05:43:23.438] "remote.SSH.configFile": undefined
[05:43:23.438] "remote.SSH.useFlock": true
[05:43:23.439] "remote.SSH.lockfilesInTmp": false
[05:43:23.439] "remote.SSH.localServerDownload": auto
[05:43:23.439] "remote.SSH.remoteServerListenOnSocket": false
[05:43:23.443] "remote.SSH.showLoginTerminal": true
[05:43:23.444] "remote.SSH.defaultExtensions": []
[05:43:23.444] "remote.SSH.loglevel": 2
[05:43:23.444] "remote.SSH.enableDynamicForwarding": false
[05:43:23.444] "remote.SSH.enableRemoteCommand": false
[05:43:23.445] "remote.SSH.serverPickPortsFromRange": {}
[05:43:23.445] "remote.SSH.serverInstallPath": {}
[05:43:23.475] SSH Resolver called for host: remote-server-name
[05:43:23.475] Setting up SSH remote "remote-server-name"
[05:43:23.483] Acquiring local install lock: /var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-remote-ssh-466bc7f5-install.lock
[05:43:23.487] Looking for existing server data file at /Users/chuachen/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-466bc7f5-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.101/data.json
[05:43:23.487] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[05:43:23.494] Install and start server if needed
[05:43:23.501] PATH: /anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin
[05:43:23.502] Checking ssh with "ssh -V"
[05:43:23.516] > OpenSSH_8.6p1, LibreSSL 2.8.3

[05:43:23.520] askpass server listening on /var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-ssh-askpass-2b328f4314bb76b3b9986eabd7d6dc1a1bf0ea04.sock
[05:43:23.520] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-ssh-askpass-78a353299af5c39c67ed3ead740e024dc68fc1a1.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53040","-o","ConnectTimeout=15","remote-server-name"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/chuachen/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-466bc7f5-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.101/data.json"}
[05:43:23.520] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.TRTgxwFKro/Listeners","SHELL":"/bin/bash","DISPLAY":"/private/tmp/com.apple.launchd.1gcoID378l/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Users/chuachen/Desktop/other/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/chuachen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.101/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/24/jwj8bhzd0w93k16zvr6fkvxc0000gn/T/vscode-ssh-askpass-2b328f4314bb76b3b9986eabd7d6dc1a1bf0ea04.sock"}
[05:43:23.523] Spawned 64361
[05:43:23.746] > local-server-1> Spawned ssh, pid=64365
[05:43:23.782] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3

**Comment by tanhakabir** [comment] 2022-03-25 17:36
Is this your whole log? I don't see any error or ending on it

**Comment by chuachen** [comment] 2022-03-26 02:55
Hi tanhakabir,

First time using your version remote-ssh-0.76.101.vsix.zip, I got above error.
Then I tried version switch to v0.76.1 and Remote-SSH to v0.77.2022031115 Pre-Release.
and then switch version to release version, then switch back.
In the end, it can work now without any error!
looks we can close this case now.

**Comment by msis** [comment] 2022-03-26 03:21
I had the same problem, but after I deleted `.vscode-server` it says `python: command not found`.
This is the full content of `.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log`:
```
[REDACTED]/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server: line 10: python: command not found
usage: dirname string [...]
usage: dirname string [...]
[REDACTED]/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server: line 13: /node: No such file or directory
```

and indeed `python` went missing, but `python3` is there. (`python` is supposed to be symlinked to `python3`).

Still didn't find a solution,

**Comment by tanhakabir** [comment] 2022-03-29 18:25
@chuachen >then switch back.

Which version are you using now that works for you?

**Comment by tanhakabir** [comment] 2022-03-29 18:26
@msis I believe your issue is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6442 and will be fixed in Insiders currently and will be fixed in stable when stable releases later this week

**Closed by tanhakabir** 2022-03-29 18:27 UTC
Labels: bug, ssh

**Comment by chuachen** [comment] 2022-03-30 04:48
VSCode, Version: 1.65.2
Remote-SSH,  v0.77.2022031115
Remote-SSH: Editing Configuration Files,  v0.76.1
Thanks again!!!
