### ISSUE TITLE
`code` `-r` in one integrated terminal reloads all open windows to the same remote connection

### ISSUE THREAD

**Issue by RuggMatt** [microsoft/vscode-remote-release#6956] opened 2022-07-15 17:32 UTC
- VSCode Version: 
  ```
  Version: 1.70.0-insider (user setup)
  Commit: 1cd90cceddf3c413673963ab6f154d2ff294b17c
  Date: 2022-07-15T05:16:39.110Z
  Electron: 18.3.5
  Chromium: 100.0.4896.160
  Node.js: 16.13.2
  V8: 10.0.139.17-electron.0
  OS: Windows_NT x64 10.0.22622
  ``
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: SSH
<details>
  <summary>Logs</summary>

```
[11:30:14.536] Log Level: 2
[11:30:14.538] remote-ssh@0.84.0
[11:30:14.538] win32 x64
[11:30:14.575] SSH Resolver called for "ssh-remote+matt-work", attempt 1
[11:30:14.575] "remote.SSH.useLocalServer": false
[11:30:14.576] "remote.SSH.showLoginTerminal": false
[11:30:14.576] "remote.SSH.remotePlatform": {"matt-work":"linux"}
[11:30:14.577] "remote.SSH.path": undefined
[11:30:14.577] "remote.SSH.configFile": undefined
[11:30:14.577] "remote.SSH.useFlock": true
[11:30:14.577] "remote.SSH.lockfilesInTmp": false
[11:30:14.578] "remote.SSH.localServerDownload": auto
[11:30:14.578] "remote.SSH.remoteServerListenOnSocket": false
[11:30:14.578] "remote.SSH.showLoginTerminal": false
[11:30:14.578] "remote.SSH.defaultExtensions": []
[11:30:14.578] "remote.SSH.loglevel": 2
[11:30:14.579] "remote.SSH.enableDynamicForwarding": true
[11:30:14.579] "remote.SSH.enableRemoteCommand": false
[11:30:14.580] "remote.SSH.serverPickPortsFromRange": {}
[11:30:14.580] "remote.SSH.serverInstallPath": {}
[11:30:14.624] SSH Resolver called for host: matt-work
[11:30:14.625] Setting up SSH remote "matt-work"
[11:30:14.634] Using commit id "1cd90cceddf3c413673963ab6f154d2ff294b17c" and quality "insider" for server
[11:30:14.640] Install and start server if needed
[11:30:14.649] Checking ssh with "ssh -V"
[11:30:14.720] > Op
[11:30:14.722] > enSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[11:30:14.728] Running script with connection command: ssh -T -D 61727 "matt-work" bash
[11:30:14.733] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:30:15.903] >  * keychain 2.8.5 ~ http://www.funtoo.org
>  * Found existing ssh-agent: 525
> ]0;C:\WINDOWS\System32\cmd.exe * Known ssh key: /home/matt/.ssh/id_rsa
[11:30:15.903] Got some output, clearing connection timeout
[11:30:15.984] > 13407e8a0bac: running
> Acquiring lock on /home/matt/.vscode-server-insiders/bin/1cd90cceddf3c413673963ab6f154d2ff294b17c/vscode-remote-lock.matt.1cd90cceddf3c413673963ab6f154d2ff294b17c
> Found existing installation at /home/matt/.vscode-server-insiders/bin/1cd90cceddf3c413673963ab6f154d2ff294b17c...
> Checking /home/matt/.vscode-server-insiders/.1cd90cceddf3c413673963ab6f154d2ff294b17c.log and /home/matt/.vscode-server-insiders/.1cd90cceddf3c413673963ab6f154d2ff294b17c.pid for a running server
> Looking for server with pid: 5577
[11:30:16.036] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status on port 41303 with wget
> 13407e8a0bac: start
> SSH_AUTH_SOCK==/tmp/ssh-XXXXXXaeGza2/agent.524==
> DISPLAY====
> webUiAccessToken====
> listeningOn==41303==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==111aaa1a-111a-1aaa-a111-1a111aa111a1==
> 13407e8a0bac: end
[11:30:16.037] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-XXXXXXaeGza2/agent.524==
DISPLAY====
webUiAccessToken====
listeningOn==41303==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==111aaa1a-111a-1aaa-a111-1a111aa111a1==

[11:30:16.038] Remote server is listening on 41303
[11:30:16.038] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":41303},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-XXXXXXaeGza2/agent.524","display":"","tmpDir":"/tmp","platform":"linux","connectionToken":"111aaa1a-111a-1aaa-a111-1a111aa111a1"},"installUnpackCode":""}
[11:30:16.041] Starting forwarding server. localPort 61734 -> socksPort 61727 -> remotePort 41303
[11:30:16.043] Forwarding server listening on 61734
[11:30:16.043] Waiting for ssh tunnel to be ready
[11:30:16.045] [Forwarding server 61734] Got connection 0
[11:30:16.046] Tunneled 41303 to local port 61734
[11:30:16.047] Resolved "ssh-remote+matt-work" to "127.0.0.1:61734"
[11:30:16.047] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-XXXXXXaeGza2/agent.524" "/tmp/vscode-ssh-auth-sock-608293157"
[11:30:16.047] Using cwd: vscode-remote://ssh-remote%2Bmatt-work/
[11:30:16.047] Remote extension host environment: {"SSH_AUTH_SOCK":"/tmp/vscode-ssh-auth-sock-608293157"}
[11:30:16.048] > 
[11:30:16.061] ------

[11:30:16.078] [Forwarding server 61734] Got connection 1
[11:30:16.190] [Forwarding server 61734] Got connection 2
[11:30:18.588] "Update SSH_AUTH_SOCK" terminal command done
```
</details> 

Steps to Reproduce:
Similar to #6875 
1. Have two different projects open over the same SSH connection (e.g. two different windows connected to the same SSH host but open in different folders) 
2. In one of the window's integrated terminal, type `code -r <some_other_folder>` to reuse that window to reopen that window in the new folder 
3. **Expected**: Only that window reloads. **Actual**: Both windows will reload  

<!-- Check to see if the problem is general, with a specific extension, or only happens when remote -->
Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

<!-- If your issue only appears in Codespaces, please visit: https://github.com/github/feedback/discussions/categories/codespaces-feedback -->

**Comment by bpasero** [comment] 2022-08-02 12:25
Duplicate of https://github.com/microsoft/vscode/issues/121926

**Closed as completed by bpasero** 2022-08-02 12:25 UTC
Labels: ssh
