### ISSUE TITLE
Remote Ssh - The process tried to write to a nonexistent pipe.

### ISSUE THREAD

**Issue by simonz130** [microsoft/vscode-remote-release#1398] opened 2019-09-11 01:58 UTC
On Windows 10 build 1803, I tried to connect to remote ssh server (debian linux).
I created config file at c:\users\%username%\.ssh\config with the following content:
```
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host devshell-vm-XXX.cloudshell.dev
    HostName devshell-vm-XXX.cloudshell.dev
    IdentityFile c:\Users\HERE_IS_USERNAME\.ssh\ssh-key
    User HERE_IS_USERNAME@devshell-vm-XXX.cloudshell.dev
    Port 6000    
```
And then tried *Remote-SSH: Connect to Host*
![image](https://user-images.githubusercontent.com/32641282/64662170-4c7d2500-d3fc-11e9-9f59-5c18a7ea8e99.png)

This is the output from *Remote -SSH*
```
[01:51:25.089] remote-ssh@0.46.0
[01:51:25.089] win32 x64
[01:51:25.091] SSH Resolver called for "ssh-remote+devshell-vm-cc3f64ee-a9b2-467a-b864-bc2a230b5141.cloudshell.dev", attempt 1
[01:51:25.091] SSH Resolver called for host: devshell-vm-cc3f64ee-a9b2-467a-b864-bc2a230b5141.cloudshell.dev
[01:51:25.091] Setting up SSH remote "devshell-vm-XXX.cloudshell.dev"
[01:51:25.289] Using commit id "3db7e09f3b61f915d03bbfa58e258d6eee843f35" and quality "stable" for server
[01:51:25.360] Testing ssh with ssh -V
[01:51:28.059] ssh exited with code: 0
[01:51:28.059] Got stderr from ssh: OpenSSH_7.9p1, OpenSSL 1.0.2k  26 Jan 2017
[01:51:28.060] Running script with connection command: ssh -D 61273 devshell-vm-XXX.cloudshell.dev bash
[01:51:28.078] Install and start server if needed
[01:51:28.556] > 
[01:51:28.556] Got some output, clearing connection timeout
[01:51:50.322] > ssh: connect to host devshell-vm-XXX.cloudshell
> .dev port 22: Connection timed out
> The process tried to write to a nonexistent pipe.
> 
[01:51:50.581] "install" terminal command done
[01:51:50.581] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[01:51:50.581] Received install output: The process tried to write to a nonexistent pipe.
[01:51:50.582] The process tried to write to a nonexistent pipe
[01:51:50.582] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"OfflineError"},"measures":{"resolveAttempts":1,"retries":1}}
[01:51:50.583] ------
```
It seems that it uses this command to connect:
```
ssh -D 59574 devshell-vm-XXX.cloudshell.dev bash
```
Which means that it doesn't respect "Port" setting (6000 instead of default 22)
While I tried this command using cmd it worked:
```
ssh -t  -i C:\Users\USER_NAME\.ssh\ssh-key THIS_IS_USERNAME@devshell-vm-XXX.cloudshell.dev -p 6000 DEVSHELL_PROJECT_ID=YYY bash
```

Why isn't remote ssh extension respecting the port on Windows? I tried the same thing on Linux and it worked.

**Comment by Xachman** [comment] 2019-09-12 01:20
Im pretty sure that ssh -D <port number>  does not have anything to do with the port you are using to connect on.   SSH has some really cool dynamic application port forwarding feature they are taking advantage of here.  I'm having the same issue now with a host I predefined and was working before.   Suddenly I started getting the "Could not establish connection to "<host>". The process tried to write to a nonexistent pipe." error too.

**Comment by Xachman** [comment] 2019-09-14 21:25
Ok so my issue was not the exactly the same as yours but I'll tell you how I resolved it.   I found that ssh in cmd prompt on windows was not OpenSSH-Win64 it was some ssh installation in chocolatey/bin.   So I moved that PATH entry under the one for OpenSSH-Win64 and it worked again.   Since your Host and Hostname are the same its hard to tell what exactly is wrong.  But if say its not reading whats in your .ssh/config like it was for me it could be that its using the wrong ssh program.

**Comment by roblourens** [comment] 2019-09-18 03:53
You might have to name your ssh config differently than the actual HostName. I'm not sure, try that.

**Comment by craigpestell** [comment] 2019-09-18 11:20
You cannot use "localhost" for a HostName in your configuration.  I had the same error and changing localhost to a different name fixed it for me.

**Comment by simonz130** [comment] 2019-09-21 00:26
Thanks folks for suggestions.

My ssh client in the path is this: c:\windows32\openssh

I renamed the host to be different from hostname and not "localhost" - didn't help.

**Comment by craigpestell** [comment] 2019-09-21 03:49
Have you tried running the exact command the script is running? `ssh -D 61273 devshell-vm-XXX.cloudshell.dev bash`

You can check for ports listening for a connection on the server with `lsof -i :<port>`.
Check that your Windows firewall isn't blocking the port.  Maybe try with with the firewall disabled.
Can you ping the destination?
You can attempt to telnet from windows to the destination machine using the hostname & port, gleaning info from any messages there.
Check your linux firewall and selinux permissions.  You can perform a network scan from linux with nmap. `sudo nmap -O <hostname>`

**Comment by Xachman** [comment] 2019-09-21 12:21
@simonz130 When you change the host what was the output?  this `ssh -D 59574 devshell-vm-XXX.cloudshell.dev bash`  should have changed to `ssh -D 59574 <newhost> bash`.

**Comment by simonz130** [comment] 2019-10-10 00:59
I checked that the server side is listening for incoming connection - I was able to connect to it from a linux machine and also from macOS. It doesn't work only on Windows.

This is what I try:
```
>ssh -t -i C:\Users\MY_USERNAME\.ssh\google_compute_engine zeltser@devshell-vm-XXXXXXXXX.cloudshell.dev -p 6000 DEVSHELL_PROJECT_ID=MY_PROJECT_ID bash
```

And this is what I get back:
```
CreateProcessW failed error:2
ssh_askpass: posix_spawn: No such file or directory
Host key verification failed.
```

**Comment by roblourens** [comment] 2019-10-10 01:41
Is the `SSH_ASKPASS` environment variable set in your environment?

**Comment by simonz130** [comment] 2019-10-11 21:01
Yeah, SSH_ASKPASS is set to a unix path.
After doing a bit more investigation, I see that there are multiple ssh clients on my PATH:
1) corporate version of SSH
2) OpenSSH

I have an ssh config that if connecting using the corporate version of ssh, it works. However when I use Remote SSH extension for VS Code, it shows that the connection is being made using OpenSSH - even though it's lower priority on PATH.

Is there a way to require Remote SSH extension to use an SSH version that I want?

This is the output I get when connecting using remote ssh:
```
[13:36:54.479] remote-ssh@0.47.1
[13:36:54.479] win32 x64
[13:36:54.481] SSH Resolver called for "ssh-remote+cloud-shell", attempt 1
[13:36:54.481] SSH Resolver called for host: cloud-shell
[13:36:54.481] Setting up SSH remote "cloud-shell"
[13:36:54.567] Using commit id "88f15d17dca836346e787762685a40bb5cce75a8" and quality "stable" for server
[13:36:54.568] Testing ssh with ssh -V
[13:36:54.725] ssh exited with code: 0
[13:36:54.725] Got stderr from ssh: OpenSSH_7.9p1, OpenSSL 1.0.2k  26 Jan 2017
[13:36:54.729] Running script with connection command: ssh -T -D 57519 cloud-shell bash
[13:36:54.735] Install and start server if needed
[13:36:54.743] Terminal shell path: C:\Windows\System32\cmd.exe
[13:36:55.092] > 
[13:36:55.093] Got some output, clearing connection timeout
[13:36:56.735] > ssh: Could not resolve hostname cloud-shell: Name or service not known
> The process tried to write to a nonexistent pipe.
> 
[13:36:56.987] "install" terminal command done
[13:36:56.988] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[13:36:56.988] Received install output: The process tried to write to a nonexistent pipe.
[13:36:56.988] Resolver error: The process tried to write to a nonexistent pipe
[13:36:56.989] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"OfflineError","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","gotUnrecognizedPrompt":"0","remoteInConfigFile":"1"},"measures":{"resolveAttempts":1,"retries":1}}
[13:36:56.990] ------

[13:37:41.095] ConfigFileWatcher: start watching file:///c%3A/Users/MY_USER_NAME/.ssh/config
[13:37:41.095] ConfigFileWatcher: adding save listener
[13:37:41.095] ConfigFileWatcher: adding close listener
[13:37:41.132] ConfigFileWatcher: closing walkThrough:/c%3A/Users/MY_USER_NAME/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D

```

**Comment by Xachman** [comment] 2019-10-11 21:29
But you can say to cloud-shell in cmd?

**Comment by simonz130** [comment] 2019-10-11 21:43
Yes, I can.

In CMD, I do this:
```
ssh -v -t -p 6000 -i C:\Users\MY_USERNAME\.ssh\MY_KEY_NOT_PUTTY_GENERATED MY_USERNAME@devshell-vm-XXX.cloudshell.dev bash -l
```

This works fine.
However if I specify the config file to use
```
ssh -v -t -F c:\users\MY_USERNAME\.ssh\config bash
```
It fails, saying that it can't connect using port 22 (even though the config explicitly states to use a different port:
```
Host cloud-shell
  User MY_USERNAME
  HostName devshell-vm-XXX.cloudshell.dev
  Port 6000
  IdentityFile C:\Users\MY_USERNAME\.ssh\MY_KEY
```

**Comment by Xachman** [comment] 2019-10-11 22:06
Can you run:

ssh cloud-shell

With nothing else from the cmd?

**Comment by Xachman** [comment] 2019-10-12 01:34
@simonz130  basically if your host configuration is working correctly then you should be able to run `ssh cloud-shell` and then the port, hostname, user, and identity file is all set.  No other command matters. My guess is that ssh is not working correctly on your system.  In the first case your error was `ssh: connect to host devshell-vm-XXX.cloudshell
> .dev port 22: Connection timed out
> The process tried to write to a nonexistent pipe.`
you mistakenly assumed that it was reading your config values because the HostName and the Host were the same.  In this new case you have a Host that is different than the HostName.  
`> ssh: Could not resolve hostname cloud-shell: Name or service not known
> The process tried to write to a nonexistent pipe.
> `
Now the error changes since it cant even find a Host for cloud-shell. No DNS will find that so its not even able to get to the point were it would timeout on requesting the default port of 22.  If you look at what I said before probably its using the wrong ssh command.  I'm going to leave room for being wrong but I'm pretty sure this is the case based on all the information you have posted.

**Comment by Jasata** [comment] 2019-11-08 12:46
I had the same error after I reinstalled my remote Debian. Solution was as simple as deleting .ssh/known_hosts from my local machine and reconnecting (Notice that you have to accept the ID).

I have no explanations why that was a problem to begin with or why deleting known_hosts (getting rid of the warning about changed ID) solved it, but for me it did.

Easy to try, if that helps you....

**Comment by roblourens** [comment] 2019-11-12 22:40
I think it's clear that in @simonz130 it is not using the correct config file. Maybe the wrong ssh binary is being used in cmd as well. We can keep debugging but I'll close this issue.

**Closed by roblourens** 2019-11-12 22:40 UTC
Labels: needs-more-info

**Comment by murillopaula** [comment] 2019-12-11 23:14
Just for the record, I did hit this same problem and I had to use the workaround proposed by @Jasata Thanks! Might be worth looking into it.

>  had the same error after I reinstalled my remote Debian. Solution was as simple as deleting .ssh/known_hosts from my local machine and reconnecting

**Comment by Xachman** [comment] 2019-12-11 23:25
@murillopaula This would probably just need some sort of clear notifications that the known host check has failed.  In @Jasata case the os was reinstalled changing the host key and invalidating connections to the same ip or hostname when the known host check happened since the old host key was stored on his local computer.  This situation seems less complex than what @simonz130 and I experienced that only seems to affect windows computers since mac and linux only ever have one implementation of ssh on them.  It may be worth opening a new issue about known_hosts.   This however is not related at all to the original posters problem.

**Comment by murillopaula** [comment] 2019-12-12 00:25
thanks @Xachman unfortunately I do not have a clear reproduction script for the "could not establish connection to the process tried to write to a nonexistent pipe" error message I got when trying to connect to my remote machine. I was connecting fine to a remote machine but when I tried to add new ones I always got that error, no matter what. Tried changing the remote-ssh extension vscode config "Show Login Terminal" to on, different SSH keys and even with different remote machines.

**Comment by Xachman** [comment] 2019-12-12 01:02
@murillopaula what does when I tried to add new ones mean?  known_hosts is a pretty simple file that just holds host keys to verify that you are connecting to the same machine you connected to before.  I would have to assume you couldn't ssh into these machines without vscode either.  Were you able to ssh outside of vscode?

**Comment by murillopaula** [comment] 2019-12-12 01:30
Yes, I was able to ssh outside of vscode each time I tested @Xachman

And sorry let me clarify: I was not able to ssh to remote machines other than the first one I ssh'd into with vscode. I was getting the "could not establish connection to the process tried to write to a nonexistent pipe" each time I tried to ssh to other remote machines. I changing the remote-ssh extension vscode config "Show Login Terminal" to "on", I tried to generate different SSH keys and I tried with different remote machines but I could only SSH to my first remote machine that I ssh'd with vscode.

Each time I tried to ssh with vscode I could ssh outside vscode

**Comment by Xachman** [comment] 2019-12-12 02:00
Alright @murillopaula glad that seemed to fix your issue.  Looks like you made a lot of other changes as well there.  In @Jasata it was a reinstall of the whole os using a connection he probably previously established.  Your case isn't that clear.  It's odd if you could connect with ssh outside of vscode that removing the known_hosts file would suddenly fix ssh for vscode. Having the logs would be beneficial for a clearer picture of whats going on there.

**Comment by umuchlish** [comment] 2019-12-13 04:43
Got the issue this morning with VS-Code using following config .ssh/config
Host local-vm-ubuntu18
    HostName machine.local
    User myaccount

Problem:
* VS-Code: The process tried to write to a nonexistent pipe!
* CMD: ssh myaccount@machine.local > Bad owner or permissions on C:\\Users\\myaccount/.ssh/config

Solution:
Windows-explorer: go to C:\\Users\\myaccount/.ssh/config > right click: 
* Properties > Security > Advanced > Disable Inheritance -> Remove all inherited permissions from this object > OK
* Under user and group > Edit > add myaccount [RWM] > OK

Now I am able to working on remote machine, no need to reinstall everything.

**Comment by MagicLegend** [comment] 2019-12-24 14:38
To leave another note for future reference (mostly to myself, might help others with it):

This could be because:
- The used public key is not in `authorized_keys` of the remote
- Bug #18 is occurring ([fix later in said issue](https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777))
- Some other misspelling in the config file
- Verify that the box you're trying to jump towards will accept you (just ssh to the jumpbox)

Note that this error is thrown even when there are other errors from the jumpbox. This has thrown me off before; so make sure that vscode (or cmd) can connect to the jumpbox. If not; the issue might actually be in the logs (rejected pubkey for example). Make sure to thoroughly read the log vscode gives.
