### ISSUE TITLE
Config wizard sometimes stuck

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#2865] opened 2020-04-28 12:19 UTC
re #2844

Sorry, no good steps (hopefully yet)

* sometimes selecting "Add Dev Container Config Files" doesn't to anything
* sometimes "Show All Definition" doesn't to anything (see attached recording)

[Screen Recording 2020-04-28 at 14.16.49.mov.zip](https://github.com/microsoft/vscode-remote-release/files/4545642/Screen.Recording.2020-04-28.at.14.16.49.mov.zip)

**Comment by egamma** [comment] 2020-11-04 17:04
Cannot reproduce closing

**Closed by egamma** 2020-11-04 17:04 UTC
