### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by soundnotation** [microsoft/vscode-remote-release#5010] opened 2021-05-06 14:31 UTC
I updated to the most recent version today. After that, my search functionality using VSCode Remote is simply endlessly loading every time I start a new search from my folder. I'm on Windows 10 and my SSH target is a linux VM.
![image](https://user-images.githubusercontent.com/23723634/117315386-f0e09480-ae87-11eb-8aa8-f1adcb625ab8.png)
(note the "loading animation segment" repeating forever)
I don't know where I have to look for errors in this case, since the output windows doesn't register anything useful.
My VSCode version is as follows:

Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

 Note: I can do everything else with remote.

**Comment by soundnotation** [comment] 2021-05-06 15:02
Update: also "jump" functionalities (e.g. opening a class when ctrl-clicking on its name), search file by name and git functionalities (GitLens, Git Blame, Git History) not working. Git is not recognizing any repository.

**Comment by roblourens** [comment] 2021-05-06 15:29
It seems like the problem is just that everything in the extension host is not working. Can you open and save files and use the terminal?

Could you check the `Log (Remote Extension Host)` output channel for useful output?

**Comment by soundnotation** [comment] 2021-05-06 15:46
Log window tells me this (repeatedly):
```
[2021-05-06 17:45:42.856] [renderer1] [info] [remote-connection][ExtensionHost][6aea0…][reconnect] resolving connection...
[2021-05-06 17:45:42.859] [renderer1] [info] [remote-connection][ExtensionHost][6aea0…][reconnect] connecting to 127.0.0.1:64380...
[2021-05-06 17:45:43.237] [renderer1] [info] [remote-connection][ExtensionHost][6aea0…][reconnect] reconnected!
[2021-05-06 17:45:57.641] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[2021-05-06 17:46:03.242] [renderer1] [info] [remote-connection][ExtensionHost][6aea0…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
```

**Comment by soundnotation** [comment] 2021-05-06 15:49
I don't see any Log (Remote Extension Host). Only Log (Extension Host)

**Comment by soundnotation** [comment] 2021-05-06 16:06
I can confirm that I can edit and save files. Searching them requires typing in part of the (or the full) path within the directory, with minor problems (e.g. underscores cannot be avoided while searching for a file with underscores in its name. Don't know if this is so by default though).

**Comment by soundnotation** [comment] 2021-05-06 16:10
@roblourens FYI, I report also the output of Log (Extension Host). There's no evident error there though.
```
[2021-05-06 18:07:29.671] [exthost] [info] extension host started
[2021-05-06 18:07:29.697] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"},"activationEvent":"onResolveRemoteAuthority:ssh-remote"}
[2021-05-06 18:07:29.697] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension
[2021-05-06 18:07:35.802] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-05-06 18:07:35.802] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/***/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-05-06 18:07:35.814] [exthost] [info] ExtensionService#_doActivateExtension alefragnani.project-manager {"startup":true,"extensionId":{"value":"alefragnani.project-manager","_lower":"alefragnani.project-manager"},"activationEvent":"*"}
[2021-05-06 18:07:35.814] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/***/.vscode/extensions/alefragnani.project-manager-12.1.0/dist/extension
[2021-05-06 18:07:35.819] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.sublime-keybindings {"startup":true,"extensionId":{"value":"ms-vscode.sublime-keybindings","_lower":"ms-vscode.sublime-keybindings"},"activationEvent":"*"}
[2021-05-06 18:07:35.820] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/***/.vscode/extensions/ms-vscode.sublime-keybindings-4.0.9/dist/extension.js
[2021-05-06 18:07:42.420] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers {"startup":true,"extensionId":{"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"},"activationEvent":"workspaceContainsTimeout:.devcontainer/devcontainer.json,.devcontainer.json"}
[2021-05-06 18:07:42.420] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/***/.vscode/extensions/ms-vscode-remote.remote-containers-0.177.0/dist/extension/extension
[2021-05-06 18:07:42.490] [exthost] [info] eager extensions activated
[2021-05-06 18:07:42.500] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onStartupFinished"}
[2021-05-06 18:07:42.500] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/***/.vscode/extensions/ms-vscode-remote.remote-wsl-0.56.1/dist/extension
```

**Comment by abernix** [comment] 2021-05-06 19:23
I am also experiencing this on VSCode 1.56.0 (macOS client, Ubuntu 18.04 LTS host).

```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0
```

I can reliably fix it by going back to v1.55.2 ([link](https://code.visualstudio.com/updates/v1_55), in case it's useful to anyone else), and it also happens on the latest Insiders.

Precisely like @soundnotation, I **do not** have a _Log (Remote Extension Host)_ option on v1.56.0 (which I can easily find on v1.55.2). 🤔 

On the remote, I've removed and re-installed `~/.vscode-server`, for good measure.  The whole file tree is loaded and I can browse through those fine, but Search doesn't work.  It seems to be reconnecting every 30 seconds, according to the _Log (Window)_:

```
[2021-05-06 22:10:17.937] [renderer1] [info] [remote-connection][ExtensionHost][b1a85…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-05-06 22:10:17.937] [renderer1] [info] [remote-connection][ExtensionHost][b1a85…][reconnect] resolving connection...
[2021-05-06 22:10:17.938] [renderer1] [info] [remote-connection][ExtensionHost][b1a85…][reconnect] connecting to 127.0.0.1:50464...
[2021-05-06 22:10:17.938] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 1/6. invoking socketFactory.connect().
[2021-05-06 22:10:18.061] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 2/6. socketFactory.connect() was successful.
[2021-05-06 22:10:18.062] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 3/6. sending AuthRequest control message.
[2021-05-06 22:10:18.120] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 4/6. received SignRequest control message.
[2021-05-06 22:10:18.121] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 5/6. sending ConnectionTypeRequest control message.
[2021-05-06 22:10:18.172] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 6/6. handshake finished, connection is up and running after 235 ms!
[2021-05-06 22:10:18.173] [renderer1] [info] [remote-connection][ExtensionHost][b1a85…][reconnect] reconnected!
[2021-05-06 22:10:38.182] [renderer1] [info] [remote-connection][ExtensionHost][b1a85…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-05-06 22:10:38.182] [renderer1] [info] [remote-connection][ExtensionHost][b1a85…][reconnect] resolving connection...
[2021-05-06 22:10:38.183] [renderer1] [info] [remote-connection][ExtensionHost][b1a85…][reconnect] connecting to 127.0.0.1:50464...
[2021-05-06 22:10:38.183] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 1/6. invoking socketFactory.connect().
[2021-05-06 22:10:38.301] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 2/6. socketFactory.connect() was successful.
[2021-05-06 22:10:38.301] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 3/6. sending AuthRequest control message.
[2021-05-06 22:10:38.353] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 4/6. received SignRequest control message.
[2021-05-06 22:10:38.354] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 5/6. sending ConnectionTypeRequest control message.
[2021-05-06 22:10:38.403] [renderer1] [trace] [remote-connection][ExtensionHost][b1a85…][reconnect][127.0.0.1:50464] 6/6. handshake finished, connection is up and running after 221 ms!
[2021-05-06 22:10:38.404] [renderer1] [info] [remote-connection][ExtensionHost][b1a85…][reconnect] reconnected!
```

Also, here's a slightly redacted version of my _SSH - Remote_ log:

```
[21:47:19.516] Log Level: 2
[21:47:19.517] remote-ssh@0.65.4
[21:47:19.517] darwin x64
[21:47:19.518] SSH Resolver called for "ssh-remote+playground", attempt 1
[21:47:19.518] "remote.SSH.useLocalServer": true
[21:47:19.519] "remote.SSH.path": undefined
[21:47:19.519] "remote.SSH.configFile": undefined
[21:47:19.519] "remote.SSH.useFlock": true
[21:47:19.519] "remote.SSH.lockfilesInTmp": false
[21:47:19.519] "remote.SSH.localServerDownload": auto
[21:47:19.520] "remote.SSH.remoteServerListenOnSocket": false
[21:47:19.520] "remote.SSH.showLoginTerminal": false
[21:47:19.520] "remote.SSH.defaultExtensions": []
[21:47:19.520] "remote.SSH.loglevel": 2
[21:47:19.520] SSH Resolver called for host: playground
[21:47:19.520] Setting up SSH remote "playground"
[21:47:19.523] Acquiring local install lock: /var/folders/mq/s5hmqjmx7djftqd_2fqjfn0w0000gn/T/vscode-remote-ssh-playground-install.lock
[21:47:19.535] Looking for existing server data file at /Users/jesse/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-playground-cfa2e218100323074ac1948c885448fdf4de2a7f-0.65.4/data.json
[21:47:19.536] Using commit id "cfa2e218100323074ac1948c885448fdf4de2a7f" and quality "stable" for server
[21:47:19.539] Install and start server if needed
[21:47:19.544] PATH: /Users/jesse/.yarn/bin:/Users/jesse/Library/Python/3.7/bin:/Users/jesse/Library/Python/2.7/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/jesse/.cargo/bin:/usr/local/sbin:/Users/jesse/bin
[21:47:19.544] Checking ssh with "ssh -V"
[21:47:19.552] > OpenSSH_8.1p1, LibreSSL 2.7.3

[21:47:19.558] askpass server listening on /var/folders/mq/s5hmqjmx7djftqd_2fqjfn0w0000gn/T/vscode-ssh-askpass-ff2c5016c881d8be85c58895f39a211a5f415a39.sock
[21:47:19.558] Spawning local server with {"ipcHandlePath":"/var/folders/mq/s5hmqjmx7djftqd_2fqjfn0w0000gn/T/vscode-ssh-askpass-97f4ac0af06379ee9d5e224d0dac3307aaf9b276.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50459","-o","ConnectTimeout=15","playground"],"dataFilePath":"/Users/jesse/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-playground-cfa2e218100323074ac1948c885448fdf4de2a7f-0.65.4/data.json"}
[21:47:19.559] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.z1qfT9ZMP8/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jesse/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/jesse/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/mq/s5hmqjmx7djftqd_2fqjfn0w0000gn/T/vscode-ssh-askpass-ff2c5016c881d8be85c58895f39a211a5f415a39.sock"}
[21:47:19.559] Spawned 67683
[21:47:19.657] > local-server> Spawned ssh: 67697
[21:47:19.661] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[21:47:19.879] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:REDACTED
[21:47:20.267] stderr> Authenticated to playground.host ([xxx.yyy.zzz.aaa]:999).
[21:47:21.535] > ready: 510079007ae4
[21:47:21.585] > Linux 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021
[21:47:21.585] Platform: linux
[21:47:21.794] > 510079007ae4: running
[21:47:21.832] > Acquiring lock on /home/jesse/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/vscode-remote-lock.jesse.cfa2e218100323074ac1948c885448fdf4de2a7f
[21:47:21.837] > Found existing installation at /home/jesse/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f...
> Checking /home/jesse/.vscode-server/.cfa2e218100323074ac1948c885448fdf4de2a7f.log and /home/jesse/.vscode-server/.cfa2e218100323074ac1948c885448fdf4de2a7f.pid for a running server
[21:47:21.851] > Looking for server with pid: 2399
[21:47:21.879] > Found running server...
```


CPUs | Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 64.00GB (18.30GB free)
Process Argv | --crash-reporter-id 983781ca-d1f9-4444-99b3-a509b7611615
Screen Reader | no
VM | 0%



Remote | SSH: playground
-- | --
OS | Linux x64 4.15.0-142-generic
CPUs | Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (8 x 2199)
Memory (System) | 15.66GB (11.71GB free)
VM | 0%


Happy to provide anything more that might be useful from either installation.

**Comment by roblourens** [comment] 2021-05-06 21:16
Do you have any extensions installed on the remote? Is there a difference if you disable them? Is there any output in the `(Remote Server)` log?

Do you see any processes using really high CPU on the remote while this is going on?

**Comment by abernix** [comment] 2021-05-06 22:13
@roblourens No extensions.  No high CPU.  I'd disabled all extensions on the remote with the same results, then went on to make sure there was nothing running `ps wwax | grep .vscode-server`, wiped the remote's `.vscode-server`, reinstalled, same results.  Rebooted the remote box for good measure and did a couple more re-installs.  Everything works completely fine if I re-set it up from 1.55.2 and I can even run both 1.55.2 and 1.60.0 (two versions, one renamed to `Visual Studio Code 1.55.2.app`) at the same time and the `v1.60.0` version will not work.

**Comment by abernix** [comment] 2021-05-06 22:18
Oh, and apologies, I didn't provide the log; nothing jumping out in the _Remote Server_ log, just:

```
[22:16:38] [127.0.0.1][f3e52317][ExtensionHostConnection] The client has reconnected.
[22:16:38] [127.0.0.1][b5c25bb4][ExtensionHostConnection] The client has reconnected.
[22:16:58] [127.0.0.1][f3e52317][ExtensionHostConnection] The client has reconnected.
[22:16:58] [127.0.0.1][b5c25bb4][ExtensionHostConnection] The client has reconnected.
[22:17:18] [127.0.0.1][f3e52317][ExtensionHostConnection] The client has reconnected.
[22:17:18] [127.0.0.1][b5c25bb4][ExtensionHostConnection] The client has reconnected.
```

**Comment by roblourens** [comment] 2021-05-07 00:17
Any ideas @alexdima?

**Comment by soundnotation** [comment] 2021-05-07 08:39
I changed the title to "etensions not working" since I noticed that the extensions tab shows a loading clock:
![image](https://user-images.githubusercontent.com/23723634/117422484-ee317e00-af1f-11eb-88a6-1d07816c1689.png)
 Later on I'll do the same tests as @abernix and let you know the results. Today it's still not working anyway.

**Comment by soundnotation** [comment] 2021-05-07 08:57
I can confirm the previous version is working fine also for me (1.55.2). I'll do further tests later on.

**Comment by soundnotation** [comment] 2021-05-07 12:10
I don't think anything useful regarding the error is reported on the Remote - SSH view.
Just as a reference, I post the log of 1.55.2:
```
[14:05:44.964] Log Level: 2
[14:05:44.970] remote-ssh@0.65.4
[14:05:44.970] win32 x64
[14:05:44.971] SSH Resolver called for "ssh-remote+soundnotation.dev", attempt 1
[14:05:44.971] "remote.SSH.useLocalServer": false
[14:05:44.971] "remote.SSH.showLoginTerminal": false
[14:05:44.972] "remote.SSH.remotePlatform": {"soundnotation.dev":"linux","soundnotation.sk":"linux","soundnotation.prod":"linux"}
[14:05:44.972] "remote.SSH.path": undefined
[14:05:44.972] "remote.SSH.configFile": C:\Users\***\.ssh\config
[14:05:44.972] "remote.SSH.useFlock": true
[14:05:44.972] "remote.SSH.lockfilesInTmp": false
[14:05:44.972] "remote.SSH.localServerDownload": auto
[14:05:44.972] "remote.SSH.remoteServerListenOnSocket": false
[14:05:44.972] "remote.SSH.showLoginTerminal": false
[14:05:44.973] "remote.SSH.defaultExtensions": []
[14:05:44.973] "remote.SSH.loglevel": 2
[14:05:44.973] SSH Resolver called for host: soundnotation.dev
[14:05:44.973] Setting up SSH remote "soundnotation.dev"
[14:05:45.001] Using commit id "cfa2e218100323074ac1948c885448fdf4de2a7f" and quality "stable" for server
[14:05:45.004] Install and start server if needed
[14:05:45.007] Checking ssh with "ssh -V"
[14:05:45.057] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[14:05:45.063] Using SSH config file "C:\Users\***\.ssh\config"
[14:05:45.063] Running script with connection command: ssh -T -D 56841 -F "C:\Users\***\.ssh\config" "soundnotation.dev" bash
[14:05:45.066] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:05:46.972] > b416252df295: running
> ]0;C:\WINDOWS\System32\cmd.exe
[14:05:46.973] Got some output, clearing connection timeout
[14:05:47.060] > Acquiring lock on /home/ubuntu/.vscode-server/bin/cfa2e218100323074ac1948c885448
> fdf4de2a7f/vscode-remote-lock.ubuntu.cfa2e218100323074ac1948c885448fdf4de2a7f   
> Found existing installation at /home/ubuntu/.vscode-server/bin/cfa2e218100323074
> ac1948c885448fdf4de2a7f...
> Checking /home/ubuntu/.vscode-server/.cfa2e218100323074ac1948c885448fdf4de2a7f.l
> og and /home/ubuntu/.vscode-server/.cfa2e218100323074ac1948c885448fdf4de2a7f.pid
>  for a running server
> Looking for server with pid: 5901
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> Checking server status on port 45541 with wget
> b416252df295: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==45541==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==1a11111a-a111-111a-aaa1-aaa1aa11a11a==
> b416252df295: end
[14:05:47.061] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==45541==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==1a11111a-a111-111a-aaa1-aaa1aa11a11a==

[14:05:47.062] Remote server is listening on 45541
[14:05:47.062] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":45541},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"1a11111a-a111-111a-aaa1-aaa1aa11a11a"},"installUnpackCode":""}
[14:05:47.064] Starting forwarding server. localPort 56844 -> socksPort 56841 -> remotePort 45541
[14:05:47.065] Forwarding server listening on 56844
[14:05:47.065] Waiting for ssh tunnel to be ready
[14:05:47.066] Tunneled 45541 to local port 56844
[14:05:47.066] Resolved "ssh-remote+soundnotation.dev" to "127.0.0.1:56844"
[14:05:47.068] [Forwarding server 56844] Got connection 0
[14:05:47.073] ------




[14:05:47.106] [Forwarding server 56844] Got connection 1
[14:05:47.258] [Forwarding server 56844] Got connection 2
```

**Comment by soundnotation** [comment] 2021-05-07 14:17
I removed the entire `~/.vscode-server` and restarted vscode 1.56.0. Extensions were now all uninstalled there. Tried to reinstall one extension and it failed (it was just installed locally, but not on the environment).
Installing the extension on another environment I have access too **works**.
I'm wondering where the difference can be, since, as I already mentioned, 1.55.2 works perfectly.

**Comment by soundnotation** [comment] 2021-05-07 14:41
Tried also to install 1.56.0 as system setup (previously I had only user setup), but the behavior is the same, unfortunately.

**Comment by raurfang** [comment] 2021-05-10 08:41
Managed to trace the issue to `weasel-pageant` running from `.zshrc`:
```bash
eval $(/mnt/c/ProgramData/chocolatey/lib/weasel-pageant.portable/tools/weasel-pageant -r)
```
Removing this line from `.zshrc` / `.bashrc` fixed the issues.

**Comment by abernix** [comment] 2021-05-17 08:48
@raurfang Glad that fixed it for you! Your dilemma seems like it must be distinct from the situation that I'm encountering, as I'm not running on WSL or Arch.

**Comment by abernix** [comment] 2021-05-27 08:17
I've just tried the latest version of VS Code and the problem still persists.  Therefore, I'm still constrained to staying at 1.55.2.  In addition to the details I provided above, is there any additional information I can provide to help debug this?

I'll re-echo @roblourens' request above and see if @alexdima has any idea?

**Comment by alexdima** [comment] 2021-06-14 13:18
Before launching the extension host process, we have a piece of code that tries to read the shell environment variables. We have an [ongoing issue](https://github.com/microsoft/vscode-remote-release/issues/5129) where, by process of elimination, the only thing that makes sense is that reading the shell environment variables never completes. That looks very similar to what @raurfang mentioned in https://github.com/microsoft/vscode-remote-release/issues/5010#issuecomment-836377459 . I've pushed a change which will be in tomorrow's insiders build where we timeout after 10s, and proceed launching the extension host despite not managing to resolve the shell environment variables. This will print as an error to the log `Could not resolve shell environment within 10 seconds. Proceeding without shell environment...`.

@abernix It would be very helpful if you can try with tomorrow's insiders.

Otherwise, the one notable change that occurred in `1.56` was [the Electron update](https://code.visualstudio.com/updates/v1_56#_electron-12-update). We keep our server nodejs version in sync with the nodejs version of Electron, so that [has bumped the server version of nodejs to `14.16.0`](https://github.com/microsoft/vscode/blob/054a9295330880ed74ceaedda236253b4f39a335/remote/.yarnrc#L2) and [it used to be `12.18.3` before](https://github.com/microsoft/vscode/blob/3c4e3df9e89829dce27b7b5c24508306b151f30d/remote/.yarnrc#L2).

**Comment by abernix** [comment] 2021-07-14 21:31
@alexdima Hey! Thanks for the detail and clarity.  I've been busy 😅 and on holiday 🌴 but am back 😊 and can report... **latest Insiders works**! 🕺 

In particular, here's my _About_:

```
Version: 1.59.0-insider (Universal)
Commit: 9520f0a515e7e24802c92f885a0efb242fca3831
Date: 2021-07-14T05:15:58.215Z (15 hrs ago)
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0
```

Furthermore, as you indicated would be the case, the _Log (Remote Server)_ log prints:

```
[2021-07-14 21:26:41.825] [remoteagent] [error] [resolve shell env] Could not resolve shell environment within 10 seconds. Proceeding without shell environment...
[2021-07-14 21:26:41.826] [remoteagent] [error] getUnixShellEnvironment#error An unknown error occurred. Please consult the log for more details.
```

Certainly seems like there might be more to unpack here, particularly as to what's throwing a wrench into its attempts to read those, but I don't immediately have any idea what might be causing the snafu.  (Probably a fair deal of unwinding my profile files to sort it out, but I can try and get around to this.)

**Comment by alexdima** [comment] 2021-08-19 09:09
Thank you for the reply. I will optimistically close this issue now.

**Closed by alexdima** 2021-08-19 09:09 UTC
Labels: ssh, needs more info

**Comment by soundnotation** [comment] 2021-08-19 16:59
I can confirm everything works on 1.59.0.
