### ISSUE TITLE
GPG commit signing still broken

### ISSUE THREAD

**Issue by jrcasso** [microsoft/vscode-remote-release#5527] opened 2021-08-29 11:28 UTC
- VSCode Version: 1.59.1
- Local OS Version: Windows 10 - 19042.804
- Remote OS Version: Debian GNU/Linux 11
- Remote Extension/Connection Type: Docker
- Logs:
```
error: gpg failed to sign the data
fatal: failed to write commit object
```

Steps to Reproduce:

1. Configure GPG for commit signing locally
2. Attempt to commit from inside a devcontainer environment.

`gpg` is installed in the container. I see that the VS Code Server does GPG related installation actions, but it's still not working.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

---

I see that there are several issues related to this that are consistently closed by the same developer, but this has been an issue for me for several months. It seems hasty to close them - please look into this.

**Comment by chrmarti** [comment] 2021-08-30 06:46
Could you attach the complete log after trying to sign a commit? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by dave-holland** [comment] 2021-10-08 17:40
@chrmarti  I'm having a similar problem.

VSCode Version: 1.61.0
Local OS Version: macOS 12.0 beta 9 (21A5543b)
Remote OS Version: Debian GNU/Linux 11
Remote Extension/Connection Type: Docker

<details>
<summary>Logs (from <code>Remote-Containers: Show Container Log</code>)</summary>
<pre>
[145 ms] Remote-Containers 0.202.1 in VS Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea).
[145 ms] Start: Resolving Remote
[147 ms] Setting up container for folder or workspace: /Users/dave/Developer/Playgrounds/Python
[148 ms] Start: Check Docker is running
[148 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[265 ms] Server API version: 1.41
[288 ms] Start: Run: git rev-parse --show-cdup
[296 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/dave/Developer/Playgrounds/Python --filter label=vsch.quality=stable
[410 ms] Start: Run: docker inspect --type container a7d3e758faa0
[532 ms] Start: Starting container
[532 ms] Start: Run: docker start a7d3e758faa0085279ed3ff43207905762de9429a752e6fcc96cbfdd86f64116
[1454 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/dave/Developer/Playgrounds/Python --filter label=vsch.quality=stable
[1583 ms] Start: Run: docker inspect --type container a7d3e758faa0
[1692 ms] Start: Inspecting container
[1692 ms] Start: Run: docker inspect --type container a7d3e758faa0085279ed3ff43207905762de9429a752e6fcc96cbfdd86f64116
[1803 ms] Start: Run in container: /bin/sh
[1804 ms] Start: Run in container: uname -m
[1971 ms] aarch64
[1971 ms] 
[1971 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[1972 ms] PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[1972 ms] 
[1973 ms] Start: Run in container: cat /etc/passwd
[1974 ms] Start: Setup shutdown monitor
[1975 ms] Forking shutdown monitor: /Users/dave/.vscode/extensions/ms-vscode-remote.remote-containers-0.202.1/dist/shutdown/shutdownMonitorProcess /var/folders/b3/9w528n_n3mj354q5kvjmjwjw0000gn/T/vscode-remote-containers-3478f285aafcaf63190689215bdc8fc5c0db985d.sock singleContainer Debug /Users/dave/Library/Application Support/Code/logs/20211008T115840/exthost12/ms-vscode-remote.remote-containers 1633713105842
[1976 ms] Start: Run in container: test -d /root/.vscode-server
[1977 ms] 
[1977 ms] 
[1977 ms] Start: Run in container: test -f /var/vscode-server/.patchEtcEnvironmentMarker
[1978 ms] 
[1978 ms] 
[1978 ms] Start: Run in container: test -f /var/vscode-server/.patchEtcProfileMarker
[1979 ms] 
[1979 ms] 
[1979 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[1980 ms] 
[1980 ms] 
[1980 ms] Exit code 1
[1981 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json
[1982 ms] 
[1982 ms] cat: /root/.vscode-server/data/Machine/settings.json: No such file or directory
[1982 ms] Exit code 1
[1982 ms] 
Support for ARM64 is in preview.

[1982 ms] Start: Run in container: test -d /root/.vscode-server/bin/ee8c7def80afc00dd6e593ef12f37756d8f504ea
[1983 ms] 
[1983 ms] 
[1983 ms] Start: Run in container: test -d /vscode/vscode-server/bin/linux-arm64/ee8c7def80afc00dd6e593ef12f37756d8f504ea
[1984 ms] 
[1984 ms] 
[1984 ms] Start: Run in container: touch '/vscode/vscode-server/bin/linux-arm64/ee8c7def80afc00dd6e593ef12f37756d8f504ea'
[1984 ms] Start: Launching Remote-Containers helper.
[1984 ms] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-4f5e3651b6634e889129b1b3b6bc0c32089aa08b.sock) forwarded to host (/private/tmp/com.apple.launchd.u3CvBphLXe/Listeners).
[1984 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[1985 ms] 
[1985 ms] 
[1999 ms] /Users/dave/.gnupg/S.gpg-agent.extra
[1999 ms] 
[1999 ms] Start: Run in container: gpgconf --list-dir agent-socket
[2002 ms] /root/.gnupg/S.gpg-agent
[2002 ms] 
[2002 ms] Start: Run in container: gpgconf --list-dir homedir
[2004 ms] /root/.gnupg
[2004 ms] 
[2004 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[2006 ms] 
[2006 ms] 
[2006 ms] Exit code 2
[2006 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[2007 ms] userEnvProbe: loginInteractiveShell (default)
[2007 ms] userEnvProbe shell: /bin/bash
[2008 ms] 
[2008 ms] 
[2008 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-4f5e3651b6634e889129b1b3b6bc0c32089aa08b.js' >/tmp/vscode-remote-containers-4f5e3651b6634e889129b1b3b6bc0c32089aa08b.js
[2008 ms] Start: Run: gpgconf --list-dir homedir
[2009 ms] 
[2009 ms] 
[2010 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[2011 ms] 
[2011 ms] 
[2011 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-4f5e3651b6634e889129b1b3b6bc0c32089aa08b.js' >/tmp/vscode-remote-containers-server-4f5e3651b6634e889129b1b3b6bc0c32089aa08b.js
[2016 ms] /Users/dave/.gnupg
[2016 ms] 
[2024 ms] 
[2024 ms] 
[2024 ms] Start: Run in container: # Copy /Users/dave/.ssh/known_hosts to /root/.ssh/known_hosts
[2024 ms] Start: Run in container: /root/.vscode-server/bin/ee8c7def80afc00dd6e593ef12f37756d8f504ea/node /tmp/vscode-remote-containers-server-4f5e3651b6634e889129b1b3b6bc0c32089aa08b.js
[2028 ms] 
[2028 ms] 
[2028 ms] Start: Run in container: gpgconf --list-dir homedir
[2030 ms] /root/.gnupg
[2030 ms] 
[2031 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { /root/.vscode-server/bin/ee8c7def80afc00dd6e593ef12f37756d8f504ea/node /tmp/vscode-remote-containers-4f5e3651b6634e889129b1b3b6bc0c32089aa08b.js $*; }; f' || true
[2037 ms] 
[2037 ms] 
[2037 ms] Start: Run in container: # Test for /root/.gnupg/pubring.kbx and gpg
[2037 ms] Start: Preparing Extensions
[2038 ms] /root/.gnupg/pubring.kbx exists
[2038 ms] 
[2038 ms] Exit code 1
[2038 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.installExtensionsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[2039 ms] 
[2039 ms] 
[2039 ms] Exit code 1
[2039 ms] Start: Run in container: # Test for /root/.gnupg/trustdb.gpg and gpg
[2040 ms] Extensions cache, install extensions: None
[2043 ms] 
[2043 ms] 
[2043 ms] Start: Run in container: test -d /root/.vscode-server/extensionsCache && ls /root/.vscode-server/extensionsCache || true
[2046 ms] denoland.vscode-deno-3.9.1
gencer.html-slim-scss-css-class-completion-1.7.8
glenn2223.live-sass-5.1.0
mrmlnc.vscode-scss-0.10.0
ms-python.python-2021.10.1317843341
ms-python.vscode-pylance-2021.10.0
ms-toolsai.jupyter-2021.9.1001312534
ms-toolsai.jupyter-keymap-1.0.0
ms-toolsai.jupyter-renderers-1.0.3
ms-vscode.cpptools-1.6.0
ms-vscode.live-server-0.2.9
pranaygp.vscode-css-peek-4.2.0
pucelle.run-on-save-1.4.7
rbbit.typescript-hero-3.0.0
rust-lang.rust-0.7.8
serayuzgur.crates-0.5.10
sibiraj-s.vscode-scss-formatter-2.2.4
syler.sass-indented-1.8.18
tamasfe.even-better-toml-0.14.2
vadimcn.vscode-lldb-1.6.8
vscjava.vscode-java-pack-0.18.5
[2046 ms] 
[2046 ms] Start: Run in container: # Copy /Users/dave/.gnupg/trustdb.gpg to /root/.gnupg/trustdb.gpg
[2050 ms] 
[2050 ms] 
[2050 ms] Start: Run in container: test -d /vscode/vscode-server/extensionsCache && ls /vscode/vscode-server/extensionsCache || true
[2050 ms] Start: Run: gpg-connect-agent updatestartuptty /bye
[2053 ms] denoland.vscode-deno-3.9.1
gencer.html-slim-scss-css-class-completion-1.7.8
glenn2223.live-sass-5.1.0
mrmlnc.vscode-scss-0.10.0
ms-python.python-2021.10.1317843341
ms-python.vscode-pylance-2021.10.0
ms-toolsai.jupyter-2021.9.1001312534
ms-toolsai.jupyter-keymap-1.0.0
ms-toolsai.jupyter-renderers-1.0.3
ms-vscode.cpptools-1.6.0
ms-vscode.live-server-0.2.9
pranaygp.vscode-css-peek-4.2.0
pucelle.run-on-save-1.4.7
rbbit.typescript-hero-3.0.0
redhat.java-0.82.0
rust-lang.rust-0.7.8
serayuzgur.crates-0.5.10
sibiraj-s.vscode-scss-formatter-2.2.4
syler.sass-indented-1.8.18
tamasfe.even-better-toml-0.14.2
vadimcn.vscode-lldb-1.6.8
visualstudioexptteam.vscodeintellicode-1.2.14
vscjava.vscode-java-debug-0.36.0
vscjava.vscode-java-dependency-0.18.8
vscjava.vscode-java-pack-0.18.5
vscjava.vscode-java-test-0.32.0
vscjava.vscode-maven-0.34.0
[2053 ms] 
[2053 ms] Extensions cache, link in container: None
[2053 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[2080 ms] Start: Starting VS Code Server
[2080 ms] Start: Run in container: /root/.vscode-server/bin/ee8c7def80afc00dd6e593ef12f37756d8f504ea/server.sh --log debug --force-disable-user-env --use-host-proxy --disable-telemetry --port 0 --extensions-download-dir /root/.vscode-server/extensionsCache --start-server --disable-websocket-compression
[2251 ms] userEnvProbe PATHs:
Probe:     '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Container: '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[2252 ms] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 33551

[2253 ms] Start: Run in container: echo 33551 >'/root/.vscode-server/data/Machine/.devport-ee8c7def80afc00dd6e593ef12f37756d8f504ea'
[2254 ms] 
[2254 ms] 
[2255 ms] Port forwarding for container port 33551 starts listening on local port.
[2255 ms] Port forwarding local port 33551 to container port 33551
[2255 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.onCreateCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.onCreateCommandMarker' ; } 2> /dev/null
[2256 ms] 
[2256 ms] 
[2256 ms] Exit code 1
[2257 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.updateContentCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.updateContentCommandMarker' ; } 2> /dev/null
[2258 ms] 
[2258 ms] 
[2258 ms] Exit code 1
[2258 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.postCreateCommandMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
[2259 ms] 
[2259 ms] 
[2259 ms] Exit code 1
[2259 ms] Start: Run in container: # Test for /root/.gitconfig and git
[2261 ms] /root/.gitconfig exists
[2261 ms] 
[2261 ms] Exit code 1
[2261 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /root/.vscode-server/bin/ee8c7def80afc00dd6e593ef12f37756d8f504ea/node /tmp/vscode-remote-containers-4f5e3651b6634e889129b1b3b6bc0c32089aa08b.js $*; }; f' || true
[2264 ms] Port forwarding connection from 56453 > 33551 > 33551 in the container.
[2264 ms] Start: Run in container: /root/.vscode-server/bin/ee8c7def80afc00dd6e593ef12f37756d8f504ea/node -e 
[2267 ms] 
[2267 ms] 
[2267 ms] Start: Run in container: mkdir -p '/root/.vscode-server/data/Machine' && [ "$(cat '/root/.vscode-server/data/Machine/.postStartCommandMarker' 2>/dev/null)" != '2021-10-08T17:11:47.197541133Z' ] && echo '2021-10-08T17:11:47.197541133Z' > '/root/.vscode-server/data/Machine/.postStartCommandMarker'
[2276 ms] 
[2276 ms] 
[2353 ms] [17:11:48] Extension host agent started.
[2499 ms] [17:11:48] [::ffff:127.0.0.1][1e1883af][ManagementConnection] New connection established.
[2504 ms] Port forwarding connection from 56466 > 33551 > 33551 in the container.
[2504 ms] Start: Run in container: /root/.vscode-server/bin/ee8c7def80afc00dd6e593ef12f37756d8f504ea/node -e 
[2793 ms] [17:11:48] [::ffff:127.0.0.1][3b2083d9][ExtensionHostConnection] New connection established.
[2799 ms] [17:11:48] [::ffff:127.0.0.1][3b2083d9][ExtensionHostConnection] <225> Launched Extension Host Process.
[3445 ms] Start: Run in container: cat /proc/245/environ
</pre>
</details>

`git commit -S` works fine on the host, but in the container I get:
```
error: gpg failed to sign the data
fatal: failed to write commit object
```

Hope this information helps. Let me know if more information is needed!

**Comment by chrmarti** [comment] 2021-10-19 07:53
Ok, let's continue our discussion there. I'm closing this issue as I haven't heard back from @jrcasso. Thanks.

**Comment by codejedi365** [comment] 2021-12-02 05:18
@chrmarti, please reopen as I have experienced this problem and it is not resolved.  I believe I have isolated the issue and it is failing to copy the trustdb.gpg from my local Mac machine into the container.  Scrolling through the container build log this is the entry:

```log
[451224 ms] Start: Run in container: # Copy /Users/username/.gnupg/trustdb.gpg to /home/node/.gnupg/trustdb.gpg
```

I run the command `gpg -k -f /Users/username/.gnupg/trustdb.gpg` to review the database on my Mac and I am able to see all 13 keys that I have.  However, in the container, running the same command while pointing at the supposed copied DB, I get no output (`gpg -k -f /home/node/.gnupg/trustdb.gpg`). 

When I manually add the single public key to the trustdb.gpg in the container, magically `git commit -S` now works as intended.

```sh
# manual copy
# Mac (local machine)
gpg --list-secret-keys # Find PUBLIC_KEY_ID
gpg --export -a PUBLIC_KEY_ID | pbcopy

# In container (Debian/typescript-node)
echo "PASTE_PUBLIC_KEY_FROM_CLIPBOARD" | gpg --import -
```

### Additional context

This is a lengthly writeup of all the troubleshooting the community has done, I did all of these without success.
https://stackoverflow.com/q/61067967/3653630, question is still unanswered/unresolved.

My repository configuration is [here](https://github.com/testcafe-community/eslint-plugin-testcafe-community/tree/dev-env).  

Based on my analysis, I would say that the socket is working fine between the local computer and the container as it is able to request encryption by my private key over the socket (since I never provided the private key to the container).  However, since it can not decrypt the signature via the public key (it doesn't have) then git/gnupg fails to actually sign the commit.

**Comment by chrmarti** [comment] 2021-12-02 08:44
@codejedi365 What is the content of the `~/.gnupg` folder right after rebuilding the container? (`ls -la ~/.gnupg`)

**Comment by codejedi365** [comment] 2021-12-02 13:17
@chrmarti, as requested:

```sh
$ ls -la ~/.gnupg
total 16
drwx------ 2 node node 4096 Dec  2 13:06 .
drwxr-xr-x 1 node node 4096 Dec  2 13:09 ..
srwxr-xr-x 1 node node    0 Dec  2 13:06 S.gpg-agent
-rw-r--r-- 1 node node 1360 Dec  2 13:06 trustdb.gpg
```

Also, I didn't mention before but I'm using the builtin Mac OS GPG tools: `gpg (GnuPG/MacGPG2) 2.2.27`.

```sh
# when I tried to list keys right after the previous command, i got this:
$ gpg --list-keys
gpg: keybox '/home/node/.gnupg/pubring.kbx' created
$ _

# ran it again, got no stdout/stderr
$ gpg --list-keys
$ _
```

**Comment by chrmarti** [comment] 2021-12-03 08:02
What are the files in your local `~/.gnupg` folder? I would have expected the pubring.kbx to be copied over too.

**Comment by codejedi365** [comment] 2021-12-03 14:18
@chrmarti - Looking over this output. It makes sense that a `pubring.kbx` is not copied over since it doesn't exist. Instead it looks like mine uses the `pubring.gpg`.  I can't say I know what all these are but I know i started with `GPG Keychain.app` when diving into GPG keys.

```sh
$ ls -la /Users/username/.gnupg
total 2912
drwx------  20 username  staff     640 Dec  1 22:27 ./
drwxr-xr-x+ 82 username  staff    2624 Dec  1 22:27 ../
-rw-------   1 username  staff       0 Sep 27  2017 .gpg-v21-migrated
drwx------   3 username  staff      96 Dec  3  2017 crls.d/
-rw-------@  1 username  staff      34 Aug 23  2019 dirmngr.conf
-rw-------   1 username  staff      89 Aug  3  2017 gpg-agent.conf
-rw-------@  1 username  staff    9052 Oct 13  2018 gpg.conf
drwx------   4 username  staff     128 Oct 13  2018 openpgp-revocs.d/
drwx------   7 username  staff     224 May 23  2019 private-keys-v1.d/
-rw-------   1 username  staff  701475 Jul 11 17:17 pubring.gpg
-rw-------   1 username  staff     600 Feb 10  2017 random_seed
-rw-------   1 username  staff    2490 Feb 10  2017 secring.gpg
-rw-------   1 username  staff   49152 Sep 22  2018 tofu.db
-rw-------   1 username  staff    1360 Jul 11 17:17 trustdb.gpg
```

**Comment by codejedi365** [comment] 2021-12-23 05:21
@chrmarti, not sure if you or the team have an update for this.  To clarify I am working on Mac OS 11.6, with `gpg (GnuPG/MacGPG2) 2.2.27, libgcrypt 1.8.7`, which came with `GPG Suite 2021.1` I believe (it upgraded over the years).  I still cannot get `Remote - Containers` to include my public keys into the container on the container build which I have diagnosed as being the primary problem.  Whatever socket "magic" is being performed to connect my gpg-agent to the host machine, that is working because as soon as I manually add the public key into the container via `echo "$key" | gpg --import -` it works.

### Not ideal or pretty workaround

See this [Gist](https://gist.github.com/codejedi365/673c24a940824c5f3d73262913cc9079) which details the how I was able to (1) automate the export all non-expired public gpg keys during an `initializeCommand` in `devcontainer.json`, (2) Use Docker to copy the public keys into the container on build, and then (3) perform a `gpg --import` to add **ONLY** the public keys to the container.

### However

Upon further diagnosis, I have come up with the following hypothesis.  GnuPG 2.2 is an intermediate version which supports both the new keybox format (`pubring.kbx`) and the prior `pubring.gpg` + `secring.gpg` formats.  If you do not have a prior config (`~/.gnupg/pubring.gpg`) when importing a new key then the keybox format is used.  If a prior config exists, then is maintains the old pubring.gpg format for compatibility.  I believe VSCode's Extension is only handling the newer keybox format scenario and not the grandfathered-in configuration.  I recommend adding something to the docs informing users to export & re-import their keys into the keybox format, if the developers don't extend support to handle the second possible format of GnuPG.  From the GnuPG docs, it sounds as if the format is legacy and will be phased out but it is unknown when that will be.

### Solution

1. Export all keys
    ```sh
    # REF: https://access.redhat.com/solutions/2115511
    gpg --export --armor > mypubkeys.asc
    gpg --export-secret-keys --armor > myprivatekeys.asc
    gpg --export-ownertrust >otrust.txt
    ```
2. Upgrade to the latest GnuPG (`v2.2.32` as of this post, might not be necessary if at least 2.2)
3. Remove/Copy old configuration folder

   ```sh
   mv ~/.gnupg ~/.gnupg_pre_2.2
   ```

4. Re-import keys which will generate a new `.gnupg` config folder with a keybox formatted pubring file.

   ```sh
   # REF: https://access.redhat.com/solutions/2115511
   gpg --import myprivatekeys.asc
   gpg --import mypublickeys.asc
   gpg --list-secret-keys
   gpg --list-keys
   # optional
   gpg --import-ownertrust otrust.txt
   ```

5. Rebuild container

**Comment by chrmarti** [comment] 2021-12-23 14:01
@codejedi365 Thanks for investigating. I just found similar documentation from GPG: https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration.html.

It looks like copying `pubring.gpg` when it exists should fix this. Will try that.

**Closed** 2021-12-23 14:04 UTC
Labels: bug, containers

**Comment by codejedi365** [comment] 2021-12-24 01:25
@chrmarti, you're welcome. One thought I had that might be more reliable longer term would to mimic part of my gist link above where I outlined a way to export/transfer/import the public keys from gpg directly. This way it would not matter about the underlying gpg file configuration.

**Comment by chrmarti** [comment] 2021-12-24 07:29
There is very little that can go wrong with the file copy. I'm not sure what error conditions there are with the Gist when applying it to the variety of GPG configuration files in use by Remote-Containers users. So for now I think the file copy is the better option as a fix in Remote-Containers. Your Gist can still help others who want to apply it manually. Thanks!

**Comment by chrmarti** [comment] 2022-01-04 19:57
Now available with VS Code Insiders and Remote-Containers 0.210.0.
