### ISSUE TITLE
Unable to open WSL2 session

### ISSUE THREAD

**Issue by pvettori** [microsoft/vscode-remote-release#6087] opened 2021-12-21 08:06 UTC
- VSCode Version: 1.63.2
- Local OS Version: Windows 10 Home ver 1909 (build SO 18363.1556)
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: WSL
- Logs:
```
[2021-12-21 07:52:07.277] Resolving wsl+Ubuntu, resolveAttempt: 1
[2021-12-21 07:52:07.347] Starting VS Code Server inside WSL (wsl2)
[2021-12-21 07:52:07.347] Extension version: 0.63.13
[2021-12-21 07:52:07.347] Windows build: 18363. Multi distro support: available. WSL path support: enabled
[2021-12-21 07:52:07.347] No shell environment set or found for current distro.
[2021-12-21 07:52:08.671] WSL daemon log file: 
[2021-12-21 07:52:08.674] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2021-12-21 07:52:08.861] Probing result: found
[2021-12-21 07:52:08.861] Server install found in WSL
[2021-12-21 07:52:08.863] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 899d46d82c4c95423fb7e10e68eba52050e30ba3 stable .vscode-server 634850172629 --port=0 --use-host-proxy --without-browser-env-var --disable-websocket-compression'
[2021-12-21 07:52:08.971] Setting up server environment: Looking for /home/******/.vscode-server/server-env-setup. Not found.
[2021-12-21 07:52:08.971] WSL version: 5.4.72-microsoft-standard-WSL2 Ubuntu
[2021-12-21 07:52:09.271] WSL-shell-PID: 292
[2021-12-21 07:52:09.271] Node executable: /home/******/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node
[2021-12-21 07:52:09.271] Starting server: /home/******/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/server.sh --connection-secret=/home/******/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/code-server-292-1640073128.token --port=0 --use-host-proxy --without-browser-env-var --disable-websocket-compression
[2021-12-21 07:52:09.271] 
[2021-12-21 07:52:09.271] 
[2021-12-21 07:52:09.271] *
[2021-12-21 07:52:09.271] * Visual Studio Code Server
[2021-12-21 07:52:09.271] *
[2021-12-21 07:52:09.271] * Reminder: You may only use this software with Visual Studio family products,
[2021-12-21 07:52:09.271] * as described in the license https://aka.ms/vscode-remote/license
[2021-12-21 07:52:09.271] *
[2021-12-21 07:52:09.271] 
[2021-12-21 07:52:09.271] Extension host agent listening on 43793
[2021-12-21 07:52:09.271] 
[2021-12-21 07:52:09.271] [08:52:09] Extension host agent started.
[2021-12-21 07:52:09.273] WSL resolver response: ::1:43793
[2021-12-21 07:52:09.273] To debug connection issues, open a local browser on http://[::1]:43793/version
[2021-12-21 07:52:09.273] Using 'wsl2VMAddress' to connect to the VS Code server as configured by setting 'remote.WSL2.connectionMethod'
```

Steps to Reproduce:

1. Open "New WSL Window" by clicking on the left lower corner.
2. The new windows shows the error: `Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)`.

Does this issue occur when you try this locally?
Yes
Does this issue occur when you try this locally and all extensions are disabled?
The issue started since the **Remote - WSL** update 0.63.5

*Note:* The issue is intermittent. I can temporarily fix it by opening a command prompt and restarting WSL with the command `wsl --shutdown`, but the problem shows again on next computer startup. Docker desktop installed and runing on the system.

**Comment by aeschli** [comment] 2022-01-09 17:46
Changing the WSL connection method back to `wslExeProxy` doesn't make a difference?
`"remote.WSL2.connectionMethod": "wslExeProxy",`

**Comment by pvettori** [comment] 2022-01-10 13:54
> Changing the WSL connection method back to `wslExeProxy` doesn't make a difference? `"remote.WSL2.connectionMethod": "wslExeProxy",`

@aeschli 
I tried every setting, but none worked.
At the moment the session works randomly. Sometimes I have to restart WSL, sometimes it just works.
Remote - WSL v0.63.13

**Comment by samytessier** [comment] 2022-01-11 10:22
Having the exact same issue as above, also using docker desktop. Have tried the same steps of reverting versions, changing proxies etc. Everything works in WSL1 but unfortunately docker only supports wsl2 it seems

**Comment by aeschli** [comment] 2024-12-13 10:35
I'm closing this. Unfortunately I can't reproduce. We also no longer have the `connectionMethod` setting.

**Closed by aeschli** 2024-12-13 10:35 UTC
Labels: wsl
