### ISSUE TITLE
Forwarded port request pending forever every now and then

### ISSUE THREAD

**Issue by AndyOGo** [microsoft/vscode-remote-release#3948] opened 2020-11-04 10:25 UTC
- VSCode Version: 1.50.1
- Local OS Version: Microsoft Windows 10 Enterprise
- Remote OS Version: Red Hat Enterprise Linux Server 7.9 (Maipo)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. starting a node server `npm start`
2. Forward the related port, e.g.`localhost:8888`
3. Open in browser
3. Coding for a while, restarting node server, etc.
4. Every now and then requests just get pending, I have no clue why

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Steps to workaround:

Restart VSCode, forward ports again and suddenly requests responding.

**Comment by alexr00** [comment] 2020-11-09 10:32
@AndyOGo where are you seeing this:

> Every now and then requests just get pending, I have no clue why

Is this in the browser you can no longer connect to the local port?

**Comment by alexr00** [comment] 2020-11-09 15:23
Actually, duplicate of https://github.com/microsoft/vscode-remote-release/issues/3678

**Closed by alexr00** 2020-11-09 15:23 UTC
Labels: needs-more-info

**Comment by AndyOGo** [comment] 2020-11-09 18:08
@alexr00 
Indeed, as my original issue description states, I'm working in the browser and I access a server which ports are forwarded to my local machine.
