### ISSUE TITLE
SSH Hangs on Cancel Viewing Large File

### ISSUE THREAD

**Issue by Tony-xy-Liu** [microsoft/vscode-remote-release#6517] opened 2022-03-29 06:54 UTC
Issue Type: <b>Bug</b>

to reproduce:
Have large file on remote ssh
ssh into remote
click on file to open
cancel opening file
now you can't open other files; must restart vs code

vs code should actually cancel file download for viewing, or at least make it non-blocking

Extension version: 0.76.1
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-37-generic snap
Restricted Mode: No
Connection to 'ssh-remote+wss' could not be established
Remote OS version: Linux x64 3.10.0-1160.59.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics (8 x 1400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 2|
|Memory (System)|7.14GB (0.41GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f7d7a5b7-e67a-4b3e-b1b8-2ac0bdda923b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

Connection to 'ssh-remote+wss' could not be established

|Item|Value|
|---|---|
|Remote|SSH: wss|
|OS|Linux x64 3.10.0-1160.59.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E7-4880 v2 @ 2.50GHz (120 x 2500)|
|Memory (System)|1007.58GB (755.85GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid2:30447481
pynewfile477:30450038

```

</details>

**Comment by bpasero** [comment] 2022-03-31 05:04
Duplicate of https://github.com/microsoft/vscode/issues/57585

**Closed by bpasero** 2022-03-31 05:04 UTC
Labels: ssh
