### ISSUE TITLE
Can't connect to windows using ssh server version 8.9+

### ISSUE THREAD

**Issue by c-lai** [microsoft/vscode-remote-release#7272] opened 2022-09-30 22:05 UTC
The issue is similar to #6348, but different.

I was able to SSH to the remote machine (Windows 11) from VScode successfully before, but after some windows updates on the remote machine, SSH doesn't work anymore. The issue is reproducible when I use either a macOS machine or a Ubuntu machine as the local machine.

Now I can SSH to the remote computer from terminal, but fail from VScode. 

- VSCode Version: 1.71.2 (Universal) Commit: 74b1f979648cc44d385a2286793c226e611f59e7
- Local OS Version: macOS 12.6 / Ubuntu
- Remote OS Version: Windows 11 22H2
- Remote Extension/Connection Type: SSH
- Logs: 
```
[17:33:38.860] Log Level: 2
[17:33:38.862] remote-ssh@0.84.0
[17:33:38.862] darwin x64
[17:33:38.868] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224a4152564953227d", attempt 1
[17:33:38.868] "remote.SSH.useLocalServer": true
[17:33:38.869] "remote.SSH.path": undefined
[17:33:38.869] "remote.SSH.configFile": undefined
[17:33:38.869] "remote.SSH.useFlock": true
[17:33:38.869] "remote.SSH.lockfilesInTmp": false
[17:33:38.870] "remote.SSH.localServerDownload": auto
[17:33:38.870] "remote.SSH.remoteServerListenOnSocket": false
[17:33:38.870] "remote.SSH.showLoginTerminal": false
[17:33:38.870] "remote.SSH.defaultExtensions": []
[17:33:38.870] "remote.SSH.loglevel": 2
[17:33:38.871] "remote.SSH.enableDynamicForwarding": true
[17:33:38.871] "remote.SSH.enableRemoteCommand": false
[17:33:38.871] "remote.SSH.serverPickPortsFromRange": {}
[17:33:38.871] "remote.SSH.serverInstallPath": {}
[17:33:38.886] SSH Resolver called for host: JARVIS
[17:33:38.886] Setting up SSH remote "JARVIS"
[17:33:38.888] Acquiring local install lock: /var/folders/sr/0x6g643911z4fv3vjczyj_3r0000gn/T/vscode-remote-ssh-3446c8c4-install.lock
[17:33:38.891] Looking for existing server data file at /Users/changxin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3446c8c4-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0/data.json
[17:33:38.891] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
[17:33:38.894] Install and start server if needed
[17:33:38.897] PATH: /Users/changxin/opt/miniconda3/bin:/Users/changxin/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
[17:33:38.898] Checking ssh with "ssh -V"
[17:33:38.904] > OpenSSH_8.6p1, LibreSSL 3.3.6

[17:33:38.907] askpass server listening on /var/folders/sr/0x6g643911z4fv3vjczyj_3r0000gn/T/vscode-ssh-askpass-ec7620451599a92ba4f83d7d92e59f3e388bc639.sock
[17:33:38.907] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/sr/0x6g643911z4fv3vjczyj_3r0000gn/T/vscode-ssh-askpass-6bc337707a9a28dc416e8ff061535730120eee63.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53531","-o","ConnectTimeout=15","JARVIS"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/changxin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3446c8c4-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0/data.json"}
[17:33:38.907] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.kGS0nenEVs/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.DLms8dN3D7/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/sr/0x6g643911z4fv3vjczyj_3r0000gn/T/vscode-ssh-askpass-ec7620451599a92ba4f83d7d92e59f3e388bc639.sock"}
[17:33:38.908] Spawned 7390
[17:33:39.066] > local-server-1> Spawned ssh, pid=7394
[17:33:39.070] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[17:33:39.157] stderr> debug1: Server host key: ssh-ed25519 SHA256:L2T8ljfD5yYxWCKD8gBgMpnTG7XsUwW98NPXQYaCz+4
[17:33:39.285] stderr> Authenticated to 10.162.37.79 ([10.162.37.79]:22).
[17:33:40.189] stderr> client_loop: send disconnect: Broken pipe
[17:33:40.192] > local-server-1> ssh child died, shutting down
[17:33:40.198] Local server exit: 0
[17:33:40.199] Received install output: local-server-1> Spawned ssh, pid=7394
OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Server host key: ssh-ed25519 SHA256:L2T8ljfD5yYxWCKD8gBgMpnTG7XsUwW98NPXQYaCz+4
Authenticated to 10.162.37.79 ([10.162.37.79]:22).
client_loop: send disconnect: Broken pipe
local-server-1> ssh child died, shutting down

[17:33:40.199] Failed to parse remote port from server output
[17:33:40.201] Resolver error: Error: 
	at g.Create (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at t.handleInstallOutput (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async t.withShowDetailsEvent (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async t.resolveWithLocalServer (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async t.resolve (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[17:33:40.205] ------
```

Does this issue occur when you try this locally?: No

I tried SSH on the remote computer to itself (via IP) using VScode, and it succeeded. 

Thanks

**Comment by fenying** [comment] 2022-10-02 15:30
Same here, this problem occurs since I updated to Bug11 22H2 (Home edition, 22H2, 22621.525), but I get different logs, and it just keep connecting to my SSH server in VBox (archlinux). I could connect to my server using ssh.exe command.

I think this is problem related to **SSH local server**, because it disappear away if I changed `remote.SSH.useLocalServer` to `false`.

```
[23:21:54.550] Log Level: 2
[23:21:54.550] remote-ssh@0.84.0
[23:21:54.551] win32 x64
[23:21:54.562] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22486f6d6553747564696f227d", attempt 1
[23:21:54.562] "remote.SSH.useLocalServer": true
[23:21:54.562] "remote.SSH.path": undefined
[23:21:54.563] "remote.SSH.configFile": undefined
[23:21:54.563] "remote.SSH.useFlock": true
[23:21:54.563] "remote.SSH.lockfilesInTmp": false
[23:21:54.563] "remote.SSH.localServerDownload": auto
[23:21:54.563] "remote.SSH.remoteServerListenOnSocket": false
[23:21:54.563] "remote.SSH.showLoginTerminal": false
[23:21:54.563] "remote.SSH.defaultExtensions": []
[23:21:54.563] "remote.SSH.loglevel": 2
[23:21:54.563] "remote.SSH.enableDynamicForwarding": true
[23:21:54.563] "remote.SSH.enableRemoteCommand": false
[23:21:54.563] "remote.SSH.serverPickPortsFromRange": {}
[23:21:54.563] "remote.SSH.serverInstallPath": {}
[23:21:54.565] SSH Resolver called for host: HomeStudio
[23:21:54.565] Setting up SSH remote "HomeStudio"
[23:21:54.567] Acquiring local install lock: C:\Users\Angus\AppData\Local\Temp\vscode-remote-ssh-6dc9fd9c-install.lock
[23:21:54.568] Looking for existing server data file at c:\Users\Angus\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-6dc9fd9c-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0\data.json
[23:21:54.568] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
[23:21:54.570] Install and start server if needed
[23:21:54.571] Checking ssh with "ssh -V"
[23:21:54.590] > OpenSSH_
[23:21:54.590] > for_Windows_8.6p1, LibreSSL 3.4.3

[23:21:54.592] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[23:21:54.611] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[23:21:54.613] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[23:21:54.615] Got error from ssh: spawn C:\Program Files\Git\usr\bin\ssh.exe ENOENT
[23:21:54.615] Checking ssh with "C:\Program Files (x86)\Git\usr\bin\ssh.exe -V"
[23:21:54.615] Got error from ssh: spawn C:\Program Files (x86)\Git\usr\bin\ssh.exe ENOENT
[23:21:54.616] Checking ssh with "ssh -V"
[23:21:54.632] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[23:21:54.635] Using SSH config file "C:\Users\Angus\.ssh\config"
[23:21:54.635] askpass server listening on \\.\pipe\vscode-ssh-askpass-bd0ed733f80e9849a57374d8bae3798c5188adc2-sock
[23:21:54.635] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-83016d4f0c02d6d01d4aaf39040fd93bc7838437-sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","7099","-F","C:\\Users\\Angus\\.ssh\\config","HomeStudio","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"c:\\Users\\Angus\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-6dc9fd9c-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0\\data.json"}
[23:21:54.635] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\Angus\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.84.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\Angus\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\Angus\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.84.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-bd0ed733f80e9849a57374d8bae3798c5188adc2-sock"}
[23:21:54.643] Spawned 2080
[23:21:54.707] > local-server-1> Spawned ssh, pid=17052
[23:21:54.733] stderr> OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
[23:21:54.749] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:zw+fRhKPWfjAVVXxNoOxBmzkpHfGenDbLDQUBy79QZM
[23:22:11.644] Terminating local server
[23:22:11.650] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\Angus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\Angus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:630527)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[23:22:11.653] ------




[23:22:11.661] Local server exit: null
[23:22:11.669] ------

```

**Comment by c-lai** [comment] 2022-10-02 23:27
> The issue is similar to #6348, but different.
> 
> I was able to SSH to the remote machine (Windows 11) from VScode successfully before, but after some windows updates on the remote machine, SSH doesn't work anymore. The issue is reproducible when I use either a macOS machine or a Ubuntu machine as the local machine.
> 
> Now I can SSH to the remote computer from terminal, but fail from VScode.
> 
> * VSCode Version: 1.71.2 (Universal) Commit: 74b1f979648cc44d385a2286793c226e611f59e7
> * Local OS Version: macOS 12.6 / Ubuntu
> * Remote OS Version: Windows 11 22H2
> * Remote Extension/Connection Type: SSH
> * Logs:
> 
> ```
> [17:33:38.860] Log Level: 2
> [17:33:38.862] remote-ssh@0.84.0
> [17:33:38.862] darwin x64
> [17:33:38.868] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224a4152564953227d", attempt 1
> [17:33:38.868] "remote.SSH.useLocalServer": true
> [17:33:38.869] "remote.SSH.path": undefined
> [17:33:38.869] "remote.SSH.configFile": undefined
> [17:33:38.869] "remote.SSH.useFlock": true
> [17:33:38.869] "remote.SSH.lockfilesInTmp": false
> [17:33:38.870] "remote.SSH.localServerDownload": auto
> [17:33:38.870] "remote.SSH.remoteServerListenOnSocket": false
> [17:33:38.870] "remote.SSH.showLoginTerminal": false
> [17:33:38.870] "remote.SSH.defaultExtensions": []
> [17:33:38.870] "remote.SSH.loglevel": 2
> [17:33:38.871] "remote.SSH.enableDynamicForwarding": true
> [17:33:38.871] "remote.SSH.enableRemoteCommand": false
> [17:33:38.871] "remote.SSH.serverPickPortsFromRange": {}
> [17:33:38.871] "remote.SSH.serverInstallPath": {}
> [17:33:38.886] SSH Resolver called for host: JARVIS
> [17:33:38.886] Setting up SSH remote "JARVIS"
> [17:33:38.888] Acquiring local install lock: /var/folders/sr/0x6g643911z4fv3vjczyj_3r0000gn/T/vscode-remote-ssh-3446c8c4-install.lock
> [17:33:38.891] Looking for existing server data file at /Users/changxin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3446c8c4-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0/data.json
> [17:33:38.891] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
> [17:33:38.894] Install and start server if needed
> [17:33:38.897] PATH: /Users/changxin/opt/miniconda3/bin:/Users/changxin/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
> [17:33:38.898] Checking ssh with "ssh -V"
> [17:33:38.904] > OpenSSH_8.6p1, LibreSSL 3.3.6
> 
> [17:33:38.907] askpass server listening on /var/folders/sr/0x6g643911z4fv3vjczyj_3r0000gn/T/vscode-ssh-askpass-ec7620451599a92ba4f83d7d92e59f3e388bc639.sock
> [17:33:38.907] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/sr/0x6g643911z4fv3vjczyj_3r0000gn/T/vscode-ssh-askpass-6bc337707a9a28dc416e8ff061535730120eee63.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53531","-o","ConnectTimeout=15","JARVIS"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/changxin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3446c8c4-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0/data.json"}
> [17:33:38.907] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.kGS0nenEVs/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.DLms8dN3D7/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/sr/0x6g643911z4fv3vjczyj_3r0000gn/T/vscode-ssh-askpass-ec7620451599a92ba4f83d7d92e59f3e388bc639.sock"}
> [17:33:38.908] Spawned 7390
> [17:33:39.066] > local-server-1> Spawned ssh, pid=7394
> [17:33:39.070] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
> [17:33:39.157] stderr> debug1: Server host key: ssh-ed25519 SHA256:L2T8ljfD5yYxWCKD8gBgMpnTG7XsUwW98NPXQYaCz+4
> [17:33:39.285] stderr> Authenticated to 10.162.37.79 ([10.162.37.79]:22).
> [17:33:40.189] stderr> client_loop: send disconnect: Broken pipe
> [17:33:40.192] > local-server-1> ssh child died, shutting down
> [17:33:40.198] Local server exit: 0
> [17:33:40.199] Received install output: local-server-1> Spawned ssh, pid=7394
> OpenSSH_8.6p1, LibreSSL 3.3.6
> debug1: Server host key: ssh-ed25519 SHA256:L2T8ljfD5yYxWCKD8gBgMpnTG7XsUwW98NPXQYaCz+4
> Authenticated to 10.162.37.79 ([10.162.37.79]:22).
> client_loop: send disconnect: Broken pipe
> local-server-1> ssh child died, shutting down
> 
> [17:33:40.199] Failed to parse remote port from server output
> [17:33:40.201] Resolver error: Error: 
> 	at g.Create (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
> 	at t.handleInstallOutput (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
> 	at Object.e [as tryInstallWithLocalServer] (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
> 	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
> 	at async /Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
> 	at async t.withShowDetailsEvent (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
> 	at async /Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
> 	at async T (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
> 	at async t.resolveWithLocalServer (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
> 	at async t.resolve (/Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
> 	at async /Users/changxin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
> [17:33:40.205] ------
> ```
> 
> Does this issue occur when you try this locally?: No
> 
> I tried SSH on the remote computer to itself (via IP) using VScode, and it succeeded.
> 
> Thanks

I tried SSH from another windows 11 machine, and it succeeded. I guess this issue is due to some incompatibility between OpenSSH, which is used on macOS and Linux, and [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH), which is used on Windows.

**Comment by eleanorjboyd** [comment] 2022-10-13 22:21
Could you figure out which version of the OpenSSH server you have? You are able to add this setting `"remote.SSH.remotePlatform": {
        "YOUR_HOSTNAME": "windows"
}` in user settings file it should apply the workaround.

**Comment by sladiri** [comment] 2022-10-17 21:48
Thanks, that setting fixed the problem.

Also here are the versions of OpenSSH installed on the Windows PC:

Non-working version is:
`OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3`

The working version is:
`OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2`

**Comment by c-lai** [comment] 2022-10-17 22:00
> Could you figure out which version of the OpenSSH server you have? You are able to add this setting `"remote.SSH.remotePlatform": { "YOUR_HOSTNAME": "windows" }` in user settings file it should apply the workaround.

The setting fixed the problem for me as well. Thanks!

**Comment by ysig** [comment] 2022-11-13 22:52
I could perfectly connect to all my ssh connections with visual studio code and now that I updated to windows 11 22H2 it doesn't work. When will this be fixed, it's a crucial issue..?

**Comment by eleanorjboyd** [comment] 2022-11-14 18:44
Hello @ysig, did you try the setting- `"remote.SSH.remotePlatform": { "YOUR_HOSTNAME": "windows" }` and does that fix it for you? We have also added a patch fix for this to our next milestone since it might be a bit before the regression fix is made upstream: https://github.com/microsoft/vscode-remote-release/issues/7519

**Comment by ysig** [comment] 2022-11-15 10:55
Hello @eleanorjboyd. Setting it where? And what should you be the "YOUR_HOSTNAME" tag?

Thanks,
Y

**Comment by eleanorjboyd** [comment] 2022-11-15 17:40
you can put it in your settings.json and that should work and your host name is the name of your remote host you are trying to connect to like this example below of what your ssh config looks like:
_Host dev
    HostName dev.example.com
    User john
    Port 2322_

**Comment by ysig** [comment] 2022-11-16 15:33
Hi @eleanorjboyd! Thank you for your answer. No it doesn't :/ Also my remote host is a linux host not a windows one and even changing that doesn't fix the issue.

**Comment by eleanorjboyd** [comment] 2022-11-16 17:24
@ysig Can you open a new issue for this since we know it is not related to the above fix and is on a different machine type? I will respond to investigate it further there but want to create a new thread to not clutter this one. Thanks!

**Comment by ysig** [comment] 2022-11-16 18:41
What should I log though?

**Comment by eleanorjboyd** [comment] 2022-11-16 18:49
@ysig logs from remote-ssh would be great! You can find them through going to the `output` tab on your server side VS Code then select `remote-ssh` from the dropdown.

**Comment by chadbrewbaker** [comment] 2022-12-10 20:28
Why is this closed? Same issue. Can ssh fine but vscode-remote barfs on a broken pipe. I used @eleanorjboyd  I used @shanselman setup Windows 11 side, https://www.hanselman.com/blog/the-easy-way-how-to-ssh-into-bash-and-wsl2-on-windows-10-from-an-external-machine  I am using vscode 1.74.0 on MacOS M1 Ventura to connect.

**Comment by chadbrewbaker** [comment] 2022-12-10 20:55
I think I fixed it? I disabled use local server and I set remote.SSH.connectTimeout to 60 seconds.

**Comment by eleanorjboyd** [comment] 2022-12-12 15:42
Hello! Could you try steps 2 and 3 of this guide and let me know the outcome? Also could you try increasing your ssh connection timeout to 30 from 15. Thanks!

https://github.com/microsoft/vscode-remote-release/wiki/Debugging-for-Remote-SSH

**Comment by provos** [comment] 2022-12-16 14:51
I just ran into this problem and the solution was to set

`"remote.SSH.useLocalServer": false`

**Comment by eleanorjboyd** [comment] 2023-02-20 03:18
steps to verify:

1. using vscode insiders switch the newest version of the remote-ssh extension
2. have a server that is a windows machine that is running Open-SSH version 8.9 beta (any version 8.6 and up should work but we know this issue shows up on 8.6 and 8.9-beta) https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.9.1.0p1-Beta
3. to install download the zip, run install-sshd which should replace your server (you might have to delete your old sshd instance not totally sure) then start the server
4. you can check your remote openSSH version by connecting using the -v tag with ssh `ssh ____ -v`
5. Now see if you can correctly connect (and check it prompts you for your password a second time, if not you might need to remove the machine type from your json file if it is defined there)

**Closed** 2023-02-21 15:06 UTC
Labels: bug, ssh, verification-needed
