### ISSUE TITLE
Support dev containers through a Remote - Tunnel

### ISSUE THREAD

**Issue by NotAndex** [microsoft/vscode-remote-release#7679] opened 2022-12-10 13:59 UTC
Type: <b>Feature Request</b>

Dear VS Code Team,

Thank you all for your exceptional work. It is highly appreciated.

As-is situation:
I can smoothly connect to a remote VM with the new "Remote - Tunnels" feature. Then I am trying to open a new Dev Container on that VM, but no command palette support is available yet. 

Technically, I am doing the same with a “Remote – SSH” connection to the identical VM, there I get the Dev Container commands recommended in the command palette.
The issue is equivalent to: https://github.com/microsoft/vscode-remote-release/issues/2994

Are there any plans to add this feature (Dev Container through a “Remote – Tunnels” session) in a future release?

Best,
Andi

Extension version: 1.0.0
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by joyceerhl** [comment] 2022-12-13 19:23
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/7705

**Closed by joyceerhl** 2022-12-13 19:23 UTC
Labels: containers

**Comment by jhrmnn** [comment] 2023-01-06 10:31
In principle one can launch a Dev Container manually using the [CLI](https://github.com/devcontainers/cli) and then create the tunnel from within the container, but of course it does create an extra friction, so I'm very much looking forward to have this implemented.
