### ISSUE TITLE
Project and folder settings ignored when opening file from search

### ISSUE THREAD

**Issue by RemiLeb** [microsoft/vscode-remote-release#3660] opened 2020-09-14 14:09 UTC
Issue Type: <b>Bug</b>

Remote Container
Attached to remote container

When attached to a remote container, opening a file through the `search` tab will open the file stand-alone, outside of it's context.
Example: 
* My default encoding is `UTF-8`
* I have a multi-root workspace open, one of which contains `.vscode` folder with a settings defining the encoding `ISO-8899-1`.
* If I open a file on through the file explorer, the encoding is correct (`ISO-8899-1`).
* If I search for any string present in the file and open it through the search tab, the encoding is incorrect (`UTF-8`).
* Also, `File: Reveal Active File in Side Bar` will not highlight the file inside the projet root

Extension version: 0.140.1
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)
OS version: Linux x64 4.15.0-115-generic
Remote OS version: Linux x64 4.14.193-149.317.amzn2.x86_64

**Comment by chrmarti** [comment] 2020-09-15 08:14
This works for me in a simple example. Could you attach your `.code-workspace` file?

**Comment by RemiLeb** [comment] 2020-09-15 15:19
Sure.

workspace.json:
```
{
	"folders": [
		{
			"name": "my-other-project",
			"uri": "vscode-remote://k8s-container/var/www/html/vendor/myvendor/myotherproject"
		},
		{
			"name": "my-main-project",
			"uri": "vscode-remote://k8s-container/var/www/html"
		}
	],
	"settings": {
		"files.exclude": {
			"vendor": true
		},
		"files.watcherExclude": {
			"vendor": true
		}
	}
}
```

/var/www/html/.vscode/settings.json:
```
{
	"files.encoding": "utf8"
}
```

/var/www/html/vendor/myvendor/myotherproject/.vscode/settings.json:
```
{
	"files.encoding": "iso88591"
}
```
Executing a search on "myotherproject"
![image](https://user-images.githubusercontent.com/12417802/93229123-3f4bf200-f744-11ea-870d-cfa8bf9fae65.png)

Obtained when clicking on the search result
-- Note the encoding is UTF-8 instead of iso88591 and breadcrumb shows the file is not part of the project
![image](https://user-images.githubusercontent.com/12417802/93229181-4e32a480-f744-11ea-8a0c-bf9d8b4c5593.png)

Expected result (obtained by clicking on the file in the file explorer on the left:
![image](https://user-images.githubusercontent.com/12417802/93229685-d9ac3580-f744-11ea-86dc-5cd5558ba77c.png)

**Comment by chrmarti** [comment] 2020-09-16 06:02
The URIs in your workspace file are missing part of the authority. When I create one through VS Code I get, as an example:
```json
{
	"folders": [
		{
			"uri": "vscode-remote://k8s-container+podname=k8s-demo+namespace=default+name=node-as-root+image=node:12/root/folder1"
		},
		{
			"uri": "vscode-remote://k8s-container+podname=k8s-demo+namespace=default+name=node-as-root+image=node:12/root/folder2"
		}
	],
	"remoteAuthority": "k8s-container+podname=k8s-demo+namespace=default+name=node-as-root+image=node:12",
	"settings": {}
}
```

Did you handcraft the URIs? Could you retry by creating the workspace using `F1` > `Workspaces: Add Folder to Workspace...` while being attached to the pod? (I just confirmed that with the shorted URIs I can reproduce the problem.)

**Comment by RemiLeb** [comment] 2020-09-16 17:37
Yes, I did change them manually. I guess it might explain the problem I am facing.

I will explain why, but perhaps I should create a new issue about that?

The URIs generated by VSCode are unusable, they have the following format:

`vscode-remote://k8s-container+podname=beige-app-1234bcde-zd6qp+namespace=dev+name=app+image=1234567.dkr.ecr.ca-central-1.amazonaws.com/project-site:dev/var/www/html`

And the files are inaccessible:
![image](https://user-images.githubusercontent.com/12417802/93371767-e1410c80-f820-11ea-9e43-722a53ced01d.png)

Perhaps it would be because of the `/` in the image name?

Also, these URIs are including is that pod name and image name. Those changes at every update, and thus become invalid. Causing the workspaces needs to be recreated after each update. That's why I was happy to see that partial URIs would work in almost every aspect, except the issue reported here.

**Comment by chrmarti** [comment] 2020-09-17 07:33
@aeschli I tried using a workspace file in the container using relative paths, but that only partially works. The terminal opens on the first folder, I can open standalone files, but the Explorer doesn't show the folder contents. Is this expected to work?

![image](https://user-images.githubusercontent.com/9205389/93434464-7ba85b00-f8c8-11ea-9746-3b890f26b728.png)

**Comment by aeschli** [comment] 2020-09-17 08:37
@chrmarti I think you need to use use `path` instead of `uri`.

Having the workspace file inside the container is the recommended way. 
We don't create workspaces with `vscode-remote` uris (only internally for unsaved workspaces)

**Comment by chrmarti** [comment] 2020-09-17 08:44
@aeschli The `vscode-remote` URIs came from saving a workspace (in https://github.com/microsoft/vscode-remote-release/issues/3660#issuecomment-693192073).

@RemiLeb You could use a workspace file inside the container and use relative paths (thanks @aeschli):
```json
{
	"folders": [
		{
			"path": "folder1"
		},
		{
			"path": "folder2"
		}
	]
}
```

**Comment by chrmarti** [comment] 2020-09-17 08:47
@aeschli I saved the workspace locally while being connected to the container, so the workspace file needed at least the remote authority to be self-contained. It could then still use relative paths (which it didn't) I guess.

**Comment by aeschli** [comment] 2020-09-17 08:54
Ok, I see, I wasn't aware of that. The `remoteAuthority` property is not documented and probably not set when saving locally.
I'd rather stick with workspaces only on the remote side and not open another can of worms.

**Comment by RemiLeb** [comment] 2020-09-17 12:48
Thanks to both of you. As @chrmarti suggested, replacing `uri` with `path` in the workspace works exactly as expected and resolves all the problems.

If there is actually an issue, I guess it would be with `Add folder to workspace...` on remote-container, which creates an unusable `uri` entry in the workspace.

**Comment by chrmarti** [comment] 2020-09-17 15:37
The URIs are created when you save the workspace file locally, when you store it in the container the file contains just the relative paths. @aeschli Maybe saving the workspace locally while connected remotely is something you want to disallow in the UI? Moving to you, otherwise good to close. Thanks.

**Comment by RemiLeb** [comment] 2020-09-17 15:54
Could I suggest automatically creating the workspace on the remote, if possible at all?

Here is the usual flow when connecting to a remote container:

1. Attach VSCode to a remote container
2. Click `Add workspace folder...`
3. Enter the path in the dialog
4. Click OK

If you follow this, you will have an "untitled" workspace containing `uri` instead of a `path`. Even if you then save it in the container, it will still contain `uri` and be unsusable as it is.

**Comment by aeschli** [comment] 2020-09-18 07:51
I created https://github.com/microsoft/vscode/issues/106990 to fix the save workspace dialog to be only remote when in a remote window.

**Closed by aeschli** 2020-09-18 07:51 UTC
