### ISSUE TITLE
Connecting to Windows container with non-English locale fails

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vscode-remote-release#2553] opened 2020-03-16 07:12 UTC
_(I was [encouraged](https://github.com/microsoft/vscode-remote-release/issues/2351#issuecomment-599285334) to open a new issue because it's not quite related to the SSH variant of the localization problem. My input there with [recording](https://github.com/microsoft/vscode-remote-release/issues/2351#issuecomment-599251726) and actual [error messages](https://github.com/microsoft/vscode-remote-release/issues/2351#issuecomment-599254180) are there.)_

- VSCode Version: 1.43
- Local OS Version: (Hungarian) Windows Education 1909 (build: 18363.720)
- Remote OS Version: mcr.microsoft.com/windows/servercore:1909 (build: 18362.628)
- Remote Extension/Connection Type: Docker (Remote - Containers version: 0.106.0) 

Steps to Reproduce:

1. Set locale to Hungarian?
2. Connect to a remote?

My concrete image is using this Dockerfile:
```
FROM mcr.microsoft.com/windows/servercore:1909
# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
ADD https://gist.githubusercontent.com/MathiasMagnus/2f34667754769c792bcf10526e0a07b6/raw/88cac3fa5950d5510d9f9566c75f9dc37fe442fd/CppDevelopment.vsconfig C:\TEMP\CppDevelopment.vsconfig

# Install Build Tools excluding workloads and components with known issues.
RUN C:\TEMP\vs_buildtools.exe`
 --quiet`
 --wait`
 --norestart`
 --nocache`
 --installPath C:\Microsoft\VisualStudio\BuildTools`
 --config C:\TEMP\CppDevelopment.vsconfig`
 || IF "%ERRORLEVEL%"=="3010" EXIT 0

# Start developer command prompt with any other commands specified.
ENTRYPOINT ["C:\\Microsoft\\VisualStudio\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat", "&&"]

# Default to PowerShell if no other command specified.
CMD ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
```

Does this issue occur when you try this locally?: No (Connecting to the image going just by the console works fine.
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment] 2020-10-13 12:48
Remote-Containers does not support Windows containers of any locale currently.

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/445

**Closed by chrmarti** 2020-10-13 12:48 UTC
