### ISSUE TITLE
Support rmate or rsub like functionality

### ISSUE THREAD

**Issue by nikhilweee** [microsoft/vscode-remote-release#4037] opened 2020-11-18 01:28 UTC
After being connected to a remote server, VSCode currently supports two ways to open a file/folder.
1. Using the Open menu (`CTRL-O` or `CMD-O`)
2. Using the integrated terminal (`$ code path`)

Integrated terminal is nice, but while developing locally, I often see myself using `$ code path` from an external terminal. It would be great to the use the same workflow for remote development in VSCode. 

Other editors already support this functionality. Textmate has [rmate](https://github.com/textmate/rmate), Sublime has [rsub](https://packagecontrol.io/packages/rsub), Atom has [remote-atom](https://atom.io/packages/remote-atom) and until recently VSCode had a third party [extension](https://marketplace.visualstudio.com/items?itemName=rafaelmaiolla.remote-vscode) to support this feature. It would be great if VSCode supported this as well.

PS: This functionality was also requested in #263 but was not followed up.
PPS: A big thanks for VSCode Remote. It is hands down the best remote development experiece so far.

**Comment by roblourens** [comment] 2020-11-22 22:41
This has been discussed before like in https://github.com/microsoft/vscode-remote-release/issues/2721 and https://github.com/microsoft/vscode-remote-release/issues/1042 and isn't really feasible for us to improve. I guess there is a currently open issue in https://github.com/microsoft/vscode-remote-release/issues/3983 so I'll close this as a dupe of that.

**Closed by roblourens** 2020-11-22 22:41 UTC
Labels: ssh
