### ISSUE TITLE
Custom HISTFILE not being honored

### ISSUE THREAD

**Issue by reediculous456** [microsoft/vscode-remote-release#7083] opened 2022-08-17 17:32 UTC
- VSCode Version: 1.70.1
- Local OS Version: MacOS 12.5
- Remote OS Version: SuSE Linux 12 SP5
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. On server, add `export HISTFILE=/some/path/to_file`
2. ssh into the server through a standard terminal and see the history file location has been changed and `echo $HISTFILE` shows the custom location
3. ssh in using VS Code's integrated terminal and see that `echo $HISTFILE` shows the default location and not the custom one

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment] 2022-08-18 17:33
> export HISTFILE=/some/path/to_file

Are you adding this to your bashrc file?

**Comment by reediculous456** [comment] 2022-08-18 18:15
Sorry, I'm adding it to my .zshrc file since zsh is my default shell

**Comment by tanhakabir** [comment] 2022-08-18 18:30
Ah we use bash for connecting to your remote and spin up shells from bash in VS Code. I believe this might be the issue that you're facing

**Comment by reediculous456** [comment] 2022-08-18 19:00
I just checked and I have the custom HISTFILE variable declared in both my .bashrc and .zshrc and I'm still seeing this behavior

**Comment by tanhakabir** [comment] 2022-08-18 19:25
And you've killed the VS Code Server that was running previously?

**Comment by reediculous456** [comment] 2022-08-18 19:55
Yes, also this was working as intended until recently so most likely a recent plugin update caused this bug

**Comment by tofupup** [comment] 2022-08-26 00:08
I'm seeing this while using a devcontainer where I have zsh as my shell.  It respects the HISTFILE if I rebuild the container without cache, but if I rebuild it using cache, sometimes it will no longer respect the HISTFILE.  Once in this state, the only way I've found to resolve it is a rebuild without cache.

In the devcontainer situation, it seems to be caused by some sort of race between VSCode opening its first shell, and the devcontainer finishing setup (including dotfiles setup), as I notice when HISTFILE isn't working, even the SHELL env variable is set to /bin/bash (though it's definitely in a zsh shell).

Since it's a different issue, I'll open a separate GH issue once I figure out how to consistently recreate it, but wanted to add this data point.

**Comment by sigh** [comment] 2022-08-27 01:04
I'm coming across this as well. It looks like vscode's `shellIntegration-rc.zsh` is resetting `HISTFILE` for some reason: https://github.com/microsoft/vscode/blob/ef7831e9c52d3283a9d309de07da13818a90a910/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh#L27

The pull request that added that line: https://github.com/microsoft/vscode/pull/154300

I'm inferring this from appending `set -x` to the end of `~/.zshrc` and looking at what commands are being run. In my case:

```
+/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh/.zshrc:22> ZDOTDIR=/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh 
+/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh/.zshrc:25> [[ -f /Users/<redacted>/.zsh_history ]]
+/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh/.zshrc:26> HISTFILE=/Users/<redacted>/.zsh_history 
+/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh/.zshrc:32> [ -z 1 ']'
+/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh/.zshrc:36> __vsc_in_command_execution=1 
+/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh/.zshrc:37> __vsc_current_command='' 
+/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh/.zshrc:82> [[ -o NOUNSET ]]
+/var/folders/31/0_3mb7y54s9dk2hztg09lk6r0000gn/T/vscode-zsh/.zshrc:127> add-zsh-hook precmd __vsc_precmd
+add-zsh-hook:15> emulate -L zsh
```

The only work-around for me right now is to delete `~/.zsh_history` and be careful that nothing is recreating it (or delete it every time in `~/.zshrc`).

**Comment by yathaid** [comment] 2022-10-06 07:53
I had shell integration enabled and this bug made the terminal in VS code unusable for me (for at least the past two months) until I stumbled on this issue and realized the root cause. Disabling shell integration solves this.

Breaking user settings in this intrusive manner is ... absurd. I am not sure how more people aren't triggering this bug.

**Comment by reediculous456** [comment] 2022-10-06 13:22
@yathaid Do you know if there is a way to disable shell integration for anyone who SSHs into a server regardless of local config?

**Comment by yathaid** [comment] 2022-10-07 07:15
@reediculous456 uhh not really; I mostly use VSCode just locally.

**Comment by tanhakabir** [comment] 2022-10-07 07:55
cc @roblourens missed assigning this one

**Comment by mimo84** [comment] 2022-10-23 04:53
I had an extra problem, seeing the issue being caused by https://github.com/microsoft/vscode/blob/ef7831e9c52d3283a9d309de07da13818a90a910/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh#L27 checking for the existence of the `.zsh_history` file, I thought to delete such file, however such workaround for some reason I didn't bother to debug, works only once: the next VS Code terminal that you're going to open is going to have the `.zsh_history` recreated causing the issue again, therefore I have for now removed the terminal integration.

**Comment by andrp92** [comment] 2022-12-13 04:00
I am having the exact same problem

**Comment by andrp92** [comment] 2022-12-13 04:24
If this helps anyone (disable terminal integration):

https://github.com/cantino/mcfly/issues/273#issuecomment-1208848236

**Comment by meganrogge** [comment] 2023-01-06 16:41
I believe this has been fixed. Pls let me know if you can still reproduce in a more recent version

**Closed by meganrogge** 2023-01-06 16:41 UTC
