### ISSUE TITLE
A way to specify which user in wsl is used.

### ISSUE THREAD

**Issue by adminy** [microsoft/vscode-remote-release#9144] opened 2023-10-27 13:45 UTC
normally in wsl you do 

`wsl -u root -d NixOS` but with vscode, it picks some default user nixos which doesn't have all the things I have been using with the root user so ... would there be a way to specify -u or maybe a setting I can set for default user?

**Comment by aeschli** [comment] 2023-10-30 08:24
Duplicate of #286

**Closed by aeschli** 2023-10-30 08:24 UTC
Labels: wsl
