### ISSUE TITLE
Close folder doesn't stop container

### ISSUE THREAD

**Issue by ahayzen** [microsoft/vscode-remote-release#304] opened 2019-05-13 22:27 UTC
Close folder doesn't stop the container that open folder in container started.

# What happened

1) Open code-insiders with remote development extension
2) Open a folder in container
3) Notice that the bottom left green area shows the dev container is connected and setup
4) Select File->Close Folder
5) Notice that vscode resets but the bottom left shows that the dev container is still connected. At this stage one is trapped with this container open.

# What I expected to happen

At step 4 for the remote container to be disconnected.

# Workaround

At step 5 manually stop the container in docker, or with the latest code-insiders it appears quitting vscode stops the container. Then a restart works.

# Versions

```
$ lsb_release -rd
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
$ code-insiders --version
1.34.20-insider
57b550c559b945eb9d871dbf2b2e4cb9e31e2551
x64
```

Remote development extension => 0.14.0
Remote - Containers => 0.33.0

**Comment by aeschli** [comment] 2019-06-24 12:44
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/501

There's now a new command `Close Remote Connection` that closes the remote connection by turning the window into a local window.

Close Folder continues to do what it says. Remove the current folder from the workspace (which can result in an empty, remote, workspace)

**Closed by aeschli** 2019-06-24 12:44 UTC
