### ISSUE TITLE
RemoteCommand prevents VsCode Remote SSH from working

### ISSUE THREAD

**Issue by vedantroy** [microsoft/vscode-remote-release#7289] opened 2022-10-05 03:58 UTC
- VSCode Version: 
```
1.71.2
74b1f979648cc44d385a2286793c226e611f59e7
x64
```

- Local OS Version:
```
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
- Remote OS Version:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

- Remote Extension/Connection Type: SSH
- Logs:
- 
```
[23:54:08.115] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22446f636b65725633227d", attempt 5, (Reconnection)
[23:54:08.121] SSH Resolver called for host: DockerV3
[23:54:08.121] Setting up SSH remote "DockerV3"
[23:54:08.125] Acquiring local install lock: /tmp/vscode-remote-ssh-df93c816-install.lock
[23:54:08.129] Looking for existing server data file at /home/vedantroy/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-df93c816-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0/data.json
[23:54:08.131] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
[23:54:08.142] Install and start server if needed
[23:54:08.160] askpass server listening on /run/user/1000/vscode-ssh-askpass-7164e5d393b0e1eacafe8979b8db4f9b97bfb351.sock
[23:54:08.161] Spawning local server with {"serverId":5,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-58a0898cef360d22fee28ea151e0321f075136e6.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","36971","-o","ConnectTimeout=15","DockerV3"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/vedantroy/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-df93c816-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0/data.json"}
[23:54:08.162] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/usr/bin/zsh","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/snap/code/108/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-7164e5d393b0e1eacafe8979b8db4f9b97bfb351.sock"}
[23:54:08.179] Spawned 300855
[23:54:08.344] > local-server-5> Spawned ssh, pid=300863
[23:54:08.348] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
[23:54:08.720] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:MoqTJzzCZHfr0DeKFtdguSFJTHgOtpnvLSdn5Kef744
[23:54:09.293] Got askpass request: {"request":"root@100.105.135.52's password:"}
[23:54:09.293] Showing password prompt
[23:54:09.294] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-e3922f3e4a37e17c61ddc231e349ca490f789e00.sock
[23:54:09.294] Writing password prompt to globalState
[23:54:30.897] Got password response
[23:54:30.897] Interactor gave response: ****
[23:54:30.898] Cleaning up other-window auth server
[23:54:31.058] stderr> Authenticated to 100.105.135.52 ([100.105.135.52]:9002).
[23:54:31.402] > ready: 018d94b25127
[23:54:31.490] > Linux 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022
[23:54:31.491] Platform: linux
[23:54:31.579] > /bin/bash
[23:54:31.579] Shell: bash
[23:54:31.580] Creating bash subshell inside "bash"
[23:54:31.668] > bash version:  5.0.17(1)-release
[23:54:31.716] > bash version:  5.0.17(1)-release
[23:54:31.855] > 018d94b25127: running
[23:54:31.858] > Creating the server install dir failed...
> 018d94b25127: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 018d94b25127: end
[23:54:31.859] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[23:54:31.860] Failed to parse remote port from server output
[23:54:31.860] Terminating local server
[23:54:31.862] Resolver error: Error: 
	at g.Create (/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at t.handleInstallOutput (/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async t.withShowDetailsEvent (/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async t.resolveWithLocalServer (/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async t.resolve (/home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /home/vedantroy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[23:54:31.869] ------




[23:54:31.875] Local server exit: 15
```

Steps to Reproduce:

1. Use the following SSH config

```
Host DockerV3
  HostName 100.105.135.52
  Port 9002
  RemoteCommand su myotheruser
  User root
```
and try to connect to the remote.
This will fail, but if I remote the `RemoteCommand` it will work fine

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by eleanorjboyd** [comment] 2022-10-13 22:27
Hello! This is a duplicate of the following issue which has some workaround and has also been marked as a feature request in our backlog. Thanks! https://github.com/microsoft/vscode-remote-release/issues/690

**Closed by eleanorjboyd** 2022-10-13 22:27 UTC
Labels: ssh
