### ISSUE TITLE
Developing inside a container on a remote Docker host

### ISSUE THREAD

**Issue by RogerYong** [microsoft/vscode-remote-release#1698] opened 2019-06-07 17:09 UTC
I have read [Developing inside a container on a remote Docker host](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host).

Is it feasible that combine the Remote-SSH and Remote-Containers?

Two vscode servers. 

One vscode server runs on remote docker host. Source code, `devcontainer.json` and `Dockerfile` are saved in remote host.

The other runs in container for code intellisense, running and debugging

**Comment by chrmarti** [comment] 2019-10-21 10:12
The only case where we support having a `devcontainer.json` remotely is when starting from a repository on GitHub. Currently only public repositories are supported (#1578), with these you can:
- Check-in the `devcontainer.json` to GitHub.
- Change `docker.host` (and related settings if needed) to connect to the remote Docker daemon.
- `F1` > `Remote-Containers: Open Repository in Container...`
- Specify the GitHub repository.

We could think about supporting having the `devcontainer.json` available on an SSH host that also run a Docker daemon. The image building could be done in a container like we do for the repository case. Marking as feature request. /cc @egamma

**Comment by Chuxel** [comment] 2019-10-24 18:20
This is potentially a dupe of #20.

**Comment by chrmarti** [comment] 2019-10-28 21:09
True, merging with that.

/duplicate #20

**Closed** 2019-10-28 21:10 UTC
Labels: *duplicate, containers, feature-request
