### ISSUE TITLE
No auth provider with id 'github' when run remotely

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2651] opened 2020-03-31 09:09 UTC
Issue Type: <b>Bug</b>

#2638

Using a PR URL to a private repo:

![image](https://user-images.githubusercontent.com/9205389/78008257-be3ca200-733f-11ea-9633-0af19f796fef.png)

Extension version: 0.109.0
VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (2.10GB free)|
|Process Argv|-psn_0_3851180|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.68GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment] 2020-03-31 09:12
Apparently the GitHub PullRequest extension needs to be installed and enabled (which might not be the case when installed locally and already connected to a container).

**Comment by egamma** [comment] 2020-03-31 11:07
@chrmarti The GitHub Authprovider is contributed by the bundled extension `github-authentication` and not the GitHub PullRequest extension.

Did you run the command in a remote setup? Can you try to reproduce when running the command in a local setup (there seems to be problems in a remote setup).

If this still fails, can you try whether this simple extension succeeds fetching the access token:
```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	let disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
		const scope = ['repo]'];
		let token;
		try {
			let result = await vscode.authentication.getSessions('github', scope);
			if (result.length > 0) {
				token = await result[0].getAccessToken();
		
			} else {
				let auth = await vscode.authentication.login('github', scope);
				token = await auth.getAccessToken();
			}
			console.log(token);
		} catch (e) {
			console.log(e);
		}
	});
	context.subscriptions.push(disposable);
}
```

**Comment by chrmarti** [comment] 2020-04-01 05:45
You're right, it works locally without the GitHub PR extension, but not remotely.

**Comment by egamma** [comment] 2020-04-01 15:43
@chrmarti fyi, the auth provider support will not be stable API for March. I therefore enable auth only when run on insiders.

**Comment by egamma** [comment] 2020-11-05 08:23
>You're right, it works locally without the GitHub PR extension, but not remotely.

This now also works remotely, closing.

**Closed by egamma** 2020-11-05 08:23 UTC
