### ISSUE TITLE
.vscode-server folder is appended at the end of $PATH

### ISSUE THREAD

**Issue by GuillerLT** [microsoft/vscode-remote-release#6579] opened 2022-04-06 21:18 UTC
- VSCode Version: 1.66.0
- Local OS Version: Windows 11 Pro 21H2 22000.593
- Remote OS Version: macOS Monterey 12.3.1
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote host using ssh
2. Try to execute `code folder` or `code file` in the vscode terminal
3. A vscode window is opened in the remote host

It is using the remote host executable (`/usr/local/bin/code`) instead of the remote-cli executable (`/Users/username/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/bin/remote-cli/code`) because it goes first in $PATH.

```
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/username/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/bin/remote-cli:/Users/username/.cargo/bin
```

**Comment by chri7325** [comment] 2022-04-06 21:51
I'm also having the same issue. My remote machine is an M1 that uses brew to install code and my host machine is an Intel mac

```
which -a code
/opt/homebrew/bin/code
/Users/chri7325/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/bin/remote-cli/code
/opt/homebrew/bin/code
```

The extensions on my remote ssh session are also not picking up the host's extensions that are also already installed.

**Comment by aeschli** [comment] 2022-04-11 08:59
The problem is that the `/usr/local/bin` is prepended to the PATH by the shell's login script. E.g. on my Mac machine it's `.bash_profile`. So the path we add is behind.
I don't know how we could force our path to be first. @Tyriar @roblourens Any ideas?

**Comment by DavidArmendariz** [comment] 2022-05-13 23:34
Any updates on this?

**Comment by aeschli** [comment] 2022-05-16 06:59
duplicate of https://github.com/microsoft/vscode-remote-release/issues/6625

I'll look into a solution for this month

**Closed by aeschli** 2022-05-16 06:59 UTC
Labels: ssh
