### ISSUE TITLE
Failed to connect to the remote extension host server (Error: connect ECONNREFUSED ::1:37245)

### ISSUE THREAD

**Issue by Borkason** [microsoft/vscode-remote-release#2123] opened 2020-01-04 19:46 UTC
Issue Type: <b>Bug</b>

[2020-01-04 19:42:05.947] Resolving wsl+Ubuntu, resolveAttempt: 1
[2020-01-04 19:42:06.004] Starting VS Code Server inside WSL (Ubuntu)
[2020-01-04 19:42:06.004] Extension version: 0.41.6, Windows build: 19536. Multi distro support: available. WSL path support: enabled
[2020-01-04 19:42:06.117] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-01-04 19:42:06.229] Probing result: found
[2020-01-04 19:42:06.229] Server install found in WSL
[2020-01-04 19:42:06.229] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 26076a4de974ead31f97692a0d32f90d735645c0 stable .vscode-server 0  ' in c:\Users\Borkason\.vscode\extensions\ms-vscode-remote.remote-wsl-0.41.6
[2020-01-04 19:42:06.422] Setting up server environment: Looking for /root/.vscode-server/server-env-setup. Not found.
[2020-01-04 19:42:06.422] WSL version: 4.19.81-microsoft-standard Ubuntu
[2020-01-04 19:42:06.422] WSL2-shell-PID: 5945
[2020-01-04 19:42:06.422] Starting server: /root/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/server.sh  --port=0 --enable-remote-auto-shutdown 
[2020-01-04 19:42:06.422] 
[2020-01-04 19:42:06.422] 
[2020-01-04 19:42:06.422] *
[2020-01-04 19:42:06.422] * Visual Studio Code Server
[2020-01-04 19:42:06.422] *
[2020-01-04 19:42:06.422] * Reminder: You may only use this software with Visual Studio family products,
[2020-01-04 19:42:06.422] * as described in the license https://aka.ms/vscode-remote/license
[2020-01-04 19:42:06.422] *
[2020-01-04 19:42:06.422] 
[2020-01-04 19:42:06.422] 
[2020-01-04 19:42:06.736] IP Address: 172.20.12.28
[2020-01-04 19:42:06.736] Extension host agent listening on 37245
[2020-01-04 19:42:06.736] 
[2020-01-04 19:42:06.736] 
[2020-01-04 19:42:06.736] [20:42:06] Extension host agent started.
[2020-01-04 19:42:06.740] WSL resolver response: ::1:37245
[2020-01-04 19:42:06.740] To debug connection issues, open a local browser on http://[::1]:37245/version

Extension version: 0.41.6
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19536

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (8.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lengthmin** [comment] 2020-01-06 06:01
Does every first connection succeed? and the second connection will fail

**Comment by bplasmeijer** [comment] 2020-01-06 08:22
I have the same issue; the first connections are excellent, but after turn down my PC, 'windows sleep'.  The following errors are pop-up; "Could not fetch remote environment", and "Failed to connect to the remote extension host server (Error: connect ECONNREFUSED ::1:44851)"

Reboot PC solves the issue; I need to investigate the network stack after the sleep.

Any suggestions @fiveisprime ?

[2020-01-06 08:16:03.278] Resolving wsl+Ubuntu-18.04, resolveAttempt: 1
[2020-01-06 08:16:03.341] Starting VS Code Server inside WSL (Ubuntu-18.04)
[2020-01-06 08:16:03.341] Extension version: 0.42.0, Windows build: 19536. Multi distro support: available. WSL path support: enabled
[2020-01-06 08:16:03.547] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-18.04 -e sh -c "[ -d ~/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-01-06 08:16:03.692] Probing result: found
[2020-01-06 08:16:03.692] Server install found in WSL
[2020-01-06 08:16:03.692] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu-18.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 7c0095ee2d064033fc13184127a9adc603454729 insider .vscode-server-insiders 0  ' in c:\Users\DUMMY\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.42.0
[2020-01-06 08:16:03.856] Setting up server environment: Looking for /home/bartplasmeijer/.vscode-server-insiders/server-env-setup. Not found.
[2020-01-06 08:16:03.856] WSL version: 4.19.81-microsoft-standard Ubuntu-18.04
[2020-01-06 08:16:03.856] WSL2-shell-PID: 306
[2020-01-06 08:16:03.856] Starting server: /home/bartplasmeijer/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/server.sh  --port=0 --enable-remote-auto-shutdown 
[2020-01-06 08:16:04.164] 
[2020-01-06 08:16:04.164] 
[2020-01-06 08:16:04.164] *
[2020-01-06 08:16:04.164] * Visual Studio Code Server
[2020-01-06 08:16:04.164] *
[2020-01-06 08:16:04.164] * Reminder: You may only use this software with Visual Studio family products,
[2020-01-06 08:16:04.164] * as described in the license https://aka.ms/vscode-remote/license
[2020-01-06 08:16:04.164] *
[2020-01-06 08:16:04.164] 
[2020-01-06 08:16:04.164] 
[2020-01-06 08:16:04.164] IP Address: 172.19.199.85
[2020-01-06 08:16:04.164] Extension host agent listening on 44851
[2020-01-06 08:16:04.164] 
[2020-01-06 08:16:04.164] 
[2020-01-06 08:16:04.164] [09:16:04] Extension host agent started.
[2020-01-06 08:16:04.166] WSL resolver response: ::1:44851
[2020-01-06 08:16:04.166] To debug connection issues, open a local browser on http://[::1]:44851/version

![image](https://user-images.githubusercontent.com/116467/71805104-9f42b280-3065-11ea-87b1-74047cf31fd8.png)

**Comment by aeschli** [comment] 2020-01-06 09:22
Duplicate of #2060

It's a WSL2 issue.
I just released a new version of the extension: 0.42.1 that should work around the issue. It requires VSCode Insiders (1.42.0). It would be great if you can give it a try. If it works I can also make a version for the stable VSCode (1.41.1)

**Closed by aeschli** 2020-01-06 09:22 UTC

**Comment by bplasmeijer** [comment] 2020-01-06 12:28
> Duplicate of #2060
> 
> It's a WSL2 issue.
> I just released a new version of the extension: 0.42.1 that should work around the issue. It requires VSCode Insiders (1.42.0). It would be great if you can give it a try. If it works I can also make a version for the stable VSCode (1.41.1)

I will test it now.
