### ISSUE TITLE
Specify a custom vscode-server install directory

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [microsoft/vscode-remote-release#5917] opened 2021-11-19 05:27 UTC
The login directory on some of our embedded systems are read-only, so it is impossible to install vscode-server to the user's login directory.  By default, it gets installed at `~/.vscode-server`.

I would like to be able to specify a different directory for vscode-server per remote platform.  E.g. a remote-ssh setting something like:

```
"remote.SSH.remotePlatform": {
    "host1": "linux",
    "host1.vscodeServerDirectory": "/store/writable/",
    "host2": "linux",
    "host2.vscodeServerDirectory": "/tmp",
    "host3": "linux",
}
```

**Comment by tanhakabir** [comment] 2021-11-19 18:01
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/472

We actually just merged in this feature and it should be available to use in Remote-SSH Nightly this month and in stable next month. Let me know if you end up trying it and find anything unexpected!

**Closed by tanhakabir** 2021-11-19 18:01 UTC
Labels: ssh
