### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by hijkzzz** [microsoft/vscode-remote-release#6355] opened 2022-02-17 00:27 UTC
When I upgradet the remote-ssh plugin recently..
I can't connect my ubuntu server.

Remote SSH v0.74.0
VSCode Version: 1.64.2
System MacOS 12

```
[08:24:43.589] Log Level: 2
[08:24:43.590] remote-ssh@0.74.0
[08:24:43.590] darwin x64
[08:24:43.600] SSH Resolver called for "ssh-remote+computelab-304-docker", attempt 1
[08:24:43.601] "remote.SSH.useLocalServer": true
[08:24:43.601] "remote.SSH.path": undefined
[08:24:43.601] "remote.SSH.configFile": undefined
[08:24:43.601] "remote.SSH.useFlock": true
[08:24:43.601] "remote.SSH.lockfilesInTmp": false
[08:24:43.601] "remote.SSH.localServerDownload": auto
[08:24:43.602] "remote.SSH.remoteServerListenOnSocket": false
[08:24:43.602] "remote.SSH.showLoginTerminal": false
[08:24:43.602] "remote.SSH.defaultExtensions": []
[08:24:43.602] "remote.SSH.loglevel": 2
[08:24:43.602] "remote.SSH.enableDynamicForwarding": true
[08:24:43.602] "remote.SSH.enableRemoteCommand": false
[08:24:43.603] "remote.SSH.serverPickPortsFromRange": {}
[08:24:43.603] "remote.SSH.serverInstallPath": {}
[08:24:43.606] SSH Resolver called for host: computelab-304-docker
[08:24:43.606] Setting up SSH remote "computelab-304-docker"
[08:24:43.609] Acquiring local install lock: /var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-remote-ssh-9abc8450-install.lock
[08:24:43.610] Looking for existing server data file at /Users/hujian/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-9abc8450-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json
[08:24:43.610] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[08:24:43.613] Install and start server if needed
[08:24:43.616] PATH: /Users/hujian/.nvm/versions/node/v14.17.5/bin:/Users/hujian/opt/anaconda3/bin:/Users/hujian/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[08:24:43.616] Checking ssh with "ssh -V"
[08:24:43.622] > OpenSSH_8.6p1, LibreSSL 2.8.3

[08:24:43.624] askpass server listening on /var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-1688002274efd3db619705f4a21cfd7ef24cec21.sock
[08:24:43.624] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-ba1c2048dd0c7f73733fbbf1f9a4d2803a3059f3.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","56916","-o","ConnectTimeout=15","computelab-304-docker"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/hujian/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-9abc8450-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json"}
[08:24:43.624] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-1688002274efd3db619705f4a21cfd7ef24cec21.sock"}
[08:24:43.625] Spawned 94745
[08:24:43.734] > local-server-1> Spawned ssh, pid=94756
[08:24:43.737] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[08:24:44.511] stderr> debug1: Server host key: ssh-ed25519 SHA256:4iV4Hl3WSB0fhkKLzRzWeoam0dabMUURzVONDcLmc2k
[08:24:44.511] stderr> Warning: Permanently added '[computelab-304]:7022' (ED25519) to the list of known hosts.
[08:24:45.459] stderr> Authenticated to computelab-304 ([10.32.208.144]:7022).
[08:24:46.023] > Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-97-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> This system has been minimized by removing packages and content that are
> not required on a system that users do not log into.
> 
> To restore this content, you can run the 'unminimize' command.
> 
> The programs included with the Ubuntu system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
> 
> 
> The programs included with the Ubuntu system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
[08:24:46.209] > ready: 277c19484617
[08:24:46.403] > Linux 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022
[08:24:46.403] Platform: linux
[08:24:46.595] > 277c19484617: running
[08:24:46.595] stderr> bash: line 1: syntax error near unexpected token `done'
[08:24:46.596] stderr> bash: line 1: `done'
[08:24:46.596] stderr> -sh: 4: function: not found
[08:24:46.597] stderr> -sh: 74: [[: not found
[08:24:46.601] stderr> -sh: 95: [[: not found
[08:24:46.604] stderr> -sh: 160: Syntax error: "(" unexpected (expecting "then")
[08:24:46.604] stderr> Transferred: sent 18324, received 3976 bytes, in 1.1 seconds
[08:24:46.604] stderr> Bytes per second: sent 16008.2, received 3473.5
[08:24:46.605] > local-server-1> ssh child died, shutting down
[08:24:46.608] Local server exit: 0
[08:24:46.608] Received install output: local-server-1> Spawned ssh, pid=94756
OpenSSH_8.6p1, LibreSSL 2.8.3
debug1: Server host key: ssh-ed25519 SHA256:4iV4Hl3WSB0fhkKLzRzWeoam0dabMUURzVONDcLmc2k
Warning: Permanently added '[computelab-304]:7022' (ED25519) to the list of known hosts.
Authenticated to computelab-304 ([10.32.208.144]:7022).
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-97-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

ready: 277c19484617
Linux 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022
277c19484617: running
bash: line 1: syntax error near unexpected token `done'
bash: line 1: `done'
-sh: 4: function: not found
-sh: 74: [[: not found
-sh: 95: [[: not found
-sh: 160: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 18324, received 3976 bytes, in 1.1 seconds
Bytes per second: sent 16008.2, received 3473.5
local-server-1> ssh child died, shutting down

[08:24:46.609] Failed to parse remote port from server output
[08:24:46.610] Resolver error: Error: 
	at Function.Create (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:585917)
	at Object.t.handleInstallOutput (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:584569)
	at Object.e [as tryInstallWithLocalServer] (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:624925)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:643015
	at async Object.t.withShowDetailsEvent (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:646762)
	at async /Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623397
	at async b (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:619903)
	at async Object.t.resolveWithLocalServer (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623012)
	at async Object.t.resolve (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:644372)
	at async /Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:721503
[08:24:46.613] ------
```

**Comment by tanhakabir** [comment] 2022-02-17 08:08
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6341

I'll have a fix for all of you to try soon

**Closed by tanhakabir** 2022-02-17 08:08 UTC
Labels: ssh

**Comment by tanhakabir** [comment] 2022-02-17 23:34
There will be a fix for this out in tomorrow's pre-release after 8am PST. Let me know if this fixes it for you.
