### ISSUE TITLE
proxy settings in remote scope appear to affect local scope as well

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode-remote-release#5158] opened 2021-06-09 17:21 UTC
- VSCode Version: 
- Local OS Version: 
```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.18363
```
- Remote OS Version: Debian 9
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Connect to remote machine with SSH
2. Configure `http.proxy` in the Remote settings to `http://localhost:$port` (this setting doesn't exist in User settings)
3. Install the Live Share extension
4. Attempt to share, and enter the auth flow for Microsoft authentication
5. Complete auth flow in the browser, redirect back to VS Code

With no port forwarding, this fails:

```
[Info  - 17:05:51.936] Logging in...
[Info  - 17:06:01.131] Exchanging login code for token
[Error  - 17:06:01.171] request to https://login.microsoftonline.com/organizations/oauth2/v2.0/token failed, reason: connect ECONNREFUSED 127.0.0.1:$port
```

If I then add a port forwarding rule to tunnel that port back to Windows, and try the auth flow again, it succeeds. 

This leads me to believe that Live Share is initiating this token fetch request from the Code process in Windows, but is using the `http.proxy` setting that was set only for the remote server. The intent here is that this proxy only listens to clients initiating requests from the same machine, so forwarding this port works to demonstrate the problem, but isn't something we should actually be doing. 

This feels to me like a bug, that the proxy setting is being applied to a scope it wasn't set for, but I'm not sure what I should expect settings scopes to mean exactly. In any case, the ideal situation, for me, would be that it is possible to configure the local and remote networking rules independently, further ideally to make them both use PAC rules, but it would at least make the situation less confusing if we could use PAC rules on the local Windows side, and the current `http.proxy` mechanism on the Remote side.

It also seems like the networking configuration in VS Code as a whole is in a state of flux: https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support. https://github.com/microsoft/vscode/issues/12588 looks challenging, and maybe this is just a presentation of that, or maybe this is a different problem, possibly a rare interaction between the Remote extension and specifically the Live Share extension?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by leifwalsh** [comment] 2021-06-09 17:25
If it matters, I see the same behavior with the Insiders build.

**Comment by roblourens** [comment] 2021-06-23 04:59
@chrmarti ?

**Comment by chrmarti** [comment] 2021-06-23 06:21
Duplicate of https://github.com/microsoft/vscode/issues/119466

**Closed by chrmarti** 2021-06-23 06:21 UTC
Labels: ssh
