### ISSUE TITLE
Opening C:\ exhibits strange results

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#1596] opened 2019-10-03 04:16 UTC
Testing #1524 

Repro 1:
Use the custom file picker to open `C:\`
The explorer will show the folder open as C: and the tree will contain the server bin directory?

Repro 2:
Use the custom file picker to open `\`
The explorer tree will be correct but the folder will be `/` as opposed to `\`

**Comment by alexr00** [comment] 2019-10-28 10:58
Repro 1 happens even with the OS file picker.
Repro 2 is a bug.

**Comment by Tyriar** [comment] 2019-10-30 19:40
I can only open `/` which ends up showing `/` in the explorer (windows->windows). Using `\` does nothing. Not sure what's expected?

**Comment by alexr00** [comment] 2019-10-31 11:11
Looks like there are still problems here. I only test with a local setup, not windows ->windows.

**Comment by bpasero** [comment] 2020-01-24 07:11
@alexr00 I see an issue from the URI to open, for the remote case it will be `vscode-remote://test%2Btest/c%3A` but for a local case it will be `file:///c%3A/`. So there is a trailing slash missing which is important for the drive letter.

Could it be that the file picker is not given a good URI back in the remote case for root on Windows?

**Comment by bpasero** [comment] 2020-01-24 07:13
Yes I just confirmed that.

**Comment by alexr00** [comment] 2020-01-24 10:19
I fixed the missing trailing slash coming out of the simple file picker, but the issue is still happening. Someone else is removing the slash now. I followed the URI to the electron service and it still looks good that far.

**Comment by alexr00** [comment] 2020-01-24 10:26
It is here: https://github.com/microsoft/vscode/blob/4ba20708184180ff2a99c3e6982703da140699b1/src/vs/platform/windows/electron-main/windowsMainService.ts#L1062

**Comment by bpasero** [comment] 2020-01-24 10:43
Yeah thanks for finding out. Putting that check into `removeTrailingPathSeparator()` makes sense to me.

**Comment by chrmarti** [comment] 2020-01-31 13:43
Trying to verify when connected Windows to Windows:

Opening `c:` on Windows opened the install folder (note the wrong label `c:` in the Explorer):
![image](https://user-images.githubusercontent.com/9205389/73543443-4503fa00-4437-11ea-8f0a-addb04962df6.png)

Wrong path separators in initial path and when navigating the list:
![image](https://user-images.githubusercontent.com/9205389/73543603-944a2a80-4437-11ea-98fa-7eb443e08736.png)

`C:\` and `C:/` cannot be opened (no error message, OK just doesn't work).

**Comment by alexr00** [comment] 2020-01-31 14:06
Looks like the separator isn't getting set correctly when using `remote.SSH.useLocalServer` instead of `remote.SSH.windowsRemotes` To verify this issue, you'll need to use `remote.SSH.windows.Remotes`. Opening a new issue for label service not having the correct separator.

**Comment by chrmarti** [comment] 2020-01-31 14:47
Testing with `useLocalServer` false and Windows remotes set:

- `C:` opens the server's install folder.
- When in `C:\`, Open Folder comes up with `\` instead of `C:\`.
- `\` does not open (the picker stays without error message).
- `\Some\Path` does not show `..` in the items to move up.

**Comment by alexr00** [comment] 2020-01-31 15:04
Looks like I broke all those again when I moved the fix into the path utilities. Will fix again for February.

**Comment by sbatten** [comment] 2020-02-27 17:46
I see exactly the behavior reported by @chrmarti https://github.com/microsoft/vscode-remote-release/issues/1596#issuecomment-580762981 still

**Comment by Tyriar** [comment] 2020-02-27 17:49
I think the distro merge being committed again cause the initial fix that didn't fix it to close the issue incorrectly.

**Comment by alexr00** [comment] 2020-02-28 08:33
:( Looks like that's what happened. And because of that I lost the issue.

**Comment by alexr00** [comment] 2020-02-28 10:19
Opening C:\ should work. Shows as C: in Explorer, in recents shows as C:\
Opening C: should do the same as above
Known issue: after opening either of the above, the starting point of the picker for Open Folder will be incorrect: https://github.com/microsoft/vscode-remote-release/issues/2447
This is still a bug: \Some\Path does not show .. in the items to move up, will be fixed as part of #2448
Trying to open \ still doesn't work: https://github.com/microsoft/vscode-remote-release/issues/2448

**Comment by alexr00** [comment] 2020-02-28 10:21
To verify:
- Look at the known bugs #2448 and #2447
- Make sure to use `remote.SSH.windowsRemotes`
- Connect to a windows remote
- Try to open C: (or whatever your drive letter is)
- Try to open C:\ (or whatever your drive letter is)

**Closed** 2020-02-28 10:50 UTC
Labels: bug, candidate

**Comment by roblourens** [comment] 2020-02-28 19:27
Should it be displayed as `C:\` though? Just `C:` looks weird to me. But it's an edge case and I don't know what other people expect. This is after I typed `C:\` in the picker

![image](https://user-images.githubusercontent.com/323878/75580820-47994580-5a1d-11ea-9386-39fa9ebf9aad.png)

**Comment by alexr00** [comment] 2020-03-02 10:13
@isidorn for that. If you look in your recent folders after that you _should_ see "C:\\" (at least that's what I saw).

**Comment by isidorn** [comment] 2020-03-02 10:34
@roblourens can you open a new issue for that and ping me on it. Thanks
