### ISSUE TITLE
Notebook File Root not set

### ISSUE THREAD

**Issue by vnijs** [Microsoft/vscode-remote-release#43] opened 2019-05-03 04:00 UTC
- VSCode Version: 1.34.0-insider
- Local OS Version: macOS Mojave
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open an folder / workspace
2. execute os.getcwd() in the python interactive windows

Although I have loaded a workspace (see screenshot below) the directory used is still the home directory even though settings indicate `${workspaceFolder}` will be used. Any ideas

![image](https://user-images.githubusercontent.com/2998956/57119166-f34e0800-6d1c-11e9-86db-761ccacd98dc.png)

![image](https://user-images.githubusercontent.com/2998956/57119192-1b3d6b80-6d1d-11e9-891e-7dece808b11a.png)

![image](https://user-images.githubusercontent.com/2998956/57119175-fe089d00-6d1c-11e9-9294-a1a744d66fab.png)

**Comment by chrmarti** [comment] 2019-05-03 11:07
Cannot reproduce, could you try our test project: https://github.com/Microsoft/vscode-dev-containers/tree/master/containers/python-3-anaconda#testing-the-definition

If that works as expected, can you share your project?

**Comment by vnijs** [comment] 2019-05-04 00:20
The example you point to of building a new container (without an entry point) and "mounting" a directory from the host system seems work fine (i.e., I get '/workspaces/myproject' from `os.getcwd()`.

I, and my students, however, would use "Remote-containers: Attach to running container". Theses container *do* have an entrypoint (e.g., jupyter running on port 8989) and they mount their host os home drive as the home drive in the container. You can navigate to a project directory and have VSCode pickup the "workspace" file. However, that does *not* change the working directory the way it would on the host os.

The docker container I'm using at the moment is `vnijs/rsm-msba`.  When started, this will run jupyter on port 8989. I connect using.

http://localhost:8989/?token=jupyter

![image](https://user-images.githubusercontent.com/2998956/57171265-93606b80-6dc7-11e9-9e53-4947b2014ea5.png)

I also tried just using a jupyter session started by vscode but that gives some strange "bash" errors. See below.

<pre>
Jupyter Server URI: http://127.0.0.1:8888/?token=57be9514e3a562cadb5ca185b42898bc96122f977c76509f
Python version:
bash: import: command not found
bash: sys.version: command not found

bash: import: command not found
bash: sys.executable: command not found

Jupyter Notebook Version: bash: import: command not found
bash: notebook.version_info: command not found
</pre>

**Related feature requests:**

* Option to connect to a specific running kernels in a container (e.g., Python, R, etc), depending on what is available.
* When vscode connects to my container it connects as root. Could there be an option to specify the user to login as?

**Comment by chrmarti** [comment] 2019-05-06 08:37
So the Notebook File Root setting doesn't work when using a Jupyter Server URI. Moving to Microsoft/vscode-python for help as this is not specific to Remote Containers.

**Comment by chrmarti** [comment] 2019-05-06 08:43
@vnijs I can't seem to move the issue. Could you copy your report over to https://github.com/Microsoft/vscode-python/issues/new ? Thanks.

**Closed by chrmarti** 2019-05-06 08:43 UTC
Labels: containers, needs-more-info
