### ISSUE TITLE
build devcontainer failed

### ISSUE THREAD

**Issue by AisonSu** [microsoft/vscode-remote-release#7382] opened 2022-10-19 06:46 UTC
- VSCode Version: 1.72.2
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type:Containers
- Logs:
- 
- [269 ms] Dev Containers 0.255.4 in VS Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075).
[267 ms] Start: Resolving Remote
[342 ms] Setting up container for folder or workspace: c:\Users\aison\Desktop\node
[606 ms] Start: Check Docker is running
[607 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[1743 ms] Server API version: 1.41
[1751 ms] Start: Run: docker volume ls -q
[3721 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\aison\Desktop\node --filter label=vsch.quality=stable
[4655 ms] Start: Run: C:\Users\aison\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\aison\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\aison\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\aison\Desktop\node --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\aison\Desktop\node --log-level debug --log-format json --config c:\Users\aison\Desktop\node\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[6096 ms] (node:7052) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[6096 ms] (Use `Code --trace-deprecation ...` to show where the warning was created)
[6103 ms] @devcontainers/cli 0.20.0. Node.js v16.14.2. win32 10.0.19044 x64.
[6103 ms] Start: Run: docker buildx version
[7408 ms] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[7408 ms] 
[7408 ms] Start: Resolving Remote
[7421 ms] Start: Run: git rev-parse --show-cdup
[7761 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\aison\Desktop\node
[8636 ms] Start: Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/typescript-node:0-16-bullseye
[10459 ms] local container features stored at: c:\Users\aison\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\node_modules\vscode-dev-containers\container-features
[10465 ms] Start: Run: tar --no-same-owner -x -f -
[10608 ms] node:events:504
[10610 ms]       throw er; // Unhandled 'error' event
[10612 ms]       ^
[10613 ms] Error: write EPIPE
[10613 ms]     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
[10615 ms]     at writeGeneric (node:internal/stream_base_commons:151:3)
[10616 ms]     at Socket._writeGeneric (node:net:795:11)
[10617 ms]     at Socket._write (node:net:807:8)
[10618 ms]     at doWrite (node:internal/streams/writable:408:12)
[10619 ms]     at clearBuffer (node:internal/streams/writable:569:7)
[10620 ms]     at onwrite (node:internal/streams/writable:461:7)
[10620 ms]     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:106:10)
[10621 ms] Emitted 'error' event on Socket instance at:
[10622 ms]     at emitErrorNT (node:internal/streams/destroy:157:8)
[10623 ms]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[10624 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
[10626 ms]   errno: -4047,
[10627 ms]   code: 'EPIPE',
[10628 ms]   syscall: 'write'
[10629 ms] }
[10657 ms] Exit code 1
[10670 ms] Command failed: C:\Users\aison\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\aison\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\aison\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\aison\Desktop\node --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\aison\Desktop\node --log-level debug --log-format json --config c:\Users\aison\Desktop\node\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[10670 ms] Exit code 1

Steps to Reproduce:
1.Open a project with dev container
2. build starts
3. After some time the Error comes

Does this issue occur when you try this locally?: Yes

**Comment by chrmarti** [comment] 2022-10-25 12:56
Could you append your devcontainer.json?

**Comment by AisonSu** [comment] 2022-10-26 11:27
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/typescript-node
{
	"name": "Node.js & TypeScript",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick a Node version: 18, 16, 14.
		// Append -bullseye or -buster to pin to an OS version.
		// Use -bullseye variants on local on arm64/Apple Silicon.
		"args": { 
			"VARIANT": "16-bullseye"
		}
	},

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			// Add the IDs of extensions you want installed when the container is created.
			"extensions": [
				"dbaeumer.vscode-eslint"
			]
		}
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "yarn install",

	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "node",
	"features": {
		"git": "os-provided",
		"git-lfs": "latest",
		"github-cli": "latest",
		"fish": "latest"
	}
}


> Could you append your devcontainer.json?

// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/typescript-node
{
	"name": "Node.js & TypeScript",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick a Node version: 18, 16, 14.
		// Append -bullseye or -buster to pin to an OS version.
		// Use -bullseye variants on local on arm64/Apple Silicon.
		"args": { 
			"VARIANT": "16-bullseye"
		}
	},

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			// Add the IDs of extensions you want installed when the container is created.
			"extensions": [
				"dbaeumer.vscode-eslint"
			]
		}
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "yarn install",

	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "node",
	"features": {
		"git": "os-provided",
		"git-lfs": "latest",
		"github-cli": "latest",
		"fish": "latest"
	}
}

**Comment by ido-greenfeld** [comment] 2022-11-10 11:22
I'm getting the same issue
Trying to build a devcontainer - the most basic one I can think of and getting the EPIPE Error
If I press retry enough times, it eventually does build the container

VSCode version - 1.73.0


This is my devontainer - 
```
{
	"name": "Existing Dockerfile",
	"context": "..",
	"dockerFile": "../Dockerfile",
	"settings": {},

}
```
This is my Dockerfile - 
```
FROM python:3.8

RUN mkdir -p /app
WORKDIR /app

COPY . /app
```

**Comment by ido-greenfeld** [comment] 2022-11-10 11:35
I'm not sure but I think the issue it resolved if I downgrade the `Remote - Containers` extension to `v0.251.0`
@AisonSu can you see if this resolves the issue for you as well?

**Comment by ido-greenfeld** [comment] 2022-11-11 08:57
I can confirm that I've been using `v0.251.0` for the last day without any issues

@chrmarti can we provide more information to help pinpoint the issue?

**Comment by chrmarti** [comment] 2022-11-15 15:44
I'll improve the logging there to better understand what is going on. Can you check what is at the path mentioned in the log after `local container features stored at:`?

**Comment by chrmarti** [comment] 2022-11-16 10:13
No, that looks fine. Thanks.

**Comment by ido-greenfeld** [comment] 2022-11-24 06:52
hi @chrmarti, I see your PR to add logging has been approved
is there a way for us to test it out so we can provide the logs asap? or do we need to wait until a new version of the extension comes out?

**Comment by FrankFang** [comment] 2022-11-28 08:30
In case you don't know how to install old version of a vscode extension
```
code --install-extension ms-vscode-remote.remote-containers@0.251.0
```

**Comment by Workata** [comment] 2023-01-01 18:23
Add this to devcontainer.json:
```
{
    ...
    "overrideCommand": true
}
```
https://github.com/microsoft/vscode-remote-release/issues/7737#issuecomment-1357394920

**Comment by vetsasai** [comment] 2023-02-15 09:26
Facing the same issue. I am new to Docker and DevContainers. So couldnt troubleshoot so easily. Can anyone help on this, please!

**Comment by taoqf** [comment] 2023-03-02 01:34
251 works, 281 won't.

**Comment by taoqf** [comment] 2023-03-02 01:38
It's strange after I changed back to 281 from 251, the issue goes, too.

**Comment by nhatnamnguyengtvthcm** [comment] 2023-04-24 08:04
I have  the same issue:
[44 ms] Remote-Containers 0.251.0 in VS Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710).
[44 ms] Start: Resolving Remote
[63 ms] Setting up container for folder or workspace: u:\python-project
[65 ms] Start: Check Docker is running
[66 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[575 ms] Server API version: 1.41
[576 ms] Start: Run: docker volume ls -q
[3626 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=u:\python-project --filter label=vsch.quality=stable
[4242 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=u:\python-project
[4733 ms] Start: Run: C:\Users\AGN8HC\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\AGN8HC\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder u:\python-project --workspace-mount-consistency cached --id-label devcontainer.local_folder=u:\python-project --log-level debug --log-format json --config u:\python-project\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 165 --terminal-rows 17
[5258 ms] remote-containers 0.251.0.
[5258 ms] Start: Run: docker buildx version
[6379 ms] Start: Resolving Remote
[6506 ms] Start: Run: git rev-parse --show-cdup
[7522 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=u:\python-project
[8032 ms] local container features stored at: c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\node_modules\vscode-dev-containers\container-features
[8034 ms] Start: Run: tar --no-same-owner -x -f -
[8151 ms] Start: Run: docker events --format {{json .}} --filter event=start
[8332 ms] Start: Starting container
[8332 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=u:\python-project,target=/workspaces/python-project,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=u:\python-project --entrypoint /bin/sh mcr.microsoft.com/devcontainers/python:0-3.10 -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /run/desktop/mnt/host/uC/hc10fs02.apac.bosch.com/AGN8HC$/p
ython-project.
See 'docker run --help'.
[9455 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=u:\python-project
[10069 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=u:\python-project,target=/workspaces/python-project,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=u:\python-project --entrypoint /bin/sh mcr.microsoft.com/devcontainers/python:0-3.10 -c echo Container started
[10069 ms] trap "exit 0" 15
[10069 ms] exec "$@"
[10069 ms] while sleep 1 & wait $!; do :; done -
[10069 ms]     at SF (c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\spec-node\devContainersSpecCLI.js:257:2186)
[10069 ms]     at pb (c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\spec-node\devContainersSpecCLI.js:257:2124)
[10069 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[10069 ms]     at async DF (c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\spec-node\devContainersSpecCLI.js:263:2006)
[10069 ms]     at async to (c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\spec-node\devContainersSpecCLI.js:263:3110)
[10069 ms]     at async Ak (c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\spec-node\devContainersSpecCLI.js:383:8108)
[10070 ms]     at async Ok (c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\spec-node\devContainersSpecCLI.js:383:7864)
[10079 ms] Exit code 1
[10081 ms] Command failed: C:\Users\AGN8HC\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\AGN8HC\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\AGN8HC\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder u:\python-project --workspace-mount-consistency cached --id-label devcontainer.local_folder=u:\python-project --log-level debug --log-format json --config u:\python-project\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 165 --terminal-rows 17
[10081 ms] Exit code 1

**Comment by Gabrielm1984** [comment] 2023-04-24 17:38
this issue occurs to me as well.
didn't add the openAI Key in env.template file

- go to your openAI Account generate a Key
- Copy and paste it into .env.template file OPENAI_API_KEY=paste_it_here_as_is
- save and rename the file .env
- I used the pip install -r requirements.txt you can try using the docker and let us know if it worked

**Comment by VeereshE** [comment] 2023-06-03 14:18
Hi 
Can any tell me y i am getting this error 
[46403 ms] Command failed: C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\user\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-7b146ee1-50d8-4043-93a8-95435942196e1685801539448 --workspace-folder c:\Users\user\Desktop\my_restaurent_app --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\user\Desktop\my_restaurent_app --id-label devcontainer.config_file=c:\Users\user\Desktop\my_restaurent_app\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\user\Desktop\my_restaurent_app\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 69 --terminal-rows 13

**Comment by chrmarti** [comment] 2023-06-05 07:07
@nhatnamnguyengtvthcm Yours seems to be a different problem. The following in your suggests that the `u:` drive is not available in Docker:
```
[8332 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=u:\python-project,target=/workspaces/python-project,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=u:\python-project --entrypoint /bin/sh mcr.microsoft.com/devcontainers/python:0-3.10 -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /run/desktop/mnt/host/uC/hc10fs02.apac.bosch.com/AGN8HC$/p
ython-project.
```

@VeereshE Please open a new issue with the full log.

I haven't gotten to the ground of the originally reported issue here. Is anyone still seeing the EPIPE? Could you append the log from when it occurs with a recent version of the Dev Containers extension?

Thanks.

**Comment by daemonswang** [comment] 2023-06-05 10:50
I met the same issue, any update on?

**Comment by chrmarti** [comment] 2023-06-06 12:38
@daemonswang Are you seeing the EPIPE error? If not please open a new issue. If yes, please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Closed** 2023-06-14 12:28 UTC
Labels: containers, info-needed
