### ISSUE TITLE
Remote SSH terminal code command not working

### ISSUE THREAD

**Issue by af-productions** [microsoft/vscode-remote-release#4460] opened 2021-02-12 10:25 UTC
Issue Type: <b>Bug</b>

Today I read, that the code command is supposed to work, at least in a vscode Terminal. However when I tried it, I got the error "Command not found".
It´s not the first time that I tried it and got that error, but I always just assumed that that´s not supported. I´m using pretty much the same Setup on multiple linux machines but it doesn´t work on any of them.

It might just be caused by an incorrect setup or whatever, but I´d really like to be able to use it, as it would save me some time and make some things a little easier

Extension version: 0.63.0
VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.8.13-98.7.1.el7uek.x86_64
Remote OS version: Linux x64 3.10.0-327.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (20.13GB free)|
|Process Argv|--crash-reporter-id 1c8876c6-9879-4671-bb2c-5ae6a3c05c1b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: |
|OS|Linux x64 3.10.0-327.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|15.51GB (0.76GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: |
|OS|Linux x64 3.8.13-98.7.1.el7uek.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (4 x 2397)|
|Memory (System)|15.42GB (0.24GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by bamurtaugh** [comment] 2021-02-25 06:19
I wonder if this could at all be related to https://github.com/microsoft/vscode-remote-release/issues/4451.

**Comment by roblourens** [comment] 2021-03-03 17:48
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4451

**Closed** 2021-03-03 17:49 UTC
Labels: *duplicate, ssh
