### ISSUE TITLE
remote ssh: git commit fails when gpg signing via gpg-agent forwarding

### ISSUE THREAD

**Issue by diablodale** [microsoft/vscode-remote-release#1022] opened 2019-07-24 16:01 UTC
Git fails to sign a commit, with _Windows_ VSCode Remote SSH, when GnuPG on the local+remote computers are configured to use the local GPG agent/keys.

## Setup

Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Remote SSH Extension: 0.44.2
Remote Development pack: 0.15.0

## Repo

In WSL Ubuntu 18.04...

1. Setup GIT signing with GPG https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
   * Set your global git config for `gpg.program=gpg`, `user.signingkey=xxxxxx`, and `commit.gpgsign=true`
2. Setup GPG agent forwarding over SSH https://wiki.gnupg.org/AgentForwarding
3. SSH to a remote Ubuntu 18.04 server...

Now on this remote Ubuntu 18.04 server...

1. Setup GIT signing with GPG
   * Again set your global git config
2. Setup the server portion of GPG agent forwarding over SSH https://wiki.gnupg.org/AgentForwarding
   * Restart ssh daemon if you edited sshd configuration
3. Logout of the remote server (restart ssh daemon if necessary)
4. SSH again to the remote server
5. Create a new GIT repo
6. Create a `dummy` file
7. Git commit that new file. It should automatically gpg sign it due to your global git config
8. `git log --show-signature` and notice the successful gpg signature. 🙂 This demonstrates that the remote git+ssh+gpg is successfully going over the ssh tunnel and using the local gpg agent/keys.

Now on your Windows computer

1. Launch VSCode
2. Use the VSCode Remote Development Extension for SSH to open a SSH connection to the same remote server
3. Open the same remote server's folder in which you created that git repo
4. Edit and make changes to the `dummy` file
5. Using VSCode's UI, committ this file

## Result

The commit fails and VSCode shows a modal error dialog box `Git: gpg failed to sign the data`

In the `Output` tab for `Remote - SSH` is the following of interest. Notice the last line with error
```
SSH Resolver called for host: home-nas
Setting up SSH remote "home-nas"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "home-nas" bash
...
> connect to /home/dale/.gnupg/S.gpg-agent.extra port -2 failed: No such file or d
> irectory
```

## Expected

Successful commit

## Notes

I believe part of the problem is due to _Windows_ VSCode using a Win32 SSH program yet my entire GPG and SSH configuration is in WSL. In WSL I have all the SSH config settings and entire GPG environment/agent.

This topic of sockets and forwarding are likely related to the following two: https://github.com/microsoft/vscode-remote-release/issues/16 , https://github.com/microsoft/vscode-remote-release/issues/72
Potential workaround in the topic https://github.com/microsoft/vscode-remote-release/issues/937

This is my `~/.ssh/config` in WSL
```config
Host myremoteserver
  User dale
  Hostname myremoteserver
  IdentityFile ~/.ssh/id2_rsa
  RemoteForward /run/user/1000/gnupg/S.gpg-agent /home/dale/.gnupg/S.gpg-agent.extra
```

Given the error in the `Remote - SSH` log above, this suggests to me that the Windows SSH client is:

1. Referencing a WSL path. The Windows SSH client likely does not understand a local Windows path of `/home/dale/.gnupg/S.gpg-agent.extra`
2. Mismatch of networking/socket environments. The Windows SSH client is trying to setup a Windows socket at that path when it needs to be in the WSL environment because the gpg-agent is running in WSL and listening on that WSL unix-socket path.

**Comment by johnletey** [comment] 2019-07-24 18:58
@diablodale Is this equivalent? #72

**Comment by diablodale** [comment] 2019-07-24 19:25
In my `notes` area, 72 is one of the three related issues. However, not duplicates.  72 is focused on only docker containers and already has a workaround.

**Comment by johnletey** [comment] 2019-07-24 19:28
I see, sorry ... my bad ... completely missed your `notes` area 🤦‍♂️

**Comment by roblourens** [comment] 2019-07-27 00:01
You are right that this is about the WSL side and windows side. I have https://github.com/microsoft/vscode-remote-release/issues/937 for that.

**Comment by roblourens** [comment] 2019-07-27 00:03
I don't see any reason why this wouldn't work with #937, so I'll close it as a duplicate for now. Have you tried verifying that by just SSHing from a WSL terminal?

**Comment by roblourens** [comment] 2019-07-27 00:04
Also I see you found the SSH agent forwarding issue, which sounds relevant, but I think it isn't because that is really about setting the SSH_AUTH_SOCK environment variable so it can find the forwarded agent socket. However it sounds like in this case you always use the same remote socket path and there is no environment variable that needs to be fixed in the remote environment.

**Comment by diablodale** [comment] 2019-07-29 13:19
Hello. As I read what you wrote, I think your collapsing together two things:

- Feature to enable use of WSL gpg infrastructure in VSCode
- Failure of VS Code/extension (or dependencies) to recognize WSL paths+config in GPG+SSH configurations and therefore must transform them into WSL style and use WSL tools+pipes.

Making the former new feature might obscure the latter. So this issue becomes a test case (not a dup) that testers needs to add to the test case list.

Alternately, thelatter bug could be fixed which requires code changes to recognize a WSL path+config was given and then to either: a) abort with meaningful error, or b) to the transformations.

**Comment by roblourens** [comment] 2019-07-29 18:38
I don't think it's possible for vscode to do anything about the second issue on it's own. Trying to map the wsl path to a windows path will just lead to pain, and I also don't think vscode should try to validate an ssh config any further than what openssh itself does. But I will leave this issue open to make sure it is considered carefully along with #937.

**Comment by anthr76** [comment] 2020-02-29 18:03
Facing same issue via SSH with Linux to Linux.

**Comment by billcxx** [comment] 2020-08-26 16:59
For me, this solves the problem

`export GPG_TTY=$(tty)
`

https://unix.stackexchange.com/questions/257061/gentoo-linux-gpg-encrypts-properly-a-file-passed-through-parameter-but-throws-i/257065#257065

**Comment by fcastilloec** [comment] 2020-10-14 06:53
> For me, this solves the problem
> 
> `export GPG_TTY=$(tty) `
> 
> https://unix.stackexchange.com/questions/257061/gentoo-linux-gpg-encrypts-properly-a-file-passed-through-parameter-but-throws-i/257065#257065

I tried this, adding it to the remote machine's `.bashrc` but I'm still getting the error. Any other ideas?

**Comment by MathiasMagnus** [comment] 2021-02-25 11:55
Apologies for tuning into the conversation with something that may be out of context, but I don't know where else to post.

Ultimately what I want to do is setup VS Code so I can develop on remote nodes using SSH and Git code signing that is compatible with GitHub and GitLab. SSH remoting works flawlessly, signing with a passphrase protected key has to be done on the command-line, as the GUI fails to present the dialog needed to enter the passphrase.

So far, I've had no luck setting up Gpg4Win (Kleopatra?) and gpg-agent so that my local pinentry program is used to display the passphrase prompt. I've read _all_ the docs and the entire internet, and I got as far as getting `error sending to agent: No pinentry` on the remote end when trying to import my private key. (Tried adding the location of pinentry.exe to the _system PATH_ too, but I don't know how to go about solving this. I've not found a single guide that would involve Gpg4Win or any Gpg implementation on Windows and SSH remoting. I've not found one write dealing with subtleties of not being able to specify the extra-socket file path in my local Windows `~\.ssh\config` as `C:\...` or `C:/...` either, as both are considered as invalid forwarding specification. Specifying `/c/Users/...` does _seem_ to work, but from this point on I've no clue if pinentry is not found because of this.

I'm still missing a few fundamental concepts:
- Must I really deploy my keys remotely? Can't gpg-agent tunnel all key related info from my local box? (At times we have to develop on untrusted remotes, and deploying keys to the remote machine (even if they are passphrase protected) compromises them and requires revoking after use, which is a pain).
- Is there no other code signing technique that is simpler to setup?

I am aware that WLS/SSH/Container(/RemoteContainer) are all different scenarios, but currently only WSL seems to work, however SSH would be the most important for me for my work.

Should I be looking for an entirely different sign tool than GPG that is more SSH or VS Code Remote friendly? I'm using signing with Git and nothing else. Push to Gitlab and Github, but most importantly Gitlab, Github doesn't mandate signing but my org does on Gitlab.

**Comment by nitz** [comment] 2021-04-12 04:31
> > For me, this solves the problem
> > `export GPG_TTY=$(tty) `
> > https://unix.stackexchange.com/questions/257061/gentoo-linux-gpg-encrypts-properly-a-file-passed-through-parameter-but-throws-i/257065#257065
> 
> I tried this, adding it to the remote machine's `.bashrc` but I'm still getting the error. Any other ideas?

I'm just now getting around to trying out remote-ssh, so I'm getting to learn all the fun frustrations like this. I added it to my `.bashrc` as well, and it *does* work, but only in the terminal. I'm guessing since vscode-remote's ssh is a notty session, `$(tty)` is probably resolving to `not a tty`, since it's not actually interactable.

Means commits have to be done from the terminal, but any git action that doesn't require signing can be done through vscode's UI.

**Comment by fcastilloec** [comment] 2021-04-12 17:34
I recommend using [GPG Indicator](https://marketplace.visualstudio.com/items?itemName=wdhongtw.gpg-indicator) extension as a workaround. It allows you to unlock your GPG key through vscode interface, which makes it available for signing through vscode. This will only work if you have GPG caching long enough to be useful.

**Comment by Timecrash** [comment] 2021-04-13 16:49
@fcastilloec's workaround works well for me, though it requires you install the `expect` passage on WSL.

I've also found that if you unlock the GPG key in a WSL terminal (say, with `echo '' | gpg --clearsign`), it'll stay unlocked when you commit in VSCode. Might be helpful if you don't want the GPG Indicator extension installed for whatever reason.

**Comment by Yixuan-Wang** [comment] 2021-08-31 11:06
There seems to be a workaround by using a **GPG client on Windows** side instead of the WSL side, according to this [SO answer](https://stackoverflow.com/a/66143018). I've tried it and it seems working for GnuPG, too.

First, set up environment variable `GPG_TTY`:


> For me, this solves the problem
> 
> `export GPG_TTY=$(tty) `
> 
> https://unix.stackexchange.com/questions/257061/gentoo-linux-gpg-encrypts-properly-a-file-passed-through-parameter-but-throws-i/257065#257065

Then configure your **git on WSL** by:
```sh
git config --global gpg.program "/mnt/c/Program Files (x86)/gnupg/bin/gpg.exe" # route to your gpg client
```
As WSL has the power to launch win32 executables, this theoretically works. The pinentry prompt does popup when using either a terminal or VSCode git UI. But you have to migrate your GPG keys to Windows somehow.

**Comment by yozian** [comment] 2022-05-11 05:44
I try the work around with vs code extension:

[vscode-gpg-indicator](https://github.com/wdhongtw/vscode-gpg-indicator)

ref: https://stackoverflow.com/questions/62228420/signing-git-commits-on-remote-vscode-session

Hope this helps

**Comment by roblourens** [comment] 2022-12-16 23:14
I will actually fold this into https://github.com/microsoft/vscode-remote-release/issues/937

**Closed by roblourens** 2022-12-16 23:14 UTC
Labels: ssh, feature-request

**Comment by diablodale** [comment] 2022-12-18 01:10
🤔 I checked #937 and I see no fold/mentions other than my own I did back in 2019.
What are you doing/meaning by "fold"?

**Comment by aljaxus** [comment] 2022-12-18 15:20
Why was this issue closed in the first place? The issue is not resolved when using vscode remote on a remote linux machine, which is part of this issue, and the mentioned issue #937 has absolutely nothing to do with it.

**Comment by roblourens** [comment] 2022-12-19 22:15
It sounds like this issue is about configuring gpg signing through ssh via gpg in WSL. #937 covers Remote-SSH supporting a wsl-based ssh workflow and if we implement that, then I believe the original issue here will be resolved.

**Comment by ffMathy** [comment] 2023-01-13 07:34
> Why was this issue closed in the first place? With my limited knowledge it seems like the issue is not resolved when using vscode remote on a remote linux machine, which is part of this issue. On top of that #937 has nothing to do with remote GPG signing.

I'd like to know this too.

@roblourens this happens also on Mac. It is not specific to WSL.

**Comment by roblourens** [comment] 2023-01-13 17:12
Then it's not clear what "this" is, you might be describing a different issue.
