### ISSUE TITLE
Remote SSH plugin 100% remote CPU core usage 

### ISSUE THREAD

**Issue by itsunaev** [microsoft/vscode-remote-release#4348] opened 2021-01-23 17:18 UTC
![remoteHTOP](https://user-images.githubusercontent.com/26726071/105609042-78edd300-5d9e-11eb-8669-e66053025cf5.png)
![remoteHTOPafterVSclientclosed](https://user-images.githubusercontent.com/26726071/105609043-7a1f0000-5d9e-11eb-936b-8cd4e887c4ff.png)
![vscodePSExplorer](https://user-images.githubusercontent.com/26726071/105609044-7a1f0000-5d9e-11eb-9d59-d8de32093b23.png)

Issue Type: <b>Performance Issue</b>

No specific steps, just happens all the time. If VS client is closed, remote continues running problematic process (single core 100% loaded). Issue introduced with or as a result of fix for: https://github.com/microsoft/vscode/issues/109089
Since then, I keep using: VSCodeUserSetup-x64-1.49.3.exe. As issue described here is not reliable and no workaround of it.

Extension version: 0.63.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux arm 4.13.15-sunxi

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (10.77GB free)|
|Process Argv|--crash-reporter-id af2b764b-6361-43ee-bc76-cdb4d6087795|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.207|
|OS|Linux arm 4.13.15-sunxi|
|CPUs|ARMv7 Processor rev 5 (v7l) (4 x 960)|
|Memory (System)|0.48GB (0.15GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    71	  6908	code main
    0	   230	  2356	   gpu-process
    2	   172	  5964	   window (admin [SSH: 192.168.1.207] - Visual Studio Code)
    0	     4	  1832	     C:\Windows\System32\cmd.exe /c (type "C:\Users\itsunaev\AppData\Local\Temp\vscode-linux-multi-line-command-192.168.1.207-342831825.sh" | ssh -T -D 53861 "192.168.1.207" bash) & exit /b 0
    0	     9	  7572	       ssh  -T -D 53861 "192.168.1.207" bash
    0	    92	  2920	     extensionHost
    0	     6	  4928	     console-window-host (Windows internal process)
    0	    77	  7336	   window (Issue Reporter)
    0	    22	  8884	   crashpad-handler
    0	    36	 11324	   utility
    0	    84	 11844	   shared-process

Remote: SSH: 192.168.1.207
CPU %	Mem MB	   PID	Process
   30	     0	  2133	remote agent
    0	     0	  2424	   /bin/bash
    0	     0	  2769	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  2770	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: 192.168.1.207|    Folder (admin): 5545 files|      File types: pyc(1635) py(1611) json(240) js(90) txt(89) svg(52) h(36)
|                  png(36) so(30) md(24)
|      Conf files: package.json(34) launch.json(1) webpack.config.js(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by tstreibl** [comment] 2021-01-24 14:36
Guess same thing happens to me when I open folders on a wsl2 ubuntu which can be changed only with sudu rights (e.g. root or any other folder than home). As long as I stay in home everything seems to be fine. Otherwise tasks "VMMEM" (86%) and "COM Surrogate (6%)" are blocking my CPU. After closing the folder CPU abuse stops. Can reproduce the above.

**Comment by roblourens** [comment] 2021-01-25 04:24
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

This may be another issue that is fixed there

**Comment by itsunaev** [comment] 2021-01-25 16:41
Same thing. I checked with and without remote.autoForwardPorts setting disabled. Attached some screenshots.
![DisableAutoFwd](https://user-images.githubusercontent.com/26726071/105735899-20e4d700-5f2c-11eb-880e-581dd7f71e73.png)
![PS](https://user-images.githubusercontent.com/26726071/105735922-24785e00-5f2c-11eb-95ee-2d57e8fe42b3.png)

**Comment by tstreibl** [comment] 2021-01-25 21:41
> 
> 
> Can you try downloading the Insiders' build, disable the `remote.autoForwardPorts` setting, and tell me whether it happens there? https://code.visualstudio.com/insiders
> 
> This may be another issue that is fixed there

Yes, my special case is fixed with the inside build (with and without port settings). Thanks

**Comment by roblourens** [comment] 2021-01-26 18:24
@itsunaev can you share the full command line args of the busy process? This also may be from some extension. And is it a really large folder that you opened? Same thing opening different folders?

**Comment by itsunaev** [comment] 2021-01-27 15:09
Hello, retried on a small folder same thing. Full command line:
admin     2325  1862 99 14:52 ?        00:06:29
/home/admin/.vscode-server-insiders/bin/dcda88e5a69a52b3a9e141af73b68caae08cb2bf/node
/home/admin/.vscode-server-insiders/bin/dcda88e5a69a52b3a9e141af73b68caae08cb2bf/out/bootstrap-fork
--type=extensionHost
--uriTransformerPath=/home/admin/.vscode-server-insiders/bin/dcda88e5a69a52b3a9e141af73b68caae08cb2bf/out/vs/server/uriTransformer.js

**Comment by roblourens** [comment] 2021-02-10 03:41
Do you have any extensions installed on the remote? Does it make a difference to disable them?

What are you doing before this starts happening? If you are editing files, what types of files?

**Closed** 2021-03-02 23:55 UTC
Labels: ssh
