### ISSUE TITLE
Can't connect to a Windows 10 host from a Linux machine through SSH over VPN

### ISSUE THREAD

**Issue by Adam-Antios** [microsoft/vscode-remote-release#5830] opened 2021-11-08 10:03 UTC
I am trying to connect to a Windows 10 host from a Linux machine (Ubuntu 20.04.3) through SSH over VPN using the Remote-SSH extension but I get the following log while the remote connection does not get established but gets stuck at loading:

    [11:17:36.465] Log Level: 2
    [11:17:36.467] remote-ssh@0.66.0
    [11:17:36.467] linux x64
    [11:17:36.469] SSH Resolver called for "ssh-remote+192.168.1.82", attempt 1
    [11:17:36.469] "remote.SSH.useLocalServer": true
    [11:17:36.470] "remote.SSH.path": undefined
    [11:17:36.470] "remote.SSH.configFile": /home/ad/.ssh/config
    [11:17:36.470] "remote.SSH.useFlock": true
    [11:17:36.470] "remote.SSH.lockfilesInTmp": false
    [11:17:36.471] "remote.SSH.localServerDownload": auto
    [11:17:36.471] "remote.SSH.remoteServerListenOnSocket": false
    [11:17:36.471] "remote.SSH.showLoginTerminal": false
    [11:17:36.471] "remote.SSH.defaultExtensions": []
    [11:17:36.471] "remote.SSH.loglevel": 2
    [11:17:36.472] SSH Resolver called for host: 192.168.1.82
    [11:17:36.472] Setting up SSH remote "192.168.1.82"
    [11:17:36.475] Acquiring local install lock: /tmp/vscode-remote-ssh-ffd05757-install.lock
    [11:17:36.483] Looking for existing server data file at /home/ad/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ffd05757-b3318bc0524af3d74034b8bb8a64df0ccf35549a-0.66.0/data.json
    [11:17:36.484] Using commit id "b3318bc0524af3d74034b8bb8a64df0ccf35549a" and quality "insider" for server
    [11:17:36.487] Install and start server if needed
    [11:17:36.490] PATH: /home/ad/anaconda3/bin:/home/ad/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    [11:17:36.490] Checking ssh with "ssh -V"
    [11:17:36.501] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.3, OpenSSL 1.1.1f  31 Mar 2020
    [11:17:36.504] Using SSH config file "/home/ad/.ssh/config"
    [11:17:36.504] askpass server listening on /run/user/1000/vscode-ssh-askpass-73a45f6d03fb00746c0c7a9901ff5b0035ebf620.sock
    [11:17:36.505] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-dd48a32a3ab2226b3c87d2ede3930750c3ebac1e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","46709","-o","ConnectTimeout=15","-F","/home/ad/.ssh/config","192.168.1.82","powershell"],"dataFilePath":"/home/ad/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ffd05757-b3318bc0524af3d74034b8bb8a64df0ccf35549a-0.66.0/data.json"}
    [11:17:36.505] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/ad/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.66.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code-insiders/code-insiders","VSCODE_SSH_ASKPASS_MAIN":"/home/ad/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.66.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-73a45f6d03fb00746c0c7a9901ff5b0035ebf620.sock"}
    [11:17:36.508] Spawned 5946
    [11:17:36.584] > local-server-1> Spawned ssh, pid=5954
    [11:17:36.587] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.3, OpenSSL 1.1.1f  31 Mar 2020
    [11:17:37.430] Got askpass request: {"request":"a.nt@192.168.1.82's password:"}
    [11:17:37.432] Showing password prompt
    [11:17:37.434] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-addd7a5ea44d6da815127abaeef16804a6df9395.sock
    [11:17:37.434] Writing password prompt to globalState
    [11:17:40.977] Got password response
    [11:17:40.978] Interactor gave response: *************
    [11:17:40.978] Cleaning up other-window auth server
    [11:17:41.140] stderr> Authenticated to 192.168.1.82 ([192.168.1.82]:22).
    [11:17:41.447] > Windows PowerShell
    > Copyright (C) Microsoft Corporation. All rights reserved.
    > 
    > Try the new cross-platform PowerShell https://aka.ms/pscore6
    [11:17:41.520] > 
    [11:17:41.690] > PS C:\Users\a.nt> 
    [11:17:41.779] > e
    [11:17:41.806] > cho 'ready: 11753324d2c5'
    > ready: 11753324d2c5
    > PS C:\Users\a.nt> 
    [11:17:41.863] > u
    [11:17:41.891] > name -rsv
    [11:17:41.961] stderr> uname : The term 'uname' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
    [11:17:41.962] Platform: windows
    [11:17:41.962] Remote command length: 7968/8192 characters
    [11:17:41.991] > PS C:\Users\a.nt> 
    [11:17:41.992] stderr> he spelling of the name, or if a path was included, verify that the path is correct and try again.
    [11:17:41.992] stderr> At line:1 char:1
    [11:17:41.992] stderr> + uname -rsv
    [11:17:41.992] stderr> + ~~~~~
    [11:17:41.992] stderr>     + CategoryInfo          : ObjectNotFound: (uname:String) [], CommandNotFoundException
    [11:17:41.992] stderr>     + FullyQualifiedErrorId : CommandNotFoundException
    [11:17:41.993] stderr>  
    [11:17:42.019] > p
    [11:17:42.048] > owershell -NoProfile
    [11:17:42.101] > Windows PowerShell
    > Copyright (C) Microsoft Corporation. All rights reserved.
    > 
    > Try the new cross-platform PowerShell https://aka.ms/pscore6
    [11:17:42.128] > 
    [11:17:42.229] > PS C:\Users\a.nt> 
    [11:17:42.282] > p
    [11:17:42.284] > owershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "`$remoteSSHConfigurationScript=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.Ge
    [11:17:42.287] > tString([Convert]::FromBase64String('CiR1dWlkPSIxMTc1MzMyNGQyYzUiCiIke3V1aWR9OiBydW5uaW5nIgoiMTE3NTMzMjRkMmM1OiBwYXVzZUxvZyIKJFByb2dyZXNzUHJlZmVyZW5jZT0nU2lsZW50bHlDb250aW51ZScKJG5fPSdiMzMxOGJjMDUyNGFmM
    [11:17:42.288] > 2Q3NDAzNGI4YmI4YTY0ZGYwY2NmMzU1NDlhJwokcD0kZ
    [11:17:42.288] > W52OlBST0NFU1NPUl9BUkNISVRFQ1RVUkUKJGFyY2g9aWYgKCgkcCAtZXEgJ0FNRDY0JykgLW9yICgkcCAtZXEgJ0lBNjQnKSkgeyAneDY0JyB9IGVsc2UgeyAnaWEzMicgfQokb189KEpvaW4tUGF0aCAoUmVzb2x2ZS1QYXRoIH
    [11:17:42.290] > 4pICcudnNjb2RlLXNlcnZlci1pbnNpZGVycycpCiRlbnY6VlNDT0RFX0FHRU5UX0ZPTERFUj0kb18KJGxvZz0iJG9fXC4kbl8ubG9nIgokYWlfPSIkb19cLiRuXy50b2tlbiIKJHNEaXI9IiRvX1xiaW5
    [11:17:42.291] > cJG5fIgokcF89J2luc2lkZXInCiRxXz0iIgokZXh0cz0iIgokZ189JFRydWUKJGh
    [11:17:42.311] > fPSRGYWxzZQokZ2xvYmFsOnJfID0gJEZhbHNlCiRnbG9iYWw6c18gPSAnJwokZ2xvYmFsOmpfID0gJycKJGdsb2JhbDprXyA9ICcnCiRnbG9iYWw6bF8gPSAnJwokZ2xvYmFsOm1fID0gJycKJGdsb2JhbDphal8gPSAnJwpmdW5jdGlvbiBhbl8gewo
    [11:17:42.315] > ibGlzdGVuaW5nT249PSRwb3J0PT0iCiJvc1JlbGVhc2VJZD09d2luZG93cz09Igoib3NWZXJzaW9uPT0kYWhfPT0iCiJhcmNoPT0kYXJjaD09IgoicGxhdGZvcm09PXdpbmRvd3M9PSIKInVucGFja1Jlc3VsdD09JHNfPT0iCiJkaWRMb2NhbERvd25sb2FkPT0kcl89PSIKImRvd25sb2
    [11:17:42.316] > FkVGltZT09JGpfPT0iCiJpbnN0YWxsVGltZT09JGtfPT0iCiJleHRJbnN0YWxsVGltZT09JGxfPT0iCiJzZXJ2ZXJTdGFydFRpbWU9PSRtXz09Igp9CmZ1bmN0aW9uIGlfIHsKcmV0dXJuIFtzeXN0ZW0uZGlhZ25vc3RpY3Muc3RvcHdhdGNoXTo6U3RhcnROZ
    [11:17:42.318] > XcoKTsKfQpmdW5jdGlvbiBxKCRjb2RlKSB7CiIke3V1aWR9OiBzdGFydCIKImV4aXRDb2RlPT0kY29kZT09Igphbl8KIiR7dXVpZH06IGVuZCIKfQpmdW5jdGlvbiBhXyB7CiR0Xz0kUElECndoaWxlICgkVHJ1ZSkgewokdV89K
    [11:17:42.319] > GdjaW0gd2luMzJfcHJvY2VzcyB8ID8gcHJvY2Vzc2lk
    [11:17:42.319] > IC1lcSAkdF8pLnBhcmVudHByb2Nlc3NpZAppZiAoISR1Xykgewoibm8gc3NoZCBwYXJlbnQgcHJvYyIKZXhpdCAwCn0KaWYgKChncHMgLUlkICR1XykuTmFtZSAtZXEgJ3NzaGQnKSB7CnJldHVybiAkdV8KfQokdF89JHVfCn0KfQpmdW5jdGlvbiBiXyB7Cml
    [11:17:42.347] > mICgkdl8pIHsKaWYgKCEoZ3BzIC1JZCAkdl8pKSB7CiJzZXJ2ZXIgZGllZCwgZXhpdCIKZXhpdCAwCn0KfSBlbHNlIHsKaWYgKCEoZ3BzIC1JZCAkc3NoZFBJRCkpIHsKInNzaGQgcGFyZW50IGRpZWQsIGV4aXQiCmV4aXQgMAp9Cn0KfQpmdW5jdGlvbiBjXyB7CiRzPWlfCiJEb3dubG9hZGluZyBzZXJ2ZXI
    [11:17:42.347] > iCiIke3V1aWR9JSUxJSUiCiR3Xz0iIgokeF89aWYgKCRhcmNoIC1lcSAneDY0JykgeyA
    [11:17:42.410] > iLSRhcmNoIiB9IGVsc2UgeyAiIiB9CiR5Xz0ic2VydmVyLXdpbjMyJHhfIiArICR3Xwokc3BsYXQ9QHsKVXJpPSJodHRwczovL3VwZGF0ZS5jb2RlLnZpc3VhbHN0dWRpby5jb20vY29tbWl0OiRuXy8keV8vJHBfIgpUaW1lb3V0U2VjPTIwCk91dEZpbGU9InZzY29kZS1zZXJ2ZXIuemlwIgpVc2VCYXNpY1BhcnNpbmc9JFRydWUKfQpbTmV0LlNlcnZpY2VQb2ludE1hbmFnZXJdOjpTZWN1cml0eVByb3RvY29sID0gJ1RsczEyJwppcm0gQHNwbGF0CiRzLlN0b3AoKQokZ2xvYmFsOmpfID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9CmZ1bmN0aW9uIGRfIHsKJGdsb2JhbDpzXz0nc3VjY2VzcycKJHM9aV8KdHJ5IHsKJHpfPVtTeXN0ZW0uSU8uUGF0aF
    [11:17:42.436] > 06OkdldFJhbmRvbUZpbGVOYW1lKCkKJGFhXz0iJGVudjpURU1QXCR6XyIKIkV4cGFuZGluZyBzZXJ2ZXIgaW50byAkYWFfIgoiJHt1dWlkfSUlMiUlIgpFeHBhbmQtQXJjaGl2ZSAidnNjb2RlLXNlcnZlci56aXAiIC1EZXN0aW5hdGlvblBhdGggIiRhYV8iCm12ICIkYWFfXHZzY29kZS0qXCoiIC1EZXN0aW5hdGlvbiAuCiRzLlN0b3AoKQokZ2xvYmFsOmtfID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9IGNhdGNoIHsKJGdsb2JhbDpzXz0nZXJyb3InCiJGYWlsZWQgdG8gdW56aXAgc2VydmVyLiAtICQoJF8uVG9TdHJpbmcoKSkiCmZfIDM3CmRfCn0KaWYoIShUZXN0LVBhdGggIiRzRGlyXHNlcnZlci5jbWQiKSkgewokZ2xvYmFsOnNfPSdtaXNzaW5nRmlsZXMnCiJEb3dubG9hZGVkIHNlcnZlciBpcyBpbm
    [11:17:42.437] > NvbXBsZXRlLiIKZl8gMzcKZF8KfQp9CmZ1bmN0aW9uIGFrXyB7CiRhcF89W1N5c3RlbS5TZWN1cml0eS5QcmluY2lwYWwuV2luZG93c0lkZW50aXR5XTo6R2V0Q3VycmVudCgpLk5hbWUKJGdsb2JhbDphal8gPSAiZDBjM2JiZDctY2E5Ni00NTU3LWE5YmItMTYzYWE3OGVkYTFiIgpuaSAtaXQgZiAkYWlfIC1Gb3JjZQppY2FjbHMgJGFpXyAvcmVzZXQgL1EKaWNhY2xzICRhaV8gL3NldG93bmVyICIkYXBfIiAvUQppY2FjbHMgJGFpXyAvZ3JhbnQgIiQoJGFwXyk6KFIsVykiIC9RCmljYWNscyAkYWlfIC9pbmhlcml0YW5jZTpyIC9RCltTeXN0ZW0uSU8uRmlsZV06OldyaXRlQWxsTGluZXMoJGFpXywgJGdsb2JhbDphal8pCn0KZnVuY3Rpb24gYWxfIHsKJHM9aV8KaWYoVGVzdC1QYXRoICRsb2cpIHsKZGVsICRsb2cKfQokYWJfPSRzRGlyIC1yZXBsYWNlICcgJywgJ2AgJwpha18KJGFyZ3M9Ii0tc3RhcnQtc2VydmVyIC0taG9zdD0xMjcuMC4wLjEgLS1lbmFibGUtcmVtb3RlLWF1dG8tc2h1dGRvd24gLS1wb3J0PTAgLS1jb25uZWN0aW9uLXNlY3JldCAnJGFpXycgJHFfICRleHRzICo+ICckbG9nJyIKJHNwbGF0PUB7CkZpbGVQYXRoID0gInBvd2Vyc2hlbGwuZXhlIgpXaW5kb3dTdHls
    [11:17:42.438] > ZSA9ICJoaWRkZW4iCkFyZ3VtZW50TGlzdCA9IEAoCiItRXhlY3V0aW9uUG9saWN5IiwgIlVucmVzdHJpY3RlZCIsICItTm9Mb2dvIiwgIi1Ob1Byb2ZpbGUiLCAiLU5vbkludGVyYWN0aXZlIiwgIi1jIiwgIiRhYl9cc2VydmVyLmNtZCAkYXJncyIKKQpQYXNzVGhydSA9ICRUcnVlCn0KIlN0YXJ0aW5nIHNlcnZlcjogJiAnJHNEaXJcc2VydmVyLmNtZCcgJGFyZ3MiCiRnbG9iYWw6dl8gPSAoc3RhcnQgQHNwbGF0KS5JRAokcy5TdG9wKCkKJGdsb2JhbDptXyA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfQpmdW5jdGlvbiBlXyB7CiRnbG9iYWw6cl89JFRydWUKIlRyaWdnZXIgbG9jYWwgc2VydmVyIGRvd25sb2FkIgoiJHt1dWlkfTp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZCIKInBsYXRm
    [11:17:42.439] > b3JtPT13aW5kb3dzPT0iCiJ2c2NvZGVBcmNoPT0kYXJjaD09IgoiZGVzdEZvbGRlcj09JG9fXGJpblw9PSIKImRlc3RGb2xkZXIyPT0kbl89PSIKIiR7dXVpZH06dHJpZ2d
    [11:17:42.440] > lcl9zZXJ2ZXJfZG93bmxvYWRfZW5kIgoiV2FpdGluZyBmb3IgY2xpZW50IHRvIHRyYW5zZmVyIHNlcnZlciBhcmNoaXZlLi4uIgoiV2FpdGluZyBmb3IgJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWcgYW5kIHZzY29kZS1zZXJ2ZXIuemlwIHRvIGV4aXN0Igp3aGlsZSgkVHJ1ZSkgewppZihUZXN0LVBhdGggIiRzRGlyXHZzY29kZS1zY3AtZG9uZS5mbGFnIikgewppZighKFRlc3QtUGF0aCAiJHNEaXJcdnNjb2RlLXNlcnZlci56aXAiKSkgewoiVHJhbnNmZXIgZmFpbGVkIgpxIDMxCn0KIlRyYW5zZmVyIGNvbXBsZXRlIgpkZWwgJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWcKYnJlYWsKfSBlbHNlIHsKU3RhcnQtU2xlZXAgLVNlY29uZHMgMwpiXwp9Cn0KfQpmdW5jdGlvbiBmXygkY29kZSkgewppZiAoJHJfKSB7CiJBbHJlYWR5IGF0dGVtcHRlZCBsb2NhbCBkb3dubG9hZCwgZmFpbGluZyIKcSAkY29kZQp9IGVsc2VpZigkZ18pIHsKZV8KfSBlbHNlIHsKcSAkY29kZQp
    [11:17:42.466] > 9Cn0KZnVuY3Rpb24gYW1fIHsKaWYgKCRleHRzIC1uZSAiIikgewokcz1pXwomICIkc0RpclxzZXJ2ZXIuY21kIiAkcV8gQGV4dHMKJHMuU3RvcCgpCiRnbG9iYWw6bF8gPSAkcy5FbGFwc2VkTWlsbGlzZWNvbmRzCn0KfQpmdW5jdGlvbiBhY3F1aXJlTG9jaygpIHsKJGFjXz0oSm9pbi1QYXRoICIkc0RpciIgInZzY29kZS1yZW1vdGUtbG9jay4kbl8iKQp0cnkgewokbnVsbD1uaSAkYWNfIC1pdCBmIC1lYSBzaQp9IGNhdGNoIHsKIkNvdWxkIG5vdCBjcmVhdGUgc2VydmVyIGxvY2sgZmlsZS4gLSAkKCRfLlRvU3RyaW5nKCkpIgpyZXR1cm4KfQp0cnkgewoiQWNxdWlyaW5nIGxvY2sgb24gJGFjXyIKJGdsb2JhbDpmaWxlID0gW1N5c3RlbS5pby5GaWx
    [11:17:42.467] > lXTo6T3BlbigkYWNfLCAnT3BlbicsICdSZWFkJywgJ05vbmUnKQp9IGNhdGNoIHsKIkluc3RhbGwgYWxyZWFkeSBpbiBwcm9ncmVzcy4uLiAtICQoJF8uVG9TdHJpbmcoKSkiCnEgMjQKfQp9CmZ1bmN0aW9uIHByaW50UmVzdWx0KCkgewoiJHt1dWlkfTogc3RhcnQiCiJTU0hfQVVUSF9TT0NLPT0kZW52OlNTSF9BVVRIX1NPQ0s9PSIKYW5fCiJjb25u
    [11:17:42.467] > ZWN0aW9uVG9rZW49PSRnbG9iYWw6YWpfPT0iCiIke3V1aWR9OiBlbmQiCn0KZnVuY3Rpb24gbWFpbigpIHsKJGdsb2JhbDpzc2hkUElEID0gYV8KaWYoIShUZXN0LVBhdGggJHNEaXIpKSB7CiRtPSJDb3VsZCBub3QgY3JlYXRlIHNlcnZlciBkaXJlY3RvcnkiCnRyeSB7CiRudWxsPW5pIC1pdCBkICRzRGlyIC1mIC1lYSBzaQp9IGNhdGNoIHsKIiRtLiAtICQoJF8uVG9TdHJpbmcoKSkiCnJldHVybgp9CmlmKCEoVGVzdC1QYXRoICRzRGlyKSkgewoiJG0iCnJldHVybgp9Cn0KY2QgJHNEaXIKYWNxdWlyZUxvY2sKdHJ5IHsKIkxvb2tpbmcgZm9yIGV4aXN0aW5nIHNlcnZlciBpbiAkc0RpciIKaWYoVGVzdC1QYXRoICIkc0RpclxzZXJ2ZXIuY21kIikgewoiRm91bmQgaW5zdGFsbGVkIHNlcnZlciIKfSBlbHNlIHsKaWYgKCRoXykgewplXwp9IGVsc2Ugewp0cnkgeyBjXyB9IGNhdGNoIHsKIkRvd25sb2FkIGZhaWxlZC4gLSAkKCRfLlRvU3RyaW5nKCkpIgpmXyAyNQp9Cn0KZF8KfQppZighKEdldC1Qcm9jZXNzIG5vZGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgfCBXaGVyZS1PYmplY3QgUGF0aCAtTGlrZSAiJHNEaXJcKiIpKSB7CmFsXwp9IGVsc2UgewoiU2VydmVyIHdpdGggJG5fIGlzIGFscmVhZHkgcnVubmluZy4iCmFtXwppZiAoVGVzdC1QYXRoICRhaV8pIHsKJGdsb2JhbDphal8gPSAkKGNhdCAkYWlfKQp9Cn0KJGFmXz1AewpQYXRoID0gJGxvZwpQYXR0ZXJuID0gIkV4dGVuc2lvbiBob3N0IGFnZW50IGxpc3RlbmluZyBvbiAoXGQrKSIKfQokYWVfPUB7ClBhdGggPSAkbG9nClBhdHRlcm4gPSAiISEhISBTZXJ2ZXIgdGVybWluYXRlZCBkdWUgdG8gcHJlc2VuY2Ugb2YgQ1ZFLTIwMjAtMTQxNiAhISEhIgp9CiRhZF89KEdldC1EYXRlKS5BZGRTZWNvbmRzKDQpCiRhb189IlNlcnZlciBkaWQgbm90IHN0YXJ0IHN1Y2Nlc3NmdWxseS4gRnVsbCBzZXJ2ZXIgbG9nIGF0ICRsb2cgPj4+Igp3aGlsZSAoKEdldC1EYXRlKSAtbHQgJGFkXykgewppZihUZXN0LVBhdGggJGxvZykgewokYWdfPShzbHMgQGFmXykuTWF0Y2hlcy5Hcm91cHMKaWYoJGFnXykgewokZ2xvYmFsOnBvcnQgPSAkYWdfWzFdLlZhbHVlCmJyZWFrCn0KJGZhaWxlZD0oc2xzIEBhZV8pLk1hdGNoZXMuR3JvdXBzCmlmKCRmYWlsZWQpIHsKJGFvXwpjYXQgJGxvZwoiPDw8IEVuZCBvZiBzZXJ2ZXIgbG9nIgpxIDM2Cn0KfQpzbGVlcCAtTWlsbGlzZWNvbmRzIDMwCn0KaWYgKCEkcG9ydCkgewokYW9fCmNhdCAkbG9nCiI8PDwgRW5kIG9mIHNlcnZlciBsb2ciCnEgMzIKfQp9IGNhdGNoIHsKIlNlcnZlciBmYWlsZWQgdG8gc3RhcnQuIC0gJCgkXy5Ub1N0cmluZygpKSIKfSBmaW5hbGx5IHsKJGZpbGUuQ2xvc2UoKQp9CnRyeSB7CiRnbG9iYWw6YWhfID0gKGdjaW0gV2luMzJfT3BlcmF0aW5nU3lzdGVtKS5WZXJzaW9uCn0gY2F0Y2ggewoiRmFpbGVkIHRvIGZpb
    [11:17:42.468] > mQgV2luZG93cyB2ZXJzaW9uIC0gJCgkXy5Ub1N0cmluZygpKSIKJGdsb2JhbDphaF8gPSAidW5rbm93biIKfQpwcmludFJlc3VsdAoiJHBpZCwgd2F0Y2hpbmcgJHNzaGRQSUQiCndoaWxlICgkVHJ1ZSkgewpiXwpzbGVlcCAzMAp9Cn0KIjExNzUzMzI0ZDJjNTogcmVzdW1lTG9nIgptYWluCg==')))); powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand `$remoteSSHConfigurationScript"
    [11:17:42.541] > 11753324d2c5: running
    [11:17:42.590] > 
    > 11753324d2c5: pauseLog
    > 11753324d2c5: resumeLog
    [11:17:47.742] stderr> #< CLIXML
    [11:17:47.771] > no sshd parent proc
    [11:17:47.772] stderr> <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">gcim : Access denied _x000D__x000A_</S><S S="Error">At line:51 char:6_x000D__x000A_</S><S S="Error">+ $u_=(gcim win32_process | ? processid -eq $t_).parentprocessid_x000D__x000A_</S><S S="Error">+      ~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : PermissionDenied: (root\cimv2:win32_process:String) [Get-CimInstance], CimException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : HRESULT 0x80041003,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
    [11:17:47.815] > PS C:\Users\a.nt> 

Nonetheless, I can normally connect to the Windows 10 host both through the Linux and the VS Code integrated terminal. Moreover, through the Remote-SSH extension I can normally connect to Linux hosts.

**Comment by tanhakabir** [comment] 2021-11-09 02:51
Hmm this issue seems to be a duplicate of https://github.com/microsoft/vscode-remote-release/issues/2648 where you can't connect to a non-admin Windows account. Sorry we haven't had a chance to solve this yet but closing this issue since it's being tracked there

**Comment by tanhakabir** [comment] 2021-11-09 02:52
Some seem to have success with this so you could try it out? https://github.com/microsoft/vscode-remote-release/issues/2648#issuecomment-812183291

**Closed by tanhakabir** 2021-11-09 02:51 UTC
Labels: ssh
