### ISSUE TITLE
VSCode port forwarding view not consistent across multiple windows

### ISSUE THREAD

**Issue by tvvignesh** [microsoft/vscode-remote-release#4135] opened 2020-12-04 13:46 UTC
Steps to Reproduce:

Hi. When I try to open Remote SSH to the same VM across multiple VSCode windows, I see the port forwarding view to be inconsistent. For instance, the below is the view from 2 different VSCode windows (doing SSH to the same machine) - I even waited a while for it to sync.

If you see below, I am not able to see `3030->3030` and `3030->3031` in one of the windows while it shows up in other for the same VM. Shouldn't this be the same for the same SSH target?

**Window 1:**

<img width="155" alt="e1" src="https://user-images.githubusercontent.com/1165845/101170624-bcf90d00-3664-11eb-8624-c133e905acf3.PNG">

**WIndow 2:**

<img width="237" alt="e2" src="https://user-images.githubusercontent.com/1165845/101170651-c4b8b180-3664-11eb-898c-b9a014a8cb79.PNG">

- VSCode Version:

```
Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20201
```
- Local OS Version: Windows 10 Home
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH

Thanks.

**Comment by bamurtaugh** [comment] 2020-12-10 01:16
cc @alexr00

**Comment by alexr00** [comment] 2020-12-10 12:46
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2240

**Closed** 2020-12-10 12:46 UTC
Labels: *duplicate
