### ISSUE TITLE
code-insiders . from WSL shell doesn't open remote session

### ISSUE THREAD

**Issue by MattyMay** [microsoft/vscode-remote-release#788] opened 2019-06-24 17:52 UTC
Note: I know there have been a couple of issues already relating to this, but it seemed people were able to resolve their issues by adding code to their path.  Code-insiders is and has been in my windows path and my ubuntu path inherits this.

Recently, trying to launch code-insiders from within WSL terminal doesn't launch a window with remote connection but rather opens a regular windows instance of code from the directory that Ubuntu was launched, and the terminal echoes "update#setState idle".  From within code I am able to open a new WSL window. 

Forgive me if this has been discussed / solved, but I wasn't able to figure out what was wrong from the previous issues on this topic.  I have tried reinstalling code-insiders, verifying my path, disabling extensions, etc...

- VSCode Version: 1.36.0-insiders (tried both user and system, and previous release)
- Local OS Version: Windows 10 1809
- Remote OS Version: Ubuntu 18.04.1 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open Ubuntu shell
2. Type code-insiders .

**Comment by aeschli** [comment] 2019-06-24 19:20
duplicate of #780

**Closed by aeschli** 2019-06-24 19:20 UTC
