### ISSUE TITLE
Remote WSL should use the default shell of the WSL distribution

### ISSUE THREAD

**Issue by ricardosantos9521** [microsoft/vscode-remote-release#1082] opened 2019-07-31 15:46 UTC
After the update to version 39.* of the Remote - WSL( ms-vscode-remote.remote-wsl) the terminal stop using the default shell of the WSL distribution.

- VSCode Version: 1.37 Insider
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Open a windows with the WSL
2. Open terminal

The terminal should use the default shell of the WSL distribution (as in previous versions of the extension):

![image](https://user-images.githubusercontent.com/20097801/62226734-8c3efe80-b3b2-11e9-8f1b-f3006fc2284b.png)

In the current version of the extension uses sh:
![image](https://user-images.githubusercontent.com/20097801/62226809-a842a000-b3b2-11e9-834e-27aa60c85598.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2019-08-07 18:07
I'm hitting this as well

**Comment by Tyriar** [comment] 2019-08-07 18:57
This was caused by the fix for https://github.com/Microsoft/vscode/issues/77242

**Comment by Tyriar** [comment] 2019-08-07 21:09
This should be fixed soon, in the meantime you can set the shell explicitly: `"terminal.integrated.shell.linux": "/bin/bash"`

**Closed** 2019-08-08 14:39 UTC
Labels: bug, wsl
