### ISSUE TITLE
JumpHost, and centos6 remote host

### ISSUE THREAD

**Issue by kharam1436** [microsoft/vscode-remote-release#1326] opened 2019-08-30 06:59 UTC
At first, thank you for your hard work.

Here is something that I've noticed.

```
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host cssex
    HostName 69.91.198.22
    User root
    IdentityFile ~/.ssh/id_rsa

Host cssaws
    HostName ec2-35-164-227-85.us-west-2.compute.amazonaws.com
    User ec2-user
    IdentityFile ~/.ssh/haram.pem

Host uw_web
    HostName vergil.u.washington.edu
    User kharam
    IdentityFile ~/.ssh/id_rsa

Host ansible
    HostName ansible1.uwb.edu
    User root
    IdentityFile ~/.ssh/id_rsa
    ProxyJump cssex
```

Here is the copy of the configuration file
I cannot access vergil.u.washington.edu. (running centos 6)
I cannot use ProxyJump cssex.

Thank you

**Comment by roblourens** [comment] 2019-09-01 20:57
Please explain what the problem is exactly.

**Comment by kharam1436** [comment] 2019-09-02 03:53
Operating System: Windows 10 18362.295

The error message that I got was:
"Could not establish the connection to "ansible". The process tried to write to a nonexisting pipe"

When I tried to get into `ssh ansible`, it works on the shell; however, it does not work on vscode.

![image](https://user-images.githubusercontent.com/22670652/64089347-895d6380-ccfa-11e9-9a25-de0a23d1a8b1.png)

**Comment by roblourens** [comment] 2019-09-02 17:16
Can you share the log from the Remote-SSH output channel?

**Comment by kharam1436** [comment] 2019-09-02 17:28
```
[17:20:11.710] remote-ssh@0.45.6
[17:20:11.710] win32 x64
[17:20:11.710] SSH Resolver called for "ssh-remote+ansible", attempt 1
[17:20:11.710] SSH Resolver called for host: ansible
[17:20:11.710] Setting up SSH remote "ansible"
[17:20:11.737] Using commit id "f06011ac164ae4dc8e753a3fe7f9549844d15e35" and quality "stable" for server
[17:20:11.741] Testing ssh with ssh -V
[17:20:11.862] ssh exited with code: 0
[17:20:11.862] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[17:20:11.863] Running script with connection command: ssh -o ClearAllForwardings=true ansible bash
[17:20:11.865] Install and start server if needed
[17:20:11.935] > 
[17:20:11.935] Got some output, clearing connection timeout
[17:20:12.422] > ]0;C:\Windows\SYSTEM32\cmd.exe
[17:20:12.431] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[17:20:12.440] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[17:20:12.480] > CreateProcessW failed error:2
> 
[17:20:12.489] > posix_spawn: No such file or directory
> The process tried to write to a nonexistent pipe.
> 
[17:20:12.778] "install" terminal command done
[17:20:12.778] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[17:20:12.778] Received install output: The process tried to write to a nonexistent pipe.
[17:20:12.778] The process tried to write to a nonexistent pipe
[17:20:12.779] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"OfflineError"},"measures":{"resolveAttempts":1,"retries":1}}
[17:20:12.779] ------
```


This is the log from my visual studio code remote, and I noticed the option ` ClearAllForwardings=true`, 


thank you

**Comment by roblourens** [comment] 2019-09-03 03:53
I see that this looks like an issue on windows which might be fixed by a new openssh version: https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777

**Closed by roblourens** 2019-09-03 03:53 UTC
Labels: needs-more-info
