### ISSUE TITLE
code-server insider CLI 1.74.0 "Unknown platform / Exec format error"

### ISSUE THREAD

**Issue by thorgrimjansrud** [microsoft/vscode-remote-release#7631] opened 2022-12-02 12:29 UTC
Seems like there is an issue when running code-server insider 1.74.0 on my 32-bit arm device.
Related to my previous post [#7495](https://github.com/microsoft/vscode-remote-release/issues/7495#top).

- VSCode Version: 1.74.0-insider
- Local OS Version: W11 Pro 21H2
- Remote OS Version: Debian based Armv7l 32-bit
- Remote Extension/Connection Type: vscode.dev tunnel

1.  ./code tunnel  --accept-server-license-terms
![image](https://user-images.githubusercontent.com/48207719/205292464-c62322bc-77e6-401c-964e-dc895eea9594.png)

2. https://Insiders.vscode.dev
![image](https://user-images.githubusercontent.com/48207719/205292135-9df2e54c-adee-46af-9659-1fab6e83e01b.png)

3. Error
[2022-12-02 12:32:55] info [tunnels::connections::relay_tunnel_host] Opened new client on channel 3
[2022-12-02 12:32:57] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:57] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:57] info [rpc.0] Starting server...
[2022-12-02 12:32:57] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:57] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:57] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:57] info [rpc.0] Starting server...
[2022-12-02 12:32:57] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:57] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:57] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:57] info [rpc.0] Starting server...
[2022-12-02 12:32:57] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:57] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:57] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:57] info [rpc.0] Starting server...
[2022-12-02 12:32:57] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:57] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:58] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:58] info [rpc.0] Starting server...
[2022-12-02 12:32:58] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:58] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:58] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:58] info [rpc.0] Starting server...
[2022-12-02 12:32:58] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:58] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:58] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:58] info [rpc.0] Starting server...
[2022-12-02 12:32:58] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:58] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:58] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:58] info [rpc.0] Starting server...
[2022-12-02 12:32:58] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:58] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:58] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:58] info [rpc.0] Starting server...
[2022-12-02 12:32:58] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:32:58] info [rpc.0] Checking /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.log and /home/admin/.vscode-cli/server-insiders/.493a541735b84de36b628750ba716a430669cb7f.pid for a running server...
[2022-12-02 12:32:59] info [rpc.0] Found existing installation at /home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f
[2022-12-02 12:32:59] info [rpc.0] Starting server...
[2022-12-02 12:32:59] warn [rpc.0] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-02 12:33:02] warn [rpc.0] error handling call: UpdatesNotConfigured(UpdatesNotConfigured("Unknown platform, please report this error"))

[Edit 05.12.22]:

Trace/log:

/home/admin/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f/bin/code-server-insiders: line 12: /home/codesys_root/.vscode-cli/server-insiders/bin/493a541735b84de36b628750ba716a430669cb7f/node: cannot execute binary file: Exec format error

**Comment by fsmoreir** [comment] 2022-12-11 09:42
I have exactly the same issue on a armhfv7 machine.

**Comment by fsmoreir** [comment] 2022-12-11 11:35
I´m running code cli in a docker  container.

file node
node: cannot open `node' (No such file or directory)
echo $PATH 
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ls /usr/local/bin
corepack  docker-entrypoint.sh  file-server  http-server  node  nodejs  npm  npx  yarn  yarnpkg

**Comment by fsmoreir** [comment] 2022-12-11 12:11
file node
node: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 4.4.174, with debug_info, not stripped

**Comment by fsmoreir** [comment] 2022-12-11 12:28
:/usr/local/bin# /lib/ld-linux-armhf.so.3 ./node

Welcome to Node.js v18.4.0.
Type ".help" for more information.
> 1+2
3
>

**Comment by fsmoreir** [comment] 2022-12-11 16:18
My log is  a repetition of 
[2022-12-11 16:12:34] info [rpc.22] Starting server...
[2022-12-11 16:12:34] warn [rpc.22] error handling call: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
[2022-12-11 16:12:34] info [rpc.22] Checking /root/.vscode-cli/server-insiders/.f076d553210e9ea65e7bccbfa2f7a786c10fcab2.log and /root/.vscode-cli/server-insiders/.f076d553210e9ea65e7bccbfa2f7a786c10fcab2.pid for a running server...
[2022-12-11 16:12:34] info [rpc.22] Found existing installation at /root/.vscode-cli/server-insiders/bin/f076d553210e9ea65e7bccbfa2f7a786c10fcab2

I've tested with version Visual Studio Code - Insiders CLI 1.75.0 and also stable version CLI 1.74.0

**Comment by chakflying** [comment] 2023-01-07 18:29
I got this when I installed the raspberry pi 4 with a armv7 version OS, but accidentally copied the `config.txt` from a 64bit version. This caused extreme confusion with the OS, with some programs thinking I'm running `aarch64`, and the package manager installing `armhf`. I think the correct way is to reinstall the OS without the incorrect `config.txt`.

**Comment by TechnoSparks** [comment] 2023-01-11 19:00
Having the same problem and it really does seem to be caused by incorrect arch. Attempting to run the commands provided in the comments:
```bash
pi@technopi:~/.vscode-cli/server-insiders/bin/e7b5449579249db344d473370d56a5df9446c826 $ file node
node: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=67e7be9de736c056034656307e986f0b291a247f, with debug_info, not stripped```

I am on Raspbian 11 running on Pi 2 Model B

**Comment by mandar1jn** [comment] 2023-02-02 16:41
Same thing here on a pi 4 4gb (32-bit os version)

**Comment by connor4312** [comment] 2023-02-03 21:16
THis'll be fixed on the next [Insiders CLI](https://code.visualstudio.com/insiders/) on Monday. (Note that you can connect from stable VS Code just fine.)

Note that usual [Linux requirements](https://code.visualstudio.com/docs/remote/linux) exist. Not listed yet on that page, you may need to `apt install libatomic1` if you do not have it already.

**Closed** 2023-02-03 21:30 UTC
Labels: bug, code-server

**Comment by chrmarti** [comment] 2023-02-06 15:07
They busybox issue is tracked in https://github.com/microsoft/vscode-remote-release/issues/7917. My conclusion was that busybox is not sufficient to run VS Code Server, let me now if that somehow changes. Thanks.

**Comment by mandar1jn** [comment] 2023-02-14 20:47
@connor4312 thank you very much for the fix. Downloaded the latest insider and it works like a charm. A lot more performant than using vscode on a real pi over vnc. ~~now to get a ssh connection on the locked down school network and my pi setup will be complete~~
