### ISSUE TITLE
Bug? attaching to remote Docker with VS-Code without opening explorer first does not work.

### ISSUE THREAD

**Issue by De-Ma** [microsoft/vscode-remote-release#5041] opened 2021-05-11 17:05 UTC
- VS Code Version: 1.56.0
- OS Local Machine: Windows10 Home, 10.0.19042 Build 19042, x64
- OS Remote Machine: Ubuntu 18.04.5 (Kernel 4.9.201-tegra)

Expected:
- Connecting to remote Machine, starting Docker, attaching VS-Code, coding

Bug:
- Connecting to remote Machine, starting Docker, attaching VS-Code, Error no running containers
- This problem does not appear when a folder from remote machine is added to Explorer/workspace

Steps to Reproduce:
1. Start new Window of VS-Code
2. Connect with Remote Explorer to remote machine (in my case JetsenNano DevKit)
3. Start remote Docker with Docker extension 
![grafik](https://user-images.githubusercontent.com/75689014/117853680-fcb5c780-b288-11eb-9398-b679e0c724ea.png) 
4. Try to Attach Visual Studio Code 
![grafik](https://user-images.githubusercontent.com/75689014/117853858-2f5fc000-b289-11eb-8e74-4a83b2d56cde.png)
5. Error: 
![grafik](https://user-images.githubusercontent.com/75689014/117853981-50281580-b289-11eb-8c9a-1b7081809b6e.png)
It seems like its using my local installation of Docker and not as expected the remotely (SSH) connected Docker.

Steps to fix/run it:
1. Start new Window of VS-Code
2. Connect with Remote Explorer to remote machine (in my case JetsenNano DevKit)
3. Add folder from remote machine to Explorer 
![grafik](https://user-images.githubusercontent.com/75689014/117854800-1e637e80-b28a-11eb-983a-c94911f54f38.png)
3. Start remote Docker with Docker extension 
![grafik](https://user-images.githubusercontent.com/75689014/117853680-fcb5c780-b288-11eb-9398-b679e0c724ea.png) 
4. Try to Attach Visual Studio Code 
![grafik](https://user-images.githubusercontent.com/75689014/117853858-2f5fc000-b289-11eb-8e74-4a83b2d56cde.png)
5. Working
![grafik](https://user-images.githubusercontent.com/75689014/117856050-718a0100-b28b-11eb-9d27-572f5c4878ed.png)

Does this issue occur when all extensions are disabled?: Yes/No

- Not tried, installed extensions:
![grafik](https://user-images.githubusercontent.com/75689014/117856276-b31aac00-b28b-11eb-86eb-99c8d135c5c1.png)

**Comment by chrmarti** [comment] 2021-05-12 06:36
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4913

**Closed by chrmarti** 2021-05-12 06:36 UTC
Labels: containers
