### ISSUE TITLE
Clicking on a 0.0.0.0 link on a forwarded port in the terminal should be opened as localhost instead

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1810] opened 2019-11-07 18:00 UTC
In order for applications to work when using published ports via `appPort` in devcontainer.json, they need to listen to "*" or "0.0.0.0".  This means that, when the application is run, a link like `https://0.0.0.0:5000` is often seen.

Unfortunately, clicking on this link does not work, because (in this case) port 5000 is mapped specifically to `localhost`  outside of the container.  If you update the link to localhost:5000, it works fine.

This leads to a very confusing workflow where things appear to be forwarded and working - but only work from certain parts of the VS Code UX.

Consequently, we should be doing this translation as a part of the port forwarding logic in place when clicking on links in this case.  The same should be true for things like `vscode.env.openExternal` (though I have not explicitly tested this to know if that already happens).

//cc: @chrmarti @mjbvz

**Comment by Chuxel** [comment] 2019-11-07 18:17
Update, I've seen the following URIs in this situation:

http[s]://0.0.0.0:<port>
http[s]://*:<port>
http[s]://:<port>
http[s]://[::]:<port>

**Comment by mjbvz** [comment] 2019-11-08 19:07
In some setups, people map `localhost` to weird things so we can't just rewrite `0.0.0.0` -> to `localhost` at the VS Code level; it needs to come from the extension

**Comment by chrmarti** [comment] 2019-11-11 08:46
@Chuxel Where do you click on the link? When I click on `http://0.0.0.0:1234` in the terminal the browser opens on `http://127.0.0.1:1234` and the port is being forwarded. The Debug Console doesn't do that yet.

**Comment by chrmarti** [comment] 2019-11-11 09:29
Wait...it's about `appPort` forwarded ports. Might be a duplicate of https://github.com/microsoft/vscode-remote-release/issues/1817. I would still expect it to work from the terminal though (using a random port because the original one is already in use).

**Comment by chrmarti** [comment] 2019-11-11 11:27
Filed https://github.com/microsoft/vscode/issues/84480 for the Debug Console.

**Comment by Chuxel** [comment] 2020-02-26 02:12
@chrmarti Is this and #1817 already resolved?  I see the upstream microsoft/vscode#84480 is closed now.

**Comment by chrmarti** [comment] 2020-02-26 06:20
I think this is microsoft/vscode#84480. Closing.

**Closed by chrmarti** 2020-02-26 06:20 UTC
Labels: containers, ssh
