### ISSUE TITLE
Launching vscode from WSL2 fails: ".../bin/<git-commit-key>/bin/code: not found"

### ISSUE THREAD

**Issue by FlorisCalkoen** [microsoft/vscode-remote-release#6285] opened 2022-02-04 19:21 UTC
When I just opened a new WSL2 Ubuntu 20.04 terminal and ran `code .` to launch the VSCode editor it failed with the following error: 

```
/mnt/c/Users/<USER>/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /home/<USER>/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found
```

I'm running: Microsoft Windows [Version 10.0.18363.2037]

```
wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```

On windows code is still working: 
```
code --version
1.64.0
5554b12acf27056905806867f251c859323ff7e9
x64
```
Not sure if this would be relevant, but `wsl.exe --shutdown` did not resolve the issue. 

Any clue what could be happening?

**Comment by michieliJoe** [comment] 2022-02-04 19:34
Having this same issue.  I noticed that the call references `/home/<user>/.vscode-server-server`.  Removing that folder (as well as my existing .vscode-server folder) did not solve the issue.  Upon running code . again, the same `.vscode-server-server` folder was created.  Perhaps a mistake in the recent update?

**Comment by JoChaw** [comment] 2022-02-04 19:50
Yeah, something in the update fudged things up a bit. Someone figured out a relatively simple temp [fix](https://github.com/microsoft/vscode-remote-release/issues/6280#issuecomment-1029920784) that should work. 

Essentially rename `code-server` in `/.vscode-server-server` to `code` .

**Comment by FlorisCalkoen** [comment] 2022-02-04 19:59
Hmmm.. that's literally what I tried in the first place but that doesn't launch code for me. Just copied  `code-server`  to `code` again same issue. It outputs 

```

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 8000

[20:56:26] Extension host agent started.
```

**Comment by michieliJoe** [comment] 2022-02-04 20:05
Something that worked for me: open VSCode in Windows, use that window to open your remote connection to WSL.  Now `code .` works even after closing the original window.

**Comment by JoChaw** [comment] 2022-02-04 20:14
Ah, guess some configuration is a bit different between our machines then. That sucks. 

Hopefully michieliJoe's suggestion works.

**Comment by FlorisCalkoen** [comment] 2022-02-04 20:20
Yup, solution from @michieliJoe works! Thanks both!

**Comment by pedroguilhermesilva** [comment] 2022-02-04 22:31
I did what @michieliJoe told and it works here. Thanks!

**Comment by tommyokeefe** [comment] 2022-02-05 01:58
Thanks @michieliJoe 👏🏻

**Comment by jason-galea** [comment] 2022-02-05 03:56
Thanks @michieliJoe!

Open VS Code in Windows --> Click the "><" button on the bottom left --> "New WSL Window"

**Comment by nitishpatel** [comment] 2022-02-05 04:34
> Thanks @michieliJoe!
> 
> Open VS Code in Windows --> Click the `><` button on the bottom left --> "New WSL Window"
> 
> This will install the server extension for WSL, which fixes `code .`

Thanks this works fine!!

**Comment by kjayantmenon** [comment] 2022-02-05 06:03
@michieliJoe - your solution works!
This issue was killing me since last night.

**Comment by plloppii** [comment] 2022-02-05 06:15
So damn weird but thank you so much for the solution.

**Comment by afornagieri** [comment] 2022-02-05 12:52
> Something that worked for me: open VSCode in Windows, use that window to open your remote connection to WSL. Now `code .` works even after closing the original window.

Thanks, what a weird solution

**Comment by ganeshh123** [comment] 2022-02-05 13:58
> Something that worked for me: open VSCode in Windows, use that window to open your remote connection to WSL. Now `code .` works even after closing the original window.

Thanks a lot!

**Comment by 21Sal** [comment] 2022-02-05 15:38
I think the issue is caused by an outdated version for the "Remote - WSL" extension. Updating that solved the issue for me, and doesn't create the weirdly named ".vscode-server-server" folder.

**Comment by pmagwene** [comment] 2022-02-05 16:55
I think this issue is affecting remote connections to Linux hosts as well.

**Comment by tommy-yoon** [comment] 2022-02-05 23:22
I had the same problem and as suggested above, I started VSCode from Windows and opened a workspace file in WSL using the "Open Workspace From File" menu. 
Then it started installing "VS Code Server for x64" and it is working fine now.

**Comment by richardabear** [comment] 2022-02-06 08:36
Still an issue.

**Comment by hmu332233** [comment] 2022-02-06 10:56
> Something that worked for me: open VSCode in Windows, use that window to open your remote connection to WSL. Now `code .` works even after closing the original window.

Thanks!

**Comment by digitlimit** [comment] 2022-02-06 16:46
Try this:
Open Vscode by running `code .` inside your WSL project directory by using Powershell
![image](https://user-images.githubusercontent.com/2041419/152691464-35996e0c-2b61-45f6-9eb9-eedbd3b9bf07.png)

Then from the VScode, try to open an existing project from **File -> Open Recent**, then you get this:

![image](https://user-images.githubusercontent.com/2041419/152691404-50d24d8f-f142-4bd8-80e4-b87c80cdc4be.png)

Allow it to run, then after you are good again

**Comment by slydor** [comment] 2022-02-07 09:34
Had the same issue. I tried to basically reset the WSL extension in vscode and it also worked:

- close all VScode instances
- in Windows, remove all versions of `ms-vscode-remote.remote-wsl-` in the directory `C:\Users\<user>\.vscode\extensions`
- Open VScode -> install WSL extension again
- From WSL: just run code <repo>

**Comment by marwan-nwh** [comment] 2022-02-07 10:05
@slydor The solution above didn't work for me, but your solution worked, thanks very much. ❤️

**Comment by juliannevela** [comment] 2022-02-07 19:10
@michieliJoe 🙌🏻 Thank you!! I'm starting a new dev job today and went to clone down some code and WSL wasn't working! 🤦🏻 This cleared up the issue, though, and everything is running normally again! Thanks!

**Comment by Keval2124** [comment] 2022-02-09 06:28
Can someone help me I am getting this error
`/mnt/c/Users/username/.vscode/extensions/ms-vscode-remote.remote-wsl-0.64.2/scripts/wslCode.sh: 63: /home/username/.vscode/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/bin/remote-cli/code: not found`

I tried from @[slydor](https://github.com/slydor) it didn't work at all

> Had the same issue. I tried to basically reset the WSL extension in vs code and it also worked:
> 
> * close all VScode instances
> * in Windows, remove all versions of `ms-vscode-remote.remote-wsl-` in the directory `C:\Users\<user>\.vscode\extensions`
> * Open VScode -> install WSL extension again
> * From WSL: just run code

Also tried [nitishpatel](https://github.com/nitishpatel) method it still didn't work at all

> Thanks @michieliJoe!
> Open VS Code in Windows --> Click the `><` button on the bottom left --> "New WSL Window"
> This will install the server extension for WSL, which fixes `code .`

I have also tried installing vs code in wsl and reinstalling but the error does not go to all

Can someone plz help me out here?

**Comment by bamurtaugh** [comment] 2022-02-24 00:34
Hi all, thanks for the great discussion and workarounds / fixes. Are folks still experiencing this?

**Comment by cotymckinney** [comment] 2022-02-27 04:47
> Hi all, thanks for the great discussion and workarounds / fixes. Are folks still experiencing this?

@bamurtaugh can confirm that this is still an issue.  VSCode version 1.64.2, Windows 11 WSL2 Ubuntu.

**Comment by bamurtaugh** [comment] 2022-02-28 17:32
Thanks for confirming @cotymckinney. Does trying in the latest VS Code Insiders (v 1.65.0-insider) make any difference?

**Comment by cotymckinney** [comment] 2022-02-28 17:44
> Thanks for confirming @cotymckinney. Does trying in the latest VS Code Insiders (v 1.65.0-insider) make any difference?

@bamurtaugh after a quick check it does **<ins>NOT</ins>** appear to be happening with the latest (1.65) insiders build.

**Comment by bamurtaugh** [comment] 2022-02-28 20:46
Thank you for checking @cotymckinney! Let's close this for now, and I'm happy to reopen if you or other folks experience this again in Stable/Insiders versions after 1.65.

**Closed by bamurtaugh** 2022-02-28 20:46 UTC
Labels: wsl, needs more info

**Comment by Tim-mhn** [comment] 2022-03-04 04:55
Make sure that the Remote - WSL extension is updated to the latest version. I ran into the same issue just today and [nitishpatel](https://github.com/nitishpatel) fix wouldn't work. Spent some time on it until I noticed that I had `extensions.autoUpdate: false` in my user settings file. Updating Remote - WSL extension to 0.64.2 fixed everything
