### ISSUE TITLE
WSL doesn't start anymore on latest slow ring insider

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-release#3463] opened 2020-08-03 07:05 UTC
- VSCode Version: 1.48.0
- Local OS Version:  19042.423
- Remote OS Version: Ubunto 20
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Reboot the machine
2. Open a workspace hosted in WSL

<img width="1173" alt="capture" src="https://user-images.githubusercontent.com/1931590/89154905-155db800-d568-11ea-9ea1-1a8fdfa0dd19.png">

Now open a WSL bash and cd into `mnt/c` and the do `ls -la` you get

<img width="434" alt="capture" src="https://user-images.githubusercontent.com/1931590/89154963-33c3b380-d568-11ea-9206-f2d44f389e3b.png">

To recover from this you can do:

- open PS prompt and run `wsl --shutdown`
- open an WSL prompt
- open a WSL workspace. This time the workspace opens successfull and `mnt/c` exists.

**Comment by aeschli** [comment] 2020-08-13 13:40
I would say this is a duplicate of https://github.com/microsoft/WSL/issues/5552

**Closed by aeschli** 2020-08-13 13:40 UTC
Labels: wsl
