### ISSUE TITLE
Failed to establish connection to Raspberry Pi -- "The remote host's architecture is not supported"

### ISSUE THREAD

**Issue by neilbalch** [microsoft/vscode-remote-release#1691] opened 2019-10-18 20:39 UTC
- VSCode Version: 1.39.2
- Local OS Version: Windows 10 -- 1903
- Remote OS Version: Raspbian Buster, fully updated
- Remote Extension/Connection Type: _**SSH**_/Docker/WSL

Steps to Reproduce:

1. Attempt to connect via `ssh` to a Raspberry Pi (_zero_) over the LAN.
2. Connection fails, printing below to the "Output" panel:

```
[07:57:44.506] > pi@10.210.2.176's password: 
[07:57:44.507] Showing password prompt
[07:57:49.866] Got password response
[07:57:49.866] "install" wrote data to terminal: "*********"
[07:57:49.878] > 
> 
[07:57:50.635] > 79e5c4cb1ef5: running
> 
[07:57:50.673] > Unsupported architecture: armv6l
> 
[07:57:50.682] > 79e5c4cb1ef5##27##
> 
[07:57:51.036] "install" terminal command done
[07:57:51.037] Install terminal quit with output: 79e5c4cb1ef5##27##
[07:57:51.037] Received install output: 79e5c4cb1ef5##27##
[07:57:51.039] Unsupported architecture
[07:57:51.041] Resolver error: The remote host's architecture is not supported
[07:57:51.054] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"ExitCode","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","gotUnrecognizedPrompt":"0","remoteInConfigFile":"1"},"measures":{"resolveAttempts":1,"exitCode":27,"retries":1}}
[07:57:51.063] ------
```

Does this issue occur when you try this locally?: Yes/_**No**_
Does this issue occur when you try this locally and all extensions are disabled?: Yes/_**No**_

Please let me know what other debug information would be useful to help resolve the problem. Thank you very much for your time!

**Comment by JtMotoX** [comment] 2019-10-18 23:45
https://github.com/microsoft/vscode-remote-release/issues/669

**Comment by egamma** [comment] 2019-10-21 07:11
closing as a duplicate of #669 (thanks @JtMotoX)

**Closed by egamma** 2019-10-21 07:11 UTC
Labels: *duplicate
