### ISSUE TITLE
Activity bar icon disappears

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#806] opened 2019-06-25 17:16 UTC
Found while testing https://github.com/microsoft/vscode-remote-release/issues/792

Issue Type: <b>Bug</b>

1. Have some extensions that contribute activity bar icons, like GitLens, installed
2. Do a fresh install of remote-wsl extension
2. Run the `Remote-WSL: Reopen window in WSL` command

Not all activity bar icons load:
![missing_gitlens_icon](https://user-images.githubusercontent.com/3672607/60118949-38495600-9732-11e9-9ecd-d7e130594d41.png)

Extension version: 0.38.2
VS Code version: Code - Insiders 1.36.0-insider (e80dd4f217db6e230d311a87fdf4276f740f6445, 2019-06-25T05:19:01.461Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by RMacfarlane** [comment] 2019-06-25 17:22
Actually, this doesn't seem limited to the activity bar, there are other SVGs that aren't loading, like the git inline commands:
![git_icons](https://user-images.githubusercontent.com/3672607/60119377-24eaba80-9733-11e9-8738-a452834a343f.png)

**Comment by Tyriar** [comment] 2019-06-25 17:38
GHPR ext also hidden until the Window is loaded:

![image](https://user-images.githubusercontent.com/2193314/60120302-5feded80-9735-11e9-8ee2-ec370bf597ff.png)

**Comment by sandy081** [comment] 2019-06-26 13:31
Filed a separate issue for activity bar icons. This is different because I do not load icon until remote server is loaded.

**Comment by aeschli** [comment] 2019-07-18 13:58
duplicate of #966

**Closed by aeschli** 2019-07-18 13:58 UTC
