### ISSUE TITLE
Wsl downloading script not used .bash_profile and .bashrc

### ISSUE THREAD

**Issue by ice2heart** [microsoft/vscode-remote-release#432] opened 2019-05-23 08:18 UTC
- VSCode Version:
Version: 1.35.0-insider (user setup)
Commit: 94f7de61ece171f4390ece488a220d22cbb0fddd
Date: 2019-05-23T05:19:33.101Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299
- Local OS Version: windows 10 enterprise 1709
- Remote OS Version: debian 10
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. limit internet access
2. setup proxy server in .bashrc like `export http_proxy=127.0.0.1:80`
3. try to run WSL extension

Possible way to solve problem:
Use `bash -ci` instead of `bash -c` in file 'wslDaemon.js'

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment] 2019-05-23 10:55
The plan is to do the downloading on the client (Window side)

**Comment by ice2heart** [comment] 2019-05-23 11:00
Ok. But use `-ci` can help other people who use somehow env variable.

**Comment by aeschli** [comment] 2019-05-23 13:33
We just removed `-ci`as commands in the shell profiles interfered with the way we started the server.

**Comment by virgilwashere** [comment] 2019-05-23 21:25
> We just removed `-ci`as commands in the shell profiles interfered with the way we started the server.

@aeschli, before `Remote Development`, I was using this to start terminals in WSL, to control nvm/node/ssh-agent environment.  

```json
"terminal.integrated.shellArgs.windows": [
    "--rcfile $HOME/.bashrc.d/bashrc-vscode -i",
],
```

Currently reacting to changes by linking `.bashrc` to my vscode profile and allowing my terminal program to launch `bash -l -i` to active `.profile` and my "normal" `.bashrc`.

## Suggestion

The `--rcfile` option could allow vscode (server) to have a deterministic location for a `.bashrc` file somewhere relevant like : 

- [ ] `~/.vscode-remote/data/Machine/.bashrc`
- [ ] `~/.vscode-remote/data/Machine/vscode.bashrc`

**Comment by WSLUser** [comment] 2019-05-24 12:59
I like how nobody thinks about the other shells that get used (FISH and ZSH in particular come to mind). Specifying a specific shell isn't the right way. Going directly to `.profile` would be better as every shell loads that.

**Comment by aeschli** [comment] 2019-05-27 07:04
To give more context:
- the script that checks and updates the VS Code Server is run without any shell startup scripts. That's a fix as there were several issues where instructions in the startup scrips interfered.
- when starting the server, we use the configured shell ($SHELL -ic)

There are other reported issues reported about download/connectivity issues, so moving the download to the client side (in Windows) is planned anyways

**Comment by kybom** [comment] 2019-05-27 09:37
Sometimes,vscode has to install ext with https proxy,and is connecting to remote linux on the LAN. If moving the download to the client side,there could be a conflict.Maybe need an option.

**Comment by aeschli** [comment] 2019-06-21 09:57
In the upcoming version we now download the server on the Windows side. That way we avoid problems with missing proxy settings or missing certificates.

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/79

**Closed by aeschli** 2019-06-21 09:57 UTC
Labels: wsl
