### ISSUE TITLE
Support Build Args during Docker Build

### ISSUE THREAD

**Issue by eedwards-sk** [microsoft/vscode-remote-release#1857] opened 2019-11-16 00:05 UTC
I seem to be unable to specify build args during the dev container build process.

https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

I want to perform an npm install during the build process, but this requires providing an environment variable for npm private registry authentication.

a build arg would be the way to accomplish this (an env var)

I would like a way to provide build args during the build process, from file (so e.g. an `.env` file), e.g. `"build_arg_file": "npmjs.env",` :

```json
{
	"name": "foo",
	"context": "..",
	"dockerFile": "Dockerfile",
	"build_arg_file": "npmjs.env",    
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	"extensions": [
		"dbaeumer.vscode-eslint"
	]
}
```

**Comment by Chuxel** [comment] 2019-11-16 00:13
I believe this is a dupe of #46. Lets continue chatting as needed over there. Would be great if you would upvote as well!

**Closed by Chuxel** 2019-11-16 00:13 UTC
