### ISSUE TITLE
Resolving the authority ssh-remote failed

### ISSUE THREAD

**Issue by msuardi** [microsoft/vscode-remote-release#1418] opened 2019-09-16 08:41 UTC
I can't connect to a remote server due to this errors:
"Resolving the authority ssh-remote failed", "Failed to connect to the remote extension host server (Error: y.onDidWriteData is not a function)"
I have tried to uninstall, reinstall, downgrade the extension and also to remove the .vscode folders on the remote server.
I have also tried another server and I have the same problem.
I have installed the last version of vscode insider and last versione of remote-ssh.

Extension version: 0.46.0
VS Code version: Code - Insiders 1.39.0-insider (d157c2e941cae17acb79bf26a70bbfad732bdc83, 2019-09-16T06:06:10.647Z)
OS version: Windows_NT x64 10.0.16299

**Comment by doracl** [comment] 2019-09-16 08:52
`[08:51:03.393] win32 x64
[08:51:03.394] SSH Resolver called for "ssh-remote+172.16.10.246", attempt 1
[08:51:03.394] SSH Resolver called for host: 172.16.10.246
[08:51:03.394] Setting up SSH remote "172.16.10.246"
[08:51:03.416] Using commit id "d157c2e941cae17acb79bf26a70bbfad732bdc83" and quality "insider" for server
[08:51:03.438] Testing ssh with ssh -V
[08:51:03.472] ssh exited with code: 0
[08:51:03.472] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[08:51:03.472] Running script with connection command: ssh -D 52127 172.16.10.246 bash
[08:51:03.473] Install and start server if needed
[08:51:03.474] "install" process failed: TypeError: y.onDidWriteData is not a function
[08:51:03.474] y.onDidWriteData is not a function
[08:51:03.474] ------`

**Comment by evalufran** [comment] 2019-09-16 11:37
same issue here 


[10:57:39.525] remote-ssh@0.46.0
[10:57:39.525] win32 x64
[10:57:39.526] SSH Resolver called for "ssh-remote+ddserver", attempt 1
[10:57:39.527] SSH Resolver called for host: ddserver
[10:57:39.527] Setting up SSH remote "ddserver"
[10:57:39.618] Using commit id "d157c2e941cae17acb79bf26a70bbfad732bdc83" and quality "insider" for server
[10:57:39.622] Testing ssh with ssh -V
[10:57:39.777] ssh exited with code: 0
[10:57:39.778] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[10:57:39.778] Using SSH config file "C:\Users\Eva\remoteconfig.config"
[10:57:39.778] Running script with connection command: ssh -D 50411 -F C:\Users\Eva\remoteconfig.config ddserver bash
[10:57:39.782] Install and start server if needed
[10:57:39.785] "install" process failed: TypeError: y.onDidWriteData is not a function
[10:57:39.786] y.onDidWriteData is not a function
[10:57:39.786] ------

**Comment by egamma** [comment] 2019-09-16 13:18
Duplicate of #1417

**Closed by egamma** 2019-09-16 13:18 UTC
