### ISSUE TITLE
Test: DnD from vscode to local removes filename's leading dot

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-remote-release#815] opened 2019-06-25 18:53 UTC
Testing #664

- Use Docker to open https://github.com/Microsoft/vscode-remote-try-node
- Drag .gitignore to desktop
- It becomes `gitignore`

**Comment by isidorn** [comment] 2019-06-26 09:06
This can be reproduced with vscode stable for local to local.
I checked and we properly set the `downloadURL`, the issue is that Chrome for some reason removes the leading `.` in the filename.
There is nothing we can do here. since it is a chrome limitation.
I could keep this open as an upstream issue, but I do not think it is big, thus I prefer to close it.

Feel free to reopen if you prefer it that way.

**Closed by isidorn** 2019-06-26 09:06 UTC
