### ISSUE TITLE
SSH Remote generates telemetry logs under ~/c:

### ISSUE THREAD

**Issue by espresso3389** [microsoft/vscode-remote-release#7478] opened 2022-11-05 12:09 UTC
SSH Remote mistakenly generates telemetry logs under `~/c:`.
It seems the remote SSH uses Windows's local user profile directory location to generate telemetry logs.

```
$ find ~/c:
/home/kurage/c:
/home/kurage/c:/Users
/home/kurage/c:/Users/kawasaki
/home/kurage/c:/Users/kawasaki/AppData
/home/kurage/c:/Users/kawasaki/AppData/Roaming
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221022T103147
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221022T103147/window3
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221022T103147/window3/exthost
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221022T103147/window3/exthost/telemetry.log
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221021T132841
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221021T132841/window7
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221021T132841/window7/exthost
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221021T132841/window7/exthost/telemetry.log
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221021T132841/window5
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221021T132841/window5/exthost
/home/kurage/c:/Users/kawasaki/AppData/Roaming/Code - Insiders/logs/20221021T132841/window5/exthost/telemetry.log
```

- VSCode Version:
Version: 1.74.0-insider (user setup)
Commit: e764c5b816a99eb8673b2fc4fc028827f202872f
Date: 2022-11-04T05:18:32.818Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25236
Sandboxed: Yes
- Local OS Version:
OS: Windows_NT x64 10.0.25236
- Remote OS Version:
Ubuntu 22.04 or WSL at least
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
SSH

Steps to Reproduce:

1. Connect any remote server
2. Check your home directory on the remote machine

**Comment by eleanorjboyd** [comment] 2022-11-08 18:29
This is a duplicate of this issue: https://github.com/microsoft/vscode/issues/163523 which has been fixed already and is in vscode insiders. It will go out stable in our next release. Thanks!

**Closed by eleanorjboyd** 2022-11-08 18:29 UTC
Labels: ssh
