### ISSUE TITLE
Enable setting HTTP proxies for VSC server with Remote - SSH

### ISSUE THREAD

**Issue by EricHripko** [microsoft/vscode-remote-release#5727] opened 2021-10-15 15:30 UTC
# Overview
It seems like remote VS Code instances with _Remote - SSH_ extensions are using the proxy configuration of the client environment. That doesn't always work as developer workstation may use a different set of proxies (or no proxies) unlike the target server being remoted to. Possibly related issue https://github.com/microsoft/vscode-remote-release/issues/957.

# Environment
- Version of VS Code: _1.61.0_
- What type of remote connection you were using: _SSH_
- Your operating system: _Windows_
- The remote operating system you are connecting to: _Linux_
- List of extensions that you have installed: _attempting to install [C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)_

# Steps to reproduce
- Have a local environment that doesn't require proxies or uses a different set of proxies from the target server
- Connect to the target server via _Remote - SSH_
- Attempt to install [C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension
- After a while, the extension will be installed and will try to install its dependencies
- Dependencies will eventually fail to install:

```
Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 15 seconds... Failed. Retrying...Waiting 15 seconds... Failed. Retrying...Waiting 15 seconds... Failed. Retrying...Waiting 15 seconds... Failed. Retrying...Waiting 15 seconds... Failed. Retrying...Waiting 15 seconds... Failed to download https://go.microsoft.com/fwlink/?linkid=2175018
Failed at stage: downloadPackages
Error: Failed to establish a socket connection to proxies: ["PROXY someredactedproxyhost"]
```

- Observe the failure due to VSCode server attempting to use client proxies (`someredactedproxyhost` is what my laptop is using and isn't applicable to the target server)

While the reproduction case use _C/C++_ extension, this also applies to any other extension that downloads additional dependencies.

**Comment by chrmarti** [comment] 2021-10-19 08:52
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/986, continuing there.

**Closed as completed by chrmarti** 2021-10-19 08:52 UTC
Labels: *duplicate, ssh, proxy
