### ISSUE TITLE
Opening a container prompts for language extension suggestions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#4608] opened 2021-03-05 22:27 UTC
On the latest Insiders:

1. Have one or more language packs installed (I do for testing things)
2. Open a new container
3. Get notification spam for each language page

![](https://memes.peet.io/img/21-03-9907e903-30ec-49b5-8e52-17622fd35d87.png)

**Comment by chrmarti** [comment] 2021-03-08 07:47
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4617

**Closed by chrmarti** 2021-03-08 07:47 UTC
Labels: containers
