### ISSUE TITLE
remote.autoForwardPortsSource setting getting overridden

### ISSUE THREAD

**Issue by ssmall** [microsoft/vscode-remote-release#4997] opened 2021-05-04 00:24 UTC
Issue Type: <b>Bug</b>

Every time I run Developer: Reload Window, the following line gets added to my remote settings.json:

```json
"remote.autoForwardPortsSource": "output"
```

When I change this value to `process` via the Settings Explorer, this line gets automatically removed from `settings.json`, but then gets added back when I Reload Window again. It seems the only way I can get the setting to persist is by manually editing `settings.json` to set it to `"process"`.

Extension version: 0.65.4
VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.4.0
Remote OS version: Linux x64 5.10.26-1rodete1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id a277b0b1-c991-411f-977e-011c8c3b13ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: spencersmall.c.googlers.com|
|OS|Linux x64 5.10.26-1rodete1-amd64|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (16 x 2199)|
|Memory (System)|62.81GB (43.17GB free)|
|VM|0%|
</details>

**Comment by alexr00** [comment] 2021-05-04 08:51
@ssmall this is duplicate of https://github.com/microsoft/vscode/issues/117189 which is already fixed in our insiders build. 

You can download insiders now to get the fix immediately (it's usually pretty reliable, but this week it should be extra reliable because we're getting ready to release), or you can wait for the next stable release, which will likely occur this week.

**Closed by alexr00** 2021-05-04 08:51 UTC
