### ISSUE TITLE
devcontainer cli macOS permissions are wrong

### ISSUE THREAD

**Issue by davidpcaldwell** [microsoft/vscode-remote-release#7012] opened 2022-08-02 20:57 UTC
- VSCode Version: 1.69.2
- Local OS Version: macOS 12.5
- Remote OS Version: N/A
- Remote Extension/Connection Type: Containers
- Logs:

Steps to Reproduce:

1. Install the Remote Development Extension Pack
2. Try to run the devcontainer CLI
3. Observe "permission denied"

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

I tried uninstalling and reinstalling the extension pack, as well as the individual container extension, with no change.

This is a regression of some kind -- I had a series of scripts set up that ultimately invoked the devcontainer CLI, and they worked for a long time. Then they suddenly stopped working, I think pretty recently (last month or two?). I just started manually opening the containers using "Open in Container" from the main VSCode UI.

Today I got around to investigating the problem with the scripts and found the permissions problem:
```
$ ls -l "$HOME/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin"
total 56
-rw-r--r--  1 dc471n  staff  2084 Jul 11 09:45 devcontainer
-rw-r--r--  1 dc471n  staff  1108 Jul 11 09:45 devcontainer.cmd
-rw-r--r--  1 dc471n  staff    75 Jul 11 09:45 remote-containers-path
-rw-r--r--  1 dc471n  staff    59 Jul 11 09:45 vscode-app-root
-rw-r--r--  1 dc471n  staff    64 Jul 11 09:45 vscode-machine-id
-rw-r--r--  1 dc471n  staff    99 Jul 11 09:45 vscode-path
-rw-r--r--  1 dc471n  staff     6 Jul 11 09:45 vscode-quality
```

**Comment by davidpcaldwell** [comment] 2022-08-11 19:30
Possibly fixed by https://github.com/devcontainers/cli/issues/83? I don't have an easy test case at the moment since I implemented a workaround which sets the executable bit on my machine. I can look into it a bit.

**Comment by chrmarti** [comment] 2022-12-05 14:45
Closing as duplicate of https://github.com/devcontainers/cli/issues/83. Thanks.

**Closed by chrmarti** 2022-12-05 14:45 UTC
Labels: containers
