### ISSUE TITLE
Cannot start Remote Container - Cannot read property 'mntNS' of undefined

### ISSUE THREAD

**Issue by zombiemaker** [microsoft/vscode-remote-release#4242] opened 2020-12-29 21:37 UTC
- VSCode Version: 1.52.1
- Local OS Version:  Windows 10 Pro x64 2004 Build 19041.685
- Remote OS Version:  Ubuntu 18.04 for WSL and UBI 8.2 for container
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1.  Start VSC from WSL folder containing VSC project with remote container configuration
2.  Select the Remote-Container command to Reopen in Container
3.  During the container startup process, the error is generated

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

The error message is posted in the remoteContainers log file:

Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "

TypeError: Cannot read property 'mntNS' of undefined
	at V (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.154.1\dist\extension.js:1:640813)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.t.injectIntoContainer (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.154.1\dist\extension.js:1:637863)
	at async g (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.154.1\dist\extension.js:1:812172)
	at async Object.t.openDockerfileDevContainer (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.154.1\dist\extension.js:1:817469)

This error started occurring after updating VSC to 1.152.0.

This error occurs in the Insiders version of Visual Studio Code.  
I have uninstalled and re-installed Visual Studio Code.  
I have tried older releases of the Remote Container and had the same issue.

When I revert to version 1.51.1 of VSC and use v0.148.1 of Remote Containers extension, everything works.

**Comment by chrmarti** [comment] 2021-01-04 16:29
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4217.

**Closed by chrmarti** 2021-01-04 16:29 UTC
Labels: containers
