### ISSUE TITLE
Remote Explorer: Do not show WSL contribution on OS X

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1978] opened 2019-12-05 01:13 UTC
We should hide the WSL contribtion to the Remote Explorer on OS X.

![image](https://user-images.githubusercontent.com/172399/70195044-5f308e80-16b9-11ea-9c34-0afc127246d7.png)

**Comment by alexr00** [comment] 2019-12-05 08:57
Duplicate of https://github.com/microsoft/vscode/issues/86209

**Closed** 2019-12-05 08:57 UTC
Labels: *duplicate
