### ISSUE TITLE
Directly open folder to WSL mode

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode-remote-release#5040] opened 2021-05-11 21:41 UTC
So there is https://github.com/microsoft/vscode-remote-release/issues/585#issuecomment-536580102

and I was wondering if it is also possible to expand this in a way to target WSL. 

My use case is that I click "Open in VS Code" for a project in my git gui client and then have to manually switch it to WSL mode. If I could make a custom "Open in VS Code (WSL)" action that would allow me to get rid of that step. 

Maybe something like `code --remote wsl+distroname .`

**Comment by bamurtaugh** [comment] 2021-05-26 15:44
Thanks for the request! Closing as I believe this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/120, but if I've misunderstood the request, please let me know.

**Closed by bamurtaugh** 2021-05-26 15:44 UTC
Labels: wsl

**Comment by Stanzilla** [comment] 2021-05-26 15:47
@bamurtaugh Ah I guess kinda? Thanks for pointing me there!

**Comment by bamurtaugh** [comment] 2021-05-26 15:54
No problem @Stanzilla! You can also already use `code .` from a WSL terminal to open VS Code connected to Remote-WSL/in WSL mode, not sure if that was also a consideration as part of this issue.

**Comment by Stanzilla** [comment] 2021-05-26 16:05
@bamurtaugh Oh lovely! That actually works great, thanks again!

**Comment by Stanzilla** [comment] 2021-05-28 16:53
@bwateratmsft actually I noticed that this does not work well with the included vs code terminal. I always get errors about CRLF in files like it isn't **really** hooked up properly with WSL

**Comment by bamurtaugh** [comment] 2021-06-02 00:06
@Stanzilla Perhaps the info here might help? https://github.com/microsoft/vscode-remote-release/issues/206#issuecomment-492828769
