### ISSUE TITLE
[Remote-SSH Bug]: Asking for platform at every reload

### ISSUE THREAD

**Issue by aglasson** [microsoft/vscode-remote-release#10439] opened 2024-11-02 02:05 UTC
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It connects successfully

### ->

Let me preface this by saying everything is working fine, SSH connections are working fine, vscode SSH remote works fine after selecting the platform I'm connecting to "Linux" in this case.

The only problem is that annoyingly the platform prompt occurs every single time vscode connects to an SSH remote (reloads, open a new window etc.).
![Image](https://github.com/user-attachments/assets/baf89290-d29a-441a-955e-28ac1c66e8cc)

Importantly VSCode is correctly remembering the platform selected for a hostname but it is not referencing it upon next connection. This screenshot is taken from a different VSCode window after I've cleared the settings then freshly connected using a new window then checked the setting from a different window. Before I cleared this setting there was numerous other SSH hostnames I've connected to in the past.
![Image](https://github.com/user-attachments/assets/aba61e93-858a-44ab-bb30-23f59e82212d)

The devtools (Help>Toggle Developer Tools) do not show any errors or warnings that seem to relate to this functionality.

I am using existing SSH connections available in my SSH config file `C:\users\<username>\.ssh\config` using key based authentication.

### Expected Behavior

VSCode should lookup the existing **remote.SSH.remotePlatform** setting for the hostname being connected to and not prompt the user every single time it opens for a setting it already has stored.

### Steps To Reproduce

1. Connect to any SSH Remote in any way:
    - Such as clicking the remote connection icon in the bottom left of a VSCode window and connecting to any existing remote as available from the .ssh\config file.
    - Opening an existing workspace that has a connection to a remote.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[12:57:22.585] Log Level: 2
[12:57:22.602] SSH Resolver called for "ssh-remote+ga-nixutil-1", attempt 1
[12:57:22.602] "remote.SSH.useLocalServer": false
[12:57:22.602] "remote.SSH.useExecServer": true
[12:57:22.603] "remote.SSH.showLoginTerminal": false
[12:57:22.603] "remote.SSH.remotePlatform": {}
[12:57:22.603] "remote.SSH.path": undefined
[12:57:22.603] "remote.SSH.configFile": undefined
[12:57:22.603] "remote.SSH.useFlock": true
[12:57:22.603] "remote.SSH.lockfilesInTmp": false
[12:57:22.603] "remote.SSH.localServerDownload": auto
[12:57:22.603] "remote.SSH.remoteServerListenOnSocket": false
[12:57:22.603] "remote.SSH.showLoginTerminal": false
[12:57:22.603] "remote.SSH.defaultExtensions": []
[12:57:22.603] "remote.SSH.loglevel": 2
[12:57:22.604] "remote.SSH.enableDynamicForwarding": true
[12:57:22.604] "remote.SSH.enableRemoteCommand": false
[12:57:22.604] "remote.SSH.serverPickPortsFromRange": {}
[12:57:22.604] "remote.SSH.serverInstallPath": {}
[12:57:22.604] "remote.SSH.permitPtyAllocation": false
[12:57:22.604] "remote.SSH.preferredLocalPortRange: undefined
[12:57:22.604] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[12:57:22.608] VS Code version: 1.95.1
[12:57:22.608] Remote-SSH version: remote-ssh@0.115.0
[12:57:22.608] win32 x64
[12:57:22.611] SSH Resolver called for host: ga-nixutil-1
[12:57:22.611] Setting up SSH remote "ga-nixutil-1"
[12:57:22.617] Using commit id "65edc4939843c90c34d61f4ce11704f09d3e5cb6" and quality "stable" for server
[12:57:22.619] Script variables:
 {
  "InstallExitCode.24": "AlreadyInProgress",
  "InstallExitCode.25": "ServerDownloadFailed",
  "InstallExitCode.26": "NoDownloaderAvailable",
  "InstallExitCode.27": "UnsupportedArch",
  "InstallExitCode.28": "StatusCheckFailed",
  "InstallExitCode.29": "NeedInsidersArch",
  "InstallExitCode.30": "NoDownloaderAvailableForStatusCheck",
  "InstallExitCode.31": "ServerTransferFailed",
  "InstallExitCode.32": "ServerFailedToStart",
  "InstallExitCode.33": "NeedInsidersWindows",
  "InstallExitCode.34": "CreateInstallDirFailed",
  "InstallExitCode.35": "UnsupportedPlatform",
  "InstallExitCode.36": "ServerTerminatedCVE20201416",
  "InstallExitCode.37": "UnpackFailed",
  "InstallExitCode.38": "ChangeDirFailed",
  "InstallExitCode.AlreadyInProgress": "24",
  "InstallExitCode.ServerDownloadFailed": "25",
  "InstallExitCode.NoDownloaderAvailable": "26",
  "InstallExitCode.NoDownloaderAvailableForStatusCheck": "30",
  "InstallExitCode.UnsupportedArch": "27",
  "InstallExitCode.StatusCheckFailed": "28",
  "InstallExitCode.NeedInsidersArch": "29",
  "InstallExitCode.ServerTransferFailed": "31",
  "InstallExitCode.ServerFailedToStart": "32",
  "InstallExitCode.NeedInsidersWindows": "33",
  "InstallExitCode.CreateInstallDirFailed": "34",
  "InstallExitCode.UnsupportedPlatform": "35",
  "InstallExitCode.ServerTerminatedCVE20201416": "36",
  "InstallExitCode.UnpackFailed": "37",
  "InstallExitCode.ChangeDirFailed": "38",
  "InstallUnpackCode.Success": "success",
  "InstallUnpackCode.Error": "error",
  "InstallUnpackCode.MissingFiles": "missingFiles",
  "uuid": "89f2a05ad9ad",
  "startMarker": "89f2a05ad9ad: running",
  "commitId": "65edc4939843c90c34d61f4ce11704f09d3e5cb6",
  "quality": "stable",
  "token": "111aaaa1-a11a-11aa-111a-11a1a111a111",
  "vscodeAgentFolder": "$HOME/.vscode-server",
  "allowClientDownload": "1",
  "forceClientDownload": "0",
  "cliNameInArchive": "code",
  "ignoreWgetConfigFlag": " --no-config ",
  "ignoreCurlConfigFlag": " --disable ",
  "wgetTriesSegment": "--tries=1",
  "listenArgs": "--on-host=127.0.0.1 --on-port",
  "getDownloadServerStartTrigger": "89f2a05ad9ad:trigger_server_download",
  "getDownloadServerEndTrigger": "89f2a05ad9ad:trigger_server_download_end",
  "getProgressDownloading": "89f2a05ad9ad%%1%%",
  "getProgressInstalling": "89f2a05ad9ad%%2%%"
}
[12:57:22.621] Install and start server if needed
[12:57:23.370] Checking ssh with "c:\windows\system32\ssh.exe -V"
[12:57:23.372] Got error from ssh: spawn c:\windows\system32\ssh.exe ENOENT
[12:57:23.372] Checking ssh with "c:\windows\ssh.exe -V"
[12:57:23.373] Got error from ssh: spawn c:\windows\ssh.exe ENOENT
[12:57:23.373] Checking ssh with "c:\windows\system32\wbem\ssh.exe -V"
[12:57:23.374] Got error from ssh: spawn c:\windows\system32\wbem\ssh.exe ENOENT
[12:57:23.374] Checking ssh with "c:\windows\system32\windowspowershell\v1.0\ssh.exe -V"
[12:57:23.375] Got error from ssh: spawn c:\windows\system32\windowspowershell\v1.0\ssh.exe ENOENT
[12:57:23.375] Checking ssh with "c:\windows\system32\openssh\ssh.exe -V"
[12:57:23.391] > OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2

[12:57:23.394] Running script with connection command: "c:\windows\system32\openssh\ssh.exe" -T -D 61370 "ga-nixutil-1" sh
[12:57:23.394] Generated SSH command: 'type "C:\Users\adrian\AppData\Local\Temp\vscode-linux-multi-line-command-ga-nixutil-1-222269567.sh" | "c:\windows\system32\openssh\ssh.exe" -T -D 61370 "ga-nixutil-1" sh'
[12:57:23.395] Using connect timeout of 17 seconds
[12:57:23.396] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:57:23.830] > 89f2a05ad9ad: running
> Script executing under PID: 2161
> Found existing installation at /home/sysadmin/.vscode-server...
> Starting VS Code CLI...
> printenv:
> ]0;C:\WINDOWS\System32\cmd.exe    SHELL=/run/current-system/sw/bin/bash
>     __ETC_PROFILE_DONE=1
>     XDG_CONFIG_DIRS=/etc/xdg:/home/sysadmin/.nix-profile/etc/xdg:/nix/profile/etc/xdg:/home/sysadmin/.local/state/nix/profile/etc/xdg:/etc/profiles/per-user/sysadmin/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
>     LC_ADDRESS=en_AU.UTF-8
>     LC_NAME=en_AU.UTF-8
>     XCURSOR_PATH=/home/sysadmin/.icons:/home/sysadmin/.local/share/icons:/home/sysadmin/.nix-profile/share/icons:/home/sysadmin/.nix-profile/share/pixmaps:/nix/profile/share/icons:/nix/profile/share/pixmaps:/home/sysadmin/.local/state/nix/profile/share/icons:/home/sysadmin/.local/state/nix/profile/share/pixmaps:/etc/profiles/per-user/sysadmin/share/icons:/etc/profiles/per-user/sysadmin/share/pixmaps:/nix/var/nix/profiles/default/share/icons:/nix/var/nix/profiles/default/share/pixmaps:/run/current-system/sw/share/icons:/run/current-system/sw/share/pixmaps
>     LC_MONETARY=en_AU.UTF-8
>     NO_AT_BRIDGE=1
>     EDITOR=nano
>     PWD=/home/sysadmin
>     NIX_PROFILES=/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/sysadmin /home/sysadmin/.local/state/nix/profile /nix/profile /home/sysadmin/.nix-profile
>     LOGNAME=sysadmin
>     XDG_SESSION_TYPE=tty
>     NIX_PATH=/home/sysadmin/.nix-defexpr/channels:nixpkgs=/nix/var/nix/profiles/
> /per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/
> /nix/profiles/per-user/root/channels
>     NIXPKGS_CONFIG=/etc/nix/nixpkgs-config.nix
>     HOME=/home/sysadmin
>     SSH_ASKPASS=
>     LANG=en_AU.UTF-8
>     LC_PAPER=en_AU.UTF-8
>     SSH_CONNECTION=192.168.66.1 61372 192.168.67.7 22
>     GTK_A11Y=none
>     NIX_USER_PROFILE_DIR=/nix/var/nix/profiles/per-user/sysadmin
>     INFOPATH=/home/sysadmin/.nix-profile/info:/home/sysadmin/.nix-profile/share/
> /info:/nix/profile/info:/nix/profile/share/info:/home/sysadmin/.local/state/nix/p
> profile/info:/home/sysadmin/.local/state/nix/profile/share/info:/etc/profiles/per
> r-user/sysadmin/info:/etc/profiles/per-user/sysadmin/share/info:/nix/var/nix/prof
> files/default/info:/nix/var/nix/profiles/default/share/info:/run/current-system/s
> sw/info:/run/current-system/sw/share/info
>     XDG_SESSION_CLASS=user
>     LC_IDENTIFICATION=en_AU.UTF-8
>     TERM=dumb
>     GTK_PATH=/home/sysadmin/.nix-profile/lib/gtk-2.0:/home/sysadmin/.nix-profile
> e/lib/gtk-3.0:/home/sysadmin/.nix-profile/lib/gtk-4.0:/nix/profile/lib/gtk-2.0:/n
> nix/profile/lib/gtk-3.0:/nix/profile/lib/gtk-4.0:/home/sysadmin/.local/state/nix/
> /profile/lib/gtk-2.0:/home/sysadmin/.local/state/nix/profile/lib/gtk-3.0:/home/sy
> ysadmin/.local/state/nix/profile/lib/gtk-4.0:/etc/profiles/per-user/sysadmin/lib/
> /gtk-2.0:/etc/profiles/per-user/sysadmin/lib/gtk-3.0:/etc/profiles/per-user/sysad
> dmin/lib/gtk-4.0:/nix/var/nix/profiles/default/lib/gtk-2.0:/nix/var/nix/profiles/
> /default/lib/gtk-3.0:/nix/var/nix/profiles/default/lib/gtk-4.0:/run/current-syste
> em/sw/lib/gtk-2.0:/run/current-system/sw/lib/gtk-3.0:/run/current-system/sw/lib/g
> gtk-4.0
>     LESSOPEN=|/nix/store/l0p0s9l3glng4isqddm97kdw40slxv47-lesspipe-2.11/bin/less
> spipe.sh %s
>     USER=sysadmin
>     TZDIR=/etc/zoneinfo
>     SHLVL=1
>     PAGER=less
>     LC_TELEPHONE=en_AU.UTF-8
>     QTWEBKIT_PLUGIN_PATH=/home/sysadmin/.nix-profile/lib/mozilla/plugins/:/nix/p
> profile/lib/mozilla/plugins/:/home/sysadmin/.local/state/nix/profile/lib/mozilla/
> /plugins/:/etc/profiles/per-user/sysadmin/lib/mozilla/plugins/:/nix/var/nix/profi
> iles/default/lib/mozilla/plugins/:/run/current-system/sw/lib/mozilla/plugins/    
>     LC_MEASUREMENT=en_AU.UTF-8
>     __NIXOS_SET_ENVIRONMENT_DONE=1
>     XDG_SESSION_ID=12
>     LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive
>     LESSKEYIN_SYSTEM=/nix/store/sq0vq146mn2xw9qaqx1896r0icx1f3ia-lessconfig     
>     TERMINFO_DIRS=/home/sysadmin/.nix-profile/share/terminfo:/nix/profile/share/
> /terminfo:/home/sysadmin/.local/state/nix/profile/share/terminfo:/etc/profiles/pe
> er-user/sysadmin/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run
> n/current-system/sw/share/terminfo
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.66.1 61372 22
>     LC_TIME=en_AU.UTF-8
>     XDG_DATA_DIRS=/home/sysadmin/.nix-profile/share:/nix/profile/share:/home/sys
> sadmin/.local/state/nix/profile/share:/etc/profiles/per-user/sysadmin/share:/nix/
> /var/nix/profiles/default/share:/run/current-system/sw/share
>     LIBEXEC_PATH=/home/sysadmin/.nix-profile/libexec:/nix/profile/libexec:/home/
> /sysadmin/.local/state/nix/profile/libexec:/etc/profiles/per-user/sysadmin/libexe
> ec:/nix/var/nix/profiles/default/libexec:/run/current-system/sw/libexec
>     PATH=/run/wrappers/bin:/home/sysadmin/.nix-profile/bin:/nix/profile/bin:/hom
> me/sysadmin/.local/state/nix/profile/bin:/etc/profiles/per-user/sysadmin/bin:/nix
> x/var/nix/profiles/default/bin:/run/current-system/sw/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     LC_NUMERIC=en_AU.UTF-8
>     _=/run/current-system/sw/bin/printenv
> Removing old logfile at /home/sysadmin/.vscode-server/.cli.65edc4939843c90c34d61
> 1f4ce11704f09d3e5cb6.log
> Spawned remote CLI: 2179
> Waiting for server log...
[12:57:23.830] Got some output, clearing connection timeout
[12:57:23.845] > 
[12:57:23.874] > 89f2a05ad9ad: start
> listeningOn==127.0.0.1:36263==
> osReleaseId==nixos==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==48==
> execServerToken==111aaaa1-a11a-11aa-111a-11a1a111a111==
> platformDownloadPath==cli-alpine-x64==
> 89f2a05ad9ad: end
[12:57:23.874] Received install output: 
listeningOn==127.0.0.1:36263==
osReleaseId==nixos==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==48==
execServerToken==111aaaa1-a11a-11aa-111a-11a1a111a111==
platformDownloadPath==cli-alpine-x64==

[12:57:23.875] Remote server is listening on port 36263
[12:57:23.875] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":36263},"osReleaseId":"nixos","arch":"x86_64","tmpDir":"/run/user/1000","platform":"linux","execServerToken":"111aaaa1-a11a-11aa-111a-11a1a111a111"},"serverStartTime":48,"installUnpackCode":""}
[12:57:23.878] Starting forwarding server. local port 61373 -> socksPort 61370 -> remotePort 36263
[12:57:23.878] Forwarding server listening on port 61373
[12:57:23.878] Waiting for ssh tunnel to be ready
[12:57:23.879] [Forwarding server port 61373] Got connection 0
[12:57:23.880] Tunneled port 36263 to local port 61373
[12:57:23.880] Resolved "ssh-remote+ga-nixutil-1" to "port 61373"
[12:57:23.888] Initizing new exec server for ssh-remote+ga-nixutil-1
[12:57:23.888] Resolving exec server at port 61373
[12:57:23.889] [Forwarding server port 61373] Got connection 1
[12:57:23.893] > 
[12:57:23.963] Exec server for ssh-remote+ga-nixutil-1 created and cached
[12:57:23.968] ------




[12:57:23.975] [server] Checking /home/sysadmin/.vscode-server/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/log.txt and /home/sysadmin/.vscode-server/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/pid.txt for a running server...
[12:57:24.016] [server] Found running server (pid=818)
[12:57:25.632] Opening exec server for ssh-remote+ga-nixutil-1
[12:57:25.689] Verified and reusing cached exec server for ssh-remote+ga-nixutil-1
[12:57:25.693] Opening exec server for ssh-remote+ga-nixutil-1
[12:57:25.772] Verified and reusing cached exec server for ssh-remote+ga-nixutil-1

```

</p>
</details>

### Anything else?

We can see in the Remote-SSH output that it seems to not be picking up the **remote.SSH.remotePlatform** setting value that we can visually inspect IS populated in the vscode settings (see my screenshot):
`"remote.SSH.remotePlatform": {}`

This is the most similar closed github issue that had no relevant information, that I could determine, as to the cause or the fix. In their case it does mention that VSCode "won't save it" but I have proved in my case it is saving it.
> Even after I select the remote AWS Ubuntu instance as "Linux" it won't save it.  

https://github.com/microsoft/vscode-remote-release/issues/2934

**Comment by DarkAdaptedEye** [comment] 2024-11-04 22:50
Having this problem also, occurs with use of non-default profiles.

The setting including loading and saving on the settings screen will display the correct details as it also reading from the default profile. The connection will try to load from the current profile.

The 'quick' workaround:

Load a window with the default profile and get settings.json via `CTRL+P >settings.json` then select `Preferences: Open User Settings (JSON)`
Go to the window using the other profile and do the same thing.
Copy/Paste the block `"remote.SSH.remotePlatform": { ... }` to the non-default profile.

This might be a regression related to [#2934](https://github.com/microsoft/vscode-remote-release/issues/2934)

**Comment by nscavalier** [comment] 2024-11-05 02:15
I have the same problem

**Comment by joshspicer** [comment] 2024-11-05 18:14
@aglasson , are you also using a non-default VS Code profile?

**Comment by aglasson** [comment] 2024-11-05 23:01
Yep I sure am. Good fine @DarkAdaptedEye 
I'll try the suggested workaround in the short term.

**Comment by DevDorrejo** [comment] 2024-11-06 01:19
Same issue.

**Comment by chaoyi-studio** [comment] 2024-11-06 07:13
When I  using VSCode's UI settings. in user menu modify the `remote.SSH.remotePlatform` , and then re-use the remote connection, and the output result contains the `"remote. SSH.remotePlatform": {}`.
then I open the `applacition settings (json)`  and can find ` "remote.SSH.remotePlatform": {"EmbedDev": "linux"},`
 and `User Setting (json)` didn't find anything similar.
Then I tried adding  ` "remote.SSH.remotePlatform": {"EmbedDev": "linux"},` to `User Setting (json)` it workd!!

Could it be that the save stage is saved to the app settings, but the load stage reads the user settings?

**Comment by joshspicer** [comment] 2024-11-06 16:38
/duplicate https://github.com/microsoft/vscode-remote-release/issues/10376

Looks like a dupe of https://github.com/microsoft/vscode-remote-release/issues/10376, so i'll close this one as a duplicate to keep the conversation centralized - thank you for reporting

**Closed by joshspicer** 2024-11-06 16:38 UTC
Labels: ssh
