### ISSUE TITLE
Integrated terminal is blank and does not work

### ISSUE THREAD

**Issue by anoriqq** [microsoft/vscode-remote-release#4475] opened 2021-02-16 02:36 UTC
Issue Type: <b>Bug</b>

1. Connect to macOS from Windows with only Remote-SSH extension installed
2. When I open integrated terminal, nothing is displayed and nothing can be operated
![image](https://user-images.githubusercontent.com/33250012/108012154-047c1c00-704c-11eb-8ffd-5d32dd65c638.png)

<details>
<summary>settings.json</summary>

```json:settings.json
{
    "remote.SSH.remotePlatform": {
        "192.168.0.7": "macOS"
    }
}
```

</details>

<details>
<summary>Remote - SSH output</summary>

```
[11:07:10.855] Log Level: 2
[11:07:10.858] remote-ssh@0.64.0
[11:07:10.858] win32 x64
[11:07:10.859] SSH Resolver called for "ssh-remote+192.168.0.7", attempt 1
[11:07:10.860] "remote.SSH.useLocalServer": false
[11:07:10.860] "remote.SSH.showLoginTerminal": false
[11:07:10.860] "remote.SSH.remotePlatform": {}
[11:07:10.860] "remote.SSH.sshPath": undefined
[11:07:10.860] "remote.SSH.sshConfigurationFile": undefined
[11:07:10.860] "remote.SSH.useFlock": true
[11:07:10.861] "remote.SSH.lockfilesInTmp": false
[11:07:10.861] "remote.SSH.localServerDownload": auto
[11:07:10.861] "remote.SSH.remoteServerListenOnSocket": false
[11:07:10.861] "remote.SSH.showLoginTerminal": false
[11:07:10.861] "remote.SSH.defaultExtensions": []
[11:07:10.861] SSH Resolver called for host: 192.168.0.7
[11:07:10.861] Setting up SSH remote "192.168.0.7"
[11:07:10.872] Using commit id "622cb03f7e070a9670c94bae1a45d78d7181fbd4" and quality "stable" for server
[11:07:10.875] Install and start server if needed
[11:07:12.963] Checking ssh with "ssh -V"
[11:07:12.990] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[11:07:12.994] Running script with connection command: ssh -T -D 58638 "192.168.0.7" bash
[11:07:12.997] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:07:13.204] > Password:]0;C:\WINDOWS\System32\cmd.exe
[11:07:13.204] Got some output, clearing connection timeout
[11:07:13.205] Showing password prompt
[11:07:18.347] Got password response
[11:07:18.348] "install" wrote data to terminal: "************"
[11:07:18.359] > 
[11:07:18.737] > d07d2d0ca9e0: running
[11:07:18.773] > Acquiring lock on /Users/anoriqq/.vscode-server/bin/622cb03f7e070a9670c94bae1a45
> d78d7181fbd4/vscode-remote-lock.anoriqq.622cb03f7e070a9670c94bae1a45d78d7181fbd4
[11:07:18.789] > \ln /Users/anoriqq/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/v
> scode-remote-lock.anoriqq.622cb03f7e070a9670c94bae1a45d78d7181fbd4.target /Users
> /anoriqq/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/vscode-remo
> te-lock.anoriqq.622cb03f7e070a9670c94bae1a45d78d7181fbd4
> Installing to /Users/anoriqq/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d
> 7181fbd4...
> d07d2d0ca9e0%%1%%
[11:07:18.804] > Downloading with curl
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed  
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 
[11:07:18.931] >   0     0    0     0    0     0      0    
[11:07:18.944] >   0 --:--:-- --:--:-- --:--:--     0
[11:07:19.293] > 100   125  100   125    0     0    253 
[11:07:19.302] >      0 --:--:-- --:--:-- --:--:--   252
[11:07:19.920] >  28 27.7M   28 8080k    0     0
[11:07:19.933] >   7227k      0  0:00:03  0:00:01  0:00:02 7227k
[11:07:20.919] >  73 27.7M   73 20.3M    0     0  9838k      
[11:07:20.931] > 0  0:00:02  0:00:02 --:--:-- 12.4M
[11:07:21.519] > 100 27.7M  100 27.7M    0     0  10.2M      0 
[11:07:21.529] > 100 27.7M  100 27.7M    0     0  10.2M      0  0:00:02  0:00:02 --:--:-- 12.4M
> Download complete
[11:07:21.546] > d07d2d0ca9e0%%2%%
> tar --version:   
[11:07:21.560] > bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
[11:07:22.136] > Checking /Users/anoriqq/.vscode-server/.622cb03f7e070a9670c94bae1a45d78d7181fbd4
> .log and /Users/anoriqq/.vscode-server/.622cb03f7e070a9670c94bae1a45d78d7181fbd4
> .pid for a running server
[11:07:22.199] > WARNING: VS Code Server is running but its logfile is missing. Don't delete the 
> VS Code Server manually, run the command 'Uninstall VS Code Server'.
> Starting server with command... /Users/anoriqq/.vscode-server/bin/622cb03f7e070a
> 9670c94bae1a45d78d7181fbd4/server.sh --start-server --host=127.0.0.1 --enable-re
> mote-auto-shutdown  --port=0  &> "/Users/anoriqq/.vscode-server/.622cb03f7e070a9
> 670c94bae1a45d78d7181fbd4.log" < /dev/null
> printenv:
>     SHELL=/bin/zsh
>     TMPDIR=/var/folders/jg/1pghp51x0rv_d1wf_pg6r14m0000gn/T/
>     SSH_CLIENT=192.168.0.12 58640 22
>     USER=anoriqq
>     VSCODE_AGENT_FOLDER=/Users/anoriqq/.vscode-server
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin
>     PWD=/Users/anoriqq
>     SHLVL=1
>     HOME=/Users/anoriqq
>     LOGNAME=anoriqq
>     SSH_CONNECTION=192.168.0.12 58640 192.168.0.7 22
[11:07:22.206] > 
>     _=/usr/bin/printenv
>     OLDPWD=/Users/anoriqq/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d718
> 1fbd4
> rm: /Users/anoriqq/.vscode-server/.622cb03f7e070a9670c94bae1a45d78d7181fbd4.toke
> n: No such file or directory
[11:07:22.216] > 
> Spawned remote server: 7093
> Waiting for server log...
[11:07:22.256] > Waiting for server log...
[11:07:22.299] > Waiting for server log...
[11:07:22.346] > Waiting for server log...
[11:07:22.388] > Waiting for server log...
[11:07:22.430] > Waiting for server log...
[11:07:22.473] > Waiting for server log...
[11:07:22.508] > Waiting for server log...
[11:07:22.547] > Waiting for server log...
[11:07:22.586] > Waiting for server log...
[11:07:22.627] > Waiting for server log...
[11:07:22.663] > Waiting for server log...
[11:07:22.705] > Waiting for server log...
[11:07:22.753] > Waiting for server log...
[11:07:22.779] > Waiting for server log...
[11:07:22.817] > Waiting for server log...
[11:07:22.856] > Waiting for server log...
[11:07:22.896] > Waiting for server log...
[11:07:22.933] > Waiting for server log...
[11:07:22.971] > Waiting for server log...
[11:07:23.014] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[11:07:23.026] > 
> Checking server status on port 56178 with curl
[11:07:23.043] > 
[11:07:23.323] > d07d2d0ca9e0: start
> sshAuthSock====
> webUiAccessToken====
> listeningOn==56178==
> osReleaseId==Darwin==
> arch==x86_64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult==success==
> didLocalDownload==0==
> downloadTime==3000==
> installTime==1000==
> extInstallTime====
> serverStartTime==0==
> connectionToken==a1aa11a1-aaaa-1111-111a-11aa111111a1==
> d07d2d0ca9e0: end
[11:07:23.323] Received install output: 
sshAuthSock====
webUiAccessToken====
listeningOn==56178==
osReleaseId==Darwin==
arch==x86_64==
tmpDir==/tmp==
platform==macOS==
unpackResult==success==
didLocalDownload==0==
downloadTime==3000==
installTime==1000==
extInstallTime====
serverStartTime==0==
connectionToken==a1aa11a1-aaaa-1111-111a-11aa111111a1==

[11:07:23.324] Remote server is listening on 56178
[11:07:23.324] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":56178},"osReleaseId":"Darwin","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/tmp","platform":"macOS","connectionToken":"a1aa11a1-aaaa-1111-111a-11aa111111a1"},"downloadTime":3000,"installTime":1000,"serverStartTime":0,"installUnpackCode":"success"}
[11:07:23.325] Starting forwarding server. localPort 58642 -> socksPort 58638 -> remotePort 56178
[11:07:23.326] Forwarding server listening on 58642
[11:07:23.326] Waiting for ssh tunnel to be ready
[11:07:23.327] [Forwarding server 58642] Got connection 0
[11:07:23.328] Tunneled 56178 to local port 58642
[11:07:23.328] Resolved "ssh-remote+192.168.0.7" to "127.0.0.1:58642"
[11:07:23.335] ------




[11:07:23.340] [Forwarding server 58642] Got connection 1
[11:07:23.348] > 
[11:07:23.391] [Forwarding server 58642] Got connection 2
[11:07:43.653] [Forwarding server 58642] Got connection 3
[11:08:03.685] [Forwarding server 58642] Got connection 4
[11:08:23.720] [Forwarding server 58642] Got connection 5
[11:08:43.755] [Forwarding server 58642] Got connection 6
[11:09:03.794] [Forwarding server 58642] Got connection 7
[11:09:23.848] [Forwarding server 58642] Got connection 8
[11:09:43.887] [Forwarding server 58642] Got connection 9
```

</details>

I expect it to run on a remote host when I open a terminal as described  [here](https://code.visualstudio.com/docs/remote/ssh#_opening-a-terminal-on-a-remote-host)

Extension version: 0.64.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (37.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.0.7|
|OS|Darwin x64 20.2.0|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|Memory (System)|32.00GB (2.89GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by bamurtaugh** [comment] 2021-02-25 06:55
I wonder if there's any linked root cause to https://github.com/microsoft/vscode-remote-release/issues/4439 since the integrated terminal is also non-functional there.

**Comment by roblourens** [comment] 2021-03-04 18:52
Does everything else work normally (editing files and saving and so on)? Can you check the `Log (Window)` output channel for errors?

**Comment by anoriqq** [comment] 2021-03-08 09:04
> Does everything else work normally (editing files and saving and so on)?

Editing and saving files works.
In addition, extensions that install locally (Windows) also seem to work. (vim etc.)
But the extension I install on the host (macOS) doesn't seem to work. (Docker etc.)

> Can you check the Log (Window) output channel for errors?

Below is the log output.
The first permission error disappeared by running VS Code as an administrator.

<details>
<summary>Log (Window)</summary>

```log
[2021-03-08 17:43:24.444] [renderer1] [error] Failed opening file c:\Users\shota\AppData\Roaming\Code\logs\20210308T174236\exthost1\exthost.log for writing: Permission denied: Error: Failed opening file c:\Users\shota\AppData\Roaming\Code\logs\20210308T174236\exthost1\exthost.log for writing: Permission denied
	at createRotatingLogger (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:34:9)
	at c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:27:7
	at c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\node_modules\mkdirp\index.js:49:26
	at FSReqCallback.oncomplete (fs.js:173:5)
[2021-03-08 17:43:55.542] [renderer1] [info] [remote-connection][ExtensionHost][ecfcc…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-03-08 17:43:55.542] [renderer1] [info] [remote-connection][ExtensionHost][ecfcc…][reconnect] resolving connection...
[2021-03-08 17:43:55.542] [renderer1] [info] [remote-connection][ExtensionHost][ecfcc…][reconnect] connecting to 127.0.0.1:58649...
[2021-03-08 17:43:55.566] [renderer1] [info] [remote-connection][ExtensionHost][ecfcc…][reconnect] reconnected!
[2021-03-08 17:44:31.525] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-03-08 17:44:31.526] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] resolving connection...
[2021-03-08 17:44:31.527] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] connecting to 127.0.0.1:58683...
[2021-03-08 17:44:31.592] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] reconnected!
[2021-03-08 17:44:51.607] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-03-08 17:44:51.607] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] resolving connection...
[2021-03-08 17:44:51.607] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] connecting to 127.0.0.1:58683...
[2021-03-08 17:44:51.663] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] reconnected!
[2021-03-08 17:45:11.677] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-03-08 17:45:11.678] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] resolving connection...
[2021-03-08 17:45:11.678] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] connecting to 127.0.0.1:58683...
[2021-03-08 17:45:11.702] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] reconnected!
[2021-03-08 17:45:31.723] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-03-08 17:45:31.724] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] resolving connection...
[2021-03-08 17:45:31.724] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] connecting to 127.0.0.1:58683...
[2021-03-08 17:45:31.750] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] reconnected!
[2021-03-08 17:45:51.761] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-03-08 17:45:51.761] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] resolving connection...
[2021-03-08 17:45:51.761] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] connecting to 127.0.0.1:58683...
[2021-03-08 17:45:51.795] [renderer1] [info] [remote-connection][ExtensionHost][cfbf8…][reconnect] reconnected!

```

</details>

Please let me know if you have any information needed for the survey! Thanks.

**Comment by roblourens** [comment] 2021-03-09 00:21
Thanks. I suspect this is the same as https://github.com/microsoft/vscode-remote-release/issues/4439. Can you check whether the "Remote Extension Host" entry is missing from the output channel too?

**Comment by anoriqq** [comment] 2021-03-09 01:51
"Remote Extension Host" was not on the output channel

![image](https://user-images.githubusercontent.com/33250012/110405286-afb84800-80c3-11eb-9fa4-0eff0fef6ba1.png)!

**Comment by roblourens** [comment] 2021-03-09 18:10
Ok will close as a dupe of that issue.

**Closed by roblourens** 2021-03-09 18:10 UTC
Labels: needs-more-info, ssh
