### ISSUE TITLE
Terminal does not recognise Remote-Container

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode-remote-release#5078] opened 2021-05-20 06:26 UTC
Issue Type: <b>Bug</b>

When I open a terminal inside a `Remote Container` attached VS Code Window, I see the following message:

```Warning: This shell is running on your local machine```

This message is very misleading, because the shell should say that its inside the container named `abc-123` instead.

Extension version: 0.177.2
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0
Remote OS version: Linux x64 4.14.231-173.361.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (2.63GB free)|
|Process Argv|--crash-reporter-id 264c6684-aed1-41ee-b66d-1798647db0f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sha256:50d0ed8536051f0eaa14651b684d2a18bd49d1bab73eead2d11be57addf850c1 (/nk-dev-conn_pm2_1) @ aws-docker|
|OS|Linux x64 4.14.231-173.361.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.53GB (11.29GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment] 2021-05-20 06:42
Duplicate of #5055

**Closed by chrmarti** 2021-05-20 06:42 UTC
