### ISSUE TITLE
SSH include directive not supported

### ISSUE THREAD

**Issue by konradmalik** [microsoft/vscode-remote-release#5597] opened 2021-09-16 08:44 UTC
- VSCode Version: 1.60
- Local OS Version: MacOS Big Sur 11.6 and Arch Linux 
- Remote OS Version: -
- Remote Extension/Connection Type: SSH
- Logs: -

Steps to Reproduce:

Contents of my ssh config:
```
Include config.d/*

AddKeysToAgent yes
TCPKeepAlive yes
ServerAliveInterval 15
ServerAliveCountMax 6
Compression yes
ControlMaster auto
ControlPath /tmp/%r@%h:%p
ControlPersist 300

# #########
# Generic
# #########
Host *
  PubkeyAuthentication no
  IdentitiesOnly yes
```

All of my machine-related stuff is defined in separate files in `config.d`.

The SSH extension cannot see any machines I defined there:
![image](https://user-images.githubusercontent.com/13033392/133580467-fc1244e4-3c49-4646-ae2c-89409aa0abed.png)

When I specify a concrete ssh config (which is included in the main config), the extension then correctly recognizes the machines:
![image](https://user-images.githubusercontent.com/13033392/133580589-d1425574-dc57-4e89-b8ae-d4271bc79f1a.png)

**Comment by bamurtaugh** [comment] 2021-09-28 23:09
Thanks for filing! Closing a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4339 - if there's another issue here, please just let me know.

**Closed by bamurtaugh** 2021-09-28 23:09 UTC
Labels: ssh
