### ISSUE TITLE
When inside WSL, outside file changes don't automatically show up

### ISSUE THREAD

**Issue by Supermath101** [microsoft/vscode-remote-release#6985] opened 2022-07-23 21:38 UTC
# Problem Summary
This happens when in WSL on the Windows filesystem. I know, that isn't recommended for performance reasons. However, [the online resource](https://docs.microsoft.com/en-us/windows/wsl/filesystems#file-storage-and-performance-across-file-systems) says nothing about bugginess. The problem is that whenever I run a program to update file(s) outside of VS Code, normally when directly on Windows, it automatically updates with the files' new contents. However, in this setup, I have to manually close and reopen the file for it to update. See "steps to reproduce" for my use-case for this being fixed.

# Version Information
- VSCode Version:
```
Version: 1.69.1 (system setup)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:24.514Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
```
- Remote OS Version (`cat /proc/version`):
`Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022`
- Remote Extension/Connection Type: WSL

# Logs
## WSL:
```
[2022-07-23 20:54:00.892] Resolving wsl+ubuntu, resolveAttempt: 1
[2022-07-23 20:54:01.556] Starting VS Code Server inside WSL (wsl2)
[2022-07-23 20:54:01.556] Extension version: 0.66.3
[2022-07-23 20:54:01.556] Windows build: 22000. Multi distro support: available. WSL path support: enabled
[2022-07-23 20:54:01.556] No shell environment set or found for current distro.
[2022-07-23 20:54:01.691] WSL daemon log file: 
[2022-07-23 20:54:01.692] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2022-07-23 20:54:01.827] Probing result: found
[2022-07-23 20:54:01.827] Server install found in WSL
[2022-07-23 20:54:01.828] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=2313949793-3900029317-1229722776-3194783157 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
[2022-07-23 20:54:02.005] Setting up server environment: Looking for /home/supermath101/.vscode-server/server-env-setup. Not found.
[2022-07-23 20:54:02.005] WSL version: 5.10.102.1-microsoft-standard-WSL2 Ubuntu
[2022-07-23 20:54:02.005] WSL-shell-PID: 7290
[2022-07-23 20:54:02.005] Node executable: /home/supermath101/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/node
[2022-07-23 20:54:02.005] Starting server: /home/supermath101/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/bin/code-server --host=127.0.0.1 --port=0 --connection-token=2313949793-3900029317-1229722776-3194783157 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all
[2022-07-23 20:54:02.005] *
[2022-07-23 20:54:02.005] * Visual Studio Code Server
[2022-07-23 20:54:02.005] *
[2022-07-23 20:54:02.005] * By using the software, you agree to
[2022-07-23 20:54:02.005] * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
[2022-07-23 20:54:02.005] * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
[2022-07-23 20:54:02.005] *
[2022-07-23 20:54:02.005] Server bound to 127.0.0.1:37861 (IPv4)
[2022-07-23 20:54:02.005] Extension host agent listening on 37861
[2022-07-23 20:54:02.005] 
[2022-07-23 20:54:02.016] Started local proxy server on 54496.
[2022-07-23 20:54:02.016] WSL resolver response: 127.0.0.1:54496
[2022-07-23 20:54:02.016] To debug connection issues, open a local browser on http://127.0.0.1:54496/version
[2022-07-23 20:54:02.016] Using 'wslExeProxy' to connect to the VS Code server as configured by setting 'remote.WSL2.connectionMethod'
[2022-07-23 20:54:02.016] 'wslExeProxy' should fix reconnection issues after sleep and network adapter changes.
[2022-07-23 20:54:02.016] Please report issues related with the new setting to https://github.com/microsoft/vscode-remote-release/issues/5894
[2022-07-23 20:54:02.016] To revert back to the old way of connecting, change setting 'remote.WSL2.connectionMethod' to 'wsl2VMAddress'.
```

# Steps to Reproduce:

1. Open any Rust project inside WSL that's located on a Windows filesystem (e.g. `/mnt/c/...`).
2. Edit any Rust source file to make it functionally identical, but improperly formatted.
3. In an integrated terminal, run `cargo fmt`.
4. See if the file's displayed contents change at all, they didn't when I tried.
5. Close out the file that you've changed.
6. Reopen it.
7. Now see if the file changed, it finally does when I tried.

# Other Environments?
- **Does this issue occur when you try this locally?**: No!
- **Does this issue occur when you try this locally and all extensions are disabled?**: Didn't test.

**Comment by aeschli** [comment] 2023-11-22 08:13
duplicate of https://github.com/microsoft/vscode-remote-release/issues/5000

**Closed by aeschli** 2023-11-22 08:13 UTC
Labels: wsl
