### ISSUE TITLE
Support devcontainer.json option 'buildArgs'

### ISSUE THREAD

**Issue by jeffreyjam** [microsoft/vscode-remote-release#4352] opened 2021-01-25 07:21 UTC
Currently in devcontainer.json it's possible to pass a list of arguments to `docker run` with the `runArgs` option, but there's no corresponding `buildArgs` option to pass a list of arguments to `docker build`.

For my particular case I'm looking to pass the `--pull` argument to `docker build` so I can keep my devcontainers up to date by rebuilding them and don't have to bump versions by hand.

It looks like some people over in [#2200](https://github.com/microsoft/vscode-remote-release/issues/2200) are looking for the ability to pass the `--no-cache` option, and I bet there are other options people would like to pass too.

The `docker build` options `--target` and `--build-arg` were added as a part of [#46](https://github.com/microsoft/vscode-remote-release/issues/46) last year but it stopped short of adding the ability to pass arbitrary options, which would be really convenient.

There exists the similar-sounding `build.args` option in devcontainer.json right now, so it might be better to use a different name than `buildArgs`, for example `build.options` or `build.cliArgs`.

**Comment by felipecrs** [comment] 2021-01-26 15:53
`buildArgs` would be very helpful, despite I think `--pull` should be along with the default `docker build` command for the devcontainer.

**Comment by eitsupi** [comment] 2021-03-27 07:00
+1

If we want to use `--add-host` in a container, we can write it in `runArgs`, but if we want to use it during build, there is no way to set it.

```json
"runArgs": ["--add-host=host.docker.internal:host-gateway"]
```

**Comment by felipecrs** [comment] 2021-04-30 21:56
This seems to be a duplicate of https://github.com/microsoft/vscode-remote-release/issues/3545.

**Comment by pgs31** [comment] 2021-06-17 13:08
+1 I'd love to be able to use this so I can use `docker build --ssh`. I haven't been able to find a good way to get my private key into the docker build stage other than pasting it into devcontainer.json as a docker build arg.

**Comment by Chuxel** [comment] 2021-11-10 18:18
Doing some dupe cleanup. Closing as dupe of #3545

**Closed by Chuxel** 2021-11-10 18:18 UTC
Labels: containers, feature-request
