### ISSUE TITLE
Error when trying to clone a repository in container volume

### ISSUE THREAD

**Issue by chris-ch** [microsoft/vscode-remote-release#9346] opened 2023-12-26 09:35 UTC
I am opening a report identical to one that had been closed previously for lack of more information: #8869 

Open question from @chrmarti was:

> The boostrap container mounts the /var/run/docker.sock. Could you check the permissions on that locally and inside the boostrap container?

Here is how the file looks like from the container:

```
root ➜ / $ ls -la /var/run/
ls: cannot access '/var/run/docker.sock': Permission denied
total 0
drwxr-xr-x 1 root root 61 Dec 26 09:31 .
dr-xr-xr-x 1 root root 35 Dec 26 09:31 ..
-rw-r--r-- 1 root root  0 Dec 26 09:31 .containerenv
-????????? ? ?    ?     ?            ? docker.sock
drwxr-xr-x 2 root root 40 Dec 26 09:31 secrets
drwx--x--x 2 root root  6 Dec  8 04:36 sudo
```
I launched the container using the same command as in the log below:
`docker run -d --mount type=volume,src=llama2-haskell-inference-0ffc17204f972fe01ea4c52a438f6a09c5d760d585202e26946d821a0919a4ee,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity`

Additional information: using podman 4.8.0

- VSCode Version: 1.86.0-insider (Universal)
- Local OS Version: MacOS Sonoma 14.2.1
- Remote OS Version: Debian
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:

```
[43 ms] Dev Containers 0.329.0 in VS Code 1.86.0-insider (9621add46007f7a1ab37d1fce9bcdcecca62aeb0).
[43 ms] Start: Resolving Remote
[53 ms] Start: Check Docker is running
[53 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[284 ms] Server API version: 4.7.2
[285 ms] Start: Run: docker volume ls -q
[441 ms] Start: Run: docker build -f /var/folders/7j/nsbnmhv56zvcw9v31jqdjw240000gn/T/vsch/bootstrap-image/0.329.0/bootstrap.Dockerfile -t vsc-volume-bootstrap /var/folders/7j/nsbnmhv56zvcw9v31jqdjw240000gn/T/vsch/bootstrap-image/0.329.0
STEP 1/5: FROM mcr.microsoft.com/devcontainers/base:0-alpine-3.16
STEP 2/5: RUN echo "@old https://dl-cdn.alpinelinux.org/alpine/v3.15/main" >> /etc/apk/repositories
--> Using cache 69b31a50115a3874aaab41914e9b8a3d325dd4f0be9bded772271a39687d70ec
--> 69b31a50115a
STEP 3/5: RUN apk add --no-cache        git-lfs         nodejs  python3         npm     make    g++     docker-cli      docker-cli-buildx       docker-cli-compose      openssh-client-default@old     ;
--> Using cache 58ea6f80a642600a49ed549a9b249c2d6f82a77acaeec4eec380fc4d02d32289
--> 58ea6f80a642
STEP 4/5: RUN cd && npm i node-pty
--> Using cache 7c490c6cc20ee3bf871952b70a14a97b3ed3a518121c4f83b85937a949c73f1d
--> 7c490c6cc20e
STEP 5/5: COPY .vscode-remote-containers /root/.vscode-remote-containers
COMMIT vsc-volume-bootstrap
--> 2ad422140502
Successfully tagged localhost/vsc-volume-bootstrap:latest
2ad422140502e3a4a0c6eb91fea70ffddb948a1e2ecada0073c98dad6c1921a1
[9082 ms] Cloning Github repository: chris-ch/llama2-haskell-inference into /workspaces/llama2-haskell-inference

[9082 ms] Start: Run: docker run -d --mount type=volume,src=llama2-haskell-inference-0ffc17204f972fe01ea4c52a438f6a09c5d760d585202e26946d821a0919a4ee,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[16382 ms] Start: Run in container: /bin/sh
[16385 ms] Start: Launching Dev Containers helper.
[16385 ms] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-9bf7043d-9042-43c4-ba28-69f932d915b2.sock) forwarded to local host (/private/tmp/com.apple.launchd.sw0nczP5fS/Listeners).
[16385 ms] X11 forwarding: DISPLAY not set on local host.
[16386 ms] Start: Run in container: gpgconf --list-dir agent-socket
[16603 ms] /root/.gnupg/S.gpg-agent
[16603 ms] 
[16603 ms] Start: Run in container: gpgconf --list-dir homedir
[16606 ms] /root/.gnupg
[16606 ms] 
[16606 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[16610 ms] 
[16610 ms] 
[16610 ms] Exit code 2
[16611 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[16629 ms] /Users/christophe/.gnupg/S.gpg-agent.extra
[16630 ms] 
[16630 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[16630 ms] gpg-agent: Socket in container (/root/.gnupg/S.gpg-agent) forwarded to local host (/Users/christophe/.gnupg/S.gpg-agent.extra).
[16650 ms] 
[16650 ms] 
[16651 ms] Start: Run in container: command -v docker >/dev/null 2>&1
[16651 ms] Start: Run: gpgconf --list-dir homedir
[16660 ms] 
[16660 ms] 
[16661 ms] Start: Run in container: /bin/sh
[16666 ms] Start: Run in container: echo ~
[16676 ms] /Users/christophe/.gnupg
[16676 ms] 
[16677 ms] Start: Run in container: gpgconf --list-dir homedir
[16682 ms] /root/.gnupg
[16682 ms] 
[16685 ms] Start: Run in container: # Test for /root/.gnupg/pubring.kbx and gpg
[16691 ms] 
[16691 ms] 
[16691 ms] Start: Run in container: # Copy /Users/christophe/.gnupg/pubring.kbx to /root/.gnupg/pubring.kbx
[16706 ms] 
[16706 ms] 
[16707 ms] Start: Run in container: # Test for /root/.gnupg/trustdb.gpg and gpg
[16712 ms] 
[16712 ms] 
[16713 ms] Start: Run in container: # Copy /Users/christophe/.gnupg/trustdb.gpg to /root/.gnupg/trustdb.gpg
[16723 ms] 
[16723 ms] 
[16723 ms] Start: Run: gpg-connect-agent updatestartuptty /bye
[16909 ms] /root
[16910 ms] 
[16910 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-9bf7043d-9042-43c4-ba28-69f932d915b2.js' >/tmp/vscode-remote-containers-9bf7043d-9042-43c4-ba28-69f932d915b2.js
[16913 ms] 
[16914 ms] 
[16915 ms] Start: Run in container: cat ~/.docker/config.json || echo "{
[16919 ms] {
}
[16919 ms] cat: /root/.docker/config.json: No such file or directory
[16920 ms] Start: Run in container: mkdir -p /usr/local/bin && cat <<'EOF-/usr/local/bin/docker-credential-dev-containers-9bf7043d-9042-43c4-ba28-69f932d915b2' >/usr/local/bin/docker-credential-dev-containers-9bf7043d-9042-43c4-ba28-69f932d915b2
[16924 ms] 
[16924 ms] 
[16924 ms] Start: Run in container: chmod +x /usr/local/bin/docker-credential-dev-containers-9bf7043d-9042-43c4-ba28-69f932d915b2
[16928 ms] 
[16928 ms] 
[16929 ms] Start: Run in container: mkdir -p ~/.docker && cat <<'EOF-/usr/local/bin/docker-credential-dev-containers-9bf7043d-9042-43c4-ba28-69f932d915b2' >~/.docker/config.json
[16934 ms] 
[16935 ms] 
[16935 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-9bf7043d-9042-43c4-ba28-69f932d915b2.js' >/tmp/vscode-remote-containers-server-9bf7043d-9042-43c4-ba28-69f932d915b2.js_1703582548307
[16942 ms] 
[16942 ms] 
[16946 ms] Start: Run in container: # Test for /root/.gitconfig and git
[16950 ms] 
[16950 ms] 
[16950 ms] Start: Run in container: # Copy /Users/christophe/.gitconfig to /root/.gitconfig
[16955 ms] 
[16955 ms] 
[16956 ms] Start: Run in container: # Cleaning up git config
[16965 ms] 
[16965 ms] 
[16965 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global --replace-all credential.helper '!f() { node /tmp/vscode-remote-containers-9bf7043d-9042-43c4-ba28-69f932d915b2.js git-credential-helper $*; }; f' || true
[16969 ms] 
[16969 ms] 
[16970 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[16974 ms] 
[16974 ms] 
[16974 ms] Start: Run in container: # Copy /Users/christophe/.ssh/known_hosts to /root/.ssh/known_hosts
[16980 ms] 
[16981 ms] 
[17059 ms] Start: Run in container: cat /workspaces/llama2-haskell-inference/.devcontainer/devcontainer.json 2>/dev/null
[17063 ms] Start: Run in container: cat /workspaces/llama2-haskell-inference/.devcontainer/devcontainer.json 2>/dev/null
[17068 ms] Start: Run in container: test -e "/Users/christophe" || (mkdir -p "$(dirname "/Users/christophe")" && ln -s ~ "/Users/christophe")
[17074 ms] 
[17074 ms] 
[17074 ms] Start: Run in container: cat <<'EOF-/tmp/devcontainer-65fa32cd-39f3-4a28-bf68-9e25806db28c.json' >/tmp/devcontainer-65fa32cd-39f3-4a28-bf68-9e25806db28c.json_1703582548446
[17079 ms] 
[17079 ms] 
[17079 ms] Start: Run in container: docker volume ls -q
[17356 ms] Start: Run: docker rm -f 693713240d1a1824e3132fad576fd563c2c201f85e6226fe0ebaa009e0d612a8
[17362 ms] Command failed: docker volume ls -q
[17362 ms] Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/volumes": dial unix /var/run/docker.sock: connect: permission denied
[17362 ms] Exit code 1
[27867 ms] Container server: Error: no exec session with ID 3beda06ed13dfc9a679c98ab1aca058201c72145e19ffb9ef39a733c86c91348 found: no such exec session
[27870 ms] Container server terminated (code: 125, signal: null).

```

Steps to Reproduce:

1. Dev Containers: Clone repository in container volume..
2. choose a repo to clone

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tnk4on** [comment] 2024-01-05 19:48
The cause is that the run option of the Bootstrap container needs to be `--privileged`.
Make the `docker` command a wrapper for the `podman` command as follows.

```bash
% cat /usr/local/bin/docker
#!/bin/bash

# The actual command is /usr/local/bin/podman
CMD="/usr/local/bin/podman"

# Check if the first argument is "run"
if [ "$1" = "run" ]; then
    shift  # Remove the first argument
    exec $CMD run --privileged "$@"
else
    exec $CMD "$@"
fi
```
I am not sure how Docker properly mounts docker.sock when DinD is running.
This will resolve your error.

Next, you will probably get another error.
Create `devcontainer.json` as follows and save it in the clone source repository.

```json
{
	"name": "Alpine",
	"image": "mcr.microsoft.com/devcontainers/base:alpine-3.18",
	"containerEnv": {
		"HOME": "/home/vscode"
	},
	"containerUser": "vscode"
}
```

In other words, if you are not the owner of the repository, you must always fork first to create devcontainer.json.
There has been no progress at all in the last few years in improving the bugs when using Dev Container and Podman.

**Comment by Malix-Labs** [comment] 2024-10-25 18:29
Hey, are you sure it's not a duplicate of #9163 ?

**Comment by bamurtaugh** [comment] 2024-12-13 00:11
Thanks all for filing and sharing feedback, we really appreciate it.

Sounds like this can be closed as a duplicate, but please lmk if it's separate, and we'd be happy to reopen. Thank you!

**Closed by bamurtaugh** 2024-12-13 00:11 UTC
Labels: containers
