### ISSUE TITLE
[Remote SSH Nightly for Raspi] No git repo found with latest vs code nightly update

### ISSUE THREAD

**Issue by thegabriele97** [microsoft/vscode-remote-release#676] opened 2019-06-13 08:44 UTC
- VSCode Version: 1.36.0 nightly (commit: d04b5d2eb16c156e24dbf44010c315d968694bd6)
- Local OS Version: Windows 10
- Remote OS Version: latest raspbian
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. Connect to raspi using remote-ssh nightly
2. Init a new repo
```sh
cd $HOME
mkdir repo
git init
```
or clone a repo
```sh
git clone http://....repo@github.com
```
3. **Open remote repo folder with vs code and no github repo is found.**

Log output from git inside vs code:
```
Looking for git in: git
Using git 2.11.0 from git
> git rev-parse --show-toplevel
> git rev-parse --absolute-git-dir
> git rev-parse --show-toplevel
> git rev-parse --absolute-git-dir
> git rev-parse --show-toplevel
> git rev-parse --absolute-git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --absolute-git-dir
> git rev-parse --show-toplevel
> git rev-parse --absolute-git-dir
> git rev-parse --show-toplevel
> git rev-parse --absolute-git-dir
> git rev-parse --show-toplevel
> git rev-parse --absolute-git-dir
```

**With a local git repo on my pc, it works perfectly**

**Comment by egamma** [comment] 2019-06-13 14:41
Duplicate of #671. Fix is in and new insiders build will be released.

**Closed by egamma** 2019-06-13 14:41 UTC
