### ISSUE TITLE
Container: stuck with init command `yarn`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#2428] opened 2020-02-25 15:58 UTC
Refs: https://github.com/microsoft/vscode-remote-release/issues/2407#

I am using Docker on Windows and opened a repository in Docker, which worked fine at first. I then added `initializeCommand: yarn` and can no longer open the container:

```
[0 ms] Start: Resolving remote
[4 ms] Start: Check Docker is running
[38 ms] Start: Run: docker build -f c:\Users\bpasero\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.103.0\scripts\volumeBootstrap.Dockerfile -t vsc-volume-bootstrap c:\Users\bpasero\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.103.0\scripts
[340 ms] 
[511 ms] Sending build context to Docker daemon   7.68kB

[570 ms] Step 1/2 : FROM alpine:3.11.2
 ---> cc0abc535e36
Step 2/2 : RUN apk add --no-cache       nodejs  git     openssh-client  docker-cli      ;
 ---> Using cache
 ---> 434d35954d9c
Successfully built 434d35954d9c
Successfully tagged vsc-volume-bootstrap:latest
[602 ms] 
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

[604 ms] Cloning Github repository: microsoft/vscode-remote-try-node.git into /workspaces/vscode-remote-try-node

[604 ms] Start: Run: docker run -d --mount src=vsc-remote-containers,dst=/workspaces,type=volume,volume-driver=local -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[1277 ms] Start: Run: C:\Program Files\Docker\Docker\resources\bin\docker.exe exec -i -u root fa09e39655d0ef1f2ad860b3971b392d21f1170e3aeb4201c04e74b471bbcc4e /bin/sh
[1282 ms] Start: Launching Remote-Containers helper.
[1283 ms] Start: Run in container: git config --global credential.helper '!f() { node /tmp/vscode-remote-containers-54b0a0f35661af7860e938b1d6472f82a654083b.js $*; }; f'
[1499 ms] 
[1499 ms] 
[1499 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-54b0a0f35661af7860e938b1d6472f82a654083b.js' >/tmp/vscode-remote-containers-54b0a0f35661af7860e938b1d6472f82a654083b.js
[1505 ms] 
[1505 ms] 
[1505 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-54b0a0f35661af7860e938b1d6472f82a654083b.js' >/tmp/vscode-remote-containers-server-54b0a0f35661af7860e938b1d6472f82a654083b.js
[1511 ms] 
[1511 ms] 
[1808 ms] Start: Run: docker exec -u root -e SSH_AUTH_SOCK=/tmp/vscode-ssh-auth-54b0a0f35661af7860e938b1d6472f82a654083b.sock -e REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-54b0a0f35661af7860e938b1d6472f82a654083b.sock fa09e39655d0ef1f2ad860b3971b392d21f1170e3aeb4201c04e74b471bbcc4e git clone https://github.com/microsoft/vscode-remote-try-node.git /workspaces/vscode-remote-try-node
[2117 ms] 
[2294 ms] fatal: destination path '/workspaces/vscode-remote-try-node' already exists and is not an empty directory.

[2336 ms] Repository 'microsoft/vscode-remote-try-node.git' was already cloned into '/workspaces/vscode-remote-try-node'.

[2336 ms] Start: Run in container: cat /workspaces/vscode-remote-try-node/.devcontainer/devcontainer.json 2>/dev/null
[2342 ms] Start: Run: docker exec -w /workspaces/vscode-remote-try-node -u root fa09e39655d0ef1f2ad860b3971b392d21f1170e3aeb4201c04e74b471bbcc4e /bin/sh -c yarn
[2665 ms] 
[2841 ms] /bin/sh: yarn: not found
[2882 ms] 

[2919 ms] Command failed: C:\Program Files\Docker\Docker\resources\bin\docker.exe exec -w /workspaces/vscode-remote-try-node -u root fa09e39655d0ef1f2ad860b3971b392d21f1170e3aeb4201c04e74b471bbcc4e /bin/sh -c yarn
```

![image](https://user-images.githubusercontent.com/900690/75264680-0ec85900-57f0-11ea-870f-183888279a7b.png)

**Comment by chrmarti** [comment] 2020-02-26 10:18
I think it makes sense to fail, we just need to offer a way out when this happens. Like a 'safe mode' where we start a container (e.g., with the debian image) with the volume mounted and the devcontainer.json being ignored.

**Comment by egamma** [comment] 2020-06-04 08:49
Duplicate of #2726

**Closed by egamma** 2020-06-04 08:49 UTC
Labels: bug, containers
