### ISSUE TITLE
$PATH set in postCreateCommand is not persisted 

### ISSUE THREAD

**Issue by SoumeshBanerjee** [microsoft/vscode-remote-release#1627] opened 2019-10-08 07:50 UTC
If I run a script to set `$PATH` in `postCreateCommand` and print at the end of the script `echo $PATH` it's been set and just after that those `$PATH` are gone in vscode extension context.

- VSCode Version: 1.38.1
- Local OS Version: MacOS X 10.15 Beta
- Remote OS Version: Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux
- Remote Extension/Connection Type: Docker

**Comment by chrmarti** [comment] 2019-10-21 12:43
`postCreateCommand` is run in its own shell, so this is expected behavior.

Couldn't you run the commands in your Dockerfile and then add to the system's default PATH (somewhere in `/etc/` I believe)?

**Comment by SoumeshBanerjee** [comment] 2019-10-22 07:08
Even if I run that script in Dockerfile using 
`RUN /opt/script.sh`

`$PATH` is set after the script is stopped, and `$PATH` can be access by subsequent script in the Dockerfile, but the same `$PATH` is unavailable inside the extension context

**Comment by chrmarti** [comment] 2019-10-22 12:42
Environment variables are not passed between independent shells but only to child processes. So `PATH` set in one `RUN` command won't be available in a later `RUN` command. You could use `ENV` to set the `PATH` for all following `RUN` commands and the VS Code process.

**Comment by SoumeshBanerjee** [comment] 2019-10-24 06:06
Yes `ENV PATH=...` can solve the problem, but it would be hardcoding the paths which we don't know ahead of time, there is a service written to check some versions of binaries installed and extract the `PATH` based on that.

The original docker image use to work because `PATH` was set in `ENTRYPOINT` and `CMD` is set to `/bin/bash`, so when user does simple `docker run -it img/name` it works, but now `vscode-remote` uses its own `entrypoint` with infinite loop, which can be overridden but it won't solves anything because `extension` is launched in different shell I suppose? Using `docker exec ...`

One hacky solution seems to be using `postCreateCommand` inject `PATH` to `.profile` or `.bashrc` file since `postCreateCommand` run only once. 
Another might be synlinking the computed PATH to a fixed path and hardcode that path into `ENV` in `Dockerimage`?

Do you have some other suggestions or better way of solving this?

**Comment by chrmarti** [comment] 2019-10-28 21:27
Your suggestions make sense. I'll close this 'as-designed' because we don't plan opening up the launching of the VS Code Server for injecting environment variables. Thanks.

**Closed by chrmarti** 2019-10-28 21:27 UTC
Labels: containers, needs-more-info
