### ISSUE TITLE
errors when openning an integrated vscode terminal on Red Hat based WSL2

### ISSUE THREAD

**Issue by DonEstefan** [microsoft/vscode-remote-release#7842] opened 2023-01-11 23:14 UTC
- VSCode Version: 1.74.3
- Local OS Version: Win10 21H2
- Remote OS Version: a Red Hat based WSL2 distro (RHEL, Alma, Rocky or OEL) in version 8 or 9
- Remote Extension/Connection Type: ms-vscode-remote.remote-wsl (v0.72.0 -> current as of January 2023)

<details>
  <summary>WSL Logs</summary>

```
[2023-01-11 21:47:11.426] Resolving wsl+AlmaLinux-8, resolveAttempt: 1
[2023-01-11 21:47:11.622] Starting VS Code Server inside WSL (wsl2)
[2023-01-11 21:47:11.622] Extension version: 0.72.0
[2023-01-11 21:47:11.622] Windows build: 19044. Multi distro support: available. WSL path support: enabled
[2023-01-11 21:47:11.979] Using shell environment from invoking shell: /tmp/vscode-distro-env.JzU93K
[2023-01-11 21:47:12.249] WSL daemon log file: 
[2023-01-11 21:47:12.251] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d AlmaLinux-8 -e sh -c "[ -d ~/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2023-01-11 21:47:12.701] Probing result: found
[2023-01-11 21:47:12.701] Server install found in WSL
[2023-01-11 21:47:12.703] Launching C:\WINDOWS\System32\wsl.exe -d AlmaLinux-8 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 97dec172d3256f8ca4bfb2143f3f76b503ca0534 stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=743005496-3612395673-1711756260-3149086450 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --disable-telemetry --telemetry-level=off'
[2023-01-11 21:47:13.026] Setting up server environment: Looking for /home/xxx/.vscode-server/server-env-setup. Not found.
[2023-01-11 21:47:13.027] WSL version: 5.15.79.1-microsoft-standard-WSL2 AlmaLinux-8
[2023-01-11 21:47:13.342] WSL-shell-PID: 86
[2023-01-11 21:47:13.342] Node executable: /home/xxx/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node
[2023-01-11 21:47:13.342] Starting server: /home/xxx/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/bin/code-server --host=127.0.0.1 --port=0 --connection-token=743005496-3612395673-1711756260-3149086450 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --disable-telemetry --telemetry-level=off
[2023-01-11 21:47:13.342] *
[2023-01-11 21:47:13.342] * Visual Studio Code Server
[2023-01-11 21:47:13.342] *
[2023-01-11 21:47:13.342] * By using the software, you agree to
[2023-01-11 21:47:13.342] * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
[2023-01-11 21:47:13.342] * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
[2023-01-11 21:47:13.342] *
[2023-01-11 21:47:13.342] Server bound to 127.0.0.1:33393 (IPv4)
[2023-01-11 21:47:13.342] Extension host agent listening on 33393
[2023-01-11 21:47:13.342] 
[2023-01-11 21:47:13.387] Started local proxy server on 59756.
[2023-01-11 21:47:13.387] WSL resolver response: 127.0.0.1:59756
[2023-01-11 21:47:13.387] To debug connection issues, open a local browser on http://127.0.0.1:59756/version
[2023-01-11 21:47:13.387] Using 'wslExeProxy' to connect to the VS Code server as configured by setting 'remote.WSL2.connectionMethod'
[2023-01-11 21:47:13.387] 'wslExeProxy' should fix reconnection issues after sleep and network adapter changes.
[2023-01-11 21:47:13.387] Please report issues related with the new setting to https://github.com/microsoft/vscode-remote-release/issues/5894
[2023-01-11 21:47:13.387] To revert back to the old way of connecting, change setting 'remote.WSL2.connectionMethod' to 'wsl2VMAddress'.
```
</details>

Steps to Reproduce:

1. install and launch a Red Hat based distro (RHEL, Alma, Rocky, OEL) in version 8 or 9 in WSL2
2. Run `code .`
3. Open an integrated terminal
4. Receive the following errors:
```
bash: which: line 1: syntax error: unexpected end of file
bash: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
/bin/sh: which: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `which'
```

Workaround: 
The issue seems to be related to parsing the "/etc/profile.d/which2.sh" file in vscode terminal
  1. `mv /etc/profile.d/which2.sh /etc/profile.d/which2.sh_disabled` in the wsl
  2. stop all instances of vscode
  3. stop the wsl completely via `wsl --shutdown` from outside (via windows cmd)
  4. Next time you start the wsl + vscode the problem is gone

Note: 
- The error messages are not printed when starting a regular wsl terminal - only when opening in the vscode terminal
- This issue has been reported before in #6784. The issue was closed even though all requested information was provided.

**Comment by aeschli** [comment] 2023-01-24 08:46
Duplicate of https://github.com/microsoft/vscode/issues/163564

Fix is in 0.75.1, available for the latest VS Code Insiders and soon for stable.

**Closed by aeschli** 2023-01-24 08:46 UTC
Labels: wsl
