### ISSUE TITLE
Remote extensions are not installed automatically from devcontainer.json

### ISSUE THREAD

**Issue by qazwsxedckll** [microsoft/vscode-remote-release#6755] opened 2022-05-25 06:21 UTC
- VSCode Version:1.67.2
- Local OS Version:Windows 21H1
- Remote OS Version: CentOS Linux release 7.9.2009 (Core) (both ssh and docker image)
- Remote Extension/Connection Type: SSH & docker
- Logs:

[69 ms] Remote-Containers 0.234.0 in VS Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5).
[69 ms] Start: Resolving Remote
[109 ms] Start: Run: ssh 172.26.136.47 /bin/sh
[131 ms] Start: Run in host: id -un
[483 ms] root
[484 ms]  Authorized only. All activity will be monitored and reported 
[484 ms] Start: Run in host: cat /etc/passwd
[496 ms] Start: Run in host: echo ~
[506 ms] /root
[506 ms] 
[507 ms] Start: Run in host: test -x '/root/.vscode-remote-containers/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node'
[517 ms] 
[517 ms] 
[517 ms] Exit code 1
[518 ms] Start: Run in host: test -x '/root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node'
[528 ms] 
[528 ms] 
[528 ms] Start: Run in host: test -f '/root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node_modules/node-pty/package.json'
[538 ms] 
[538 ms] 
[539 ms] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.234.0.js'
[548 ms] 
[548 ms] 
[557 ms] userEnvProbe: loginInteractiveShell (default)
[557 ms] userEnvProbe shell: /bin/bash
[767 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/root/bin:/opt/gradle-6.0.1/bin:/usr/java/latest/bin:/opt/apache-maven-3.8.5/bin'
Container: None
[778 ms] Setting up container for folder or workspace: /root/wangdec/xiot-platform
[779 ms] Host: ssh://172.26.136.47
[820 ms] Start: Check Docker is running
[820 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[922 ms] Server API version: 1.41
[923 ms] Start: Run in Host: docker volume ls -q
[1053 ms] Start: Run in Host: docker inspect --type container 970003c44787682b31353c8a8f0bc3b86d6a17ce57023f5d3ed59cca5393fc6d
[1139 ms] Start: Run in Host: docker rm -f 970003c44787682b31353c8a8f0bc3b86d6a17ce57023f5d3ed59cca5393fc6d
[1467 ms] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=/root/wangdec/xiot-platform --filter label=vsch.quality=stable
[1582 ms] Start: Run in Host: /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /root/wangdec/xiot-platform --workspace-mount-consistency cached --id-label vsch.local.folder=/root/wangdec/xiot-platform --id-label vsch.quality=stable --log-level debug --log-format json --config /root/wangdec/xiot-platform/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1876 ms] remote-containers 0.234.0.
[1876 ms] Start: Resolving Remote
[1886 ms] Start: Run: git rev-parse --show-cdup
[1905 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/root/wangdec/xiot-platform --filter label=vsch.quality=stable
[2002 ms] Start: Run: docker build -f /root/wangdec/xiot-platform/.devcontainer/Dockerfile -t vsc-xiot-platform-08daa1077b010a8499b2238e184f97b8 --no-cache --pull /root/wangdec/xiot-platform
Sending build context to Docker daemon  535.8MB
Step 1/1 : FROM registry.szlanyou.com/xiot-platform-dev/xiot-platform:latest
latest: Pulling from xiot-platform-dev/xiot-platform
Digest: sha256:cd5eea4e4e0dd677b7a54f8356b73c817739d680e4fa376a82b8961fae14a1ab
Status: Image is up to date for registry.szlanyou.com/xiot-platform-dev/xiot-platform:latest
 ---> 28e04b3e0c02
Successfully built 28e04b3e0c02
Successfully tagged vsc-xiot-platform-08daa1077b010a8499b2238e184f97b8:latest
[9455 ms] Start: Run: docker inspect --type image vsc-xiot-platform-08daa1077b010a8499b2238e184f97b8
[9537 ms] Start: Run: docker -v
[9617 ms] Start: Run: docker events --format {{json .}} --filter event=start
[9622 ms] Start: Starting container
[9623 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/root/wangdec/xiot-platform,target=/workspaces/xiot-platform --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/root/wangdec/xiot-platform -l vsch.quality=stable --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --entrypoint /bin/sh vsc-xiot-platform-08daa1077b010a8499b2238e184f97b8 -c echo Container started
Container started
[10313 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/root/wangdec/xiot-platform --filter label=vsch.quality=stable
[10406 ms] Start: Run: docker inspect --type container c48af9b25888
[10492 ms] Start: Inspecting container
[10493 ms] Start: Run: docker inspect --type container c48af9b25888b566eda6821787c1668256faf4a87d5adccfd8b3b0de5277c2c0
[10575 ms] Start: Run in container: /bin/sh
[10582 ms] Start: Run in container: uname -m
[10781 ms] x86_64
[10781 ms] 
[10781 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[10788 ms] NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[10789 ms] 
[10789 ms] Start: Run in container: cat /etc/passwd
[10797 ms] Start: Run in container: test -f '/var/vscode-server/.patchEtcEnvironmentMarker'
[10802 ms] 
[10803 ms] 
[10803 ms] Exit code 1
[10804 ms] Start: Run in container: test ! -f '/var/vscode-server/.patchEtcEnvironmentMarker' && set -o noclobber && mkdir -p '/var/vscode-server' && { > '/var/vscode-server/.patchEtcEnvironmentMarker' ; } 2> /dev/null
[10814 ms] 
[10815 ms] 
[10815 ms] Start: Run in container: cat >> /etc/environment <<'etcEnvrionmentEOF'
[10826 ms] 
[10826 ms] 
[10827 ms] Start: Run in container: test -f '/var/vscode-server/.patchEtcProfileMarker'
[10831 ms] 
[10831 ms] 
[10831 ms] Exit code 1
[10831 ms] Start: Run in container: test ! -f '/var/vscode-server/.patchEtcProfileMarker' && set -o noclobber && mkdir -p '/var/vscode-server' && { > '/var/vscode-server/.patchEtcProfileMarker' ; } 2> /dev/null
[10839 ms] 
[10839 ms] 
[10839 ms] Start: Run in container: sed -i -E 's/((^|\s)PATH=)([^\$]*)$/\1${PATH:-\3}/g' /etc/profile || true
[10847 ms] 
[10847 ms] 
[10882 ms] Start: Run in Host: docker inspect --type container c48af9b25888b566eda6821787c1668256faf4a87d5adccfd8b3b0de5277c2c0
[11053 ms] Start: Run in Host: /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /root/wangdec/xiot-platform --log-level debug --log-format json --config /root/wangdec/xiot-platform/.devcontainer/devcontainer.json --mount-workspace-git-root true
[11345 ms] remote-containers 0.234.0.
[11345 ms] Start: Run: git rev-parse --show-cdup
[11369 ms] Start: Inspecting container
[11370 ms] Start: Run in Host: docker inspect --type container c48af9b25888b566eda6821787c1668256faf4a87d5adccfd8b3b0de5277c2c0
[11517 ms] Start: Run in Host: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=17be5657-572e-4e9b-9fb2-9be84a6a48e51653456130794 c48af9b25888b566eda6821787c1668256faf4a87d5adccfd8b3b0de5277c2c0 /bin/sh
[11539 ms] Start: Run in container: uname -m
[11725 ms] x86_64
[11727 ms] 
[11729 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[11755 ms] NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[11757 ms] 
[11760 ms] Start: Run in container: cat /etc/passwd
[11797 ms] Start: Updating configuration state
[11905 ms] Start: Setup shutdown monitor
[11915 ms] Forking shutdown monitor: c:\Users\ly-wangdec\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\shutdown\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-9f9f091ae822485b2dc98a70008949203ce2eeee-sock singleContainer Debug c:\Users\ly-wangdec\AppData\Roaming\Code\logs\20220525T084509\exthost20\ms-vscode-remote.remote-containers 1653456131805
[11969 ms] Start: Run in container: test -d /root/.vscode-server
[11991 ms] 
[11992 ms] 
[11992 ms] Exit code 1
[11993 ms] Start: Run in container: test -d /root/.vscode-remote
[12021 ms] 
[12023 ms] 
[12023 ms] Exit code 1
[12026 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[12049 ms] 
[12050 ms] 
[12083 ms] Start: Run in Host: /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /root/wangdec/xiot-platform --log-level debug --log-format json --config /root/wangdec/xiot-platform/.devcontainer/devcontainer.json --include-features-configuration --mount-workspace-git-root true
[12442 ms] remote-containers 0.234.0.
[12442 ms] Start: Run: git rev-parse --show-cdup
[12467 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json
[12484 ms] 
[12485 ms] cat: /root/.vscode-server/data/Machine/settings.json: No such file or directory
[12485 ms] Exit code 1
[12487 ms] Start: Run in container: test -d /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
[12503 ms] 
[12506 ms] 
[12507 ms] Exit code 1
[12509 ms] Start: Run in container: test -d /vscode/vscode-server/bin/linux-x64/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
[12533 ms] 
[12534 ms] 
[12535 ms] Start: Run in container: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5' '/root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5'
[12567 ms] 
[12569 ms] 
[12569 ms] Start: Run in container: touch '/vscode/vscode-server/bin/linux-x64/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5'
[12570 ms] Start: Launching Remote-Containers helper.
[12574 ms] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-8f33953589fa70a206d38ac84c19ebc2108007a1.sock) forwarded to local host (\\.\pipe\openssh-ssh-agent).
[12576 ms] Start: Run in Host: gpgconf --list-dir agent-extra-socket
[12589 ms] 
[12590 ms] 
[12616 ms] sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/libexec
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
dirmngr-socket:/var/run/dirmngr/socket
agent-socket:/root/.gnupg/S.gpg-agent
homedir:/root/.gnupg
[12617 ms] 
[12618 ms] Start: Run in container: gpgconf --list-dir agent-socket
[12639 ms] sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/libexec
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
dirmngr-socket:/var/run/dirmngr/socket
agent-socket:/root/.gnupg/S.gpg-agent
homedir:/root/.gnupg
[12640 ms] 
[12640 ms] Start: Run in container: gpgconf --list-dir homedir
[12664 ms] sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/libexec
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
dirmngr-socket:/var/run/dirmngr/socket
agent-socket:/root/.gnupg/S.gpg-agent
homedir:/root/.gnupg
[12665 ms] 
[12665 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[12684 ms] 
[12685 ms] 
[12685 ms] Exit code 2
[12686 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[12690 ms] Start: Run in Host: docker exec -i -u root c48af9b25888b566eda6821787c1668256faf4a87d5adccfd8b3b0de5277c2c0 /bin/sh
[12695 ms] userEnvProbe: loginInteractiveShell (default)
[12697 ms] userEnvProbe shell: /bin/bash
[12719 ms] Start: Run in container: echo ~
[12723 ms] 
[12723 ms] 
[12724 ms] Start: Run in Host: gpgconf --list-dir homedir
[12744 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[12768 ms] sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/libexec
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
dirmngr-socket:/var/run/dirmngr/socket
agent-socket:/root/.gnupg/S.gpg-agent
homedir:/root/.gnupg
[12771 ms] 
[12784 ms] 
[12785 ms] 
[12785 ms] Start: Run in container: gpgconf --list-dir homedir
[12807 ms] sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/libexec
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
dirmngr-socket:/var/run/dirmngr/socket
agent-socket:/root/.gnupg/S.gpg-agent
homedir:/root/.gnupg
[12809 ms] 
[12809 ms] Start: Run in container: # Copy /root/.ssh/known_hosts to /root/.ssh/known_hosts
[12905 ms] 
[12908 ms] 
[12911 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system --replace-all credential.helper '!f() { /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /tmp/vscode-remote-containers-8f33953589fa70a206d38ac84c19ebc2108007a1.js $*; }; f' || true
[12927 ms] /root
[12927 ms] 
[12928 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-8f33953589fa70a206d38ac84c19ebc2108007a1.js' >/tmp/vscode-remote-containers-8f33953589fa70a206d38ac84c19ebc2108007a1.js
[12980 ms] 
[12981 ms] 
[12985 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[13004 ms] 
[13005 ms] 
[13005 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-8f33953589fa70a206d38ac84c19ebc2108007a1.js' >/tmp/vscode-remote-containers-server-8f33953589fa70a206d38ac84c19ebc2108007a1.js_1653456144810
[13121 ms] 
[13122 ms] 
[13179 ms] Start: Run in container: # Test for /root/.gnupg/pubring.gpg and gpg
[13218 ms] 
[13219 ms] 
[13221 ms] Start: Run in container: cat '/root/.vscode-server/data/Machine/.connection-token-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5' 2>/dev/null || (umask 377 && echo 'd6459f5b-1e59-461e-9353-0189b30301fa' >'/root/.vscode-server/data/Machine/.connection-token-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-32b27617-26f6-4edc-99a6-c7335a5ae0fb' && mv -n '/root/.vscode-server/data/Machine/.connection-token-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-32b27617-26f6-4edc-99a6-c7335a5ae0fb' '/root/.vscode-server/data/Machine/.connection-token-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5' && rm -f '/root/.vscode-server/data/Machine/.connection-token-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-32b27617-26f6-4edc-99a6-c7335a5ae0fb' && cat '/root/.vscode-server/data/Machine/.connection-token-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5')
[13266 ms] d6459f5b-1e59-461e-9353-0189b30301fa
[13267 ms] 
[13268 ms] Start: Run in container: # Copy /root/.gnupg/pubring.gpg to /root/.gnupg/pubring.gpg
[13271 ms] Start: Starting VS Code Server
[13274 ms] Start: Preparing Extensions
[13320 ms] 
[13322 ms] 
[13322 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.installExtensionsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[13351 ms] 
[13353 ms] 
[13361 ms] Extensions cache, install extensions: ms-vscode.cpptools-extension-pack, tibotix.definition-autocompletion, mhutchie.git-graph, eamodio.gitlens, VisualStudioExptTeam.vscodeintellicode, yzhang.markdown-all-in-one, shd101wyy.markdown-preview-enhanced, esbenp.prettier-vscode, albert.TabOut, Gruntfuggly.todo-tree
[13362 ms] Start: Run in container: test -d /root/.vscode-server/extensionsCache && ls /root/.vscode-server/extensionsCache || true
[13387 ms] 
[13388 ms] 
[13388 ms] Start: Run in container: # Test for /root/.gnupg/trustdb.gpg and gpg
[13421 ms] 
[13423 ms] 
[13425 ms] Start: Run in container: test -d /vscode/vscode-server/extensionsCache && ls /vscode/vscode-server/extensionsCache || true
[13448 ms] 
[13448 ms] 
[13449 ms] Start: Run in container: # Copy /root/.gnupg/trustdb.gpg to /root/.gnupg/trustdb.gpg
[13450 ms] Extensions cache, link in container: None
[13453 ms] Start: Run in Host: docker exec -i -u root -e SHELL=/bin/bash -e VSCODE_AGENT_FOLDER=/root/.vscode-server -w /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 c48af9b25888b566eda6821787c1668256faf4a87d5adccfd8b3b0de5277c2c0 /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 --extensions-download-dir /root/.vscode-server/extensionsCache --install-extension ms-vscode.cpptools-extension-pack --install-extension tibotix.definition-autocompletion --install-extension mhutchie.git-graph --install-extension eamodio.gitlens --install-extension VisualStudioExptTeam.vscodeintellicode --install-extension yzhang.markdown-all-in-one --install-extension shd101wyy.markdown-preview-enhanced --install-extension esbenp.prettier-vscode --install-extension albert.TabOut --install-extension Gruntfuggly.todo-tree --start-server 
[13500 ms] 
[13501 ms] 
[13502 ms] Start: Run in Host: gpg-connect-agent updatestartuptty /bye
[13536 ms] userEnvProbe PATHs:
Probe:     '/opt/rh/devtoolset-7/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin'
Container: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[13815 ms] *
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[13826 ms] Server bound to 127.0.0.1:36015 (IPv4)
Extension host agent listening on 36015

[13828 ms] Start: Run in container: echo 36015 >'/root/.vscode-server/data/Machine/.devport-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5'
[13847 ms] 
[13847 ms] 
[13849 ms] Port forwarding for container port 36015 starts listening on local port.
[13853 ms] Port forwarding local port 36015 to container port 36015
[13890 ms] Port forwarding connection from 50778 > 36015 > 36015 in the container.
[13891 ms] Start: Run in Host: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=17be5657-572e-4e9b-9fb2-9be84a6a48e51653456130794 c48af9b25888b566eda6821787c1668256faf4a87d5adccfd8b3b0de5277c2c0 /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node -e 
[13903 ms] Start: Run in container: # Test for /root/.gitconfig and git
[13936 ms] 
[13937 ms] 
[13937 ms] Start: Run in container: # Copy /root/.gitconfig to /root/.gitconfig
[13980 ms] 
[13981 ms] 
[14063 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global --replace-all credential.helper '!f() { /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /tmp/vscode-remote-containers-8f33953589fa70a206d38ac84c19ebc2108007a1.js $*; }; f' || true
[14089 ms] 
[14089 ms] 
[14297 ms] Port forwarding 50778 > 36015 > 36015 stderr: Connection established
[14315 ms] Installing extensions...
[14329 ms] [13:22:26] Extension host agent started.
[14487 ms] Port forwarding connection from 50779 > 36015 > 36015 in the container.
[14487 ms] Start: Run in Host: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=17be5657-572e-4e9b-9fb2-9be84a6a48e51653456130794 c48af9b25888b566eda6821787c1668256faf4a87d5adccfd8b3b0de5277c2c0 /root/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node -e 
[14645 ms] [13:22:26] ComputeTargetPlatform: linux-x64
[14724 ms] [13:22:26] [127.0.0.1][ed86ad0e][ManagementConnection] New connection established.
[14748 ms] Port forwarding 50779 > 36015 > 36015 stderr: Connection established
[14902 ms] [13:22:26] [127.0.0.1][8a48d067][ExtensionHostConnection] New connection established.
[14917 ms] [13:22:26] [127.0.0.1][8a48d067][ExtensionHostConnection] <294> Launched Extension Host Process.
</details>

Steps to Reproduce:

1. ssh to a remote machine(which is in the internal net of my corp and have internet access)
2. git clone a repo with devcontainer.json
3. rebuild and reopen in container
4. the extensions list in devcontainer.json are not installed automatically.
5. the extensions can be install manually by click "Install in Dev Container:"
{
	"name": "xxx",
	"build": {
		"dockerfile": "Dockerfile",
		"context": ".."
	},
	"runArgs": ["--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined"],

	// Set *default* container specific settings.json values on container create.
	"settings": {},

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"ms-vscode.cpptools-extension-pack",
		"tibotix.definition-autocompletion",
		"mhutchie.git-graph",
		"eamodio.gitlens",
		"VisualStudioExptTeam.vscodeintellicode",
		"yzhang.markdown-all-in-one",
		"shd101wyy.markdown-preview-enhanced",
		"esbenp.prettier-vscode",
		"albert.TabOut",
		"Gruntfuggly.todo-tree"
	]

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	// "remoteUser": "vscode"
}

It work fine on my own wsl2(which is also connect to my crop's net). I have checked several issues which have the same problem. It may related to proxy but I'm not setting any.

**Comment by ryanmerolle** [comment] 2022-05-25 13:42
I have the issue when using remote ssh extension and then navigating to a repo with a devcontainer I reopen in.

Exactly as you see above, I have extensions listed in the devcontainer.json, the extensions install just fine via the GUI, are listed in the devcontainer startup logs, but not shown as installed.  This works as intended using devcontainers in WSL locally.

**Comment by chrmarti** [comment] 2022-06-01 09:40
Are you behind a network proxy? Note that the extensions are installed in the background, so it might take a moment to finish. (I see the server logs `Installing extensions...`.)

**Comment by qazwsxedckll** [comment] 2022-06-02 10:39
I am probably behind a proxy but so is my own pc and wsl and I have no idea about how it is set up. The installation never finished. When I installed extensions by clicking the Install in Dev Container icon, the downstream speed went up first and the upstream speed went up on my local pc. So I guess the extensions were downloaded first and scp to the remote?

**Comment by chrmarti** [comment] 2022-06-03 09:49
You are right. We are tracking proxy support as https://github.com/microsoft/vscode-remote-release/issues/986. Closing as duplicate, thanks.

**Closed by chrmarti** 2022-06-03 09:49 UTC
Labels: containers, needs more info
