### ISSUE TITLE
VSCode Server could not register service workers when third-party cookies are disabled

### ISSUE THREAD

**Issue by URenko** [microsoft/vscode-remote-release#8256] opened 2023-03-24 08:07 UTC
- VSCode Version:
- Local OS Version:
- Remote OS Version: 1.76.2
- Remote Extension/Connection Type: Server
- The version of VS Code Server: 20220909.27

Steps to Reproduce:

1. launch code-server with `code-server`, follow the guide to use tunnel. (or `serve-local`, through nginx to provide HTTPS).
2. install the python extension.
3. use a browser with third-party cookies disabled. In my case, I use firefox and disable it by setting `network.cookie.cookieBehavior = 1` at about:config. (see https://kb.mozillazine.org/Network.cookie.cookieBehavior for details).
4. create an ipynb file and open it. Then you will get
```
Error: Could not register service workers: SecurityError: The operation is insecure..
```
6. set `network.cookie.cookieBehavior = 0` will make it work.

It seems that it try to register a service worker in `https://....vscode-cdn.net/...`, which break the rule of same origin.

It's not just ipynb, it seems that some other things that use service workers have the same problem, but I can't point it out right now.

I noticed a similar issue at the #6924 and contact him, but he allow third-party cookies now thus no longer faces this issue.

**Comment by mjbvz** [comment] 2023-03-28 23:07
Duplicate of https://github.com/microsoft/vscode/issues/176218

We aren't using cookies but unfortunately the third party cookies settings in some browsers also disables our service workers. Our webviews will not work without these

**Closed by mjbvz** 2023-03-28 23:07 UTC
