### ISSUE TITLE
Some translations in Source Control View are broken

### ISSUE THREAD

**Issue by gtianw** [microsoft/vscode-remote-release#10379] opened 2024-10-11 02:34 UTC
- VSCode Version:1.94.2
- Local OS Version:Windows_NT x64 10.0.19045
- Remote OS Version:Linux x64 5.15.153.1-microsoft-standard-WSL2
- Remote Extension/Connection Type: WSL

When the project is opened via `ms-vscode-remote.remote-wsl`, some translations in Source Control View are broken.
![Image](https://github.com/user-attachments/assets/dc59f0db-0bbb-4b88-b5b7-d36c192e9b33)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by TylerLeonhardt** [comment] 2024-10-23 23:10
This is a duplicate of https://github.com/microsoft/vscode/issues/151000

**Closed by TylerLeonhardt** 2024-10-23 23:10 UTC
