### ISSUE TITLE
I hope can use `code` command open file or folder

### ISSUE THREAD

**Issue by rectcircle** [microsoft/vscode-remote-release#1453] opened 2019-09-22 10:25 UTC
When I use vscode to develop locally, I am used to opening a file or directory using the shell command `code $file_or_dir`. But remote extendsion doesn't seem to support the code command, I hope I can open the file with `code` command in the remote shell of vscode.

**Comment by egamma** [comment] 2019-09-23 14:15
This is support when you execute the command from the integrated terminal in a remote context.

CLI support for opening a remote file/folder is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/585

**Closed by egamma** 2019-09-23 14:15 UTC
