### ISSUE TITLE
Failed to attach container with VS Code.

### ISSUE THREAD

**Issue by LiQiaopeng-1995** [microsoft/vscode-remote-release#8815] opened 2023-08-08 12:39 UTC
I use a Windows 10 laptop , use VS Code remote ssh to my company's Ubuntu16.04 desktop computer. and use Docker Remote to attach develop container in VS Code.
After recently update, I found I could't attach container to VS Code with error below:
Running the command remote-containers.attachToRunningContainerFromViewlet results in an error: Command in host failed: getent passwd $Company\$name. This may be caused by the extension that submitted remote-containers.attachToRunningContainerFromViewlet. 
I think this may be caused by  "\" in "$Company\$name.". But I don't know how to enclose the username in quotes.

**Comment by bamurtaugh** [comment] 2023-08-29 21:12
Thanks for filing. Closing as a dupe of https://github.com/microsoft/vscode-remote-release/issues/8811, but please let me know if this is a separate issue.

**Closed by bamurtaugh** 2023-08-29 21:12 UTC

**Comment by fehtemam** [comment] 2023-10-05 13:41
For anyone coming here from Google: I got this error with both recent versions of Dev Containers (0.315.0 & 0.315.1) with the following message:

```Error running command remote-containers.attachToRunningContainerFromViewlet: The operation was aborted. This is likely caused by the extension that contributes remote-containers.attachToRunningContainerFromViewlet.```

Downgraded to 0.309.0 and it is working again. 

On Ubuntu 22.04 on a remote server trying to connect to a container on that same remote server. Attaching shell worked but attaching VSCode did not. Downgrading resolved the issue.  VSCode 1.82
