### ISSUE TITLE
Remote SSH config files have no syntax colorization or intellisense

### ISSUE THREAD

**Issue by marcdepoe** [microsoft/vscode-remote-release#3785] opened 2020-10-01 15:10 UTC
I have installed the **Remote - SSH: Editing Configuration Files** extension (`ms-vscode-remote.remote-ssh-edit`), enabled globally. When I open config file located on my local machine, there is syntax colorization and keyword intellisense as advertised. When I open config file located on a remote machine, there is not.

**VS Code** v1.49.2

**Remote connection type** SSH

**Local OS**: Microsoft Windows 10 Pro
**Remote OS**: CentOS 8

Extensions
**Remote - SSH** v0.55.0 (enabled globally)
**Remote - SSH: Editing Configuration Files** v0.55.0 (enabled globally)

List of step to reproduce issue:
- Install extension **Remote - SSH: Editing Configuration Files**
- connect to remote server via SSH
- open remote config file (`~/.ssh/config`)

What I expect to see
- syntax colorization in the opened config file

What I actually see
- no syntax colorization

**Comment by bamurtaugh** [comment] 2020-10-28 19:34
@roblourens Is the Editing Configuration Files extension expected to provide colorizations for remote config files as well?

**Comment by roblourens** [comment] 2020-11-06 17:05
Yep. What language is in the status bar when you open this file? You should see 
![image](https://user-images.githubusercontent.com/323878/98394172-345c6200-200f-11eb-9481-19c40a1435ad.png)

**Comment by marcdepoe** [comment] 2020-11-06 18:24
Language Mode is `Plain Text`

It's unclear to me how the association is typically made, so for the time being I have manually made the following broad association in my roaming `settings.json`:

```json
"files.associations": {
    "config": "ssh_config"
}
```

And although I have no such association in my local `settings.json`, my local ssh config file does indeed have the proper Language Mode / association - **SSH Config** - when opened. I'm not sure what magic is at work.

**Comment by roblourens** [comment] 2020-11-07 00:33
It's registered for

```
"filenamePatterns": [
	"**/.ssh/config",
	"/etc/ssh/ssh_config"
],
```

and you said it's under `/ssh/config`, which makes sense, we are only looking for `.ssh`, I think that is more typical

**Comment by marcdepoe** [comment] 2020-11-07 16:30
Sorry, that was a typo on my part. It is in fact in the standard location `~/.ssh/config`.

Where am I supposed to be able to find the above registered `"filenamePatterns"` because I'm not seeing that anywhere and have the extension enabled globally. The extension doesn't seem to be doing anything actually.

**Comment by marcdepoe** [comment] 2020-11-07 19:33
For what it's worth, I updated my `settings.json` using the glob pattern you provided in place of what I had and strangely it wasn't matching. It ultimately matches only if I prefix `config` with a wildcard:
```json
"files.associations": {
    "**/.ssh/*config": "ssh_config"
}
```
This is despite the file being simply named `config`.

I did not add a rule for `/etc/ssh/ssh_config` but that file *is* properly associated.

**Comment by roblourens** [comment] 2020-11-07 19:33
You won't see it, it's in the extension's code. If you use `"**/.ssh/config"` in your `files.associations` setting then it works right?

**Comment by marcdepoe** [comment] 2020-11-12 20:56
@roblourens not sure if you saw my last comment as I posted it less than a minute before yours.

**Comment by roblourens** [comment] 2020-11-12 22:44
Oops, thanks for the ping.

> It ultimately matches only if I prefix config with a wildcard

No clue what's going on there. Any idea @aeschli?

**Comment by aeschli** [comment] 2020-11-13 08:44
I'm puzzled too,, also I can't reproduce out of the box. Make a remote connection (to a Mac, in my case), open the remote `~/./ssh./config`. Editor mode is `SSH Config`.
May I suggest to remove all file association settings (user/workspace/machine) and try again? Also Run with all extension disabled (except the SSH extensions).
What the reason could be that `"**/.ssh/*config"` works but not `"**/.ssh/config"` is that I believe we favor the longest matching. So maybe there's a `**/.ssh/config` somewhere else. @bpasero Actually knows all about language association.

**Comment by andyneff** [comment] 2020-11-13 19:55
Would it be possible to add

```
"firstLine":"^#.*\\bssh_config.*"
```

or something similar to the `shellscript` `languages` block, so any scenario that isn't covered has a way to add a comment to the first line to tell the syntax highlight to trigger?

**Comment by roblourens** [comment] 2020-11-13 20:29
@andyneff  Is that a typical thing to have in an ssh config file? You already have a workaround which is using `files.associations`.

@marcdepoe I guess I should ask what other extensions you have installed, something could interfere with this like @aeschli suggests

**Comment by andyneff** [comment] 2020-11-16 15:41
@roblourens No, I do not think that is a typical thing to have in an ssh config file. I was just thinking of other compromises that will help all users. For example if I have have two ssh config named `personal_ssh_config` and `personal_8_ssh_config` they don't have the same extension in that pattern. However if I got in the habit and named them `personal.ssh_config` and `personal_8.ssh_config` the `file.associations` would totally work.

**Comment by marcdepoe** [comment] 2020-11-17 15:24
Thank you all for your feedback.

> May I suggest to remove all file association settings (user/workspace/machine) and try again? Also Run with all extension disabled (except the SSH extensions).

I've disabled all extensions except **_Remote - SSH_** and **_Remote - SSH: Editing Configuration Files_** and I have also completely cleared out my local and workspace settings files. Still, when I open the remote file `~/.ssh/config` it is `Plain Text`.

I temporarily disabled **_Remote - SSH: Editing Configuration Files_** and as expected, `/etc/ssh/ssh_config` opened as plain text. When I re-enable, that file opens as `SSH Config` but `~/.ssh/config` still opens as `Plain Text`.

I even recreated the `~/.ssh/config` file just to be absolutely sure that it didn't strangely have a leading non-printable character on `config`.

I assume there's no way to programmatically determine where a file inherits its associated editor mode?

I will say it seems nice that with the wildcard that I'm using (`"**/.ssh/*config"`) I'm able to have alternate config files of the form `~/.ssh/custom_config` or `~/.ssh/custom.config` if I want the super fancy gear icon.

**Comment by roblourens** [comment] 2021-03-19 17:15
Sorry but I still don't know what's happening and can't repro, and I haven't gotten any other reports of this issue, so I'm going to close this.

**Closed by roblourens** 2021-03-19 17:15 UTC
Labels: bug, needs-more-info, ssh
