### ISSUE TITLE
[Remote-SSH Bug]: Reconnect to vsode fails with install script error

### ISSUE THREAD

**Issue by mmohdnowfal** [microsoft/vscode-remote-release#10453] opened 2024-11-08 09:27 UTC
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It connects successfully

### ->

Whenever there is an update from vscode and decide to restart vscode , remote SSH session doesn't connect back successfully to the remote machine after the restart
I see the below pop up message when i try to connect 
![Image](https://github.com/user-attachments/assets/b7578e0c-dd26-466d-a88c-7791667befa8)

Until i quit all the vscode session and open new connection the issue doesn't resolve

Toggling remote.SSH.useLocalServer did not help

### Expected Behavior

On updating the vscode Remote SSH Connection to the machine should be successful and able to use terminal, browse files

### Steps To Reproduce

1. Keep your remote SSH connection open 
2. Whenever there is an update from vscode, vscode will prompt to restart the vscode to update
3.  Select to Restart to update
4. Connection to remote will fail 

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```

[14:20:33.120] > vscode-cli-65edc4939843c90c34d61f4ce11704f09d   0%    0     0.0KB/s   --:-- ETA
[14:20:33.805] > vscode-cli-65edc4939843c90c34d61f4ce11704f09d   0%   32KB  46.9KB/s   03:07 ETA
> scp: write remote "/workspace/logedin_user/.vscode-server/vscode-cli-65edc4939843c90c34d61f4ce11704f09d3e5cb6.tar.gz": Failure
[14:20:34.497] > scp: failed to upload file vscode-cli-65edc4939843c90c34d61f4ce11704f09d3e5cb6.tar.gz to /workspace/logedin_user/.vscode-server
[14:20:35.172] > vscode-cli-65edc4939843c90c34d61f4ce11704f09d   0%    0     0.0KB/s   --:-- ETA
[14:20:35.511] > vscode-cli-65edc4939843c90c34d61f4ce11704f09d 100%    9     0.0KB/s   00:00    
> scp: write remote "/workspace/logedin_user/.vscode-server/vscode-cli-65edc4939843c90c34d61f4ce11704f09d3e5cb6.tar.gz.done": Failure
[14:20:36.186] > scp: failed to upload file vscode-cli-65edc4939843c90c34d61f4ce11704f09d3e5cb6.tar.gz.done to /workspace/logedin_user/.vscode-server
[14:20:36.683] > Found flag and server on host
[14:20:36.690] > 2540a8e641e4%%2%%
[14:20:36.722] > tar --version: tar (GNU tar) 1.28
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> ERROR: tar exited with a non-zero exit code: 2
> Already attempted local download, failing
> 2540a8e641e4: start
> exitCode==37==
[14:20:36.769] "Copy server to host" terminal command done
[14:20:37.024] > listeningOn====
> osReleaseId==rhel==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/254091==
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime==33==
> serverStartTime====
> execServerToken==1a1111aa-a111-1aaa-a111-a11111aaaa1a==
> platformDownloadPath==cli-alpine-x64==
> 2540a8e641e4: end
[14:20:37.024] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==rhel==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/254091==
platform==linux==
unpackResult==error==
didLocalDownload==1==
downloadTime====
installTime==33==
serverStartTime====
execServerToken==1a1111aa-a111-1aaa-a111-a11111aaaa1a==
platformDownloadPath==cli-alpine-x64==

[14:20:37.029] Resolver error: Error: Failed to install the VS Code Server
	at v.ServerInstallError (/Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:575896)
	at d (/Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:569305)
	at t.handleInstallOutput (/Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:571275)
	at t.tryInstall (/Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:691495)
	at async /Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:650540
	at async t.withShowDetailsEvent (/Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:653784)
	at async x (/Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:647325)
	at async t.resolve (/Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:651199)
	at async /Users/logedin_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.116.2024110715/out/extension.js:2:931367
[14:20:37.033] ------




[14:20:37.266] "install" terminal command done
[14:20:37.266] Install terminal quit with output: 



```

</p>
</details>

### Anything else?

Similar issue previously raised by me , https://github.com/microsoft/vscode-remote-release/issues/10326
Which closed without any resolution

**Comment by joshspicer** [comment] 2024-11-08 22:26
Was this a one-time issue you hit on the latest upgrade, or are you able to consistently reproduce?   You only see this on VS Code upgrades?

```
> scp: write remote "/workspace/logedin_user/.vscode-server/vscode-cli-65edc4939843c90c34d61f4ce11704f09d3e5cb6.tar.gz.done": Failure
```

From the log, this could probably be attributed to some network transient issue on your host or the remote, although it looks like our check for identifying success (copying a flag: `Found flag and server on host`) is wrong

**Comment by mmohdnowfal** [comment] 2024-11-12 15:51
On every new vscode update i will be facing this issue, while connecting for the first time. I have to quit all my instance of vscode and then reconnect again to fix this issue, after this everything will work normal until next update. 
We face the same issue with multiple such remote and local machines.

**Comment by joshspicer** [comment] 2024-11-18 21:29
Can you try using scp manually to demonstrate that you're able to scp from your local machine to the host?  Unforunately the error from scp in your log is not too clear.

Could you (1) share the entire Remote - SSH log (it appears you've truncated it) and (2) try manually running the scp command that you'll find in your log with the verbose flag

**Comment by joshspicer** [comment] 2024-11-18 21:32
> On every new vscode update i will be facing this issue

Could you share the most recent extension version where this behavior does not repro?

**Comment by mmohdnowfal** [comment] 2024-11-19 02:11
> Can you try using scp manually to demonstrate that you're able to scp from your local machine to the host? Unforunately the error from scp in your log is not too clear.
> 
> Could you (1) share the entire Remote - SSH log (it appears you've truncated it) and (2) try manually running the scp command that you'll find in your log with the verbose flag
> 
> I ask for the entire log as the extension should be attempting to download the VS Code server from the remote host . Have you disabled that manually, does your remote environment not have access to the internet, or is there also an error there?

issue is seen while there is a new update from vscode, so i will need some time to provide these info. I will try reproducing the issue after downgrading the vscode.  
One thing i have already confirmed is whether i am able to SSH or open a vnc session to the same remote host , ssh/vnc works without any issue. I haven't tried SCP yet, i will verify this

**Comment by joshspicer** [comment] 2024-12-13 19:56
Reading over again, it sounds like consistently (after an update) closing VS Code once makes everything work?  You will need to close all VS Code windows anyway after an update?  Could you manually close your SSH windows before restarting? The setting `window.restoreWindows` could also help here to not automatically restore all windows.  Perhaps you can set the `"update.mode": "none"` setting so that you're fully in control of when the update happens?

**Closed** 2024-12-21 12:32 UTC
Labels: ssh, info-needed
