### ISSUE TITLE
VS Code Server for WSL Failed to Start. No messages received for 90s

### ISSUE THREAD

**Issue by ggadget6** [microsoft/vscode-remote-release#1366] opened 2019-09-04 23:18 UTC
I've been having this problem for some time now. It only occurs after closing VS Code and then reopening. I'm using WSL1, not WSL2.

VSCode Version: 1.39.0-insider and 1.38.0
Local OS Version: Windows 10 1803
Remote OS Version: Ubuntu
Remote Extension/Connection: WSL
Steps to Reproduce:

Open VS Code.
Open a new Remote-WSL window.
Close VS Code.
Reopen VS Code, and open a new Remote-WSL window
Does this issue occur when all extensions are disabled?: Yes (except the Remote-WSL extension)

This issue does not occur if VS Code is opened using the "code ." command in the Ubuntu bash shell in windows both times. It also doesn't occur if the Ubuntu bash shell is left open in the background while running VS Code the two times.

The issue seems similar to #894, but that uses WSL2. It also seems similar to #133, but this issue is occurring with bash (not zsh) and with no proxy being used.

![Image](https://user-images.githubusercontent.com/33883297/64299860-b99a4180-cf48-11e9-89ec-40bb8460c2e8.JPG)

**Comment by aeschli** [comment] 2019-09-10 09:00
Can you enable the setting `"remote.WSL.debug": true`, run again and attach the content of the WSL log/terminal?

**Comment by ggadget6** [comment] 2019-09-10 22:59
Unfortunately, it seems like that didn't change much, unless I'm looking at the wrong thing
![Picture](https://user-images.githubusercontent.com/33883297/64656342-21df9c00-d3fd-11e9-98c3-1fe38e77dad3.JPG)

**Comment by aeschli** [comment] 2019-09-11 08:44
That should look different. Can you close all VSCode windows reopen again?

**Comment by aeschli** [comment] 2019-09-11 08:59
Actually, no, it seems the debug option was recognised (env was added to the command line). Maybe an issue with wsl.exe

Can you manually run `c:\windows\System32\wsl.exe sh -c 'env'` from a windows command prompt?

**Comment by ggadget6** [comment] 2019-09-11 17:02
I can run that command before wsl has crashed (i.e. after a restart), but not afterwards. Here's the output from before, and I'll add a screenshot too: 

USER=rushilk
SHLVL=1
HOME=/home/rushilk
LOGNAME=rushilk
NAME=RushilSurface
_=/bin/sh
TERM=xterm-256color
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/MATLAB/R2018b/bin:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/ggadg/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/ggadg/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/ggadg/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/ggadg/AppData/Roaming/npm:/mnt/c/Users/ggadg/AppData/Local/atom/bin:/mnt/c/Users/ggadg/AppData/Local/Programs/Microsoft VS Code/bin
LANG=C.UTF-8
SHELL=/bin/bash
PWD=/mnt/c/Windows/System32
HOSTTYPE=x86_64
![Capture 3](https://user-images.githubusercontent.com/33883297/64718448-3458e480-d494-11e9-8ac1-f60200958b8d.JPG)


After wsl has crashed (which I can cause by running the sequence of steps in my first post) the command you asked me to run no longer works.

**Comment by espositofulvio** [comment] 2019-09-20 13:42
Hi,
I'm getting the same problem, I can confirm it works if I type "code ." in a wsl shell, but it gets stuck when opening a WSL folder from within VSCode. 

I ran `c:\windows\System32\wsl.exe sh -c 'env'` from a command prompt and the result was
 
```
USER=fulvio
SHLVL=0
HOME=/home/fulvio
OLDPWD=/mnt/c/Users/fulvi
PYENV_SHELL=zsh
WSL_DISTRO_NAME=Ubuntu-18.04
LOGNAME=fulvio
NAME=undisclosed
_=/bin/sh
TERM=xterm-256color
PATH=/home/fulvio/.pyenv/shims:/home/fulvio/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/ProgramData/Boxstarter:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files/Git/cmd:/mnt/c/tools/php7:/mnt/c/Program Files/nodejs/:/mnt/d/Software/Python3/Python3.7.4/Scripts/:/mnt/d/Software/Python3/Python3.7.4/:/mnt/d/Software/rust/.cargo/bin:/mnt/c/Users/fulvi/.poetry/bin:/mnt/d/Software/rust/bin:/mnt/c/Users/fulvi/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/fulvi/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/fulvi/AppData/Roaming/Composer/vendor/bin:/mnt/c/Program Files (x86)/REFPROP/:/mnt/d/Software/flutter/bin:/mnt/d/Software/AndroidSDK/tools/bin:/mnt/d/Software/AndroidSDK/platform-tools/:/mnt/c/tools/cmdermini/bin:/mnt/c/Users/fulvi/AppData/Roaming/npm:/mnt/d/Software/vscode/bin
LANG=en_GB.UTF-8
SHELL=/usr/bin/zsh
PWD=/mnt/c/Users/fulvi
PYENV_ROOT=/home/fulvio/.pyenv
HOSTTYPE=x86_64
WSLENV=
```

**Comment by aeschli** [comment] 2019-09-26 09:31
Can you find out if has to do with the folder you are opening with `code .`?
Close all VScode windows, and use `code .` on a folder with little content.

**Comment by espositofulvio** [comment] 2019-09-26 09:40
Nope, every folder I tried works if I type `code .` from a wsl shell, but opening the folder directly from VSCode always gives the error.

**Comment by DavidA2014** [comment] 2019-10-03 16:13
I am running VS Code 1.38.1 from behind a company proxy server. When I execute:

    F1: Remote=WSL: New Window using Distro...

from Code running in Windows, for Ubuntu 18.04 WSL, I see:

    Downloading:     
    VS Code Server for WSL failed to start. No messages received for 90s

How can I fix this please?

**Comment by RodrigoCMoraes** [comment] 2019-10-14 02:36
In reddit I see an workaround for that, just remove or comment any line in your ```.bashrc``` that have ```cd```.

But for me, I had to remove the line command: ``` source "$BASH_IT"/bash_it.sh```. Because I use bashit as bash style.

Hope that helps.

**Comment by espositofulvio** [comment] 2019-10-14 06:44
It looks like the problem went away with the 1.39 update, at least for me.

**Comment by ggadget6** [comment] 2019-10-14 06:49
@espositofulvio Wow, perfect timing. Same thing here, I was just testing it out and I don't seem to be having the issue. Whoo!

Not exactly sure what changed, but whatever it was seemed to fix it.

**Comment by DavidA2014** [comment] 2019-10-14 11:20
I have Code v.1.39.1 but I still have the problem.

**Comment by aeschli** [comment] 2019-10-29 10:35
Closing as this works now for @ggadget6 and @espositofulvio 

@DavidA2014 Let's continue the issues caused by proxies in #1611

**Closed by aeschli** 2019-10-29 10:35 UTC
Labels: wsl
