### ISSUE TITLE
can't save root files

### ISSUE THREAD

**Issue by Bahubali-Dev** [microsoft/vscode-remote-release#3419] opened 2020-07-24 11:39 UTC
Issue Type: <b>Bug</b>

after editing root files in centos 7 not allowing to save the file

Extension version: 0.51.0
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.0-1127.13.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: centos8|
|OS|Linux x64 3.10.0-1127.13.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (1 x 2300)|
|Memory (System)|0.47GB (0.02GB free)|
|VM|0%|
</details>

**Comment by Chuxel** [comment] 2020-07-24 13:34
Duplicate of #1688

**Closed by Chuxel** 2020-07-24 13:34 UTC
