### ISSUE TITLE
Some extensions not display right.

### ISSUE THREAD

**Issue by Hypnoes** [microsoft/vscode-remote-release#3890] opened 2020-10-22 06:23 UTC
- VSCode Version: 1.50.1(user setup)
- Local OS Version: Windows_NT x64 10.0.19041
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: wsl2

![image](https://user-images.githubusercontent.com/13956546/96832848-005f3980-1472-11eb-806b-c36037515a98.png)

![image](https://user-images.githubusercontent.com/13956546/96832893-153bcd00-1472-11eb-8364-ab0ed78fce02.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Hypnoes** [comment] 2020-10-22 06:25
Extensions are working, just not right displayed.

**Comment by aeschli** [comment] 2020-11-05 19:25
Likely a duplicate of https://github.com/microsoft/vscode/issues/97564

Can you check 
- open regedit.exe
- search for `svg`
You should see Content Type image/svg+xml

**Comment by Hypnoes** [comment] 2020-11-06 01:26
![image](https://user-images.githubusercontent.com/13956546/98314795-b8174e00-2011-11eb-9cf5-ba15f9256731.png)
I' do find one. Infect their many 'svg‘ content I find.

**Comment by Hypnoes** [comment] 2020-11-06 01:40
I had checked `class_root/.svg`  according to microsoft/vscode#97564 and yes here it is.
![image](https://user-images.githubusercontent.com/13956546/98315809-0c233200-2014-11eb-962b-a03c7f5b3d12.png)

**Comment by aeschli** [comment] 2020-11-06 08:12
Thanks for checking, all looks good there. that was not the issue.

The console says 500 Internal Privoxy Error. I'm not familiar with Privoxy, but can it be that it filters access to certain resources?

We access the images and fonts from 'remote extensions' (extension installed in WSL) through URIs like:
```vscode-remote-resource://192.168.88.62:43665/vscode-remote-resource?path=%2Fhome%2Faeschli%2F.vscode-server-insiders%2Fextensions%2Fms-azuretools.vscode-docker-1.7.0%2Fresources%2Fdark%2Frefresh.svg&tkn=1c48f79d-1c63-429a-9b5a-9742e2dacea0```

Maybe you need to configure [Privoxy](https://www.privoxy.org/) to allow these accesses.

**Comment by Hypnoes** [comment] 2020-11-09 01:23
@all I'm closing this issue cuz I found the problem. It caused by shadowsocks (a proxy client) in version `4.3.1.128`, which use wrong proxy-rule in certain range of local ip address.  And it is now fixed by update. Thanks for all tracking this issue.

**Closed** 2020-11-09 01:24 UTC
Labels: needs-more-info, wsl
