### ISSUE TITLE
sleep 180 infinity processes

### ISSUE THREAD

**Issue by forgetfr** [microsoft/vscode-remote-release#6286] opened 2022-02-04 20:47 UTC
Am seeing the same issue as #968 (https://github.com/microsoft/vscode-remote-release/issues/968)  but it is closed.

Many of our users are using vscode-extension-ssh to connect to the HPC environment. 
Unfortunately after terminating properly VSCode many persistent processes (ssh -> bash -> sleep) remained on the system indefinitely. This as a negative effect on the next attempts of those users to connect.

Could you provide a solution to fix this issue, or an explanation.

ADD: The users are using the last version of VSCode and the extension on Windows 10. This behavior can be simulated on Fedora35, Ubuntu 21.10 and on RHEL8.3

Thanks,

Example of process remained of system hours after a properly disconnection
```
# ps -ef | grep $username$
root           940     788  0 15:16 ?        00:00:00 sshd: $username$ [priv]
$username$     945       1  0 15:16 ?        00:00:00 /usr/lib/systemd/systemd --user
$username$     947     945  0 15:16 ?        00:00:00 (sd-pam)
$username$     954     940  0 15:16 ?        00:00:00 sshd: $username$@pts/0
$username$     955     954  0 15:16 pts/0    00:00:00 -bash
root           984     788  0 15:18 ?        00:00:00 sshd: $username$ [priv]
$username$     988     984  0 15:18 ?        00:00:00 sshd: $username$@notty
$username$     989     988  0 15:18 ?        00:00:00 bash
root          1177     788  0 15:19 ?        00:00:00 sshd: $username$ [priv]
$username$    1181    1177  0 15:19 ?        00:00:00 sshd: $username$@notty
$username$    1182    1181  0 15:19 ?        00:00:00 bash
$username$    1476    1182  0 15:41 ?        00:00:00 sleep 180
$username$    1477     989  0 15:41 ?        00:00:00 sleep 180
$username$    1481     955  0 15:44 pts/0    00:00:00 ps -ef
$username$    1482     955  0 15:44 pts/0    00:00:00 grep --color=auto $username$
```

**Comment by gad83** [comment] 2022-02-04 20:53
i'm actually having the same problem with my servers.
users are using vscode and working normally
my nightly verifications made me aware of users that have finished working but had many persistent processes still running
those processes are mainly ssh, bash and sleep 180

**Comment by tanhakabir** [comment] 2022-02-08 06:12
This is the current expected behavior of the `sleep`:

Linux - it dies when ssh disconnects
Windows - it gets orphaned when ssh disconnects so it polls the process tree to detect when that happens, then terminates itself

And both of you are saying that long after VS Code is terminated you see these sleep processes? I believe they only close after 3 minutes and you can't check within VS Code since that would keep it alive, you'd have to check separately. https://github.com/microsoft/vscode-remote-release/issues/968 was fixed which is why it was closed. Are you seeing a regression on this? More specific details about the fix start here: https://github.com/microsoft/vscode-remote-release/issues/968#issuecomment-520019656

**Comment by forgetfr** [comment] 2022-02-08 15:19
Hi @tanhakabir ,

I read the #968 and unfortunately ssh, sleep and a bash processes still on system several days after the user disconnect the connection inside the menu of VS Code, or by closing VS Code.

As myself, I closed VS Code last friday, and I can see processes link to my username on the system today (5 days later).

To make sure it was not related to the system on which I'm connecting, I pop up an Ubuntu 21.10 VM on my Windows 10 laptop, with the default system configuration, the same behavior can be reported. I even try with a fedora 35 VM with the default configuration.

Thanks for your help!

**Comment by ryanpatiency** [comment] 2022-09-07 03:13
I have encounter the same issue. Every time I reconnect to server due to ssh disconnect, A new `sleep 180` process was create but leave the old one alive. So by the date I notice, there are like 10 `sleep 180` process on the server. I use the 1.71 vscode and update my ssh extension already

**Comment by qishansun** [comment] 2022-11-03 14:16
same issue here.

**Comment by roblourens** [comment] 2022-12-17 05:16
Likely dupe of https://github.com/microsoft/vscode-remote-release/issues/7642 (fix merged but not released)

**Closed by roblourens** 2022-12-17 05:16 UTC
Labels: bug, ssh
