### ISSUE TITLE
I lost my open editors again

### ISSUE THREAD

**Issue by renoX** [microsoft/vscode-remote-release#2416] opened 2020-02-24 09:32 UTC
Issue Type: <b>Bug</b>

Very often following a reboot of the remove Linux server or sometimes even after just a disconnection/reconnection of the network (due to the Windows client PC going to sleep), I lost my open editors.
That's very annoying.

Extension version: 0.49.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.176-2.NSN.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.183.129.109|
|OS|Linux x64 4.4.176-2.NSN.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (24 x 2100)|
|Memory (System)|94.42GB (71.37GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment] 2020-03-02 22:50
Can you explain in more detail? Do you just mean that you had some tabs open and then you were disconnected, and reloaded the window, and then those tabs were gone?

Do you have a folder open in the remote window?

**Comment by renoX** [comment] 2020-03-03 13:29
>Do you just mean that you had some tabs open and then you were
disconnected, and reloaded the window, and then those tabs were gone?

Yes.

>Do you have a folder open in the remote window?

I'm not 100% sure but I think that the last time it happened to me, I
didn't have a folder opened, just files.

Best regards,
Renaud



Le lun. 2 mars 2020 à 23:50, Rob Lourens <notifications@github.com> a
écrit :

**Comment by roblourens** [comment] 2020-03-04 15:56
I've tried and haven't been able to reproduce this. Any ideas @bpasero?

**Comment by bpasero** [comment] 2020-03-04 17:15
Yeah this can happen locally as well:
* open a couple of files from a folder
* close VSCode
* delete the folder
* start VSCode

=> all tabs are gone

This is because we try to open an editor and that fails, then we close the editor and try to open the next. 

We cannot show the editor because we have no contents to display if we cannot load the contents, so we close it.

**Comment by roblourens** [comment] 2020-03-04 17:49
I see that if I reload the window and am not able to connect, but I think @renoX is saying that it connects successfully after reloading the window, is that right?

**Comment by renoX** [comment] 2020-03-05 10:01
Usually it doesn't manage to reconnect the first time, I have to press the
button "reconnect/reload "the window two times (it did this to me this
morning again).

I've tried with a folder opened and I lost my opened tab again after
reconnection (after having to reconnect twice).

Maybe it's because I did a git pull in the server in the meantime (during
the period that the Windows client was disconnected)?

Or could it be an issue due to the ssh client on Windows?

Best regards,
Renaud



Le mer. 4 mars 2020 à 18:49, Rob Lourens <notifications@github.com> a
écrit :

**Comment by tiptronic85** [comment] 2020-03-27 09:08
@roblourens 
It happens also to me and it's very annoying.
The version of the plugin is not important because happened with 0.49 and still with 0.50 and 0.50.1
In the log console i cannot see nothing of useful, but if you need a log tell me where i can find it.
Thank you in advance

**Comment by tiptronic85** [comment] 2020-04-08 07:52
I have a log of this morning:

IP Address: 192.168.1.171
Extension host agent listening on 43060


[09:47:38] Extension host agent started.
[09:48:04] [127.0.0.1][a795bbe9][ManagementConnection] New connection established.
[09:48:04] [127.0.0.1][3b518176][ExtensionHostConnection] New connection established.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
mesg: ttyname failed: Inappropriate ioctl for device
[09:48:06] [127.0.0.1][3b518176][ExtensionHostConnection] <9873> Launched Extension Host Process.
[09:49:09] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)

**Comment by tiptronic85** [comment] 2020-04-10 07:41
It happens everyday at the first opening of vscode

**Comment by bamurtaugh** [comment] 2020-11-04 00:55
Possible dupe of/related to https://github.com/microsoft/vscode-remote-release/issues/3475?

**Comment by roblourens** [comment] 2020-11-05 20:06
I think this is https://github.com/microsoft/vscode-remote-release/issues/3475. Will close in favor of that since I like the repro steps. Thanks @bamurtaugh!

**Closed by roblourens** 2020-11-05 20:06 UTC
Labels: bug, needs-more-info, ssh
