### ISSUE TITLE
Better open folder experience

### ISSUE THREAD

**Issue by titaneric** [microsoft/vscode-remote-release#862] opened 2019-06-28 15:23 UTC
Issue Type: <b>Feature Request</b>

When using the ssh extention to connect to guest computer, open folder will list all the directories under current folder "inside" the VS code, which I think is good.

However, when typing some prefix of given folder name at the upper path bar, the background color of file name under list will only turn blue. Make me hard to locate the folder.

![](https://imgur.com/6Z1aV5W.png)

Maybe there are several ways to improve it:

1. Support the automatic complete, use the "tab".
2. The list will only show the filtered folder name.

Look forward to improving it, thank you all.

Extension version: 0.42.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment] 2019-07-01 08:50
Looks like everyone is thinking about this at the same time :) Duplicate of https://github.com/microsoft/vscode/issues/76295

**Closed** 2019-10-01 10:44 UTC
