### ISSUE TITLE
Failure to log in loses state

### ISSUE THREAD

**Issue by dymil** [microsoft/vscode-remote-release#3842] opened 2020-10-13 00:06 UTC
Issue Type: <b>Bug</b>

If I re-open VSCode having last been working in a remote workspace, but then the log-in fails (say, because I left the prompt open and the server booted me), retrying results in all my open editor tabs being closed, which would not be the case had I successfully logged in the first time around. I don't believe this is the expected behaviour from a user's perspective.

Extension version: 0.55.0
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.111.1.amd64-smp

**Comment by bamurtaugh** [comment] 2020-10-28 22:17
Thanks for opening this @dymil. I believe this is the same as https://github.com/microsoft/vscode-remote-release/issues/3475, so closing to avoid duplicate issues. If I've misunderstood your issue or you have any other questions or feedback, please just let me know, and I'd be happy to reopen or discuss further.

**Closed by bamurtaugh** 2020-10-28 22:17 UTC
Labels: ssh

**Comment by dymil** [comment] 2020-10-29 00:37
I think it's subtly different from the stated issue in that steps 1&2 don't apply – here, there isn't an open connection and then an SSH connection failure, but just a failure from the get-go. I could easily see "This issue also occurs if VSCode is closed while in state 3.b" sharing a root cause though.

**Comment by bamurtaugh** [comment] 2020-11-02 20:38
Thanks for the additional info @dymil. As you mention, this sounds like potentially a shared root cause as the linked issue, although the steps vary a bit.

Just so that your issue doesn't get lost (as 3475 has a few more comments), I think it might make sense for me to go ahead and comment your issue in that thread as a potential alternate path resulting in the same lost state. 

If it turns out the issues don't share a root cause, or it would overall just work out better to separate them out, I'll go ahead and reopen this issue.
