### ISSUE TITLE
Extension can't start when debugging extension source code using remote

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-remote-release#1830] opened 2019-11-12 02:08 UTC
VSCode Version: 1.40.0
Remote Development Version :0.17.0

My extension source code is on remote linux machine. I opened source code using remote-development on windows and debug extension, but extension can't start. I set log level to 'trace' but no helpful logs.

**Comment by Lennon925** [comment] 2019-11-12 02:11
There is only line in my extension source code: ‘console.log('Extension start to active!');’. This log didn't occur after debug.

**Comment by chrmarti** [comment] 2019-11-12 06:45
What's in the Debug Console?

**Comment by weinand** [comment] 2019-11-12 08:05
@Lennon925 how is your extension activated?

**Comment by Lennon925** [comment] 2019-11-13 01:06
> @Lennon925 how is your extension activated?

My extension will be activated when you open a .c or .cpp file.
	"activationEvents": [
		"onLanguage:c",
		"onLanguage:cpp"
	],

**Comment by Lennon925** [comment] 2019-11-13 01:55
> What's in the Debug Console?

![12](https://user-images.githubusercontent.com/39362073/68726214-be8c0900-05fb-11ea-8b21-2794b91ae711.PNG)

**Comment by Lennon925** [comment] 2019-11-13 07:40
![345](https://user-images.githubusercontent.com/39362073/68742753-e5faca00-062b-11ea-8056-5ee3303579a4.PNG)

**Comment by Lennon925** [comment] 2019-11-13 07:54
It seems that it's not stable, I tried many times and only one time extension was actived and debugged. Most of time extension can't be actived. One time extension was actived but can't be debugged.

**Comment by weinand** [comment] 2019-11-13 09:08
@Lennon925 what exactly is your setup? Please provide detailed steps so that I can reproduce the issue (ideally based on the "hello world" extension from https://code.visualstudio.com/api/get-started/your-first-extension)

**Comment by Lennon925** [comment] 2019-11-14 01:14
> @Lennon925 what exactly is your setup? Please provide detailed steps so that I can reproduce the issue (ideally based on the "hello world" extension from https://code.visualstudio.com/api/get-started/your-first-extension)

1. git clone 'hello world' extension source code to your linux machine.
2. open this extension source code on your windows using remote development.
3. click 'run extension' to debug this extension on your windows
4. after debug mode launched, you will see this extension won't be actived. And also it can't be debugged if you set a breakpoint on code.

**Comment by Lennon925** [comment] 2019-11-14 02:07
maybe it will be helpful

![344](https://user-images.githubusercontent.com/39362073/68820556-95847a80-06c6-11ea-8be3-e6056d5e5698.PNG)

**Comment by Lennon925** [comment] 2019-11-15 01:51
> @Lennon925 what exactly is your setup? Please provide detailed steps so that I can reproduce the issue (ideally based on the "hello world" extension from https://code.visualstudio.com/api/get-started/your-first-extension)

Any update？

**Comment by sean-mcmanus** [comment] 2019-11-15 20:55
Our C/C++ extension has hit the same issue, i.e. there doesn't appear to be a way to deploy a development bits onto the remote machine -- my workaround was to install a "debug" vsix with more logging.

**Comment by Lennon925** [comment] 2019-11-18 09:18
> Our C/C++ extension has hit the same issue, i.e. there doesn't appear to be a way to deploy a development bits onto the remote machine -- my workaround was to install a "debug" vsix with more logging.

thank you very much. my current workaround is same with you.

**Comment by weinand** [comment] 2019-11-18 09:27
@chrmarti do you understand what "there doesn't appear to be a way to deploy a development bits onto the remote machine" means?

**Comment by chrmarti** [comment] 2019-11-18 10:12
No, I have it working (if I understand the setup correctly) with Remote-Containers. The screenshot in https://github.com/microsoft/vscode-remote-release/issues/1830#issuecomment-553690575 shows many reconnections happening, maybe something is going on with the remote connection?

**Comment by sean-mcmanus** [comment] 2019-11-18 21:34
Maybe Lennon's repro is different, but for our C/C++ scenario, I'm using the Remote WSL extension, and "Launch Extension" with https://github.com/microsoft/vscode-cpptools/tree/release and it ends up not running the "debug" version of the extension, i.e. the debugger says "Breakpoint set but not yet bound". No one else on our team knows how to get it to work (if it's possible).

**Comment by Lennon925** [comment] 2019-11-19 01:04
> Maybe Lennon's repro is different, but for our C/C++ scenario, I'm using the Remote WSL extension, and "Launch Extension" with https://github.com/microsoft/vscode-cpptools/tree/release and it ends up not running the "debug" version of the extension, i.e. the debugger says "Breakpoint set but not yet bound". No one else on our team knows how to get it to work (if it's possible). Doing Remote-WSL: Reopening Folder in Windows (i.e. not WSL) fixes it and debugging is possible like normal.

I am using remote-ssh and behavior is same with you.

**Comment by Lennon925** [comment] 2019-11-19 01:11
> No, I have it working (if I understand the setup correctly) with Remote-Containers. The screenshot in [#1830 (comment)](https://github.com/microsoft/vscode-remote-release/issues/1830#issuecomment-553690575) shows many reconnections happening, maybe something is going on with the remote connection?

I am using remote-ssh instead of remote-container.

**Comment by Lennon925** [comment] 2019-12-03 07:07
@chrmarti @weinand Any update ?

**Comment by renerchen** [comment] 2019-12-03 07:46
### Hi all, I have the same problem, when I activate one extension on the remote host with remote ssh,  the extension fail to run. Remote-connection starts again and again! The logs is following:

**workbench.desktop.main.js:sourcemap:250 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
t.log @ workbench.desktop.main.js:sourcemap:250
workbench.desktop.main.js:sourcemap:250 [Extension Host] (node:24952) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.desktop.main.js:sourcemap:250
workbench.desktop.main.js:sourcemap:250 [Extension Host] (node:24952) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.desktop.main.js:sourcemap:250
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
workbench.desktop.main.js:sourcemap:250 [Extension Host] Extension "nextcode-Reference" start to active!
workbench.desktop.main.js:sourcemap:250 [Extension Host] (node:95488) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
t.log @ workbench.desktop.main.js:sourcemap:250
workbench.desktop.main.js:sourcemap:250 [Extension Host] (node:24952) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
t.log @ workbench.desktop.main.js:sourcemap:250
workbench.desktop.main.js:sourcemap:250 [Extension Host] (node:24952) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
t.log @ workbench.desktop.main.js:sourcemap:250
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] waiting for 5 seconds before reconnecting...
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] resolving connection...
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] connecting to 127.0.0.1:60400...
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] reconnected!
workbench.desktop.main.js:sourcemap:1541   ERR write ECONNRESET: Error: write ECONNRESET
	at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] waiting for 5 seconds before reconnecting...
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] resolving connection...
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] connecting to 127.0.0.1:60400...
workbench.desktop.main.js:sourcemap:1541   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] reconnected!
workbench.desktop.main.js:sourcemap:3695 Extension Host
workbench.desktop.main.js:sourcemap:3695 Debugger attached.
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] waiting for 5 seconds before reconnecting...
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] resolving connection...
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] connecting to 127.0.0.1:60400...
workbench.desktop.main.js:sourcemap:1541   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
workbench.desktop.main.js:sourcemap:1541  INFO [remote-connection][ExtensionHost][4d7b2…][reconnect] reconnected!**

**Comment by Lennon925** [comment] 2019-12-04 07:36
@weinand can you reproduce this issue and any update about this?

**Comment by weinand** [comment] 2019-12-05 15:44
No, I cannot reproduce the issue (but I do not really understand your setup).

I suggest that we first try to get the "hello world" extension working.

Are you able to debug the "hello world" extension locally on Windows? E.g. setting breakpoints in line 11 and 20 and then hitting them when executing the "hello" action via F1?

**Comment by Lennon925** [comment] 2019-12-13 06:09
> No, I cannot reproduce the issue (but I do not really understand your setup).
> 
> I suggest that we first try to get the "hello world" extension working.
> 
> Are you able to debug the "hello world" extension locally on Windows? E.g. setting breakpoints in line 11 and 20 and then hitting them when executing the "hello" action via F1?

In a word, I am able to deubg the "hello world" extenison locally on Windows but I can't when I use remote-ssh. Is it clear?

**Comment by sean-mcmanus** [comment] 2020-09-25 16:55
I don't repro this issue now.

**Comment by weinand** [comment] 2020-11-06 09:33
Closing since @sean-mcmanus and me are not able to reproduce this.

**Closed by weinand** 2020-11-06 09:33 UTC
Labels: debug, needs-more-info
