### ISSUE TITLE
Locked files preventing other build systems from access

### ISSUE THREAD

**Issue by SandSnip3r** [microsoft/vscode-remote-release#877] opened 2019-07-01 20:50 UTC
My environment is Windows 10, WSL, VSCode 1.35, and Visual Studio 2017
My general workflow is to launch vscode from wsl bash, write my code in vscode, then compile with visual studio.
The problem is that the remote development plugin for vscode locks the files and visual studio cant modify the locked files. The compiled object files cannot be overwritten because they're locked.

**Comment by roblourens** [comment] 2019-07-05 21:14
This sounds like an issue with some extension you are using. Maybe the C# or C++ extensions

**Comment by definelicht** [comment] 2019-07-10 18:22
I have the same issue. I disabled all other extensions, and it persisted. Ultimately, the problem is with the Remote WSL extension. Whenever I modify and save a remote file, VSCode seems to lock all build-related files in the directory, such that I cannot access any files from a different application (cmd in my case), until I close the workspace in VSCode.

Is there a way to avoid this issue? I'm currently unable to use Remote WSL because of this.
If this is not the correct place, could you advise where we should direct this issue?

**Comment by SandSnip3r** [comment] 2019-07-10 18:26
I think it's narrow to instantly assume it's another plugin's fault. It seems to make sense that a remote development plugin would lock a file for editing which results in the issue that we're having.

@definelicht I also uninstalled Remote WSL because of this.

**Comment by definelicht** [comment] 2019-07-10 20:25
Maybe amend the title, since this is not Visual Studio specific. Rather, locking the files causes a conflict with any external build system.

**Comment by aeschli** [comment] 2019-07-11 08:20
Maybe that's related to the WSL issue that file watcher lock folders?

There's a new setting in WSL: `remote.WSL.fileWatcher.polling`.
Can you try if that fixes the issue?

See
https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace

**Comment by dopry** [comment] 2019-09-17 14:24
remote.WSL.fileWatcher.polling has resolved https://github.com/microsoft/vscode-remote-release/issues/362 for me.

**Comment by Mordef** [comment] 2019-10-11 06:05
"remote.WSL.fileWatcher.polling": true,
Did not work for me, must quit VS-Code, rename in wsl-shell and restart VS-Code
Version: 1.39.1 (system setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Datum: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.18362
WSL: 0.39.9

WSL1 with Ubuntu 18.04

**Comment by aleksijohansson** [comment] 2019-12-06 16:15
I have this same issue and `remote.WSL.fileWatcher.polling` seems to have fixed it for me!

**Comment by aeschli** [comment] 2019-12-09 07:23
yes, pretty sure this is related to the https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace

Closing as dup.

**Closed by aeschli** 2019-12-09 07:23 UTC
Labels: wsl
