### ISSUE TITLE
There's no run or debug option to debug app in container

### ISSUE THREAD

**Issue by ryan-efendy** [microsoft/vscode-remote-release#5794] opened 2021-10-27 22:45 UTC
Issue Type: <b>Bug</b>

Open Remote - Containers
Select Try a Development Container Sample
Select Node
Navigate to "Run and Debug" and is empty

Extension version: 0.203.0
VS Code version: Code - Insiders 1.62.0-insider (0f7f6e338a4e86306474d4d01bdea9b8fe798017, 2021-10-27T05:15:08.811Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No
Remote OS version: Linux arm64 5.10.47-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id f1bfd64f-cc52-4aa7-9bd5-ab82475bf95f --crash-reporter-id f1bfd64f-cc52-4aa7-9bd5-ab82475bf95f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js|
|OS|Linux arm64 5.10.47-linuxkit|
|CPUs|unknown (4 x 0)|
|Memory (System)|1.93GB (0.06GB free)|
|VM|0%|
</details>

**Comment by ryan-efendy** [comment] 2021-11-02 18:19
Any update on this @chrmarti @weinand?

**Comment by Cecilia-Sensalari** [comment] 2021-11-03 12:23
Hi, I have the same problem when opening VSC in remote through SSH. Killing the processes and deleting `.vscode-server` did not solve the issue.

**Comment by weinand** [comment] 2021-11-03 13:44
I'm investigating...

**Comment by weinand** [comment] 2021-11-04 15:42
The empty "Run and Debug" is an indication that no debugger extension is available in the dev container. Since VS Code comes with the built-in debugger "js-debug", this situation should not really occur...
Could it be that your "js-debug" is disabled?
Please open the Extensions viewlet and enter "js-debug" in the filter box.
A grayed-out JavaScript Debugger is disabled. Please enable it...

<img width="1047" alt="2021-11-04_16-40-02" src="https://user-images.githubusercontent.com/1898161/140364870-26574199-4883-4075-8a2e-e1e4ba3f6149.png">

**Comment by Cecilia-Sensalari** [comment] 2021-11-04 16:00
Hi,
Thanks a lot for looking into this!
The extension is already enabled:
![image](https://user-images.githubusercontent.com/57489957/140373851-977deb9f-c83c-4f44-bfe9-d46d4032d32d.png)
I discovered that my VS code is not detecting an interpreter (in my case Python), could it be that this is causing problems in setting up the debug interface?

**Comment by weinand** [comment] 2021-11-04 16:13
@Cecilia-Sensalari I don't think so. VS Code does not know anything about interpreters. So a missing Python interpreter is not detected by VS Code. Only the Python extension would be able to detect this... 

But is the Python extension(s) correctly enabled in the dev container?
They should show up in the "DEV CONTAINER ... INSTALLED" section:

<img width="525" alt="2021-11-04_17-10-40" src="https://user-images.githubusercontent.com/1898161/140376694-3cc1b592-d896-4834-97af-7e0ae0ade7d6.png">

**Comment by ryan-efendy** [comment] 2021-11-05 02:45
Thanks @weinand yea in my case I had disabled the built-in debugger "js-debug" and instead installed below:

![image](https://user-images.githubusercontent.com/12979345/140449631-888f6596-65ce-4e73-9605-39a1e3c2c15a.png)

**Comment by weinand** [comment] 2021-11-09 17:19
My analysis:
If **js-debug** is disabled locally (because **js-debug-nightly** has been installed), opening the workspace remotely (e.g. in a Docker container) will not automatically install js-debug-nightly in the remote. As a consequence, no enabled debug extension will be available which results in the situation described in this issue.

I see two options for addressing this:
- js-debug-nightly will be installed automatically in the remote to faithfully mimic the behavior of the built-in js-debug.
- js-debug-nightly is not automatically installed but we try to make clear what the problem is by showing this message in the "Run and Debug" viewlet:
  <img width="440" alt="2021-11-09_18-15-19" src="https://user-images.githubusercontent.com/1898161/140972333-3f169aed-99ff-487b-8b51-6b3795a7c424.png">
  (this option has already been implemented in the latest Insiders)

@connor4312 @roblourens @sandy081 opinions?

**Comment by sandy081** [comment] 2021-11-11 09:15
> If js-debug is disabled locally (because js-debug-nightly has been installed), 

This is because js-debug and js-debug-nightly are two different extensions mainly to have insiders support for the extension. We are planning to support insiders extension in VS Code through one extension. I am assuming this might fixes it. But, there is a catch here that js-debug is a built-in extension and we do not support updating built in extensions and we have to think how to support this. 

CC @isidorn

**Comment by isidorn** [comment] 2021-11-11 15:48
After discussing with @sandy081 we have decided that enabling built-in extensions to on-board to the [insiders extension story](https://github.com/microsoft/vscode/issues/15756) will only be possible once we start supporting updating built-in extensions out of band.
Here's an issue tracking this https://github.com/microsoft/vscode/issues/68410

**Closed** 2021-11-19 12:31 UTC
Labels: needs more info, debug
