### ISSUE TITLE
remote ssh stuck in loop trying to connect with vscode 1.69

### ISSUE THREAD

**Issue by ltalirz** [microsoft/vscode-remote-release#6945] opened 2022-07-14 08:14 UTC
I am using the remote SSH extension to connect from WSL2 under Windows 11 to a Ubuntu 20.04 VM.
I am using [this setup](https://stackoverflow.com/a/66048792/1069467) in order to use my SSH config from WSL2.

My setup was working fine with VSCode 1.68.1
After receiving the upgrade to VSCode 1.69.1, I was no longer able to connect to the remote host. The remote ssh extension would fail to install the server on the remote host and continue retrying in an infinite loop.
I remember the logs containing the suggestion to try `"remote.SSH.useFlock": true`. I tried but it did not change anything.

Downgrading my local installation from VSCode 1.69.1 back to 1.68.1 solved the issue.

- VSCode Version: 1.69.1
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH  (I am on the pre-release version `v0.85.2022071315
` of `Remote - SSH`, but I also tried downgrading to the release version and it did not help)
- Logs:

Unfortunately I did not keep a copy of the logs; I can go back to 1.69.1 and provide them if someone thinks it is worth looking into this issue.

Until then, I hope the workaround to [downgrade vscode](https://stackoverflow.com/a/49347158/1069467) helps if someone else experiences the issue.

**Comment by dlaliberte** [comment] 2022-07-14 16:49
I don't know if my problem is related (I am using 1.69, and my remote connection suddenly started failing with an empty "Workspace Trust" tab) but previous issues about "Opening Remote...' being stuck  are marked as closed and locked, so I can't add my "me too" there.  

I got it working again by renaming my remote folder, which triggered the connection process to get unstuck and ask me for the name of the remote folder.

**Comment by eleanorjboyd** [comment] 2022-12-09 22:18
Hello! My name is Eleanor and I am the new maintainer for the Remote-SSH extension. Are you still experiencing this issue? Thanks

**Comment by dlaliberte** [comment] 2022-12-10 01:28
I have seen the problem I reported a couple more times, and I was successful working around it the same way. That was a few months ago, and I haven't seen the problem since then.

**Comment by eleanorjboyd** [comment] 2022-12-12 15:35
Thank you for the update and I am sorry the issue re-appeared in your workflow. I am glad it is no longer persisting so I am going to close this issue, but feel free to re-open it if this problem emerges again. Thanks!

**Closed by eleanorjboyd** 2022-12-12 15:35 UTC
Labels: ssh, info-needed

**Comment by maayanorner** [comment] 2023-01-25 11:50
Hi Eleanor - unfortunately, it still happens consistently.
To reproduce, try to connect the server, work a little and kill the connection unexpectedly. The fix is to log in to the server and delete some files in .vscode-server, which makes it quite likely it's a bug IMHO.

**Comment by maayanorner** [comment] 2023-01-25 13:49
Hi Eleanor - unfortunately, it still happens consistently.
To reproduce, try to connect the server, work a little and kill the connection unexpectedly. The fix is to log in to the server and delete some files in .vscode-server (or sometimes kill the server), which makes it quite likely it's a bug IMHO (but of course, it's too complicated to really know without getting into the code).

**Comment by eleanorjboyd** [comment] 2023-02-01 16:54
Hello! Is this happening with the latest version of the extension and vscode? How do you kill the connection? Can you include logs from your reconnection attempt that does not work?

**Comment by eleanorjboyd** [comment] 2023-03-06 16:18
closing as the original author has no longer seen this issue (commented [here](https://github.com/microsoft/vscode-remote-release/issues/8144)) - please open a new issue if you are seeing this problem. Thanks!
