### ISSUE TITLE
SSH Remote not reading hosts in include files

### ISSUE THREAD

**Issue by jlcampuzano** [microsoft/vscode-remote-release#749] opened 2019-06-20 21:06 UTC
- VSCode Version: 1.35.1 
- Local OS Version: macOS 10.14.5 (18F132)
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Have ssh config file where the host definitions are in include filles instead of the /~/.ssh/config. with the syntax

Include foobar
Include directory/foobar

[From 7.3p1 and up, there is the Include keyword, which allows you to include configuration files."

Include
        Include the specified configuration file(s).  Multiple pathnames may be specified and each pathname may contain glob(3) wildcards and, for user configurations, shell-like “~” references to user home directories.  Files without absolute paths are assumed to be in ~/.ssh if included in a user configuration file or /etc/ssh if included from the system configuration file.  Include directive may appear inside a Match or Host block to perform conditional inclusion.

Source: ssh_config(5).](https://superuser.com/questions/247564/is-there-a-way-for-one-ssh-config-file-to-include-another-one)

2. When the hosts are on this includes the extension does not parse the hosts

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by ryansully** [comment] 2019-06-21 02:00
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/65?

**Comment by egamma** [comment] 2019-06-21 08:16
Closing as a duplicate of #65 (thanks @ryansully)

**Closed by egamma** 2019-06-21 08:16 UTC
