### ISSUE TITLE
Using `code -r` terminal command with multiple VS Code Remote SSH sessions reopens ALL sessions on a targeted folder

### ISSUE THREAD

**Issue by maciejmatczak** [microsoft/vscode-remote-release#4984] opened 2021-04-29 14:49 UTC
- VSCode Version: 1.55.2
- Local OS Version: Windows 10 1909
- Remote OS Version: CentOS 7.3
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

We need an ssh target and 3 folders.

1. Start menu -> VS Code (session A) - open FOLDER1 on an ssh target
2. Start menu -> VS Code (session B) - open FOLDER2 on an ssh target
3. In a session B's terminal use command: `code -r FOLDER3`
4. Both, session A and session B gets reloaded on FOLDER3

I am hitting it very often, using multiple sessions and terminal's `code -r`. Remote terminal is very handy to navigate through the file system, hence I tend to use it when _recent_ list gets overcrowded.

Does this issue occur when you try this locally?: NA
Does this issue occur when you try this locally and all extensions are disabled?: NA

**Comment by aeschli** [comment] 2021-05-06 09:00
duplicate of https://github.com/microsoft/vscode/issues/121926

**Closed** 2021-05-31 21:26 UTC
