### ISSUE TITLE
Use host git and ssh configuration and credentials

### ISSUE THREAD

**Issue by guylevin** [microsoft/vscode-remote-release#2534] opened 2020-03-12 17:48 UTC
When using the remote development container, you can't pull or push to git from the terminal, or from the vscode UI, because the container is not using the host ssh key

I tried to share the key as a volume (~/.ssh) , but on windows it is a problem because you get the wrong file permissions 

```
"mounts": [
"source=${localEnv:HOME}${localEnv:USERPROFILE}/.ssh/,target=/root/.ssh/,type=bind,consistency=cached"
]
```

I suggest that 
* VSCode should use the host environment to access the source control
* There should also be a terminal window to the host environment

**Comment by bhack** [comment] 2020-03-16 13:46
Is this for the Key or for  nussubg`known_hosts`? See https://github.com/microsoft/vscode-remote-release/issues/2285

**Comment by guylevin** [comment] 2020-03-16 14:23
It is the key, so you'll be able to connect to git from vscode

**Comment by bhack** [comment] 2020-03-16 14:27
So is this a duplicate of https://github.com/microsoft/vscode-remote-release/issues/2398?

**Comment by roblourens** [comment] 2020-03-16 22:06
@guylevin Do you have ForwardAgent set? Is the local OS windows? If so, https://github.com/microsoft/vscode-remote-release/issues/2398

**Comment by bhack** [comment] 2020-03-16 22:11
Check https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent

**Comment by guylevin** [comment] 2020-03-16 23:03
> @guylevin Do you have ForwardAgent set? Is the local OS windows? If so, #2398

The local os is windows

How do you set up ForwardAgent on remote development containers extension?

**Comment by guylevin** [comment] 2020-03-16 23:07
> Check https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent

Thanks @bhack 
I'm not sure how this relate

**Comment by guylevin** [comment] 2020-03-16 23:08
> So is this a duplicate of #2398?

It is probably a related situation 
I can see it's unresolved

**Comment by bhack** [comment] 2020-03-16 23:11
The link Is to setup the forward agent

**Comment by roblourens** [comment] 2020-03-16 23:16
Closing as a dupe of #2398 for now

**Closed by roblourens** 2020-03-16 23:16 UTC
Labels: needs-more-info

**Comment by guylevin** [comment] 2020-03-18 21:57
Thanks @bhack the forward agent is doing what I wanted
https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent

I added to ~/.ssh/config
Host *
  ForwardAgent yes

I still have 2 questions
1. Setting host * is not really safe, is there a better idea to support all vscode remote containers, without setting each separately ?
2. Is it possible to do the same with known hosts?

**Comment by bhack** [comment] 2020-03-18 22:08
I don't know why you need `*`. For 2. See https://github.com/microsoft/vscode-remote-release/issues/2285

**Comment by guylevin** [comment] 2020-03-18 22:11
What host to write then? If I want the key to be forwarded to all vscode dev containers automatically

**Comment by bhack** [comment] 2020-03-18 22:22
It could automatically work trought socket (pipe) also on Windows. See https://github.com/microsoft/vscode-remote-release/issues/106#issuecomment-558494074

**Comment by guylevin** [comment] 2020-03-18 22:41
On Linux it seems to forward the key without doing anything as mentioned on[ the link you sent](https://github.com/microsoft/vscode-remote-release/issues/106#issuecomment-558494074)


I'll try the same on windows

**Comment by Chuxel** [comment] 2020-03-19 00:09
See https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container

Windows does not have the SSH agent running by default in the OS.  Linux may or may not.  macOS does.

If you really want to mount the .ssh folder on windows, you have to mount it to an alternate location, copy everything to the right location and modify the permissions.  This is why we switched to the SSH agent as the guidance.
