### ISSUE TITLE
Open Folder in Container in Remote-SSH(nested open)

### ISSUE THREAD

**Issue by hikaruna** [microsoft/vscode-remote-release#1707] opened 2019-10-23 07:10 UTC
I set up a remote SSH server. On that remote server, we are building a development environment using Docker.

I want to connect to the development dockerContainer on the remote server after connecting to my remote server.

Currently, vscode seems to be impossible to open remote-container after SSH connection.
I hope this will be possible and will allow multiple connections.

---

SSH-forwarding docker.sock on the remote machine and specifying it as DOCKER_HOST on the local machine does not meet my needs. This is because the volume system of the remote machine file system cannot be mounted.

**Comment by Chuxel** [comment] 2019-10-24 18:16
@hikaruna FYI - You can use a named volume or override the source code mount path as described here: https://aka.ms/vscode-remote/containers/remote-host.

Otherwise this is a dupe of #20.

**Closed by Chuxel** 2019-10-24 18:16 UTC
