### ISSUE TITLE
vscode-server uses  ~100% of my server's CPU

### ISSUE THREAD

**Issue by vlad-iancu** [microsoft/vscode-remote-release#4466] opened 2021-02-13 20:44 UTC
- VSCode Version: 1.53.2 x64
- Local OS Version: Ubuntu 20.04.02 LTS 64-bit
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.Connect to a remote server via the Remote SSH extension

My server is simply lagging because of the vscode-server binary that is running.
How I found out that this is the source of the problem and not something else:
1.I used  the command provided here: https://unix.stackexchange.com/a/22244 to find out the most CPU consuming processes.
2.after I killed the vscode-server I noticed that the spike in resources have gone down for my server
![image](https://user-images.githubusercontent.com/73757768/107861185-c533ac80-6e4c-11eb-90ca-3a461fd713db.png)

**Comment by justin-augusto** [comment] 2021-02-13 22:24
I recently (in the last week) started experiencing this as well on Ubuntu 20.04.2 (not 20.04.02) LTS 64-bit.

**Comment by bamurtaugh** [comment] 2021-02-26 01:29
Thanks for reporting @vlad-iancu @justin-augusto. Since it looks like this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/4348, I'm going to close this issue, but please feel free to let me know if I've missed anything, and I'd be happy to reopen/discuss further.

**Closed by bamurtaugh** 2021-02-26 01:29 UTC
Labels: ssh
