### ISSUE TITLE
Wrong title in marketplace? XD

### ISSUE THREAD

**Issue by JasonBenfrin** [microsoft/vscode-remote-release#7264] opened 2022-09-28 17:12 UTC
- VSCode Version: 1.71.2
- Local OS Version: Ubuntu 22.04.1

Steps to Reproduce:

1. Search for [object Object] in marketplace

![[object Object]](https://i.imgur.com/FtcH6Tq.png)

![object Object in Web](https://i.imgur.com/PzzNKep.png)

**Comment by joshsleeper** [comment] 2022-09-28 18:40
dupe of #7262 btw~

**Comment by chrmarti** [comment] 2022-09-29 06:59
Closing as duplicate. Thanks.

**Closed by chrmarti** 2022-09-29 06:59 UTC
