### ISSUE TITLE
Some icons are not being displayed in VS Code Remote

### ISSUE THREAD

**Issue by shopskyi** [microsoft/vscode-remote-release#966] opened 2019-07-11 09:53 UTC
Issue Type: <b>Bug</b>

The following icons are not being displayed in VS Code Remote
- "Stage"  "Unstage" changes icons (on "Source Control" panel) 
-  the icons of the installed extensions (on the Side Bar)

![image](https://user-images.githubusercontent.com/28783686/61041215-a6e90d80-a3da-11e9-9e00-01e39a1ee7c4.png)

The icons works but not visible

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
cisco|jam|1.6.1
vscode-docker|ms-|0.7.0
remote-wsl|ms-|0.38.9
vscode-icons|vsc|8.8.0
vscode-todo-highlight|way|1.0.4
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
project-manager|ale|10.5.2
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.8.5
terraform|mau|1.3.12
vscode-azureterraform|ms-|0.2.4
vscode-aks-tools|ms-|0.0.1
vscode-kubernetes-tools|ms-|1.0.1
python|ms-|2019.6.24221
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
powershell|ms-|2019.5.0
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.17
vscode-helm|tec|0.4.0
vscode-ansible|vsc|0.5.2
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by SwimmingTiger** [comment] 2019-07-16 07:53
Same issue.

The developer tool shows the URL in these missing icons have an unsupported scheme.

<img width="1064" alt="vscode缺失按钮" src="https://user-images.githubusercontent.com/4986069/61275877-6e35a380-a7e1-11e9-9b98-b7864450fd99.png">

**Comment by kinglionsz** [comment] 2019-07-19 15:00
I'm a bit confused about the screenshot.
What you show is output in the 'Output View,' correct?
You have a WSL window open?
Looks like the messages come from the main which fails to load some image.
Duplicate of microsoft/vscode-remote-release#966

**yes
1,run wsl.exe
2,in the wsl windows, run code-insiders
and now , vs code is opening and the wsl windows output :**

ubuntu@DESKTOP-J925CM6:/mnt/c/WINDOWS/system32$ code-insiders
[main 2019-07-19T14:44:28.712Z] update#setState idle
[main 2019-07-19T14:44:42.319Z] Received resolved authority wsl+Ubuntu-18.04
[main 2019-07-19T14:44:45.947Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.947Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.948Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.948Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.949Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.950Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:58.715Z] update#setState checking for updates
[main 2019-07-19T14:44:58.989Z] update#setState idle
while vs code closed, the wsl windows stop output.
the Issue appears after I update vs code. it is ok before update.
@aeschli

**Comment by kinglionsz** [comment] 2019-07-19 15:01
I'm a bit confused about the screenshot.
What you show is output in the 'Output View,' correct?
You have a WSL window open?
Looks like the messages come from the main which fails to load some image.
Duplicate of #966

**yes
1,run wsl.exe
2,in the wsl windows, run code-insiders
and now , vs code is opening and the wsl windows output :**

ubuntu@DESKTOP-J925CM6:/mnt/c/WINDOWS/system32$ code-insiders
[main 2019-07-19T14:44:28.712Z] update#setState idle
[main 2019-07-19T14:44:42.319Z] Received resolved authority wsl+Ubuntu-18.04
[main 2019-07-19T14:44:45.947Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.947Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.948Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.948Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.949Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.950Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:58.715Z] update#setState checking for updates
[main 2019-07-19T14:44:58.989Z] update#setState idle
**while vs code closed, the wsl windows stop output.
the Issue appears after I update vs code. it is ok before update.**
@aeschli

**Comment by alexandrudima** [comment] 2019-07-22 08:38
I think we have to remove the connection from the main process and fetch the resources from the renderer process...

**Closed** 2019-07-24 15:36 UTC
Labels: *duplicate, bug

**Comment by ShailenNaidoo** [comment] 2019-08-11 08:42
I just updated my VS Code to 1.37.0 and tried VS Code remote and tried to install the extensions that I commonly use but the icons are not visible but the extensions are usable.

I have [Gitlens](https://github.com/eamodio/vscode-gitlens.git) installed but the icon does not show but I can still use it:

![image](https://user-images.githubusercontent.com/26552540/62831780-8358f300-bc24-11e9-911e-a06869ce33c2.png)

This happens for every non-standard VS Code extension
