### ISSUE TITLE
Remote SSH and WSL

### ISSUE THREAD

**Issue by dereklstinson** [microsoft/vscode-remote-release#1850] opened 2019-11-14 19:24 UTC
Remote explorer doesn't show all of the options.  I have to refresh vscode to show the other options. Right now I am trying to get into ssh, but it is stuck on wsl.

Extension version: 0.47.2
VS Code version: Code - Insiders 1.41.0-insider (eccf417b72fc0a632ec2cbd7855a681cdb8c81fa, 2019-11-14T09:50:04.822Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-66-generic
Remote OS version: Linux x64 4.15.0-66-generic
Remote OS version: Linux x64 4.4.0-17763-Microsoft
Remote OS version: Linux x64 4.15.0-66-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (17.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: Z9PE-D16|
|OS|Linux x64 4.15.0-66-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (40 x 1200)|
|Memory (System)|62.86GB (57.22GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Z9PE-D16|
|OS|Linux x64 4.15.0-66-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (40 x 1200)|
|Memory (System)|62.86GB (57.22GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|31.94GB (17.08GB free)|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: Z9PE-D16|
|OS|Linux x64 4.15.0-66-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (40 x 1200)|
|Memory (System)|62.86GB (57.22GB free)|
|VM|0%|
</details>
aste.

**Comment by egamma** [comment] 2019-11-19 11:53
/needsMoreInfo 

>Remote explorer doesn't show all of the options. I have to refresh vscode to show the other options. Right now I am trying to get into ssh, but it is stuck on wsl.

@dereklstinson can you provide a screen shot of what you are seeing.

**Comment by alexr00** [comment] 2019-11-19 14:51
Very likely a duplicate of https://github.com/microsoft/vscode-remote-release/issues/1847
If you update to a newer insiders the issue should be fixed! Please do ping this issue again with a screen shot if updating doesn't solve it!

**Closed by alexr00** 2019-11-19 14:51 UTC
Labels: needs more info
