### ISSUE TITLE
support multiple config files

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-remote-release#5473] opened 2021-08-18 08:52 UTC
I have several ssh config files. It would be nice to configure once all of them.

**Comment by akosyakov** [comment] 2021-08-19 10:34
It is kind of the same like include directive in the ssh config file which is broken right now because of https://github.com/microsoft/vscode-remote-release/issues/5449

**Comment by roblourens** [comment] 2021-10-19 22:53
We should do this with normal ssh configs, closing as dupe of #5449

**Closed by roblourens** 2021-10-19 22:53 UTC
Labels: ssh, feature-request
