### ISSUE TITLE
404 when installing vscode server on remote

### ISSUE THREAD

**Issue by jeffliu-LL** [microsoft/vscode-remote-release#6831] opened 2022-06-15 14:01 UTC
- VSCode Version: 1.68.0
- Local OS Version: Windows 10 21H2 build 19044.1706
- Remote OS Version: Ubuntu 18.04.6 LTS
- Remote Extension/Connection Type: SSH
- Logs:
```
update.code.visualstudio.com/commit%3A4af164ea3a06f701fe3e89a2bcbb421d2026b68f/server-linux-x64/stable:1          Failed to load resource: the server responded with a status of 404 (Not Found)
log.ts:313   ERR resolveAuthority(ssh-remote) returned an error after 9719 ms Error: Server returned 404
    at v (request.ts:42:9)
    at k.download (downloadService.ts:33:26)
log.ts:313   ERR Error received from starting extension host (kind: Remote)
log.ts:313   ERR Error: Server returned 404
    at v (request.ts:42:9)
    at k.download (downloadService.ts:33:26)
log.ts:313   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
3log.ts:313   ERR Error: Server returned 404
    at v (request.ts:42:9)
    at k.download (downloadService.ts:33:26)
log.ts:313   ERR Cannot register remote filesystem provider. Error while fetching remote environment. Server returned 404
notificationsAlerts.ts:42 Failed to connect to the remote extension host server (Error: Server returned 404)
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:313   ERR Error: Server returned 404
    at v (request.ts:42:9)
    at k.download (downloadService.ts:33:26)
log.ts:313   ERR Server returned 404: Error: Server returned 404
    at v (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:622:38476)
    at k.download (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:1592)
log.ts:313   ERR Error: Server returned 404
    at v (request.ts:42:9)
    at k.download (downloadService.ts:33:26)
log.ts:307  WARN Shell integration failed to add capabilities within 10 seconds
log.ts:313   ERR Server returned 404: Error: Server returned 404
    at v (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:622:38476)
    at k.download (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:1592)
10log.ts:313   ERR Server returned 404: Error: Server returned 404
    at v (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:622:38476)
    at k.download (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:1592)
```

Steps to Reproduce:

1. Update to 1.68.0 of vscode
2. Connect to remote via ssh - tries to update via wget and fails; tries to download locally and scp to remote and fails

This seems to be a duplicate of https://github.com/microsoft/vscode/issues/147324 and #6607, but those were closed saying that it was a temporary failure. The URL that fails is https://update.code.visualstudio.com/commit%3A4af164ea3a06f701fe3e89a2bcbb421d2026b68f/server-linux-x64/stable which has the same `%3A` vs `:` encoding issue as the previous issues.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by jeffliu-LL** [comment] 2022-06-15 14:14
I was able to work around it by locally downloading the package from https://update.code.visualstudio.com/commit:4af164ea3a06f701fe3e89a2bcbb421d2026b68f/server-linux-x64/stable, copying it to the remote server and untarring into `~/.vscode_server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f`

**Comment by tanhakabir** [comment] 2022-06-15 17:55
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6804

You can try using VS Code Insiders for now as a workaround!

**Closed by tanhakabir** 2022-06-15 17:55 UTC
Labels: ssh
