### ISSUE TITLE
code-insiders command no longer works in containers, breaks git credential handler

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#490] opened 2019-05-28 20:33 UTC
I initially discovered this because the forwarded git credential manager didn't appear to be working, but I realized this is broader. It appears to have hit in 0.54 or the most recent VS Code Insiders update.

Repro is simple:
1. Open a folder in a container
2. Go to a terminal, type `code-insiders ~` or some other file

Expected: File / folder opens
Actual: Errors with both code-insiders or code:
```
root@036652fe0531:/workspaces/vscode-remote-try-node# code-insiders ~/.gitconfig 
bash: code-insiders: command not found
root@036652fe0531:/workspaces/vscode-remote-try-node# code ~/.gitconfig
bash: code: command not found
root@036652fe0531:/workspaces/vscode-remote-try-node# 
```

There also is an error that appears in the startup log that I think is git credential management forwarding failing:

```
==> Received an extension host connection.
==> Using UI language: en
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
mesg: ttyname failed: Inappropriate ioctl for device
==> Received a management connection
==> Received a management connection
```

If you open up the Git output window after pushing, you'll see things like this indicating it's not in place:
```
> git push origin master:master
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
Everything up-to-date
```
//cc: @chrmarti

**Comment by chrmarti** [comment] 2019-05-29 06:27
@roblourens I think this might be caused by https://github.com/microsoft/vscode-distro/commit/f1b3a1410f60f9fb123b1b8d2b27af9137009783 overwriting the `PATH` I set when launching the agent. /cc @aeschli

**Comment by roblourens** [comment] 2019-05-29 23:21
This should be fixed by the PR righ?

**Comment by chrmarti** [comment] 2019-05-31 06:44
Yes. Closing for verification.

Verifiers: Please verify that Stable has `code` and Insiders has `code-insiders` on the PATH of the remote terminal.

**Closed by chrmarti** 2019-05-31 06:44 UTC
Labels: bug, containers, important

**Comment by alexr00** [comment] 2019-05-31 09:08
Verified with insiders. Stable still needs to be verified.

**Comment by jrieken** [comment] 2019-06-03 10:39
Verified with Stable
