### ISSUE TITLE
asWebviewUri: UriError - the path cannot begin with two slash characters

### ISSUE THREAD

**Issue by benc-uk** [microsoft/vscode-remote-release#1643] opened 2019-10-10 14:59 UTC
- VSCode Version: 1.39
- Local OS Version: Windows 10 Insiders 18995
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: WSL and SSH

Steps to Reproduce:

1. Use v0.3.1 of my extension https://marketplace.visualstudio.com/items?itemName=bencoleman.armview in a WSL or SSH VS Code session
2. None of the resources in the webview are loaded, the extension no longer works.
3. I see error `Unable to read file (Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"))`

I'm using the webview API
`panel.webview.asWebviewUri` to form the URLs of the components my WebView needs to load, e.g.
```
panel.webview.asWebviewUri(vscode.Uri.file(path.join(extensionPath, 'assets', 'css', 'main.css')));
```

I've been developing this extension for several weeks and work exclusively in WSL remote mode. I've never once had an issue until I updated to version 0.39.9 of the WSL extension (with VS Code 1.39).
Problem does NOT happen when working in local mode

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

(Note. I've put a quick fix in the latest version v0.3.2 of my extension, but it's a clumsy hack to load all resources from remote external URL, which isn't a viable solution long term)

**Comment by benc-uk** [comment] 2019-10-11 06:45
Issue also happens in SSH, not just WSL

I've verified this effects all extensions using a webView and loading resources from the extension folder. for example the webview example in the vscode-extension-samples repo
For example https://github.com/microsoft/vscode-extension-samples/issues/219

**Comment by mjbvz** [comment] 2019-10-14 21:24
Duplicate of https://github.com/microsoft/vscode/issues/82336

**Closed by mjbvz** 2019-10-14 21:24 UTC
Labels: remote
