### ISSUE TITLE
exit of vscode remote containter leaves processes with high cpu in container

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#6543] opened 2022-04-01 10:14 UTC
- VSCode Version: 1.66.0
- Local OS Version: Ubuntu 20.04
- Remote OS Version: CentOS 7.6
- Remote Extension/Connection Type:  Docker
- Logs:

Steps to Reproduce:

1. Run vscode remote container
2. exit vscode 

 
Does this issue occur when you try this locally?:  No
Does this issue occur when you try this locally and all extensions are disabled?: No
 

Full cmd line of high cpu process:
```
/root/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /root/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/server-main.js --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --use-host-proxy --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-e18005f0f1b33c29e81d732535d8c0e47cafb0b5 --extensions-download-dir /root/.vscode-server/extensionsCache --start-server --disable-websocket-compression
```
There are 2 such processes, each using one core of CPU to its full. One with 2M/s memory increase, another with 0.2M/s memory usage increase. I only noticed this after today 1.66.0 vscode update. Not sure if it occurred before.

**Comment by zydou** [comment] 2022-04-01 11:26
I got this too.

**Comment by chrmarti** [comment] 2022-04-01 14:35
Also when reloading the window.

@alexdima This seems to be a variation of the broken stdio we looked at:
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/9205389/161284985-8b1656c1-a57e-4d9a-be55-2357ba516f4e.png">

**Comment by chrmarti** [comment] 2022-04-04 13:14
Fixed in Remote-Containers as #6547. It might still make sense to investigate on the server's side.

https://github.com/microsoft/vscode-remote-release/issues/6547#issuecomment-1086922718 mentions something similar with Remote-SSH. (Reproduced only 1 out of 3 times I tried, so maybe it is actually a different issue.) /cc @tanhakabir

**Comment by tanhakabir** [comment] 2022-04-04 15:20
@chrmarti the linked issue looks like an issue with connecting. The error logs comes from OpenSSH and we don't actually get to the VS Code Server yet. But I'll try to reproduce and investigate if something similar to this issue is happening on my end.

**Comment by chrmarti** [comment] 2022-04-04 15:31
@tanhakabir Some guessing on my side: It might be caused by the VS Code Server consuming the CPU when this issue hits. I have seen it consume 100% CPU (but only once) after triggering reconnection by terminating the SSH client. I was still able to connect, but that might depend on how many CPUs the SSH server has available.

**Comment by tanhakabir** [comment] 2022-04-04 17:54
@chrmarti what are the repro steps you're using to repro this issue?

Also do you have a link to track and learn more about this issue? https://github.com/microsoft/vscode-remote-release/issues/6543#issuecomment-1085980778 

I'm also not familiar with `docker exec`. What does it do and how does it fix the issue of the VS Code Server seeming to use too much CPU?

**Comment by alexdima** [comment] 2022-04-04 19:05
> It might still make sense to investigate on the server's side.

@chrmarti What are the repro steps? Just reloading the window again?

**Comment by chrmarti** [comment] 2022-04-05 07:06
@alexdima With Remote-Containers 0.231.2 a window reload triggers the problem.

With Remote-SSH I think once saw it in a reconnection scenario (killing the SSH client locally to trigger reconnection). A window reload did not trigger it.

@tanhakabir `docker exec` is a Docker command to run an arbitrary command in a container. Using that seems to work around the problem for Remote-Containers (previously I was using an existing connection to the container which has lower latency than a separate `docker exec`).

**Comment by thomas-qualia** [comment] 2022-04-05 13:21
The Remote SSH problem is happening to me every day. It just started after one of the recent VS Code updates. It happens consistently after a period of inactivity (like stepping away from my mac for a bit). My fix right now is to cmd+shift+p and 'Remote-SSH: Kill VS Code Server on Host...' and then reopen the workspace.

Let me know if there's any more information that would be helpful that I can gather beyond what I already posted in https://github.com/microsoft/vscode-remote-release/issues/6547#issuecomment-1086922718

**Comment by connor4312** [comment] 2022-04-29 22:32
I don't hit this on Insiders, but also didn't reproduce on stable. Are there additional verification steps needed for this?

**Comment by alexdima** [comment] 2022-05-02 06:59
I think this only reproduces with Remote-Containers 0.231.2 and is visible after doing `top`. @chrmarti Could you please try to verify this?

**Comment by alexdima** [comment] 2022-10-25 07:32
I'll close this one given we have put in place a workaround in the extension. @chrmarti Please reopen if we should continue looking into this.

**Comment by connor4312** [comment] 2022-12-30 20:02
Repro steps: https://github.com/microsoft/vscode/issues/168194#issuecomment-1368056786

**Closed** 2023-01-17 19:26 UTC
Labels: bug, containers, verification-steps-needed

**Comment by TylerLeonhardt** [comment] 2023-01-27 00:41
Verification steps from @connor4312:

Terminal 1: code-insiders tunnel …
[insiders.vscode.dev](http://insiders.vscode.dev/): connect
Terminal 2 (from within [insiders.vscode.dev](http://insiders.vscode.dev/)): pkill -9 -f tunnel
Terminal 1: repeat
[insiders.vscode.dev](http://insiders.vscode.dev/): reload
it shouldn’t fail
