### ISSUE TITLE
Running the WSL terminal as a local WSL terminal

### ISSUE THREAD

**Issue by xsrvmy** [microsoft/vscode-remote-release#5149] opened 2021-06-06 15:56 UTC
Currently the WSL terminal appears to be rendered on the linux side and then sent to VSCode. As a result there is flickering when typing.

Is it possible to add an option to run the WSL terminal as a local terminal instance using WSL.exe?

**Comment by bamurtaugh** [comment] 2021-06-08 00:06
Do you have an example (i.e. gif/video) of the flickering you see when typing?

**Comment by xsrvmy** [comment] 2021-06-08 01:24
I guess flickering is not the right word. However there is definitely a slight delay between the cursor moving right and the character appearing on the screen. The delay is not there if I start a wsl terminal in a local instance of vscode.

**Comment by bamurtaugh** [comment] 2021-06-09 02:17
> The delay is not there if I start a wsl terminal in a local instance of vscode.

To make sure I understand, how are you currently starting your WSL terminal? Are you starting VS Code on Windows, then opening a new WSL terminal? And you just see the delay when using a terminal in Remote-WSL?

**Comment by xsrvmy** [comment] 2021-06-09 02:42
Yeah starting Windows VSCode locally then opening a WSL profile.

**Comment by bamurtaugh** [comment] 2021-06-14 19:44
cc @aeschli for thoughts - I'm not sure if this would be feasible (i.e. details here https://code.visualstudio.com/docs/remote/faq#_what-is-the-advantage-of-the-extension-over-using-wsl-as-the-terminal, communication between extensions, WSL, VS Code server). 

Also, it's not really expected to see a delay when typing in a Remote-WSL instance. If you could provide greater details about your distro, VS Code and Remote-WSL version, if you see a delay typing elsewhere beyond the terminal/doing anything else, and even a gif of what you might be seeing, that'd also be helpful.

**Comment by aeschli** [comment] 2021-06-15 11:53
@Tyriar is the expert here.

**Comment by jasonwilliams** [comment] 2021-07-12 11:19
This issue is the same as https://github.com/microsoft/vscode/issues/100427 it’s been raised before and has affected quite a few of us.

although the issue is in the terminal it seems the delay appears to be happening in the remote extension (see thread). @bamurtaugh I’m not sure whether the issue above should be moved here or kept on VSCode main.

**Comment by bamurtaugh** [comment] 2021-07-12 17:54
Thanks for linking that issue @jasonwilliams! As this is @Tyriar's area and he's assigned to both, happy to default to what he thinks is best, but I think it makes sense to keep that issue https://github.com/microsoft/vscode/issues/100427 with its context/labels/milestone assignment as-is in the VS Code repo, and we can close out this one as a dupe.

**Closed** 2021-10-08 18:50 UTC
Labels: wsl
