### ISSUE TITLE
Infinite Login prompt

### ISSUE THREAD

**Issue by wwangsa** [microsoft/vscode-remote-release#8197] opened 2023-03-14 15:26 UTC
Type: <b>Bug</b>

When login to the remote ssh (RHEL) after VSCode updates applied, it will keep prompting for password and 2FA infinitely. If we cancel it multiple times, we will get locked from the server. The workaround is to ssh to the server using terminal, delete the .vscode-server folder. Once deleted, it will be back to normal. This happens to my coworker as well. We're using macbook on Ventura 13.2.1 and his on 13.1

Extension version: 0.98.0
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
pythonb192cf:30669361
funwalk2:30682974

```

</details>

**Comment by jtegtmeier** [comment] 2023-03-14 20:16
Getting this too (maybe) on VSCode 1.76.0 from Ubuntu local OS (wsl). 

I'm attempting to log in to a remote Debian host with `OpenSSH_8.4p1 Debian-5+deb11u1`, but having an issue with the "Starting forwarding server" step. Strangely, logging into a different remote Ubuntu host with `OpenSSH_8.2p1 Ubuntu-4ubuntu0.5` seems to still be working more often (but I did still see the issue here a couple of times). Same `sshd_config` and `~/.ssh/` files on both.

Having trouble narrowing the issue down.

Remote - SSH reports this error after the initial ssh connection:
```
Failed to set up socket for dynamic port forward to remote port 34995: connect ECONNREFUSED 127.0.0.1:1503. Is the remote port correct?
```

*Note, If I let the login loop long enough (20-40 min) it sometimes does eventually succeed with the "Start Forwarding server" step.*

Same workaround always works, deleting the `.vscode_server` folder on remote host allows consistent login.

**Comment by jtegtmeier** [comment] 2023-03-16 23:23
Duplicate of #8132?

**Comment by jtegtmeier** [comment] 2023-03-17 07:19
In my case, the 2FA was not working well with the `Remote.SSH: Enable Dynamic Forwarding` options. Disabling this allowed me to consistently connect (although I needed to interact with my 2fa more times than I'd like).

**Comment by wwangsa** [comment] 2023-03-17 18:00
I'm afraid we have to wait until the next updates. The `remote-ssh` log doesn't retain past connections

**Comment by jtegtmeier** [comment] 2023-03-17 21:09
Here are my logs if it helps. Hope I'm not hijacking the issue, seems like a similar issue, but may be slightly different than the origianl bug desc. I'll open another issue if my workaround stops working or starts to bug me enough.

Remote - SSH logs:

<details>

<summary>Login success (after removing `.vscode-server` dir or killing the vscode server pid's on remote machine)</summary>


*Note, `C:\Users\WINDOWS_USER\bin\ssh.bat` simply contains a `@wsl ssh %*` command to initiate ssh using wsl.*

```
[13:48:29.325] Log Level: 2
[13:48:29.344] VS Code version: 1.76.2
[13:48:29.345] Remote-SSH version: remote-ssh@0.98.0
[13:48:29.345] win32 x64
[13:48:29.349] SSH Resolver called for "ssh-remote+10.10.10.200", attempt 1
[13:48:29.349] "remote.SSH.useLocalServer": false
[13:48:29.350] "remote.SSH.showLoginTerminal": false
[13:48:29.350] "remote.SSH.remotePlatform": {"10.10.10.200":"linux"}
[13:48:29.350] "remote.SSH.path": C:\Users\WINDOWS_USER\bin\ssh.bat
[13:48:29.350] "remote.SSH.configFile": undefined
[13:48:29.351] "remote.SSH.useFlock": true
[13:48:29.351] "remote.SSH.lockfilesInTmp": false
[13:48:29.351] "remote.SSH.localServerDownload": auto
[13:48:29.351] "remote.SSH.remoteServerListenOnSocket": false
[13:48:29.351] "remote.SSH.showLoginTerminal": false
[13:48:29.352] "remote.SSH.defaultExtensions": []
[13:48:29.352] "remote.SSH.loglevel": 2
[13:48:29.352] "remote.SSH.enableDynamicForwarding": true
[13:48:29.352] "remote.SSH.enableRemoteCommand": false
[13:48:29.352] "remote.SSH.serverPickPortsFromRange": {}
[13:48:29.352] "remote.SSH.serverInstallPath": {}
[13:48:29.361] SSH Resolver called for host: 10.10.10.200
[13:48:29.361] Setting up SSH remote "10.10.10.200"
[13:48:29.366] Using commit id "ee2b180d582a7f601fa6ecfdad8d9fd269ab1884" and quality "stable" for server
[13:48:29.373] Install and start server if needed
[13:48:29.376] Checking ssh with "C:\Users\WINDOWS_USER\bin\ssh.bat -V"
[13:48:29.574] > OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022

[13:48:29.664] Running script with connection command: "C:\Users\WINDOWS_USER\bin\ssh.bat" -T -D 27090 "10.10.10.200" bash
[13:48:29.667] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:48:30.016] > ]0;C:\WINDOWS\System32\cmd.exe
[13:48:30.016] Got some output, clearing connection timeout
[13:48:31.486] > 0a5713e02637: running
[13:48:31.533] > Acquiring lock on /home/linux_user/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd26
> 9ab1884/vscode-remote-lock.linux_user.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
> Found existing installation at /home/linux_user/.vscode-server/bin/ee2b180d582a7f601fa6
> ecfdad8d9fd269ab1884...
> Checking /home/linux_user/.vscode-server/.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884.log 
> and /home/linux_user/.vscode-server/.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884.pid for a
>  running server
> Looking for server with pid: 2244153
> Running ssh connection command... /home/linux_user/.vscode-server/bin/ee2b180d582a7f601
> fa6ecfdad8d9fd269ab1884/bin/code-server --start-server --host=127.0.0.1 --accept
> -server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level a
> ll   &> "/home/linux_user/.vscode-server/.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884.log"
>  < /dev/null
> printenv:
>     SHELL=/usr/bin/zsh
>     PWD=/home/linux_user
>     LOGNAME=linux_user
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/linux_user
>     LANG=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/linux_user/.vscode-server
>     SSH_CONNECTION=10.10.10.41 62940 10.10.10.200 22666
>     XDG_SESSION_CLASS=user
>     USER=linux_user
>     SHLVL=0
>     XDG_SESSION_ID=318
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=10.10.10.41 62940 22666
>     PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
>     OLDPWD=/home/linux_user
>     _=/usr/bin/printenv
> Removing old logfile at /home/linux_user/.vscode-server/.ee2b180d582a7f601fa6ecfdad8d9f
> d269ab1884.log
> Spawned remote server: 2245523
> Waiting for server log...
[13:48:31.540] > 
[13:48:31.617] > Waiting for server log...
[13:48:31.674] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> nse) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> atement).
> *
> 
> 0a5713e02637: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==36665==
> osReleaseId==debian==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==73==
> connectionToken==1111aaaa-111a-11aa-1aa1-1a1a1111a1a1==
> 0a5713e02637: end
[13:48:31.674] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==36665==
osReleaseId==debian==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==73==
connectionToken==1111aaaa-111a-11aa-1aa1-1a1a1111a1a1==

[13:48:31.675] Remote server is listening on 36665
[13:48:31.675] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":36665},"osReleaseId":"debian","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"1111aaaa-111a-11aa-1aa1-1a1a1111a1a1"},"serverStartTime":73,"installUnpackCode":""}
[13:48:31.679] Starting forwarding server. localPort 27092 -> socksPort 27090 -> remotePort 36665
[13:48:31.681] Forwarding server listening on 27092
[13:48:31.681] Waiting for ssh tunnel to be ready
[13:48:31.683] [Forwarding server 27092] Got connection 0
[13:48:31.685] Tunneled 36665 to local port 27092
[13:48:31.685] Resolved "ssh-remote+10.10.10.200" to "127.0.0.1:27092"
[13:48:31.688] Failed to set up socket for dynamic port forward to remote port 36665: connect ECONNREFUSED 127.0.0.1:27090. Is the remote port correct?
[13:48:31.697] ------




[13:48:32.092] [Forwarding server 27092] Got connection 1
[13:48:32.339] [Forwarding server 27092] Got connection 2
```

</details>

<details>

<summary>Login failure for subsequent connection attempts</summary>

```
[13:37:05.245] Log Level: 2
[13:37:05.267] VS Code version: 1.76.2
[13:37:05.268] Remote-SSH version: remote-ssh@0.98.0
[13:37:05.268] win32 x64
[13:37:05.269] SSH Resolver called for "ssh-remote+10.10.10.200", attempt 1
[13:37:05.270] "remote.SSH.useLocalServer": false
[13:37:05.271] "remote.SSH.showLoginTerminal": false
[13:37:05.271] "remote.SSH.remotePlatform": {"10.10.10.200":"linux"}
[13:37:05.271] "remote.SSH.path": C:\Users\WINDOWS_USER\bin\ssh.bat
[13:37:05.271] "remote.SSH.configFile": undefined
[13:37:05.272] "remote.SSH.useFlock": true
[13:37:05.272] "remote.SSH.lockfilesInTmp": false
[13:37:05.272] "remote.SSH.localServerDownload": auto
[13:37:05.272] "remote.SSH.remoteServerListenOnSocket": false
[13:37:05.272] "remote.SSH.showLoginTerminal": false
[13:37:05.272] "remote.SSH.defaultExtensions": []
[13:37:05.273] "remote.SSH.loglevel": 2
[13:37:05.273] "remote.SSH.enableDynamicForwarding": true
[13:37:05.273] "remote.SSH.enableRemoteCommand": false
[13:37:05.273] "remote.SSH.serverPickPortsFromRange": {}
[13:37:05.273] "remote.SSH.serverInstallPath": {}
[13:37:05.280] SSH Resolver called for host: 10.10.10.200
[13:37:05.280] Setting up SSH remote "10.10.10.200"
[13:37:05.286] Using commit id "ee2b180d582a7f601fa6ecfdad8d9fd269ab1884" and quality "stable" for server
[13:37:05.293] Install and start server if needed
[13:37:05.296] Checking ssh with "C:\Users\WINDOWS_USER\bin\ssh.bat -V"
[13:37:05.511] > OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022

[13:37:05.607] Running script with connection command: "C:\Users\WINDOWS_USER\bin\ssh.bat" -T -D 26844 "10.10.10.200" bash
[13:37:05.609] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:37:05.974] > ]0;C:\WINDOWS\System32\cmd.exe
[13:37:05.975] Got some output, clearing connection timeout
[13:37:08.412] > 47f39397bbee: running
[13:37:08.451] > Acquiring lock on /home/linux_user/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd26
> 9ab1884/vscode-remote-lock.linux_user.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
> Found existing installation at /home/linux_user/.vscode-server/bin/ee2b180d582a7f601fa6
> ecfdad8d9fd269ab1884...
> Checking /home/linux_user/.vscode-server/.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884.log 
> and /home/linux_user/.vscode-server/.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884.pid for a
>  running server
[13:37:08.466] > Looking for server with pid: 2234846
[13:37:08.486] > Found running server...
[13:37:08.497] > 
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> nse) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> atement).
> *
> 
[13:37:08.510] > Checking server status on port 33369 with wget
> 47f39397bbee: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==33369==
> osReleaseId==debian==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==11111aa1-a1aa-11aa-a111-11111a111111==
> 47f39397bbee: end
[13:37:08.510] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==33369==
osReleaseId==debian==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==11111aa1-a1aa-11aa-a111-11111a111111==

[13:37:08.511] Remote server is listening on 33369
[13:37:08.511] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":33369},"osReleaseId":"debian","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"11111aa1-a1aa-11aa-a111-11111a111111"},"installUnpackCode":""}
[13:37:08.515] Starting forwarding server. localPort 26852 -> socksPort 26844 -> remotePort 33369
[13:37:08.517] Forwarding server listening on 26852
[13:37:08.517] Waiting for ssh tunnel to be ready
[13:37:08.519] Tunneled 33369 to local port 26852
[13:37:08.519] Resolved "ssh-remote+10.10.10.200" to "127.0.0.1:26852"
[13:37:08.521] [Forwarding server 26852] Got connection 0
[13:37:08.524] Failed to set up socket for dynamic port forward to remote port 33369: connect ECONNREFUSED 127.0.0.1:26844. Is the remote port correct?
[13:37:08.533] ------




[13:37:08.547] [Forwarding server 26852] Got connection 1
[13:37:08.548] Failed to set up socket for dynamic port forward to remote port 33369: connect ECONNREFUSED 127.0.0.1:26844. Is the remote port correct?
```

</details>

**Comment by eleanorjboyd** [comment] 2023-03-17 21:46
@meganrogge do you think this could be related to https://github.com/microsoft/vscode/issues/177044?

**Comment by meganrogge** [comment] 2023-03-20 14:54
It's possible, though this seems more likely to be the issue

> In my case, the 2FA was not working well with the Remote.SSH: Enable Dynamic Forwarding options. Disabling this allowed me to consistently connect (although I needed to interact with my 2fa more times than I'd like).

**Comment by eleanorjboyd** [comment] 2023-03-23 15:38
Hi! Sounds good we can wait until it appears again to get those logs. They should also be saved `~/.vscode-server/hash.log` on the remote side but if you deleted this folder to help with reconnection then they won't be there any longer.

**Comment by alligatorbait** [comment] 2023-03-29 21:53
I had network latency issues between host and VM, extending the ssh connect timeout was the solution. Not sure of the details of your errors, but could be similar.

Extend timeout for Remote - SSH in VSCode.
(Ctrl+Shift+X)
Click the Gear Icon on Remote - SSH
Click Extension Settings
Set Timeout to something worthy of current network latency: "remote.SSH.connectTimeout": 60

**Comment by eleanorjboyd** [comment] 2023-03-30 16:27
glad you figured out a solution! Happy coding 🎉

**Closed by eleanorjboyd** 2023-03-30 16:27 UTC
Labels: ssh, info-needed
