### ISSUE TITLE
Open Editor Preview works only the first time

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4434] opened 2021-02-07 21:33 UTC
To reproduce:
- Remote Containers > Try a Sample > Node
- npm install
- npm start
- In the notification select 'Open Preview in Editor'
![image](https://user-images.githubusercontent.com/172399/107160016-e7808280-6993-11eb-8045-42337c7e878d.png)
- the preview shows up in the browser:
![image](https://user-images.githubusercontent.com/172399/107160072-4e05a080-6994-11eb-84b9-0471fe094684.png)

- modify server.js
- leave the simple browser editor open
- kill the server process
- npm start
- Open in Preview again

The embedded browser remains empty:
![image](https://user-images.githubusercontent.com/172399/107160042-20b8f280-6994-11eb-90b7-871d2f0923e4.png)

When closing the Simple browser before the second run then the simple browser works

**Comment by alexr00** [comment] 2021-02-08 12:48
@mjbvz I'm just calling `IExternalUriOpener.openExternalUri` with the same arguments again. Is there something else I should do to make the simple browser editor refresh correctly?

**Comment by mjbvz** [comment] 2021-02-09 05:33
@alexr00 I just pushed a fix for  https://github.com/microsoft/vscode-remote-release/issues/4438 which was related

I also pushed https://github.com/microsoft/vscode/commit/87a3effc79a191a64854547fb6d05bd57433099f which attempts to disable caching for iframe contents

I'll test this again once those changes are in since I am currently having issues testing OSS with containers

**Comment by alexr00** [comment] 2021-02-09 10:12
Tested with the new insiders that contains your changes, and the issue is fixed there. Thank you!

**Closed by alexr00** 2021-02-09 10:12 UTC
Labels: bug
