### ISSUE TITLE
VS Code hangs when connection times out

### ISSUE THREAD

**Issue by christatedavies** [microsoft/vscode-remote-release#3479] opened 2020-08-06 12:07 UTC
We've had an instance where the SSH connection has dropped  (vscode v1.47.3, remote ssh v0.51.0) and the developer didn't notice. VS Code locked up and he had to kill the app (MacOS) - when he returned, the code changes were gone - presumably because the connection has been dropped.

It would be good to get a keep alive in the SSH connection. I did try to use this in my config, but in the SSH Ouptput window, I don't see any keep live messages. Not that it doesn't mean its not working...

```
Host xxx.xxx.xxx.xxx
  HostName my-dev-box
  User chris-td
  ForwardAgent yes
  ServerAliveInterval 120
```

**Comment by Chuxel** [comment] 2020-09-02 23:02
I suspect this is a dupe of #3096 - though that shouldn't cause us to hang.  @roblourens Any idea?

**Comment by roblourens** [comment] 2020-10-03 21:54
Sorry for the slow response. VS Code shouldn't hang when the connection to the server is lost, it should be able to recover and reconnect without losing work. The hang is probably not necessarily related to issues with SSH. Was this a one-off or a recurring issue? Will close for now unless we determine that there is some bug

**Closed by roblourens** 2020-10-03 21:54 UTC
Labels: ssh
