### ISSUE TITLE
Remote development with ssh should not expect that we have admin permissions on target server.

### ISSUE THREAD

**Issue by ysig** [microsoft/vscode-remote-release#6152] opened 2022-01-10 14:53 UTC
Hi,

I recently started working in a cluster to which I have normal ssh access.

The problem is that I don't have admin permissions, which is something really normal in big clusters for security reasons.

Also port forwarding is highly regulated and there is a good chance that tcp forwarding is deactivated to which I have no say.

When I try to install vscode server (the standard procedure when connecting through ssh) I get the following: 

```
tmpDir==/run/user/301900==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==7f28e997-5c25-4c1d-a810-7b07ec4e0803==
d5444d6902c8: end
channel 3: open failed: administratively prohibited: open failed
channel 4: open failed: administratively prohibited: open failed
```

I find a duplicated of this issue [here](https://github.com/microsoft/vscode-remote-release/issues/744) that were not properly addressed.

In the end to do ssh on a server you don't need to have admin permissions and seeing updating files should be possible anyway (just a simple sshfs should work).

Thus, I would like to request one of the following features to be implemented:
1. Either maintain a legacy and less featured ssh connection fallback module for when the `install vscode server` fails, that has limited functionalities.
2. Provide a way that the admin of a server can install a vscode server for a user ones and then the user will be able to connect without this requiring administrator permissions to operate or allowing for security backdoors.

**Comment by roblourens** [comment] 2022-01-11 04:48
You don't need to have admin access on the remote. It's likely that tcp forwarding is disabled on your remote ssh server, is that possible?

**Comment by ysig** [comment] 2022-01-11 09:57
Yes it is, but it is the case in a lot of servers.
(sshfs works though, and this should be enough)

**Comment by tanhakabir** [comment] 2022-01-11 21:11
Unfortunately we need tcp forwarding enabled on your remote for the remote-ssh extension to work. There's this issue https://github.com/microsoft/vscode-remote-release/issues/92 that tracks this request.

I'm going to close this issue for now since it seems like a duplicate of https://github.com/microsoft/vscode-remote-release/issues/92 but let me know if I'm incorrect!

**Closed by tanhakabir** 2022-01-11 21:11 UTC
Labels: needs more info
