### ISSUE TITLE
Can't connect to Non-English Windows remote

### ISSUE THREAD

**Issue by rura6502** [microsoft/vscode-remote-release#2351] opened 2020-02-13 14:43 UTC
- VSCode Version: 1.43.0-insider(system setup)
- Local OS Version: Windows 10
- Remote OS Version: Windows 10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. register new ssh host(server)
2. try 'connect to Host in New Window'

with this error message

'uname' is not recognized as an internal or external command,
operable program or batch file.

this is full log

```
[23:40:13.978] Log Level: 3
[23:40:13.982] remote-ssh@0.49.0
[23:40:13.982] win32 x64
[23:40:13.984] SSH Resolver called for "ssh-remote+192.168.11.127", attempt 1
[23:40:13.985] SSH Resolver called for host: 192.168.11.127
[23:40:13.985] Setting up SSH remote "192.168.11.127"
[23:40:13.988] Acquiring local install lock: C:\Users\LOCAL_USER\AppData\Local\Temp\vscode-remote-ssh-192.168.11.127-install.lock
[23:40:14.007] Looking for existing server data file at c:\Users\LOCAL_USER\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-192.168.11.127-1fbacccbc900bb59ba8a8f26a4128d48a1c97842\data.json
[23:40:14.008] Using commit id "1fbacccbc900bb59ba8a8f26a4128d48a1c97842" and quality "insider" for server
[23:40:14.010] Install and start server if needed
[23:40:14.024] Checking ssh with "ssh -V"
[23:40:14.067] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[23:40:14.067] Requires non-windows OpenSSH, skipping
[23:40:14.067] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[23:40:14.098] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[23:40:14.098] Requires non-windows OpenSSH, skipping
[23:40:14.098] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[23:40:14.132] > OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[23:40:14.134] askpass server listening on \\.\pipe\vscode-ssh-askpass-6dce331a3450c758c2232ca5e9d48f079bb74111-sock
[23:40:14.134] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-e5063a3a61a2103e81377a6aaedc66b37d8a4a55-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-T","-D","3401","192.168.11.127"],"dataFilePath":"c:\\Users\\LOCAL_USER\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-192.168.11.127-1fbacccbc900bb59ba8a8f26a4128d48a1c97842\\data.json"}
[23:40:14.134] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\LOCAL_USER\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-0.49.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\LOCAL_USER\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-0.49.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-6dce331a3450c758c2232ca5e9d48f079bb74111-sock"}
[23:40:14.140] Spawned 23468
[23:40:14.223] > local-server> Spawned ssh: 16088
[23:40:14.798] Got askpass request: {"request":"REMOTE_USER@192.168.11.127's password: "}
[23:40:14.799] Showing password prompt
[23:40:14.800] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-aeddc90ccec7615f3228581f4ac09bfa53990026-sock
[23:40:14.800] Writing password prompt to globalState
[23:40:16.066] Got password response
[23:40:16.066] Interactor gave response: ***
[23:40:16.066] Cleaning up other-window auth server
[23:40:16.265] > Microsoft Windows [Version 10.0.17763.1039]
> (c) 2018 Microsoft Corporation. All rights reserved.
> 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>
[23:40:16.280] > echo 'ready: ae157128ab2c'
> 'ready: ae157128ab2c'
> 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>
[23:40:16.352] > uname -rsv
[23:40:16.411] > 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>
[23:40:16.412] stderr> 'uname' is not recognized as an internal or external command, operable program or batch file.
[23:40:33.069] Terminating local server
[23:40:33.072] Resolver error: Connecting with SSH timed out
[23:40:33.081] ------




[23:40:33.084] Local server exit: null

```

**Comment by roblourens** [comment] 2020-02-13 17:41
Could you try installing the nightly version of the extension (uninstall the stable version first) and then trying again?

**Comment by rura6502** [comment] 2020-02-14 00:19
@roblourens 
Thx your reply.
uninstall the stable version, then I tried to use nightly version. got the same problem

```
[09:16:09.490] Log Level: 2
[09:16:09.491] remote-ssh-nightly@2020.2.18300
[09:16:09.491] win32 x64
[09:16:09.493] SSH Resolver called for "ssh-remote+192.168.11.127", attempt 1
[09:16:09.494] SSH Resolver called for host: 192.168.11.127
[09:16:09.494] Setting up SSH remote "192.168.11.127"
[09:16:09.499] Acquiring local install lock: C:\Users\LOCAL_USER\AppData\Local\Temp\vscode-remote-ssh-192.168.11.127-install.lock
[09:16:09.502] Looking for existing server data file at c:\Users\LOCAL_USER\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-ssh-nightly\vscode-ssh-host-192.168.11.127-1fbacccbc900bb59ba8a8f26a4128d48a1c97842\data.json
[09:16:09.504] Using commit id "1fbacccbc900bb59ba8a8f26a4128d48a1c97842" and quality "insider" for server
[09:16:09.506] Install and start server if needed
[09:16:09.515] Checking ssh with "ssh -V"
[09:16:09.560] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:16:09.561] Requires non-windows OpenSSH, skipping
[09:16:09.561] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[09:16:09.600] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:16:09.601] Requires non-windows OpenSSH, skipping
[09:16:09.601] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[09:16:09.646] > OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[09:16:09.648] askpass server listening on \\.\pipe\vscode-ssh-askpass-786c3ab6a2170d50fa03aa40821a9537b3d55341-sock
[09:16:09.649] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-453868a2dc34f5302925e6d898329f521146323b-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","3247","192.168.11.127"],"dataFilePath":"c:\\Users\\LOCAL_USER\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\ms-vscode-remote.remote-ssh-nightly\\vscode-ssh-host-192.168.11.127-1fbacccbc900bb59ba8a8f26a4128d48a1c97842\\data.json"}
[09:16:09.649] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\LOCAL_USER\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-nightly-2020.2.18300\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\LOCAL_USER\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-nightly-2020.2.18300\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-786c3ab6a2170d50fa03aa40821a9537b3d55341-sock"}
[09:16:09.657] Spawned 6224
[09:16:09.762] > local-server> Spawned ssh: 22724
[09:16:09.794] stderr> OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[09:16:09.949] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Vd2gj7nwpOLcttWoe/pkveps9yTl+K8IeWOsDcPkTT0
[09:16:10.130] Got askpass request: {"request":"REMOTE_USER@192.168.11.127's password: "}
[09:16:10.132] Showing password prompt
[09:16:10.133] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-36f4559a8aac1ce4d785574251271cbc225270d0-sock
[09:16:10.133] Writing password prompt to globalState
[09:16:12.420] Got password response
[09:16:12.420] Interactor gave response: ***
[09:16:12.420] Cleaning up other-window auth server
[09:16:12.444] stderr> Authenticated to 192.168.11.127 ([192.168.11.127]:22).
[09:16:12.564] > Microsoft Windows [Version 10.0.17763.1039]
> (c) 2018 Microsoft Corporation. All rights reserved.
> 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>echo 'ready: 95e7afb6a0cf'
[09:16:12.566] > 'ready: 95e7afb6a0cf'
> 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>
[09:16:12.568] > uname -rsv
> 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>
[09:16:12.568] stderr> 'uname' is not recognized as an internal or external command, operable program or batch file.
[09:16:29.422] Terminating local server
[09:16:29.423] Resolver error: Connecting with SSH timed out
[09:16:29.427] ------




[09:16:29.429] Local server exit: null
```

**Comment by roblourens** [comment] 2020-02-14 19:21
This is really confusing - that output is actually expected because that's how we probe the remote to check whether it's windows or linux. We are looking for that exact error message so something strange must be going wrong in the code that does this.

Would you install this version of the extension that has some extra logging, which will hopefully tell me what's going on? 
[remote-ssh-nightly-1000.0.0.zip](https://github.com/microsoft/vscode-remote-release/files/4206373/remote-ssh-nightly-1000.0.0.zip)


Just rename to '.vsix', uninstall the installed version of the extension, and run the "install from vsix" command in vscode.

**Comment by rura6502** [comment] 2020-02-16 00:42
@roblourens 

```
[09:37:57.742] Log Level: 2
[09:37:57.743] remote-ssh-nightly@2020.2.19680
[09:37:57.743] win32 x64
[09:37:57.747] SSH Resolver called for "ssh-remote+192.168.11.127", attempt 1
[09:37:57.747] SSH Resolver called for host: 192.168.11.127
[09:37:57.748] Setting up SSH remote "192.168.11.127"
[09:37:57.751] Acquiring local install lock: C:\Users\LOCAL_USER\AppData\Local\Temp\vscode-remote-ssh-192.168.11.127-install.lock
[09:37:57.755] Looking for existing server data file at c:\Users\LOCAL_USER\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-ssh-nightly\vscode-ssh-host-192.168.11.127-1fbacccbc900bb59ba8a8f26a4128d48a1c97842\data.json
[09:37:57.756] Using commit id "1fbacccbc900bb59ba8a8f26a4128d48a1c97842" and quality "insider" for server
[09:37:57.758] Install and start server if needed
[09:37:57.762] Checking ssh with "ssh -V"
[09:37:57.820] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:37:57.821] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[09:37:57.864] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:37:57.865] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[09:37:58.014] > OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[09:37:58.018] askpass server listening on \\.\pipe\vscode-ssh-askpass-b9f87dbbd7be8bbd13f83bb6c2e0cb9c907432ca-sock
[09:37:58.018] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-f1e880e6673df78bb41aa5e34d4d992630f9a9e1-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","2523","192.168.11.127"],"dataFilePath":"c:\\Users\\LOCAL_USER\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\ms-vscode-remote.remote-ssh-nightly\\vscode-ssh-host-192.168.11.127-1fbacccbc900bb59ba8a8f26a4128d48a1c97842\\data.json"}
[09:37:58.019] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\LOCAL_USER\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-nightly-2020.2.19680\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\LOCAL_USER\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-nightly-2020.2.19680\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-b9f87dbbd7be8bbd13f83bb6c2e0cb9c907432ca-sock"}
[09:37:58.027] Spawned 23216
[09:37:58.143] > local-server> Spawned ssh: 24532
[09:37:58.176] stderr> OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[09:37:58.478] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Vd2gj7nwpOLcttWoe/pkveps9yTl+K8IeWOsDcPkTT0
[09:37:58.748] Got askpass request: {"request":"REMOTE_USER@192.168.11.127's password: "}
[09:37:58.749] Showing password prompt
[09:37:58.750] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-c7da7c461338199012fe7ec0e24a6e210650e8bf-sock
[09:37:58.750] Writing password prompt to globalState
[09:38:02.622] Got password response
[09:38:02.622] Interactor gave response: ***
[09:38:02.623] Cleaning up other-window auth server
[09:38:02.678] stderr> Authenticated to 192.168.11.127 ([192.168.11.127]:22).
[09:38:02.838] > Microsoft Windows [Version 10.0.17763.1039]
> (c) 2018 Microsoft Corporation. All rights reserved.
> 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>
[09:38:02.855] > echo 'ready: ddadfb5e0c26'
> 'ready: ddadfb5e0c26'
> 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>
[09:38:02.930] > uname -rsv
[09:38:02.986] > 
> REMOTE_USER@DESKTOP-HPF4V65 C:\Users\REMOTE_USER>
[09:38:02.986] stderr> 'uname'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
[09:38:02.986] stderr> ��ġ ������ �ƴմϴ�.
[09:38:19.626] Terminating local server
[09:38:19.628] Resolver error: Connecting with SSH timed out
[09:38:19.640] ------

[09:38:19.651] Local server exit: null
```

actually My windows is korean version. so I expect that error is `'uname' is not recognized as an internal or external command, operable program or batch file.`. when I put the command `uname -rsv` in remote server english cmd, I got this error. `'uname' is not recognized as an internal or external command, operable program or batch file.`.

**Comment by roblourens** [comment] 2020-02-16 18:36
Oh, so that error is probably translated into Korean. I will have to use a different method to detect the platform...

**Comment by nedsociety** [comment] 2020-02-24 16:48
Same situation here. Here's a temporary workaround until fix is implemented.

Create a uname.bat file in %USERPROFILE% (or wherever your SSH session starts) with following content:

```
@echo off
chcp 65001 > NUL
echo 'uname' is not recognized as an internal or external command, 1>&2
echo operable program or batch file. 1>&2
exit /b 9009
```

It will emulate the expected error message in English then additionally set codepage to UTF-8 for future commands.

**Comment by roblourens** [comment] 2020-02-25 18:55
I haven't been able to repro this. What language are you using @nedsociety? 

The default codepage is actually still english even when I am using a different language, not sure why that is. I did set a registry key so that the codepage would be changed by default in each cmd session but I am still able to connect just fine.

If you run `echo 'uname' | ssh <host>` from the client you are connecting from, what output do you get?

**Comment by roblourens** [comment] 2020-02-25 18:58
And the remote OS is win 10 for both of you?

**Comment by roblourens** [comment] 2020-02-25 19:09
And is your default ssh shell cmd or powershell? (cmd is the default)

**Comment by KKKIIO** [comment] 2020-03-04 15:39
I encounter the same problem. Both Os is win 10, and the default shell of remote ssh server is powershell, here is the output of `echo uname | ssh <host>` in my local computer:
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
Windows PowerShell
��Ȩ���� (C) Microsoft Corporation����������Ȩ����

�����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6

PS C:\Users\xieziheng>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   在 Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   在 Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
uname
uname : 无法将“uname”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ uname
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (uname:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\xieziheng>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   在 Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   在 Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by nedsociety** [comment] 2020-03-04 16:15
@roblourens
Both server (18362.657) and client (18363.657) are Win10. The client defaults to English except Korean input method being installed additionally. The server, however, has Korean as its default language (*1) as well as its default non-Unicode locale (*2). I cannot put it into test for now so I'm not sure which one is the culprit. And cmd is the shell.

*1. Korean language pack is installed and defaulted for app language
*2. Language settings -> Administrative language settings -> Language for non-Unicode programs -> Change system locale -> Korean

Here's the output:

```
C:\Users\ned>echo chcp | ssh 172.17.45.146
Pseudo-terminal will not be allocated because stdin is not a terminal.
ned@172.17.45.146's password:
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

ned@DESKTOP-I5OPL4I C:\Users\ned>chcp
Ȱ�� �ڵ� ������: 949

ned@DESKTOP-I5OPL4I C:\Users\ned>
C:\Users\ned>

C:\Users\ned>echo uname | ssh 172.17.45.146
Pseudo-terminal will not be allocated because stdin is not a terminal.
ned@172.17.45.146's password:
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

ned@DESKTOP-I5OPL4I C:\Users\ned>uname
'uname'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.

ned@DESKTOP-I5OPL4I C:\Users\ned>
```

Note that these mojibake, copied directly from cmd terminal, seems different when I manually type `uname` into ssh session without piping:

```
C:\Users\ned>ssh 172.17.45.146
ned@172.17.45.146's password:
```

here as soon as I type my password **the terminal is cleared** as if I've run `chcp`. Then,

```
ned@DESKTOP-I5OPL4I C:\Users\ned>uname
'uname'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

ned@DESKTOP-I5OPL4I C:\Users\ned>
```
which shows proper Korean language.

**Comment by roblourens** [comment] 2020-03-04 19:48
> *2. Language settings -> Administrative language settings -> Language for non-Unicode programs -> Change system locale -> Korean

This was the key - now I can reproduce the issue! Thanks

**Comment by MathiasMagnus** [comment] 2020-03-15 19:12
@roblourens I have a similar problem, but with a docker container on Windows (I'm trying to put all my dev tools into containers: compilers, build system, etc.). I'm trying to connect to my locally running container, and I get a similar error with the error message holding partly Hungarian localized text (argues about the user not existing). I guess that the root problem is the same, the way Linux and Windows are detected. It bails out after trying to execute the aforementioned Linux commands.

I recorded what I did and [uploaded](https://1drv.ms/v/s!AmBiyz2ky0L5r6Z5vef9ZQnSVO3Kjg?e=m7VQgi) to my personal OneDrive. (If it's blurry, please download as the web player may be too blurry to read text.)

**Comment by charraeus** [comment] 2020-03-15 19:17
I have a similar problem with SSH. I use a German Windows 10. @nedsociety 's workaround works for me, too. 
Many thanks to @nedsociety for it.

**Comment by MathiasMagnus** [comment] 2020-03-15 19:33
At a closer look, it may not be the same issue. This is the detailed error message:
```
[1 ms] Start: Resolving remote
[3 ms] Setting up container quizzical_brattain

[16 ms] Start: Check Docker is running
[21 ms] Start: Inspecting container
[29 ms] Start: Run: C:\Program Files\Docker\Docker\resources\bin\docker.exe exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=84db56fb-67e6-49dc-9cdf-a0ffaf1b22521584300691605 328e91ad8860b9512027bde588774a8e6b6257a39843b6b7e007867601272b84 /bin/sh
[34 ms] Start: Run in container: uname -m
[134 ms] Start: Run in container: cat /etc/passwd
[134 ms] Stdin closed!
[135 ms] Shell server terminated (code: 126, signal: null)
container 328e91ad8860b9512027bde588774a8e6b6257a39843b6b7e007867601272b84 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: Helytelen a felhasználónév vagy a jelszó. (0x52e)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF6655CAE77: (caller: 00007FF66557E4AB) Exception(7) tid(570) 8007052E The user name or password is incorrect.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess] 
 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"/bin/sh","User":"root","WorkingDirectory":"/","Environment":{"VSCODE_REMOTE_CONTAINERS_SESSION":"84db56fb-67e6-49dc-9cdf-a0ffaf1b22521584300691605"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```
It seems that it's trying to execute commands under user root, as that's how docker is invoked on the local machine, but on a Windows remote, no user named `root` exists, that's why the error message.

**Comment by roblourens** [comment] 2020-03-16 00:09
@MathiasMagnus please open a new issue, it doesn't look related to this one.

Another workaround for the issue with non-English remotes:

```
"remote.SSH.useLocalServer": false,
"remote.SSH.windowsRemotes": ["<your remote hostname>"] // only if the remote is Windows
```

**Comment by Hill1942** [comment] 2020-05-18 04:46
Same situation.
Is there a solution to this problem ?

**Comment by Hill1942** [comment] 2020-05-18 04:56
> Same situation here. Here's a temporary workaround until fix is implemented.
> 
> Create a uname.bat file in %USERPROFILE% (or wherever your SSH session starts) with following content:
> 
> ```
> @echo off
> chcp 65001 > NUL
> echo 'uname' is not recognized as an internal or external command, 1>&2
> echo operable program or batch file. 1>&2
> exit /b 9009
> ```
> 
> It will emulate the expected error message in English then additionally set codepage to UTF-8 for future commands.

it works, thanks !

**Comment by fzhangfanz** [comment] 2020-06-05 06:38
I have the same question.
local OS:mac os catalina 10.15.5
remote OS: win10 1909

The uname file is not a Windows file.
To solove the problem,u need to manually choose OS.
Add "remote.SSH.useLocalServer": false        to  setting.json

**Comment by roblourens** [comment] 2020-08-01 02:58
This will be in the Remote-SSH "nightly" extension after the weekend and I'd really appreciate people testing it out

**Closed** 2020-08-01 02:57 UTC
Labels: bug, ssh

**Comment by sunghwan2789** [comment] 2020-08-04 13:35
@roblourens I just installed nightly extension and saw it work! Thank you 👍
