### ISSUE TITLE
Unable to run vscode-server and nginx on localhost together (used to work)

### ISSUE THREAD

**Issue by pimski** [microsoft/vscode-remote-release#2071] opened 2019-12-20 09:31 UTC
Since yesterday I'm not able to run vscode-server and nginx together on localhost. This used to be possible, which was nice since I want nginx to listen to localhost and not to a changing ip-adress (which seems to be in the range 172.30.x.x). Now only one of the two can listen to localhost.

- VSCode Version: 1.41.1
- Local OS Version: Windows 10 Insider Preview 19536.1000 (rs_prerelease)
- Remote OS Version: Ubuntu 18.04.3 LTS
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

Scenario 1) First start nginx, then vscode
1. wsl --shutdown
2. wsl
3. sudo service nginx start
4. Browsing to "http://localhost/" works (shows nginx page)
5. Start vscode (unable to connect to vscode-server)
From Remote-WSL: Show log
```
[2019-12-20 09:57:04.339] [renderer1] [error] [remote-connection][Management   ][c1003…][initial][::1:36877] socketFactory.connect() failed. Error:
[2019-12-20 09:57:04.339] [renderer1] [error] Error: connect ECONNREFUSED ::1:36877
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-20 09:57:04.339] [renderer1] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2019-12-20 09:57:04.339] [renderer1] [error] Error: connect ECONNREFUSED ::1:36877
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-20 09:57:04.445] [renderer1] [error] [remote-connection][ExtensionHost][25f95…][initial][::1:36877] socketFactory.connect() failed. Error:
[2019-12-20 09:57:04.445] [renderer1] [error] Error: connect ECONNREFUSED ::1:36877
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-20 09:57:04.445] [renderer1] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2019-12-20 09:57:04.445] [renderer1] [error] Error: connect ECONNREFUSED ::1:36877
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-20 09:57:04.461] [renderer1] [error] connect ECONNREFUSED ::1:36877: Error: connect ECONNREFUSED ::1:36877
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-20 09:57:04.462] [renderer1] [error] Could not fetch environment: Error: Could not fetch environment
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3798:126
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2019-12-20 09:57:04.462] [renderer1] [error] connect ECONNREFUSED ::1:36877: Error: connect ECONNREFUSED ::1:36877
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
```

Scenario 2) First start vscode, then nginx
1. wsl --shutdown
2. wsl
3. Start VS Code (starts fine)
4. sudo service nginx start
5. Browsing to "http://localhost/" doesn't work

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by nikosdouvlis** [comment] 2019-12-23 16:12
I can confirm this one. I am experiencing the same behavior

**Comment by AdamVig** [comment] 2019-12-23 21:30
Possible duplicate of #2060.

**Comment by aeschli** [comment] 2019-12-30 11:59
dup of #2060.

**Closed by aeschli** 2019-12-30 11:59 UTC
