### ISSUE TITLE
Reopen in Container no longer uses <project>/.env for environment referenced in docker-compose.yml

### ISSUE THREAD

**Issue by enjibby** [microsoft/vscode-remote-release#4639] opened 2021-03-10 03:21 UTC
- VSCode Version: 1.54.1
- Local OS Version: Windows 10 Pro (build 19042.804)
- Remote OS Version: WSL2, Docker Desktop 3.2.0.1 and Ubuntu 20.10
- Remote Extension/Connection Type: Docker/WSL

Steps to Reproduce:

1. Load a project that contains variables defined in `.env` and references to those variables in `docker-compose.yml`
2. Verify that `docker-compose up` uses the variables as it has always done.
3. Use `docker-compose down` to ensure that Visual Studio Remove Containers extension has to start the containers from scratch
4. Use Visual Studio Command Palette to select "Remote-Containers: Re-open in Container"
5. Take note that the new containers started by VSCode are not correctly set up using the variables defined and referenced in previous steps.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment] 2021-03-12 08:58
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4560

**Closed by chrmarti** 2021-03-12 08:58 UTC
Labels: containers
