### ISSUE TITLE
'Docker Compose required' when trying to 'reopen in a container'

### ISSUE THREAD

**Issue by AmirNamdar** [microsoft/vscode-remote-release#4626] opened 2021-03-08 16:11 UTC
- VSCode Version:
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z (3 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
- Local OS Version:
OS: Darwin x64 20.2.0
- Remote Containers Extenstion Version:
v0.163.0

Steps to Reproduce:
1.
![image](https://user-images.githubusercontent.com/39570722/110346907-b64dad80-8038-11eb-87c8-ba539cea422e.png)
2.
![image](https://user-images.githubusercontent.com/39570722/110346977-c82f5080-8038-11eb-8670-bfd2b8b07131.png)

I had a similiar issue where the extension couldn't find `docker`:
![image](https://user-images.githubusercontent.com/39570722/110347497-57d4ff00-8039-11eb-8f43-b14d1f56929d.png)
I solved this problem by specefieng the `docker` path with:
![image](https://user-images.githubusercontent.com/39570722/110347700-8c48bb00-8039-11eb-820d-8de88a17b5bc.png)

Unfourtunately, there doesn't seem to be a setting for docker-compose.
Obviously something broke in my local environment. 
I don't know what to fix without knowing where `docker-compose` is searched for.

Thanks

**Comment by chrmarti** [comment] 2021-03-12 08:10
Duplicate of https://github.com/microsoft/vscode/issues/118372 and/or https://github.com/microsoft/vscode/issues/118460

**Closed by chrmarti** 2021-03-12 08:10 UTC
Labels: containers
