### ISSUE TITLE
Jupyter notebook not openning/executing using dev container 

### ISSUE THREAD

**Issue by RicaBenhossi** [microsoft/vscode-remote-release#3087] opened 2020-05-29 11:38 UTC
Issue Type: <b>Bug</b>

Since last 3 or 4 days my jupyter notebooks are not opening on my dev container. When I'm not connected to the container, it opens. Using vscode stable version, it opens both ways: local and using dev container.

Even regular python files using #%% notation to run cells are not running on dev container. It shows "executing cells" forever in Status Bar.

I already tried to build the container again from scratch but didn't work...

VS Code version: Code - Insiders 1.46.0-insider (cd41dd1f6065db76c77c6e2f659bb50e6f558dec, 2020-05-29T05:40:08.467Z)
OS version: Linux x64 5.3.0-53-generic
Remote OS version: Linux x64 5.3.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2241)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|7.67GB (0.17GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: EnergyStats|
|OS|Linux x64 5.3.0-53-generic|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2241)|
|Memory (System)|7.67GB (0.17GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.0.1
bracket-pair-colorizer|Coe|1.0.61
remote-containers|ms-|0.118.1
remote-ssh-edit-nightly|ms-|2020.5.19620
remote-ssh-nightly|ms-|2020.5.19620
vscode-remote-extensionpack|ms-|0.20.0
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|10.1.1
jinja|who|0.0.8
Bookmarks|ale|11.2.0
project-manager|ale|11.0.1
read-only-indicator|ale|3.2.0
gitkraken-glo|axo|1.1.0
vscode-django|bat|0.20.0
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.36.0
python-preview|don|0.0.4
git-extension-pack|don|0.1.3
githistory|don|0.6.5
gitlens|eam|10.2.1
todo-tree|Gru|0.0.176
MagicPython|mag|1.1.0
vscode-docker|ms-|1.2.1
python|ms-|2020.5.80290
resourcemonitor|mut|1.0.7
embrace|myc|1.0.0
autodocstring|njp|0.5.2
markdown-preview-enhanced|shd|0.5.10
clockify-tracker|tob|3.0.11
vscodeintellicode|Vis|1.2.7
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment] 2020-05-31 10:16
/needsMoreInfo can you please provide minimal notebook sample that enables us to reproduce the problem in a dev container. Can you share your container definition?

**Comment by aeschli** [comment] 2020-06-02 08:07
@RicaBenhossi @mnaveedb Anything intersting in the dev tools console (Help > Toggle Developer Tools) or in the log (Output > Log (...))?

**Comment by RicaBenhossi** [comment] 2020-06-02 23:17
Sorry for the delay in answering the questions. I've updated VSCode today (as I do every day) and it seems that it back to normal again... 

@egamma if you still want to check it out, here is one of my Jupyter notebooks that I've been using to test this issue and the files to dev container I use [EnergyStats.zip](https://github.com/microsoft/vscode-remote-release/files/4720040/EnergyStats.zip)
But a blank notebook with a simple print("Hello world") wasn't working though and was working perfectly before. 

@aeschli the only thing I've seen in the Console log is this error:
![image](https://user-images.githubusercontent.com/15204313/83574418-d5486d80-a503-11ea-87d2-cf220d271592.png)
But this error was already happening before and it doesn't seem to prevent the execution or even the opening of Jupyter notebooks. In fact, I've installed the stable version of VSCode (where the problem doesn't happen) and this error happens there too, and there the notebooks open and execute normally on the stable version. Here's the full log of Insiders version if you want to check it out [VSCodeInsiders.log](https://github.com/microsoft/vscode-remote-release/files/4719944/VSCodeInsiders.log)

Thank you guys for the help and, again, sorry for the delay...

**Comment by mnaveedb** [comment] 2020-06-03 10:10
I updated and Jupyter notebook started **working**. 
@aeschli  There is no error reported in logs though I still added them here


**Log (Extension Host)**
[2020-06-03 11:56:59.567] [exthost] [info] extension host started
[2020-06-03 11:56:59.583] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onResolveRemoteAuthority:wsl"}
[2020-06-03 11:56:59.584] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/mnave/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.44.2/dist/extension
[2020-06-03 11:57:03.606] [exthost] [info] ExtensionService#_doActivateExtension vscode.python {"startup":false,"extensionId":{"value":"vscode.python","_lower":"vscode.python"},"activationEvent":"onLanguage:python"}
[2020-06-03 11:57:03.607] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/mnave/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/python/dist/pythonMain
[2020-06-03 11:57:03.639] [exthost] [info] eager extensions activated

**Log (Remote Extension)
[2020-06-03 11:57:04.736] [exthost] [info] extension host started
[2020-06-03 11:57:04.888] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"extensionId":{"value":"ms-python.python","_lower":"ms-python.python"},"activationEvent":"onLanguage:python"}
[2020-06-03 11:57:04.894] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/extensions/ms-python.python-2020.6.83879-dev/out/client/extension
[2020-06-03 11:57:05.620] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-06-03 11:57:05.620] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/bin/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/extensions/debug-auto-launch/dist/extension
[2020-06-03 11:57:05.626] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-06-03 11:57:05.626] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/bin/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/extensions/emmet/dist/extension
[2020-06-03 11:57:05.681] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-06-03 11:57:05.682] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/bin/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/extensions/git/dist/main
[2020-06-03 11:57:05.764] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":true,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"*"}
[2020-06-03 11:57:05.764] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/bin/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/extensions/github-authentication/dist/extension.js
[2020-06-03 11:57:05.791] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-06-03 11:57:05.792] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/bin/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/extensions/merge-conflict/dist/extension
[2020-06-03 11:57:05.797] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":true,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"*"}
[2020-06-03 11:57:05.797] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/bin/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/extensions/microsoft-authentication/dist/extension.js
[2020-06-03 11:57:05.817] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-06-03 11:57:05.817] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/bin/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/extensions/search-result/dist/extension.js
[2020-06-03 11:57:05.819] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":true,"extensionId":{"value":"ms-vscode.cpptools","_lower":"ms-vscode.cpptools"},"activationEvent":"*"}
[2020-06-03 11:57:05.819] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/extensions/ms-vscode.cpptools-0.28.2/dist/main
[2020-06-03 11:57:06.670] [exthost] [info] Extension 'ms-python.python' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
[2020-06-03 11:57:06.766] [exthost] [info] eager extensions activated
[2020-06-03 11:57:19.373] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-06-03 11:57:19.374] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/naveed/.vscode-server-insiders/bin/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/extensions/github/dist/extension.js

**Log (Main)**log:mainLog

[2020-06-03 11:56:56.652] [main] [info] update#setState idle
[2020-06-03 11:57:27.785] [main] [info] update#setState checking for updates
[2020-06-03 11:57:27.865] [main] [info] update#setState idle

**Comment by mnaveedb** [comment] 2020-06-03 10:18
I also updated it works
There are some errors
@egamma I have attached the logs
[-1591179345711.log](https://github.com/microsoft/vscode-remote-release/files/4722594/-1591179345711.log)

**Comment by bamurtaugh** [comment] 2020-10-23 21:23
Hey @RicaBenhossi, thanks for opening this issue. Since it sounds like the issue was resolved after updating VS Code, going to close this issue. But please feel free to let us know if you're still experiencing any problems or have any other questions, and we'd be happy to discuss further or reopen. Thank you!

**Closed by bamurtaugh** 2020-10-23 21:23 UTC
Labels: needs-more-info
