### ISSUE TITLE
Possibility to use a bash command for an args

### ISSUE THREAD

**Issue by jolo-dev** [microsoft/vscode-remote-release#3628] opened 2020-09-03 12:20 UTC
Is it possible to use a bash command for a build args?
I need to retrieve it from the AWS parameter store via using the AWS-CLI
For example: 
```json
..
"build": {
    "args": {
      "PASSWORD": "$(aws ssm get-parameter --name /user/password --with-decryption | jq -r '.Parameter.Value')",
    }
  },
..
```
If I run the docker command in the terminal it works:
```bash
docker build \
    --build-arg PASSWORD=$(aws ssm get-parameter --name /user/password --with-decryption | jq -r '.Parameter.Value') .
```
Question:
Is there a way to do that?

**Comment by chrmarti** [comment] 2020-09-04 06:35
This is not supported at the moment. You could use a local environment variable with `"${localEnv:VAR_NAME}"`.

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/1050.

**Closed by chrmarti** 2020-09-04 06:35 UTC
Labels: containers
