### ISSUE TITLE
The terminal shell path "cmd.exe" does not exist

### ISSUE THREAD

**Issue by mlangTse** [microsoft/vscode-remote-release#1496] opened 2019-09-26 11:38 UTC
.[11:36:44.191] Install and start server if needed
[11:36:44.541] "install" terminal command done
[11:36:44.541] Install terminal quit with output: 
[11:36:44.541] Received install output: 
[11:36:44.541] Failed to parse remote port from server output: 
[11:36:44.541] 
[11:36:44.541] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":1,"retries":1}}
[11:36:44.541] ------

how to fix this

**Comment by roblourens** [comment] 2019-09-27 15:01
If you open a terminal and type `cmd.exe`, does it work? Do you know why cmd.exe is not on your path?

**Comment by mlangTse** [comment] 2019-09-28 03:58
> If you open a terminal and type `cmd.exe`, does it work? Do you know why cmd.exe is not on your path?

i can open cmd.exe, and i just check the cmd.exe is on my path, but i don't know why it said "cmd.exe" does not exist while connect remote

**Comment by roblourens** [comment] 2019-09-30 17:47
Hm, it seems like vscode can't find it on the path in vscode's environment. So if you open a local vscode window, can you use the terminal and find cmd.exe on the path in that environment?

**Comment by mlangTse** [comment] 2019-10-01 00:05
> Hm, it seems like vscode can't find it on the path in vscode's environment. So if you open a local vscode window, can you use the terminal and find cmd.exe on the path in that environment?

I can use terminal in a local vscode window

**Comment by roblourens** [comment] 2019-10-01 03:54
Dupe of https://github.com/microsoft/vscode-remote-release/issues/1479

**Closed by roblourens** 2019-10-01 03:54 UTC
Labels: needs-more-info

**Comment by mlangTse** [comment] 2019-10-01 06:27
> Dupe of #1479

this fix the "cmd.exe" DNE issue, however it just keep "Setting up SSH Host CSE: Connect to VS Code Server -- retry"

**Comment by mlangTse** [comment] 2019-10-01 06:32
> Dupe of #1479

All GOOD now!!! Thanks!!!
