### ISSUE TITLE
Adjustable project-name flag for docker-compose

### ISSUE THREAD

**Issue by lando-cal** [microsoft/vscode-remote-release#512] opened 2019-05-29 20:25 UTC
Currently, the docker-compose command seems to base `--project-name` off of the parent/project folder.

Launching containers from two sub-folders of a root project, seems to namespace them in separate areas. I've yet to find a way to override this. While this may work when both containers are inheriting from a top level docker-compose file, this would mean major refactoring of our repositories to match our IDE, rather than just specifying a flag to launch related projects under the same namespace.

As an example:

- Project1/
  - devcontainer1/
    - devcontainer.json
    - docker-compose.dev.yml
  - Project1.componentX/
    - devcontainer2/
      - devcontainer.json
      - docker-compose.dev.yml
    - Dockerfile
    - docker-compose.yml
  - docker-compose.yml
  - Dockerfile

`devcontainer1/devcontainer.json` expands `Project1/docker-compose.yml` , creating Docker networks/assets prepended with `Project1_`.

`devcontainer2/devcontainer.json` expands `Project1.componentX/docker-compose.yml`, which then either fails, as it's referencing Docker networks/assets with no prefix, or creates assets with the now incorrect prefix of `Project1.componentX` if assets are created explicitly.

**Comment by chrmarti** [comment] 2019-05-31 12:40
Related: #222

**Comment by chrmarti** [comment] 2019-10-21 10:47
We should also check for COMPOSE_PROJECT_NAME in .env or ENV.

**Comment by oben59** [comment] 2019-12-29 17:53
I'm really interested in this feature, to be consistent with how docker-compose works. 
I'd like to be able to clone a project with a docker-compose container declaration, just change the project name parameter and be able to launch my dev container regardless of the directory I cloned it in without any naming collision.

**Comment by ihormaslov** [comment] 2020-01-09 07:57
I have the same issue.
Seems like COMPOSE_PROJECT_NAME is ignored in .env

**Comment by szymon-nowak** [comment] 2020-01-09 11:26
Maybe custom (remote) project name could also be defined in the devcontainer.json file?

**Comment by LiNuXaDDiKt** [comment] 2020-03-10 12:49
I'm also quite interested.  managing directory naming is a pain when multiple developers are working on the same server.  Managing this from either the .env file or devcontainer.json would be ideal I think.

**Comment by TsuyoshiUshio** [comment] 2020-06-17 21:01
+1 I also want to override the project_name. I have directories that has a different name but almost the same docker compose. I need to remove container when I switch the directory.

**Comment by reaper8055** [comment] 2020-08-01 07:33
I was wondering if there's a fix other than what @zhijian720 mentioned?

**Comment by mrmachine** [comment] 2020-09-24 23:49
#979 (closed as a dupe of this issue) and #2645 (incorrectly closed with "working as described") give the best explanation for this issue.

The [official docs](https://code.visualstudio.com/docs/remote/containers-advanced#_setting-the-project-name-for-docker-compose) still say:

> VS Code will respect the value of the COMPOSE_PROJECT_NAME environment variable if set for the VS Code process or in a .env file in the root of the project.

And yet, VS Code will in fact always bring up containers with `--project-name BASENAME_OF_PROJECT_DIR`

    [3787 ms] Start: Run: docker-compose --project-name syrinscape -f /Users/tailee/IC/Projects/FOO/docker-compose.yml -f /Users/tailee/IC/Projects/FOO/.devcontainer/docker-compose.dev.yml up -d --build

This CLI arg seems to override `COMPOSE_PROJECT_NAME` exported before launching VS Code from CLI or in `.env` in the project root directory.

**Comment by chrmarti** [comment] 2020-09-25 10:52
@mrmachine Using the `COMPOSE_PROJECT_NAME` environment variable should work, could you open a bug report for this?

**Comment by mrmachine** [comment] 2020-09-25 15:42
@chrmarti Is that not what this issue is all about, already? There are several comments about it in this issue, even from you saying that:

> We should also check for COMPOSE_PROJECT_NAME in .env or ENV.

And #979 which perfectly describe the problem was already closed as a duplicate of this issue.

**Comment by chrmarti** [comment] 2020-09-29 12:39
I made the environment variable work a while back. You seem to describe a regression and I would appreciate a separate issue so I can follow up.

This issue is tracking the addition of a property to the devcontainer.json for the project name - the way I interpret it.

**Comment by rubensa** [comment] 2020-10-05 11:57
Yes, that's the point of this _feature-request_, to allow specifying **project-name** (for **docker-compose**) in **.devcontainer.json** so you don't have to create a **.env** file in the **root** of your project and set the **COMPOSE_PROJECT_NAME** variable there.

**Comment by chrmarti** [comment] 2021-03-09 08:20
@odannyc Not at this moment. It is best to 👍 the issue's description to add your vote.

**Comment by farums** [comment] 2021-04-17 22:41
а если еще внутри docker-compose топ-то  docker in docker   COMPOSE_PROJECT_NAME в .env  не могу задать потому что он воссияет на внутренний докер

**Comment by gwax** [comment] 2021-05-04 23:20
I would like to add an additional note as to the benefit of configuration in `devcontainer.json` rather than `.env`

There are a lot of tools, which structure themselves around managing environment via a `.env` file, which can clash with VSCode, including docker-compose itself. Being unconfigurable outside of a shared file makes the solution unusable by developers that share their repo with other non-VSCode developers or use tools that collide with `.env` (e.x. dotenv and and its variants).

**Comment by crhan** [comment] 2022-04-17 00:09
I have met this problem when I was preparing a dev environments for the whole team on a shared server. The docker compose project name will always be collised when two dev members open the same code project. Think of the "Clone Repository in Container Volume scene. And every dir name and structure will be the same.

**Comment by mmenzyns** [comment] 2022-10-20 13:17
I used @crhan solution to my problem. I needed devcontainer to not collide with standard docker-compose usage, I think @gwax might have had the same problem. What I did is create .env right before creating devcontainer, and deleting it right after devcontainer is created. It's definitely ugly solution, but I see no other choice, I put something similar to this in devcontainer.json:

`
"initializeCommand": "echo COMPOSE_PROJECT_NAME=debug > .env",
"postCreateCommand": "rm -f .env",
`

**Comment by marcindulak** [comment] 2022-10-20 16:20
The above "initializeCommand" trick creating `.env` seems not working anymore https://github.com/microsoft/vscode-remote-release/issues/7377

**Comment by akkie** [comment] 2023-03-23 16:15
I also have another example were it would help to define the name in the devcontainer.json file. It seems that there is also no workaround for my case, expect using the directory structure as described in one of the previous comments.

I have two docker compose files. One for test and one for dev. Both of them overriding a base docker compose file. Each docker compose file is based on its own Docker file and I also do not start all containers for each environment.

Why do I need these two environments. For dev as example I need the base node image and for test I use the playwright image. The database for dev is defined to persist the data and for the test environment it's configured to use ephemeral data.

**Comment by hpe-ykoehler** [comment] 2023-05-09 15:51
From the issue I linked, the default behavior of using ".devcontainer" for the docker-compose project name is not working anymore.

Ideally devcontainer (and cli) should now find some other means to set a default project name that match the docker compose criteria (maybe stripping the . for example)

**Comment by denvolj** [comment] 2023-08-22 14:44
Here is some piece of code if someone wants and have time to contribute: https://github.com/devcontainers/cli/blob/413c5f790f3a4972bf6f05b71d71ac946c87bc7c/src/spec-node/dockerCompose.ts#L45

**Comment by johnmcdowall** [comment] 2023-09-14 04:57
@chrmarti It's a very confusing choice to have the compose project name come from a `.env` file and not from configuration in the `devcontainer.json` file. Is there a specific reason reading a `project_name` key in `decvontainer.json` was not chosen? Is there any reason that shouldn't be done? Would a PR be accepted that allowed that option?

**Comment by sliekens** [comment] 2023-09-24 14:33
I might be missing the point of having the extension pass `--project-name $dirname` at all.

Doesn't Docker Compose already use the directory name if you omit the option?

It should also be possible to set the project name in the `docker-compose.yml`

``` yml
version: "3.9"
name: my-project-name # <----- used as prefix for volumes etc.
services:
   app: # ...

volumes:
  app-data: # <-----  my_project_name__app-data
```

Currently the extension overrides the `name` from the `docker-compose.yaml` by passing a different `--project-name`. I'm not sure why it's doing that?

**Comment by sliekens** [comment] 2023-09-24 15:06
> Here is some piece of code if someone wants and have time to contribute: https://github.com/devcontainers/cli/blob/413c5f790f3a4972bf6f05b71d71ac946c87bc7c/src/spec-node/dockerCompose.ts#L45

As far as I can tell, `getProjectName` can be greatly simplified by just _asking_ docker-compose for the project name.

Here's how you would do it in bash, but can be easily modified to work in Node.js:

``` sh
$ docker-compose -f docker-compose.yml config --format json | jq .name
"my-project-name"
```

This reuses the logic built in to Docker Compose to determine the project name:

- From the `COMPOSE_PROJECT_NAME` environment variable
- From the top level `name:` variable from the config file (or the last `name:` from a series of config files specified using -f)
- The basename of the project directory containing the config file (or containing the first config file specified using -f)

This can be implemented in a fully backwards-compatible way. Using a `.env` file to set `COMPOSE_PROJECT_NAME` will continue to work. Otherwise the YAML is checked for a `name:` property, which is currently not supported. If neither are set, the base name of the directory containing the (first) config file will be used.

cc @chrmarti

**Comment by johnmcdowall** [comment] 2023-09-24 17:39
@sliekens Great find, and yes an even better approach to just go with docker defaults. All of my Docker related files are in a subdir `.docker` so I don't like it using the defualt directory name, so passing a name in some form is a must for me.

**Comment by zsteinkamp** [comment] 2023-09-28 22:40
The lack of support for using `name:` from the `docker-compose.yml` file surprised me. I would have assumed this would be evaluated prior to checking for .env or env vars.

**Comment by sliekens** [comment] 2023-10-21 10:50
> I would have assumed this would be evaluated prior to checking for .env or env vars.

Env vars are checked first to enable multiple instances of a compose project.

<pre>
$ <b>COMPOSE_PROJECT_NAME=main</b> docker-compose up -d
[+] Running 4/4
 ✔ Network main_default           Created                                                                                                                                                                                                                                          0.1s
 ✔ Volume "main_postgres-data"    Created                                                                                                                                                                                                                                          0.0s
 ✔ Container main-db-1            Started                                                                                                                                                                                                                                          0.1s
 ✔ Container main-devcontainer-1  Started                                                                                                                                                                                                                                          0.1s
$ <b>COMPOSE_PROJECT_NAME=alt</b> docker-compose up -d
[+] Running 4/4
 ✔ Network alt_default           Created                                                                                                                                                                                                                                           0.1s
 ✔ Volume "alt_postgres-data"    Created                                                                                                                                                                                                                                           0.0s
 ✔ Container alt-db-1            Started                                                                                                                                                                                                                                           0.1s
 ✔ Container alt-devcontainer-1  Started
</pre>

For my projects, I put a static `.env` file with nothing but `COMPOSE_PROJECT_NAME` in source control. It would be nice if `name:` in docker-compose.yml would be supported so I can delete the file again.

**Comment by DavidTWynn** [comment] 2024-04-23 20:01
I am running into this issue too where I would like to use the top level name: in my docker compose file to set the compose project name. .env is not enough because I would like it to be changed by another environment variable. I can do this is a compose file but not .env.

**Comment by Superskyyy** [comment] 2024-04-24 13:37
> The above "initializeCommand" trick creating `.env` seems not working anymore #7377

https://github.com/microsoft/vscode-remote-release/issues/7377#issuecomment-1315348288 according to this comment it should be back to working again.

**Comment by DavidTWynn** [comment] 2024-04-24 13:49
Yes I was able to use the initilizeCommand and postCreateCommand to do what I need as a work around. The difference for me was I already had a .env so needed to append to it, then remove just the line that was changed.

Hoping this will be fixed in the future by respecting the top-level name: in a docker compose file.

**Comment by Superskyyy** [comment] 2024-04-25 06:14
I didn't use initializeCommand because our use case demand each user to fully isolate with other user's containers, so I wrote up a similar script like the previous suggested code, the idea is to replace the container_name and generate a .env file (project_name) with `make devcontainer`. One small inconvenience is that we need to dynamically assemble and gitignore the docker compose file, otherwise container name still will be accidentally checked into git if not careful. Can also solve with a pre-commit hook.

**Comment by Superskyyy** [comment] 2024-04-28 06:47
I'm surprised that it will not use the docker compose .env file in the .devcontainer folder, instead it has to be at the root of the project. So I need to programatically create two  .envs.. which is not a good looking solution.

**Comment by chrmarti** [comment] 2024-05-03 06:49
> I'm surprised that it will not use the docker compose .env file in the .devcontainer folder, instead it has to be at the root of the project. So I need to programatically create two .envs.. which is not a good looking solution.

It needs to be next to the docker-compose.yml. This is given by Docker Compose: https://docs.docker.com/compose/environment-variables/set-environment-variables/

**Comment by chrmarti** [comment] 2024-05-03 16:37
Fixing by adding support for the name attribute in the compose file.

**Closed by chrmarti** 2024-05-03 16:37 UTC
Labels: containers, feature-request

**Comment by zsteinkamp** [comment] 2024-05-03 18:23
Thank you @chrmarti! I will feel the benefit of this improvement many times over!

**Comment by chrmarti** [comment] 2024-05-07 18:02
This is now available with Dev Containers 0.365.0-pre-release. Let us know if it works (or doesn't!) for you, thanks!

**Comment by DavidTWynn** [comment] 2024-05-07 18:12
Yes that worked for me. I tried it out yesterday and it didn’t but now it does. Making sure there is no environment variable, I see the “docker compose ls” project name was changed with the name value in docker compose. 

I updated my dev container extension to the newest release, removed the initializeCommand and postCreateCommand from devcontainer.json that setup the old environment variable, I then added the top level name attribute to docker-compose.yml, deleted the old compose instance and container then with vscode rebuild the container and compose environment.

**Comment by sliekens** [comment] 2024-06-11 15:23
It works for me. PS: don't forget to update https://code.visualstudio.com/remote/advancedcontainers/set-docker-compose-project-name.

**Comment by chrmarti** [comment] 2024-06-13 09:08
@sliekens Thanks, updating the docs here: https://github.com/microsoft/vscode-docs/pull/7377

We automatically use `docker compose` when there is no `docker-compose` and with Docker Desktop `docker-compose` just forwards to `docker compose`. Azure Pipelines seems to be in the process of removing v1: https://github.com/actions/runner-images/issues/9557.
