### ISSUE TITLE
Docker in WSL2 - Unable to start container development.

### ISSUE THREAD

**Issue by mrbrownt** [microsoft/vscode-remote-release#3472] opened 2020-08-04 22:03 UTC
- VSCode Version: 1.47.3
- Local OS Version: Windows 10 2004 20180.1000
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: Docker & WSL2
- Docker for Windows Version: 2.3.4.0

Steps to Reproduce:

1. In WSL2 open a project with a devcontainer configuration, specifically within the WSL2 file system, i.e. `/home/$USER/project`
2. Open in Remote Window -> Remote Containers: Reopen in Container

Docker WSL Integration has been enabled for the WSL2 distro and works fine outside of the context of vscode.

Logs when opening:
```
[15 ms] Start: Resolving remote
[16 ms] Setting up container for folder or workspace: \\wsl\Ubuntu\home\mrbrownt\Projects\gitlab.com\appliedsystems\us-rating\silk-react-components

[108 ms] Start: Check Docker is running
[108 ms] Start: Run: docker info
[405 ms] Start: Run: docker-compose version --short
[867 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=silk-react-components_devcontainer --filter label=com.docker.compose.service=node
[1005 ms] Start: Run: docker-compose -f \\wsl\Ubuntu\home\mrbrownt\Projects\gitlab.com\appliedsystems\us-rating\silk-react-components\.devcontainer\docker-compose.yml config --services
[1606 ms] node
[1607 ms] 
[1607 ms] Start: Run: docker events --format {{json .}} --filter status=start
[1613 ms] Start: Run: docker-compose --project-name silk-react-components_devcontainer -f \\wsl\Ubuntu\home\mrbrownt\Projects\gitlab.com\appliedsystems\us-rating\silk-react-components\.devcontainer\docker-compose.yml up -d --build
Creating silk-react-components_devcontainer_node_1 ... error

ERROR: for silk-react-components_devcontainer_node_1  Cannot create container for service node: \\wsl\Ubuntu\home\mrbrownt\Projects\gitlab.com\appliedsystems\us-rating\silk-react-compo
nents%!(EXTRA string=is not a valid Windows path)

ERROR: for node  Cannot create container for service node: \\wsl\Ubuntu\home\mrbrownt\Projects\gitlab.com\appliedsystems\us-rating\silk-react-components%!(EXTRA string=is not a valid W
indows path)
ERROR: Encountered errors while bringing up the project.
[2372 ms] Command failed: docker-compose --project-name silk-react-components_devcontainer -f \\wsl\Ubuntu\home\mrbrownt\Projects\gitlab.com\appliedsystems\us-rating\silk-react-components\.devcontainer\docker-compose.yml up -d --build
```

**Comment by chrmarti** [comment] 2020-08-05 10:02
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/3430.

**Closed by chrmarti** 2020-08-05 10:02 UTC
Labels: containers
