### ISSUE TITLE
"Remove" action should go last

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1288] opened 2019-08-27 23:33 UTC
Testing microsoft/vscode-internalbacklog#772

I think the `x` action should be the last one to the right, to match what some other tree views with actions do. Not a big deal but it just feels right since it's the most destructive button.

**Comment by alexr00** [comment] 2019-08-28 07:53
Done! Duplicate of #1273

**Closed by alexr00** 2019-08-28 07:53 UTC
Labels: *duplicate
