### ISSUE TITLE
vscode does not run from command line - invalid argument

### ISSUE THREAD

**Issue by pgrudzien12** [microsoft/vscode-remote-release#10378] opened 2024-10-10 07:42 UTC
Type: <b>Bug</b>

After latest update I cannot run `code .` command from wsl shell. I get the following error:
```
pawel@WINAPMvruz0v6T1:~/code/deepsearch/code/notebooks$ code .
/mnt/c/Users/pawel.grudzien/AppData/Local/Programs/Microsoft VS Code/Code.exe: Invalid argument
                                                                                               
```

Extension version: 0.88.4
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.35GB (7.24GB free)|
|Process Argv|--crash-reporter-id 61358820-83b1-45ae-b97f-9213bc77cc4d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 0)|
|Memory (System)|15.30GB (12.63GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 0)|
|Memory (System)|15.30GB (12.63GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
5fd0e150:31155592

```

</details>

**Comment by aeschli** [comment] 2024-10-22 07:36
Duplicate of https://github.com/microsoft/WSL/issues/6170

Normally running `wsl --shutdown` fixes the issue.

**Closed by aeschli** 2024-10-22 07:36 UTC

**Comment by aeschli** [comment] 2024-10-22 07:41
Also see https://github.com/microsoft/vscode-remote-release/issues/7050
Verify that you don't run VS Code as Admin.
