### ISSUE TITLE
Remote session fails to connect with ProxyJump

### ISSUE THREAD

**Issue by bymet** [microsoft/vscode-remote-release#386] opened 2019-05-20 18:21 UTC
Issue Type: <b>Bug</b>

1. Add ssh config file with next structure
```
Host jump
  User <jump-user-name>
  HostName <jump-ip-address>

Host server
  User <user-name>
  HostName <ip-address>
  ProxyJump jump
```

2. Select server throught VSCode-Inseder UI
3. Get next error message
```
Can't connect to server: unreachable or not Linux x86_64 (posix_spawn: No such file or directory)
```

Extension version: 0.37.0
VS Code version: Code - Insiders 1.35.0-insider (a5536b8f5a16a10d859f3dec1e59701671bf069e, 2019-05-20T05:17:36.269Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3900)|
|Memory (System)|15.89GB (5.15GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment] 2019-05-21 22:42
Can you share the log from the "Remote - SSH" output channel?

**Comment by bymet** [comment] 2019-05-22 08:28
Confirming that mobyedge-server is a valid reachable host
Running type "C:\Users\STANIS~1.TES\AppData\Local\Temp\vscode-linux-multi-line-command-mobyedge-server.sh" | ssh  mobyedge-server to confirm the host platform
> 
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> CreateProcessW failed error:2
> posix_spawn: No such file or directory
> 
"uname" terminal command done
mobyedge-server: unreachable or not Linux x86_64. (posix_spawn: No such file or directory)

**Comment by bymet** [comment] 2019-05-22 08:36
Also good to mention that same ssh configuration works fine inside WSL

**Comment by roblourens** [comment] 2019-05-22 19:54
And if you type `ssh  mobyedge-server` in a command prompt, that works? Is it possible that `ssh` is not on your path in vscode?

**Comment by bymet** [comment] 2019-05-23 10:16
It works fine inside bash/WSL, but fails inside powershell/cmd

**Comment by bymet** [comment] 2019-05-23 16:04
Looks like some thing wrong with ssh itself on windows

**Comment by roblourens** [comment] 2019-05-23 18:45
Oh, it sounds like linux ssh is on your path, not windows ssh.

**Comment by roblourens** [comment] 2019-05-23 18:46
I think this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/359 then.

**Closed by roblourens** 2019-05-23 18:46 UTC
Labels: needs-more-info, ssh

**Comment by pd93** [comment] 2019-05-30 15:07
@roblourens. I don't think this is a dupl. of #359. This happens to me when the only installed version of OpenSSH is the Powershell one.

I'm fairly sure it *is* however, a dupl. of #18. I would appreciate if you could take a look at the comments over there. I believe this may be caused by https://github.com/PowerShell/Win32-OpenSSH/issues/1172, which has been open for quite some time. This seems like a pretty big limitation of SSH in Windows.

**Comment by bymet** [comment] 2019-05-30 15:12
@roblourens, Recently I installed [next](https://chocolatey.org/packages/openssh) version of ssh. Right now everything works fine. So yes, looks like it's issue with ssh itself.

**Comment by roblourens** [comment] 2019-05-30 16:53
Thanks for bringing https://github.com/PowerShell/Win32-OpenSSH/issues/1172 to my attention. That does sound like a serious issue.
