### ISSUE TITLE
Symlinks break the container build process

### ISSUE THREAD

**Issue by nikrolls** [microsoft/vscode-remote-release#3437] opened 2020-07-28 22:38 UTC
- VSCode Version: 1.47.3 
- Local OS Version: Windows 10 2004 (insider build 20175)
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker (Docker Desktop Community 2.3.0.4 using WSL2 engine)

Steps to Reproduce:

1. Create a project structure like so:
```json
# .devcontainer.json
{
  "context": ".",
  "dockerFile": "Dockerfile",
}
```
```sh
# Dockerfile
FROM alpine:latest # or any other distro
```
2. Create a symlinked file:
```
$ touch test
$ ln -s test test-link
```
3. Rebuild and reopen in container

**Expected outcome:** a successful build
**Actual outcome:** a failed build with a `tar` error:
```
[770 ms] Start: Resolving remote
[837 ms] Setting up container for folder or workspace: \\wsl\Ubuntu\home\test

[1510 ms] Start: Run: git rev-parse --show-toplevel
[1574 ms] Start: Check Docker is running
[1574 ms] Start: Run: docker info
[7651 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl\Ubuntu\home\test --filter label=vsch.quality=stable
[11001 ms] Start: Run: docker build -f \\wsl\Ubuntu\home\test\Dockerfile -t vsc-test-8c159f332c7bb180f37fb1b8077b24ff \\wsl\Ubuntu\home\test
time="2020-07-29T10:29:41+12:00" level=error msg="Can't add file \\\\?\\UNC\\wsl\\Ubuntu\\home\\test\\test-link to tar: open \\\\?\\UNC\\wsl\\Ubuntu\\home\\test\\test-link: The system cannot find the path specified."
time="2020-07-29T10:29:41+12:00" level=error msg="Can't close tar writer: archive/tar: missed writing 4 bytes"
Sending build context to Docker daemon  3.072kB
Error response from daemon: Error processing tar file(exit status 1): unexpected EOF
[18512 ms] Command failed: docker build -f \\wsl\Ubuntu\home\test\Dockerfile -t vsc-test-8c159f332c7bb180f37fb1b8077b24ff \\wsl\Ubuntu\home\test
```
Same result with VS Code Insider 1.48.0-insider (slightly different path structure due to opening from a WSL mount):
```
[167 ms] Start: Resolving remote
[169 ms] Setting up container for folder or workspace: u:\home\test

[836 ms] Start: Run: git rev-parse --show-toplevel
[904 ms] Start: Check Docker is running
[906 ms] Start: Run: docker info
[6056 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=u:\home\test --filter label=vsch.quality=insider
[9354 ms] Start: Run: docker build -f u:\home\test\Dockerfile -t vsc-test-1f8d477a94798a90421fc6fa08b116d0 u:\home\test
time="2020-07-29T10:35:19+12:00" level=error msg="Can't add file \\\\?\\U:\\home\\test\\test-link to tar: open \\\\?\\U:\\home\\test\\test-link: The system cannot find the path specified."
time="2020-07-29T10:35:19+12:00" level=error msg="Can't close tar writer: archive/tar: missed writing 4 bytes"
Sending build context to Docker daemon  3.072kB
Error response from daemon: Error processing tar file(exit status 1): unexpected EOF
[11871 ms] Command failed: docker build -f u:\home\test\Dockerfile -t vsc-test-1f8d477a94798a90421fc6fa08b116d0 u:\home\test
```
4. Change the symlink to a hardlink:
```sh
$ ln -f test test-link
```
5. Rebuild and reopen in container

**Outcome:** a successful build

This may be an issue with the extension, the current Windows Insider build, or with the Docker for Windows build; it's hard to tell. As I receive updates for these components I'll update the ticket with my results.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment] 2020-07-30 07:38
Might be a duplicate of #3430.

**Comment by nikrolls** [comment] 2020-07-30 07:53
I'm experiencing #3430 as well - I think they're different issues but may very well be the same bug in the build causing them.

**Comment by nikrolls** [comment] 2020-08-03 23:27
FYI, this issue is still present in the latest Windows Insider dev build (build 20180), with the latest versions of Code, Code Insiders, and extensions. This is to be expected as this build was just 20175 plus the latest production fixes updates.

**Comment by chrmarti** [comment] 2020-08-04 08:01
@nikrolls Could you retry with the latest Remote-Containers 0.131.0?

**Comment by nikrolls** [comment] 2020-08-05 03:35
@chrmarti There's no error now, but it just hangs indefinitely on the `docker build` step:
```sh
[63 ms] Start: Resolving remote
[67 ms] Start: Run: wsl -d Ubuntu -e wslpath -u \\wsl\Ubuntu\home\test
[941 ms] Start: Run: wsl 
[959 ms] Start: Run in container: printenv ; exit
[1309 ms] SHELL=/bin/bash
WSL_DISTRO_NAME=Ubuntu
PWD=/mnt/c/Users/test/AppData/Local/Programs/Microsoft VS Code Insiders
LOGNAME=test
HOME=/home/test
LANG=C.UTF-8
WSL_INTEROP=/run/WSL/2288_interop
TERM=xterm-256color
USER=test
SHLVL=1
WSLENV=
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/test/bin:/home/test/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/test/.windows-build-tools/python27/:/mnt/c/Users/test/AppData/Local/nvs/node/11.0.0/x64/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/test/AppData/Local/nvs/default/node_modules/windows-build-tools/node_modules/.bin:/mnt/c/Users/test/AppData/Local/nvs/default/node_modules/.bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/test/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/test/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/OpenSSL-Win64/bin:/mnt/c/Users/test/AppData/Local/Programs/Fiddler:/mnt/c/Users/test/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/test/.dotnet/tools:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Users/test/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/snap/bin
HOSTTYPE=x86_64
_=/usr/bin/printenv
[1310 ms] 
[1310 ms] Setting up container for folder or workspace: /home/test

[1673 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/test' && test '-f' '/home/test/.devcontainer/devcontainer.json'
[2022 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/test' && test '-f' '/home/test/.devcontainer.json'
[2316 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/test' && cat '/home/test/.devcontainer.json'
[2624 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/test' && git 'rev-parse' '--show-toplevel'
[3060 ms] Start: Check Docker is running
[3061 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/test' && docker 'info'
[5007 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/test' && docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl\Ubuntu\home\test' '--filter' 'label=vsch.quality=insider'
[5578 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/test' && cat '/home/test/Dockerfile'
[6239 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/test' && docker 'build' '-f' '/home/test/Dockerfile' '-t' 'vsc-test-a07210afcea2a9fa8775a9c25f8f10b6' '/home/test'
```

**Comment by chrmarti** [comment] 2020-08-05 09:24
Is there much else in `/home/test`? `docker build` first uploads the context folder to the daemon, maybe that takes long?

I thought I reproduced in on Mac, but don't see it anymore after running the `docker build` command from a terminal. Tried getting back to it using `docker system prune --all` (careful with that command) without luck.

**Comment by nikrolls** [comment] 2020-08-05 09:43
The only files are the ones listed in the reproduction steps: the `.devcontainer.json` file, the empty test file, and the symlink.

**Comment by chrmarti** [comment] 2020-08-06 12:33
Can you run the build step manually?

**Comment by nikrolls** [comment] 2020-08-06 21:15
Apologies @chrmarti, I had done that for previous tests but forgot to for this one.

I see that this version is accessing WSL directly rather than going through Docker for Windows. Personally I think that's a positive step 🙂

So the issue with hanging may be to do with my specific installation - so I tried on a new WSL2 distro and it builds OK. There's a new error now, I'm not sure if it's related to this issue or #3430.
```sh
[2020-08-06T21:07:01.526Z] [PID 5252] [54 ms] Start: Resolving remote
[2020-08-06T21:07:01.528Z] [PID 5252] [56 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl\Ubuntu-20.04\home\test\repro
[2020-08-06T21:07:01.908Z] [PID 5252] [436 ms] Start: Run: wsl 
[2020-08-06T21:07:01.917Z] [PID 5252] [445 ms] Start: Run in container: printenv ; exit
[2020-08-06T21:07:02.109Z] [PID 5252] [637 ms] SHELL=/bin/bash
WSL_DISTRO_NAME=Ubuntu
PWD=/mnt/c/Users/test/AppData/Local/Programs/Microsoft VS Code Insiders
LOGNAME=test
HOME=/home/test/repro
LANG=C.UTF-8
WSL_INTEROP=/run/WSL/4431_interop
TERM=xterm-256color
USER=test
SHLVL=1
WSLENV=
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/test/repro/bin:/home/test/repro/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/test/.windows-build-tools/python27/:/mnt/c/Users/test/AppData/Local/nvs/node/11.0.0/x64/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/test/AppData/Local/nvs/default/node_modules/windows-build-tools/node_modules/.bin:/mnt/c/Users/test/AppData/Local/nvs/default/node_modules/.bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/test/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/test/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/OpenSSL-Win64/bin:/mnt/c/Users/test/AppData/Local/Programs/Fiddler:/mnt/c/Users/test/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/test/.dotnet/tools:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Users/test/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/snap/bin
HOSTTYPE=x86_64
_=/usr/bin/printenv
[2020-08-06T21:07:02.109Z] [PID 5252] [637 ms] 
[2020-08-06T21:07:02.110Z] [PID 5252] [638 ms] Setting up container for folder or workspace: /home/test/repro


[2020-08-06T21:07:02.398Z] [PID 5252] [926 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && test '-f' '/home/test/repro/.devcontainer/devcontainer.json'
[2020-08-06T21:07:02.650Z] [PID 5252] [1178 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && test '-f' '/home/test/repro/.devcontainer.json'
[2020-08-06T21:07:02.978Z] [PID 5252] [1506 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && cat '/home/test/repro/.devcontainer.json'
[2020-08-06T21:07:03.530Z] [PID 5252] [2058 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && git 'rev-parse' '--show-toplevel'
[2020-08-06T21:07:04.015Z] [PID 5252] [2543 ms] Start: Check Docker is running
[2020-08-06T21:07:04.015Z] [PID 5252] [2543 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker 'info'
[2020-08-06T21:07:05.196Z] [PID 5252] [3724 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl\Ubuntu-20.04\home\test\repro' '--filter' 'label=vsch.quality=insider'
[2020-08-06T21:07:06.898Z] [PID 5252] [5426 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && cat '/home/test/repro/Dockerfile'
[2020-08-06T21:07:07.183Z] [PID 5252] [5711 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker 'build' '-f' '/home/test/repro/Dockerfile' '-t' 'vsc-repro-bc6d005968afde792502d9b3be1faf63' '/home/test/repro'
[2020-08-06T21:07:07.527Z] [PID 5252] 
[2020-08-06T21:07:08.002Z] [PID 5252] Sending build context to Docker daemon  4.096kB
[2020-08-06T21:07:08.097Z] [PID 5252] Step 1/1 : FROM alpine:latest
 ---> a24bb4013296
Successfully built a24bb4013296
[2020-08-06T21:07:08.133Z] [PID 5252] Successfully tagged vsc-repro-bc6d005968afde792502d9b3be1faf63:latest
[2020-08-06T21:07:08.135Z] [PID 5252] [6663 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker 'inspect' '--type' 'image' 'vsc-repro-bc6d005968afde792502d9b3be1faf63'
[2020-08-06T21:07:08.675Z] [PID 5252] [7203 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker '-v'
[2020-08-06T21:07:09.242Z] [PID 5252] [7770 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker 'events' '--format' '{{json .}}' '--filter' 'status=start'
[2020-08-06T21:07:09.250Z] [PID 5252] [7778 ms] Start: Starting container
[2020-08-06T21:07:09.250Z] [PID 5252] [7778 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker 'run' '-a' 'STDOUT' '-a' 'STDERR' '--mount' 'type=bind,source=/home/test/repro,target=/workspaces/test' '-l' 'vsch.quality=insider' '-l' 'vsch.remote.devPort=0' '-l' 'vsch.local.folder=\\wsl\Ubuntu-20.04\home\test\repro' '--entrypoint' '/bin/sh' 'vsc-repro-bc6d005968afde792502d9b3be1faf63' '-c' 'echo Container started ; trap "exit 0" 15; while sleep 1 & wait $!; do :; done'
[2020-08-06T21:07:09.594Z] [PID 5252] 
[2020-08-06T21:07:11.703Z] [PID 5252] docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.
ERRO[0001] error waiting for container: context canceled
[2020-08-06T21:07:11.734Z] [PID 5252] [10262 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl\Ubuntu-20.04\home\test\repro' '--filter' 'label=vsch.quality=insider'
[2020-08-06T21:07:12.327Z] [PID 5252] [10855 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/test/repro' && docker 'inspect' '--type' 'container' 'e6889583b696'
[2020-08-06T21:07:12.824Z] [PID 5252] [11352 ms] Command failed: docker run -a STDOUT -a STDERR --mount type=bind,source=/home/test/repro,target=/workspaces/test -l vsch.quality=insider -l vsch.remote.devPort=0 -l vsch.local.folder=\\wsl\Ubuntu-20.04\home\test\repro --entrypoint /bin/sh vsc-repro-bc6d005968afde792502d9b3be1faf63 -c echo Container started ; trap "exit 0" 15; while sleep 1 & wait $!; do :; done
```

**Comment by PavelSosin-320** [comment] 2020-08-07 08:18
Hopefully, the default of tar --one-file-system is false, but when I faced such an issue I didn't find the proper documentation except [tar cross file system meaning](https://unix.stackexchange.com/questions/107113/meaning-of-crossing-filesystem-boundaries-one-file-system-etc)

**Comment by nikrolls** [comment] 2020-08-17 08:16
This issue appears to be resolved in the following environment:

* VSCode Version: 1.48.0 / Remote - Containers: 0.134.0
* Local OS Version: Windows 10 2004 (insider build 20190)
* Remote OS Version: Ubuntu 20.04
* Remote Extension/Connection Type: Docker (Docker Desktop Community 2.3.0.4 using WSL2 engine)

#3430 also seems to be resolved in this configuration.

**Comment by chrmarti** [comment] 2020-08-17 13:38
Thanks, closing as fixed.

**Closed by chrmarti** 2020-08-17 13:38 UTC
Labels: bug, containers
