### ISSUE TITLE
[error] Error: Extension 'ms-vscode.remote-explorer' CANNOT use API proposal: extensionsAny.

### ISSUE THREAD

**Issue by soraclub** [microsoft/vscode-remote-release#7194] opened 2022-09-15 09:37 UTC
- VSCode Version:  1.71.1
- Local OS Version: win10
- Remote OS Version: centos7.4
- Remote Extension/Connection Type: SSH
- Logs:

`[2022-09-15 17:02:28.140] [exthost] [error] Activating extension ms-vscode.remote-explorer failed due to an error:
[2022-09-15 17:02:28.140] [exthost] [error] Error: Extension 'ms-vscode.remote-explorer' CANNOT use API proposal: extensionsAny.
Its package.json#enabledApiProposals-property declares: contribViewsRemote but NOT extensionsAny.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode.remote-explorer
    at g (c:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:68142)
    at Object.get allAcrossExtensionHosts [as allAcrossExtensionHosts] (c:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:34914)
    at t (c:\Users\guanz\.vscode\extensions\ms-vscode.remote-explorer-0.1.2022091309\dist\node\extension.js:1:56743)
    at new t.RemoteTreeDataProvider (c:\Users\guanz\.vscode\extensions\ms-vscode.remote-explorer-0.1.2022091309\dist\node\extension.js:1:57085)
    at t.activate (c:\Users\guanz\.vscode\extensions\ms-vscode.remote-explorer-0.1.2022091309\dist\node\extension.js:1:61466)
    at Function._callActivateOptional (c:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:17649)
    at Function._callActivate (c:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:17307)
    at c:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:15118
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at E._activate (c:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8224)
    at E._waitForDepsThenActivate (c:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8166)
    at E._initialize (c:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7530)`

Steps to Reproduce:

1. just launch VSCode

**Comment by Azero-NG** [comment] 2022-09-16 08:48
- VSCode Version: 1.71.2
- Local OS Version: Macos 12.6 (21G115)
- Remote OS Version: Debian 9.13
- kernel version: 4.14.81.bm.29
- Remote Extension/Connection Type: SSH
- log:
[2022-09-16 11:40:53.807] [exthost] [error] Activating extension ms-vscode.remote-explorer failed due to an error:
[2022-09-16 11:40:53.807] [exthost] [error] Error: Extension 'ms-vscode.remote-explorer' CANNOT use API proposal: extensionsAny.
Its package.json#enabledApiProposals-property declares: contribViewsRemote but NOT extensionsAny.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode.remote-explorer
	at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:68142)
	at get allAcrossExtensionHosts [as allAcrossExtensionHosts] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:34914)
	at t (/Users/azero/.vscode/extensions/ms-vscode.remote-explorer-0.1.2022091309/dist/node/extension.js:1:56743)
	at new t.RemoteTreeDataProvider (/Users/azero/.vscode/extensions/ms-vscode.remote-explorer-0.1.2022091309/dist/node/extension.js:1:57085)
	at t.activate (/Users/azero/.vscode/extensions/ms-vscode.remote-explorer-0.1.2022091309/dist/node/extension.js:1:61466)
	at Tn._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17649)
	at Tn._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17307)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:15118
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async E._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8224)
	at async E._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8166)
	at async E._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7530)

**Comment by soraclub** [comment] 2022-09-16 09:36
I append "extensionsAny" to  "extensionEnabledApiProposals"."ms-vscode.remote-explorer"  in "C:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\product.json", then the explorer works well. 
Is this a problem of vscode itself ?

```
{
...
  "extensionEnabledApiProposals": {
 ...
  "ms-vscode.remote-explorer": [
	"contribViewsRemote",
	"extensionsAny" // added
    ],
}
```

**Comment by vuuihc** [comment] 2022-09-21 04:36
版本: 1.71.2 (Universal)
提交: 74b1f979648cc44d385a2286793c226e611f59e7
日期: 2022-09-14T21:05:37.721Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.3.0
沙盒化: No
<img width="706" alt="image" src="https://user-images.githubusercontent.com/3747378/191415332-32344ea5-9011-4f53-a695-10e193f87e11.png">

**Comment by eleanorjboyd** [comment] 2022-09-23 20:38
Hello! Could you list the version of your remote-explorer extension? You can find this by going to the `extensions` tab then searching for `remote explorer` in the marketplace and the version should be listed to the right of the extension name after you click on the search result and would look something like: v0.1.2022091309
![Screen Shot 2022-09-23 at 1 37 32 PM](https://user-images.githubusercontent.com/26030610/192052755-eeea3cae-c7d8-4eaa-9d1a-b85b0190798f.png)

**Comment by soraclub** [comment] 2022-09-26 10:09
> Hello! Could you list the version of your remote-explorer extension? You can find this by going to the `extensions` tab then searching for `remote explorer` in the marketplace and the version should be listed to the right of the extension name after you click on the search result and would look something like: v0.1.2022091309 ![Screen Shot 2022-09-23 at 1 37 32 PM](https://user-images.githubusercontent.com/26030610/192052755-eeea3cae-c7d8-4eaa-9d1a-b85b0190798f.png)

yes，the version is exactly "v0.1.2022091309" in my VSCode

**Comment by gtpalmer** [comment] 2022-09-26 10:15
> I append "extensionsAny" to "extensionEnabledApiProposals"."ms-vscode.remote-explorer" in "C:\Users\guanz\AppData\Local\Programs\Microsoft VS Code\resources\app\product.json", then the explorer works well. Is this a problem of vscode itself ?
> 
> ```
> {
> ...
>   "extensionEnabledApiProposals": {
>  ...
>   "ms-vscode.remote-explorer": [
> 	"contribViewsRemote",
> 	"extensionsAny" // added
>     ],
> }
> ```

I had the same exact issue and this solution also worked for me.

**Comment by NicolasGoeddel** [comment] 2022-10-11 18:23
Where can I find `product.json` on Linux because I got the same issue here. There is no `product.json` anywhere in my `$HOME/.vscode` directory.

**Comment by eleanorjboyd** [comment] 2022-10-12 16:25
Hello- can someone verify if this is fixed? We pushed a fix two days ago on the most recent version of remote-explorer.

**Comment by suzakuwcx** [comment] 2022-11-13 01:28
- OS: archlinux
- Code-oss version: 1.73.0  , 8fa188b2b301d36553cbc9ce1b0a146ccb93351f , x86
- All extension are newest

No, problems still exist, the problem is appear after upgrading all extension to newest version, (old version is about half a years ago, specific version number is missing)

here is the log, and open vscode with "--enable-proposed-api ms-vscode.remote-explorer" append can have a temporarily solve :

> CRITI Extension 'ms-vscode.remote-explorer CANNOT USE these API proposals 'contribViewsRemote, extensionsAny'. You MUST start in extension development mode or use the --enable-proposed-api command line flag

![image](https://user-images.githubusercontent.com/73207484/201500881-a56af05c-48fa-42be-a731-d6d9f5062a73.png)

> Where can I find `product.json` on Linux because I got the same issue here. There is no `product.json` anywhere in my `$HOME/.vscode` directory.

@NicolasGoeddel , the product.json may locate at /usr/lib/code/product.json if installing in system directory

**Closed** 2022-12-01 15:38 UTC
Labels: ssh, info-needed

**Comment by braydonk** [comment] 2022-12-12 20:06
This has started happening to me on the latest version of the extension, pre-release, and a version from 3 weeks ago.

Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:26.920Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.18.16-1rodete4-amd64 <---- This means Rolling Debian Testing
Sandboxed: No

**Comment by eleanorjboyd** [comment] 2022-12-13 18:30
@braydonk could you send your remote-ssh logs and the logs from your dev tools?

**Comment by braydonk** [comment] 2022-12-13 19:28
Here are the logs from my dev tools.
```
﻿﻿Error: Extension 'ms-vscode.remote-explorer' CANNOT use API proposal: localization.
Its package.json#enabledApiProposals-property declares: contribViewsRemote, extensionsAny but NOT localization.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode.remote-explorer
    at f (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:54344)
    at Object.t (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:54813)
    at t.explorerFolderSortOrder (vscode-file://vscode-app/home/braydonk/.vscode/extensions/ms-vscode.remote-explorer-0.0.3/dist/node/extension.js:2:420597)
    at t.RemoteTreeDataProvider.getChildren (vscode-file://vscode-app/home/braydonk/.vscode/extensions/ms-vscode.remote-explorer-0.0.3/dist/node/extension.js:2:413779)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at v.fetchChildrenNodes (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:21066)
    at v.getChildren (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:16693)
onDidChangeNotification @ notificationsAlerts.ts:40
```
This error always appears when I try to open the Remote Development pane from the Primary Side Bar.

I am not sure how to get remote-ssh logs; I didn't find any instructions for that in `CONTRIBUTING.md`, is there somewhere else I should look?

**Comment by eleanorjboyd** [comment] 2022-12-13 20:14
@braydonk, thank you so much for sending this over! This actually should give us all the information we need to make this fix so no need to get the remote-ssh logs, apologies for not providing instructions there. We will get back to you with updates, thanks!

**Comment by eleanorjboyd** [comment] 2022-12-13 20:15
@braydonk also if you do get stuck in the future with remote-ssh here is a new troubleshooting wiki we have created in case it could be helpful next time! https://github.com/microsoft/vscode-remote-release/wiki/Debugging-for-Remote-SSH

**Comment by roblourens** [comment] 2022-12-13 21:16
@braydonk looks like you're on an old version of vscode, please update

> Version: 1.72.2

you may not get the latest version of extensions unless you're on the latest vscode, this should be fixed in the latest

**Comment by braydonk** [comment] 2022-12-13 21:33
Ah okay, that's tricky since my organization controls which version of VSCode we're on, so I only get updates once they decide. Is there an old version of the remote extension I could install manually that may still work on version 1.72.2?

**Comment by roblourens** [comment] 2022-12-13 21:45
You can try an old version of remote-ssh (an older version won't depend on remote-explorer).

0.84 for example should work
