### ISSUE TITLE
Unable to install extension - not compatible with VS Code '1.56.2'.

### ISSUE THREAD

**Issue by illbebach** [microsoft/vscode-remote-release#5147] opened 2021-06-06 02:10 UTC
> Version: 1.56.2
> Commit: 054a9295330880ed74ceaedda236253b4f39a335
> Date: 2021-05-12T16:45:26.313Z
> Electron: 12.0.4
> Chrome: 89.0.4389.114
> Node.js: 14.16.0
> V8: 8.9.255.24-electron.0
> OS: Linux x64 5.8.0-55-generic

remote ssh will not install in offline mode on Ubuntu.

Steps to Reproduce:

```
$ code --install-extension ms-vscode-remote.remote-ssh-0.65.6.vsix
Installing extensions...
Unable to install extension 'ms-vscode-remote.remote-ssh' as it is not compatible with VS Code '1.56.2'.
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment] 2021-06-07 23:51
The version of the client and server must match. Closing as I believe this is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/1242. If I've misunderstood the request here, please just let me know. Thanks!

**Closed by bamurtaugh** 2021-06-07 23:51 UTC
Labels: ssh
