### ISSUE TITLE
markdown preivew not load image

### ISSUE THREAD

**Issue by xu-wang11** [microsoft/vscode-remote-release#392] opened 2019-05-21 04:07 UTC
- VSCode Version: Version 1.35.0-insider 
- Local OS Version: macoOS Mojave 10.14.4
- Remote OS Version:  CentOS 6.8
- Remote Extension/Connection Type: SSH

As the title says.

**Comment by mjbvz** [comment] 2019-05-21 05:27
Duplicate of #376

**Closed by mjbvz** 2019-05-21 05:27 UTC
