### ISSUE TITLE
Unfriendly error when using a full github url

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#1541] opened 2019-10-01 12:27 UTC
Testing https://github.com/microsoft/vscode-remote-release/issues/1515

Path used: https://github.com/chrisdias/myUsefulSite

Error:
![image](https://user-images.githubusercontent.com/38270282/65962167-5f61a300-e458-11e9-8f7e-8eb16a2609b5.png)

From the terminal: 
```
Cloning Github repository:  into volume vsc--ed2abd62588d75a5f761af364a76275d
Run: docker run --rm --mount src=vsc--ed2abd62588d75a5f761af364a76275d,dst=,type=volume,volume-driver=local alpine/git clone https://github.com/chrisdias/myUsefulSite 
invalid argument "src=vsc--ed2abd62588d75a5f761af364a76275d,dst=,type=volume,volume-driver=local" for "--mount" flag: target is required
See 'docker run --help'.
```

**Comment by egamma** [comment] 2019-10-03 08:55
Duplicate of #1557.

**Closed by egamma** 2019-10-03 08:55 UTC
Labels: bug, containers
