### ISSUE TITLE
lose connection when delete lots of files by vscode ssh

### ISSUE THREAD

**Issue by NickLiu635** [microsoft/vscode-remote-release#5087] opened 2021-05-22 02:29 UTC
I deleted some repo ...（i think it will take hours if i deleted it by command）
after that,every window i opened lose connection again and again...

**Comment by bamurtaugh** [comment] 2021-05-26 16:50
This sounds like/related to https://github.com/microsoft/vscode-remote-release/issues/1257.

**Comment by bamurtaugh** [comment] 2021-06-07 21:56
I'm going to close as a duplicate of https://github.com/microsoft/vscode-remote-release/issues/1257. If you have any additional info to provide, please let us know. Thank you!

**Closed by bamurtaugh** 2021-06-07 21:56 UTC
Labels: ssh
