### ISSUE TITLE
SSH Remote failed to parse ssh_config with extra `Host` lines

### ISSUE THREAD

**Issue by ttimasdf** [microsoft/vscode-remote-release#3314] opened 2020-07-05 04:27 UTC
- VSCode Version: 1.46.1
- Local OS Version: Windows 10 19041
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH

I've gone through several similar issues #65 #2446 #2976 But I think this one is a bug breaking existing features.

Steps to Reproduce:

1. Create a ssh_config with several `Include` directives -- works fine.

![图片](https://user-images.githubusercontent.com/2762704/86525454-d6c9d480-beb9-11ea-8d9b-3573479f7787.png)

2. Add following lines at the end of `ssh_config` file -- still no problem.

```
Host *
    IdentitiesOnly yes
```

3. Cut these lines and prepend them at `ssh_config` start. -- everything breaks.

![图片](https://user-images.githubusercontent.com/2762704/86525481-43dd6a00-beba-11ea-9b80-71d83dbb18ed.png)

4. Change Host name to `test` , only one host still exists.

![图片](https://user-images.githubusercontent.com/2762704/86525497-71c2ae80-beba-11ea-9c8d-12e721b5a078.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment] 2022-02-08 06:53
I believe this issue is fixed now. Or I'm not able to reproduce this anymore. @ttimasdf if you still see this issue please let me know but I'm going to close this now since I'm not reproducing this.

**Closed by tanhakabir** 2022-02-08 06:53 UTC
Labels: bug, ssh
