### ISSUE TITLE
No Results = Spinning Cursor on Remote WSL with MSSQL

### ISSUE THREAD

**Issue by jeffkempster** [microsoft/vscode-remote-release#932] opened 2019-07-08 18:20 UTC
Issue Type: <b>Bug</b>

I am all of a sudden having issue with the Results window showing after executing a SQL query with the MSSQL extention.  I have been using vscode remotely with a wsl and ubuntu for a few months now, but after a recent update I can no longer see any results. The query is running fine, but nothing ever shows up.  If I open the query on the local (windows) side the results display correctly. 

I have tried to uninstall everything VSCode, mssql and reinstall but i get the same.  I am connected to the server just fine, because my intellisense is working just fine. 

Extension version: 0.38.7
VS Code version: Code - Insiders 1.37.0-insider (d50852db1af10ec100a71ad57cc3a04c8aead117, 2019-07-08T05:37:36.104Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (10.05GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+default/home/jeffk/Scratch --remote=wsl+default|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.79GB (10.05GB free)|
|VM|0%|
</details>

**Comment by jeffkempster** [comment] 2019-07-08 18:21
![image](https://user-images.githubusercontent.com/14044079/60833147-a575d600-a18b-11e9-92ca-2d10929d3268.png)

**Comment by Chuxel** [comment] 2019-08-10 13:15
Root cause appears to be #1132, so I am closing this as a dupe - but we're on it!

**Closed by Chuxel** 2019-08-10 13:15 UTC
Labels: *duplicate
