### ISSUE TITLE
Code Server doesn't work on jupyterhub/kubernetes

### ISSUE THREAD

**Issue by sa-** [microsoft/vscode-remote-release#6999] opened 2022-07-29 07:45 UTC
- VSCode Version: latest
- Local OS Version: macOS
- Remote OS Version: ubuntu
- Remote Extension/Connection Type: Server
- Logs:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/1297369/181710439-24c36539-8c10-4300-92b0-71a4d8dcfff5.png">

Steps to Reproduce:

1. Deploy jupyterhub to kubernetes
2. Add some sort of SSO (Single Sign-On) authentication to jupyterhub
3. Create a jupyter server
4. Open a terminal
5. Run `wget -O- https://aka.ms/install-vscode-server/setup.sh | sh`
6. Run `sudo chmod +x /usr/local/bin/code-server`
7. Run `code-server serve-local --without-connection-token --accept-server-license-terms`
8. Try to access VS Code and find only a blank page. There are some errors in the console

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by sa-** [comment] 2022-08-01 17:53
^The label should be for server rather than ssh

**Comment by tanhakabir** [comment] 2022-08-18 17:55
Do you have a screen recording of what you see in vscode.dev when you try to connect? Or logs from the code-server?

**Comment by sa-** [comment] 2022-08-29 06:24
Hey thanks for having a look at this.

I'm running this with the command `serve-local` so vscode.dev is not involved in this process. The only logs are in the screenshot that I provided, the `code-server` logs seem to be blank.

```
$ code-server serve-local --without-connection-token --accept-server-license-terms --log debug
[2022-08-29 08:22:16] debug Resolved quality Stable to e4503b30fc78200f846c62cf8091b76ff5547662
[2022-08-29 08:22:16] debug Installing and setting up VS Code Server...
[2022-08-29 08:22:16] info Found existing installation at /home/skapadia/.vscode-cli/server-stable-web/bin/e4503b30fc78200f846c62cf8091b76ff5547662
[2022-08-29 08:22:16] debug Server setup complete
[2022-08-29 08:22:16] info Starting server...
[2022-08-29 08:22:16] debug Starting server with command... Command { std: "/home/skapadia/.vscode-cli/server-stable-web/bin/e4503b30fc78200f846c62cf8091b76ff5547662/bin/code-server" "--host=127.0.0.1" "--port=8000" "--without-connection-token" "--accept-server-license-terms" "--log=debug", kill_on_drop: false }
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:8000 (IPv4)
Extension host agent listening on 8000

Web UI available at http://localhost:8000/
[08:22:16] Extension host agent started.
[08:22:16] ComputeTargetPlatform: linux-x64
```

**Comment by tanhakabir** [comment] 2022-08-29 17:41
@DonJayamanne any thoughts

**Comment by jiyuanq** [comment] 2022-09-08 10:14
I'm encountering the same issue. Wondering if there's any update?
Judging from the errors it looks like it's trying to load js from `/hub`, where the jupyterhub login service is, but the right path should be something like `/user/<username>/code-server/...`

**Comment by jiyuanq** [comment] 2022-09-08 11:42
I guess it’s about absolute path vs relative path. VS code is using absolute paths which points to /hub as root path

**Comment by sa-** [comment] 2022-09-08 11:55
@microsoft if I were you I would hire @jiyuanq

**Comment by jabbera** [comment] 2022-11-07 14:59
You need to use the jupyter server proxy to rewrite the url: 

https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#absolute-url

**Comment by aeschli** [comment] 2022-12-16 09:13
Duplicate of https://github.com/microsoft/vscode/issues/165391

**Closed by aeschli** 2022-12-16 09:13 UTC
Labels: info-needed, code-server
