### ISSUE TITLE
Permission denied when moving a directory to another on WSL

### ISSUE THREAD

**Issue by rodrigoestevao** [microsoft/vscode-remote-release#1245] opened 2019-08-26 02:19 UTC
Issue Type: <b>Bug</b>

I was trying to move a directory to another directory within the same parent, but I'm receiving the following error: Error: EACCES: permission denied, rename '/mnt/e/Workspace/udemy/rest-api-flask-and-python/templates' -> '/mnt/e/Workspace/udemy/rest-api-flask-and-python/section3/templates'.
I have already double checked the permissions, and everything is ok.  

![image](https://user-images.githubusercontent.com/1023380/63660960-1babb780-c78f-11e9-8ca7-7890a487971b.png)

Extension version: 0.39.2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.38GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+default/mnt/e/Workspace/udemy/rest-api-flask-and-python --remote=wsl+default|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 3000)|
|Memory (System)|15.95GB (6.38GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment] 2019-08-26 07:50
Duplicate of https://github.com/microsoft/WSL/issues/3395

pls see 'Workaround for renaming folders'  https://devblogs.microsoft.com/commandline/tips-and-tricks-for-linux-development-with-wsl-and-visual-studio-code/

**Closed by egamma** 2019-08-26 07:50 UTC
