### ISSUE TITLE
Unable to click on link after renaming port for devcontainer.json

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#4554] opened 2021-02-24 18:28 UTC
Testing #4433 with Codespaces

Version : 1.54.0-insider (user setup)
Commit : 9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea
Date : 2021-02-23T10:46:22.816Z
Electron : 11.3.0
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19042

I'm unable to click on the following link after a rename
![unable-link](https://user-images.githubusercontent.com/7199958/109047494-cbb2f700-768a-11eb-9ec6-034d30cf08a9.PNG)

**Comment by alexr00** [comment] 2021-02-25 09:52
Duplicate of https://github.com/microsoft/vssaas-planning/issues/2685

**Closed by alexr00** 2021-02-25 09:52 UTC
