### ISSUE TITLE
devcontainer.jsonを上書きしようとする

### ISSUE THREAD

**Issue by rifumi** [microsoft/vscode-remote-release#9323] opened 2023-12-18 04:45 UTC
Type: <b>Bug</b>

.devcontainer/devcontainer.jsonが存在するディレクトリをvscodeで開く
コンテナで再度開く
devcontainer.jsonがすでに存在すると言われる
続行する
上書きしますかと言われる（上書きせずに既存のdevcontainer.jsonを使ってコンテナを開く方法を教えて欲しい）。

Extension version: 0.327.0
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|18, 31, 22|
|Memory (System)|16.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id c39d037c-80e5-4ede-8ec4-4099ec5f9d8c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184c:30925681

```

</details>

**Comment by hibiki-kato** [comment] 2024-02-20 06:52
I had the same issue.
After I updated docker desktop, it was fixed.

OS:Windows11
docker desktop: 4.27.1

**Comment by hibiki-kato** [comment] 2024-02-20 07:03
The problem was as below.
Normally if there is  a .devcontainer/devcontainer.json, Dev Containers automatically runs container when we choose "Reopen in container".
However, Dev Container tried to create a new .devcontainer/devcontainer.json ignoring existing one.

**Comment by hibiki-kato** [comment] 2024-02-20 07:13
Duplicate of #9440

**Closed** 2024-03-01 02:33 UTC
Labels: containers, *english-please
