### ISSUE TITLE
Credential forwarding does not work with NTLM and does not give a warning

### ISSUE THREAD

**Issue by cmorty** [microsoft/vscode-remote-release#4226] opened 2020-12-22 15:17 UTC
Host: Windows, Code 1.52.1
Docker: Linux with WSL2, git 2.25.1
I run git using ` -c http.sslVerify=false`, as importing the Root-CA was a PITA.

On the host git authenticates using NTLM (I checked this using `GCM_TRACE=1`). Running a Docker-Container via VSCode authentication fails. If I provide my credentials on the Windows-Host using `GCM_AUTHORITY=basic git clone ....` the credentials get successfully forwarded to the Docker container.

If I understand https://github.com/microsoft/Git-Credential-Manager-Core correctly NTLM is not supported by Linux. It would however be nice to get some warning or a popup requesting my credentials.

**Comment by chrmarti** [comment] 2021-01-04 13:36
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/3702.

**Closed by chrmarti** 2021-01-04 13:36 UTC
Labels: containers
