### ISSUE TITLE
Error after updating vscode

### ISSUE THREAD

**Issue by crsuarez** [microsoft/vscode-remote-release#3553] opened 2020-08-21 18:44 UTC
We have written the needed data int
Issue Type: <b>Bug</b>

[Error - 1:42:03 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'lineComments' of undefined

Extension version: 0.44.4
VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.21GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/c/Users/.../ --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.85GB (7.21GB free)|
|VM|0%|
</details>
o your clipboard because it was too large to send. Please paste.

**Comment by ialejandro** [comment] 2020-08-24 06:14
@crsuarez yaml extension -in my case- report that error, maybe you can disable until RedHat or Microsoft fix it.

**Comment by chrmarti** [comment] 2020-08-24 08:01
Duplicate of redhat-developer/vscode-yaml#353

**Closed by chrmarti** 2020-08-24 08:01 UTC

**Comment by crsuarez** [comment] 2020-08-24 19:30
> 
> 
> @crsuarez [yaml extension](https://github.com/redhat-developer/vscode-yaml) -in my case- report that error, maybe you can disable until RedHat or Microsoft fix it.

Thank you, I did it and now is working again.

**Comment by rushi47** [comment] 2020-08-26 07:37
Was facing the same issue, Disabled as of now.

**Comment by abdennour** [comment] 2020-08-26 08:37
same issue as well this morning

**Comment by kbks** [comment] 2020-08-26 11:39
downgrade to the previous version of yaml extension helped me as well
