### ISSUE TITLE
Run docker compose file with ENV variables from WSL

### ISSUE THREAD

**Issue by amarth1982** [microsoft/vscode-remote-release#835] opened 2019-06-26 17:23 UTC
I have a compose yml like this

services:
 myservices:
  image: node:{$NODE_VERSION}

Running remote-container is failing in vscode, as NODE_VERSION env variable is defined in WSL but not in WINDOWS

I have many other ENV variables used in docker-compose.yml like this I dont want everything to be created in Windows

It would be nice to have this, so the remote-container can read the WSL env vars

Note: I also I tried using WSLENV to share my wsl env vars to windows however the scope of those vars are limited to that session

**Comment by Chuxel** [comment] 2019-06-26 17:25
This is not supported right now, but happy to add it as a feature request.

**Comment by amarth1982** [comment] 2019-06-27 14:45
Right now I get it working using
[WLSENV](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/)

added the following line to .bashrc

export WSLENV=$WSLENV:VAR_NODE_IMAGE_NAME/u:VAR_NODE_VERSION/u
cmd.exe /C  set | grep  '^VAR' | tr '=' ' ' | awk '{printf "SETX %s %s\n", $1, $2}' | cmd.exe >> /dev/null

this will add the env vars to Windows when I launch my terminal

**Comment by bmweller** [comment] 2019-07-31 22:06
This is a significant shortcoming of using a vscode's devcontainer concept. 

I'd like to be able to set up a base set of dev containers and then attach a working directory containing a project as a mount point for the docker-compose volume using an environment variable substitution.  While this can be achieved using the .bashrc it's not scalable only affording a single permutation at a time.  

I can think of several docker-compose use cases where the container being built is dynamically configured at assembly time using custom environment variables.  

Therefore I would recommend one or more of the following in a solution:
1) Source environment variables from the immediate parent process for example when invoking code-insider .
2) Source environment variables from a .env file in the cwd
3) extend the schema for the dev-container.yml filetype to include an environment member.

**Comment by Chuxel** [comment] 2019-08-01 00:01
@bmweller That's interesting feedback, though in this case it was related to WSL specifically (I updated the title to be more accurate).

Two things on general env vars:

1.[Compose env files](https://docs.docker.com/compose/environment-variables/) should work. Are they not? Are you trying to do something not covered by these capabilities?

2. One thing to be aware of is that Docker Compose start/stop flows (and related vars) can be managed entirely outside of VS Code while still using devcontainer.json. If you "Open/Reopen Folder in Container", with a `devcontainer.json` in it, VS Code will look to see if the service you specify is already running and simply connect if so.

**Comment by bmweller** [comment] 2019-08-01 21:46
@Chuxel, thanks for reviewing.  Ok, let me know if I should raise my observation as a separate feature / defect enhancement -- as you correctly noted my observation has nothing specifically to do with WSL.

While I can confirm environment variable are found, they are only found from vars sourced directly in the .bashrc.  

Say for instance I declared an env var named PROJECT_PATH and set that in the .bashrc.  Then when running `code-insider ./my-dev-container-project`  the variable is substituted in the docker-compose process as expected via the devcontainer.json settings.

However when I execute this directly via the current process (e.g.  `PROJECT_PATH=/full-path-to/my-favorite-lang-frontend-project code-insider ./my-dev-container-project`)  the code instance itself persists the variable (i.e. it's visible in the embedded terminal) however the vscode-remote plugin does not leverage the parent process environment and relies solely on the .bashrc during the "open in container" devcontainer bootstrap process.

Again if this is completely unrelated to WSL and should be tagged with devcontainer support I'd appreciate your guidance on opening a new issue.

**Comment by Chuxel** [comment] 2019-08-01 23:00
@bmweller We probably need to get more explicit in terms of workflow and what you are exactly trying to do, because what you describe does work for me, so I'm unclear where the issue is. However, there might be a subtly somewhere. Can you provide exact repro steps?  What OS are you on?

What you might be observing is a VS Code behavior that has nothing to do with VS Code - Remote.  If you have an existing VS Code window open, the process is reused when you run a command from the command line to improve perf.  To get env vars to stick from the command line, you should shut down VS Code entirely and then start it up.

**Comment by bmweller** [comment] 2019-08-02 15:16
Yes being explicit is a great idea -- I've captured the details here now. I'll take the workflow as a separate topic and for now narrow the focus on docker-compose substitutions.  So what I've discovered / uncovered was that my initial testing was against `code` vs `code-insider.`

Also I think to your note when I open a new instance of `code` from a terminal ( when I have an existing code session running) the process hierarchy of the new instance hangs off the existing.   `code-insider` works as expected in this case and the container gets the variable from the terminal invocation value.  However in `code` the value is always 'cached' from the existing instance, the only way to get around the old value is to completely exit all instances of code before invoking the terminal variables instance.


```
:/tmp$ code --version
1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64
---
:~$ code-insiders --version
1.37.0-insider
d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c
x64
```

```
:~$ uname -a
Linux brian 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

From .bashrc
```
export PROJECT_NAME=sample 
~                                                                               
~                                                                               
~                                                                               
~                                                                                                                              
"~/.bash_aliases" 1 line, 27 characters

:~$ grep .bash_aliases ~/.bashrc 
# ~/.bash_aliases, instead of adding them here directly.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
```
Sample .devcontainer project
[sample-devcontainer.zip](https://github.com/microsoft/vscode-remote-release/files/3461851/sample-devcontainer.zip)

Successful workflow `code-insiders` with an existing window open using a new standalone terminal invocation.
```
:/tmp$ env |grep PROJ
PROJECT_NAME=sample
:/tmp$ ls -ld sample-devcontainer/
drwxrwxr-x 3 brian brian 4096 Aug  2 10:30 sample-devcontainer/

:/tmp$ PROJECT_NAME1=aNoThEr PROJECT_NAME=RePlAcEd code-insiders sample-devcontainer/

```
starting the .devcontainer from the UI


 [Crtl + ] 
> remote-containers: Reopen Folder in Container

after initialization ran 
```
:/tmp$ docker inspect cd |jq "..|.Labels? | select (. != null) "
{
  "com.docker.compose.config-hash": "469f329cb552ae9d850ec4a27b5f36ae296aac6bd1ee15d0bb1931214e7646f4",
  "com.docker.compose.container-number": "1",
  "com.docker.compose.oneoff": "False",
  "com.docker.compose.project": "sampledevcontainerdevcontainer",
  "com.docker.compose.service": "dev-container",
  "com.docker.compose.version": "1.17.1",
  "my.project.name": "RePlAcEd-value",
  "my.project.name1": "aNoThEr-value"
}
```

**Comment by Chuxel** [comment] 2019-08-02 15:45
@bmweller Yes, this is a VS Code behavior, so it might be good to raise it outside of the context of VS Code Remote in the vscode repo itself.  If you open an integrated terminal even without docker, the behavior you see would happen. (Just type `env` or echo the variable -- if you completely shut down, VS Code it will appear.  If you start a new terminal with VS Code running already, you may not.)

See https://github.com/microsoft/vscode/issues/47816, https://github.com/microsoft/vscode/issues/15452, and others like it in the VS Code repo. That's the best place to up-vote.

**Comment by bmweller** [comment] 2019-08-03 10:14
Thank you @Chuxel, though now I'm wondering what the integration cycle of insider is with code.  If this is working as expected in code-insider why have these two issues been open against code for over a year???

**Comment by chrmarti** [comment] 2020-09-04 06:33
When the folder you are working with is a WSL folder we now use WSL's environment variables and also pass these to Docker Compose (https://github.com/microsoft/vscode-remote-release/issues/3548). Closing as implemented.

**Closed by chrmarti** 2020-09-04 06:33 UTC
Labels: containers, feature-request, wsl
