### ISSUE TITLE
Don't resolve docker command on Mac

### ISSUE THREAD

**Issue by odanado** [microsoft/vscode-remote-release#74] opened 2019-05-03 14:30 UTC
- VSCode Version: 1.34.0-insider 
- Local OS Version: macOS Mojave 10.14.4
- Remote OS Version: node:lts (Docker Image)
- Remote Extension/Connection Type: Docker
- Docker Desktop for Mac: 2.0.0.2 (30215)
- Docker Engine: 18.09.1

Steps to Reproduce:

1. Install Docker Desktop for Mac ( docker command is placed to `/usr/local/bin` ).
2. Run `git clone https://github.com/Microsoft/vscode-remote-try-node`
3. Open vscode-remote-try-node using vscode-insider 
4. Run Open Folder in Container on vscode-insider 
5. I got an error that `Docker version 17.06.1 or later required`

![スクリーンショット 2019-05-03 21 53 06](https://user-images.githubusercontent.com/6040962/57143855-c6702280-6dfa-11e9-9e2f-582aa23266c3.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I found the cause of the issue. Execution result of `echo $PATH` is `/usr/bin:/bin:/usr/sbin:/sbin` in extensions of vscode. The result does'nt include `/usr/local/bin`.

**Comment by chrmarti** [comment] 2019-05-06 08:54
Could be #35. Where are you adding `/usr/local/bin` to your PATH?

**Comment by odanado** [comment] 2019-05-07 18:26
I didn't add `/usr/local/bin` to `$PATH` .
I ran `ln -s /usr/local/bin/docker /usr/bin` .

**Comment by chrmarti** [comment] 2019-05-08 10:20
@odanado You seemed to say that `/usr/local/bin` not being on the PATH was the reason for the problem you see. I was wondering where `/usr/local/bin` was being added. Am I misunderstanding?

**Comment by odanado** [comment] 2019-05-09 15:50
I haven't found a way to add `/usr/local/bin` to `$PATH`. 
A way to make a symbolic link of docker command to `/usr/bin` is a workaround.

**Comment by chrmarti** [comment] 2019-05-09 19:16
@odanado And after adding the symlink you still see `Docker version ... required` error dialog? Could you run `which -a docker` and see if that tells you where that older version sits?

**Comment by odanado** [comment] 2019-05-10 00:28
The error dialog was not displayed after making the symbolic link. 
An execution result of `which -a docker`: 
```
$ which -a docker
/usr/local/bin/docker
/usr/bin/docker
```

**Comment by chrmarti** [comment] 2019-05-10 05:47
Is that from the integrated terminal or an external terminal window? Does the output differ for the two (could you post the output from the other)?

**Comment by lypanov** [comment] 2019-05-10 07:20
As a random side note, I'd like to mention that Powershell doesn't seem to be supported. I had to change my shell back to bash/zsh before VS Code was able to pick up my path. I know this is a quite fringe use case. I wonder what shell the original poster is using? Maybe another unsupported shell?

**Comment by egamma** [comment] 2019-05-10 07:27
@lypanov 

pls file a separate issue for this:

>As a random side note, I'd like to mention that Powershell doesn't seem to be supported.

**Comment by odanado** [comment] 2019-05-13 14:03
In VSCode Terminal:
```
$ which -a docker
/usr/local/bin/docker
/usr/bin/docker
```

In iTerm2
```
$ which -a docker
/usr/local/bin/docker
/usr/bin/docker
```

**Comment by chrmarti** [comment] 2019-05-14 16:38
@odanado What do you get for:
```
docker version --format '{{.Server.Version}}'
echo $?
```

What is your default shell? (bash / zsh / pwsh)

**Comment by odanado** [comment] 2019-05-15 16:32
In VSCode Terminal:
```
$ docker version --format '{{.Server.Version}}'
18.09.1
$ echo $?
0
```

My default shell is zsh.

**Comment by chrmarti** [comment] 2019-05-15 16:50
When the error dialog appears, could you Cancel and then check what is in the dev console? (Help > Toggle Developer Tools)

There might be an error logged there that would help us track this down.

**Comment by AngellusMortis** [comment] 2019-05-16 04:12
Looks like a dupe of my issue #35. Anything that is not in the system `$PATH` is not being used by VS Code to build containers. In this case, @odanado, if you look in the following files, you should be able to verify that `/usr/local/bin` is not in the default system `$PATH`, but they will vary from system to system:

* /etc/profile
* For Bash: /etc/bashrc or /etc/bash.bashrc
* For ZSH: /etc/zsh* (on my system, ZSH is using /etc/zsh/zprofile to just source /etc/profile).

**Comment by odanado** [comment] 2019-05-16 14:31
Toggle Developer Tools
![スクリーンショット 2019-05-16 23 31 21](https://user-images.githubusercontent.com/6040962/57862091-c298c300-7832-11e9-8c56-0ace8ae8d189.png)

**Comment by chrmarti** [comment] 2019-05-17 00:04
@Tyriar I thought the terminal would run with the same PATH as the extension host. Is this not the case?

**Comment by chrmarti** [comment] 2019-05-27 06:33
/duplicate https://github.com/microsoft/vscode-remote-release/issues/35

**Closed** 2019-05-27 06:33 UTC
Labels: *duplicate, bug, containers
