### ISSUE TITLE
VSCode Extension enables itself on update

### ISSUE THREAD

**Issue by brwilkinson** [microsoft/vscode-remote-release#683] opened 2019-06-13 19:32 UTC
Each time the Remote -SSH extension on VS Code updates, it sets itself to enabled.

Even when it was disabled before the update.

This does not occur with the other extensions, including the other "Remote - X" extensions

**Comment by egamma** [comment] 2019-06-13 19:45
duplicate of #431

**Closed by egamma** 2019-06-13 19:45 UTC
Labels: *duplicate
