### ISSUE TITLE
Icons missing in scm provider view on remote SSH instance

### ISSUE THREAD

**Issue by mjcrouch** [microsoft/vscode-remote-release#2829] opened 2020-04-25 11:22 UTC
When a `SourceControlResourceState` provides an `iconPath` via its `decorations` property - the icon does not appear in the source control view when running via remote - SSH

- VSCode Version: 1.44.2
- Local OS Version: Win 7 Enterprise
- Remote OS Version: RHEL 7.7
- Remote Extension/Connection Type: SSH

This is a continuation of #2115 - one underlying cause of the issue was solved, but it is still impossible to see icons on the remote instance of vs code because of the error shown in that issue, as reported during verification

![](https://user-images.githubusercontent.com/2230985/75580559-deb1cd80-5a1c-11ea-8e5f-9e4c29d6c0e2.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by joaomoreno** [comment] 2020-07-23 15:26
Dupe of https://github.com/microsoft/vscode/issues/103073

**Closed by joaomoreno** 2020-07-23 15:26 UTC
