### ISSUE TITLE
Change user after connecting

### ISSUE THREAD

**Issue by claytongulick** [microsoft/vscode-remote-release#4457] opened 2021-02-12 03:48 UTC
After connecting to a host, I need to ability to change the user multiple times.

The use case is this: I connect to a remote vm with a user who is a member of the ssh group. This is a different user than the app user for security reasons - the app user should never have ssh permissions.

When debugging remotely, I need the application to execute under the 'app' user permissions, not the user that's connected via ssh, so I need to somehow have vs code issue a "su" command and have all the subsequent commands, debugging and filesystem access happen under the switched user.

In the case of a server that's configured with additional scripts that execute under different user permissions (job user, etc...) I need to also be able to switch to that user in order to debug and troubleshoot the job in the remote environment.

Thanks for the great work!!

**Comment by roblourens** [comment] 2021-03-03 00:00
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/690

**Closed by roblourens** 2021-03-03 00:00 UTC
Labels: feature-request, ssh
