### ISSUE TITLE
Opening WSL folder in Docker container causes error (Win v.21354)

### ISSUE THREAD

**Issue by tonyjmartinez** [microsoft/vscode-remote-release#4864] opened 2021-04-11 02:45 UTC
I have the same issue as [#3430](https://github.com/microsoft/vscode-remote-release/issues/3430), but that issue is closed. I'm trying to open the current WSL folder in a Docker container. After a recent Windows update I started hitting the error below.

edit: Just verified that rolling back to 21343.1 fixes this issue.

- VSCode Version: 1.55.1
- Local OS Version: Windows 10 21354.1
- Remote OS Version:
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Docker desktop is running, WSL folder is open in VSCode.
2. Select 'Open folder in container' - choosing current folder
3. Docker starts building until it hits the following error
```
docker: Error response from daemon:
\\wsl.localhost\Ubuntu-20.04\home\to
ny\projects\the-hackboard%!(EXTRA st
ring=is not a valid Windows path).
See 'docker run --help'.
[8359 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl.localhost\Ubuntu-20.04\home\tony\projects\the-hackboard --filter label=vsch.quality=stable
[9839 ms] Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=\\wsl.localhost\Ubuntu-20.04\home\tony\projects\the-hackboard,target=/workspaces/the-hackboard,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl.localhost\Ubuntu-20.04\home\tony\projects\the-hackboard -l vsch.quality=stable -l vsch.remote.devPort=0
```

Does this issue occur when you try this locally?: Yes, I'm only running locally
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment] 2021-04-12 20:53
Please give Remote-Containers 0.167.0 a try. That currently requires VS Code Insiders available here: https://code.visualstudio.com/insiders/

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4789.

**Closed by chrmarti** 2021-04-12 20:53 UTC
Labels: containers

**Comment by tonyjmartinez** [comment] 2021-04-13 16:24
@chrmarti thanks, that worked.
