### ISSUE TITLE
Gitlens and Github pull

### ISSUE THREAD

**Issue by ragaDani** [microsoft/vscode-remote-release#993] opened 2019-07-18 01:51 UTC
Issue Type: <b>Bug</b>

The icons on gitlens and github pull requests aren't showing. Furthermore, the interactive icons(push,pull, stage, discard, etc) within gitlens, source control and github are also not showing when using ubuntu 18.04(haven't checked on others) on wsl.

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.90GB (16.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4001)|
|Memory (System)|23.90GB (16.60GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment] 2019-07-18 13:12
duplicate of #966

**Closed by aeschli** 2019-07-18 13:12 UTC
