### ISSUE TITLE
Open vscode remote via CLI

### ISSUE THREAD

**Issue by FlavioAmurrioCS** [microsoft/vscode-remote-release#1355] opened 2019-09-03 18:02 UTC
I would like to be able to have vscode open connected to a remote host via CLI and have a default host/dir if none is provided.
ie
```bash
code-ssh <hostname> <path>
```
Hostname can either be the last connected host or from an environmental variable if none is provided
When connecting to a host, use the provided path or have a fall back path(maybe home dir)

**Comment by egamma** [comment] 2019-09-09 17:30
Duplicate of #585

**Closed by egamma** 2019-09-09 17:30 UTC
