### ISSUE TITLE
Incomplete Ruby syntax highlighting in Remote SSH

### ISSUE THREAD

**Issue by OmriSama** [microsoft/vscode-remote-release#805] opened 2019-06-25 16:56 UTC
Issue Type: <b>Bug</b>

When using Ruby through Remote SSH, syntax highlighting is incomplete. One of the biggest examples of this is that Symbols appear as green for me (same as strings) instead of orange like they do when normally viewing the code file.

Methods with parentheses also don't appear as blue like they did in the past.

Here is an example of Ruby code with Remote-SSH:
![image](https://user-images.githubusercontent.com/10534779/60117633-447fe400-972f-11e9-87e7-3fbbc61ac3dc.png)

vs. Ruby code with properly functioning syntax highlighting:
![image](https://user-images.githubusercontent.com/10534779/60117659-56618700-972f-11e9-912b-b2d6d02760ea.png)

I don't think this is an issue with the Ruby extension, as this syntax highlighting should be built into VScode.

```
Extension version: 0.42.2
VS Code version: Code - Insiders 1.36.0-insider (e80dd4f217db6e230d311a87fdf4276f740f6445, 2019-06-25T05:19:01.461Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 5.0.0-19-generic
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v4 @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux x64 5.0.0-19-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v4 @ 2.80GHz (4 x 2793)|
|Memory (System)|13.60GB (10.62GB free)|
|VM|100%|
</details>

**Comment by krisquigley** [comment] 2019-07-06 21:57
I'm having a similar problem but with the Remote WSL extension

**Comment by rebornix** [comment] 2019-07-16 22:56
Actually Ruby extension has its own syntax highlighting logic as implemented in https://github.com/rubyide/vscode-ruby/blob/ed52679b332913e69c4dff2f0fdff9d67f88669d/scripts/update-grammar.js . Duplicate of https://github.com/rubyide/vscode-ruby/issues/483

**Comment by rebornix** [comment] 2019-07-16 23:11
Closing it here as it's something we should push forward in the extension.

**Closed by rebornix** 2019-07-16 23:11 UTC
