### ISSUE TITLE
Open tabs are lost after connection hard reset even when using a workspace

### ISSUE THREAD

**Issue by munael** [microsoft/vscode-remote-release#2787] opened 2020-04-17 18:54 UTC
- VSCode Version: 2020-06-20 (1.47.0 insiders)
- Local OS Version: Windows 10 1909
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to a remote machine
2. (optional) Open a VSCode workspace
3. Open tabs and customize the session view a bit
4. Work normally until (or induce) a disconnect
5. VSC attempts to reconnect
6. If that fails and you get to the point where the only option is to reload the window, reload
7. Most tabs should be lost unless they had changes unsaved (not sure)
8. Tab groups remain (but are empty) if you set the option to preserve tab groups when the last is closed. _All tabs are still closed_

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

Screenshot of most common error when this happens:
![image](https://user-images.githubusercontent.com/5769148/85555538-4fad6e80-b626-11ea-9ef2-5aca798235a0.png)

**Comment by bamurtaugh** [comment] 2020-11-04 01:23
Seems related to/possible dupe of https://github.com/microsoft/vscode-remote-release/issues/3475 (although opened before 3475, we've been tracking 3475).

**Closed** 2020-11-05 20:07 UTC
Labels: bug, ssh
