### ISSUE TITLE
Simple Browser - Rendering issues when opened from the Ports view for the second time

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4438] opened 2021-02-08 07:23 UTC
![image](https://user-images.githubusercontent.com/172399/107187663-a6658e00-69e6-11eb-9d7c-81b2fdcbe807.png)

To reproduce:
- remote containers > try a sample > try node
- npm install
- npm start
- open the Ports view
- open the simple browser from the Ports view (see screenshot)
- open the simple browser for a second time -> the rendering issue shows up.

// CC @alexr00

**Comment by mjbvz** [comment] 2021-02-09 05:02
This was actually a generic webview issue (you can also reproduce it by refreshing the markdown preview in an ssh workspace)

It was caused by my change which enabled better caching for webview resources. Should be fixed by https://github.com/microsoft/vscode/commit/518097377de2ca84d9ba1f01933dee5393e0d76f

**Closed by mjbvz** 2021-02-09 05:02 UTC
Labels: bug
