### ISSUE TITLE
workspaceMount/workspaceMount does not support Windows paths (Windows Containers issue)

### ISSUE THREAD

**Issue by CarlosDomingues** [microsoft/vscode-remote-release#4658] opened 2021-03-12 01:05 UTC
**Problem**

Using Windows paths in `workspaceMount` and `workspaceFolder` doesn't seem to be possible. Trying to use Windows paths as targets for either volumes and bind mounts will return `Workspace folder in devcontainer.json must be an absolute path.`.

**Information**

- VSCode Version: 1.55.0-insider
- Local OS Version: Windows 10 
- Remote OS Version: Any Windows Container
- Remote Extension/Connection Type: Docker

**Steps to Reproduce**

1. On a Windows 10 computer, enable Windows Containers.
2. Check if Windows Containers are working correctly, e.g: `docker run -it -v c:\Users\<my-user>:c:\Workspace mcr.microsoft.com/windows/servercore:1809 Powershell`
3. Try to configure `.devcontainer/.devcontainer.json`:

```json
{
  "name": "vscode-wincontainer-test",
  "dockerFile": "Dockerfile",
  "context": "..",
  "workspaceMount": "source=${localWorkspaceFolder},target=c:\Workspace",
  "workspaceFolder": "c:\Workspace"
}

```

`.devcontainer/Dockerfile`:

```Dockerfile
FROM  mcr.microsoft.com/windows/servercore:1809
SHELL ["Powershell", "-Command"]
```

I have tried a few path variations such as `\\`, as well as using Unix paths (`/`), but none would work.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by vovimayhem** [comment] 2021-03-12 03:08
Hey, just FYI, looks like windows containers aren't supported:

https://code.visualstudio.com/docs/remote/containers#_system-requirements

**Comment by chrmarti** [comment] 2021-03-12 10:58
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/445

**Closed by chrmarti** 2021-03-12 10:58 UTC
Labels: containers
