### ISSUE TITLE
Not able to Connect WSL from VSCODE || WSL (21) ERROR: CreateProcessParseCommon:711: Failed to translate

### ISSUE THREAD

**Issue by Mounesh1881** [microsoft/vscode-remote-release#9810] opened 2024-04-23 09:32 UTC
We observed that we were running into below errors while connecting from Visual Studio to WSL.

![image](https://github.com/microsoft/vscode-remote-release/assets/109141221/00cf3ff5-a1b7-4727-a91b-a3b91a75a469)
![image](https://github.com/microsoft/vscode-remote-release/assets/109141221/75dd5777-f440-48dc-8716-9b04ed21b2a8)
Start: Run: wsl -l -v
[414 ms] Initializing configuration support...
[414 ms] Internal initialization of dev container support package...
[484 ms] Start: Run: wsl -d docker-desktop-data -e /bin/sh -c echo ~
[986 ms] Could not connect to WSL.
[986 ms] Command failed: wsl -d docker-desktop-data -e /bin/sh -c echo ~
[986 ms] 
[986 ms] <3>WSL (21) ERROR: CreateProcessParseCommon:711: Failed to translate C:\Users\ECADMIN\AppData\Local\Programs\Microsoft VS Code
<3>WSL (21) ERROR: CreateProcessParseCommon:757: getpwuid(0) failed 2
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Common Files\Oracle\Java\javapath
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows\system32
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows\System32\Wbem
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Windows\System32\OpenSSH\
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\dotnet\
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\ProgramData\chocolatey\bin
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Amazon\AWSCLIV2\
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Program Files\Docker\Docker\resources\bin
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\ProgramData\Riverbed\ProcessInjection\rpictrlBin
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\ECADMIN\AppData\Local\Microsoft\WindowsApps
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\ProgramData\Riverbed\ProcessInjection\rpictrlBin
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\ECADMIN\AppData\Local\Microsoft\WindowsApps
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\ECADMIN\AppData\Local\GitHubDesktop\bin
<3>WSL (21) ERROR: UtilTranslatePathList:2866: Failed to translate C:\Users\ECADMIN\AppData\Local\Programs\Microsoft VS Code\bin
<3>WSL (21) ERROR: CreateProcessEntryCommon:334: getpwuid(0) failed 2
<3>WSL (21) ERROR: CreateProcessEntryCommon:505: execvpe /bin/sh failed 2
<3>WSL (21) ERROR: CreateProcessEntryCommon:508: Create process not expected to return

**Comment by aeschli** [comment] 2024-04-23 13:51
`docker-desktop-data` is an internal distro (used by the docker implemetation).
Can you use a different distro and see if the issue exists?

**Comment by Mounesh1881** [comment] 2024-04-24 07:22
as discussed @aeschli

please find the requested information here.

we are running  .devcontainer file below the content of the file

// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/ubuntu
{
	"name": "Ubuntu",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:jammy",
	"features": {
		"ghcr.io/devcontainers/features/terraform:1": {}
	},

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "uname -a",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	"remoteUser": "vscode"
}

**Comment by aeschli** [comment] 2024-04-24 08:03
This is a problem in WSL: https://github.com/microsoft/WSL/issues/9252
Closing as duplicate of https://github.com/microsoft/WSL/issues/9252

There are some solutions in there: Can you see if https://github.com/microsoft/WSL/issues/9252#issuecomment-1648236238 works?

**Comment by Mounesh1881** [comment] 2024-04-24 08:38
the solution provided in #9252  is not working for me.
i want to someone can look into my issue help to resolve.

**Comment by aeschli** [comment] 2024-04-24 09:20
@chrmarti Is it dev containers that runs ` wsl -d docker-desktop-data -e /bin/sh -c echo ~` ?

**Comment by Mounesh1881** [comment] 2024-04-25 03:06
@chrmarti Can you please help us here

**Comment by Mounesh1881** [comment] 2024-04-25 11:16
@aeschli @chrmarti  can we have update here

**Comment by aeschli** [comment] 2024-04-25 12:26
@Mounesh1881 @chrmarti is on vacation this week, please be patient

**Comment by chrmarti** [comment] 2024-04-29 14:04
What is the folder's path that you want to reopen in a container? Is it in a WSL or Windows filesystem?

Are any of the following settings set:
![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/38112fc0-8ac9-4b68-a503-a49992d59fe0)

**Comment by Mounesh1881** [comment] 2024-04-30 06:04
Just i am running this "image": "mcr.microsoft.com/devcontainers/base:jammy" only , no extra action written in code there.

**Comment by chrmarti** [comment] 2024-04-30 07:00
Are you using a workspace folder on a Windows drive or in a WSL filesystem?

Also check the above mentioned user settings.

**Comment by Mounesh1881** [comment] 2024-04-30 08:51
![image](https://github.com/microsoft/vscode-remote-release/assets/109141221/f38f5738-303c-4b8d-995c-644ff41c75d3)

**Comment by chrmarti** [comment] 2024-04-30 09:30
Please reply to all of the following:
1. Are you using a workspace folder on a Windows drive or in a WSL filesystem?
2. What about the `Dev Containers: Execute In WSL` setting? It is not part of your above screenshot.
3. What is the output of running `wsl -l -v` in a terminal on Windows?

**Comment by chrmarti** [comment] 2024-04-30 13:12
`docker-desktop-data` is shown as the default distro, this makes Dev Containers use this distro which is not a completely functional Linux install. Please run `wsl --setdefault Ubuntu` to fix this.

I also suggest you uncheck `Dev Containers: Execute In WSL` in the user settings unless there is a specific reason to always access the Docker CLI through WSL. (Dev Containers will still go through WSL when the workspace folder is in a WSL filesystem.)

**Comment by Mounesh1881** [comment] 2024-05-02 05:05
thank you so much this worked for me

**Comment by chrmarti** [comment] 2024-05-02 13:51
Thanks for confirming. Closing as answered.

**Closed by chrmarti** 2024-05-02 13:51 UTC
Labels: containers, info-needed
