### ISSUE TITLE
Port Forwarding buttons to browser in Panel not working

### ISSUE THREAD

**Issue by afshawnlotfi** [microsoft/vscode-remote-release#6560] opened 2022-04-04 15:51 UTC
Issue Type: <b>Bug</b>

In the same panel as Terminal under the Ports tab the port fowarding buttons next to Local Address that can open port in the browser no longer work. Have to launch through action menu

![image](https://user-images.githubusercontent.com/6283745/161582728-d7d03067-4eaf-4a84-893a-5d48ec82dc16.png)

Extension version: 0.231.3
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.104-linuxkit
Remote OS version: Linux x64 5.10.104-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id b11c828d-1824-4ceb-98f3-e087d4ddfa9d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Miniconda (Python 3)|
|OS|Linux x64 5.10.104-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (4 x 2787)|
|Memory (System)|7.68GB (4.46GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Java 8|
|OS|Linux x64 5.10.104-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (4 x 2787)|
|Memory (System)|7.68GB (4.46GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
vscaat:30438848
pynewfile477:30463512

```

</details>

**Comment by alexr00** [comment] 2022-04-05 09:23
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6533, which should be released this week.

**Closed by alexr00** 2022-04-05 09:23 UTC
Labels: ssh
