### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by hahia** [microsoft/vscode-remote-release#7092] opened 2022-08-19 12:52 UTC
I have installed vscode-server on the remote server (linux) and I can connect to the remote server on a windows pc. But when I want to connect to the remote machine through another computer (macos), I can't connect to it.

My config:
`Host sm1
  HostName localhost
  Port 8889
  User xxxx
  IdentityFile /Users/h2q/.ssh/id_rsa
`

The log:
`[20:43:47.924] Log Level: 2
[20:43:47.924] remote-ssh@0.84.0
[20:43:47.924] darwin arm64
[20:43:47.927] SSH Resolver called for "ssh-remote+sm1", attempt 1
[20:43:47.928] "remote.SSH.useLocalServer": false
[20:43:47.928] "remote.SSH.showLoginTerminal": false
[20:43:47.928] "remote.SSH.remotePlatform": {"sm1":"linux"}
[20:43:47.928] "remote.SSH.path": undefined
[20:43:47.928] "remote.SSH.configFile": /Users/h2q/.ssh/config
[20:43:47.928] "remote.SSH.useFlock": false
[20:43:47.928] "remote.SSH.lockfilesInTmp": true
[20:43:47.929] "remote.SSH.localServerDownload": auto
[20:43:47.929] "remote.SSH.remoteServerListenOnSocket": false
[20:43:47.929] "remote.SSH.showLoginTerminal": false
[20:43:47.929] "remote.SSH.defaultExtensions": []
[20:43:47.929] "remote.SSH.loglevel": 2
[20:43:47.929] "remote.SSH.enableDynamicForwarding": true
[20:43:47.929] "remote.SSH.enableRemoteCommand": false
[20:43:47.929] "remote.SSH.serverPickPortsFromRange": {}
[20:43:47.930] "remote.SSH.serverInstallPath": {}
[20:43:47.940] SSH Resolver called for host: sm1
[20:43:47.940] Setting up SSH remote "sm1"
[20:43:47.942] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[20:43:47.944] Install and start server if needed
[20:43:47.945] PATH: /Users/h2q/miniconda3/bin:/Users/h2q/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[20:43:47.945] Checking ssh with "ssh -V"
[20:43:47.948] > OpenSSH_8.1p1, LibreSSL 2.7.3

[20:43:47.949] Using SSH config file "/Users/h2q/.ssh/config"
[20:43:47.949] Running script with connection command: ssh -T -D 53849 -o ConnectTimeout=1000 -F '/Users/h2q/.ssh/config' sm1 bash
[20:43:49.735] > Connection closed by ::1 port 8889
[20:43:49.736] Got some output, clearing connection timeout
[20:43:49.994] "install" terminal command done
[20:43:49.995] Install terminal quit with output: Connection closed by ::1 port 8889
[20:43:49.995] Received install output: Connection closed by ::1 port 8889
[20:43:49.996] Failed to parse remote port from server output
[20:43:49.996] Resolver error: Error: 
	at Function.Create (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.t.tryInstall (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643908
	at async Object.t.withShowDetailsEvent (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[20:43:50.004] ------

[20:43:50.065] ------

[20:43:50.065] SSH Resolver called for "ssh-remote+sm1", attempt 2, (Reconnection)
[20:43:50.065] SSH Resolver called for host: sm1
[20:43:50.065] Setting up SSH remote "sm1"
[20:43:50.066] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[20:43:50.067] Install and start server if needed
[20:43:50.069] Using SSH config file "/Users/h2q/.ssh/config"
[20:43:50.069] Running script with connection command: ssh -T -D 53866 -o ConnectTimeout=1000 -F '/Users/h2q/.ssh/config' sm1 bash
[20:43:50.569] > Connection closed by ::1 port 8889
[20:43:50.570] Got some output, clearing connection timeout
[20:43:50.819] "install" terminal command done
[20:43:50.819] Install terminal quit with output: Connection closed by ::1 port 8889
[20:43:50.819] Received install output: Connection closed by ::1 port 8889
[20:43:50.819] Failed to parse remote port from server output
[20:43:50.820] Resolver error: Error: 
	at Function.Create (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.t.tryInstall (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643908
	at async Object.t.withShowDetailsEvent (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[20:43:50.821] ------

[20:43:50.827] ------

[20:43:50.827] SSH Resolver called for "ssh-remote+sm1", attempt 3, (Reconnection)
[20:43:50.827] SSH Resolver called for host: sm1
[20:43:50.827] Setting up SSH remote "sm1"
[20:43:50.828] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[20:43:50.829] Install and start server if needed
[20:43:50.830] Using SSH config file "/Users/h2q/.ssh/config"
[20:43:50.830] Running script with connection command: ssh -T -D 53871 -o ConnectTimeout=1000 -F '/Users/h2q/.ssh/config' sm1 bash
[20:43:51.315] > Connection closed by ::1 port 8889
[20:43:51.315] Got some output, clearing connection timeout
[20:43:51.568] "install" terminal command done
[20:43:51.568] Install terminal quit with output: Connection closed by ::1 port 8889
[20:43:51.568] Received install output: Connection closed by ::1 port 8889
[20:43:51.568] Failed to parse remote port from server output
[20:43:51.569] Resolver error: Error: 
	at Function.Create (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.t.tryInstall (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643908
	at async Object.t.withShowDetailsEvent (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[20:43:51.570] ------

[20:43:51.577] ------

[20:43:51.577] SSH Resolver called for "ssh-remote+sm1", attempt 4, (Reconnection)
[20:43:51.578] SSH Resolver called for host: sm1
[20:43:51.578] Setting up SSH remote "sm1"
[20:43:51.579] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[20:43:51.581] Install and start server if needed
[20:43:51.583] Using SSH config file "/Users/h2q/.ssh/config"
[20:43:51.583] Running script with connection command: ssh -T -D 53873 -o ConnectTimeout=1000 -F '/Users/h2q/.ssh/config' sm1 bash
[20:43:52.097] > Connection closed by ::1 port 8889
[20:43:52.097] Got some output, clearing connection timeout
[20:43:52.351] "install" terminal command done
[20:43:52.351] Install terminal quit with output: Connection closed by ::1 port 8889
[20:43:52.352] Received install output: Connection closed by ::1 port 8889
[20:43:52.352] Failed to parse remote port from server output
[20:43:52.353] Resolver error: Error: 
	at Function.Create (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.t.tryInstall (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643908
	at async Object.t.withShowDetailsEvent (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[20:43:52.356] ------

[20:43:52.359] ------

[20:43:52.359] SSH Resolver called for "ssh-remote+sm1", attempt 5, (Reconnection)
[20:43:52.361] SSH Resolver called for host: sm1
[20:43:52.361] Setting up SSH remote "sm1"
[20:43:52.362] Using commit id "6d9b74a70ca9c7733b29f0456fd8195364076dda" and quality "stable" for server
[20:43:52.365] Install and start server if needed
[20:43:52.368] Using SSH config file "/Users/h2q/.ssh/config"
[20:43:52.368] Running script with connection command: ssh -T -D 53878 -o ConnectTimeout=1000 -F '/Users/h2q/.ssh/config' sm1 bash
[20:43:52.949] > Connection closed by ::1 port 8889
[20:43:52.950] Got some output, clearing connection timeout
[20:43:53.197] "install" terminal command done
[20:43:53.197] Install terminal quit with output: Connection closed by ::1 port 8889
[20:43:53.197] Received install output: Connection closed by ::1 port 8889
[20:43:53.198] Failed to parse remote port from server output
[20:43:53.198] Resolver error: Error: 
	at Function.Create (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.t.tryInstall (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643908
	at async Object.t.withShowDetailsEvent (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/h2q/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[20:43:53.199] ------`

Do I need to reinstall vscode-server？
Thank you for your help!!!

**Comment by tanhakabir** [comment] 2022-08-19 23:55
Looks like the issue is with the error `Connection closed by ::1 `

What kind of remote machine are you connecting to?

**Comment by hahia** [comment] 2022-08-20 01:29
> Looks like the issue is with the error `Connection closed by ::1 `
> 
> What kind of remote machine are you connecting to?

High Performance Computing Cluster (HPC). I first connect to login node, then go to computing Node by the ssh command
`ssh -NfL 8888:computing_node_IP:22 my_user_name@login_node_IP`

**Comment by hahia** [comment] 2022-08-23 09:58
> Looks like the issue is with the error `Connection closed by ::1 `
> 
> What kind of remote machine are you connecting to?

How to fix this, thanks for any help!!!

**Comment by roblourens** [comment] 2023-04-10 17:22
Sorry, this slipped through the cracks, is it still an issue? The log isn't giving us any useful details.

**Closed** 2023-04-17 17:54 UTC
Labels: ssh, info-needed
