### ISSUE TITLE
Connection failed the default shell is not bash compatible (like fish)

### ISSUE THREAD

**Issue by beci** [microsoft/vscode-remote-release#296] opened 2019-05-13 12:13 UTC
- VSCode Version: 1.34.20-insider
- Local OS Version: Windows 10
- Remote OS Version: linux (arch 5.0.13)
- Remote Extension/Connection Type: SSH

Bash installed, but not as the default shell, which is [fish](https://fishshell.com/).

Steps to Reproduce:

1. set [fish](https://fishshell.com/) as default shell on remote server: `chsh -s /usr/bin/fish`
2. try to connect, and get the following error:
```bash
SSH Resolver called for "ssh-remote+arch"
SSH Resolver called for host: arch
Setting up SSH remote "arch"
Using commit id "57b550c559b945eb9d871dbf2b2e4cb9e31e2551" and quality "insider" for server
Install and start server if needed
> Pseudo-terminal will not be allocated because stdin is not a terminal.
> 
> /usr/bin/python: No module named virtualfish
> fish: Expected a string, but instead found a redirection
> cat << 'EOF' > $INSTALL_SCRIPT
>      ^
> 
"install" terminal command done
Received install output:      ^
Failed to parse remote port from server output:      ^
```

It's clear the script on the server side is not fish compatible, because if I change the default shell to bash, it's fine. I can's see where is the source code of this extension, so blindly the possible solutions:
 - simply use `#!/bin/bash` at the beginning of the target script
 - find bash (or other compatible shell) and run each command in it
 - make the script fish compatible

**Comment by egamma** [comment] 2019-05-13 12:50
duplicate of #33

**Closed by egamma** 2019-05-13 12:50 UTC
