### ISSUE TITLE
Custom icons not appearing with wsl remote turned on

### ISSUE THREAD

**Issue by RitikPatni** [microsoft/vscode-remote-release#1138] opened 2019-08-11 15:01 UTC
Issue Type: <b>Bug</b>

Custom icons which include icons from popular extensions like vscode-spotify, gitlens are not appearing when wsl remote is turned although the functionality isnot compromised so I'm not sure why the icons are not appearing

Extension version: 0.39.2
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.96GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/c/Users/ritik/Documents/gsap-experiments --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.84GB (1.96GB free)|
|VM|0%|
</details>

**Comment by egamma** [comment] 2019-08-13 10:14
Duplicate of #687

**Closed by egamma** 2019-08-13 10:14 UTC
