### ISSUE TITLE
Docker Containers Not Stopping When Closing Project Launched from WSL 2 Disk/Location

### ISSUE THREAD

**Issue by chucknelson** [microsoft/vscode-remote-release#3507] opened 2020-08-12 14:43 UTC
- VSCode Version: 1.47.3
- Local OS Version: Windows 10 Pro 10.0.19041 Build 19041 / Version 2004
- Remote OS Version: Debian 10 (Buster)
- Remote Extension/Connection Type: Docker

General info:
* Using a docker-compose `.devcontainer` definition here: https://github.com/chucknelson/fliplist/tree/master/.devcontainer
* Running Docker for Windows 2.3.0.4 with the **WSL 2 Backend**
* WSL 2 is running Ubuntu 18.04.3 LTS

Steps to Reproduce:
1. Open project with `.devcontainer` configured from **WSL 2 disk/location** for decent disk performance (e.g., opening from project files stored in `\\wsl$\...` instead of `C:\...`).
2. Wait for containers to start and project to open.
3. Close VS Code.
4. Run `docker ps` either locally or in WSL, and notice that the containers never stop.

I can see something going wrong in the logs, particularly `exthost1\ms-vscode-remote.remote-containers\shutdownMonitor.log`.

If I open and run the exact same project from my `C:\` drive (i.e., not from the WSL 2 disk), container shutdown seems to occur as expected:
```
...
[2020-08-12T14:22:37.439Z] [PID 33900] [492728 ms] Start: Run: docker exec -i -u vscode 37c2c93714dc6687dcc9abb0d80e106eaef1649ca189e9e19a36960120f6ef21 /bin/sh
[2020-08-12T14:22:37.473Z] [PID 33900] [492762 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink -f /proc/$pid/cwd ; xargs -0 < /proc/$pid/environ ; xargs -0 < /proc/$pid/cmdline ; } ; echo ; done 2>/dev/null
[2020-08-12T14:22:37.672Z] [PID 33900] [492961 ms] Start: Run: docker-compose --project-name fliplist_devcontainer -f c:\Users\chucknelson\Development\fliplist\.devcontainer\docker-compose.yml stop -t 0
[2020-08-12T14:22:39.607Z] [PID 33900] [494896 ms] Command output: {"stdout":"","stderr":"Stopping fliplist_devcontainer_app_1 ... \r\r\nStopping fliplist_devcontainer_db_1  ... \r\r\n\u001b[2A\u001b[2K\rStopping fliplist_devcontainer_app_1 ...
...
```

When I open and run the project form the WSL 2 disk, container shutdown fails:
```
...
[2020-08-12T04:27:32.036Z] [PID 33032] [19528 ms] Start: Run: docker exec -i -u vscode 1e1ff8c2bd015f938ad07b04a03ffba8cbb9cfe2a9c7658e99fc29c5aed959d1 /bin/sh
[2020-08-12T04:27:32.060Z] [PID 33032] [19552 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink -f /proc/$pid/cwd ; xargs -0 < /proc/$pid/environ ; xargs -0 < /proc/$pid/cmdline ; } ; echo ; done 2>/dev/null
[2020-08-12T04:27:32.062Z] [PID 33032] [19554 ms] Unexpected error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at c:\Users\chucknelson\.vscode\extensions\ms-vscode-remote.remote-containers-0.128.0\dist\shutdownMonitorProcess.js:1:24761
    at c:\Users\chucknelson\.vscode\extensions\ms-vscode-remote.remote-containers-0.128.0\dist\shutdownMonitorProcess.js:1:25229
    at async Object.exec (c:\Users\chucknelson\.vscode\extensions\ms-vscode-remote.remote-containers-0.128.0\dist\shutdownMonitorProcess.js:1:25250)
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment] 2020-08-17 07:39
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/3272

Please retry with the latest VS Code and Remote-Containers extension.

**Closed by chrmarti** 2020-08-17 07:39 UTC
Labels: containers
