### ISSUE TITLE
Leaking SSH processes with useLocalServer=false

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#7642] opened 2022-12-06 03:29 UTC
- Set `"remote.SSH.useLocalServer": false`
- Open a Remote-SSH window
- Note `ps ax | grep ssh | wc -l`
- Reload the window
- `ps ax | grep ssh | wc -l` again, it has increased by 2
- Keep reloading the window, more ssh processes accumulate

I assume this is due to terminal persistence for Remote-SSH's local terminals. Since they are background terminals, they shouldn't be kept alive. I think we've fixed this before. If Remote-SSH should be killing its own terminal to prevent this, we can probably do that too.

**Comment by roblourens** [comment] 2022-12-06 15:12
I didn't know about the `isTransient` flag. I'll try that. We just set `hideFromUser`.

**Comment by yaroslavsadin** [comment] 2022-12-06 18:11
@roblourens I noticed the same issue even when `useLocalServer=true`

**Comment by yaroslavsadin** [comment] 2022-12-07 11:51
I can confrim that:

![image](https://user-images.githubusercontent.com/6427691/206172131-5a420e28-474a-4e53-8203-8e92b5f7ced1.png)

I have three windows open and aftr reloading one of them:

```console
$ ps aux | grep ssh | wc -l
10
$ ps aux | grep ssh | wc -l
12
```

The probelm is when I reload too many times my server becomes unresponsive. Could this be the same issue or shall I create another one?

**Comment by roblourens** [comment] 2022-12-08 20:30
If you are on Windows, that setting is disabled even when it appears checked

**Comment by TylerLeonhardt** [comment] 2023-01-27 20:15
![image](https://user-images.githubusercontent.com/2644648/215188345-66f144c3-52cd-41a1-8fc2-17dcf017846c.png)

I still see the accumulation with Remote - SSH v0.95.2023012415

**Comment by ryanpatiency** [comment] 2023-02-01 01:26
In which release was this bug fixed? Remote - SSH v0.90.1 still has this issue windows -> Ubuntu

**Comment by eleanorjboyd** [comment] 2023-02-01 16:41
Hello! This is not yet fixed but is on our agenda for the February iteration. We do not have a finalized timeline but hopefully would be released to stable in about a month.

**Comment by roblourens** [comment] 2023-02-01 17:01
@meganrogge Setting `isTransient: false` isn't working anymore, do you know what could have changed? In my trace-level ptyHost logs, I never see this message https://github.com/microsoft/vscode/blob/6b5ec19d095970dc43bf78d3a21d10a0d81c90f7/src/vs/platform/terminal/node/ptyService.ts#L630

**Comment by meganrogge** [comment] 2023-02-01 20:28
You shouldn't see that message because it's not a persistent process, so won't be detached. do you see this? https://github.com/microsoft/vscode/blob/6b5ec19d095970dc43bf78d3a21d10a0d81c90f7/src/vs/platform/terminal/node/ptyService.ts#L294

**Comment by meganrogge** [comment] 2023-02-01 20:29
>  Moreover, these ssh processes won't be killed if I close one of three windows, they last until all the vscode windows are closed. 

This is interesting.

**Comment by roblourens** [comment] 2023-02-02 00:15
> You shouldn't see that message because it's not a persistent process

Seems like it's checking whether it should persist inside that method though. I don't see that shutDown message either

**Comment by meganrogge** [comment] 2023-02-02 16:54
Just tried via `isTransient: true` in an extension created terminal and it didn't persist. Maybe @tyriar has a thought, but this hasn't been touched/changed recently.

**Comment by roblourens** [comment] 2023-02-03 04:44
I can try to set it up to debug in OSS, what should I look at?

**Comment by meganrogge** [comment] 2023-02-03 13:56
actually, I see where there could be a bug

https://github.com/microsoft/vscode/blob/192204b5bfd1c978327debe0e68188101a515b58/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L640-L651

we might be returning at line 645 when we should be disposing of any instances with `isTransient: true`

**Comment by meganrogge** [comment] 2023-02-03 14:09
yep, without that change, when I reload with `isTransient: true` I see `WARN Couldn't get layout info, a terminal was probably disconnected Could not find pty on pty host` in the console indicating the process wasn't disposed of 

with it, I see the process killed

**Comment by meganrogge** [comment] 2023-02-03 17:23
@roblourens you can try debugging/logging around here. it appears to be doing the right thing 

https://github.com/microsoft/vscode/pull/173302#issuecomment-1416165410

**Comment by meganrogge** [comment] 2023-02-03 17:27
> actually, I see where there could be a bug
> 
> I think line 1308 should factor in `shouldPersist`
> 
> https://github.com/microsoft/vscode/blob/d4d77fbce7cdb5c7473e53b1a4da7888ea6e9794/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1308

it already factors that in

**Comment by jlynchMicron** [comment] 2023-04-24 21:44
Hi All, 
Don't want to be pushy, but are there any ideas what is causing this issue and how to remedy it?   I believe this issue is causing hundreds of zombie/extra processes/threads on a development server I help manage.  This server has lots of cores where multiple VScode developers are working on high parallelism software, so this leads to a lot of extra processes/threads being left behind.

Here is an example of what I am seeing:
![image](https://user-images.githubusercontent.com/58755604/234122967-a3ad1875-bf8b-45fb-a041-6d22a62ccfda.png)

It seems like for every process/thread being created that is doing actual work (in white) tons of clones are being made (in green).  I would normally not question this since I am not familiar with the inner workings of VScode, but it seems to be doing it for python processes I run in the terminal that I know do not spawn their own sub-processes/threads.

**Comment by meganrogge** [comment] 2023-04-24 22:43
The root cause here is probably the node processes hanging around. @deepak1556 I believe you fixed that? did you have to revert the fix?

**Comment by deepak1556** [comment] 2023-04-25 01:58
The fix has not been released to stable yet, refs https://github.com/microsoft/vscode/issues/174956. Please try with insiders and see if the issue persists.

**Comment by meganrogge** [comment] 2023-04-25 02:07
probable duplicate of #174956

**Comment by chaosite** [comment] 2023-04-30 13:45
This is effectively DoSing a shared server we use. We have a shared Linux server used by ~500 students, over time they each leave behind multiple zombie processes.

The DoS happens since each `shellIntegration-bash.sh` process takes up at least 1 pty, and by default Linux is limited to 4096 ptys. Once we hit that number, the server stops accepting new interactive ssh connections (at least `ssh -T <command>` still works).

**Comment by meganrogge** [comment] 2023-05-01 15:13
same as #179798

**Comment by roblourens** [comment] 2023-05-02 16:51
I can still repro this with my original steps

**Comment by Tyriar** [comment] 2023-05-02 22:22
vscode issue: https://github.com/microsoft/vscode/issues/179911

**Comment by Tyriar** [comment] 2023-05-02 22:24
This was meant to be fixed with a node-pty update in 1.78: https://github.com/microsoft/vscode/issues/174956#issuecomment-1494581637

@deepak1556 @rzhao271 any insights here? I'm a bit stumped.

**Comment by roblourens** [comment] 2023-05-02 22:34
FYI @meganrogge is looking into this and it seems like it is just a terminal lifecycle issue and not related to that node-pty issue

**Comment by meganrogge** [comment] 2023-05-02 23:05
In this case, the terminals are `hideFromUser` and are created before there's a `remoteTerminalBackend`. Thus, they are not tracked by either the `terminalGroupService` or the `ptyHost`, respectively. I believe something like this might fix it:

https://github.com/microsoft/vscode/commit/1f656b00750f23b70d78dedf26855a855e0db6da

**Closed** 2023-05-02 23:51 UTC
Labels: bug, ssh

**Comment by meganrogge** [comment] 2023-06-01 16:06
@roblourens I believe you verified that this was fixed before, but can you pls do so again?
