### ISSUE TITLE
Remote container extension is chewing up all my CPU for no visible reason

### ISSUE THREAD

**Issue by nrclark** [microsoft/vscode-remote-release#9154] opened 2023-10-30 18:07 UTC
Type: <b>Bug</b>

Install VScode on a mac. Use remote-host to connect to an Ubuntu 22.04 workstation. Don't use devcontainers at all, local or remote.

Extension version: 0.315.1
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 21.6.0
Modes:
Connection to 'ssh-remote+workstation' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id e25b9015-5b48-4dff-adef-964218ad56bc|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+workstation' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet0:30874138
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by iamGavinJ** [comment] 2023-11-11 16:49
Possible dupe of #9110

**Comment by roblourens** [comment] 2023-12-18 22:13
Can you explain the situation some more? Dev Containers, or Remote-SSH? What process is using high CPU?

**Closed** 2023-12-26 12:28 UTC
Labels: ssh, info-needed
