### ISSUE TITLE
Source control not showing changes automatically, visible on refresh

### ISSUE THREAD

**Issue by Norbz** [microsoft/vscode-remote-release#7453] opened 2022-11-03 16:23 UTC
Hello There. Not sure if this should be reported to this repo or the vscode main one...

I'm having issues very similar to this https://github.com/microsoft/vscode-remote-release/issues/314

On a real (yet quite small) nodeJS project, file changes are not showing in the source control tab, but I can see them when hitting the refresh button or restarting VSCode. I'm talking about 3400 files without node_modules and 45500 with node_modules. Removing them doesn't not change the behavior.

On an empty folder with just a local git  initialised, I can see files being added or modified automatically.

I should also note that every git command relying on the git remote does not work from the source control panel (pull, fetch, push etc) But i'm not sure this is the same issue or not. I'm using SSH for my git remote (git@bitbucket.org:...)

All projects are on Ubuntu filesystem under `/home/xxx/workspace/<project>`

- VSCode Version: 1.73.0 (user setup)
- Local OS Version: Windows_NT x64 10.0.19044
- Remote OS Version: Ubuntu 20.04.5 (WSL 2)
- Remote Extension/Connection Type: WSL
- Logs:

Steps to Reproduce:

1. Open a project from ubuntu (code . or code myProject/)
2. From the integrated terminal, create a file (touch testFile)
3. File isn't showing in Source Control Panel
4. Hit refresh, file is now showing in source control panel

Check to see if the problem is general, with a specific extension, or only happens when remote
Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

Hope someone can help me with this :)

**Comment by ziki77** [comment] 2023-01-18 13:19
Same issue here with WSL2 and prj in /mnt/c/.....

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by Norbz** [comment] 2023-01-19 15:23
Any news on this ?

still having the same issue, with everything updated :

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z (1 wk ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

WSL extension : v0.72.0
Remote Development extension : v0.23.0

**Comment by abhyuditjain** [comment] 2023-03-14 19:08
I am also facing the same issue.

`Version: 1.76.1 (user setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No`

**Comment by olguzzar** [comment] 2023-08-31 19:03
Also experienced this issue while running through the [Python Dev Container Sample](https://github.com/microsoft/vscode-remote-try-python).

Screen recording: 

https://github.com/microsoft/vscode-remote-release/assets/95261576/0c474c59-8b60-4a21-bccc-607271c2d88b


Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

cc @bamurtaugh

**Comment by aeschli** [comment] 2023-11-22 08:12
duplicate of https://github.com/microsoft/vscode-remote-release/issues/5000

**Closed by aeschli** 2023-11-22 08:12 UTC
Labels: wsl
