### ISSUE TITLE
Remote-WSL launching server as root instead of inheriting user env

### ISSUE THREAD

**Issue by robcee** [microsoft/vscode-remote-release#4170] opened 2020-12-10 17:54 UTC
- VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
- OS version: Windows_NT x64 10.0.19042
- Remote OS version: Linux x64 4.19.104-microsoft-standard
- Remote OS Version: (Ubuntu 20.04)
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Navigate to a code directory from a running WSL2 instance, logged in as "user"
2. launch code via `code .`
3. Open Integrated Terminal

Expected:

VS Code starts server and opens IDE with integrated Terminal as "user"

Actual:

VS Code starts server as root and integrated terminal launches as root user. Files created in IDE are owned by root user. Github integrations are broken, etc.

![Screenshot 2020-12-10 132636](https://user-images.githubusercontent.com/27976/101810329-0c20c100-3aef-11eb-885f-da0599d7b58a.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Hard to say, Remote-WSL is an extension.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.75GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+UbuntuFocal/home/rob/Projects/Nightpuck/iQPuckWeb --remote=wsl+UbuntuFocal --crash-reporter-id 6abfd936-139b-4c30-9d8d-b1561c28b8d5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: UbuntuFocal|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|25.01GB (22.80GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
antd-snippets|ban|1.2.0
vscode-icontheme-nomo-dark|be5|1.3.6
node-snippets|chr|1.3.2
vscode-firefox-debug|fir|2.9.1
dotenv|mik|1.0.1
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.61.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.11
html5-boilerplate|sid|1.1.1
npm-intellisense|chr|1.3.1
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.13
githistory|don|0.6.14
vscode-npm-script|eg2|0.3.13
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.411183155
</details>

originally filed as: https://github.com/microsoft/vscode/issues/112232

**Comment by robcee** [comment] 2020-12-10 17:59
Related, found this on StackOverflow:

https://stackoverflow.com/questions/65066617/vscode-creates-files-in-wsl2-as-root-rather-than-default-user

**Comment by robcee** [comment] 2020-12-10 18:27
attempted to reproduce this on my laptop but wasn't able to. WSL2 launches with the correct user. Something different between these two installations.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.59GB (2.35GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/rob/Projects/Nightpuck/iQPuckWeb --remote=wsl+Ubuntu-20.04 --crash-reporter-id 880485b3-7076-4576-8809-b69f64292808|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|12.16GB (10.58GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
antd-snippets|ban|1.2.0
vscode-icontheme-nomo-dark|be5|1.3.6
node-snippets|chr|1.3.2
vscode-firefox-debug|fir|2.9.1
dotenv|mik|1.0.1
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.61.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.11
html5-boilerplate|sid|1.1.1
node-essentials|afr|1.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
path-intellisense|chr|2.3.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.13
vscode-npm-source|dku|1.0.0
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.21.2
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.411183155
vscode-typescript-tslint-plugin|ms-|1.3.0
vscode-jest|Ort|3.2.0
fabric8-analytics|red|0.2.1
vscode-yaml|red|0.13.0
vs-code-node-require|tgr|1.4.7
vscodeintellicode|Vis|1.2.10
vscode-import-cost|wix|2.13.0


</details>

**Comment by robcee** [comment] 2020-12-14 15:05
A bit more context around the differences between these two systems and some possible sources of the issue.

## Desktop

The Desktop system where I am seeing the root invocation problem was an upgrade of Ubuntu 18.04 to 20.04 via dist-upgrade. It was initially a WSL 1 system, which was upgraded to WSL 2.

Listing the contents of code's binary directory on this system gives:

`-rwxrwxrwx 1 root root 1982 Dec 10 22:45 '/mnt/c/Program Files/Microsoft VS Code/bin/code'`

Invocation of WSL2 is via Windows Terminal v1.43. Settings Entry:

```        {
		    "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
		    "hidden": false,
		    "name": "Ubuntu Focal",
		    "source": "Windows.Terminal.Wsl",
            "colorScheme": "One Half Dark",
            "fontFace": "Consolas",
            "fontSize": 11,
            "acrylicOpacity": 0.8,
            "useAcrylic": true,
		},
```

## Laptop

The Laptop system, where I do not experience this issue, was a fresh WSL 2 installation of Ubuntu 20.04.

Listing the contents of code's binary directory: 

`-r-xr-xr-x 1 rob 1982 Nov 10 23:34 '/mnt/c/Program Files/Microsoft VS Code/bin/code'*`

Invocation of WSL2 is via Windows Terminal v1.43. Settings Entry:

```        {
		    "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
		    "hidden": false,
		    "name": "Ubuntu Focal",
		    "source": "Windows.Terminal.Wsl",
            "colorScheme": "One Half Dark",
            "fontFace": "Consolas",
            "fontSize": 11,
            "acrylicOpacity": 0.8,
            "useAcrylic": true,
		},
```

**Comment by robcee** [comment] 2020-12-15 15:00
Checking options on my desktop machine (where the problem exists), I found this in the WSL Extension's Settings:

![image](https://user-images.githubusercontent.com/27976/102231633-8c1aa280-3ec4-11eb-84ea-c7522b82a9d2.png)

`"remote.WSL.useShellEnvironment": true`

**Comment by robcee** [comment] 2020-12-15 15:15
verified this is also happening in 1.49 on this system as well.

**Comment by PavelSosin-320** [comment] 2020-12-15 15:53
It is even more tricky: 
Ubuntu 20.04 starts with systemd if the Ubuntu is started via its Ubuntu-20.04.exe. There is no way to pass wsl options like -u but It has sudo group,i.e. the Windows user can be assigned to the sudo group and it works like after execution sudo -i interactively. 
Other distros: if Linux user matching Windows user has no password it is possible to switch user to root uing sudo -i and it doesn't ask for the password
Yet other distros: there is /etc/sudoers file in other Linux systems and visudo utility to add the user to the sudoers
WT doesn't have a configuration option and always starts with Windows user and its environment.
Entering into distro always passing wsl -d -u options works in all cases.

**Comment by robcee** [comment] 2020-12-15 16:03
That matches what I see here because I lack any systemd on my WSL2 Ubuntu installation on Desktop. I don't have my laptop handy to check, but it I know I don't have to invoke it with that -u option on startup and it seems to be inheriting my environment correctly.

This feels like a potential configuration option for a fix. Let a user set their preferred user in a Windows Environment variable or configuration setting and then launch WSL accordingly. Being explicit rather than forcing Code to launch the correct environment based on guesswork feels like it's bound to have some funny edge cases, mine included.

**Comment by PavelSosin-320** [comment] 2020-12-15 16:33
@robcee Ubuntu and Ubuntu 20.04 with Kube installed are 2 very different distros. In Ubuntu 20.04 the problem of systemd is solved in some secret way although WSL team insists that it is absolutely impossible. If distro supports systemd all servers must be started using systemd units. In Ubuntu 20.04 Microk8s is started in this way. But it causes other problems: 1.configurations for root and rootless users may differ. 2.There is a special authentication systemd daemon assigning users to namespaces. This feature is required only by docker,podman,runc,crun,containerd, and their friends.

**Comment by robcee** [comment] 2020-12-15 17:08
interesting, and even more complicated. I wasn't aware there were two WSL Ubuntu distros available. I don't have k8s installed here.

**Comment by robcee** [comment] 2020-12-18 12:31
is there anyway I can force code to run the server as a specific user? Would love a workaround for this, even if that means launching the server manually or via a script.

**Comment by PavelSosin-320** [comment] 2020-12-18 12:57
@robcee Of course, you can do it from the command line or powershell: wsl **-d your-desired-distro** **-u your-desired-user** the-command-starting-server.
Also fro bat file or powershell ps script. Also scheduled as described here [run powershell script scheduled](https://blog.netwrix.com/2018/07/03/how-to-automate-powershell-scripts-with-task-scheduler/)

**Comment by robcee** [comment] 2020-12-18 14:30
thanks, @PavelSosin-320! I’ll experiment and see if I can get something working here.

**Comment by robcee** [comment] 2021-01-04 10:42
I found a work-around embedded here: https://github.com/microsoft/WSL/issues/4276.

It describes the same problem I was experiencing, and a couple of different ways of mitigating it by setting the default user that wsl starts with. The solution I ended up using was creating `/etc/wsl.conf` and specifying my default user there.

documentation for this is here: https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980

I've also found this issue, which is similar to this one: https://github.com/microsoft/vscode-remote-release/issues/286.

**Comment by aeschli** [comment] 2021-01-19 14:37
This is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/286
For now, the WSL remote extension always uses the default user.

See https://github.com/microsoft/vscode-remote-release/issues/286#issuecomment-492402644 on how to change the WSL default user.

**Closed by aeschli** 2021-01-19 14:37 UTC
Labels: bug, plan-review, wsl
