### ISSUE TITLE
Cannot open remote docker since upgrade macOS Catalina

### ISSUE THREAD

**Issue by Yablon** [microsoft/vscode-remote-release#1654] opened 2019-10-12 07:26 UTC
- VSCode Version: 1.39.1
- Local OS Version: macOS Catalina(10.15)
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open remote docker and select one container
2. Wait until:
Error: cannot open file:///Users/someone/Library/Application%20Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/imageConfigs/f793.json. Detail: Cannot read file(Error: Cannot find file(/Users/dingkuo/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/imageConfigs/f793.json))
    at n.then.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4707:361)

Does this issue occur when you try this locally?: I can open remote ssh.
Does this issue occur when you try this locally and all extensions are disabled?: I cannot open remote docker since I upgrade the macOS Catalina.

Thank you for your attention!

**Comment by Yablon** [comment] 2019-10-12 07:29
#1649

**Comment by Sumi-Sumi** [comment] 2019-10-12 13:51
I face same question but I have different environment.
My environment
* VScode Version: 1.39.1
* Local OS Version: Ubuntu18.04
* Remote OS Version: Ubuntu 18.04
* Remote Extension/Connection Type: Docker

Made sure Docker didn't have problem. (I opened Jupyter NoteBook in Docker)
I used this function yesterday.

Thank you.

**Comment by chrmarti** [comment] 2019-10-21 10:16
Very much looks like a duplicate of #1649.

/duplicate #1649

**Closed** 2019-10-21 10:16 UTC
Labels: *duplicate
