### ISSUE TITLE
Performance issue: Remote - SSH

### ISSUE THREAD

**Issue by georgitrifonov** [microsoft/vscode-remote-release#2495] opened 2020-03-09 11:47 UTC
Issue Type: <b>Bug</b>

The CPU and memory are too high on the remote VM after opening "Explorer" and I choose to see all directories "/".

Extension version: 0.49.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-957.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.0.5.127|
|OS|Linux x64 3.10.0-957.el7.x86_64|
|CPUs|Common KVM processor (3 x 2299)|
|Memory (System)|3.70GB (1.41GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment] 2020-03-09 21:35
Can you use the process explorer, or run `code --status` to check which processes are using high cpu/memory? It is probably the file watcher, in which case this goes with https://github.com/microsoft/vscode-remote-release/issues/2349

**Comment by georgitrifonov** [comment] 2020-03-10 15:27
[https://photos.google.com/share/AF1QipMoo8zGbrID3yLgWQo5T4xEvzPBQXgVe_6hXxhc-MC4he9XOXqqfTSE0PMgTy8-aA/photo/AF1QipM8fUMHLzA_04YzgnHIQbBSRpzfWzZFrlKeEJpo?key=RW9LM25fdk5zX2JTQl9FcmdFcnk5VTNWTmFyWVVR](url)

**Comment by roblourens** [comment] 2020-03-11 05:06
It looks like some extension is searching for `**/package.json`, do you know which extension that might be?

**Comment by georgitrifonov** [comment] 2020-03-11 07:19
I have no idea.

These are all extensions I have: [https://photos.google.com/share/AF1QipN1MNtzIuDBSYuoeoA8qtvTK4rGvxkBj85U7xwrpH1ZRKqKOIyyuyQ5bXDeGR1Sdw/photo/AF1QipPh5wPAYzNMRKvDQCiDiFDHRTapYP2YwTyv9Rt0?key=SGpDemE2Q2VHcmZRRy1vSmNFSURCNThwY1h1S0dn](url)

**Comment by roblourens** [comment] 2020-11-05 22:26
And so this was happening when opening the root `/`? I will call it a dupe of https://github.com/microsoft/vscode-remote-release/issues/1257

**Closed by roblourens** 2020-11-05 22:26 UTC
Labels: needs-more-info, ssh
