### ISSUE TITLE
Remote - Docker cant find ca.pem on remote host VS Code Insiders

### ISSUE THREAD

**Issue by DiDeoxy** [microsoft/vscode-remote-release#1552] opened 2019-10-01 16:45 UTC
- VSCode Version: 1.39.0-insider
- OS Version:
Windows_NT x64 10.0.18362
Steps to Reproduce:

1. Open a devcontainer on a remote host by setting DOCKER_HOST and using an SSH tunnel
2. get error message:

Setting up container for folder or workspace: c:\Users\mhargreaves\repos\devcontainers\R
Run: docker build -f c:\Users\mhargreaves\repos\devcontainers\R\.devcontainer\Dockerfile -t vsc-r-ebf94a90a032f620bff1a2473e6e5625 c:\Users\mhargreaves\repos\devcontainers\R\.devcontainer
unable to resolve docker endpoint: open undefined\ca.pem: The system cannot find the path specified.
Failed: Building an image from the Dockerfile.
Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker.exe build -f c:\Users\mhargreaves\repos\devcontainers\R\.devcontainer\Dockerfile -t vsc-r-ebf94a90a032f620bff1a2473e6e5625 c:\Users\mhargreaves\repos\devcontainers\R\.devcontainer

Does this issue occur when all extensions are disabled?: Yes/No

Requires extensions

**Comment by Chuxel** [comment] 2019-10-01 19:08
Possible dupe of #1550 

@DiDeoxy Did you specify `docker.host` in `settings.json`?

**Comment by DiDeoxy** [comment] 2019-10-01 19:33
It is a dupe of 1550, sorry about that. I also find it works in stable vs code.

I have specified docker.host. I haven't touched a thing since yesterday when it worked. Only difference is I restarted vs code insiders.

**Comment by Chuxel** [comment] 2019-10-01 19:35
@DiDeoxy No worries yours came in around the same time. Yes, this is a very recent change, so you can watch #1550 for updates. Closing as dupe.

**Closed by Chuxel** 2019-10-01 19:35 UTC
Labels: *duplicate
