### ISSUE TITLE
Allow for @ Symbol in username

### ISSUE THREAD

**Issue by shockogit** [microsoft/vscode-remote-release#5686] opened 2021-10-07 14:57 UTC
The extension (ID ms-vscode-remote.remote-ssh) does not appear to handle usernames with the @ symbol in the path. For example, on a domain joined Linux system I might logon as follows:

- ssh 'user@domain'@hostname
- ssh -l user@domain hostname

The extension seems to parse the username and strip the quote characters

**Comment by shockogit** [comment] 2021-11-02 10:22
> Just to clarify then `user@mydomain.com` is your User.
> 
> And `myhost.mydomain.com` is the remote you're trying to ssh into?
> 
> When I run it on my end I am successfully able to log into a remote where my User contains `@`

Can you post the contents of your config file?

**Comment by tanhakabir** [comment] 2021-11-02 17:29
```
Host 147.182.250.143
  HostName 147.182.250.143
  User foo@bar
```
Where I created an account on my VM with an `@` sign.

And I received this:
![image](https://user-images.githubusercontent.com/12758612/139915566-ce4a6d4a-3ede-480b-a823-1c4136eb78e2.png)


> 'enter the password for @myhost.mydomain.com'

Is the issue that it wasn't `Enter password for myuser@mydomain.com@myhost.mydomain.com`?

**Comment by shockogit** [comment] 2021-11-03 10:34
This seems to ebbe be resolved in the latest version released yesterday: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh&ssr=false#version-history. Trying to find what;s been fixed in this release

**Comment by tanhakabir** [comment] 2021-11-03 16:40
We don't exactly have a CHANGELOG for the SSH extension but these were the bugs that were fixed in the last release: https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+milestone%3A%22October+2021%22+is%3Aclosed+label%3Assh

If the problem is solved I'll close this issue! Let me know if it isn't resolved for you

**Closed by tanhakabir** 2021-11-03 16:40 UTC
Labels: ssh, needs more info
