### ISSUE TITLE
Fail to clone private repo is container volume

### ISSUE THREAD

**Issue by Zenthae** [microsoft/vscode-remote-release#9353] opened 2023-12-28 23:22 UTC
Type: <b>Bug</b>

VS Code fail to clone private GitHub repository in container volume. I don't see any error, it just stops. I tested with public containers from my account and the sample, everything is working fine.
SSH key is fine too, I tested it and I can manually clone the repo with `git clone git:github.com:Zenthae/gook.git`

`git ls-remote https://github.com/Zenthae/gook.git` is not working though, as it's asking for HTTPS credentials, which are not allowed anymore with GitHub

```log
[2023-12-28T22:57:21.694Z] Start: Run: wsl -d Docker -e wslpath -u C:\Program Files\Microsoft VS Code
[2023-12-28T22:57:21.694Z] Dev Containers 0.327.0 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
[2023-12-28T22:57:21.782Z] Stop (88 ms): Run: wsl -d Docker -e wslpath -u C:\Program Files\Microsoft VS Code
[2023-12-28T22:57:21.784Z] Start: Run: wsl -d Docker -e /bin/sh -c cd '/mnt/c/Program Files/Microsoft VS Code' && /bin/sh
[2023-12-28T22:57:21.786Z] Start: Run in host: id -un
[2023-12-28T22:57:21.843Z] root
[2023-12-28T22:57:21.843Z] 
[2023-12-28T22:57:21.843Z] Stop (57 ms): Run in host: id -un
[2023-12-28T22:57:21.844Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2023-12-28T22:57:21.845Z] Stop (1 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2023-12-28T22:57:21.845Z] Start: Run in host: echo ~
[2023-12-28T22:57:21.846Z] /root
[2023-12-28T22:57:21.846Z] 
[2023-12-28T22:57:21.846Z] Stop (1 ms): Run in host: echo ~
[2023-12-28T22:57:21.846Z] Start: Run in host: test -x '/root/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node'
[2023-12-28T22:57:21.847Z] 
[2023-12-28T22:57:21.847Z] 
[2023-12-28T22:57:21.847Z] Stop (1 ms): Run in host: test -x '/root/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node'
[2023-12-28T22:57:21.847Z] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.327.0.js'
[2023-12-28T22:57:21.848Z] 
[2023-12-28T22:57:21.848Z] 
[2023-12-28T22:57:21.848Z] Stop (1 ms): Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.327.0.js'
[2023-12-28T22:57:21.849Z] userEnvProbe: loginInteractiveShell (default)
[2023-12-28T22:57:21.849Z] userEnvProbe: not found in cache
[2023-12-28T22:57:21.849Z] userEnvProbe shell: /bin/bash
[2023-12-28T22:57:21.889Z] userEnvProbe PATHs:
Probe:     'redacted'
Container: None
[2023-12-28T22:57:21.917Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2023-12-28T22:57:21.947Z] Stop (30 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2023-12-28T22:57:21.947Z] 1.43
[2023-12-28T22:57:26.917Z] Start: Run in Host: git ls-remote https://github.com/Zenthae/gook.git
[2023-12-28T22:57:44.157Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2023-12-28T22:57:44.190Z] Stop (33 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2023-12-28T22:57:44.190Z] 1.43
[2023-12-28T22:57:50.926Z] Start: Run in Host: git ls-remote https://github.com/Zenthae/it_management.git
[2023-12-28T23:04:41.330Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2023-12-28T23:04:41.364Z] Stop (34 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2023-12-28T23:04:41.364Z] 1.43
[2023-12-28T23:04:46.461Z] Start: Run in Host: git ls-remote https://github.com/Zenthae/gook.git
```

Extension version: 0.327.0
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by evanyu10** [comment] 2024-01-09 22:11
Just realized that this issue exists after submitting my own

**Comment by JOSEPHGILBY** [comment] 2024-01-25 19:10
This appears to be the same as issue #9163 .

**Comment by JOSEPHGILBY** [comment] 2024-01-28 00:35
I still want to get that issue some attention since they haven't even put these git ls-remote hanging issues on backlog.

**Comment by evanyu10** [comment] 2024-01-28 01:41
Yeah. Sorry, I have been backed up with my feasibility report for my
capstone project. I just put in my 2 weeks at my weekend job so I can focus
more on this project.

**Comment by Malix-off** [comment] 2024-06-15 18:53
still.

**Comment by rgalonso** [comment] 2024-08-19 17:13
Please see my comments in [#9377](https://github.com/microsoft/vscode-remote-release/issues/9377#issuecomment-2297030387) and [#9163](https://github.com/microsoft/vscode-remote-release/issues/9163#issuecomment-2297045772).

**Comment by Malix-Labs** [comment] 2024-10-25 18:25
May be duplicate of #9163

**Comment by Malix-Labs** [comment] 2024-10-25 18:26
duplicate of #9163

**Comment by bamurtaugh** [comment] 2024-12-13 00:10
Thanks all for the feedback and link to the duplicate!

**Closed by bamurtaugh** 2024-12-13 00:10 UTC
Labels: containers
