### ISSUE TITLE
 Remote container: some Ruby extensions no work 

### ISSUE THREAD

**Issue by JMDC-SUN** [microsoft/vscode-remote-release#1028] opened 2019-07-25 10:44 UTC
I am developing a ruy/rails App  in Remote container by Attach Vscode.
But some extensions is no work.

- Local OS Version:
   Windows10
- Remote OS Version:
  CentOS7 
- Remote Extension/Connection Type: SSH/Docker/WSL
  Docker/Remote container

Steps to Reproduce:

1. Install Ruby and Rufo

2. Install vscode-rufo extension.
    https://github.com/bessey/vscode-rufo

3. When I save file, the error occured
> /bin/sh: rufo: command not found

**Comment by Chuxel** [comment] 2019-07-25 13:44
@JMDC-SUN Can you post your Dockerfile? Tough to repro without the container.

**Comment by JMDC-SUN** [comment] 2019-07-26 00:44
Thank you very much. Ruby extensions had worked a week ago, but no work in recent week.
It is my docker file.
`FROM centos/ruby-25-centos7:2.5
USER root
SHELL ["/bin/bash", "-c"]
 
### openss1.1.1を導入 ###
RUN yum-config-manager --enable rhel-server-rhscl-7-rpms
RUN yum-config-manager --enable rhel-7-server-optional-rpms
RUN yum -y update
RUN yum  -y groupinstall "Development Tools"
RUN yum -y remove openssl
RUN yum install -y xz wget libffi libffi-devel bzip2-devel ncurses-devel gdbm-devel xz-devel sqlite-devel readline-devel zlib-devel libuuid-devel chrpath strace gdb sudo vim -y
WORKDIR /tmp
RUN wget 'https://www.openssl.org/source/openssl-1.1.1.tar.gz'
RUN tar -xf openssl-1.1.1.tar.gz
WORKDIR /tmp/openssl-1.1.1
RUN ls
RUN ./config shared --prefix=/usr/local/openssl11 --openssldir=/usr/local/openssl11 && make && make install
RUN ln -s /usr/local/openssl11/lib/libssl.so.1.1 /usr/lib64/libssl.so.1.1
RUN ln -s /usr/local/openssl11/lib/libcrypto.so.1.1 /usr/lib64/libcrypto.so.1.1

### Nodejs,yarnのインストール ### 
### yarnのnodejsのバージョンはV8までで、V10を削除する
RUN yum remove rh-nodejs10-nodejs.x86_64 -y 
RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash
RUN yum install -y nodejs
RUN curl -o- -L https://yarnpkg.com/install.sh | bash
RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
RUN yum install yarn -y

### gitの最新バージョンをインストール
RUN yum -y install curl-devel expat-devel gettext-devel  openssl-devel zlib-devel gcc perl-ExtUtils-MakeMaker
RUN yum -y remove git
WORKDIR /tmp
RUN wget https://www.kernel.org/pub/software/scm/git/git-2.21.0.tar.gz
RUN tar -xf git-2.21.0.tar.gz
WORKDIR /tmp/git-2.21.0
RUN make configure
RUN make prefix=/usr/local all
RUN make prefix=/usr/local install
RUN source /etc/bashrc
RUN git --version

RUN sudo yum install -y gcc ruby-devel zlib-devel
RUN mkdir /myapp
WORKDIR /myapp
ENV LANG C.UTF-8
ENV RAILS_ENV local
ADD Gemfile /myapp/Gemfile
ADD Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
ADD . /myapp
`

It is my docker-compose file for starting container.
`version: '3'
services:
  #vertica:
  #  image: "cjonesy/docker-vertica:9.1.1-0"
  #  ports:
  #    - "5433:5433"

  app: &app_base
    container_name: "app_${USER}"
    build: .
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle
      - yarn-cache:/usr/local/share/.cache/yarn/v4
      - vscodesetting1:/opt/app-root/src/.vscode-remote
      - vscodesetting2:/opt/app-root/src/.vscode-server-insiders
      - ~/.gitconfig:/opt/app-root/src/.gitconfig
    ports:
      - "3000:3000"
      - "3035:3035"
      - "7658:7658"
    command: bash -c "rm -f /myapp/tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"


volumes:
  bundle_data:
    driver: local
  
  yarn-cache:
    driver: local
  
  vscodesetting1:
    driver: local

  vscodesetting2:
    driver: local
`

**Comment by chrmarti** [comment] 2020-10-13 13:43
Could be related to us no longer reading the environment variables set by the shell startup scripts. You can now turn this back on in the devcontainer.json with `"userEnvProbe": "loginInteractiveShell"`.

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/3224.

**Closed by chrmarti** 2020-10-13 13:43 UTC
Labels: containers
