### ISSUE TITLE
SSH Agent Forwarding doesn't work when inheritEnv is disabled

### ISSUE THREAD

**Issue by carljmitchell** [microsoft/vscode-remote-release#1835] opened 2019-11-13 00:07 UTC
Issue Type: <b>Bug</b>

I am using my local desktop's public SSH key for accessing Azure DevOps Repos. I would like to sync those repos on remote machines using VSCode and the Remote-SSH extension using Agent Fowarding from my local desktop. Command line git works from SSH terminals outside of VSCode. The git UI works inside VSCode. Command line git does not work on terminals spawned within VSCode, instead prompting me with the following:
```
git@ssh.dev.azure.com's password:
```

Extension version: 0.47.2
VS Code version: Code - Insiders 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37, 2019-11-12T05:39:58.193Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-1061-azure

**Comment by roblourens** [comment] 2019-11-30 20:50
Could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by carljmitchell** [comment] 2019-12-02 17:21
Here is the log:
[remote-ssh-log.txt](https://github.com/microsoft/vscode-remote-release/files/3912395/remote-ssh-log.txt)

**Comment by roblourens** [comment] 2019-12-02 18:21
Please try `ssh-add -l` in the terminal and check whether you get the keys that you expect from the local agent. If not, look for the line like this:

`Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-8RJ6PP18h7/agent.126630" "/tmp/vscode-ssh-auth-sock-62636700"`

And check whether both those files exists, and the second is symlinked to the first.

**Comment by carljmitchell** [comment] 2019-12-02 19:49
I did a bit more experimenting on this and found that the issue is somewhat transient. It seems that in scenarios where a new remote server is established (e.g. because I have just restarted the remote machine), my ssh-agent forwarding works properly. In scenarios where a remote server is already running, my ssh-agent forwarding fails. In both cases, those two files exist and are properly symlinked (though are different pairs of files in the two logs). Below are the logs for the two different scenarios I'm experiencing.

New remote server, ssh-agent forwards successfully:
[good_log.txt](https://github.com/microsoft/vscode-remote-release/files/3913057/good_log.txt)

Found running server, ssh-agent forwarding fails:
[bad_log.txt](https://github.com/microsoft/vscode-remote-release/files/3913058/bad_log.txt)

**Comment by roblourens** [comment] 2019-12-02 19:54
It sounds like maybe the `SSH_AUTH_SOCK` variable isn't set properly? Can you check `echo $SSH_AUTH_SOCK`?

**Comment by carljmitchell** [comment] 2019-12-02 21:01
Yup, looks like that's the issue.

From the log output that works:
`[12:59:02.672] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-WIiDh8p5ws/agent.2865" "/tmp/vscode-ssh-auth-sock-420451055"`
Then echo $SSH_AUTH_SOCK gives:
`/tmp/ssh-WIiDh8p5ws/agent.2865`

From the log output that fails because it found an already-running server:
`[13:00:04.916] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-qJv1Faiwnd/agent.3268" "/tmp/vscode-ssh-auth-sock-208739934"`
Then echo $SSH_AUTH_SOCK still gives:
`/tmp/ssh-WIiDh8p5ws/agent.2865`

So it looks like the auth sock variable isn't being updated when connecting to an existing server.

**Comment by roblourens** [comment] 2019-12-02 22:39
It should actually be `/tmp/vscode-ssh-auth-sock-420451055`. Otherwise it won't work after reconnection. So we are failing to set it at all.

Can you run "Set Log Level", pick "Trace", run "Reload Window", then share the log file from `~/.vscode-server-insiders/.<currenthash>.log`? It might not have useful info. I am actually adding another logging statement to help understand this.

**Comment by carljmitchell** [comment] 2019-12-02 23:12
Attached.

[current.log](https://github.com/microsoft/vscode-remote-release/files/3913702/current.log)

**Comment by roblourens** [comment] 2019-12-02 23:17
Yeah nothing stands out. Tomorrow's insiders will also explicitly log the initial remote env so we should see if we at least got to the point of trying to set the SSH_AUTH_SOCK variable but I don't know why we wouldn't.

**Comment by carljmitchell** [comment] 2019-12-05 00:19
No, nothing in my bashrc or profile touches SSH_AUTH_SOCK. Attaching the most recent REMOTE-SSH output and <currenthash>.log below, hopefully with the new logging from your changes:

[current_log.txt](https://github.com/microsoft/vscode-remote-release/files/3924524/current_log.txt)
[remote_ssh.txt](https://github.com/microsoft/vscode-remote-release/files/3924525/remote_ssh.txt)

**Comment by roblourens** [comment] 2019-12-06 03:26
Ok, so that shows that we tried to spawn the remote EH process with the correct SSH_AUTH_SOCK. I still don't know where it would have gone. Can you check the remote process's environment manually like this?

- Help > Open Process Explorer
- Find the pid of the remote extension host (at the bottom of the list under the section for your remote, the `extensionHost` row)
- Run `cat /proc/<pid>/environ`

That should show the actual environment of the remote EH. Also, you aren't using tmux or a similar tool right?

**Comment by carljmitchell** [comment] 2019-12-06 18:03
Nope, no tmux or screen. Environment log attached:
[env.txt](https://github.com/microsoft/vscode-remote-release/files/3933395/env.txt)

**Comment by roblourens** [comment] 2019-12-06 18:18
Ok, that proves that the remote EH has the correct environment, and the terminal is not getting it. What can you tell me about your shell and terminal setup, do you have any terminal settings in vscode set?

**Comment by PiotrCzapla** [comment] 2019-12-15 23:26
I have very similar issue. The extensionHost has SSH_AUTH_SOCK set while the terminal does not. It seems it is due to the fact that it is spawned from 'remote agent' process instead of 'extensionHost'.
See attached screenshot
<img width="868" alt="Screenshot 2019-12-16 at 00 26 37" src="https://user-images.githubusercontent.com/340180/70870997-bc222380-1f9a-11ea-8301-5900bc888ba5.png">

**Comment by roblourens** [comment] 2019-12-16 01:10
Have you set `terminal.integrated.inheritEnv` to false? Wonder if it has anything to do with that.

**Comment by quartox** [comment] 2019-12-26 19:12
Can confirm I see this issue with `terminal.integrated.inheritEnv` set to false (the default) and it is fixed with `terminal.integrated.inheritEnv` set to true.

**Comment by roblourens** [comment] 2019-12-27 15:03
Thanks. I'm not sure how to handle this scenario.

**Comment by Tyriar** [comment] 2019-12-27 16:06
Sounds like it's acting as designed since the environment isn't getting inherited from the window. I don't see a way that we could special case only the ssh variable to not respect inheritEnv, that also sounds like a bad idea. Suggest closing as designed?

**Comment by quartox** [comment] 2019-12-27 16:28
For me the only reason it was turned off was a warning about conda environments. Can we alter that warning or make a separate warning about other environment variables being lost?

**Comment by Tyriar** [comment] 2019-12-27 16:29
What warning?

**Comment by quartox** [comment] 2019-12-27 17:13
I guess it is coming from the python extension.

```
We noticed you're using a conda environment. If you are experiencing issues with this environment in the integrated terminal, we recommend that you let the Python extension change "terminal.integrated.inheritEnv" to false in your user settings.
```

It points to [this link](https://code.visualstudio.com/updates/v1_36#_launch-terminals-with-clean-environments). The final sentence of this section is `"The default value for terminal.integrated.inheritEnv is true, which is the previous behavior, but we will probably switch the value to false in the future."`

**Comment by Tyriar** [comment] 2019-12-27 17:18
@quartox yes it is, maybe they should indicate that it doesn't work properly in remote workspaces or something. inheritEnv has other issues as well and needs to be fixed eventually (https://github.com/microsoft/vscode/issues/76542), this problem seems to be that the ssh extension and python extensions conflict with each other.

**Comment by quartox** [comment] 2019-12-27 19:20
One other comment that may or may not be relevant. The `SSH_AUTH_SOCK` is set to a different value from using ssh from a terminal. If the plan is to make inheritEnv false more common, then it might be useful to have the terminal environment similar to any other terminal environment. I don't understanding how it works, however, so I can only speak to how a user might expect it to behave.

**Comment by roblourens** [comment] 2019-12-30 19:20
For now I just have to say that agent forwarding isn't supported when inheritEnv is disabled. I'm not sure how else to get the SSH_AUTH_SOCK into the terminal unless I 

- manipulate `terminal.integrated.env.linux`
- make it a predictable value that a user can set in their own bash profile

**Comment by carljmitchell** [comment] 2019-12-30 20:09
Modifying the `terminal.integrated.inheritEnv` setting to `true` resolved this issue for me (as well as an issue I was having with my conda environment on the remote machine).

I ran into some confusion with this setting, as it appeared in both the VSCode default settings.json (set to true) and in my personal user settings.json (set to false). I don't believe I set this myself, so I'm guessing an extension may have done so. In case anyone else runs into the same issue in the future, check your personal settings.json.

**Closed** 2021-03-03 04:43 UTC
Labels: bug, ssh

**Comment by JacksonKearl** [comment] 2021-03-26 18:50
Steps?

**Comment by roblourens** [comment] 2021-03-26 19:08
- Set `"terminal.integrated.inheritEnv": false`
- Connect to an SSH remote
- Check that `SSH_AUTH_SOCK` is set in the terminal, to something that has `vscode` in the path

**Comment by JacksonKearl** [comment] 2021-03-26 19:27
I see the variable empty with "terminal.integrated.inheritEnv":  true or false.. this is connecting to. prallels vm

**Comment by roblourens** [comment] 2021-03-26 19:44
Hard to set up... I've verified it
