### ISSUE TITLE
Invisible git buttons

### ISSUE THREAD

**Issue by ignishub** [microsoft/vscode-remote-release#1189] opened 2019-08-17 20:05 UTC
![image](https://user-images.githubusercontent.com/1565839/63216744-dcec8080-c142-11e9-91bb-55ad4cafb475.png)

Git buttons is invisible in this extensions. AND at starts as there is no changes at all with just files as like repository is just initialized

- Latest Stable 
- Windows 10 18963 Insiders
- Pengwin(WLinux)
- No remote extensions 

Also testet on other machine with 
- Latest VSCode Insiders 
- Windows 10 18956 Insiders
- Pengwin(WLinux)
- Golang extension

**Comment by ignishub** [comment] 2019-08-19 12:07
On new vscode insiders buttons sometimes is visible. But at start repository changes is full of files without changes.

**Comment by egamma** [comment] 2019-08-20 09:57
duplicate of  #687

**Closed** 2019-08-20 10:52 UTC
