### ISSUE TITLE
No parameter config equivalent to `--ssh default` in build parameters to support pip ssh requirements installations

### ISSUE THREAD

**Issue by highronn** [microsoft/vscode-remote-release#5855] opened 2021-11-10 12:53 UTC
When I build my dev container image I need to install some python requirements through pip that reference a specific repository commit.
To do so when I build my image myself I just need to pass `--ssh default` to my `docker build` command in order to use any ssh key declared via `ssh-add` command.
I've red the doc and didn't find any way to specify at build time this argument.
Do you think its possible to add this functionality?
I'm genuinely inclined to do if you give me some guidance on where to do it :D

**Comment by Chuxel** [comment] 2021-11-10 15:19
This sounds one of the use cases for https://github.com/microsoft/vscode-remote-release/issues/4352 on the surface since the same scenario is mentioned there.  However, we could keep this open for a specific property and for consideration for the dev container CLI. Thoughts @chrmarti ?

**Comment by highronn** [comment] 2021-11-10 17:01
Actually - I found this [issue](https://github.com/microsoft/vscode-remote-release/issues/3545) which try to solve the problem in a more generic way. If you think its better to do it the generic way, I can put an eye on it.

**Comment by Chuxel** [comment] 2021-11-10 18:18
Makes sense. Let's close this as a dupe of #3545.

**Closed by Chuxel** 2021-11-10 18:18 UTC
Labels: containers, feature-request
