### ISSUE TITLE
Unable to set up a remote SSH using VSCode

### ISSUE THREAD

**Issue by peminguyen** [microsoft/vscode-remote-release#3889] opened 2020-10-22 03:28 UTC
I really like using VS Code to edit my code via SSH. Although I am able to ssh to my remote server using Terminal, or even the Terminal in VS Code, I can't set up the remote SSH server using the VS Code remote-ssh extension. It keeps saying that I can't access it. Here's the output from console.

```
[20:25:31.436] Log Level: 2
[20:25:31.440] remote-ssh@0.55.0
[20:25:31.441] darwin x64
[20:25:31.442] SSH Resolver called for "ssh-remote+toriel.cs.washington.edu", attempt 1
[20:25:31.443] SSH Resolver called for host: toriel.cs.washington.edu
[20:25:31.443] Setting up SSH remote "toriel.cs.washington.edu"
[20:25:31.450] Acquiring local install lock: /var/folders/7t/b50905x50q51qt6sccm0m2vr0000gn/T/vscode-remote-ssh-toriel.cs.washington.edu-install.lock
[20:25:31.466] Looking for existing server data file at /Users/peminguyen/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-toriel.cs.washington.edu-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json
[20:25:31.469] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[20:25:31.470] Install and start server if needed
[20:25:31.477] Checking ssh with "ssh -V"
[20:25:31.501] > OpenSSH_7.9p1, LibreSSL 2.7.3

[20:25:31.507] askpass server listening on /var/folders/7t/b50905x50q51qt6sccm0m2vr0000gn/T/vscode-ssh-askpass-cd8f5ede41289fca5c4f67e9f67cfdf73dc283e0.sock
[20:25:31.508] Spawning local server with {"ipcHandlePath":"/var/folders/7t/b50905x50q51qt6sccm0m2vr0000gn/T/vscode-ssh-askpass-a83c6ca82090fe30f1ff294be31654f1f1f5a65b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","55481","-o","ConnectTimeout=15","toriel.cs.washington.edu"],"dataFilePath":"/Users/peminguyen/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-toriel.cs.washington.edu-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json"}
[20:25:31.508] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/7t/b50905x50q51qt6sccm0m2vr0000gn/T/vscode-ssh-askpass-cd8f5ede41289fca5c4f67e9f67cfdf73dc283e0.sock"}
[20:25:31.514] Spawned 22383
[20:25:31.716] > local-server> Spawned ssh: 22384
[20:25:31.731] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[20:25:31.963] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:L53PQY9bGdeZ+YkArVPlPK3q+4GZejzf0rUEDXjohWc
[20:25:32.397] Got askpass request: {"request":"pemi@toriel.cs.washington.edu's password:"}
[20:25:32.397] Showing password prompt
[20:25:32.399] Listening for interwindow password on /var/folders/7t/b50905x50q51qt6sccm0m2vr0000gn/T/vscode-ssh-askpass-a51f3c9ca51ef5fc29569708481de178cd7a25a0.sock
[20:25:32.399] Writing password prompt to globalState
[20:25:34.388] Got password response
[20:25:34.388] Interactor gave response: **********
[20:25:34.388] Cleaning up other-window auth server
[20:25:34.473] stderr> Authenticated to toriel.cs.washington.edu ([172.28.4.118]:22).
[20:25:34.649] > Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-135-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> 647 packages can be updated.
> 557 updates are security updates.
> 
> New release '18.04.5 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
[20:25:34.698] > ready: 6cee17fc68d9
[20:25:34.748] > Linux 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018
[20:25:34.749] Platform: linux
[20:25:34.855] stderr> bash: line 1: SCH_DIR/server.sh: No such file or directory
[20:25:34.856] stderr> bash: line 2: syntax error near unexpected token `then'
[20:25:34.856] stderr> bash: line 2: `	then'
[20:25:34.858] > 6cee17fc68d9: running
[20:25:34.858] stderr> -sh: 4: function: not found
[20:25:34.858] stderr> -sh: 23: [[: not found
[20:25:34.860] stderr> -sh: 86: Syntax error: "(" unexpected (expecting "then")
[20:25:34.862] stderr> Transferred: sent 15128, received 3508 bytes, in 0.4 seconds
[20:25:34.862] stderr> Bytes per second: sent 38905.5, received 9021.7
[20:25:34.863] > local-server> ssh child died, shutting down
[20:25:34.869] Local server exit: 0
[20:25:34.870] Received install output: OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:L53PQY9bGdeZ+YkArVPlPK3q+4GZejzf0rUEDXjohWc
Authenticated to toriel.cs.washington.edu ([172.28.4.118]:22).
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-135-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

647 packages can be updated.
557 updates are security updates.

New release '18.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

ready: 6cee17fc68d9
Linux 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018
bash: line 1: SCH_DIR/server.sh: No such file or directory
bash: line 2: syntax error near unexpected token `then'
bash: line 2: `	then'
6cee17fc68d9: running
-sh: 4: function: not found
-sh: 23: [[: not found
-sh: 86: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 15128, received 3508 bytes, in 0.4 seconds
Bytes per second: sent 38905.5, received 9021.7

[20:25:34.870] Stopped parsing output early. Remaining text: OpenSSH_7.9p1, LibreSSL 2.7.3debug1: Server host key: ecdsa-sha2-nistp256 SHA256:L53PQY9bGdeZ+YkArVPlPK3q+4GZejzf0rUEDXjohWcAuthenticated to toriel.cs.washington.edu ([172.28.4.118]:22).Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-135-generic x86_64) * Documentation:  https://help.ubuntu.com * Management:     https://landscape.canonical.com * Support:        https://ubuntu.com/advantage647 packages can be updated.557 updates are security updates.New release '18.04.5 LTS' available.Run 'do-release-upgrade' to upgrade to it.ready: 6cee17fc68d9Linux 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018bash: line 1: SCH_DIR/server.sh: No such file or directorybash: line 2: syntax error near unexpected token `then'bash: line 2: `	then'6cee17fc68d9: running-sh: 4: function: not found-sh: 23: [[: not found-sh: 86: Syntax error: "(" unexpected (expecting "then")Transferred: sent 15128, received 3508 bytes, in 0.4 secondsBytes per second: sent 38905.5, received 9021.7
[20:25:34.871] Failed to parse remote port from server output
[20:25:34.876] Resolver error: Error: 
	at Function.Create (/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130564)
	at Object.t.handleInstallOutput (/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:127671)
	at Object.t.tryInstallWithLocalServer (/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /Users/peminguyen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[20:25:34.878] ------
```

Thanks a lot!

**Comment by bamurtaugh** [comment] 2020-10-28 23:47
Possibly related to/dupe of https://github.com/microsoft/vscode-remote-release/issues/3814?

**Comment by roblourens** [comment] 2020-11-06 20:31
Seems like something is mangling the install script that we pass through SSH. Does something like `echo "echo hello" | ssh yourhost` work?

**Comment by roblourens** [comment] 2020-11-06 20:33
What is your default shell? Sounds like https://github.com/microsoft/vscode-remote-release/issues/3897

**Closed** 2020-11-06 20:33 UTC
Labels: bug, needs-more-info, ssh
