### ISSUE TITLE
Remote SSH_AUTH_SOCKET not symlinked properly when opening folder

### ISSUE THREAD

**Issue by zerotohero** [microsoft/vscode-remote-release#8073] opened 2023-02-20 18:58 UTC
This seems a little strange. If I connect to my remote server without opening a specific folder, the SSH agent forwarding works properly. However, if I instead have VS Code load one of the open folders, it fails. It's like the `ln` command is never run. Here's the failing log:

```console
[13:51:10.370] Log Level: 1
[13:51:10.377] VS Code version: 1.75.1
[13:51:10.377] Remote-SSH version: remote-ssh@0.96.0
[13:51:10.377] darwin arm64
[13:51:10.380] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22536b756c6c4e7563227d", attempt 1
[13:51:10.380] "remote.SSH.useLocalServer": true
[13:51:10.380] "remote.SSH.path": undefined
[13:51:10.380] "remote.SSH.configFile": undefined
[13:51:10.380] "remote.SSH.useFlock": true
[13:51:10.381] "remote.SSH.lockfilesInTmp": false
[13:51:10.381] "remote.SSH.localServerDownload": auto
[13:51:10.381] "remote.SSH.remoteServerListenOnSocket": false
[13:51:10.381] "remote.SSH.showLoginTerminal": false
[13:51:10.381] "remote.SSH.defaultExtensions": []
[13:51:10.381] "remote.SSH.loglevel": 1
[13:51:10.381] "remote.SSH.enableDynamicForwarding": true
[13:51:10.381] "remote.SSH.enableRemoteCommand": false
[13:51:10.382] "remote.SSH.serverPickPortsFromRange": {}
[13:51:10.382] "remote.SSH.serverInstallPath": {}
[13:51:10.384] SSH Resolver called for host: SkullNuc
[13:51:10.384] Setting up SSH remote "SkullNuc"
[13:51:10.386] Acquiring local install lock: /var/folders/n1/23v_5p4j3lg6r9stv2x8m6g80000gn/T/vscode-remote-ssh-023fd848-install.lock
[13:51:10.387] Looking for existing server data file at /Users/******/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-023fd848-441438abd1ac652551dbe4d408dfcec8a499b8bf-0.96.0/data.json
[13:51:10.387] Found local server running: {"remoteListeningOn":{"port":36773},"osReleaseId":"pop","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-XXXXN0lIbR/agent.176312","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"a11a1a11-1111-1aa1-a1aa-1111a11a1111","pid":12223,"ipcHandlePath":"/var/folders/n1/23v_5p4j3lg6r9stv2x8m6g80000gn/T/vscode-ssh-askpass-67da1d97f7ed64bdb50bdab7430b63f31d27bc36.sock","socksPort":57110,"startupTime":1676918094755}
[13:51:10.392] Found running server - short-circuiting install
[13:51:10.395] Starting forwarding server. localPort 60286 -> socksPort 57110 -> remotePort 36773
[13:51:10.395] Forwarding server listening on 60286
[13:51:10.395] Waiting for ssh tunnel to be ready
[13:51:10.406] Tunneled 36773 to local port 60286
[13:51:10.406] Resolved "ssh-remote+7b22686f73744e616d65223a22536b756c6c4e7563227d" to "127.0.0.1:60286"
[13:51:10.406] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-XXXXN0lIbR/agent.176312" "/run/user/1000/vscode-ssh-auth-sock-978673932"
[13:51:10.407] Using cwd: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a22536b756c6c4e7563227d/
[13:51:10.407] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1000/vscode-ssh-auth-sock-978673932"}
[13:51:10.407] Updating terminal environments: {"SSH_AUTH_SOCK":"/run/user/1000/vscode-ssh-auth-sock-978673932"}
[13:51:10.408] [Forwarding server 60286] Got connection 0
[13:51:10.410] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"pop","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"success"},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":30}}
[13:51:10.412] ------




[13:51:10.487] [Forwarding server 60286] Got connection 1
[13:51:10.541] [Forwarding server 60286] Got connection 2
```

```console
$ env | grep SSH_AU
SSH_AUTH_SOCK=/run/user/1000/vscode-ssh-auth-sock-978673932
```

```console
$ ls -alh /run/user/1000/vscode-ssh-auth-sock-978673932
ls: cannot access '/run/user/1000/vscode-ssh-auth-sock-978673932': No such file or directory
```

And here's the same log for a window where I just had it connect to the remote without loading a specific folder:

```console
[13:43:51.174] Log Level: 1
[13:43:51.180] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22536b756c6c4e7563227d", attempt 1
[13:43:51.180] "remote.SSH.useLocalServer": true
[13:43:51.181] "remote.SSH.path": undefined
[13:43:51.181] "remote.SSH.configFile": undefined
[13:43:51.181] "remote.SSH.useFlock": true
[13:43:51.181] "remote.SSH.lockfilesInTmp": false
[13:43:51.181] "remote.SSH.localServerDownload": auto
[13:43:51.181] "remote.SSH.remoteServerListenOnSocket": false
[13:43:51.181] "remote.SSH.showLoginTerminal": false
[13:43:51.181] "remote.SSH.defaultExtensions": []
[13:43:51.181] "remote.SSH.loglevel": 1
[13:43:51.181] "remote.SSH.enableDynamicForwarding": true
[13:43:51.181] "remote.SSH.enableRemoteCommand": false
[13:43:51.181] "remote.SSH.serverPickPortsFromRange": {}
[13:43:51.181] "remote.SSH.serverInstallPath": {}
[13:43:51.184] VS Code version: 1.75.1
[13:43:51.184] Remote-SSH version: remote-ssh@0.96.0
[13:43:51.184] darwin arm64
[13:43:51.185] SSH Resolver called for host: SkullNuc
[13:43:51.185] Setting up SSH remote "SkullNuc"
[13:43:51.187] Acquiring local install lock: /var/folders/n1/23v_5p4j3lg6r9stv2x8m6g80000gn/T/vscode-remote-ssh-023fd848-install.lock
[13:43:51.187] Looking for existing server data file at /Users/******/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-023fd848-441438abd1ac652551dbe4d408dfcec8a499b8bf-0.96.0/data.json
[13:43:51.188] Found local server running: {"remoteListeningOn":{"port":36773},"osReleaseId":"pop","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-XXXXN0lIbR/agent.176312","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"a11a1a11-1111-1aa1-a1aa-1111a11a1111","pid":12223,"ipcHandlePath":"/var/folders/n1/23v_5p4j3lg6r9stv2x8m6g80000gn/T/vscode-ssh-askpass-67da1d97f7ed64bdb50bdab7430b63f31d27bc36.sock","socksPort":57110,"startupTime":1676918094755}
[13:43:51.192] Found running server - short-circuiting install
[13:43:51.194] Starting forwarding server. localPort 58764 -> socksPort 57110 -> remotePort 36773
[13:43:51.194] Forwarding server listening on 58764
[13:43:51.194] Waiting for ssh tunnel to be ready
[13:43:51.205] Tunneled 36773 to local port 58764
[13:43:51.205] Resolved "ssh-remote+7b22686f73744e616d65223a22536b756c6c4e7563227d" to "127.0.0.1:58764"
[13:43:51.206] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-XXXXN0lIbR/agent.176312" "/run/user/1000/vscode-ssh-auth-sock-920461807"
[13:43:51.206] Using cwd: vscode-remote://ssh-remote%2B7b22686f73744e616d65223a22536b756c6c4e7563227d/
[13:43:51.206] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1000/vscode-ssh-auth-sock-920461807"}
[13:43:51.206] Updating terminal environments: {"SSH_AUTH_SOCK":"/run/user/1000/vscode-ssh-auth-sock-920461807"}
[13:43:51.207] [Forwarding server 58764] Got connection 0
[13:43:51.209] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"pop","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"success"},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":29}}
[13:43:51.211] ------




[13:43:51.226] [Forwarding server 58764] Got connection 1
[13:43:51.380] [Forwarding server 58764] Got connection 2
[13:43:52.471] "Update SSH_AUTH_SOCK" terminal command done
[13:43:55.526] TELEMETRY: {"eventName":"extraInfo","properties":{"remoteCloud":""},"measures":{}}
```

```console
$ env | grep SSH_AU
SSH_AUTH_SOCK=/run/user/1000/vscode-ssh-auth-sock-920461807
```

```console
$ ls -alh /run/user/1000/vscode-ssh-auth-sock-920461807
lrwxrwxrwx 1 ****** ****** 32 Feb 20 13:43 /run/user/1000/vscode-ssh-auth-sock-920461807 -> /tmp/ssh-XXXXN0lIbR/agent.176312
```

What seems to be missing from the non-working one is the line `"Update SSH_AUTH_SOCK" terminal command done`. But I don't see any indication that it failed, or a reason why it wouldn't succeed. If I copy/paste the `ln` command, it works fine. 

I have deleted the remote VS Code server folder and let VS Code reinstall it. I also have another remote running Ubuntu where this doesn't seem to be an issue.

Thanks for any help!

**Comment by maaarghk** [comment] 2023-02-20 21:20
likely a dupe of https://github.com/microsoft/vscode/issues/168202 and https://github.com/microsoft/vscode-remote-release/issues/7995

**Comment by davidkhess** [comment] 2023-02-21 12:49
@chrmarti here’s another one on the remote extension side of things we could really use some help with.

**Comment by zerotohero** [comment] 2023-02-27 22:12
@eleanorjboyd This isn't the first time I've used the remote SSH extension this way. And in this case it seems to work properly unless I specify that VS Code open a folder. The issue you linked to looks like it has to do with a stale environment variable, but in this case the environment variable is set to a new value. The issue is that the symlink isn't actually created. 

They seem like slightly different issues to me?

**Comment by eleanorjboyd** [comment] 2023-02-27 23:33
Can you specify what you mean by: ` if I instead have VS Code load one of the open folders`. Also what command are you talking about here `It's like the ln command is never run.`?

**Comment by maaarghk** [comment] 2023-02-28 13:01
@eleanorjboyd There are more details here -> https://github.com/microsoft/vscode-remote-release/issues/7995#issuecomment-1422753238 albeit the comment was seemingly left on the wrong issue

**Comment by zerotohero** [comment] 2023-02-28 18:23
@eleanorjboyd 
> if I instead have VS Code load one of the open folders

When VS Code lists remotes, I can either have it open a new window for the remote host OR a new window with a previously opened folder (so that the Explorer tab lists files/folders, source control loads git info, etc). So in this case, the issue only occurs if I open a new window with a folder. 

> It's like the ln command is never run

In the failing log, you'll see the line:
```console
[13:51:10.406] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-XXXXN0lIbR/agent.176312" "/run/user/1000/vscode-ssh-auth-sock-978673932"
```
However, there is never confirmation that this command, `ln -f -s "/tmp/ssh-XXXXN0lIbR/agent.176312" "/run/user/1000/vscode-ssh-auth-sock-978673932"`, ran successfully (which is confirmed in the working log). If I run this command manually by copy/pasting it into a terminal window, then SSH Agent Forwarding works as expected.

**Comment by tm1000** [comment] 2023-02-28 19:26
This was a regression for me and my coworker. Same problem as @zerotohero stated:

> However, there is never confirmation that this command, ln -f -s "/tmp/ssh-XXXXN0lIbR/agent.176312" "/run/user/1000/vscode-ssh-auth-sock-978673932", ran successfully (which is confirmed in the working log). If I run this command manually by copy/pasting it into a terminal window, then SSH Agent Forwarding works as expected.

**Comment by eleanorjboyd** [comment] 2023-02-28 21:17
Will investigate further- could someone confirm the version they are on where they are seeing the regression? Also if you go back a version does it fix the issue?

**Comment by tm1000** [comment] 2023-02-28 21:25
@eleanorjboyd I'm on v0.96.0 of https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

When I rollback I still have the issue even if I go back an entire year

The logs look the same:
```
[13:21:35.756] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-XXXXtaIs9P/agent.3227838" "/run/user/0/vscode-ssh-auth-sock-876161544"
[13:21:35.756] Using cwd: vscode-remote://ssh-remote%2B192.168.68.21/
[13:21:35.756] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/0/vscode-ssh-auth-sock-876161544"}
```

But the link is old (and so is SSH_AUTH_SOCK sometimes):
```
root@development:/usr/src/telephony# echo $SSH_AUTH_SOCK
/run/user/0/vscode-ssh-auth-sock-780936740
root@development:/usr/src/telephony# ls -l /run/user/0/vscode-ssh-auth-sock-780936740
lrwxrwxrwx 1 root root 33 Feb 28 17:43 /run/user/0/vscode-ssh-auth-sock-780936740 -> /tmp/ssh-XXXXTrQEha/agent.3091935
```

**Comment by zerotohero** [comment] 2023-02-28 21:58
I'm also on v0.96.0. Selecting an older version of the extension doesn't seem to change the behavior here.

**Comment by zerotohero** [comment] 2023-03-01 21:38
Just realized something else... It might not be whether or not a "folder" is opened. It actually seems to be based on whether or not it's trying to load a file when it connects. 

1. Clone a new repo
2. `code <folder-name>`
3. SSH agent forwarding works, I see the line `"Update SSH_AUTH_SOCK" terminal command done`
4. Click a file from Explorer tab to load its contents. 
5. Close the VS Code window. 
6. In the originally opened window, `code <folder-name>`
7. New loads the contents of the text file again, agent forwarding fails, missing `terminal command done` output. 
8. Close the tab where the file contents is showing, so no tabs are open
9. Close VS Code window
10. 6. In the originally opened window, `code <folder-name>`
11. SSH agent forwarding works, I see the line `"Update SSH_AUTH_SOCK" terminal command done`

Just tried this with several folders (closing all tabs) and was able to repeat this behavior. @tm1000 do you see the same thing?

@tm1000 do you see the same behavior?

**Comment by tm1000** [comment] 2023-03-02 06:49
It only worked for me once, but when it did work I did see `"Update SSH_AUTH_SOCK" terminal command done`. When it fails I dont see that at all

**Comment by davidkhess** [comment] 2023-03-02 17:40
Confirming what @zerotohero is reporting. When I have an indication that the agent hasn't been forwarded (i.e. git push fails), I:

1. close all tabs
2. Perform `Developer: Reload Window`
3. git push now works (i.e. agent was properly forwarded after the reload)

**Comment by tm1000** [comment] 2023-03-07 22:39
It looks like setting `"remote.SSH.useLocalServer": false` fixes this for me (you can only set this in the user config file)

**Comment by alpsayin** [comment] 2023-03-11 15:00
> It looks like setting `"remote.SSH.useLocalServer": false` fixes this for me (you can only set this in the user config file)
> 
> Ref: [microsoft/vscode#168202 (comment)](https://github.com/microsoft/vscode/issues/168202#issuecomment-1453076451)

I don't know why but this also worked for me. After restarting both vscode (not just reload) and vscode-server that is.

**Comment by zerotohero** [comment] 2023-03-13 19:57
Setting `"remote.SSH.useLocalServer": false` seems to work for me as well. Not sure if there are any other side effects but it's opening with some tabs so it's a win so far...

**Comment by tm1000** [comment] 2023-03-13 23:12
@zerotohero apparently it can end up using more resources on your remote with multiple vscode sessions

I've only run into the out of memory killer once however since changing that. I usually have about two to four different workspaces open to the same host

**Comment by eleanorjboyd** [comment] 2023-03-14 18:48
I think it would be best to move this discussion to this thread: https://github.com/microsoft/vscode/issues/168202 since that is the original issue. This will allow us to involve all stakeholders in the discussion. Please reopen if there are things that need to be included in this thread that do not fit in the other. Thanks

**Closed by eleanorjboyd** 2023-03-14 18:48 UTC
Labels: ssh
