### ISSUE TITLE
Support portAttributes as a top level attribute in devContainer.json

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4432] opened 2021-02-07 16:44 UTC
It is currently possible to define additional attributes for ports in the setting `remote.portAttributes` for discoverability we should support to define port attributes in a top level attribute `portAttributes` in `devContainer.json`

**Comment by alexr00** [comment] 2021-02-26 09:22
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4445

**Closed by alexr00** 2021-02-26 09:22 UTC
Labels: remote
