### ISSUE TITLE
Remote targets sort/filter

### ISSUE THREAD

**Issue by zhj0924** [microsoft/vscode-remote-release#4784] opened 2021-03-30 01:58 UTC
Issue Type: <b>Feature Request</b>

I need to arrange and sort my wsl targets folders/workspaces. I need to be able to drag them around

Extension version: 0.54.6
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.21343
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by aeschli** [comment] 2021-04-08 07:09
Not sure what you mean by 'wsl targets folders/workspaces'

Can you explain more? Can you add a screenshot of where you want drag and drop?

**Comment by zhj0924** [comment] 2021-04-08 12:05
files and folders in the remote explorer
![image](https://user-images.githubusercontent.com/35902491/114023581-ea7ae080-9827-11eb-8bc1-11aad7c2e55b.png)
![image](https://user-images.githubusercontent.com/35902491/114023633-f9619300-9827-11eb-8e4b-48e8643e9377.png)

**Comment by alexr00** [comment] 2021-04-08 13:00
Duplicate of https://github.com/microsoft/vscode/issues/32592

**Closed by alexr00** 2021-04-08 13:00 UTC
