### ISSUE TITLE
Installation fails due to missing release version

### ISSUE THREAD

**Issue by runbikeswim** [microsoft/vscode-remote-release#7329] opened 2022-10-11 18:24 UTC
- VSCode Version: 1.72.1
- Local OS Version: Windows 11 (Windows_NT x64 10.0.22621)
- Remote OS Version: - 
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:

Steps to Reproduce:

1. Open EXTENSION: MARKETPLACE
2. Select "Install" of "Remote Explorer"
3. Pop-Up appears showing error (see attached screen shot)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

![Screenshot 2022-10-11 202405](https://user-images.githubusercontent.com/25247189/195170148-b0f7c9b6-a254-45a6-a858-9b14c9add660.png)

**Comment by philipdowner** [comment] 2022-10-11 18:36
Duplicate of #7330.

**Comment by chrmarti** [comment] 2022-10-12 06:19
Closing as duplicate. Should be fixed in the latest version.

**Closed by chrmarti** 2022-10-12 06:19 UTC
