### ISSUE TITLE
Dev Container within WSL2

### ISSUE THREAD

**Issue by shayne** [microsoft/vscode-remote-release#2535] opened 2020-03-12 18:00 UTC
There are a few issues about connecting to containers running under WSL2, for which there are known workarounds. Currently my workflow involves a script to start a pseudo-dev-container. Then manually attach to the container (running under WSL2) using the Docker VSCode extension.

This task is for the specific feature request to add Dev Container support to workspaces under WSL2.

With the recent Docker Desktop edge release Docker powered by WSL2 is incredibly easy to get up and running. Even traditional Dev Containers, where the files are under the Windows filesystem work seamlessly. This is great. However, the IO performance when working from the Windows filesystem is far less performant than if working from within the WSL2 filesystem.

For this reason I use the aforementioned workflow. It would be great, however, if VSCode would prompt to relaunch in a Dev Container (as it does now), but when opening a folder/workspace under WSL2.

This would allow WSL2 users to simply clone a repository from their WSL2 terminal, type `$ code` and VSCode would open with the dialog in the bottom right offering to reopen the project in the configured Dev Container.

**Comment by chrmarti** [comment] 2020-10-13 12:50
Should work out-of-the-box now.

Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2498.

**Closed by chrmarti** 2020-10-13 12:50 UTC
