### ISSUE TITLE
Does not see duplicated folder names distinct by case

### ISSUE THREAD

**Issue by cmeans** [microsoft/vscode-remote-release#770] opened 2019-06-21 21:23 UTC
Issue Type: <b>Bug</b>

If there are two folders with the same name, e.g. "gb" and "GB", only "gb" will be seen/shown.  "GB" becomes visible when folder "gb" is removed.

Extension version: 0.42.2
VS Code version: Code - Insiders 1.36.0-insider (9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21, 2019-06-21T05:18:36.348Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.4.0-131-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 4|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vagrant_vm|
|OS|Linux x64 4.4.0-131-generic|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (4 x 2592)|
|Memory (System)|4.84GB (2.63GB free)|
|VM|100%|
</details>

**Comment by egamma** [comment] 2019-06-22 05:35
duplicate of microsoft/vscode#12448

**Closed by egamma** 2019-06-22 05:35 UTC
