### ISSUE TITLE
Support installing DevContainers extension on remote tunnels

### ISSUE THREAD

**Issue by jon77p** [microsoft/vscode-remote-release#7715] opened 2022-12-14 21:08 UTC
Nice job launching remote tunnels! I’ve been working through using remote tunnels as a self-hosted alternative to codespaces (since I already have personal images/features that are compliant with the devcontainers spec), but it looks like it is not possible to install the Dev Containers extension as this is blocked from being installed in VS Code in the Web.

Weirdly, there is no option to install this extension onto the local host running the remote tunnel (other extensions have this fine), and it looks like that capability is blocked for the Dev Containers extension.

**Comment by Chuxel** [comment] 2022-12-14 23:36
Yep, not implemented yet but totally makes sense! Closing as a dupe of #7705 if you want to upvote that.

**Closed by Chuxel** 2022-12-14 23:36 UTC
Labels: containers
